### ISSUE TITLE
Convention on minor variable changes

### ISSUE THREAD

**Issue by kirby1hero** [keiyoushi/tachiyomi-extensions-source#1]
### Describe why this should be added

In my implementation of the Bato.To fix, I have a minor change to the extension that changes the name of two variables.
In this case, it's changing "imgHttpsLis" to "imgHttps", and "imgHttpsLisString" to "imgHttpsString".
This is minor, but when the source changes its tag's name, the variable describing that name should also be changed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
Feel free to make a PR :)
