### ISSUE TITLE
restore commit history

### ISSUE THREAD

**Issue by shadow578** [keiyoushi/tachiyomi-extensions-source#10]
### Describe why this should be added

i've recovered the commit history of the original repo at [shadow578/tachiyomi-extensions](https://github.com/shadow578/tachiyomi-extensions/issues/1). Maybe it's worth looking into restoring the commit history of this repo?

**Comment by FourTOne5** [comment]
Hi I already have the history but I didn't use it as it's too big, I'll probably push that to another repo for archival reasons but not in this one.

**Comment by shadow578** [comment]
i went ahead and created my own repo with the full commit history at https://github.com/tachiyomi-extensions-org/tachiyomi-extensions.

if you'd like, i could add you as a maintainer
