### ISSUE TITLE
When login to boylove ACC manga cannot be read

### ISSUE THREAD

**Issue by HYChin** [keiyoushi/tachiyomi-extensions-source#1005]
### Source information

Boylove / 香香腐宅1.4.10

### Source language

Chinese

### Steps to reproduce

1. Open extension in Webview
2. Login to my account
3. Go back to library all manga from boylove cannot be read 

### Expected behavior

Manga should be readed even I login to my ACC 
![Screenshot_2024-02-05-12-12-47-900_eu kanade tachiyomi](https://github.com/keiyoushi/extensions-source/assets/125426885/506571ac-c77e-428e-8fca-61b5add5f1ed)
![IMG_20240205_123454](https://github.com/keiyoushi/extensions-source/assets/125426885/56f5b392-2dca-45f6-a2bf-d72b20551078)

### Actual behavior

The login page have error now. Once I login ACC, the error will show. I have tried the troubleshooting guide still cannot solve. 

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 14

### Other details

When not login to the acc, it is normal. After Login, all manga cannot be read. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by HYChin** [comment]
Hi, may I know why this issue keep being closed ?

**Comment by beer-psi** [comment]
The bot already told you what you need to do.

**Comment by HYChin** [comment]
Now the issue this, why keep saying me not read the acknowledgements? Before is normal, this issue is happen just now.

**Comment by HYChin** [comment]
Just now I alr open 1 issue but keep closed mine. I want to which I didn't follow the acknowledgement?

**Comment by HYChin** [comment]
> The bot already told you what you need to do.

The bot told me troubleshoot? I have mention in the post there, i have try. But still not success. Pls check the SQL STATE hy000
