### ISSUE TITLE
Doujindesu url change

### ISSUE THREAD

**Issue by WEPOXS** [keiyoushi/tachiyomi-extensions-source#1020]
### Source information

1.4.6

### Source language

Indonesia

### Source new URL

https://www.doujindesu.to/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by devil6venom** [comment]
Sorry to say this, but can't you just override the new url if there is no theme change or major changes on sites?? There is already baseurl override option!!!! Use that!

**Comment by beer-psi** [comment]
> Sorry to say this, but can't you just override the new url if there is no theme change or major changes on sites?? There is already baseurl override option!!!! Use that!

That is an option for some sources that change their URL frequently. I'm not aware if DoujinDesu has it, but it's intended as a temporary solution and not something to depend on permanently.

**Comment by devil6venom** [comment]
> > Sorry to say this, but can't you just override the new url if there is no theme change or major changes on sites?? There is already baseurl override option!!!! Use that!
> 
> That is an option for some sources that change their URL frequently. I'm not aware if DoujinDesu has it, but it's intended as a temporary solution and not something to depend on permanently.

Well even the original one is working fine. I just installed the ext and checked.. its working fine ..and all things are normal! Even the override is working properly!! Kindly check once againand removed the Domain changed and bug label from it!!

**Comment by WEPOXS** [comment]
> Sorry to say this, but can't you just override the new url if there is no theme change or major changes on sites?? There is already baseurl override option!!!! Use that!

yeah I know, but the default URL is still the same, so if there are people who still don't know about that feature, it will be a problem for them, especially if they don't join discord or other discussions

**Comment by WEPOXS** [comment]
> > > Sorry to say this, but can't you just override the new url if there is no theme change or major changes on sites?? There is already baseurl override option!!!! Use that!
> > 
> > That is an option for some sources that change their URL frequently. I'm not aware if DoujinDesu has it, but it's intended as a temporary solution and not something to depend on permanently.
> 
> Well even the original one is working fine. I just installed the ext and checked.. its working fine ..and all things are normal! Even the override is working properly!! Kindly check once againand removed the Domain changed and bug label from it!!

![Screenshot_20240207_024647_Mihon.jpg](https://github.com/keiyoushi/extensions-source/assets/146017577/cc201407-e457-4c3a-9886-b9555b432dad)
Well, I just checked and it turns out doujindesu.tv is still active but on the extension the connection resets and I've used VPN, it's still the same

**Comment by devil6venom** [comment]
> > > > Sorry to say this, but can't you just override the new url if there is no theme change or major changes on sites?? There is already baseurl override option!!!! Use that!
> > > 
> > > 
> > > That is an option for some sources that change their URL frequently. I'm not aware if DoujinDesu has it, but it's intended as a temporary solution and not something to depend on permanently.
> > 
> > 
> > Well even the original one is working fine. I just installed the ext and checked.. its working fine ..and all things are normal! Even the override is working properly!! Kindly check once againand removed the Domain changed and bug label from it!!
> 
> ![Screenshot_20240207_024647_Mihon.jpg](https://private-user-images.githubusercontent.com/146017577/302757600-cc201407-e457-4c3a-9886-b9555b432dad.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNzI3MDMsIm5iZiI6MTcwNzI3MjQwMywicGF0aCI6Ii8xNDYwMTc1NzcvMzAyNzU3NjAwLWNjMjAxNDA3LWU0NTctNGMzYS05ODg2LWI5NTU1YjQzMmRhZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwMjIwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGIxZDJlNDViOGM2M2I4M2E3YmIzMTVmNWQwYWUyN2M0ODI2MmJhMjFiMjYwNjE3MTg5MGE3NjE5NjBhODMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gdtc4BwezJDyTU2iqNVdQrP2YmNo5iXBTu1TnFy5lf4) Well, I just checked and it turns out doujindesu.tv is still active but on the extension the connection resets and I've used VPN, it's still the same

Well, in my case, its working perfectly fine!!!

**Comment by WEPOXS** [comment]
> > > > > Sorry to say this, but can't you just override the new url if there is no theme change or major changes on sites?? There is already baseurl override option!!!! Use that!
> > > > 
> > > > 
> > > > That is an option for some sources that change their URL frequently. I'm not aware if DoujinDesu has it, but it's intended as a temporary solution and not something to depend on permanently.
> > > 
> > > 
> > > Well even the original one is working fine. I just installed the ext and checked.. its working fine ..and all things are normal! Even the override is working properly!! Kindly check once againand removed the Domain changed and bug label from it!!
> > 
> > ![Screenshot_20240207_024647_Mihon.jpg](https://private-user-images.githubusercontent.com/146017577/302757600-cc201407-e457-4c3a-9886-b9555b432dad.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNzI3MDMsIm5iZiI6MTcwNzI3MjQwMywicGF0aCI6Ii8xNDYwMTc1NzcvMzAyNzU3NjAwLWNjMjAxNDA3LWU0NTctNGMzYS05ODg2LWI5NTU1YjQzMmRhZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwMjIwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGIxZDJlNDViOGM2M2I4M2E3YmIzMTVmNWQwYWUyN2M0ODI2MmJhMjFiMjYwNjE3MTg5MGE3NjE5NjBhODMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gdtc4BwezJDyTU2iqNVdQrP2YmNo5iXBTu1TnFy5lf4) Well, I just checked and it turns out doujindesu.tv is still active but on the extension the connection resets and I've used VPN, it's still the same
> 
> Well, in my case, its working perfectly fine!!!

I've uninstalled and reinstalled it's still the same, maybe it's just me, so I'll use the override option
![Screenshot_20240207_155601_Mihon.jpg](https://github.com/keiyoushi/extensions-source/assets/146017577/f748c982-ce86-4602-9fd7-25cbec735f25)

![Screenshot_20240207_155702_Tachiyomi.jpg](https://github.com/keiyoushi/extensions-source/assets/146017577/5cf9974f-98df-4193-b18a-46be66ab1342)

**Comment by devil6venom** [comment]
> > > > > > Sorry to say this, but can't you just override the new url if there is no theme change or major changes on sites?? There is already baseurl override option!!!! Use that!
> > > > > 
> > > > > 
> > > > > That is an option for some sources that change their URL frequently. I'm not aware if DoujinDesu has it, but it's intended as a temporary solution and not something to depend on permanently.
> > > > 
> > > > 
> > > > Well even the original one is working fine. I just installed the ext and checked.. its working fine ..and all things are normal! Even the override is working properly!! Kindly check once againand removed the Domain changed and bug label from it!!
> > > 
> > > 
> > > ![Screenshot_20240207_024647_Mihon.jpg](https://private-user-images.githubusercontent.com/146017577/302757600-cc201407-e457-4c3a-9886-b9555b432dad.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNzI3MDMsIm5iZiI6MTcwNzI3MjQwMywicGF0aCI6Ii8xNDYwMTc1NzcvMzAyNzU3NjAwLWNjMjAxNDA3LWU0NTctNGMzYS05ODg2LWI5NTU1YjQzMmRhZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwMjIwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGIxZDJlNDViOGM2M2I4M2E3YmIzMTVmNWQwYWUyN2M0ODI2MmJhMjFiMjYwNjE3MTg5MGE3NjE5NjBhODMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gdtc4BwezJDyTU2iqNVdQrP2YmNo5iXBTu1TnFy5lf4) Well, I just checked and it turns out doujindesu.tv is still active but on the extension the connection resets and I've used VPN, it's still the same
> > 
> > 
> > Well, in my case, its working perfectly fine!!!
> 
> I've uninstalled and reinstalled it's still the same, maybe it's just me, so I'll use the override option ![Screenshot_20240207_155601_Mihon.jpg](https://private-user-images.githubusercontent.com/146017577/302918157-f748c982-ce86-4602-9fd7-25cbec735f25.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTc4ODMsIm5iZiI6MTcwNzI5NzU4MywicGF0aCI6Ii8xNDYwMTc1NzcvMzAyOTE4MTU3LWY3NDhjOTgyLWNlODYtNDYwMi05ZmQ3LTI1Y2JlYzczNWYyNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwOTE5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDhiY2RkODAzZTcyMWI3MTk4NjAxYWJlNDA0NjUxZjdiMTY4MzRlMTc4M2I0MGQ3YWU0MmIyNjgxZGYyZGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sHhHEPlbPsS4VZzzYVObnIViOf6Uj6OaY7X82ZYZv_M)
> 
> ![Screenshot_20240207_155702_Tachiyomi.jpg](https://private-user-images.githubusercontent.com/146017577/302918371-5cf9974f-98df-4193-b18a-46be66ab1342.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTc4ODMsIm5iZiI6MTcwNzI5NzU4MywicGF0aCI6Ii8xNDYwMTc1NzcvMzAyOTE4MzcxLTVjZjk5NzRmLTk4ZGYtNDE5My1iMThhLTQ2YmU2NmFiMTM0Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwOTE5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmU5MGFiYWYxYmM2MjNlNDZjNTgyOWMxNjdhMzgxZWM3YjQ3MzU4MDY3MjU4Mzk3MDkzZmZjZTk0NjA5YzQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZLfzJGzhQzcaHCQxmN3fmNq9Ck2eHm3TGRl9RChZkzw)

Try changing dns and restart..if not use any vpn and check..

**Comment by SupKelelawar** [comment]
i think that different site

**Comment by WEPOXS** [comment]
> > > > > > > Sorry to say this, but can't you just override the new url if there is no theme change or major changes on sites?? There is already baseurl override option!!!! Use that!
> > > > > > 
> > > > > > 
> > > > > > That is an option for some sources that change their URL frequently. I'm not aware if DoujinDesu has it, but it's intended as a temporary solution and not something to depend on permanently.
> > > > > 
> > > > > 
> > > > > Well even the original one is working fine. I just installed the ext and checked.. its working fine ..and all things are normal! Even the override is working properly!! Kindly check once againand removed the Domain changed and bug label from it!!
> > > > 
> > > > 
> > > > ![Screenshot_20240207_024647_Mihon.jpg](https://private-user-images.githubusercontent.com/146017577/302757600-cc201407-e457-4c3a-9886-b9555b432dad.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNzI3MDMsIm5iZiI6MTcwNzI3MjQwMywicGF0aCI6Ii8xNDYwMTc1NzcvMzAyNzU3NjAwLWNjMjAxNDA3LWU0NTctNGMzYS05ODg2LWI5NTU1YjQzMmRhZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwMjIwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGIxZDJlNDViOGM2M2I4M2E3YmIzMTVmNWQwYWUyN2M0ODI2MmJhMjFiMjYwNjE3MTg5MGE3NjE5NjBhODMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gdtc4BwezJDyTU2iqNVdQrP2YmNo5iXBTu1TnFy5lf4) Well, I just checked and it turns out doujindesu.tv is still active but on the extension the connection resets and I've used VPN, it's still the same
> > > 
> > > 
> > > Well, in my case, its working perfectly fine!!!
> > 
> > I've uninstalled and reinstalled it's still the same, maybe it's just me, so I'll use the override option ![Screenshot_20240207_155601_Mihon.jpg](https://private-user-images.githubusercontent.com/146017577/302918157-f748c982-ce86-4602-9fd7-25cbec735f25.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTc4ODMsIm5iZiI6MTcwNzI5NzU4MywicGF0aCI6Ii8xNDYwMTc1NzcvMzAyOTE4MTU3LWY3NDhjOTgyLWNlODYtNDYwMi05ZmQ3LTI1Y2JlYzczNWYyNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwOTE5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDhiY2RkODAzZTcyMWI3MTk4NjAxYWJlNDA0NjUxZjdiMTY4MzRlMTc4M2I0MGQ3YWU0MmIyNjgxZGYyZGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sHhHEPlbPsS4VZzzYVObnIViOf6Uj6OaY7X82ZYZv_M)
> > 
> > ![Screenshot_20240207_155702_Tachiyomi.jpg](https://private-user-images.githubusercontent.com/146017577/302918371-5cf9974f-98df-4193-b18a-46be66ab1342.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTc4ODMsIm5iZiI6MTcwNzI5NzU4MywicGF0aCI6Ii8xNDYwMTc1NzcvMzAyOTE4MzcxLTVjZjk5NzRmLTk4ZGYtNDE5My1iMThhLTQ2YmU2NmFiMTM0Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwOTE5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmU5MGFiYWYxYmM2MjNlNDZjNTgyOWMxNjdhMzgxZWM3YjQ3MzU4MDY3MjU4Mzk3MDkzZmZjZTk0NjA5YzQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZLfzJGzhQzcaHCQxmN3fmNq9Ck2eHm3TGRl9RChZkzw)
> 
> Try changing dns and restart..if not use any vpn and check..
![Screenshot_20240207_195118_Tachiyomi.jpg](https://github.com/keiyoushi/extensions-source/assets/146017577/a004ed3e-61d2-4601-9bed-f77d834b75c3)

![Screenshot_20240207_195201_Mihon.jpg](https://github.com/keiyoushi/extensions-source/assets/146017577/10ad7c6f-62b8-47dd-bf43-fb55827fabcd)

![Screenshot_20240207_195238_Mihon.jpg](https://github.com/keiyoushi/extensions-source/assets/146017577/905d31c7-1dcf-4f7b-8ee6-532c85e257ee)

![Screenshot_20240207_195218_Settings.jpg](https://github.com/keiyoushi/extensions-source/assets/146017577/acd2942f-8ced-4ce9-b335-f8a893a193e7)

![Screenshot_20240207_195141_Tachiyomi.jpg](https://github.com/keiyoushi/extensions-source/assets/146017577/7509c307-22ec-42ca-a3da-024304961abd)

![Screenshot_20240207_195133_Tachiyomi.jpg](https://github.com/keiyoushi/extensions-source/assets/146017577/415a5ba0-fcc2-4d98-8221-7290c28960ac)

![Screenshot_20240207_195243_Mihon.jpg](https://github.com/keiyoushi/extensions-source/assets/146017577/c4a5a488-597c-487d-b413-4f145466aeb3)



I tried 2 apps, Mihon and Tachiyomi, both of which were the same as this

**Comment by WEPOXS** [comment]
> > > > > > > Sorry to say this, but can't you just override the new url if there is no theme change or major changes on sites?? There is already baseurl override option!!!! Use that!
> > > > > > 
> > > > > > 
> > > > > > That is an option for some sources that change their URL frequently. I'm not aware if DoujinDesu has it, but it's intended as a temporary solution and not something to depend on permanently.
> > > > > 
> > > > > 
> > > > > Well even the original one is working fine. I just installed the ext and checked.. its working fine ..and all things are normal! Even the override is working properly!! Kindly check once againand removed the Domain changed and bug label from it!!
> > > > 
> > > > 
> > > > ![Screenshot_20240207_024647_Mihon.jpg](https://private-user-images.githubusercontent.com/146017577/302757600-cc201407-e457-4c3a-9886-b9555b432dad.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNzI3MDMsIm5iZiI6MTcwNzI3MjQwMywicGF0aCI6Ii8xNDYwMTc1NzcvMzAyNzU3NjAwLWNjMjAxNDA3LWU0NTctNGMzYS05ODg2LWI5NTU1YjQzMmRhZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwMjIwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGIxZDJlNDViOGM2M2I4M2E3YmIzMTVmNWQwYWUyN2M0ODI2MmJhMjFiMjYwNjE3MTg5MGE3NjE5NjBhODMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gdtc4BwezJDyTU2iqNVdQrP2YmNo5iXBTu1TnFy5lf4) Well, I just checked and it turns out doujindesu.tv is still active but on the extension the connection resets and I've used VPN, it's still the same
> > > 
> > > 
> > > Well, in my case, its working perfectly fine!!!
> > 
> > I've uninstalled and reinstalled it's still the same, maybe it's just me, so I'll use the override option ![Screenshot_20240207_155601_Mihon.jpg](https://private-user-images.githubusercontent.com/146017577/302918157-f748c982-ce86-4602-9fd7-25cbec735f25.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTc4ODMsIm5iZiI6MTcwNzI5NzU4MywicGF0aCI6Ii8xNDYwMTc1NzcvMzAyOTE4MTU3LWY3NDhjOTgyLWNlODYtNDYwMi05ZmQ3LTI1Y2JlYzczNWYyNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwOTE5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDhiY2RkODAzZTcyMWI3MTk4NjAxYWJlNDA0NjUxZjdiMTY4MzRlMTc4M2I0MGQ3YWU0MmIyNjgxZGYyZGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sHhHEPlbPsS4VZzzYVObnIViOf6Uj6OaY7X82ZYZv_M)
> > 
> > ![Screenshot_20240207_155702_Tachiyomi.jpg](https://private-user-images.githubusercontent.com/146017577/302918371-5cf9974f-98df-4193-b18a-46be66ab1342.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTc4ODMsIm5iZiI6MTcwNzI5NzU4MywicGF0aCI6Ii8xNDYwMTc1NzcvMzAyOTE4MzcxLTVjZjk5NzRmLTk4ZGYtNDE5My1iMThhLTQ2YmU2NmFiMTM0Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwOTE5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmU5MGFiYWYxYmM2MjNlNDZjNTgyOWMxNjdhMzgxZWM3YjQ3MzU4MDY3MjU4Mzk3MDkzZmZjZTk0NjA5YzQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZLfzJGzhQzcaHCQxmN3fmNq9Ck2eHm3TGRl9RChZkzw)
> 
> Try changing dns and restart..if not use any vpn and check..

Yow bro, I can already access the extension with the default URL so you can close this issue
