### ISSUE TITLE
LectorManga - Bug in "Show all scanlator" option

### ISSUE THREAD

**Issue by orcb0lg** [keiyoushi/tachiyomi-extensions-source#1028]
### Source information

LectorManga 1.4.35

### Source language

Spanish

### Steps to reproduce

1. Show all scanlator option its disabled in source config.
2. Refresh a manga
3. Chapters are repeated with different scanlators

### Expected behavior

The expected behavior its show only one chapter uploaded by one scanlator

### Actual behavior

After refreshing a manga, the chapters are repeated even if the option "show all scanlator" its disabled in source/extension config

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 14

### Other details

This issue start happening after the update of the source/extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Can you provide any manga where it happens?

**Comment by MrDfour** [comment]
> Can you provide any manga where it happens?

Came to repot this same thing so I thought it would be good to help. It scared me to see suddenly a thousand new chapters lol

![Screenshot_20240205-185536_TachiyomiSY](https://github.com/keiyoushi/extensions-source/assets/103494853/27c3115e-36f7-401a-a184-da46ee80c4a0)

**Comment by orcb0lg** [comment]
Sorry for the late response, I was busy during the day and forget to check the issue but at least someone has the same problem and provide the evidence. I recently installed the extension update, so far everything is going well. Thanks for your work. (i apologize for my broken english, is not my main language)
