### ISSUE TITLE
CreepyScans search is broken

### ISSUE THREAD

**Issue by morethanhater** [keiyoushi/tachiyomi-extensions-source#1034]
### Source information

CreepyScans 1.4.33

### Source language

English

### Steps to reproduce

1. Select source at source list page
2. Try to search for anything

### Expected behavior

You're seeing search results

### Actual behavior

You're seeing an error "search is not available"

### Mihon/Tachiyomi version

J2K 1.7.4

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by SnakeDoc83** [comment]
Seems like an issue with their website.

**Comment by morethanhater** [comment]
> Seems like an issue with their website.

Search preview box still works though

**Comment by SnakeDoc83** [comment]
Mmm, only the "predictive" search, could do something with that. Do you know if their search was working regularly before or if filtered search worked?

**Comment by morethanhater** [comment]
> Do you know if their search was working regularly before or if filtered search worked?

Sorry, can't confirm anything here.

**Comment by SnakeDoc83** [comment]
No problem, thought I'd ask.

**Comment by Secozzi** [comment]
The site has only had the "predictive" search.
