### ISSUE TITLE
TuMangaOnline not loading chapters

### ISSUE THREAD

**Issue by TheeoCornnaro** [keiyoushi/tachiyomi-extensions-source#1045]
### Source information

TuMangaOnline 1.4.50

### Source language

Spanish

### Steps to reproduce

1. select some of the new mangas or nsfw content
2. chapter list works well but chapter does not load
in vwebview page redirects you to google. 
it is not getting the good address after selected.
https://visortmo.com/library/manhwa/78067/cazador-de-milfs-de-otro-mundo does not work
https://visortmo.com/library/manhwa/217/solo-leveling does work well.
there are differences on the network tracing

### Expected behavior

Images should load at least in webview but apparently it is not capturing the good link

### Actual behavior

images do not load after a long loop

### Mihon/Tachiyomi version

0.16.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Check and update your extension to the latest version before making reports please. The latest version is 1.4.51. And it works fine on my end

**Comment by TheeoCornnaro** [comment]
i did try on 1.4.51. still not working.

in webview the error is.

The webpage at https://animationdraw.com/ could not be loaded because:

net::ERR_CACHE_MISS

**Comment by bapeey** [comment]
Ignoring the WebView issue, what is the error message when trying to open the chapter?

**Comment by ButeryMetal** [comment]
I had that same problem, I just changed the User Agent in the Mihon settings and it worked for me

**Comment by TheeoCornnaro** [comment]
it was doing a full loop to load and nothing
I tried other user agents.
I changed TachiyomiSy for mihon and seems to work now

thanks for the help
