### ISSUE TITLE
MangaLike : Source request

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#1054]
### Source name

MangaLike

### Source link

https://manga-like.org/

### Source language

Arabic

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by devil6venom** [comment]
Madara theme!!

**Comment by beer-psi** [comment]
Isn't this a Mangalek mirror?

**Comment by MikeZeDev** [comment]
Its a real mess to know which one of those mangalek / like is a clone , a mirror, or an original, good luck 🤟 

references :

https://github.com/manga-download/hakuneko/issues/6546
https://github.com/manga-download/hakuneko/issues/6495
https://github.com/manga-download/hakuneko/issues/6680

**Comment by mohamedotaku** [comment]
manga-lek.net
manga-lek.org
manga-lek.com
manga-like.net
manga-like.org
manga-link.com
manga-link.org
manga-link.net

They are the same thing, and if the original site falls, they all fall, just like what happened with the old links.
My opinion is to put all this links in one extension.
