### ISSUE TITLE
Source Request: Major Scans (Old Robin Manga)

### ISSUE THREAD

**Issue by RenasBayraktar** [keiyoushi/tachiyomi-extensions-source#1056]
### Source name

Major Scans

### Source link

https://www.majorscans.com

### Source language

Turkish

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Mangathemesia theme

**Comment by Norsze** [comment]
The site is now English?

Seems it turned into a very basic aggregator site

**Comment by RenasBayraktar** [comment]
They changed the domain to majorscans.com

**Comment by RenasBayraktar** [comment]
Edited the post acccordingly.

**Comment by AwkwardPeak7** [comment]
Major scans exist
