### ISSUE TITLE
Hunters scan erro 404

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#1060]
### Source information

Hunters Scans 1.4.33

### Source language

Português Brasil

### Steps to reproduce

![Screenshot_20240206-155914](https://github.com/keiyoushi/extensions-source/assets/157044539/32529700-1c85-4993-8169-db2272e6e9f0)

### Expected behavior

.

### Actual behavior

.

### Mihon/Tachiyomi version

Mihon 0.16.3

### Android version

Android 11

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Duplicate of #929
