### ISSUE TITLE
Please add Immortal Updates back to extension list

### ISSUE THREAD

**Issue by sovit042** [keiyoushi/tachiyomi-extensions-source#108]
### Source name

Immortal Updates

### Source link

https://immortalupdates.com/

### Source language

English

### Other details

NSFW: No

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
An extension with the provided URL (https://immortalupdates.com/) already exists with the name of **Immortal Updates**, under the **English** section: https://keiyoushi.github.io/extensions/extensions/#en.immortalupdates
