### ISSUE TITLE
AYATOON

### ISSUE THREAD

**Issue by kyoyacchi** [keiyoushi/tachiyomi-extensions-source#1081]
### Source name

AYATOON

### Source link

https://ayatoon.com/

### Source language

Turkish

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
Source is down

**Comment by vetleledaal** [comment]
> Source is down

Works fine for me, just need to VPN into Turkey.

**Comment by choppeh** [comment]
> > Source is down
> 
> Works fine for me, just need to VPN into Turkey.

geo block 😓

**Comment by kyoyacchi** [comment]
> Source is down

No, it's working fine.
