### ISSUE TITLE
Cannot install updated extensions

### ISSUE THREAD

**Issue by MedusaWasInnocent** [keiyoushi/tachiyomi-extensions-source#109]
### Source information

Bato.to 1.4.33, Cubari 1.4.24

### Source language

Multi, English

### Steps to reproduce

1. In app, select install button for extension 
2. After "Do you want to install this app?" appears, select Install
3. Extension seems to install for a few seconds, then suddenly stops. No error message is shows. 

### Expected behavior

Extensions should be installed

### Actual behavior

Extension installation suddenly stops

### Tachiyomi version

0.15.2

### Android version

Android 12

### Other details

This problem appears only with extensions that show updates. Any extensions from before tachiyomi removed its extension repo installs fine. 

Solutions tried: 

- disabling play protect
- uninstalling tachiyomi and deleting all tachiyomi files (excluding backups)
- rolling back to Tachiyomi 0.15.1
- downloading the extension directly from github, error "App not installed as package conflicts with an existing package." Error persists regardless of app version, after uninstalling tachiyomi and after uninstalling Bato extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ORLOX93** [comment]
I have exact issue with different extensions, i would think is a global bug for all extensions. But i need to point out that the installation never actually starts, it closes as soon as you press install.

**Comment by beer-psi** [comment]
Uninstall the previous extensions from Tachiyomi. If that does not work, uninstall it from your device's settings by looking for `Tachiyomi: <extension name>`.

**Comment by MedusaWasInnocent** [comment]
> Uninstall the previous extensions from Tachiyomi. If that does not work, uninstall it from your device's settings by looking for `Tachiyomi: <extension name>`.

Hi

Thank you for the advice. I have done this already. I uninstalled Bato in app and made sure it was uninstalled in phone settings. I now cannot access Bato.to because the extension will not install at all.

**Comment by ORLOX93** [comment]
I got really worried about not being able to reinstall an extension, so i picked the one i cared less to test and could successfully uninstall the old version and reinstall the new one.

**Comment by MedusaWasInnocent** [comment]
> I got really worried about not being able to reinstall an extension, so i picked the one i cared less to test and could successfully uninstall the old version and reinstall the new one.

I could only do that with extensions that haven't been updated. Is this the same with you?

**Comment by ORLOX93** [comment]
> > I got really worried about not being able to reinstall an extension, so i picked the one i cared less to test and could successfully uninstall the old version and reinstall the new one.
> 
> I could only do that with extensions that haven't been updated. Is this the same with you?

Not at all. I followed beerpiss instructions and could reinstall all 6 of the extensions that had updates on my end.

**Comment by MedusaWasInnocent** [comment]
> > > I got really worried about not being able to reinstall an extension, so i picked the one i cared less to test and could successfully uninstall the old version and reinstall the new one.
> > 
> > I could only do that with extensions that haven't been updated. Is this the same with you?
> 
> Not at all. I followed beerpiss instructions and could reinstall all 6 of the extensions that had updates on my end.

Could you tell me what you did exactly? I must not understand beerpiss properly

**Comment by ORLOX93** [comment]
> > > > I got really worried about not being able to reinstall an extension, so i picked the one i cared less to test and could successfully uninstall the old version and reinstall the new one.
> > > 
> > > 
> > > I could only do that with extensions that haven't been updated. Is this the same with you?
> > 
> > 
> > Not at all. I followed beerpiss instructions and could reinstall all 6 of the extensions that had updates on my end.
> 
> Could you tell me what you did exactly? I must not understand beerpiss properly

I'm pressing the name of the extension to install/uninstall, not the icon (dunno if that affects anything, but I'm clarifying).

I click the name of the extension that says it has an update available (that shows the extension info page) and then click uninstall (the app takes like 1 or 2 extra seconds after uninstalling to actually remove the extension from the list).
Then i type the name of the extension on the search bar and press on the name to install.

And that's about it.

**Comment by MedusaWasInnocent** [comment]
> > > > > I got really worried about not being able to reinstall an extension, so i picked the one i cared less to test and could successfully uninstall the old version and reinstall the new one.
> > > > 
> > > > 
> > > > I could only do that with extensions that haven't been updated. Is this the same with you?
> > > 
> > > 
> > > Not at all. I followed beerpiss instructions and could reinstall all 6 of the extensions that had updates on my end.
> > 
> > Could you tell me what you did exactly? I must not understand beerpiss properly
> 
> I'm pressing the name of the extension to install/uninstall, not the icon (dunno if that affects anything, but I'm clarifying).
> 
> I click the name of the extension that says it has an update available (that shows the extension info page) and then click uninstall (the app takes like 1 or 2 extra seconds after uninstalling to actually remove the extension from the list).
> Then i type the name of the extension on the search bar and press on the name to install.
> 
> And that's about it.

That's what I did, and it does not work. I have no idea what is wrong. 

You said you had 6 extensions that updated. The ones that updated (and can't install) for me are Bato and Cubari. Can you tell me the other 4? I want to see if I can install them.

**Comment by minhngoc25a** [comment]
Here is something I do to prevent all the tricky installation stuff:

1. Create a Tachiyomi backup.
2. Use another device (or an emulator) and install the TachiyomiSY fork.
3. Wait for the backup to finish restoring (the progress is showed in the notification bar, can take long for huge libraries)
4. Go to **Browse >> Migrate** to view the list of old sources and install all sources in the Keiyoushi repo corresponding to the old official repository. Then, tap **All** on the sources to use the SY fork mass migrate feature.
5. After you've confirmed that all your comics in the second device have been migrated properly, uninstall all Tachiyomi extensions from the first device, go to Settings and clear **all data** of Tachiyomi. Then create a backup on the second device and restore it on the first device.

Why use a second device? => To prevent you from mistaking extensions from different repositories, we should use a clean installation. If you're confident that you can distinguish, you can do it in the same device.

**Comment by ORLOX93** [comment]
I know one of them was TuMangaOnline (because is the only Spanish extension that i have). Another one is Bato.to, but i don't remember the other ones.

I think you have to either follow minhngoc25a's advice or just use a different extension to replace bato.to, i recommend Mangadex or Comick (i use both).

**Comment by MedusaWasInnocent** [comment]
> Here is something I do to prevent all the tricky installation stuff:
> 
> 1. Create a Tachiyomi backup.
> 2. Use another device (or an emulator) and install the TachiyomiSY fork.
> 3. Wait for the backup to finish restoring (the progress is showed in the notification bar, can take long for huge libraries)
> 4. Go to **Browse >> Migrate** to view the list of old sources and install all sources in the Keiyoushi repo corresponding to the old official repository. Then, tap **All** on the sources to use the SY fork mass migrate feature.
> 5. After you've confirmed that all your comics in the second device have been migrated properly, uninstall all Tachiyomi extensions from the first device, go to Settings and clear **all data** of Tachiyomi. Then create a backup on the second device and restore it on the first device.
> 
> Why use a second device? => To prevent you from mistaking extensions from different repositories, we should use a clean installation. If you're confident that you can distinguish, you can do it in the same device.

Thanks for this advice! I did try it, it did not work T^T tachiyomi does work on the other device though, so the problem is definitely my phone.

I tried using a SY on my phone and bato still wouldn't install! I have no idea what I am doing wrong. I uninstalled all extensions, deleted all Tachiyomi files. All that's left is wiping my phone entirely.

I'm desperate, if you have some advice I am happy to hear it

**Comment by PTracana** [comment]
Check the permissions of tachiyomi. 
My tachi got it's permissions reset and couldn't install "unknown apps"
@MedusaWasInnocent

**Comment by NotNeko-Chan** [comment]
Have the same issue with Nhentai v1.4.39

Unfortunately I haven't been able to come uo with a solution either.

**Comment by MedusaWasInnocent** [comment]
> Check the permissions of tachiyomi. 
> My tachi got it's permissions reset and couldn't install "unknown apps"
> @MedusaWasInnocent 

I checked that, still doesn't work. Thanks for the advice though

**Comment by MedusaWasInnocent** [comment]
> Have the same issue with Nhentai v1.4.39
> 
> Unfortunately I haven't been able to come uo with a solution either.

If I ever figure out the problem I'll let you know

**Comment by MedusaWasInnocent** [comment]
> Have the same issue with Nhentai v1.4.39
> 
> Unfortunately I haven't been able to come uo with a solution either.

I SOLVED IT!!!

My device is a Samsung, and a long time ago I used tachiyomi in the secure folder (stupid idea, don't do this). Uninstalled tachiyomi and the extensions from there and now it all works.

**Comment by NotNeko-Chan** [comment]
> > Have the same issue with Nhentai v1.4.39
> > 
> > Unfortunately I haven't been able to come uo with a solution either.
> 
> I SOLVED IT!!!
> 
> My device is a Samsung, and a long time ago I used tachiyomi in the secure folder (stupid idea, don't do this). Uninstalled tachiyomi and the extensions from there and now it all works. 

My device is also a Samsung. I too had also used Tachiyomi in the Secure Folder. Followed your advice and it actually worked. Feel incredibly dumb right now, but I'm so glad it's been solved.

**Comment by beer-psi** [comment]
Locking this thread permanently as we already have a pretty clear troubleshooting guide for this.

### If there were no errors installing
Try restarting Tachiyomi. There is a known bug where the app thinks the extension wasn't updated, even if it did.

### If installation ended with "App not installed"
Uninstall your old extension before installing Keiyoushi extensions. If it still doesn't install, try uninstalling the extension from your device's settings by searching for `Tachiyomi: <extension name>`.

This is caused by Keiyoushi extensions having a different signature from old official extensions, making Android refuse to update it.

**For devices with "secure folder"**: You may need to check if the extension was installed in the secure folder, if you cannot find it in your device's settings.
