### ISSUE TITLE
mangatale: Some images do not appear 

### ISSUE THREAD

**Issue by mozzaru** [keiyoushi/tachiyomi-extensions-source#1097]
### Source information

mangatale 1.4.30

### Source language

Indonesia 

### Steps to reproduce

1. Open yokai
2. Select the mangatale extension
3. Select last update

### Expected behavior

.

### Actual behavior

.

### Mihon/Tachiyomi version

1.7.12(yokai)

### Android version

Android 11

### Other details

![Screenshot_2024-02-07-21-05-31-63_21015a41200050f19d2d2db913bd7dc1](https://github.com/keiyoushi/extensions-source/assets/100791931/05be2cbe-3c12-4668-9728-829addc8899b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by SnakeDoc83** [comment]
That's how it looks on their website too, literally noimg165px.png
