### ISSUE TITLE
Taiyo: Latest updates only show 6 entries

### ISSUE THREAD

**Issue by nomaxsnx** [keiyoushi/tachiyomi-extensions-source#1109]
### Source information

Taiyo português 1.4.1

### Source language

Português 

### Steps to reproduce

1 install extension
2 Open extension 

### Expected behavior

All the mangas, manhua and so on were supposed to appear, but only those do.

### Actual behavior

![Screenshot_2024-02-07-16-57-30-237_app mihon](https://github.com/keiyoushi/extensions-source/assets/157644160/31493876-9217-4a67-a099-b0c383654f8b)

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
This is intended. You can visit https://taiyo.moe yourself and see that there are only 6 latest updates on the page.

**Comment by nomaxsnx** [comment]
Try searching for some character that will appear more, that doesn't just have those mangas

![Screenshot_2024-02-09-18-29-05-883_com android chrome](https://github.com/keiyoushi/extensions-source/assets/157644160/9eef9b06-0ce5-4e8d-ba04-6401d71a57f2)

**Comment by vetleledaal** [comment]
Latest/popular isn't paginated, so that's why it only shows 6 or so entries. Searching for "A" works as you'd expect, but these can't be used for the latest tab, since, well, they're not the latest manga.

If you find a place on the website where it list out more entries at once, feel free to point us in the right direction in the form of a feature request.
