### ISSUE TITLE
Bato.to

### ISSUE THREAD

**Issue by diamanteuzumaki** [keiyoushi/tachiyomi-extensions-source#1130]
### Source information

0.15.3

### Source language

English

### Steps to reproduce

Cannot access Bato.to. cannot download anything because there is no json link

### Expected behavior

access to bato.to

### Actual behavior

no access

### Mihon/Tachiyomi version

0.15.3

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by SnakeDoc83** [comment]
You didn't include extension version information, I'm guessing it's an old version. Update your extension (you may need to uninstall and then re-add it if it's from the old repo).

**Comment by diamanteuzumaki** [comment]
Extension 1.4.33. I tried uninstalling and reinstalling and it doesn't work.

**Comment by Norsze** [comment]
> Extension 1.4.33. I tried uninstalling and reinstalling and it doesn't work.

Still you on an old version that is probably not from this repo. We have 1.4.35.

It is not our issue that you have the wrong extension.
