### ISSUE TITLE
Plot Twist No Fansub source extension not installing

### ISSUE THREAD

**Issue by P10Ms** [keiyoushi/tachiyomi-extensions-source#1141]
### Source information

Plot Twist No Fansub 1.4.1

### Source language

Spanish

### Steps to reproduce

1. Enter the app
2. Search the extension
3. Click the install button
4. The source can't install

### Expected behavior

The source should install properly and should appear in the installed sources section.

### Actual behavior

The source can't be installed in the app and from the website, and when trying to install it from the website says that the app hasn't been installed. The rest of extensions can be installed properly.

### Mihon/Tachiyomi version

Mihon r6501

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Works fine for me.

Make sure there is not an old version in the phone by going to your phone's settings app and going to the app list section. Search it and make sure there is no "Plot Twist no Fansub" there. They usually look like this in the list: Tachiyomi: (extension name)

**Comment by P10Ms** [comment]
> Works fine for me.
> 
> Make sure there is not an old version in the phone by going to your phone's settings app and going to the app list section. Search it and make sure there is no "Plot Twist no Fansub" there. They usually look like this in the list: Tachiyomi: (extension name)

It helped! I had a very old version installed in my device. Thank you very much!
