### ISSUE TITLE
MangaDex not saving Fiters from Account Login

### ISSUE THREAD

**Issue by BuckwheatBidoof** [keiyoushi/tachiyomi-extensions-source#1145]
### Source information

MangaDex 1.4.192

### Source language

English

### Steps to reproduce

1. Log into MangaDex Account
2. Set Content Filters to enable all
3. Search any Erotica or Pornographic material without changing filters

### Expected behavior

Erotica or Pornographic material will show

### Actual behavior

No Erotica or Pornographic material will show

### Mihon/Tachiyomi version

Tachiyomi SY 1.10.2

### Android version

Android 10

### Other details

MangaDex extension does not filter content based on logged in account.
Affects Migration from other sources not showing MangaDex.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
MangaDex has never had any support for logging in through the WebView, because credentials are stored inside local storage and not cookies, which we can't access without spinning up a headless browser.
