### ISSUE TITLE
Recover Extension Yugenmangas

### ISSUE THREAD

**Issue by YuiitsunoYoake** [keiyoushi/tachiyomi-extensions-source#1163]
### Describe why this should be added

A few days ago in #960 it was commented that the source "yugenmangas" was linked to another page "ikigaimangas.com" and did not work, leading to its elimination in #963, but when I checked the page "yugenmangas" in the browser it is running with another domain "yugenmangas.net". Is there any possibility that this extension can be recovered and a change made to the domain so that it works again?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
According to their statement, they only enabled the page so that their users can transfer their saved series to the new page, they stopped uploading chapters to the page so I don't see the need for it to be added again
