### ISSUE TITLE
Hunters Scans: Extension broken

### ISSUE THREAD

**Issue by FelypeRo** [keiyoushi/tachiyomi-extensions-source#1166]
### Source information

Hunters Scans 1.4.33

### Source language

Portuguese (Brazil)

### Steps to reproduce

Open app - Browse - Open extension: Hunters Scan

### Expected behavior

When opening the extension, the mangas/manhwas should appear

### Actual behavior

HTTP 404 occurs

### Mihon/Tachiyomi version

Mihon 0.16.3

### Android version

Android 11

### Other details

the link has not been changed. Chapters are updated normally on the website.
![image](https://github.com/keiyoushi/extensions-source/assets/38269904/f4e8b2f9-2975-4a61-9ace-5a5a1da43988)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nomaxsnx** [comment]
Duplicata of #929
