### ISSUE TITLE
Happymh: images not loading

### ISSUE THREAD

**Issue by caitlin-cheng-ccc** [keiyoushi/tachiyomi-extensions-source#1181]
### Source information

Happymh 1.4.7

### Source language

Chinese

### Steps to reproduce

1. Open extension
2. Click any manhua
3. Read
4. Loading fails
![Screenshot_20240210_135122_Mihon](https://github.com/keiyoushi/extensions-source/assets/88336231/6a6faa2f-22d2-44f0-a8a0-14d7f55dd151)
5. Open webview
![Screenshot_20240210_134429_Mihon](https://github.com/keiyoushi/extensions-source/assets/88336231/622bfb60-0bab-497c-81c8-08a4cc546c89)

### Expected behavior

Loading succeed and manhua is showing

### Actual behavior

Loading fails and unable to read in webview as well

### Mihon/Tachiyomi version

App version: 0.16.3 (standard, 139663a, 4, 2024-01-29T20:34Z) 

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by breadrollfort** [comment]
Android version 13 apologies

**Comment by caitlin-cheng-ccc** [comment]
Android version 13 apologies

**Comment by alan0507** [comment]
I have the same problem
But my webview is working

**Comment by Nevermind425** [comment]
Does anyone know how to solve that?

**Comment by vactorlao** [comment]
Happymh cannot load here

https://github.com/keiyoushi/extensions-source/assets/7175977/36a66aa4-759e-495f-a564-78e7f0bded07

**Comment by vactorlao** [comment]
iOS happymh also cannot load

https://github.com/keiyoushi/extensions-source/assets/7175977/cd07e906-e387-4500-833f-a7c5f513a160

**Comment by sherlkay** [comment]
Im having the same issues. But webview is working. Mine is Android 14 AP21.240119.009.

**Comment by sao-coding** [comment]
Android version 11
Loading fails
![image](https://github.com/keiyoushi/extensions-source/assets/58339015/a05442e7-21c1-4ecd-9a35-666ceb8cebe3)

**Comment by Wcraft233** [comment]
After testing, it still cannot load after updating, but the WebView is normal
![Screenshot_2024-02-20-00-41-19-937_app mihon](https://github.com/keiyoushi/extensions-source/assets/30252123/d200e591-0d80-44b3-8dd6-cb60f5975cd4)
![Screenshot_2024-02-20-00-41-08-207_app mihon](https://github.com/keiyoushi/extensions-source/assets/30252123/3a1c25bd-50ed-4756-ad93-e3b4599bf556)
