### ISSUE TITLE
Kaisen Backup - Source Request

### ISSUE THREAD

**Issue by DFBR1208** [keiyoushi/tachiyomi-extensions-source#1188]
### Source name

Kaisen Backup

### Source link

https://www.kaisenbackup.com/

### Source language

Portuguese (Brazil)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Source has been down for 3 weeks. Closing.
And by down I mean there have been no chapters available.
