### ISSUE TITLE
Flix Scans: Could not resolve host

### ISSUE THREAD

**Issue by FangMin2005** [keiyoushi/tachiyomi-extensions-source#119]
### Source information

Flix scans 1.4.3

### Source language

English 

### Steps to reproduce

1. Download the entensions
2. Click on the entension in the sources tab 

### Expected behavior

It shows 6 series 

### Actual behavior

It shows this
![Screenshot_20240111_034306](https://github.com/keiyoushi/extensions-source/assets/90857600/e9dae707-1173-47f1-ad8d-c3d84b8ae1a8)

### Tachiyomi version

0.15.2

### Android version

Android 11

### Other details

I'm pretty sure the problem is caused by flix scans changing their home page. 
When I click on Flixscans.org I get redirected to https://flixscans.org/webtoons/romance/home. On their discord server web status channel, they said that the past few days that their website have been attacked and they're working on solutions. I'm pretty sure this is one of their solutions. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FangMin2005** [comment]
That url may be a temporary solution

**Comment by AwkwardPeak7** [comment]
closing in favor of #183
