### ISSUE TITLE
Colamanga search not working

### ISSUE THREAD

**Issue by caitlin-cheng-ccc** [keiyoushi/tachiyomi-extensions-source#1196]
### Source information

Colamanga 1.4.16

### Source language

Chinese

### Steps to reproduce

1. Open colamanga
2. Go to search
3. Search any manhua
4. No results
![Screenshot_20240211_000737_Mihon](https://github.com/keiyoushi/extensions-source/assets/88336231/0b7f417f-64f7-4320-88c6-caf3c524ccab)

### Expected behavior

Search a manhua in the search bar and the result shows up and any related search

### Actual behavior

No results even when webview search shows results
![Screenshot_20240211_000942_Mihon](https://github.com/keiyoushi/extensions-source/assets/88336231/6c17125d-7927-4c55-8f0a-a9be83f5356f)

### Mihon/Tachiyomi version

Mihon 0.16.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by anenasa** [comment]
I suspect [this line](https://github.com/keiyoushi/extensions-source/blob/1cdcae168474cd4f6f3b51cb2e45b76524fd2095/multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/colamanga/ColaManga.kt#L129C1-L129C13) is at fault. It was `fed-deta-info` before.

**Comment by hsiayuchih** [comment]
same problem
