### ISSUE TITLE
Manga Koma - Source request

### ISSUE THREAD

**Issue by reporttachiyomi** [keiyoushi/tachiyomi-extensions-source#1198]
### Source name

Manga Koma

### Source link

https://mangakoma01.net/

### Source language

Japanese

### Other details

18+/NSFW = yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Uses same theme as MangaSect/DocTruyen5s

**Comment by beer-psi** [comment]
> Uses same theme as MangaSect/DocTruyen5s 

Which is, interestingly, a branch of MangaReader. At this point I'm not sure if there's even anything concrete about MangaReader other than the chapter pages being loaded through AJAX.
