### ISSUE TITLE
Scan Hentai FR

### ISSUE THREAD

**Issue by WoodlyBasquin56** [keiyoushi/tachiyomi-extensions-source#1210]
### Source name

Scan Hentai FR

### Source link

https://scan-hentai.fr/

### Source language

French

### Other details

+18 yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by WoodlyBasquin56** [comment]
@KirinRaikage

**Comment by KirinRaikage** [comment]
Can you reopen an issue and not check the "clown" thing?

**Comment by Norsze** [comment]
Since @KirinRaikage seems to want to take this on

**Comment by WoodlyBasquin56** [comment]
Nice
