### ISSUE TITLE
MangaSee/MangaLife uses chapter naming scheme as scanlator name

### ISSUE THREAD

**Issue by Smol-Ame** [keiyoushi/tachiyomi-extensions-source#1215]
### Source information

MangaSee 1.4.36 / MangaLife 1.4 28

### Source language

English

### Steps to reproduce

As pointed out in repo-support, certain titles with more than one chapter naming scheme, the extension/app recognizes those different naming schemes as "scanlator groups"

Some of the titles include Berserk, Dr. Stone, One-Punch Man, and Trigun.

![Screenshot_20240212_173911_Mihon](https://github.com/keiyoushi/extensions-source/assets/155411819/1ac9704f-b735-4958-aedf-a2732eac7982)
![Screenshot_20240212_174027_Mihon](https://github.com/keiyoushi/extensions-source/assets/155411819/8a84cd04-fffa-427f-bdd5-a58e1c1612f7)
![Screenshot_20240212_174054_Mihon](https://github.com/keiyoushi/extensions-source/assets/155411819/4f6110eb-e707-4f44-9cf9-1fe8c41e97c7)
![Screenshot_20240212_174136_Mihon](https://github.com/keiyoushi/extensions-source/assets/155411819/c4ca27a2-c2ce-4bfd-a1cd-c2897d05651d)

### Expected behavior

It shouldn't be considered (in the app) as a scanlator group

### Actual behavior

It thinks it's a scanlator group

### Mihon/Tachiyomi version

TachiyomiSY r542

### Android version

Android 14

### Other details

As mentioned by Xori in the channel, it only started happening after the latest update to that extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
This was an intentional feature added about a week ago (https://github.com/keiyoushi/extensions-source/pull/1131) so users can choose to block out some chapters.

**Comment by Xori71** [comment]
> This was an intentional feature added about a week ago (#1131) so users can choose to block out some chapters.

Then they can use the freaking bookmark feature, like we’ve always been doing. It’s a very stupid implementation, the way it was done. I am surprised that the one who did the Pull Request didn't see the flaws in it.

**Comment by Norsze** [comment]
I wouldn't call it stupid, let's be civil. This is a very rare occurrence from what I have found. Half of them seem redundant with just the naming scheme being changed. And half seem somewhat useful with separation of seasons, magazine versions or in Trigun's case the separation of a prequel and sequel. 

It's very rare, have to look for it to get bothered and will only be pointless maybe half the time.

**Comment by Xori71** [comment]
> I wouldn't call it stupid, let's be civil. This is a very rare occurrence from what I have found. Half of them seem redundant with just the naming scheme being changed. And half seem somewhat useful with separation of seasons, magazine versions or in Trigun's case the separation of a prequel and sequel.
> 
> It's very rare, have to look for it to get bothered and will only be pointless maybe half the time.

Yes, let's ignore the fact that Trigun and One-Punch Man are already separated thanks to the chapter names themselves. The change is redundant. It doesn’t fix anything because NepNep doesn’t add scanlation info.

**Edit:** And for the record, I can see the vision. But it just doesn’t work with these extensions.
