### ISSUE TITLE
OzalScans : Dead Source report 

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#1220]
### Source name

OzalScans

### Source language

Arabic

### Source link

https://kingofmanga.com

### Other details

This link is a new website and has no connection to it OzulScans You must create a new source KingOfManga Delete the previous source

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
> Important announcement
> Hello, dear readers, we would like to note that the Ozul Skans team has returned to the field and has merged with the Black team and become Thunder. https://thunderscans.com/

Users should migrate to exisiting thunderscans extension.

**Comment by ghost** [comment]
> > Important announcement
> > Hello, dear readers, we would like to note that the Ozul Skans team has returned to the field and has merged with the Black team and become Thunder. https://thunderscans.com/
> 
> Users should migrate to exisiting thunderscans extension.

You must remove the Ozul Manga source and create a new source called King Manga

**Comment by Norsze** [comment]
that is two different requests, either this is a source removal, domain change or a source request. Can't be two in one.

**Comment by vetleledaal** [comment]
Fixed in #1917
