### ISSUE TITLE
Team X : Manual link update feature 

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#1221]
### Source name

Team X

### Source language

Arabic

### Describe your suggested feature

An option must be added that allows the source's link to be changed manually because the source often updates and changes its link

### Other details

I expect the source will cancel the old link soon. Address of the new link
https://www.team1x1shojo.com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by mohamedotaku** [comment]
"team1x1shojo" it's mirror for "teamxnovel"

**Comment by ghost** [comment]
> "team1x1shojo" it's mirror for "teamxnovel"

I know that TeamX is always changing its domain, so I suggested the feature of manually modifying the domain.
