### ISSUE TITLE
Mangadig search/migrate not working & chapters not loading

### ISSUE THREAD

**Issue by Dinor** [keiyoushi/tachiyomi-extensions-source#1223]
### Source information

Mangadig 1.4.1

### Source language

English

### Steps to reproduce

Migrate & Search:
Search on the source or migrate a series to the source

Chapters:
Open source and then go to a series and open a chapter.

### Expected behavior

Migrate & Search:
Shows everything related to the search

Chapters:
Chapter loads properly 

### Actual behavior

Migrate & Search:
No results found

Chapters:
Chapter keeps loading for a long time then the app crashes or it says timed out decrypting image links

### Mihon/Tachiyomi version

TachiyomiJ2K 1.7.4 & Mihon 0.16.3

### Android version

Android 8

### Other details

The chapters load fine on webview 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
The search issue has been fixed in 1.4.2, but I can't reproduce the timeout issue. Can you give a specific series that's causing the issue?

**Comment by Dinor** [comment]
Thank you, the search works now. 😄 
Before the timeout error, it worked fine on webview but it crashed the app after loading for a while but now I've been getting the timeout error for all the series and it shows a white screen in webview. If I open it in a browser from the overflow menu, the website works fine

**Comment by Dinor** [comment]
An update to this, the timeout issue was fixed in 1.4.3 and it works in webview too. However, for some series like for example "A Record of a Mortal's Journey to Immortality", the chapters load for a while then the app crashes.
Also I've been getting a similar issue that was on reaper scans where the cover shows the first time when you open/refresh the series but once you go out of it, the cover doesn't show anymore and it has the broken image icon
