### ISSUE TITLE
Manwa shows no results, but webview is okay

### ISSUE THREAD

**Issue by yuduotianguang** [keiyoushi/tachiyomi-extensions-source#1224]
### Source information

manwa1.4.4

### Source language

Chinese

### Steps to reproduce

1.Open the app
2.Open manwa
3.No result but webview  is okay

https://github.com/keiyoushi/extensions-source/assets/104707441/ee30fdf1-d79e-4dd8-be07-dbcbacdecd9b

### Expected behavior

It can be used to read

### Actual behavior

No results

### Mihon/Tachiyomi version

TachiyomiJ2K1.7.4

### Android version

Android13

### Other details

It happens only when in China IP, you need click some buttons in webview

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by NeKoOuO** [comment]
用英文 這裡不是中文論壇
www.deepl.com
