### ISSUE TITLE
Nartag

### ISSUE THREAD

**Issue by Gabriel062323** [keiyoushi/tachiyomi-extensions-source#123]
### Source name

nartag

### Source link

https://nartag.com/

### Source language

Spanish

### Other details

if possible free paid please 

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Extension already exist as "Traducciones Amistosas" under the Spanish section.

**Comment by Gabriel062323** [comment]
> Extension already exist as "Traducciones Amistosas" under the Spanish section.

thank you so much, years in this bro
