### ISSUE TITLE
Tumangaonline does not download some manga

### ISSUE THREAD

**Issue by daniel95000** [keiyoushi/tachiyomi-extensions-source#1231]
### Source information

Tumangaonline 1.51

### Source language

Spanish

### Steps to reproduce

1.I start downloading some mangas like the manga chapter "Contrato de esclavitud obsceno" of that length

2.They are not downloaded due to Cloudfire failure

3.Since it doesn't download, I try to read it directly without downloading it with the application

4.The same thing happens and it doesn't let me read it due to Cloudfire's failure

5.I try the same steps with another manga of that length (Example: "Yakusoku No Neverland) and if it works

### Expected behavior

You should have downloaded and/or let me read those mangas in the app

### Actual behavior

The chapters should have been downloaded and/or it should be possible to read but strangely it could not be

### Mihon/Tachiyomi version

TachiyomiSY Stable 1.10.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Refer to the Cloudflare section at the [troubleshooting guide](https://keiyoushi.github.io/docs/guides/troubleshooting#cloudflare)

**Comment by daniel95000** [comment]
> Refer to the Cloudflare section at the [troubleshooting guide](https://keiyoushi.github.io/docs/guides/troubleshooting#cloudflare)

I'm here because I already tried to do that but it didn't work for me. Or maybe I didn't know how to do the user agent thing well.

**Comment by bapeey** [comment]
> I'm here because I already tried to do that but it didn't work for me. Or maybe I didn't know how to do the user agent thing well.

The only thing you can do is keep trying different user agents or wait for the site to lower its protection. Also, in the latest version of the extension an option was added so that if you have a cloudflare error when opening a chapter, you can open the manga in WebView to show the captcha

**Comment by daniel95000** [comment]
I just don't know how to test that... I mean I don't understand how testing different user agents works, I just don't know what to do. As for the other thing you say, I have already tried opening it in webview, when I open it I get the check box but once I do it it gives an error and asks me to verify myself again

**Comment by bapeey** [comment]
You just need to try different ones until one works. Try using your browser's user agent (the one that appears on this [page](https://whatmyuseragent.com)), and then change the user agent string in the app as the [guide](https://keiyoushi.github.io/docs/guides/troubleshooting#changing-your-user-agent) says
