### ISSUE TITLE
Not loading Images ( Newtoki)

### ISSUE THREAD

**Issue by Morse069** [keiyoushi/tachiyomi-extensions-source#1242]
### Source information

Newtoki 1.4.29

### Source language

Korean

### Steps to reproduce

Solve captcha
Click any chapter (Old and New)
It says no image

### Expected behavior

Can load images 

### Actual behavior

![Screenshot_2024-02-14-02-38-54-05_afd66b7916d19a60815f56273408b73e](https://github.com/keiyoushi/extensions-source/assets/121346796/08bc2f49-dca3-4b79-bb9f-84d25c273c9f)

### Mihon/Tachiyomi version

0.16.0

### Android version

Android 10

### Other details

Webview is okay

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KW1J** [comment]
I am also experiencing the same issue as this.  Other extensions work, but this one doesn't work.

**Comment by FengTeLai** [comment]
能读取到作品更新目录，但在线观看和webview单图查看都是链接失效
![Screenshot_20240215_051532_eu kanade tachiyomi](https://github.com/keiyoushi/extensions-source/assets/117538601/cb185561-d9c3-4e52-9548-dd1f612a6ba0)

**Comment by jake1015** [comment]
The image URL is fetched correctly. However, Newtoki is performing a referrer check, and if there is no referrer or wrong referrer, it sends a 404 not found error.

For example, if you send a request like

curl "https://img1.newtoki21.org/data/file/webtoon/25185533/36125141/U8w_zmraL0lp.jpg"

it will result in a 404 not found error. But if you send it with a referrer like

curl "https://img1.newtoki21.org/data/file/webtoon/25185533/36125141/U8w_zmraL0lp.jpg" -H "Referer: https://newtoki325.com/"

it will download correctly.

**Comment by FengTeLai** [comment]
@jake1015 I still don't get it, the URL works fine, but the image doesn't show up, and if I want to view a single image, I still have to tap on the corresponding chapter on the web side first.
Newtoki's 3rd party app has fixed this issue, hopefully the plugin here will as well.

**Comment by KW1J** [comment]
> @jake1015 I still don't get it, the URL works fine, but the image doesn't show up, and if I want to view a single image, I still have to tap on the corresponding chapter on the web side first. Newtoki's 3rd party app has fixed this issue, hopefully the plugin here will as well.

Can you tell me what kind of 3rd party app it is?

**Comment by FengTeLai** [comment]
> > @jake1015 I still don't get it, the URL works fine, but the image doesn't show up, and if I want to view a single image, I still have to tap on the corresponding chapter on the web side first. Newtoki's 3rd party app has fixed this issue, hopefully the plugin here will as well.
> 
> Can you tell me what kind of 3rd party app it is?

Just search Newtoki in github.（Java）

**Comment by KW1J** [comment]
thanks
