### ISSUE TITLE
Newtoki/ Manatoki images couldn't be loaded

### ISSUE THREAD

**Issue by Kantotero** [keiyoushi/tachiyomi-extensions-source#1251]
### Source information

NewToki/ManaToki 1.4.29

### Source language

Korean/한국어

### Steps to reproduce

1. Open manhwa and read in manatoki/newtoki
2. Open webview if captcha appears;
3. `Images wouldn't load ` error appears
4. Opening it on webview works but tachiyomi doesn't load images, tried on different manhwas from manatoki & newtoki, all of the mnahwas doesn't display images

### Expected behavior

The images should pop out just fine.

### Actual behavior

`Images couldn't be loaded` error appears
![IMG_20240214_214056](https://github.com/keiyoushi/extensions-source/assets/125627064/2dc68ac8-b7bd-48bc-8ca7-aad2d6980ada)

### Mihon/Tachiyomi version

J2K 1.7.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Kantotero** [comment]
https://github.com/keiyoushi/extensions-source/issues/1242#issue-2133535227 so on Mihon it also doesn't work

**Comment by beer-psi** [comment]
Duplicate of #1242
