### ISSUE TITLE
SSL certificate expired for source: zh.dmzj

### ISSUE THREAD

**Issue by XeonStin** [keiyoushi/tachiyomi-extensions-source#1254]
### Source information

DMZJ 1.4.42

### Source language

Chinese/zh

### Steps to reproduce

Open any chapter of any manga

### Expected behavior

I should see manga content

### Actual behavior

I saw error message "SSLHandshakeException: Unacceptable certificate:
CN=DigiCert Global Root CA,
OU=www.digicert.com, O=DigiCert Inc, C=US"

![IMG_20240214_230655](https://github.com/keiyoushi/extensions-source/assets/3463519/08c91b7c-44b8-43f2-b685-0a1bfc40f720)

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 13/MIUI 14.0.8

### Other details

The SSL certificate for *.dmzj.com has expired since 2023.11.9

However, certificate for *.idmzj.com still works. Maybe change the API URL to "nnv4api.idmzj.com" instead?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by erinacio** [comment]
Besides nnv4api, `api.dmzj.com` also expires.

**Comment by stevenyomi** [comment]
Source certificate misconfiguration, already resolved.
