### ISSUE TITLE
[Webdex Scans] HTTP 404, check website in WebView

### ISSUE THREAD

**Issue by ImFiru** [keiyoushi/tachiyomi-extensions-source#1258]
### Source name

Webdex Scans

### Source language

English

### Source link

https://webdexscans.com/

### Other details

The website works as normal, the problem is in the extension 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by ImNebby** [comment]
why did you close it ?
