### ISSUE TITLE
 No covers in colamanga

### ISSUE THREAD

**Issue by yuduotianguang** [keiyoushi/tachiyomi-extensions-source#1269]
### Source information

colamanga1.4.18

### Source language

Chinese

### Steps to reproduce

1.Open the app
2.Open colamanga
3.Collect a manga in the library
4.Close the app and open again
5.No covers even if refreshing

### Expected behavior

It has a cover

### Actual behavior

No cover

### Mihon/Tachiyomi version

TachiyomiJ2K1.7.4

### Android version

Android13

### Other details

There is no problem in original Tachiyomi
or Mihon or TachiyomiSY, but there is also no problem in other add-ins in TachiyomiJ2K,
so I think it something wrong

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by NeKoOuO** [comment]
用英文 這裡不是中文論壇
www.deepl.com

**Comment by AwkwardPeak7** [comment]
J2K only issue
