### ISSUE TITLE
colamanga Search Questions

### ISSUE THREAD

**Issue by TangBaoY** [keiyoushi/tachiyomi-extensions-source#1271]
### Source information

colamanga 1.4.17

### Source language

Chinese

### Steps to reproduce

For example, if you search for "哔哩哔哩漫画", the search result of the website is 11 books, and the software only displays 10 books.

### Expected behavior

Display all

### Actual behavior

Search results show only 10 books

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by NeKoOuO** [comment]
用英文 這裡不是中文論壇
www.deepl.com

**Comment by TangBaoY** [comment]
> 用英文 這裡不是中文論壇
> www.deepl.com

标题是英文
内容反馈为中文可以不🤨

**Comment by NeKoOuO** [comment]
> 
> 标题是英文
> 内容反馈为中文可以不🤨

...你內容不寫英文dev 怎麼看的懂

**Comment by TangBaoY** [comment]
> 
> > 
> > 标题是英文
> > 内容反馈为中文可以不🤨
> 
> ...你內容不寫英文 dev怎麼看的懂

这个中文插件居然是外国人在维护？😮

**Comment by NeKoOuO** [comment]
> 
> 这个中文插件居然是外国人在维护？😮

我幫你看了一下 應該是這個擴展只抓取第一頁的搜尋結果導致的
第11個的搜尋結果是顯示在第二頁

**Comment by TangBaoY** [comment]
> 
> > 
> > 这个中文插件居然是外国人在维护？😮
> 
> 我幫你看了一下 應該是這個擴展只抓取第一頁的搜尋結果導致的
> 第11個的搜尋結果是顯示在第二頁

是的，虽然知道是为什么但是什么也不会😵
只能在这求助了

**Comment by beer-psi** [comment]
> ...你內容不寫英文 dev怎麼看的懂

https://translate.google.com

Issue reports for Chinese sites are written in Chinese, oh the humanities! I really don't care what language you write them in as long as I can paste it into a translator and get the gist of it. We also have a Chinese-speaking maintainer. Please stop spamming the issue tracker by telling people to use DeepL.

**Comment by TangBaoY** [comment]
> 
> > ...你內容不寫英文 dev怎麼看的懂
> 
> https://translate.google.com
> 
> Issue reports for Chinese sites are written in Chinese, oh the humanities! I really don't care what language you write them in as long as I can paste this into a translator and get the gist of it. We also have a Chinese-speaking maintainer. Please stop spamming the issue tracker by telling people to use DeepL.
> 
> 

Thank you so much for clearing up my confusion😊
