### ISSUE TITLE
Pinattsuki

### ISSUE THREAD

**Issue by MadameVerre** [keiyoushi/tachiyomi-extensions-source#1278]
### Source name

Pinattsuki

### Source link

https://www.pinattsuki.my.id/

### Source language

Indonesia

### Other details

18+/NSFW = yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Use DojinRead (Blogspot) Theme Version 2.1

**Comment by Norsze** [comment]
No reader, they use an external site for the actual images, it's all on imgbox.com

**Comment by vetleledaal** [comment]
Source has been down for 3 weeks. Closing.
