### ISSUE TITLE
Magus Manga browsing is broken again (HTTP 404)

### ISSUE THREAD

**Issue by lcd047** [keiyoushi/tachiyomi-extensions-source#1288]
### Source information

Magus Manga 1.4.30

### Source language

English

### Steps to reproduce

Browse > Sources > Magus Manga > Latest

### Expected behavior

The list of manga should be displayed

### Actual behavior

Operation returns "HTTP 404".  Opening in WebView does show the list of manga

### Mihon/Tachiyomi version

Mihon 0.15.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
~new domain is https://vofeg.com/~

**Comment by lcd047** [comment]
This is after the extension was migrated to the new domain (hence broken "again").  It did work at the new domain for a short while.
