### ISSUE TITLE
Manhwa freak reporting http error 404

### ISSUE THREAD

**Issue by Noobforever18** [keiyoushi/tachiyomi-extensions-source#1310]
### Source information

Manhwa Freak 1.4.31

### Source language

English

### Steps to reproduce

1. Open the source in tachiyomi. 2. Select any manhwa. 3. Read or download any manhwa. 4. Showing http error 404

### Expected behavior

It should either allow you to read the manhwa or download the manhwa.

### Actual behavior

It showed http error 404

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
You need to refresh the manga/manhwa before you can read any of the chapters in the Manhwa Freak extension. The issue comes from the chapter links changing frequently. Please read https://mihon.app/docs/guides/troubleshooting/diagnosis if refreshing doesn't fix your issue.

If you have tried everything in the guide, you can comment here. Please include a screenshot if you do.

**Comment by Noobforever18** [comment]
Man I swear yesterday i uninstalled, cleared cookie plus cache and refreshed the extension. Yet it kept on showing the error. And just now i checked again didn't even refreshed it and now it's not only downloading but also showing the manhwa. How? Anyway it's working so i think the thread can be checked as solved
