### ISSUE TITLE
MangaDex extension is failing to install.

### ISSUE THREAD

**Issue by focusedup** [keiyoushi/tachiyomi-extensions-source#132]
### Source information

MangaDex 1.4.192

### Source language

All

### Steps to reproduce

1. Search "MangaDex" in the Extensions list
2. Press the Download/Install button
3. Select "Install" for the prompt, which reads "Do you want to install an update to this existing application? Your existing data will not be lost." 

### Expected behavior

I'd expect MangaDex to then appear in my source list after clearing cache/cookies and relaunching. 

### Actual behavior

But it does not appear in the list. I tried this with Bato, and it worked without issues. Maybe this is related to the fact that I had MangaDex on a previous installation of tachiyomi.

### Tachiyomi version

0.15.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Duplicate of #109
