### ISSUE TITLE
SlimeRead HTTP 521

### ISSUE THREAD

**Issue by Starkr1** [keiyoushi/tachiyomi-extensions-source#1336]
### Source information

SlimeRead 1.4.2

### Source language

Português ( Brasil)

### Steps to reproduce

When opening the extension in mihon, an HTPP521 error appears, even though the site is working correctly.

### Expected behavior

The extension should work like the others, such as the same language extension.

### Actual behavior

When opening the extension, an HTTP 521 error appears, even though the site is working normally through the  webview.

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 11

### Other details

The extension was supposed to be working like this but it's showing this.
![Screenshot_20240217-115402_Mihon](https://github.com/keiyoushi/extensions-source/assets/160334424/899aad8a-df25-4428-a179-a98a7a664628)
![Screenshot_20240217-112814_Mihon](https://github.com/keiyoushi/extensions-source/assets/160334424/9ee77a1b-5578-4193-9a5d-58e683f857fa)
![Screenshot_20240217-113303_Mihon](https://github.com/keiyoushi/extensions-source/assets/160334424/9bb4c77a-faa4-498e-a364-468d3ebf812d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Starkr1** [comment]
The problem is still there, what should I do?

**Comment by bapeey** [comment]
> The problem is still there, what should I do?

Do you update your extension?

**Comment by Starkr1** [comment]
Oh, I've updated it now, thank you very much for your support, it worked.
