### ISSUE TITLE
manganato

### ISSUE THREAD

**Issue by yvesdakempo** [keiyoushi/tachiyomi-extensions-source#135]
### Source information

Manganato

### Source language

English

### Source new URL

https://manganato.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
An extension with the provided URL (https://manganato.com/) already exists with the name of **Manganato**, under the **English** section: https://keiyoushi.github.io/extensions/extensions/#en.manganato

**Comment by yvesdakempo** [comment]
it's weird, i had to re-migrate the manga from manganato to the new manganato, it was readmanganato.com before..now it's fixed after re-migrating...
