### ISSUE TITLE
Sflix broken!! 

### ISSUE THREAD

**Issue by Bipolar708** [keiyoushi/tachiyomi-extensions-source#1352]
### Source information

Sflix 14.24

### Source language

English

### Steps to reproduce

Try to watch/download anything..... it says video list is empty/video not found

### Expected behavior

Be able to download / stream episodes /movies

### Actual behavior

Error saying video not found/video list is empty 

### Mihon/Tachiyomi version

Aniyomi preview r7507

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
We're not Aniyomi bro

**Comment by Bipolar708** [comment]
Yea I know but then the extension repository also functions in aniyomiㄟ(ツ)ㄏ........ the extension has a problem..... regardless off app

**Comment by Smol-Ame** [comment]
> Yea I know but then the extension repository also functions in aniyomiㄟ(ツ)ㄏ........ the extension has a problem..... regardless off app

It may function, but Keiyoushi doesn't have or support any anime extensions, that's all built into their app
