### ISSUE TITLE
YKMH shows HTTP 500

### ISSUE THREAD

**Issue by hsiayuchih** [keiyoushi/tachiyomi-extensions-source#1355]
### Source information

YKMH 1.4.28

### Source language

Chinese

### Steps to reproduce

![微信图片_20240218152458](https://github.com/keiyoushi/extensions-source/assets/21278771/0605127d-bb31-44c5-b898-b40d8a917f3f)

### Expected behavior

Can read manga normally.

### Actual behavior

http 500

### Mihon/Tachiyomi version

Mihon 0.16.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Doesn't happen now.
