### ISSUE TITLE
Pocket Comics的地区限制是怎么解除的？

### ISSUE THREAD

**Issue by FengTeLai** [keiyoushi/tachiyomi-extensions-source#136]
### Source name

Comico 1.4.5

### Source language

chinese

### Describe your suggested feature

它的部分作品在网页及APP端有IP和国家地区限制，请问大佬们是怎么在tachiyomi里解除这一限制的？

### Other details

因没有讨论区，只能在这个模板内提问了。

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
自行查看源码。
