### ISSUE TITLE
add manhuabaiku

### ISSUE THREAD

**Issue by FengTeLai** [keiyoushi/tachiyomi-extensions-source#1360]
### Source name

漫百库

### Source link

https://www.manhuabaiku.com/

### Source language

chinese

### Other details

This site is miaoshangmanhua's backup site, due to miaoshangmanhua server pressure, often Error code 522, so I would like to add this site to this plugin.
Note: PC web version can not be used normally, you need to go through the cell phone web terminal to work!

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Desktop site returns 404, mobile redirects to another site. The other site is covered by the extension named '包子漫画'.
