### ISSUE TITLE
Manhwatop : problem with downloading every last page

### ISSUE THREAD

**Issue by MrGoraj** [keiyoushi/tachiyomi-extensions-source#137]
### Source information

Manhwatop 1.4.34

### Source language

English

### Steps to reproduce

Just try download anything from Manhwatop.

In reading mode, it also fails to load the last page from within the app.

In WebView mode, everything loads correctly.

### Expected behavior

Completed download of all pages from chapter 

### Actual behavior

![Screenshot_20240111_075118_TachiyomiJ2K](https://github.com/keiyoushi/extensions-source/assets/32809530/da18e0e2-67b5-4785-bd8d-660420bd1bf0)

![Screenshot_20240111_080511_TachiyomiJ2K](https://github.com/keiyoushi/extensions-source/assets/32809530/1ace5298-65b7-4790-b1c1-a39c08992cff)

### Tachiyomi version

TachiyomiJ2K 1.7.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Could not reproduce on TachiyomiSY 1.10.0 and J2K 1.7.3, Return to Player Chapter 146.
