### ISSUE TITLE
UmeTruyen

### ISSUE THREAD

**Issue by jayqism** [keiyoushi/tachiyomi-extensions-source#1370]
### Source name

UmeTruyen

### Source link

https://umetruyenvip.com

### Source language

Vietnamese

### Other details

18+/NSFW = yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Theme is similar to ManhwaZ, at least according to the 404 page

**Comment by beer-psi** [comment]
Not really Madara, just a Madara clone. Same theme as ManhwaZ and SayHentai.
