### ISSUE TITLE
Error 404 Mangas no sekai and Manhua fenix

### ISSUE THREAD

**Issue by KatoMegushua** [keiyoushi/tachiyomi-extensions-source#1377]
### Source information

Manhua Fenix 1.4.38 and Mangas no Sekai 1.4.38

### Source language

Spanish

### Steps to reproduce

1 install
2 use

### Expected behavior

1 use source

### Actual behavior

1 "The source doesn't display anything."

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 13

### Other details

![Screenshot_20240218_145645_Mihon](https://github.com/keiyoushi/extensions-source/assets/145884813/be6dfbe5-6f6a-430d-9c08-fdc9cdf3782b)
![Screenshot_20240218_145638_Mihon](https://github.com/keiyoushi/extensions-source/assets/145884813/e3da55e8-bce3-41ad-8420-63b64aacb4da)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KatoMegushua** [comment]
What?

**Comment by vetleledaal** [comment]
> [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.

You ticked this, causing the bot to close the issue.
In any case, your issue will be addressed in #1365 and #1368
