### ISSUE TITLE
MangaLek : Problem after update

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#1389]
### Source information

MangaLek 1.4.38

### Source language

Arabic

### Steps to reproduce

1. I updated the source to the latest update today
2. Enter the source
3. After a period of time error (Couldflire)

### Expected behavior

The source should work without any problems. Note that the previous update worked without any problems

### Actual behavior

It should work without any problem (couldflire) because the problem was solved with the previous challenges. I would like to restore the previous version of the source, which has no problems.

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Duplicate of #1379
