### ISSUE TITLE
NicoManga

### ISSUE THREAD

**Issue by DchanN** [keiyoushi/tachiyomi-extensions-source#14]
### Source name

NicoManga

### Source link

https://nicomanga.com/

### Source language

Japanese - 日本語

### Other details

![image](https://github.com/keiyoushi/extensions-source/assets/101858971/969e8b6d-5e1b-444e-810c-cf4743e2f5a2)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by CodeSpoof** [comment]
I'm on it
