### ISSUE TITLE
BlackoutComic (pt) - thumbnail strange 

### ISSUE THREAD

**Issue by nomaxsnx** [keiyoushi/tachiyomi-extensions-source#1402]
### Source information

Blackout Comics - 1.4.1

### Source language

português 

### Steps to reproduce

1 - install the extension
2 - open

### Expected behavior

I can't post the image for this reason, you have to look at the extension

I can also be banned.

### Actual behavior

I can't post the image for this reason, you have to look at the extension

I can also be banned.

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 13

### Other details

I recommend that you be alone.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
![Screenshot_20240222_205845_Mihon.jpg](https://github.com/keiyoushi/extensions-source/assets/66540317/b9e1be9a-e83d-4572-90de-c4d09cfaf527)

This is what they see, added blur to remove the picture.
