### ISSUE TITLE
MangaGezgini not uptade

### ISSUE THREAD

**Issue by Thekages** [keiyoushi/tachiyomi-extensions-source#1404]
### Source information

Manga Gezgini 1.4.34

### Source language

Turkish

### Steps to reproduce

I am doing a global update. MangaGezgini's manga are not updated.MangaGezgini 
![Screenshot_20240219-183241_Tachiyomi](https://github.com/keiyoushi/extensions-source/assets/139270824/9e5ad446-ba50-4b1e-bc53-e0ed25110f0c)
does not update automatically. When I update it myself, it happens, but "NullPointerException: Null" appears at the bottom.

### Expected behavior

Manga is update

### Actual behavior

Manga is not update

### Mihon/Tachiyomi version

Tachiyomi App version: 0.15.3 

### Android version

Android 8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Same issue as #1397
