### ISSUE TITLE
Photos 18 problem?

### ISSUE THREAD

**Issue by devil6venom** [keiyoushi/tachiyomi-extensions-source#1408]
### Source information

Photos 18

### Source language

Multi

### Steps to reproduce

Well, Not working! Browsing mangas but bo thumbnail or chapters loading!

### Expected behavior

Should be able to browse picture 

### Actual behavior

Errors found.
The image couldn't be loaded!

### Mihon/Tachiyomi version

TachiYomisy

### Android version

Android 13

### Other details

![Screenshot_20240219-222812](https://github.com/keiyoushi/extensions-source/assets/92388530/352378e2-4cab-437b-88cc-a3ca0749be60)
![Screenshot_20240219-222814](https://github.com/keiyoushi/extensions-source/assets/92388530/49d226e2-b50b-45e3-bba8-141bbf7ee207)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
fixed in #1477
