### ISSUE TITLE
Happymh: images don't load

### ISSUE THREAD

**Issue by Wcraft233** [keiyoushi/tachiyomi-extensions-source#1409]
### Source information

Happymh 1.4.8

### Source language

Chinese

### Steps to reproduce

1. Open extension
2. Click any manhua
3. Read
4. Failed to load image
![Screenshot_2024-02-20-00-53-22-853_app mihon](https://github.com/keiyoushi/extensions-source/assets/30252123/267bf109-a814-4c7c-87f3-7147c0d0af73)

5. open on WebView
![Screenshot_2024-02-20-00-56-04-488_app mihon](https://github.com/keiyoushi/extensions-source/assets/30252123/499dc981-e0c1-4eca-9bce-de2382315c84)

### Expected behavior

Load images normally

### Actual behavior

Failed to load image

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 13

### Other details

#1396 does not fix #1181 as expected

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
The behavior is already reverted to the same as v1.4.6. If image still fails to load, you can't load it in v1.4.6 either. Wait for someone else to investigate.

**Comment by stevenyomi** [comment]
Try changing User Agent string in extension settings and solving Cf challenge in WebView.

**Comment by Wcraft233** [comment]
> Try changing User Agent string in extension settings and solving Cf challenge in WebView.

I tried to change the User Agent string in extension, restarted the software and passed the Cf challenge using WebView, but the software still could not load the image, even if I clicked the View in WebView button to display the image.

**Comment by Wcraft233** [comment]
After trying multiple network environments, I found one that could load images normally.

**Comment by RadStorm04** [comment]
> After trying multiple network environments, I found one that could load images normally.

Which one are you using? I can't seem to find one that's usable

**Comment by soon97** [comment]
I have the same question. I still can't load the picture after updating.
![Screenshot_2024-02-20-08-20-45-451_eu kanade tachiyomi](https://github.com/keiyoushi/extensions-source/assets/160553646/5e399cfd-7960-4370-b7b7-8130b65d2d20)

**Comment by Kxdiong** [comment]
change the User-Agent to 
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 QIHU 360ENT
or another UA from pc/windows, then restart and try again
hope this helps you, cheers!

**Comment by jackytsen** [comment]
> > After trying multiple network environments, I found one that could load images normally.
> 
> Which one are you using? I can't seem to find one that's usable

you can try
Mozilla/5.0 (Linux; Android 12; SM-F900U) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile

**Comment by Wcraft233** [comment]
> > After trying multiple network environments, I found one that could load images normally.
> 
> Which one are you using? I can't seem to find one that's usable

UA:Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36

I tried to use a network environment that worked fine before, but the image failed to load. Images can be loaded even when clicked to view using webview.

**Comment by Kxdiong** [comment]
> > > After trying multiple network environments, I found one that could load images normally.
> > 
> > 
> > Which one are you using? I can't seem to find one that's usable
> 
> UA:Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36
> 
> I tried to use a network environment that worked fine before, but the image failed to load. Images can be loaded even when clicked to view using webview.



> change the User-Agent to Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 QIHU 360ENT or another UA from pc/windows, then restart and try again hope this helps you, cheers!

**Comment by sao-coding** [comment]
@Wcraft233 

change the User-Agent to 

`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 QIHU 360ENT`

### **_This can indeed be used_**

**Comment by Wcraft233** [comment]
> @Wcraft233
> 
> change the User-Agent to
> 
> `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 QIHU 360ENT`
> 
> ### **_This can indeed be used_**

This UA is available.
