### ISSUE TITLE
Happymh嗨皮 problem

### ISSUE THREAD

**Issue by NeKoOuO** [keiyoushi/tachiyomi-extensions-source#141]
https://github.com/keiyoushi/extensions-source/issues/121#issue-2075128512 "Idiot bot closed my issue, but it should not have closed it's special one."

**Comment by beer-psi** [comment]
The bot may be dumb, but it was correct in closing your previous issue. We cannot help if Cloudflare passes in WebView, but does not pass in extension, that is still a Cloudflare issue.

Do not try to circumvent the bot by creating an issue not following any of the listed templates.
