### ISSUE TITLE
Scylla Scans (EN) broken parsing

### ISSUE THREAD

**Issue by Molnes** [keiyoushi/tachiyomi-extensions-source#1410]
### Source information

Scylla Scans 1.4.9

### Source language

English

### Steps to reproduce

1. Try to update library 

### Expected behavior

Update scylla scans

### Actual behavior

Received error:
! Unexpected JSON token at offset 11: Expected EOF after parsing, but had h instead at path: $
JSON input: <!DOCTYPE html>
<html>
<head>
<title>Welc.....
  # Scylla Scans (EN)
.......

### Mihon/Tachiyomi version

1.10.2 / 0.16.3

### Android version

Android 14

### Other details

Using TachiomySY 1.10.2
Still broke on mihon 0.16.3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Site is on maintenance
