### ISSUE TITLE
Alpha Manga official source

### ISSUE THREAD

**Issue by xavyc** [keiyoushi/tachiyomi-extensions-source#1415]
### Source name

Alpha Manga

### Source link

https://www.alpha-manga.com/

### Source language

English

### Other details

Official source, from the manga i'm reading there, the first 3 and last 3 seem free. (a la MangaPlus).

The only downside is that seem like the last 3 are only accessible via their app.

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
> The only downside is that seem like the last 3 are only accessible via their app.

Not worth it then
