### ISSUE TITLE
HentaiNexus, first page error for specific series

### ISSUE THREAD

**Issue by FallenInTheAbyss** [keiyoushi/tachiyomi-extensions-source#1418]
### Source information

HentaiNexus 1.4.8

### Source language

English

### Steps to reproduce

This issue is specifically happening when I try to download 3 certain chapter entries.

1. Search "Tales of a harem in another world"
2. Click on either the entry for chapter/volume 2, 3, or 4
3. Open the reader and wait for the first page to load
4. Hit the download option after exiting reader
![Screenshot_20240219_192414_Mihon](https://github.com/keiyoushi/extensions-source/assets/160549220/b2c765dc-c364-4629-a0be-70f0f33dca46)
![Screenshot_20240219_192218_Mihon](https://github.com/keiyoushi/extensions-source/assets/160549220/9dafa546-2977-4819-8abc-be292e35c54d)
![Screenshot_20240219_192230_Mihon](https://github.com/keiyoushi/extensions-source/assets/160549220/0cfeddc1-b8a6-428d-9fdd-9874b635eaa8)
![Screenshot_20240219_192443_Mihon](https://github.com/keiyoushi/extensions-source/assets/160549220/3f195b18-9b3f-490f-b1f7-0bb5f05e6b0e)

### Expected behavior

1. All of the pages should have loaded in
2. The full chapter should have been properly downloaded

### Actual behavior

1. The first page keep showing up as an error, asking for a reload or to open web view. The first page loads properly on web view however.
2. The chapter cannot complete the download due to this error.

![Screenshot_20240219_192243_Mihon](https://github.com/keiyoushi/extensions-source/assets/160549220/02744509-743a-4da6-8a50-4b156c7add4f)
![Screenshot_20240219_192847_Mihon](https://github.com/keiyoushi/extensions-source/assets/160549220/f1f5faa6-03bd-4a58-9426-80635716d3ab)
![Screenshot_20240219_192900_Mihon](https://github.com/keiyoushi/extensions-source/assets/160549220/ac7c80c2-cc9d-48f5-90d4-efbec7f24296)
![Screenshot_20240219_192907_Mihon](https://github.com/keiyoushi/extensions-source/assets/160549220/90ac9c0e-ad37-4aa5-831b-a10eaf2a7879)

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 14

### Other details

This seems to be happening to these specific chapters only, not to the recent uploads, it's pretty strange.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Working as expected for me. Was probably a transient issue present on the site.

If you are still experiencing this issue, please post the User-Agent you're using and what manga you're trying to read. Either here, or in a new issue if this issue gets locked before you get to it.
