### ISSUE TITLE
Add Mangatype

### ISSUE THREAD

**Issue by Pote38** [keiyoushi/tachiyomi-extensions-source#1419]
### Source name

Mangatype

### Source link

https://mangatype.com

### Source language

English

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by ChikaTempest** [comment]
up!

**Comment by fang3412** [comment]
Whoop, almost made a new post about this.

Going to throw out that this source has updated chapters beyond any other source I have come across for several manga. 
In my case 
Outcast is too good at martial arts, there's 20 more chapters than anywhere else 
Heir of mythical heroes also has about 20 more chapters

**Comment by vetleledaal** [comment]
As the site says, this is just redirecting to `newtoki***.com`. Use the "NewToki / ManaToki" extension instead.
If the search is broken in NewToki you can open an issue for that directly.
