### ISSUE TITLE
Sources contain errors  (cloudflare)

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#1421]
### Source information

MangaStarz 1.4.39

### Source language

Arabic

### Steps to reproduce

Open source error  (couldflire)

### Expected behavior

It must solve its own problem (Couldflire) Example of this source MangaLak

### Actual behavior

error (couldflire)

### Mihon/Tachiyomi version

Mihon 0.16.3

### Android version

Android 13

### Other details

I wonder if it is possible to add a manga source to other sources that have errors (Couldflire)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CactusTheGuy** [comment]
This is cloudflare problem

**Comment by ghost** [comment]
> This is cloudflare problem

Yes, it is a problem that exists in more than one source, but in the MangaLek source, it has been solved 

Other sources have the same problem and the formula is an example :
1- MangaLink
2- MangaLionz
3- MangaSpark
4- MangaStarz
5- MangaLek (The problem has been resolved)
