### ISSUE TITLE
NetTruyenCO (unoriginal)

### ISSUE THREAD

**Issue by Nyarunaa** [keiyoushi/tachiyomi-extensions-source#1423]
### Source information

Nettruyen 1.4.27

### Source language

Vietnamese

### Source new URL

https://nettruyenco.vn/

### Other details

Only https://nettruyenco.vn/ can read and works normally, this is also the real source

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by trungsamset0** [comment]
https://www.nettruyenbb.com/ is also a new one

**Comment by Nyarunaa** [comment]
> https://www.nettruyenbb.com/ is also a new one

but this one is fake, don't have so many manga and also Ad so much

**Comment by trungsamset0** [comment]
https://nettruyenco.vn/ is not the offical source

**Comment by trungsamset0** [comment]
> > https://www.nettruyenbb.com/ is also a new one
> 
> but this one is fake, don't have so many manga and also Ad so much

The one u sent was the one with ads, the one i sent didnt

**Comment by Nyarunaa** [comment]
hmmm, I see, https://www.nettruyenbb.com/ is better

**Comment by trungsamset0** [comment]
https://www.facebook.com/share/p/WdHFLF99rs948ara/?mibextid=qi2Omg
You can get the official and read more about this situation
