### ISSUE TITLE
NetTruyen URL changes

### ISSUE THREAD

**Issue by trungsamset0** [keiyoushi/tachiyomi-extensions-source#1424]
### Source information

NetTruyen 1.4.27

### Source language

Vietnamese

### Source new URL

https://www.nettruyenbb.com/

### Other details

https://nettruyenco.vn/ is a fake site 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by AccelDragnel** [comment]
It's true, the old Nettruyen source has been changed "https://www.nettruyenbb.com/".
