### ISSUE TITLE
App crashes when trying to change 'Sort'

### ISSUE THREAD

**Issue by dapoktan** [keiyoushi/tachiyomi-extensions-source#1428]
### Source information

NewToki/ManaToki

### Source language

Korean

### Steps to reproduce

Open 'Filter', click 'Sort',  change sorting to one of the options: "기본(날짜순)" "인기순" "추천순" "업데이트순", and the app crashes.

this happens in mihon, tachi, and various other forks i have tested.

[mihon_crash_logs.txt](https://github.com/keiyoushi/extensions-source/files/14346955/mihon_crash_logs.txt)

### Expected behavior

should sort the manga to the selected choice, whether it be date, popularity, follows, or updated date.. 

### Actual behavior

crashes and shows crash report, giving options to restart application

[mihon_crash_logs.txt](https://github.com/keiyoushi/extensions-source/files/14346936/mihon_crash_logs.txt)

### Mihon/Tachiyomi version

0.16.3

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
A log that actually has useful info

[mihon_crash_logs(4).txt](https://github.com/keiyoushi/extensions-source/files/14347225/mihon_crash_logs.4.txt)
