### ISSUE TITLE
PotatoManga : No results found

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#1429]
### Source information

PotatoManga 1.4.30

### Source language

Arabic

### Steps to reproduce

1- Open source
2- No results found

### Expected behavior

The results should appear

### Actual behavior

Results did not appear

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 13

### Other details

![Screenshot_٢٠٢٤٠٢٢٠-١٨١١٥٧](https://github.com/keiyoushi/extensions-source/assets/159192815/88bb0f77-306c-4288-b4df-c77becc4e918)
![Screenshot_٢٠٢٤٠٢٢٠-١٨١٢١٩](https://github.com/keiyoushi/extensions-source/assets/159192815/446fda4b-be16-4af0-98b3-e236d685bfd6)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
Seems source is down (https://ar.potatomanga.xyz)
