### ISSUE TITLE
Can't download 

### ISSUE THREAD

**Issue by danixlolo** [keiyoushi/tachiyomi-extensions-source#143]
### Source information

MangaSee 1.4.35

### Source language

English 

### Steps to reproduce

1. Trying to download MangaSee
2. Gets the downloading window
3. Doesn't download to the app

### Expected behavior

MangaSee is downloaded 

### Actual behavior

Doesn't download 

### Tachiyomi version

Stable 0.15.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Uninstall the extension before updating. If that does not work, uninstall it from your device's settings by navigating to your device's Settings -> Apps and uninstall it from there by looking for `Tachiyomi: <extension name>`.

This is usually caused your previous extension having a different signature from the updated extension, making Android refuse to update it.
