### ISSUE TITLE
Mangas no Sekai 

### ISSUE THREAD

**Issue by KatoMegushua** [keiyoushi/tachiyomi-extensions-source#1435]
### Source information

Mangas No Sekai 1.4.41

### Source language

Spanish

### Steps to reproduce

Install and use

### Expected behavior

Use and view

### Actual behavior

When opening a title, it displays a message that there are no chapters, this happens with all titles from the source.

In the search, it shows the same titles over and over again.

### Mihon/Tachiyomi version

0.16.3

### Android version

13

### Other details

![Screenshot_20240220_115831_Mihon](https://github.com/keiyoushi/extensions-source/assets/145884813/d9667ca8-7c3f-4abf-8a3d-39018a6082de)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
update your extension
