### ISSUE TITLE
Mangas no Sekai no ID manga

### ISSUE THREAD

**Issue by AleixLopez17** [keiyoushi/tachiyomi-extensions-source#1439]
### Source information

Mangas No Sekai 1.4.42

### Source language

Spanish

### Steps to reproduce

1. Abrir cualquier manga
2. Recargar pagina
3. No actualiza el manga
![Screenshot_2024-02-20-20-45-12-685_eu kanade tachiyomi](https://github.com/keiyoushi/extensions-source/assets/79077041/37dd8946-e83e-454a-9a4d-a05bc53c5669)
![Screenshot_2024-02-20-20-45-22-727_eu kanade tachiyomi](https://github.com/keiyoushi/extensions-source/assets/79077041/0c1e88a3-00b1-434d-859b-4e198eaa4c33)

### Expected behavior

Actualizas el manga y salen los nuevos capitulos

### Actual behavior

Actualizas el manga y te salta un error de id que no genera los capitulos nuevos

### Mihon/Tachiyomi version

Tachiyomi 0.15.3

### Android version

Android 13

### Other details

Aparte de no actualizar los capitulos, el apartado de mangas recientes no se actualiza igual que el del WebView

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KatoMegushua** [comment]
"I have the same issue. The manga ID couldn't be obtained."
