### ISSUE TITLE
Cannot install extension

### ISSUE THREAD

**Issue by Shikuro165** [keiyoushi/tachiyomi-extensions-source#1441]
### Source information

Hentaivn 1.4.31

### Source language

vi

### Steps to reproduce

1. Search extension "hentaivn"
2. Click install

### Expected behavior

This should install extension like normal 

### Actual behavior

Instead, it just show "could not install extension"

### Mihon/Tachiyomi version

J2K v1.7.4

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Did you try uninstalling the extension before installing it again? If you're moving from the official extension it will fail to install due to different signatures. If you want a more descriptive error you can try using the [Split APK Installer](https://play.google.com/store/apps/details?id=com.aefyr.sai).

**Comment by Shikuro165** [comment]
yeah, I can install it now, thank you so much

> Did you try uninstalling the extension before installing it again? If you're moving from the official extension it will fail to install due to different signatures. If you want a more descriptive error you can try using the [Split APK Installer](https://play.google.com/store/apps/details?id=com.aefyr.sai).
