### ISSUE TITLE
New Story Reading Page for Vietnamese People "Kho Truyen"

### ISSUE THREAD

**Issue by tuanbmt4152** [keiyoushi/tachiyomi-extensions-source#1453]
### Source name

Kho Truyen

### Source link

https://khotruyen.cc/

### Source language

Vietnamese "Vi"

### Other details

New Story Reading Page for Vietnamese People "[Kho Truyen](https://khotruyen.cc/)"

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by mohamedotaku** [comment]
Use Madara theme

**Comment by beer-psi** [comment]
Fake Madara again...

**Comment by Norsze** [comment]
my bad, sorry

**Comment by Karutovn** [comment]
> ### Source name
> 
> Kho Truyen
> 
> ### Source link
> 
> https://khotruyen.cc/
> 
> ### Source language
> 
> Vietnamese "Vi"
> 
> ### Other details
> 
> New Story Reading Page for Vietnamese People "[Kho Truyen](https://khotruyen.cc/)"
> 
> ### Acknowledgements
> 
> - [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
> - [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> - [X] I have written a meaningful title with the source name.
> - [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
> - [X] I will fill out all of the requested information in this form.

Pls update source link (linksource error)

**Comment by tuanbmt4152** [comment]
Source link : [https://khotruyen.club/](url)
