### ISSUE TITLE
Issue with new chapters for rizz comic

### ISSUE THREAD

**Issue by ManiV97** [keiyoushi/tachiyomi-extensions-source#1455]
### Source information

Rizz comic 1.4.3

### Source language

English

### Steps to reproduce

Error in updating the new chapters in rizz comics.

When the manhwa are been updated no new chapters are being updated.

The error is showing as follows: 
"JsonDecodingException: Expected start of the array '[', but had 'EOF' instead at path: $

JSON input:"
![Screenshot_20240221_200704](https://github.com/keiyoushi/extensions-source/assets/143166150/1c1c312e-e640-4c55-8aae-9e64c64aeef8)

### Expected behavior

New Chapters are updated when as manhwa are reload to check for new chapters, as they are shown in the webview of manhwa.
![Screenshot_20240221_200730](https://github.com/keiyoushi/extensions-source/assets/143166150/10e902f1-9a02-4c1c-985f-307451a0f599)

### Actual behavior

No new chapters are been updated when reload the manhwa.

### Mihon/Tachiyomi version

Tachiyomi 0.15.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
Update your extension

**Comment by ManiV97** [comment]
> Update your extension

Extension has been updated, it was a mistake written before, it was already updated to v1.4.3.

The problem remains the same.
![Screenshot_20240221_203844](https://github.com/keiyoushi/extensions-source/assets/143166150/1c792ad7-280e-4742-a9e8-17384ef84e88)

**Comment by AwkwardPeak7** [comment]
still outdated https://keiyoushi.github.io/extensions/#en.rizzcomic
