### ISSUE TITLE
NhatTruyen Extension change URL

### ISSUE THREAD

**Issue by QuangTKD** [keiyoushi/tachiyomi-extensions-source#1473]
### Source information

NhatTruyen v1.4.17

### Source language

Vietnamese

### Source new URL

https://nhattruyens.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
The current domain is still working. Did they announce they were moving somewhere?

**Comment by QuangTKD** [comment]
> The current domain is still working. Did they announce they were moving somewhere?

![image](https://github.com/keiyoushi/extensions-source/assets/38491090/c7a31eac-ed22-426e-b07c-812f98fc19df)

Yes on discord and their facebook fanpage announcde  to change domain since 20-Feb

**Comment by vetleledaal** [comment]
I could not find the fanpage you were talking about. In any case, it seems like https://nhattruyenup.com is the correct URL.

It looks like you're being blocked from accessing the site, have you tried enabling DoH or use a VPN? The troubleshooting guide has more details.
