### ISSUE TITLE
Iqiyi has changed URL

### ISSUE THREAD

**Issue by hsiayuchih** [keiyoushi/tachiyomi-extensions-source#1474]
### Source information

Iqiyi 1.4.2

### Source language

Chinese

### Source new URL

https://manhua.iqiyi.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by mohamedotaku** [comment]
the url  https://www.iqiyi.com/manhua  still work normally

**Comment by hsiayuchih** [comment]
> the url https://www.iqiyi.com/manhua still work normally

But the extension doesn't work.Browsing with webview reveals that the domain automatically jumps to the **https://manhua.iqiyi.com/**
![Screenshot_20240224_102812_Mihon](https://github.com/keiyoushi/extensions-source/assets/21278771/6d6d9ebf-eb40-4212-b07b-7c92e699889c)

**Comment by anenasa** [comment]
https://www.iqiyi.com/manhua works fine for me. Please make sure you are using a desktop user agent, not a mobile one.

**Comment by hsiayuchih** [comment]
> https://www.iqiyi.com/manhua works fine for me. Please make sure you are using a desktop user agent, not a mobile one.

~Does using desktop user agent affect the use of other extensions? Also what desktop user agent do I need to set up? Any recommendations? Thanks!~
