### ISSUE TITLE
Episodes do not appear in the "https://asurascans.com.tr/" extension

### ISSUE THREAD

**Issue by Bastankara** [keiyoushi/tachiyomi-extensions-source#1485]
### Source name

sections are not visible

### Source link

https://asurascans.com.tr/

### Source language

Turkish

### Other details

The sections do not appear on the website I provided on the mihon application.

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Read the status updates next time, migrate from Asura Scans (Turkish) to Armoni Scans.

**Comment by Bastankara** [comment]
thank you and sorry for not seeing it is my first time using "github"

**Comment by Bastankara** [comment]
> Read the status updates next time, migrate from Asura Scans (Turkish) to Armoni Scans.

thank you and sorry for not seeing it is my first time using "github"
