### ISSUE TITLE
Yomu Mangás HTTP 404

### ISSUE THREAD

**Issue by JosephShay** [keiyoushi/tachiyomi-extensions-source#1488]
### Source information

Yomu Mangás 1.4.3

### Source language

Brazilian Portuguese

### Steps to reproduce

1: Confirmed that the website's webview is working correctly.
2: Extension updated according to keiyoushi list standards.
3: Investigate persistent HTTP error occurring in the last 2 days in the extension

### Expected behavior

As long as the webview is operational and the extension is in compliance with Keiyoushi standards, it is presumed to be functional.

### Actual behavior

the webview works, but the extension, even when updated, stopped working somehow.

### Mihon/Tachiyomi version

Tachiyomi Stable 0.15.3

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by GMak9** [comment]
This problem still persists. 
It seems to me to be the same "issue": #2878
Maybe it's the same issue solved in the commit: #3139 WebView Block. But, when you click on open WebView the site works normally, so I suppose it will be another cloudflare protection mechanism.

**Comment by choppeh** [comment]
This source is no longer available
