### ISSUE TITLE
opscans url change

### ISSUE THREAD

**Issue by t0xicP0w3r** [keiyoushi/tachiyomi-extensions-source#149]
### Source information

1.4.27

### Source language

Multiple

### Source new URL

https://opchapters.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by NeKoOuO** [comment]
你確定這個來源存在嗎? 我在en區找不到

**Comment by C0rvidae** [comment]
There's literally no manga on the website as of right now, so this is untestable

**Comment by t0xicP0w3r** [comment]
> There's literally no manga on the website as of right now, so this is untestable

When i first opened the issue there were the three manga that they were translating, but yeah i also cant see nothing now

**Comment by t0xicP0w3r** [comment]
> There's literally no manga on the website as of right now, so this is untestable

Should i close the issue and open a new one when it'll be solved, or should i leave it open?
