### ISSUE TITLE
Webtoon Hatti: Last page issue

### ISSUE THREAD

**Issue by Rip0000** [keiyoushi/tachiyomi-extensions-source#1491]
### Source information

Webtoon hatti

### Source language

turkish

### Steps to reproduce

lastpage not downloaded

### Expected behavior

lastpage not downloaded

### Actual behavior

lastpage not downloaded

### Mihon/Tachiyomi version

0.15.3

### Android version

android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
![image](https://github.com/keiyoushi/extensions-source/assets/10671518/760f4a8d-cdcd-4874-9c9b-2e850ac18ce3)

They deliberately put fake images

**Comment by Rip0000** [comment]
Is there anything we can do to solve this or can I do?

**Comment by MikeZeDev** [comment]
Website owner keep changing stuff to mess with mihon and hakuneko. As a user you cant do anything.

**Comment by Rip0000** [comment]
I understand thank you for the answer

**Comment by choppeh** [comment]
I couldn't reproduce this problem, perhaps it was solved in #3281

**Comment by Smol-Ame** [comment]
If you encounter this issue again, make a new request & put the names of the entries doing this
