### ISSUE TITLE
Add Extension CrotPedia 

### ISSUE THREAD

**Issue by Fauzy-Rahadian** [keiyoushi/tachiyomi-extensions-source#1517]
### Source name

CrotPedia

### Source link

https://158.220.106.212/

### Source language

Indonesia

### Other details

18+/NSFW = YES

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by 0Ha16wA5** [comment]
Related to #1116, but different URL

**Comment by Fauzy-Rahadian** [comment]
> Terkait dengan #1116 , tetapi URL berbeda

that's the newest URL, can you add this to the extension?

**Comment by TheKingTermux** [comment]
As far as I remember, the Tachiyomi Extension does not allow creating applications with an IP Address because of some Security Reason, so if you provide a URL in the form of an IP Address, it might be rejected

**Comment by stevenyomi** [comment]
Duplicate of #1116
