### ISSUE TITLE
Manhua plus NXDOMAIN

### ISSUE THREAD

**Issue by taos15** [keiyoushi/tachiyomi-extensions-source#1524]
### Source information

Manhua plus 1.4.41

### Source language

English

### Steps to reproduce

Refresh a manga using that source

### Expected behavior

When refetching or updating a manga it will get the lastest episodes from the source

### Actual behavior

It fails to fetxh with a error `Couldnt reach manhuaplus.com:NXDOMAIN`
![Screenshot_20240224_014226_Mihon](https://github.com/keiyoushi/extensions-source/assets/122130728/4f4ae12d-8322-4349-8e9e-0e4c62831b39)

### Mihon/Tachiyomi version

App version: 0.16.3-6520 (standard, 840b647b4, 4, 2024-02-17T21:13Z) Android version: 14 (SDK 34; build UP1A.231005.007.S908USQS4DXB1) Device brand: samsung Device manufacturer: samsung Device name: b0q (b0qsqw) Device model: SM-S908U WebView: Android System WebView 121.0.6167.178

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Pretty sure Manhua Plus is currently down (look in WebView or go to their site in your browser), please wait for them to bring themselves back online, or migrate to another source for now.

**Comment by taos15** [comment]
> Pretty sure Manhua Plus is currently down (look in WebView or go to their site in your browser), please wait for them to bring themselves back online, or migrate to another source for now.

Webview loads for me
![Screenshot_20240224_015121_Mihon](https://github.com/keiyoushi/extensions-source/assets/122130728/420bfa9d-b6c6-4051-adcf-fd47e0a87417)

**Comment by Smol-Ame** [comment]
Could be cached/one of the only working pages, doesn't load on my end & https://downforeveryoneorjustme.com/manhuaplus.com says it's down too
