### ISSUE TITLE
MintManga extension doesnt save webview sign-in info

### ISSUE THREAD

**Issue by RoskoDaneworth** [keiyoushi/tachiyomi-extensions-source#1527]
### Source information

MintManga 1.4.68

### Source language

Russian

### Steps to reproduce

Trying to search for 18+ titles on MintManga (like "What happens inside the dungeon" manhwa), app says i need authorization in webview, do the sign-in into my account, info doesnt save and search query still asking for authorization.

### Expected behavior

After webview sign-in account details should be saved

### Actual behavior

After webview sign-in account details are not saved

### Mihon/Tachiyomi version

16.3

### Android version

12

### Other details

Other extensions (ReadManga, MangaLib, ReManga, etc) save webview info as normal, no problems there.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by e-shl** [comment]
Which domain is used?
![Screenshot_2024-03-02-12-10-39-98_5901a79de973a50c74cff4cbb6149856.jpg](https://github.com/keiyoushi/extensions-source/assets/35057681/63908264-6bfb-4d3c-abb2-5d13e7ca7232)

**Comment by RoskoDaneworth** [comment]
> Which domain is used? 

https://1.mintmanga.one/ is the right one for the site.

**Comment by e-shl** [comment]
> What happens inside the dungeon

![Screenshot_2024-03-07-19-01-13-21_5901a79de973a50c74cff4cbb6149856.jpg](https://github.com/keiyoushi/extensions-source/assets/35057681/a03b30a6-16b8-426c-b32b-01ab83e1283d)

![Screenshot_2024-03-07-19-01-08-60_5901a79de973a50c74cff4cbb6149856.jpg](https://github.com/keiyoushi/extensions-source/assets/35057681/821050b7-bbbf-4be2-97c4-e5a5f8524798)

**Comment by RoskoDaneworth** [comment]
I changed domain manually to 2.mintmanga.one (it changed recently) and now it is working.
For some reasons the basic domain in extension was "mintmanga.com" and so it didnt save webview.
I think this issue can be closed now.
