### ISSUE TITLE
Fontes não atualizam

### ISSUE THREAD

**Issue by Nika0202** [keiyoushi/tachiyomi-extensions-source#1528]
### Source name

https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json

### Source language

Português/Inglês/Espanhol

### Describe your suggested feature

Nenhuma das fontes atualizam, sempre dá erro. Tenho 78 fontes que se recusam a atualizar, em português, espanhol e inglês. Gostaria que corrigisem isso, por gentileza. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by l2eused** [comment]
Is package that you already installed from official repo before? if yes, you could uninstall it and install all again.
> This problem is because different signature package and your phone denied it to update

[Get Start](https://keiyoushi.github.io/docs/guides/getting-started#adding-the-extension-repo)
> Before you start - Uninstall all existing extensions. You will not get extension updates otherwise.

**Comment by AwkwardPeak7** [comment]
if you need help come to our discord server
