### ISSUE TITLE
Dynasty-scans cover not loading

### ISSUE THREAD

**Issue by Chiro-kun** [keiyoushi/tachiyomi-extensions-source#153]
### Source information

Dynasty-scans 1.4.22

### Source language

English

### Steps to reproduce

1. Open dynasty-scans extension
2. Covers are not loading

https://github.com/keiyoushi/extensions-source/assets/57830288/3d3eccc5-069b-425e-94b5-9a885f15e5c6

### Expected behavior

Covers should load in the homepage too

### Actual behavior

Covers are not loading

### Tachiyomi version

Preview r6404

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
This is a known issue - Dynasty Scans do not provide covers on the search page, which we're scraping from: https://dynasty-scans.com/search?q=&classes%5B%5D=Series&sort=
