### ISSUE TITLE
Extension site update 

### ISSUE THREAD

**Issue by commoner-dev** [keiyoushi/tachiyomi-extensions-source#1533]
### Source information

Manhuaplus 1.4.41

### Source language

English

### Steps to reproduce

1:Extension manhua e.g martial peak
2: refresh to update 
3: (issue) it either shows null or no chapters
![Screenshot_20240225-014742](https://github.com/keiyoushi/extensions-source/assets/53960061/8ee28de1-6c84-44a2-ac0d-916386b9d9a6)

### Expected behavior

Should update chapters

### Actual behavior

Shows error

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 8

### Other details

Pls update manhuaplus(.com) to manhuaplus(.org) as the issue is with the site updating it's name and if possible provide method to manually edit extensions our(my)selves since a simple issue like this can be solved if source editing was added.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
ManhuaPlus is currently down/broken, please wait for a fix or migrate to a different source
