### ISSUE TITLE
Mangaswat domain changed 

### ISSUE THREAD

**Issue by 7allom** [keiyoushi/tachiyomi-extensions-source#1536]
### Source information

Mangaswat 1.4.42

### Source language

Arabic

### Source new URL

https://swatmanhua.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by 7allom** [comment]
How?
I downloaded it from the official website

**Comment by beer-psi** [comment]
> How? I downloaded it from the official website

The latest version is 1.4.44.
