### ISSUE TITLE
Manga Demon No Chapters Found in Tachiyomi

### ISSUE THREAD

**Issue by Kenn876** [keiyoushi/tachiyomi-extensions-source#1544]
### Source information

Manga Demon 1.4.8

### Source language

English 

### Steps to reproduce

1. Go to Sources
2. Press Manga Demon
3. Pick a manga or manhwa
4. It will say "No Chapters Found"

### Expected behavior

It should show the list of chapters

### Actual behavior

Instead it says "No Chapters Found". Even if you reload, or clear the cache, webview data, or the cookies.
![Screenshot_20240226_032212](https://github.com/keiyoushi/extensions-source/assets/137243023/a27419c7-c41d-4e37-8f28-a9510612a92b)

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ManiV97** [comment]
Manga demon has changed it's source to "https://demontoon.com"
