### ISSUE TITLE
Manhua Plus not showing any manhua

### ISSUE THREAD

**Issue by meldy6223** [keiyoushi/tachiyomi-extensions-source#1548]
### Source information

Manhus Plus 1.4.41

### Source language

English

### Steps to reproduce

1. Go to the browse page
2. Click on the extension
3. It shows a no result found page
4. Open in Webview and the website is open with no issues

### Expected behavior

It should show a list of manhua available from the source

### Actual behavior

It shows a no result found page

### Mihon/Tachiyomi version

TachiJ2K 1.7.4

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by devil6venom** [comment]
Use another source, unofficial!!

**Comment by devil6venom** [comment]
Its because of domain changed! Already there is unofficial version which is redirect of official! Use that!

**Comment by meldy6223** [comment]
Alright thanks a lot for the solution. It is working now. Appreciate the help.
