### ISSUE TITLE
Manhua plus is not working properly

### ISSUE THREAD

**Issue by InzamamulQureshi** [keiyoushi/tachiyomi-extensions-source#1554]
### Source information

Manhua plus v1.4.41

### Source language

English 

### Steps to reproduce

Open manhua plus extension, It will not work, it will show no results found

### Expected behavior

It should list all available manhua

### Actual behavior

It gives error "No results found"

### Mihon/Tachiyomi version

Tachiyomi 0.15.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Stop opening new requests and read what the bot tells you. The Discord server has a status update message about it since yesterday. Also, if you had searched through the GitHub issues, you would see there's been multiple issue reports about this source. They are currently down/broken, wait for a fix or migrate to the other Manhua Plus extension.

**Comment by vetleledaal** [comment]
#1548
