### ISSUE TITLE
Images appear twice in MajorScans

### ISSUE THREAD

**Issue by Thekages** [keiyoushi/tachiyomi-extensions-source#1558]
### Source information

MajorScans 1.4.28

### Source language

Turkish

### Steps to reproduce

1 enters the chapte 2 Images appear twice in a row

### Expected behavior

Each image must appear once.

### Actual behavior

each image appears twice

### Mihon/Tachiyomi version

Mihon 0.16.3

### Android version

Android 8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
Its probably because images are twice in the page: inside and outside a noscript tag
