### ISSUE TITLE
Comico missing in extension search result

### ISSUE THREAD

**Issue by Anutrix** [keiyoushi/tachiyomi-extensions-source#1559]
### Source information

Extension name: Comico (lang: all; package: eu.kanade.tachiyomi.extension.all.comico) Extension version: 1.4.5 (lib: 1.4; version code: 5) NSFW: true  Update available: false Obsolete: false Shared: true Repository: null 

### Source language

All

### Steps to reproduce

1. Go to extension search(Browse -> Extension).
2. Search for Comico.
3. Notice it's missing in search result on the app but present on the website.

### Expected behavior

Comico should appear in search results inside the app.

### Actual behavior

Comico is missing in app only.
![Screenshot_20240226-184535_Mihon](https://github.com/keiyoushi/extensions-source/assets/11459028/ffd6f408-21a1-4731-87a6-09fee91d6a5f)
![Screenshot_20240226-184826_Firefox](https://github.com/keiyoushi/extensions-source/assets/11459028/b7930375-31e0-4724-b964-36bc8b7cd134)

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 14

### Other details

Couldn't find other extensions with this issue. Others might exist.
Not sure if it's app issue since there's only one extension with the issue.

Let me know if want me to close this.

For now I downloaded the apk from the website.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
check your 18+ filter in app settings

**Comment by Anutrix** [comment]
![Screenshot_20240228-102142_Mihon](https://github.com/keiyoushi/extensions-source/assets/11459028/42dc32e5-8ad0-4c15-af61-ffc342c0f61d)

Is there some setting other than this? Also, many other sources with same flag show in extension search results show up fine.

**Comment by Norsze** [comment]
Comico is a **multi** source, enable multi in the filter settings found in the overflow menu (the three dots) when in the extension list.

**Comment by Anutrix** [comment]
![Screenshot_20240228-103244_Mihon](https://github.com/keiyoushi/extensions-source/assets/11459028/9ac19460-f0ad-4d43-a244-bb3a37d8d2d5)

**Comment by Anutrix** [comment]
Can you reopen this? @AwkwardPeak7

**Comment by Smol-Ame** [comment]
> ![Screenshot_20240228-103244_Mihon](https://private-user-images.githubusercontent.com/11459028/308426662-9ac19460-f0ad-4d43-a244-bb3a37d8d2d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNDQ0MjQsIm5iZiI6MTcwOTI0NDEyNCwicGF0aCI6Ii8xMTQ1OTAyOC8zMDg0MjY2NjItOWFjMTk0NjAtZjBhZC00ZDQzLWEyNDQtYmIzYTM3ZDhkMmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDIyMDIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZjA4YjQwMTA5ZDBjNzE2Zjk5ODdiZjE5OTM3ZTQyZTM2OGMzMzk0OGViNTFkODBhN2NlMDQ4Yjk3ODQ0MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cv2FtQvR0Q3EIkgt7zAeXKOdaifYBUcLOpU93Es4ZQk)

Did you also enable Multi in your Sources list?

**Comment by Anutrix** [comment]
> > ![Screenshot_20240228-103244_Mihon](https://private-user-images.githubusercontent.com/11459028/308426662-9ac19460-f0ad-4d43-a244-bb3a37d8d2d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNDQ0MjQsIm5iZiI6MTcwOTI0NDEyNCwicGF0aCI6Ii8xMTQ1OTAyOC8zMDg0MjY2NjItOWFjMTk0NjAtZjBhZC00ZDQzLWEyNDQtYmIzYTM3ZDhkMmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDIyMDIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZjA4YjQwMTA5ZDBjNzE2Zjk5ODdiZjE5OTM3ZTQyZTM2OGMzMzk0OGViNTFkODBhN2NlMDQ4Yjk3ODQ0MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cv2FtQvR0Q3EIkgt7zAeXKOdaifYBUcLOpU93Es4ZQk)
> 
> Did you also enable Multi in your Sources list?

https://github.com/keiyoushi/extensions-source/issues/1559#issuecomment-1968235436

**Comment by Smol-Ame** [comment]
I see what's going on. Enable Japanese in your Extensions list, then Comico will show up

**Comment by Smol-Ame** [comment]
Sorry for another ping everyone, or search up Pocket Comics for the English one to show up

Comico / コミコ is a catch-all name on the website

**Comment by Anutrix** [comment]
@Smol-Ame Thx for the help. Your observations are correct. Comico appears when we enable Japanese filter too. And I can find it as Pocket Comics in Multi.

But since it's still called Comico in Multi section, during and in after install search results.
I was kinda expecting same name to work during pre-install search:
![Screenshot_20240301-035559_Package_installer](https://github.com/keiyoushi/extensions-source/assets/11459028/3b1ee8c2-ef0f-45a4-bca8-c8324b0ae026)
So feels like a bug...
Not sure which repo though.....
