### ISSUE TITLE
No result found Epsilon scan

### ISSUE THREAD

**Issue by WoodlyBasquin56** [keiyoushi/tachiyomi-extensions-source#1563]
### Source information

Epsilon Scan 1.4.28

### Source language

French

### Steps to reproduce

1.It works when you enter the WebView
 2. As soon as you try to access it through the Mihon application it says "No result Found"

### Expected behavior

It worked a few days ago

### Actual behavior

No result
![Screenshot_20240226-155153](https://github.com/keiyoushi/extensions-source/assets/73551993/47bf7bc9-4987-4917-b55f-37cbc0b1399b)
 found

### Mihon/Tachiyomi version

Mihon Beta r6530

### Android version

Android 13

### Other details

![Screenshot_20240226-155153](https://github.com/keiyoushi/extensions-source/assets/73551993/e94dc384-8229-432b-8033-a82658b9947e)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by WoodlyBasquin56** [comment]
@KirinRaikage Tu peux résoudre le problème s'il te plaît

**Comment by KirinRaikage** [comment]
@WoodlyBasquin56 Le site semble complétement pété.
The website doesn't have any images while loading the site itself.
You can close the issue and reopen if you notice that the original site has images/chapters back.

**Comment by KirinRaikage** [comment]
Never mind, it may be a WebView thing. 
Website loads images fine through Chrome, but not through Firefox, from my tests.

**Comment by WoodlyBasquin56** [comment]
@KirinRaikage Il a peut-être changé de nom et d'URL qui sait

**Comment by WoodlyBasquin56** [comment]
@KirinRaikage pourquoi on a toujours accès alors

**Comment by KirinRaikage** [comment]
Non non...
