### ISSUE TITLE
Kemono's extension doesn't show all the content of the web(s)

### ISSUE THREAD

**Issue by lalalasupa0** [keiyoushi/tachiyomi-extensions-source#1565]
### Source information

Kemono 1.4.10

### Source language

All

### Steps to reproduce

Open entrie in kemono (artist's profile)

### Expected behavior

Should show all its "chapters" (only those that have images, ofc)

### Actual behavior

It skips some

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 12

### Other details

I'm having this experience right now with hxd9585's profile in Kemono, for example, the "chapter" _12月 (1)_ is on the website but it doesn't come up in the extension, and has images, ofc

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
check extension settings for number of chapters loaded.

**Comment by lalalasupa0** [comment]
> check extension settings for number of chapters loaded.

It's not that!!
I already checked it, some "chapters" simply don't appear even with the settings in maximum posts
*I forgot to mention that

Can u open this now or sum, idk

**Comment by Norsze** [comment]
For clarity, which 12月1 are you talking about? Give the date(year) of the upload, there are multiple 12月1 as it only indicates that it's the first upload in the month of December.

**Comment by lalalasupa0** [comment]
> For clarity, which 12月1 are you talking about? Give the date(year) of the upload, there are multiple 12月1 as it only indicates that it's the first upload in the month of December.

There may be several on the web with that same name, but the point is that the extension does not show them all
The one I'm talking bout Is the actually very first one in that artist's profile, _12月 (1)_, with the "( )", date: "published: 2020-12-11 00:35:18" & "imported: 2020-12"
Actually, no "chapter" from that year appears in the extension but it does appear on the web, and they do have images
