### ISSUE TITLE
Plz add Arya Scans

### ISSUE THREAD

**Issue by sovit042** [keiyoushi/tachiyomi-extensions-source#1573]
### Source name

Arya Scans

### Source link

https://aryascans.com

### Source language

English

### Other details

NSFW = NO

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by sovit042** [comment]
Bro is there someone who can make a extension of this site plz .

**Comment by sovit042** [comment]
😶

**Comment by stevenyomi** [comment]
@sovit042 Stop bumping issues or you'll be blocked.

**Comment by sovit042** [comment]
@stevenyomi what do u mean by bumping?

**Comment by stevenyomi** [comment]
> what do u mean by bumping?

https://www.google.com/search?q=bump+thread

This is the last warning. Another meaningless reply then you'll be blocked.
