### ISSUE TITLE
Manga demon not updating

### ISSUE THREAD

**Issue by InzamamulQureshi** [keiyoushi/tachiyomi-extensions-source#1577]
### Source information

Manga demon v1.4.8

### Source language

English

### Steps to reproduce

Go to extensions, you will see manga demon extension update, try updating it

### Expected behavior

After clicking on update it should update normally

### Actual behavior

The update fails

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 14

### Other details

The extension is not updating

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
https://demoncomics.org/ redirects to https://demontoon.com/ , which is down. Do you know if they moved elsewhere?

**Comment by InzamamulQureshi** [comment]
https://demontoon.com/ is working just fine for me

**Comment by vetleledaal** [comment]
My bad. DNS was acting up. I can see it's online now.

**Comment by ankithdev21** [comment]
Have the same issue.

**Comment by aeron-leeding** [comment]
I have the same issue

To break it down the thumbnails for a small list (not any om the actual main webpage) of manga populate but when clicked on do not present any chapters 

The Web view does work and redirects to demontoon.com

**Comment by AwkwardPeak7** [comment]
for extension update issue: uninstall existing extension and reinstall. Rest of the comments aren't related to the issue content.
