### ISSUE TITLE
Lolivault 

### ISSUE THREAD

**Issue by Doro-kun2112** [keiyoushi/tachiyomi-extensions-source#1588]
### Source name

Fuente de lolivault 

### Source link

https://lector.lolivault.net

### Source language

Español

### Other details

+18/NSFW: YES

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Doro-kun2112** [comment]
Empecé a leer los doujin de lolivault en pc con el programa "fmd" y descargue tachiyomi con la intención de terminar de ver todo el contenido que me faltaba xd, y como nunca añadieron la extensión me tocó pedirla xd

**Comment by LetrixZ** [comment]
No creo que tenga sentido agregarla ya que no parece que vayan a subir nuevo contenido.

**Comment by Doro-kun2112** [comment]
No creo que vuelvan a actualizar la página, pero sería bueno contar con la
página y su contenido, llevo esperando a ver si agregan la página 3 años xd
y me gustaría poder verla en tachiyomi 🐱

**Comment by Doro-kun2112** [comment]
Thank you, it was the best birthday gift you gave me this year 😸🥳
