### ISSUE TITLE
Extension update 

### ISSUE THREAD

**Issue by Hanimeniac23** [keiyoushi/tachiyomi-extensions-source#1591]
### Source information

flixscans.org

### Source language

English

### Steps to reproduce

Cant open in normal view

### Expected behavior

The extension expected to open in normal view but can't.

### Actual behavior

This is what happened the the extension open "Couldn't reach Unable to resolve host "api.flixscans.org": No address associated with hostname"

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 12 

### Other details

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by devil6venom** [comment]
Working fine on mine! Check your wifi or user agent data! Its browsing fine on mine!

**Comment by Norsze** [comment]
Works fine for me too, follow devil6venom's suggestions, change your WiFi, DNS or [user agent](https://keiyoushi.github.io/docs/guides/troubleshooting#changing-your-user-agent), alternatively use a VPN. Your error suggests your network is the issue, not the extension.
