### ISSUE TITLE
Komiksan

### ISSUE THREAD

**Issue by Aruhiii** [keiyoushi/tachiyomi-extensions-source#1597]
### Source information

Komiksan 1.4.30

### Source language

Bahasa Indonesia 

### Steps to reproduce

results not found, you can read it in webview

### Expected behavior

I hope this bug can be fixed

### Actual behavior

results not found

### Mihon/Tachiyomi version

TachiyomiSY 

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [ ] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Aruhiii** [comment]
what should I do again and say thank you?

**Comment by TheKingTermux** [comment]
>> what should I do again and say thank you?

> - [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.

Just uncheck this, and re-open this issue, In the future, don't ever check that option and properly read the acknowledgements carefully
