### ISSUE TITLE
Asura Scans timeout on library update

### ISSUE THREAD

**Issue by hirata-estate** [keiyoushi/tachiyomi-extensions-source#1598]
### Source information

Asura Scans 1.4.29

### Source language

English 

### Steps to reproduce

1. Have a library with a lot of entries from Asura.
2. Update the library.

Issue seems to happen after the 13th entry.
(I have 63 from Asura, 50 of them fail)

![Screenshot_20240229-005257_Microsoft 365 (Office)~2](https://github.com/keiyoushi/extensions-source/assets/61897277/f2dd8275-4789-4290-94b4-ef36ba5db248)

### Expected behavior

Entries all update without issue.

### Actual behavior

Entries do not update and an error spits out.

### Mihon/Tachiyomi version

Tachiyomi 0.15.3 & Mihon 0.16.4

### Android version

Android 14

### Other details

Have tried resetting cookies and webview, and changing my user agent string to no avail.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Not an extension issue, they're doing maintenance, go look in WebView or go to their site to see this.
