### ISSUE TITLE
Webtoon on batoto are distorterted

### ISSUE THREAD

**Issue by Illythia** [keiyoushi/tachiyomi-extensions-source#1602]
### Source information

bato.to 1.4.35

### Source language

English

### Steps to reproduce

Go to library
Open webtoon from Batoto
Click on chapter
Chapter loads

### Expected behavior
Images should load and align properly 
Images
![Screenshot_2024-02-29-01-11-19-34_76d0f6352040d5ab219b0498c33ac39d](https://github.com/keiyoushi/extensions-source/assets/129698114/2092b52d-de65-46d2-b01d-091eddbb55d2)
![Screenshot_2024-02-29-01-11-37-68_76d0f6352040d5ab219b0498c33ac39d](https://github.com/keiyoushi/extensions-source/assets/129698114/03387641-ffc8-49dc-aef1-07c2f04a5ed3)
![Screenshot_2024-02-29-01-12-47-84_76d0f6352040d5ab219b0498c33ac39d](https://github.com/keiyoushi/extensions-source/assets/129698114/10919670-ca03-4c87-9161-e401912d2afd)
![Screenshot_2024-02-29-01-13-10-70_76d0f6352040d5ab219b0498c33ac39d](https://github.com/keiyoushi/extensions-source/assets/129698114/9671dfce-6833-4325-b275-fd751fcc4094)

### Actual behavior

Image isn't aligned properly.

### Mihon/Tachiyomi version

Beta r6530

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [ ] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
How appropriate, next time confirm with the Discord that it's an actual bug and not just user error. Disable the crop the little icon in the bottom middle right.

**Comment by Illythia** [comment]
> How appropriate, next time confirm with the Discord that it's an actual bug and not just user error. Disable the crop the little icon in the bottom middle right.

Thank you so much! So dumb of me to never notice that. I doesn't do that on other sources because I have it disabled but didn't know that was what was doing it. It didn't do that on other version.
