### ISSUE TITLE
Kumanga strange behaviour (Normal in Webview)

### ISSUE THREAD

**Issue by V0lms** [keiyoushi/tachiyomi-extensions-source#1606]
### Source information

kumanga 1.4.9

### Source language

Spanish 

### Steps to reproduce

Open extension
Open one manga
Wait

https://github.com/keiyoushi/extensions-source/assets/101695647/4e15f663-553e-4a3b-87b8-99dec71566e6

### Expected behavior

Have a normal picture and update the content 

### Actual behavior

Spear a strange picture and don't update the number of chapters 

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
I see that the cover is incorrect, but what is the problem with the chapters?

**Comment by V0lms** [comment]
Sorry, I have forgotten to show that it doesn't update the chapter 
![kumangaError1](https://github.com/keiyoushi/extensions-source/assets/101695647/4fd8128a-a8c6-484b-b75c-d88a30d9af4e) 
![kumangaError2](https://github.com/keiyoushi/extensions-source/assets/101695647/29c16f5a-697c-4d8f-9f93-dce5c5371c95)

**Comment by bapeey** [comment]
I tested it and the chapter update works fine, consider that the page only shows 10 chapters per page, which means that the extension has to go through 369 pages to fetch the chapters, which may take a while.

**Comment by V0lms** [comment]
Okay the chapters update sorry for that.
And what happens with the cover?

**Comment by bapeey** [comment]
@V0lms Can you confirm if the thumbnail problem is fixed? It seems that the page changed something and it no longer happens, update your manga manually to update the cover

**Comment by V0lms** [comment]
> @V0lms Can you confirm if the thumbnail problem is fixed? It seems that the page changed something and it no longer happens, update your manga manually to update the cover

Yes, now the cover is good
