### ISSUE TITLE
Asura Scans

### ISSUE THREAD

**Issue by TofuuSoGood** [keiyoushi/tachiyomi-extensions-source#1611]
### Source information

Asura Scans 1.4.29

### Source language

English

### Source new URL

https://asuratoon.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by TofuuSoGood** [comment]
whenever i try opening asura scans on open web it's directing to the old url, I can't even read anything from the said extension

**Comment by Norsze** [comment]
Wait until DNS network issues resolve, will maybe take a day
