### ISSUE TITLE
Asura Scans - APK use still Asura Comics 

### ISSUE THREAD

**Issue by Sam4000der2** [keiyoushi/tachiyomi-extensions-source#1612]
### Source information

1.4.29

### Source language

English

### Source new URL

https://asuratoon.net

### Other details

Supposedly the APK already uses Asuratoon, but it still uses Asuracomics (the old URL). 

The old URL is still unavailable, the new one has long been online again. 

Please check whether the APK was built with the correct source code and whether the old URL is still contained in the code.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Wait for DNS issues to resolve, be patient, the domain used in the extension is correct, the app has just cached the DNS from earlier, it should get resolved by itself when the old DNS timeouts
