### ISSUE TITLE
Asura Scans URL change

### ISSUE THREAD

**Issue by Th4tguy1995** [keiyoushi/tachiyomi-extensions-source#1615]
### Source information

Asura Scans  1.4.29

### Source language

English

### Source new URL

https://asura-scans.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
This is a new copycat aggregator site it seems like. Not the real Asura website. Asura jas their group page on every upload, this one just has aggregated stuff from everywhere

**Comment by Norsze** [comment]
Probably best to open a new issue as a **source request** as this is **_not_** a domain change or a bug for the real Asura source
