### ISSUE TITLE
Asura scans nullpointer 

### ISSUE THREAD

**Issue by BerenOneHand** [keiyoushi/tachiyomi-extensions-source#1621]
### Source information

Asura scans 1.4. 29

### Source language

English 

### Steps to reproduce

1. Update an asura scans item
2. Exception thrown

1. Browse asura scans popular
2. Open item not in library
3. Null pointer exception 

### Expected behavior

Chapters should be updated

### Actual behavior

Exception happens

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
Migrate from Asura to Asura if the problem persists
