### ISSUE TITLE
Anchira: trending filter overrides text search

### ISSUE THREAD

**Issue by stevenyomi** [keiyoushi/tachiyomi-extensions-source#1622]
See https://github.com/keiyoushi/extensions-source/pull/1522#pullrequestreview-1900843186

**Comment by LetrixZ** [comment]
Reminder that unless you're logged in, which will get you banned if using the extension, the search won't work.

**Comment by stevenyomi** [comment]
@LetrixZ I was just recording a PR review. Let me know if this is meaningless, so I could close this issue.

**Comment by MediocreLegion** [comment]
@LetrixZ actually that's wrong, I was using search without issues (and without having an account) until the update broke it. Now it's being overwritten most of the times by the trending filter (searching the artist name still works for some reason).

**Comment by MediocreLegion** [comment]
Correction, it seems like they changed some stuff without saying in their changelog. After a bit of testing, all that's needed is adding `title:` or `tag:` to the beginning of the query.

**Comment by LetrixZ** [comment]
> Correction, it seems like they changed some stuff without saying in their changelog. After a bit of testing, all that's needed is adding `title:` or `tag:` to the beginning of the query.

It should be back to normal now

**Comment by Norsze** [comment]
Source down and dead due to DMCA
