### ISSUE TITLE
Madokami: Thumbnails don't load in browse

### ISSUE THREAD

**Issue by mikitakahazekura** [keiyoushi/tachiyomi-extensions-source#163]
### Source information

Madokami 1.4.8

### Source language

English

### Steps to reproduce

1. Go to the Madokami source.
2. Notice thumbnails don't load.

### Expected behavior

Thumbnails load

### Actual behavior

Thumbnails don't load

### Tachiyomi version

0.15.2

### Android version

Android 14

### Other details

If you access a particular title (open manually at least one time), the thumbnail will load. Only thumbnails of titles whose list of chapters you access will load. Thumbnails are loading on Tachiyomi J2K 1.7.3.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
I believe this is intended behavior, unless https://manga.madokami.al/recent contains manga thumbnails.
