### ISSUE TITLE
Scylla Scans API has been deleted/moved

### ISSUE THREAD

**Issue by mothquits** [keiyoushi/tachiyomi-extensions-source#1630]
### Source information

Scylla Scans 1.4.9

### Source language

English

### Steps to reproduce

1. Add Scylla Scans Extension
2. Select Scylla Scans source
3. Unable to resolve host api.scyllascans.org

### Expected behavior

I should be able to search or update as normal.

### Actual behavior

api.scyllascans.org stopped existing around 2/8/24 leaving the extension non functional.

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 12

### Other details

Placed as bug rather than changed URL because I could find a new API link.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
Website doesnt answer anyway

**Comment by mothquits** [comment]
Just checked and it seems like they took the API down and the site down a week later do to some issues. They seeming plan to get both in a functioning state again.
