### ISSUE TITLE
Add Re Manga (Arabic) back

### ISSUE THREAD

**Issue by DemonEmperor1** [keiyoushi/tachiyomi-extensions-source#1635]
### Source name

Re Manga

### Source link

https://re-manga.com/

### Source language

Arabic 

### Other details
Why was it deleted? The source is still working
![Screenshot_٢٠٢٤٠٣٠١-١٧١٨٢٥_Mihon](https://github.com/keiyoushi/extensions-source/assets/161745216/a8603512-0aa3-41d7-8c4f-f37537ed1bde)

_No response_

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Keep using it if it works for you

**Comment by stevenyomi** [comment]
Re-Manga (Arabic) is added back under the changed package name `ar.remangaarabic`, so you need to uninstall and reinstall the extension to receive further updates. No migration is needed.
