### ISSUE TITLE
Lura Toon - HTTP 404. (AGAIN)

### ISSUE THREAD

**Issue by nomaxsnx** [keiyoushi/tachiyomi-extensions-source#1639]
### Source information

Lura Toon 1.4.42

### Source language

Português 

### Steps to reproduce

1 install extension
2 Open extension
3 wait now

### Expected behavior

![Screenshot_2024-03-01-16-56-58-660_app mihon](https://github.com/keiyoushi/extensions-source/assets/157644160/ee4a657d-c2a8-4f1d-810d-94576be84ab6)

### Actual behavior

404

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
cannot reproduce, open a new issue if issue occurs again
