### ISSUE TITLE
Animated Glitched Comics chapters not updating

### ISSUE THREAD

**Issue by xhugo92** [keiyoushi/tachiyomi-extensions-source#1640]
### Source information

Animated Glitched Comics 1.4.28

### Source language

English

### Steps to reproduce

1. Go to recent 
2. Try updating the chapters

### Expected behavior

Show the news chapters that apear in the front page 

### Actual behavior

Only show old chapters

### Mihon/Tachiyomi version

Mihon 0.16.4

### Android version

Android 13

### Other details

I already tried cleaning the cache from webview, mihon and chrome 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AnshumanSarkar2001** [comment]
Chapters are not update in the page of the comic due to which it's not updating. You can compare it with recent page and the manga page.

**Comment by AwkwardPeak7** [comment]
closing as this issue is on their site
