### ISSUE TITLE
No result found

### ISSUE THREAD

**Issue by ChikaTempest** [keiyoushi/tachiyomi-extensions-source#1659]
### Source information

Manhwa Freak 1.4.32

### Source language

English

### Steps to reproduce

Can't view in the extension page. No result found.
Can't add the manhwa
![Screenshot_20240302-203033_TachiyomiJ2K](https://github.com/keiyoushi/extensions-source/assets/105035665/1ff3e355-1ff0-4a10-99f4-efebca31e4ec)
![Screenshot_20240302-203240_TachiyomiJ2K](https://github.com/keiyoushi/extensions-source/assets/105035665/a20d8392-a829-47b1-abd4-bee3c3a25c63)

### Expected behavior

Can open the extension 
Can see the extension
Can add the manhwa in to the favorite

### Actual behavior

The view on the extension page should show the manhwa or manga that can be add to the library

### Mihon/Tachiyomi version

Mihon 0.16.4

### Android version

Android 11

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
duplicate of #1648
