### ISSUE TITLE
Manga1000: can't find manga page

### ISSUE THREAD

**Issue by rafiq017** [keiyoushi/tachiyomi-extensions-source#1664]
### Source information

Manga1000 1.4.11

### Source language

Japanese 

### Steps to reproduce

I can't open the chapter of Aoki Hagane no Arpeggio in Tachiyomi even though there's no Chapta or anything that is blocked in the webview. I tried randomly selecting another series but the problem is still the same. Tried troubleshooting the app clearing the cache, changing DNS, still not working. But when I open with the webview I can open the page like normally the website does. I think there's a problem with the extension.

### Expected behavior

Normally getting page from the website and can download the page.

### Actual behavior

Can't open the chapter and/or even download any page from it.

### Mihon/Tachiyomi version

App version: 0.15.3 (standard, a9c7cbf, 119, 2024-01-13T19:03Z) Stable

### Android version

Android 12

### Other details

![Screenshot_2024-03-03-01-48-30-40_99c04817c0de5652397fc8b56c3b3817](https://github.com/keiyoushi/extensions-source/assets/38656924/3abdc971-f87e-4931-95e4-d917ece5e59c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Seems like an issue with the site. When testing Aoki Hagane no Arpeggio I get an error on chapter 150, same as with WebView. Chapter 155 works fine in both the app and WebView.

Do you have a specific example where the same chapter works in WebView but not in the app?

**Comment by AwkwardPeak7** [comment]
closing in favor of #4233
