### ISSUE TITLE
They changed the website

### ISSUE THREAD

**Issue by MidKnight1512** [keiyoushi/tachiyomi-extensions-source#1665]
### Source information

Manhwa Freak 1.4.32

### Source language

English 

### Source new URL

https://freakcomic.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by MidKnight1512** [comment]
Hello but the site has now shifted to freakcomic.com and mihon is not updating the changes but if i go to webview then it loads perfectly

**Comment by Smol-Ame** [comment]
> Hello but the site has now shifted to freakcomic.com and mihon is not updating the changes but if i go to webview then it loads perfectly

Read the bot response, your issue is a duplicate of #1648 and there's a contributor working on it (see #1655 & #1660).

Next time search the issues before opening one & checking acknowledgements without doing so.
