### ISSUE TITLE
Toonkor BaseUrl change 

### ISSUE THREAD

**Issue by NeKoOuO** [keiyoushi/tachiyomi-extensions-source#1670]
### Source information

Toonkor 1.4.4

### Source language

Korean 

### Source new URL

https://toonkor340.com

### Other details

Url release from 
툰코 TOONKOR
https://t.me/new_toonkor

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
I will close this one as #1671 seems more relevant since you can change base URL
