### ISSUE TITLE
Toonkor can't use even I change to the right domain 

### ISSUE THREAD

**Issue by NeKoOuO** [keiyoushi/tachiyomi-extensions-source#1671]
### Source information

Toonkor 1.4.4

### Source language

Korean 

### Steps to reproduce

Webview still working so I'm sure it not website problem 
![Screenshot_2024-03-03-16-55-08-696_eu kanade tachiyomi sy](https://github.com/keiyoushi/extensions-source/assets/111511925/cfde82a8-a3df-407f-b43c-13168b99e465)
![Screenshot_2024-03-03-16-55-21-905_eu kanade tachiyomi sy](https://github.com/keiyoushi/extensions-source/assets/111511925/e79646dd-227c-438e-9ca4-8e407bef190e)

### Expected behavior

It should be loaded 

### Actual behavior

No matter how long I wait, nothing will load
![Screenshot_2024-03-03-16-55-01-419_eu kanade tachiyomi sy](https://github.com/keiyoushi/extensions-source/assets/111511925/04cb5514-7189-4fe7-8493-1ea5190e8511)

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Can you try letting it load for a while? I had to let it load for almost 2 minutes before it loaded the content.

**Comment by Norsze** [comment]
Well the extension seems to work, albeit very slow, which is more the fault of the source, so I am marking this as not planned, as everything works as good as it could

**Comment by NeKoOuO** [comment]
> Well the extension seems to work, albeit very slow, which is more the fault of the source, so I am marking this as not planned, as everything works as good as it could

Okay...
