### ISSUE TITLE
Roumanwu URL changed

### ISSUE THREAD

**Issue by strumgeistxu** [keiyoushi/tachiyomi-extensions-source#1676]
### Source information

zh.roumanwu 1.4.7

### Source language

Chinese 

### Source new URL

https://roum12.xyz

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by NeKoOuO** [comment]
This website has two domain
https://rouman5.com
https://roum12.xyz
but this extension both of the domain options are https://roum10.xyz

**Comment by lisansas** [comment]
> This website has two domain https://rouman5.com https://roum12.xyz but this extension both of the domain options are https://roum10.xyz

Exactly, I found this too

**Comment by NeKoOuO** [comment]
Have you encountered a situation where you cannot load images in the app and 401 is displayed, but the webview can still be used normally?
https://github.com/keiyoushi/extensions-source/issues/1824#issuecomment-1994192124
