### ISSUE TITLE
MangaPlus missing German support making all other languages crash

### ISSUE THREAD

**Issue by Migue28** [keiyoushi/tachiyomi-extensions-source#1680]
### Source information

MANGA Plus by SHUEISHA  1.4.50

### Source language

All languages

### Steps to reproduce

All language can be selected too.
<img src="https://github.com/keiyoushi/extensions-source/assets/17736149/75986307-66d7-41c4-91eb-e51d22b3e119" width="200">

Enter MANGA Plus by SHUEISHA source and search something, can be a character.
<img src="https://github.com/keiyoushi/extensions-source/assets/17736149/0c69cf01-6c46-425d-9904-d7943d502264" width="200">

It shows that German is missing, but German is not an option in available languages.
<img src="https://github.com/keiyoushi/extensions-source/assets/17736149/13266854-9ac6-42dc-8684-291529b9f309" width="200">

### Expected behavior

Should show manga results instead of error.

### Actual behavior

Does not show any results:
```SerializationException: eu.kanade.tachiyomi.extension.all.mangaplus.Language does not contain element with name 'GERMAN' at path $.success.titleRankingViewV2.rankedTitles[37].titles[5].language  ```
![1709481514269](https://github.com/keiyoushi/extensions-source/assets/17736149/506ba5f5-c2bf-46b4-8721-2602454aaeaa)

### Mihon/Tachiyomi version

Mihon 0.16.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Sayan8910** [comment]
Same problem,
