### ISSUE TITLE
Photos18 The image couldn't be loaded

### ISSUE THREAD

**Issue by Lanuras** [keiyoushi/tachiyomi-extensions-source#1699]
### Source information

Photos18 1.4.2

### Source language

Multi

### Steps to reproduce

Step 1: Install as usual
Step 2: Choose any entry
Issue here 1: Open a chapter to read
Issue here 2: Download Chapter
![Screenshot_2024-03-04-07-38-55-02_551f7f0ca926862b368845ce7ee433aa](https://github.com/keiyoushi/extensions-source/assets/116725459/b77b9939-fb80-41b6-8cdc-4a87d9bdafa8)

### Expected behavior

Image should load like with other sources.
Example using "Comick (ENG)":

![Screenshot_2024-03-04-07-24-09-44_551f7f0ca926862b368845ce7ee433aa](https://github.com/keiyoushi/extensions-source/assets/116725459/fb3d6169-6883-4d77-823c-f8069cc8ab20)

### Actual behavior

Issue here 1: Image did not load inside the reader

Issue here 2: Chapter download does not progress

### Mihon/Tachiyomi version

0.16.4 (stable)

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by devil6venom** [comment]
Working fine on me.  Kindly check dns and user agent setting! Or reinstall extension!
![Screenshot_20240304-144720](https://github.com/keiyoushi/extensions-source/assets/92388530/957696c2-40b6-44aa-8b85-5886307a71f9)

**Comment by Lanuras** [comment]
> Working fine on me.  Kindly check dns and user agent setting! Or reinstall extension!

Thank you for your help!
What DNS settings and agent are you using? I reinstalled the extension and already switched the agent I'm using, but the DNS setting was disabled entirely. I tried Cloudfare but that did not work for me.
