### ISSUE TITLE
java.lang.NullPointerException when trying to download a chapter

### ISSUE THREAD

**Issue by Zerlaxv1** [keiyoushi/tachiyomi-extensions-source#1701]
### Source information

MangaFire 1.4.4

### Source language

All (FR in this case)

### Steps to reproduce

Try to download One Piece colored ch. 231
https://mangafire.to/manga/one-piece-digital-colored-comics.06w3

### Expected behavior

Chapter download complete

### Actual behavior

The download is stuck at 18/19

### Mihon/Tachiyomi version

TachiyomiJ2K 1.7.4 / Mihon 16.3

### Android version

14

### Other details

![Screenshot_20240304_174040_TachiyomiJ2K](https://github.com/keiyoushi/extensions-source/assets/62764982/d7001d99-ff94-4581-b410-ae6f474ff0d3)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Site issue, some pages are broken
