### ISSUE TITLE
Project request: Auto update extension

### ISSUE THREAD

**Issue by Elixtra** [keiyoushi/tachiyomi-extensions-source#1705]
### Describe why this should be added

Adding auto-updating extensions to Keiyoushi is crucial for several reasons:

1. User Convenience: Auto-updating extensions ensure that Keiyoushi users always have the latest features and improvements without manual effort. This enhances user satisfaction and provides a seamless experience.

2. Security Measures: Automatic updates promptly address security vulnerabilities, reducing the risk of breaches. This is essential for safeguarding user data and maintaining the integrity of the Keiyoushi platform.

3. Efficient Development: Automation streamlines the update process, allowing the Keiyoushi development team to focus on innovation and improving the software rather than managing individual updates manually.

4. Stay Competitive: In the dynamic software landscape, staying up-to-date is crucial for competitiveness. Auto-updating extensions enable Keiyoushi to adapt to evolving technology standards, ensuring it remains relevant and competitive.

5. Bug Fixes: Automatic updates quickly address any bugs or issues, contributing to a more stable and reliable Keiyoushi platform. This, in turn, enhances the overall user experience.

In summary, incorporating auto-updating extensions in Keiyoushi is essential for user satisfaction, security, efficient development, competitiveness, and maintaining a reliable software platform.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
This is something the app needs to implement. 

Also plz don't use chatGPT to write issues
