### ISSUE TITLE
Shinigami URL change

### ISSUE THREAD

**Issue by WEPOXS** [keiyoushi/tachiyomi-extensions-source#1708]
### Source information

Shinigami 1.4.53

### Source language

Indonesia

### Source new URL

https://shinigami.cx/

### Other details

![Screenshot_20240305_121922_Mihon](https://github.com/keiyoushi/extensions-source/assets/146017577/b6cc5c7c-83cd-45ac-845c-733da15835f8)
![Screenshot_20240305_121929_Mihon](https://github.com/keiyoushi/extensions-source/assets/146017577/62119801-55f2-431b-bcb5-82e1161f2da6)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by WEPOXS** [comment]
and can you add this too? 
https://github.com/keiyoushi/extensions-source/issues/1552#issue-2153227634

**Comment by vetleledaal** [comment]
The extension is already using that domain. Your images also indicate that it is working as expected.

**Comment by WEPOXS** [comment]
> The extension is already using that domain. Your images also indicate that it is working as expected.

why is it a black screen when opening in web view??
![Screenshot_20240308_101326_Mihon.jpg](https://github.com/keiyoushi/extensions-source/assets/146017577/97cc0312-681b-49e1-80bd-f338989f862a)

![Screenshot_20240308_101333_Mihon.jpg](https://github.com/keiyoushi/extensions-source/assets/146017577/5d4776ae-d813-4552-8c1f-ef6b74ea00ce)

![Screenshot_20240308_101505_Chrome.jpg](https://github.com/keiyoushi/extensions-source/assets/146017577/7fbd66cc-8f71-40b6-af26-b75cb3bc4dc0)

**Comment by vetleledaal** [comment]
Make sure you follow the [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/). The first two sections are relevant for your case.

**Comment by WEPOXS** [comment]
> Make sure you follow the [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/). The first two sections are relevant for your case.

Alrght sir
