### ISSUE TITLE
NetTruyen URL change

### ISSUE THREAD

**Issue by Ailfree** [keiyoushi/tachiyomi-extensions-source#1711]
### Source information

NetTruyen 1.4.28

### Source language

Vietnamese

### Source new URL

https://www.nettruyenkk.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Taki132** [comment]
Giờ đợi bên admin chấp nhận request là oke th nhé 🤡

**Comment by QuangTKD** [comment]
> Giờ đợi bên admin chấp nhận request là oke th nhé bro 🤡

Có thể giúp tôi NhatTruyen nữa được không ? [NhatTruyen Extension change URL #1473
](url)

**Comment by AccelDragnel** [comment]
The FB page confirmed, is not "https://www.nettruyenkk.com", the official site is "https://www.nettruyenee.com"
