### ISSUE TITLE
Mangadex not working

### ISSUE THREAD

**Issue by tbartsch1** [keiyoushi/tachiyomi-extensions-source#1712]
### Source information

Mangadex 1.4.192

### Source language

Multi language

### Steps to reproduce

1. Open mangadex source

### Expected behavior

Should load anda show the manga from mangadex

### Actual behavior

Nothing loads

### Mihon/Tachiyomi version

Aniyomi R7509

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
???
Seems to work fine for me

**Comment by AwkwardPeak7** [comment]
cannot reproduce, make soure your network isn't blocking the site.

If you need further help, come to our discord
