### ISSUE TITLE
Remove the Following Sources

### ISSUE THREAD

**Issue by devil6venom** [keiyoushi/tachiyomi-extensions-source#1725]
### Source name

MangaNelo

### Source language

English

### Source link

https://manganelo.biz/

### Other details

There are 3 ext with same name but all 3 are down!

Manganelo.biz
Manganelo.website
Manganelos.com
![Screenshot_20240306-091340](https://github.com/keiyoushi/extensions-source/assets/92388530/ae2870c6-f565-4d04-b22c-918b8b10fea8)
![Screenshot_20240306-091324](https://github.com/keiyoushi/extensions-source/assets/92388530/19f6bd8e-b5c2-4502-989c-e0a8bd9098c2)
![Screenshot_20240306-091318](https://github.com/keiyoushi/extensions-source/assets/92388530/9d472caf-a64a-49f6-aaa2-132777e2ff9f)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by kissinglucifer** [comment]
actually just a url change
new url is https://m.manganelo.com
![Screenshot_20240311-132539](https://github.com/keiyoushi/extensions-source/assets/70305334/ac0ff336-2842-42e1-a72f-e31ce379b804)

**Comment by SoraAki000** [comment]
> actually just a url change
> new url is https://m.manganelo.com
> ![Screenshot_20240311-132539](https://github.com/keiyoushi/extensions-source/assets/70305334/ac0ff336-2842-42e1-a72f-e31ce379b804)
> 
> 

ERM... Manganelo is not related with mentioned sources, just for you to know...
