### ISSUE TITLE
manhwalist rebranded to komiknesia

### ISSUE THREAD

**Issue by WEPOXS** [keiyoushi/tachiyomi-extensions-source#1726]
### Source name

Komiknesia

### Source link

https://komiknesia.xyz

### Source language

Indonesia

### Other details

Nsfw/+18 = no
This is a new domain manhwalist (manhwalist.xyz) change to komiknesia.xyz
And rename manhwalist to komiknesia

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by mohamedotaku** [comment]
This is two requests in one issue "add hizanami" and "delete manhwalist"

**Comment by WEPOXS** [comment]
> This is two requests in one issue "add hizanami" and "delete manhwalist" 

Not deleted, but rather replaced

**Comment by WEPOXS** [comment]
> This is two requests in one issue "add hizanami" and "delete manhwalist" 

Manhwalist is change to hizanami and mybe this label domain change not sourch request, mybe

**Comment by MikeZeDev** [comment]
hizanami.xyz

![image](https://github.com/keiyoushi/extensions-source/assets/10671518/2270f632-95a7-4451-bceb-c0bd21f21fe7)

**Comment by WEPOXS** [comment]
> hizanami.xyz
> 
> ![image](https://github.com/keiyoushi/extensions-source/assets/10671518/2270f632-95a7-4451-bceb-c0bd21f21fe7)
> 

Is it under repair, or adding mybe features?

**Comment by WEPOXS** [comment]
Update url to komiknesia.xyz

**Comment by WEPOXS** [comment]
> hizanami.xyz
> 
> ![image](https://github.com/keiyoushi/extensions-source/assets/10671518/2270f632-95a7-4451-bceb-c0bd21f21fe7)
> 

So..

**Comment by WEPOXS** [comment]
> This is two requests in one issue "add hizanami" and "delete manhwalist" 

so..? when will you pull request this? 
please 🫠
