### ISSUE TITLE
Ar extension listed as all

### ISSUE THREAD

**Issue by MRmustafa478** [keiyoushi/tachiyomi-extensions-source#1740]
### Source information

Thunder scans 1.4.30

### Source language

Arabic 

### Steps to reproduce

This extension is Arabic in language
But it's listed as all
Causing confusion for who looking for it
Making a multiple requests for adding it under label source request 
And also the bot don't recognize this
![Screenshot_2024-03-06-20-41-09-88_4641ebc0df1485bf6b47ebd018b5ee76](https://github.com/keiyoushi/extensions-source/assets/97904728/e2cd1034-4ea4-40b8-aca0-2e9c1021a8e2)

### Expected behavior

I should be listed as ar

### Actual behavior

It's listed as all
![Screenshot_2024-03-06-20-55-24-46_4641ebc0df1485bf6b47ebd018b5ee76](https://github.com/keiyoushi/extensions-source/assets/97904728/e88348cc-b693-4906-b6fd-85542461286e)

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 12

### Other details

I add this request as a small contributer

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
it is under All or Multi section because it has english and arabic versions.
