### ISSUE TITLE
Westmanga Null Pointer

### ISSUE THREAD

**Issue by CrazyGamerIE** [keiyoushi/tachiyomi-extensions-source#1742]
### Source information

Westmanga 1.4.33

### Source language

Indonesia

### Steps to reproduce

Updated 2 times still got bug

### Expected behavior

After refreshing in comic 

### Actual behavior

I got Null Pointer, sorry i dont really know how to report using this web:')

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 13

### Other details

![Screenshot_20240307-030431_Mihon](https://github.com/keiyoushi/extensions-source/assets/43118487/3f2bb32a-5ec7-4b84-8f11-18a9a0cb6e50)
![Screenshot_20240307-030450_Mihon](https://github.com/keiyoushi/extensions-source/assets/43118487/f33c57b3-fe68-4cd9-860c-4b26f1dd5b43)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
duplicate https://github.com/keiyoushi/extensions-source/issues/1719
