### ISSUE TITLE
Sushi-scan ne marche pas.

### ISSUE THREAD

**Issue by Guts055** [keiyoushi/tachiyomi-extensions-source#1745]
### Source information

Sushi-Scan 1.4.41

### Source language

French

### Steps to reproduce

Je rentre dans l'application et je pars dans la source sushiscan mais elle n'affiche pas le contenu, elle se charge comme à l'infini 

### Expected behavior

Normalement la source doit afficher le contenu 

### Actual behavior

Elle ne l'affiche pas,elle charge à l'infini sans arrêt .
J'ai vérifié su c'était la connexion mais 
![Screenshot_2024-03-06-23-51-27-934_app mihon](https://github.com/keiyoushi/extensions-source/assets/162513812/620cc4f9-3acb-44a0-955c-cb287be425b4)
c'est pas le cas

### Mihon/Tachiyomi version

Michon 0.16.4

### Android version

Version 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Ouvre SushiScan en WebView et tu devrais avoir un message de blocage. 
Y'a rien qui puisse être fait à propos de ça.

**Comment by Guts055** [comment]
Quand j'ouvre en webview, ça me dit que j'ai été bloqué

**Comment by KirinRaikage** [comment]
Oui, classique, c'est le site lui même qui bloque, pas Tachiyomi.
Folks, can you close this issue as it's the classic blocking error, like below:
![Screenshot_20240307_083135_Mihon](https://github.com/keiyoushi/extensions-source/assets/11159175/f3649ea2-5089-4647-9164-d088c1125560)

**Comment by Guts055** [comment]
Ok,thanks you

**Comment by Guts055** [comment]
Ok, thanks you
