### ISSUE TITLE
Harmony scan

### ISSUE THREAD

**Issue by WoodlyBasquin56** [keiyoushi/tachiyomi-extensions-source#1752]
### Source name

Harmony scan

### Source link

https://harmony-scan.fr/

### Source language

French 

### Other details

Yes 18+ 
It's the banana scan that changed its name

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by WoodlyBasquin56** [comment]
@KirinRaikage  c'est toi qui t'es occupé de la mise à jour d'epsilon scan parce que c'est la source qui a changé en elle même donc la mise à jour  a échoué et donc lorsqu'on y entre ça apparaît tout noir avec des defauts
![Screenshot_20240307-104957](https://github.com/keiyoushi/extensions-source/assets/73551993/29ea0e06-d494-4e68-a2f1-a8dfbeb9b164)
Voilà ce qui passe lorsqu'on passe à l'extérieur en Webview 
![Screenshot_20240307-105040](https://github.com/keiyoushi/extensions-source/assets/73551993/63daee92-d5ec-445a-85d3-b1fbab0cc1bf)

On te le dit pas souvent mais merci pour ce que tu fais en tant que contributeur

**Comment by KirinRaikage** [comment]
Salut salut, non c'est pas moi pour Epsilon Scan mais la source Epsilon fonctionne chez moi, aucun problème !
Si ce n'est qu'une question de covers tu peux nettoyer la base de données pour Epsilon ? 
OK pour Harmony c'est noté

**Comment by xavimaa** [comment]
> Salut salut, non c'est pas moi pour Epsilon Scan mais la source Epsilon fonctionne chez moi, aucun problème ! Si ce n'est qu'une question de covers tu peux nettoyer la base de données pour Epsilon ? OK pour Harmony c'est noté

Salut, j'ai le même problème que @WoodlyBasquin56 de mon côté sur EpsilonScan

**Comment by WoodlyBasquin56** [comment]
@KirinRaikage même après le nettoyage 
![Screenshot_20240307-115330](https://github.com/keiyoushi/extensions-source/assets/73551993/309d76a0-83df-4d81-a425-815bdf176e23)
 C'est toujours pareil
![Screenshot_20240307-115339](https://github.com/keiyoushi/extensions-source/assets/73551993/45ab3ba7-ecb3-400a-9aed-b68dd3395cc3)

**Comment by KirinRaikage** [comment]
Ça te fait ce truc la depuis l'update ?
Et je répète ma question mais est ce que c'est seulement un problème de covers ou vous arrivez même pas à lire de mangas ?

**Comment by xavimaa** [comment]
> Ça te fait ce truc la depuis l'update ? Et je répète ma question mais est ce que c'est seulement un problème de covers ou vous arrivez même pas à lire de mangas ?

De mon coté ça charge à l'infini jusqu'au message "L'image n'a pas pu être chargée".
Etrangement dès que je clique sur "Ouvrir dans Webview" après l'erreur l'image s'affiche bien dans la webview mais pas dans Mihon.
Je peux pas donner de feedback pour dire si c'est depuis l'update, je viens juste d'installer l'extension.

**Comment by WoodlyBasquin56** [comment]
@KirinRaikage On arrive ni à télécharger ni avoir les images en Webview alors lorsqu'on est à l'extérieur de Mihon sur Chrome par exemple on peut lire et voir les images 
Je pense que celui qui a fait la mise à jour n'a pas changé les paramètres internes de la source en prenant  compte le changement du Webdesign
Un exemple le site était comme ça 
![Screenshot_20240307-121825](https://github.com/keiyoushi/extensions-source/assets/73551993/5ca4221b-52ad-4841-b15a-7d600cbe7b74)
Maintenant
![Uploading Screenshot_20240307-121933.png…]()

**Comment by WoodlyBasquin56** [comment]
Maintenant 
![Screenshot_20240307-121933](https://github.com/keiyoushi/extensions-source/assets/73551993/8accd4ee-32ed-428b-adaa-93558cc9e629)

**Comment by xavimaa** [comment]
@WoodlyBasquin56 @KirinRaikage J'ai ouvert une issues pour le problème avec Epsilon scan #1753

**Comment by KirinRaikage** [comment]
Mais l'extension fonctionne je comprends pas pourquoi vous ouvrez des issues pour Epsilon parce que ça fonctionne depuis la MaJ. Je peux pas reproduire le problème.

**Comment by xavimaa** [comment]
> Mais l'extension fonctionne je comprends pas pourquoi vous ouvrez des issues pour Epsilon parce que ça fonctionne depuis la MaJ. Je peux pas reproduire le problème.

Je suis bien sur la dernière version de Mihon avec la dernière version de l'extension. J'ai même tout réinstallé proprement, c'est vraiment étrange que pour toi ça fonctionne et moi non

**Comment by WoodlyBasquin56** [comment]
Ça va de même pour moi

**Comment by WoodlyBasquin56** [comment]
@KirinRaikage Tu pourrais pourquoi pas le supprimer en parlant de l'issue et l'ajoutant comme nouveau source et tu pourrais nous envoyer une screenshot lorsque tu es dans Epsilon scan pour voir

**Comment by WoodlyBasquin56** [comment]
Tu peux le sélectionner en tant que fichier pas en image  ça n'apparaît pas
![Screenshot_20240307-140406](https://github.com/keiyoushi/extensions-source/assets/73551993/e18dc7db-5591-42d3-af2b-a4dfcaf93bda)

**Comment by KirinRaikage** [comment]
![Screenshot_20240307_200157_Mihon](https://github.com/keiyoushi/extensions-source/assets/11159175/0df0457e-95d2-41fe-a2d9-9eba5ee52022)

**Comment by KirinRaikage** [comment]
![Screenshot_20240307_200050_Mihon](https://github.com/keiyoushi/extensions-source/assets/11159175/0f09bb38-e85c-4fbc-9205-6de9c1ef140d)
+ toutes les covers chargent

**Comment by KirinRaikage** [comment]
Messieurs, pour ne pas polluer cette issue et comme elle sera bientôt fermée, j'ai donné des pistes de résolution pour Epsilon Scan dans #1753
J'espère que ça vous aidera !

**Comment by WoodlyBasquin56** [comment]
@AwkwardPeak7 Is this a madara source for Epsilon scan because the source is buggy for some of the people who use LTE as networks You could check please thank you in advance
