### ISSUE TITLE
Epsilon Scan : Cover and pages do not load

### ISSUE THREAD

**Issue by xavimaa** [keiyoushi/tachiyomi-extensions-source#1753]
### Source information

Epsilon Scan 1.4.35

### Source language

French

### Steps to reproduce

1) Open the extension (problem with manga covers)
2) Click on a manga and open a chapter (infinite page loading)

### Expected behavior

Display of manga covers and pages

### Actual behavior

Hello,

The covers of the mangas from Episilon Scan are not displayed. 
The list of mangas, the metadata, and the chapters are well recovered.

The pages of the mangas do not display, it loads indefinitely and ends with an error message “The image could not be loaded”. 
When I click on “Open in Webview” the image displays correctly in the webview but I have nothing in Mihon.

![Screenshot_20240307_184901_Mihon](https://github.com/keiyoushi/extensions-source/assets/82511742/46a6b611-2a95-4618-9e82-2627f3521fa7)
![Screenshot_20240307_184908_Mihon](https://github.com/keiyoushi/extensions-source/assets/82511742/e0d61141-3b9c-4bae-b180-662c8b98c94e)
![Screenshot_20240307_185002_Mihon](https://github.com/keiyoushi/extensions-source/assets/82511742/195d4bc5-beed-420d-bb8a-88c90ab775b9)
![Screenshot_20240307_185009_Mihon](https://github.com/keiyoushi/extensions-source/assets/82511742/9c7aebe5-58d0-4825-bbde-932848d63eea)

### Mihon/Tachiyomi version

Mihon 0.16.4

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Can someone advise ? I can't reproduce this specific issue as covers and chapters are correctly loading on my aide:
![Screenshot_20240307_200050_Mihon](https://github.com/keiyoushi/extensions-source/assets/11159175/6a19f102-47b0-47fe-8b29-b9f23f4b08f8)
![Screenshot_20240307_200157_Mihon](https://github.com/keiyoushi/extensions-source/assets/11159175/e93c2dae-662a-42e8-aad2-7a925c393f09)

**Comment by KirinRaikage** [comment]
J'ai compris le problème. Je pense que le site bloque certains agents utilisateur.
You need to change the default user agent used in Mihon's settings.
For example, I've tested with the default user agent, I could reproduce the issue.
Please follow https://mihon.app/docs/guides/troubleshooting/

**Comment by xavimaa** [comment]
Thank you very much, it fixed my problem so I am closing this issue 🙏
