### ISSUE TITLE
EveriaClub (unoriginal, gravure)

### ISSUE THREAD

**Issue by 0Ha16wA5** [keiyoushi/tachiyomi-extensions-source#1765]
### Source name

Everia Club

### Source link

https://www.everiaclub.com/

### Source language

All

### Other details

`Everiaclub.com` seems to be a clone of `everia.club`

It might be a good to have both of them, since `everia.club` regularly lost their old content due to using third party hosting. 

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by 0Ha16wA5** [comment]
https://github.com/komikku-app/komikku-extensions/commit/95cbc2795b1241db8b74ea0bdd165902cc89551b
https://github.com/komikku-app/komikku-extensions/commit/4a371b977b83558f78ad8b624e2b11ec47b638f0

Should be merged here

**Comment by Norsze** [comment]
Can you stop going into issues and asking to merge another repository's stuff into ours? If they want to they can do it themselves

**Comment by Norsze** [comment]
Our rules since you seem to have missed them:

1\. **Have more than two brain cells.**
Basically, use common sense. This includes, but is not limited to, following staff instructions, not spamming, not bypassing word filters, etc.

10\. **No recommendations of sources or other third-party extension repos.**
Recommending sources causes unneeded load on the websites and may make extensions harder to maintain. Other third-party repositories are not affiliated with us, we do not support them, and they should not be shared here.

**Comment by 0Ha16wA5** [comment]
@Norsze Sorry, I thought instead of duplicating work, it might be good to just use someone else work as long the license is compatible. I'll stop doing it.

I saw other project doing cross reference for collaboration, just like other Mihon forks, so why not?

**Comment by Norsze** [comment]
I am not an admin, but one of them can chime in, but the rule makes me sceptical to this being ok

**Comment by vetleledaal** [comment]
If there is another extension repo with the same license as this repo (Apache License 2.0), it should be compatible under the conditions\*:
- License and copyright notice
- State changes

Copyright notices are most commonly found in README files and source code files. As long as these copyright notices remain unchanged, sufficient attribution is given, and commits are used for tracking changes -- you would fulfill the above requirements.

If any contributor wants to lift code from an external repo and provide attribution they should either use the `cherry-pick` mechanism in git or explicitly [add attribution to relevant commits](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors). Do note that the previously linked files are permanent links and may not reflect the most recent version.

As for rule 10, I don't think following licensing obligations can be considered an endorsement. At most an acknowledgement of the _extension authors_.

(\* summary provided by GitHub, [as-is with no implied or explicit warranty](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#disclaimer))

**Comment by cuong-tran** [comment]
let me just make the cherry-pick
