### ISSUE TITLE
Shinigami search function does not work

### ISSUE THREAD

**Issue by MadameVerre** [keiyoushi/tachiyomi-extensions-source#1766]
### Source information

Shinigami 1.4.53

### Source language

Indonesia

### Steps to reproduce

Already tried to migrate from another source but title not found
![Screenshot_2024-03-08-20-03-35-68](https://github.com/keiyoushi/extensions-source/assets/159318915/54a33dd2-b397-4110-8513-6c2893ca9de7)

### Expected behavior

![Screenshot_2024-03-08-20-00-37-52](https://github.com/keiyoushi/extensions-source/assets/159318915/dfcb814d-d9e1-41a3-b029-4b89864896cc)

### Actual behavior

![Screenshot_2024-03-08-20-01-32-46](https://github.com/keiyoushi/extensions-source/assets/159318915/7c5572f0-316c-4aec-b45e-55bc07d6f4f8)

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 13

### Other details

Have tried using specific titles and not, same result

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by RaidBuster** [comment]
I had the same issue too.

**Comment by inipew** [comment]
It works

![Screenshot_20240316-053104_Mihon](https://github.com/keiyoushi/extensions-source/assets/130418272/c806cbe1-9bbe-4ebf-98a0-4e0aafd39bcc)

**Comment by TheKingTermux** [comment]
It works fine to me

![Screenshot_2024-07-26-08-20-10-21_afd66b7916d19a60815f56273408b73e.jpg](https://github.com/user-attachments/assets/e2f04ace-56a8-4363-8080-d452506438f7)
