### ISSUE TITLE
Nexo scans

### ISSUE THREAD

**Issue by paz-web** [keiyoushi/tachiyomi-extensions-source#1769]
### Source information

Nexo scans 1.4.36

### Source language

PT BR

### Steps to reproduce

Não aparece os capítulos recentes do manga 

Exemplo 
![Screenshot_20240308-130105](https://github.com/keiyoushi/extensions-source/assets/145807935/089e2e6c-83cf-461e-bf71-3598b94b7ed7)
![Screenshot_20240308-130119](https://github.com/keiyoushi/extensions-source/assets/145807935/2d45a168-7de5-43e4-96b5-50f27e35dae5)

### Expected behavior

Deveria atualizar os capítulos 

### Actual behavior

Não atualiza os capítulos 

### Mihon/Tachiyomi version

0.15.2.4

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
https://github.com/keiyoushi/extensions-source/issues/1718
