### ISSUE TITLE
Comick: Failed to Bypass Cloudflare

### ISSUE THREAD

**Issue by NemuiNeko27** [keiyoushi/tachiyomi-extensions-source#1770]
### Source information

Comick 1.4.42

### Source language

Multi

### Steps to reproduce

1. Open Comick extension.
2. Encounter the issue of failed Cloudflare bypass.
3. Follow the solution by opening the webview and verifying with Cloudflare.
4. Successfully access the Comick website in the webview.
5. Return to the extension, expecting the issue to be resolved.
6. Despite verifying with Cloudflare, the issue persists in the extension.
7. Attempt to refresh the extension, but the problem persists.
![Screenshot_20240309-084821_Mihon](https://github.com/keiyoushi/extensions-source/assets/162644630/09cf8bf0-6e88-4a9d-b682-7135ba439fd4)
![Screenshot_20240309-084842_Mihon](https://github.com/keiyoushi/extensions-source/assets/162644630/5302eb0d-2c5e-4b54-ae23-e8c1c5343990)
![Screenshot_20240309-084850_Mihon](https://github.com/keiyoushi/extensions-source/assets/162644630/a4217f10-c091-44bb-ac57-cf45ad3edb8a)
![Screenshot_20240309-084931_Mihon](https://github.com/keiyoushi/extensions-source/assets/162644630/05eed40d-8198-4bde-bb95-d3c9d465dd8a)

### Expected behavior

- After successfully verifying with Cloudflare in the webview, accessing the Comick extension should work seamlessly without encountering the Cloudflare bypass issue.

### Actual behavior

- Even after verifying with Cloudflare through the webview, the Comick extension still faces the issue of failed Cloudflare bypass. Refreshing the extension does not resolve the problem, creating a persistent access issue.

### Mihon/Tachiyomi version

Mihon 0.16.4

### Android version

Android 11

### Other details

- Opening the webview again allows normal access to the Comick website, but returning to the extension results in the continued occurrence of the Cloudflare bypass issue.
- Tried it with other extension that required Cloudflare bypass (like nh*ntai) but it works not like Comick extension. So I think the problem lies in this extension.
- Also, tried changing user agent, clearing cookies and webview data, and re-installing the extension but still didn't work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by NemuiNeko27** [comment]
I think the issues is not with Cloudflare but the extension itself. Because I can access others extension that required Cloudflare bypass flawlessly. And as I stated before, I already do all the steps refering to solving cloudflare issues but still the Comick extension didn't work.

**Comment by Smol-Ame** [comment]
Works on my end, not an extension issue, change your user-agent (restart app after applying), and see if it works. If not, try another user-agent, repeat.

**Comment by Eagle1337** [comment]
works on my machine
