### ISSUE TITLE
Hentai2Read broken cover

### ISSUE THREAD

**Issue by blackheart911126** [keiyoushi/tachiyomi-extensions-source#1776]
### Source information

Hentai2Read 1.4.14

### Source language

English

### Steps to reproduce

1. Browse source
2. Click to open any manga
3. Wait until loading complete
4. Go back

### Expected behavior

Cover should be fine

### Actual behavior

Broken cover

### Mihon/Tachiyomi version

TachiyomiJ2K 1.7.4

### Android version

14

### Other details

![Screenshot_2024-03-09-19-59-39-847](https://github.com/keiyoushi/extensions-source/assets/113771133/ba2e08c1-9b97-4196-b164-15c9b57aa27b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by BuckwheatBidoof** [comment]
Yep, covers broken on TachiSY preview r554 as well

**Comment by Junn2002** [comment]
broken on newest TachiyomiAZ and newest Mihon to
![Screenshot_2024-03-23-12-16-59-794_app mihon](https://github.com/keiyoushi/extensions-source/assets/162298110/dad7634d-2572-4006-ba07-df6cecd3e6e1)
![Screenshot_2024-03-23-12-16-40-857_eu kanade tachiyomi az](https://github.com/keiyoushi/extensions-source/assets/162298110/1c88e830-de1f-4f80-9f3b-10b2c5aab656)
o
