### ISSUE TITLE
Manga Demon new url 

### ISSUE THREAD

**Issue by Xebilon** [keiyoushi/tachiyomi-extensions-source#1782]
### Source information

Manga Demon 1.4.9

### Source language

English

### Source new URL

https://demonreader.org/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by ManiV97** [comment]
There is no update for manga demon extension, the latest version is still 1.4.9.
The extension is not updated to new url: https://demonreader.org/
