### ISSUE TITLE
MangaPark, ability to change file version of specific chapters

### ISSUE THREAD

**Issue by BobbyWibowo** [keiyoushi/tachiyomi-extensions-source#1785]
### Source name

MangaPark

### Source language

English

### Describe your suggested feature

Here's a sample chapter that contain multiple file versions,
https://mangapark.net/title/101352-en-cultivator-vs-superhero/6240377-vol-0-ch-65

The issue is that for that specific chapter (and a few others in the series), neither the oldest nor the newest file versions use the arguably better quality scanlations. The better one is among the other file versions in between instead.

If you are logged-in in the website, it seems you can choose preferred file version for each chapter. The viewer will then default to that file version everytime (it may be remembering the uploader instead, since next/previous chapters will seemingly default to them too).

But the extension doesn't seem to have the ability to respect that.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
option to show all chapters will be available in the next version

![image](https://github.com/user-attachments/assets/02608acd-bc03-41aa-895a-d6009ed2555b)
