### ISSUE TITLE
carteldemanhwas: Request timed out

### ISSUE THREAD

**Issue by Vladraig** [keiyoushi/tachiyomi-extensions-source#179]
### Source information

carteldemanhwas 1.4.32

### Source language

Spanish 

### Steps to reproduce

step 1. enter the extension
Step 2. Select Recents Tab
step 3. look for a manhwa
step 4. when it was downloading, it stayed loading
Step 5. Wait for it to finish loading
step 6. I got the message "timeout"
step 7. I tried several times, but it stayed the same
step 8. I checked if the extension page was working and if it was working

### Expected behavior

they should load me more manhwa

### Actual behavior

I got the message "timeout"

### Tachiyomi version

0.1.5.2

### Android version

Android 8.1.0 and another Android 9.0 phone

### Other details

In the search engine for that extension I also got the message "timeout"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Can't replicate, maybe the source was down and you were seeing a cached version

**Comment by Vladraig** [comment]
> No se puede replicar, tal vez la fuente estaba inactiva y estabas viendo una versión en caché

A few minutes after posting the notice it had already been resolved but thanks for responding
