### ISSUE TITLE
ThorFinn - pt

### ISSUE THREAD

**Issue by nomaxsnx** [keiyoushi/tachiyomi-extensions-source#1799]
### Source name

Thorfinn

### Source link

https://thorfinn.xyz/

### Source language

Português 

### Other details

Thema: Madara 

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Site only has 1 manga with no chapters.

**Comment by nomaxsnx** [comment]
> Site only has 1 manga with no chapters.

Because they've just launched the site, they'll soon be putting up more

**Comment by vetleledaal** [comment]
Still- with no chapters it's impossible to make an extension. Create another issue when they have at least 1 chapter if you can't reopen this issue.
