### ISSUE TITLE
[Bug] Anchira: Unexpected JSON token

### ISSUE THREAD

**Issue by l2eused** [keiyoushi/tachiyomi-extensions-source#181]
### Source information

Anchira

### Source language

EN

### Steps to reproduce

1. install Extension
2. Open in Tachi SY lastest build
3. Showing error (see screenshot)
4. try to open in webview and clear cookies
5. Error still appear

### Expected behavior

shouldn't show error message

### Actual behavior

error message appear

![Screenshot_20240112-220319](https://github.com/keiyoushi/extensions-source/assets/94383254/342e5792-bcbd-4bf8-9116-89c948e00a09)

### Tachiyomi version

1.10.0 (SY preview build)

### Android version

Android 13

### Other details

Extension version: 1.4.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Closed by #180
