### ISSUE TITLE
Manga Demon

### ISSUE THREAD

**Issue by Darkon82** [keiyoushi/tachiyomi-extensions-source#1816]
### Source information

Manga Demon 1.4.9

### Source language

Englis

### Source new URL

demontoon.org

### Other details

I think they put a page as demontoon.org and an istant jump to demonreader.org so in webview it still work but no chapter are found or loaded.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Please stop opening new/duplicate issues about the same source.

Search the issues first before making a new issue, as one of the basic requirements & acknowledgements in the form.
