### ISSUE TITLE
Webdex scans error 404 on popular and latest tabs

### ISSUE THREAD

**Issue by ManiV97** [keiyoushi/tachiyomi-extensions-source#1817]
### Source information

1.4.35

### Source language

English

### Steps to reproduce

Error: 
![Screenshot_20240311_135338](https://github.com/keiyoushi/extensions-source/assets/143166150/78a645af-e8fe-4d86-a5ac-a4e9290b1770)
HTTP 404

### Expected behavior

Extension should work

### Actual behavior

Extension is not working, Error 404

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
The issue seems to be that their "ongoing projects" page is gone, so the extension probably pulls from the wrong place. Workaround: Search for title
