### ISSUE TITLE
Omega Scans json error/can't migrate to itself when told

### ISSUE THREAD

**Issue by Jalt3r** [keiyoushi/tachiyomi-extensions-source#1823]
### Source information

Omega Scans 1.4.38

### Source language

English

### Steps to reproduce

1.pull down to update chapter(Doesn't work)
2.app tells me to migrate omega into omega(cant migrate & received unexpected json error)
4.try to load webview, all urls lead to the discord page

### Expected behavior

Should update chapter after pull down reload &/or be able to migrate. Webview should lead to what I'm reading

### Actual behavior

Reload doesn't work and tells me to migrate omega scans into itself to fix,but I can't migrate. Webview doesn't lead into what I'm reading but to the "join discord" link on the site instead. Also I recieve a json error notice

![Screenshot_20240311_155505_TachiyomiSY](https://github.com/keiyoushi/extensions-source/assets/50228830/3f7261b1-a32f-46fc-8cff-d797b46aba00)
![Screenshot_20240311_155516_TachiyomiSY](https://github.com/keiyoushi/extensions-source/assets/50228830/2331e07c-64c5-47aa-bcbe-ab9216f7cbba)
![Screenshot_20240311_155533_TachiyomiSY](https://github.com/keiyoushi/extensions-source/assets/50228830/94a9bddf-4277-45dd-9c53-4ad7650145b7)

### Mihon/Tachiyomi version

1.10.5

### Android version

Android 14

### Other details

Not sure what to make of the json error problem but it could also just need a url update to the extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Amatsu-Kami** [comment]
the website is down, that's why they are redirecting to a discord invite
![image](https://github.com/keiyoushi/extensions-source/assets/91038682/55899c91-5e4b-4829-bd28-7631738ee4c0)
