### ISSUE TITLE
MM Scans (Unofficial)

### ISSUE THREAD

**Issue by Xeiv** [keiyoushi/tachiyomi-extensions-source#1840]
### Source information

MMScans 1.4.42

### Source language

English

### Source new URL

https://meowmeowcomics.com/

### Other details

I know there's #296 but it's for the source being down rather than a domain change report so I created a new one.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
I am not sure this is MMscans, they have not made a statement about it on their Discord. This might be a copycat that is posting what they upload on Patreon

**Comment by Xeiv** [comment]
Yeah it doesn't seem to be them, just checked properly now. Well it probably is still good for people who want to read on the app, though it does seem to be a bit outdated compared to the kofi and patreon. 
I don't know if it's possible to use a source with Kofi or patreon on the app since they post pdf files.
