### ISSUE TITLE
Manga Demon Chapters Not Loading. Download HTTP Error 522

### ISSUE THREAD

**Issue by Kenn876** [keiyoushi/tachiyomi-extensions-source#1841]
### Source information

Manga Demon 1.4.10

### Source language

English

### Steps to reproduce

1. Go to Manga Demon
2. Pick a manga or manhwa
3. Click on chapter
4. Try downloading chapter

### Expected behavior

The chapter pages should load and appear, and you can download the chapter too.

### Actual behavior

What happens instead is that the pages don't load and you can't download the chapters, saying there is an "HTTP Error 522".

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 12

### Other details

This happens to every manga or manhwa. I have cleared my cache, web data, and cookies. I have even force stop the app and restart it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Akshar062** [comment]
I don't have this issue i try all step but i can read and download chapters

## Manga Demon 1.4.10

## Tachiyomi version
0.15.3

## Android version
Android 9

**Comment by AwkwardPeak7** [comment]
5xx errors are server side and nothing we can do about them
