### ISSUE TITLE
instamanhwa extension stop working 

### ISSUE THREAD

**Issue by Spyroboy26** [keiyoushi/tachiyomi-extensions-source#1847]
### Source information

instamanhwa 1.4.36

### Source language

English 

### Steps to reproduce

Just  click  it

### Expected behavior

Manga covers should appear 

### Actual behavior

Nothing found 

### Mihon/Tachiyomi version

App version: 0.15.2.4 (standard, 16361e5, 121, 2024-01-28T19:30Z) Android version: 13 (SDK 33; build TP1A.220624.014.G781USQSEHXA1) Android build ID: TP1A.220624.014.G781USQSEHXA1 Device brand: samsung Device manufacturer: samsung Device name: r8q (r8qsqx) Device model: SM-G781U WebView: Android System WebView 122.0.6261.66

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
I got redirected to https://www.xmanhwa.me/ 

![image](https://github.com/user-attachments/assets/ccac05fb-fc13-41f3-b2f2-b70320a50518)
