### ISSUE TITLE
Restore previous version  : GMANGA

### ISSUE THREAD

**Issue by DemonEmperor1** [keiyoushi/tachiyomi-extensions-source#1850]
### Source information

GMANGA 1.4.14

### Source language

Arabic 

### Steps to reproduce

1- Enter the source
2- Opening a business
3- The chapter appears repeatedly for each chapter (there is more than one translation team for the chapter, so the chapters appear repeatedly)

### Expected behavior

Previously, there was an option to show the most viewed chapter only so that the chapter would not be repeated. Now there is no such option in the latest update

### Actual behavior

The chapter number appears repeated more than two, three or four times .
If I activate the automatic download feature, it can download more than one copy of the chapter 

### Mihon/Tachiyomi version

Mihon 1.16.4

### Android version

Android 13

### Other details

Attached are pictures of the problem before and after the update : 

1- Before updating
![Screenshot_٢٠٢٤٠٣١٣-١٢٣٤١٥](https://github.com/keiyoushi/extensions-source/assets/161745216/479ed49e-ee60-4ece-a197-1a37d0424f3f)
![Screenshot_٢٠٢٤٠٣١٣-١٢٣٤١٩](https://github.com/keiyoushi/extensions-source/assets/161745216/e410785c-cb6e-47f3-8110-fb4d860bf5b4)
![Screenshot_٢٠٢٤٠٣١٣-١٢٣١٢٣](https://github.com/keiyoushi/extensions-source/assets/161745216/ce94ad30-f8fa-43fa-af76-cb03237c2e88)

2- After the update
![Screenshot_٢٠٢٤٠٣١٣-١٢٢٧٤٥_Mihon](https://github.com/keiyoushi/extensions-source/assets/161745216/7d0c76a5-7b74-4e88-bcfd-3eb401350b9d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
use scanlator filter built into the app

**Comment by DemonEmperor1** [comment]
> use scanlator filter built into the app

Where is it in the application to do it?

**Comment by AwkwardPeak7** [comment]
> Where is it in the application to do it?

![image](https://github.com/keiyoushi/extensions-source/assets/48650614/e0b1c2b6-ee9e-46c8-8530-8da192d65a46)

**Comment by DemonEmperor1** [comment]
> > Where is it in the application to do it?
> 
> ![image](https://private-user-images.githubusercontent.com/48650614/312417402-e0b1c2b6-ee9e-46c8-8530-8da192d65a46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjYzMzEsIm5iZiI6MTcxMDMyNjAzMSwicGF0aCI6Ii80ODY1MDYxNC8zMTI0MTc0MDItZTBiMWMyYjYtZWU5ZS00NmM4LTg1MzAtOGRhMTkyZDY1YTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEwMzM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2MTA0MzlhODdmYmVmZDY3Njc2NDhkMTRjMmU3MmRiNDBkOGU4MWUwNDg0NGI1NGFhOWY5MmI3Y2E5NjA0NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pABzlzZDYRqoEwNhSrxOiHNZGexih-NPHskGXcQuhO8)

Thank you

**Comment by DemonEmperor1** [comment]
> > Where is it in the application to do it?
> 
> ![image](https://private-user-images.githubusercontent.com/48650614/312417402-e0b1c2b6-ee9e-46c8-8530-8da192d65a46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjY2OTAsIm5iZiI6MTcxMDMyNjM5MCwicGF0aCI6Ii80ODY1MDYxNC8zMTI0MTc0MDItZTBiMWMyYjYtZWU5ZS00NmM4LTg1MzAtOGRhMTkyZDY1YTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEwMzk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NGU1ZTU1NmNhZDc4OTg2NDcyZjk4OWEyNjI0OGUyYmQ0YmRhZTFiNmI2Y2M4Y2FmM2EyMGZiMDBiN2Y3NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ulI64X3ikBmJd63wwjFID03KBrIw-A9LwFqrBjEt_J8)

ياترى هل بالامكان اظهار الفصول 

> > Where is it in the application to do it?
> 
> ![image](https://private-user-images.githubusercontent.com/48650614/312417402-e0b1c2b6-ee9e-46c8-8530-8da192d65a46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjY2OTAsIm5iZiI6MTcxMDMyNjM5MCwicGF0aCI6Ii80ODY1MDYxNC8zMTI0MTc0MDItZTBiMWMyYjYtZWU5ZS00NmM4LTg1MzAtOGRhMTkyZDY1YTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEwMzk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NGU1ZTU1NmNhZDc4OTg2NDcyZjk4OWEyNjI0OGUyYmQ0YmRhZTFiNmI2Y2M4Y2FmM2EyMGZiMDBiN2Y3NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ulI64X3ikBmJd63wwjFID03KBrIw-A9LwFqrBjEt_J8)

We may face a problem when blocking some people because there will be missing chapters

**Comment by DemonEmperor1** [comment]
> > > Where is it in the application to do it?
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/48650614/312417402-e0b1c2b6-ee9e-46c8-8530-8da192d65a46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjY2OTAsIm5iZiI6MTcxMDMyNjM5MCwicGF0aCI6Ii80ODY1MDYxNC8zMTI0MTc0MDItZTBiMWMyYjYtZWU5ZS00NmM4LTg1MzAtOGRhMTkyZDY1YTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEwMzk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NGU1ZTU1NmNhZDc4OTg2NDcyZjk4OWEyNjI0OGUyYmQ0YmRhZTFiNmI2Y2M4Y2FmM2EyMGZiMDBiN2Y3NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ulI64X3ikBmJd63wwjFID03KBrIw-A9LwFqrBjEt_J8)
> 
> I wonder if it is possible to show the chapters?
> 
> > > Where is it in the application to do it?
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/48650614/312417402-e0b1c2b6-ee9e-46c8-8530-8da192d65a46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjY2OTAsIm5iZiI6MTcxMDMyNjM5MCwicGF0aCI6Ii80ODY1MDYxNC8zMTI0MTc0MDItZTBiMWMyYjYtZWU5ZS00NmM4LTg1MzAtOGRhMTkyZDY1YTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEwMzk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NGU1ZTU1NmNhZDc4OTg2NDcyZjk4OWEyNjI0OGUyYmQ0YmRhZTFiNmI2Y2M4Y2FmM2EyMGZiMDBiN2Y3NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ulI64X3ikBmJd63wwjFID03KBrIw-A9LwFqrBjEt_J8)
> 
> We may face a problem when blocking some people because there will be missing chapters

**Comment by AwkwardPeak7** [comment]
then remove the filter when there is some chapter missing? 

you can also just use "skip duplicate chapters" in settings > reader

**Comment by DemonEmperor1** [comment]
> then remove the filter when there is some chapter missing?
> 
> you can also just use "skip duplicate chapters" in settings > reader

Ok, the automatic download of chapters will download the chapter more than once and will take data. Thank you. I will request the feature in the application.
