### ISSUE TITLE
Mode scanlator  error

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#1860]
### Source information

Mode Scanlator 1.4.3

### Source language

Português (Brasil)

### Steps to reproduce

![Screenshot_20240313-163111](https://github.com/keiyoushi/extensions-source/assets/157044539/dc52a7ae-6dbb-419d-af85-dad138b16cf0)

### Expected behavior

.

### Actual behavior

.

### Mihon/Tachiyomi version

TachiyomiSY 1.10.5

### Android version

Android 11 

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by QuagZy** [comment]
Não carrega as páginas

**Comment by ghost** [comment]
Não carrega as páginas

**Comment by nomaxsnx** [comment]
> Não carrega as páginas

Algumas imagens só podem ser visto no próprio site ou webview, por conta que estão em zip

![Screenshot_2024-03-15-13-53-19-507_app mihon-edit](https://github.com/keiyoushi/extensions-source/assets/157644160/b873786a-065c-472b-9d42-26e009a69e06)

**Comment by ghost** [comment]
Antes de atualizar não tava assim

**Comment by bapeey** [comment]
What is the error message if you try to download a chapter?

**Comment by nomaxsnx** [comment]
> What is the error message if you try to download a chapter?

I don't know if this is considered an error, some chapters have ".zip" and others don't, try reading "Cultivo Duplo" chapter "89".

**Comment by bapeey** [comment]
the extension should be able to handle those zip ([code](https://github.com/keiyoushi/extensions-source/blob/c4821c54ed85049b09d546442d45bc2fd4372be7/lib-multisrc/peachscan/src/eu/kanade/tachiyomi/multisrc/peachscan/PeachScan.kt#L174))

**Comment by nomaxsnx** [comment]
So my friend, if it supports .zip, it should work, but I don't know what the error is.

**Comment by nomaxsnx** [comment]
And that's when I wanted the extensions to have a debugger to discover the error

**Comment by nomaxsnx** [comment]
> the extension should be able to handle those zip ([code](https://github.com/keiyoushi/extensions-source/blob/c4821c54ed85049b09d546442d45bc2fd4372be7/lib-multisrc/peachscan/src/eu/kanade/tachiyomi/multisrc/peachscan/PeachScan.kt#L174))

Is this extension supported?

![Screenshot_2024-03-15-22-16-23-729_com mi android globalFileexplorer](https://github.com/keiyoushi/extensions-source/assets/157644160/3b69489e-1b87-40f7-8039-1900778b0931)

And

![Screenshot_2024-03-15-22-19-27-722_com android chrome](https://github.com/keiyoushi/extensions-source/assets/157644160/1e018f96-954c-426a-8be1-4166db1517f3)


It should be the manga images I just downloaded

**Comment by bapeey** [comment]
Yes, all chapters have zipped images. 
Tested with [A batalha através dos céus - Ch. 431](https://modescanlator.com/doupo-cangqiong/431/)

**Comment by nomaxsnx** [comment]
> Yes, all chapters have zipped images. Tested with [A batalha através dos céus - Ch. 431](https://modescanlator.com/doupo-cangqiong/431/)

It's working 
![Screenshot_2024-03-15-22-23-32-821_app mihon](https://github.com/keiyoushi/extensions-source/assets/157644160/5e24c15c-c7a9-4b57-912e-25531732b745)

**Comment by nomaxsnx** [comment]
> > the extension should be able to handle those zip ([code](https://github.com/keiyoushi/extensions-source/blob/c4821c54ed85049b09d546442d45bc2fd4372be7/lib-multisrc/peachscan/src/eu/kanade/tachiyomi/multisrc/peachscan/PeachScan.kt#L174))
> 
> Is this extension supported?
> 
> ![Screenshot_2024-03-15-22-16-23-729_com mi android globalFileexplorer](https://private-user-images.githubusercontent.com/157644160/313363184-3b69489e-1b87-40f7-8039-1900778b0931.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NTI1MzUsIm5iZiI6MTcxMDU1MjIzNSwicGF0aCI6Ii8xNTc2NDQxNjAvMzEzMzYzMTg0LTNiNjk0ODllLTFiODctNDBmNy04MDM5LTE5MDA3NzhiMDkzMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQwMTIzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzUzNThkMWIwZTE0YTRjMzg0NmJjNWQ1NjQwMzQzZGI4MWVjNTI0MWIzZDMxZjIzMmI1YzI3NDUzOGVlNTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._QzTzcgjuHVfrg824AttOj3FwcRy9on_onqpgYPE8y8)
> 
> And
> 
> ![Screenshot_2024-03-15-22-19-27-722_com android chrome](https://private-user-images.githubusercontent.com/157644160/313363448-1e018f96-954c-426a-8be1-4166db1517f3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NTI1MzUsIm5iZiI6MTcxMDU1MjIzNSwicGF0aCI6Ii8xNTc2NDQxNjAvMzEzMzYzNDQ4LTFlMDE4Zjk2LTk1NGMtNDI2YS04YmUxLTQxNjZkYjE1MTdmMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQwMTIzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2Y2NzkwYTlkZGFmZWY3NmJhNGU4ZGUyMmEyNTBiYWRmZDQyZjU1NDJlYWI1MDAzMmI2ZWM4ZWQ1MDM0OGFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KBP4Li7GmMMQx9T7Kt4RxLXC1QKMifW9xVxN8NVxzaI)
> 
> It should be the manga images I just downloaded

After downloading the .Bin image on the cell phone, apparently some sleeves are encrypted 

![Screenshot_2024-03-15-22-22-52-375_com mi android globalFileexplorer-edit](https://github.com/keiyoushi/extensions-source/assets/157644160/31dce33d-2fa9-42e0-b1bd-3af16c8320c7)

![Screenshot_2024-03-15-22-25-04-346_cn wps xiaomi abroad lite](https://github.com/keiyoushi/extensions-source/assets/157644160/fde6c079-b53b-4e35-931e-5040e4f1fc2f)

**Comment by nomaxsnx** [comment]
> What is the error message if you try to download a chapter?

Sorry now that I've seen it, I tried to download it and this error appeared: "Could not download in SVG".

![Screenshot_2024-03-15-22-40-49-902_com android chrome-edit](https://github.com/keiyoushi/extensions-source/assets/157644160/43e99128-e63f-43eb-abdb-f3d2a18b8f18)

**Comment by paz-web** [comment]
Continua com o mesmo erro

**Comment by nomaxsnx** [comment]
[](url)

> Continua com o mesmo erro

![Screenshot_2024-03-25-15-31-38-278_app mihon](https://github.com/keiyoushi/extensions-source/assets/157644160/5502f256-222e-425b-9b09-64adabeb124f)


Se atualizou a extensão, app está atualizado?, pois pra min não está ocorrendo esse erro

**Comment by nomaxsnx** [comment]
Obs: fala se o Rf dragon ou mode?, e fala nome do manga

**Comment by paz-web** [comment]
Falo da mode e também da dragon

![Screenshot_20240325-235406](https://github.com/keiyoushi/extensions-source/assets/145807935/85dd8426-ecfd-40a7-9ead-62063cc5b712)
![Screenshot_20240325-235401](https://github.com/keiyoushi/extensions-source/assets/145807935/22e5c1cd-04b6-4fde-a2f8-4a3d5dfebd4d)
![Screenshot_20240325-235434](https://github.com/keiyoushi/extensions-source/assets/145807935/b43ab3bd-fc86-4761-85d1-7912955880a8)
![Screenshot_20240325-235425](https://github.com/keiyoushi/extensions-source/assets/145807935/a7fcdb68-3bb5-475a-83ff-0c2452de6c4f)

![Screenshot_20240325-235937](https://github.com/keiyoushi/extensions-source/assets/145807935/841e95d7-82c8-497d-825b-d9c52e47e581)
![Screenshot_20240325-235625](https://github.com/keiyoushi/extensions-source/assets/145807935/95f974a8-21e3-433b-9b49-2033068e4ffa)
![Screenshot_20240325-235954](https://github.com/keiyoushi/extensions-source/assets/145807935/a58769ab-8124-4913-b6cf-52e5ddea10db)

**Comment by nomaxsnx** [comment]
> Falo da mode e também da dragon
> 
> ![Screenshot_20240325-235406](https://private-user-images.githubusercontent.com/145807935/316711873-85dd8426-ecfd-40a7-9ead-62063cc5b712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MjMwODksIm5iZiI6MTcxMTQyMjc4OSwicGF0aCI6Ii8xNDU4MDc5MzUvMzE2NzExODczLTg1ZGQ4NDI2LWVjZmQtNDBhNy05ZWFkLTYyMDYzY2M1YjcxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQwMzEzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTZiYTBkOTkwZGE3ZjU4NWQyMTZmYWUzMTU1MTk4OWViNzdhMmVhNWQxOTc1ZTdkYzg5ODEzM2YwZDgyOTcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F2MSfCWkuq4sVfiWWMPYMTLMalO6VZVf_n7ijW63GPY) ![Screenshot_20240325-235401](https://private-user-images.githubusercontent.com/145807935/316711881-22e5c1cd-04b6-4fde-a2f8-4a3d5dfebd4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MjMwODksIm5iZiI6MTcxMTQyMjc4OSwicGF0aCI6Ii8xNDU4MDc5MzUvMzE2NzExODgxLTIyZTVjMWNkLTA0YjYtNGZkZS1hMmY4LTRhM2Q1ZGZlYmQ0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQwMzEzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjY0YjhkMzBkNWU5ZTNkMGRjODk0YjBhZmEzYTBlYTI5YjdlMmUyMzk1ZGMyOTI4OWYwZmQyYWNmYWQxYjgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jS0XPW4mcsi1otmr5C5GazBFWdvTvx0z9a4uICKGKxk) ![Screenshot_20240325-235434](https://private-user-images.githubusercontent.com/145807935/316711886-b43ab3bd-fc86-4761-85d1-7912955880a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MjMwODksIm5iZiI6MTcxMTQyMjc4OSwicGF0aCI6Ii8xNDU4MDc5MzUvMzE2NzExODg2LWI0M2FiM2JkLWZjODYtNDc2MS04NWQxLTc5MTI5NTU4ODBhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQwMzEzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTRhNmM1MjBiY2Y4ZjY3ZTg5YzE4OGRlNmZjNDhjMjQ1NGQ0MmIwODRiYTI3YTcwZjE0YTdhMGFmN2JhOTg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hxypU9apo3SSo4h_9HpAHAMDOrIly7gfa3WKtLQixMM) ![Screenshot_20240325-235425](https://private-user-images.githubusercontent.com/145807935/316711889-a7fcdb68-3bb5-475a-83ff-0c2452de6c4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MjMwODksIm5iZiI6MTcxMTQyMjc4OSwicGF0aCI6Ii8xNDU4MDc5MzUvMzE2NzExODg5LWE3ZmNkYjY4LTNiYjUtNDc1YS04M2ZmLTBjMjQ1MmRlNmM0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQwMzEzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjQ0MjM3MjZmMDFmODgzN2Q0ODE2NmI2OGFkMDY1YjUxNWMxZmZlMmY4MmUzM2E2MTIwNGYxYWM0YWQwYjI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.npw5Z1uzLHjD2EKqUr_kKeZUdbA0C-2v4qJaA9cj8ms)
> 
> ![Screenshot_20240325-235937](https://private-user-images.githubusercontent.com/145807935/316713006-841e95d7-82c8-497d-825b-d9c52e47e581.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MjMwODksIm5iZiI6MTcxMTQyMjc4OSwicGF0aCI6Ii8xNDU4MDc5MzUvMzE2NzEzMDA2LTg0MWU5NWQ3LTgyYzgtNDk3ZC04MjViLWQ5YzUyZTQ3ZTU4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQwMzEzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWFiMmMyZjQwOTA4YTZmM2EyNDA1YWQ1NTdmNzQ4YjkwMjljNmUyMmMzYjkyNzhkOTgwNWEwN2RlNzEyNDQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fzmkBay1p-jcUuFZ-wIlEya4asggMAIACWZPe3gZawQ) ![Screenshot_20240325-235625](https://private-user-images.githubusercontent.com/145807935/316713011-95f974a8-21e3-433b-9b49-2033068e4ffa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MjMwODksIm5iZiI6MTcxMTQyMjc4OSwicGF0aCI6Ii8xNDU4MDc5MzUvMzE2NzEzMDExLTk1Zjk3NGE4LTIxZTMtNDMzYi05YjQ5LTIwMzMwNjhlNGZmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQwMzEzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWY4ZDc2YWU3YjZiYzkzZTkyOTY1YzMzNzdkNDNmZDIwM2Y0YTk0NmIxY2QxOGVkNGRiYjlkMDY0MmQwNzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cjkkvirCixM-bo-h2QmY0aOn0lFJ11YXcTdgq3_FsPg) ![Screenshot_20240325-235954](https://private-user-images.githubusercontent.com/145807935/316713014-a58769ab-8124-4913-b6cf-52e5ddea10db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MjMwODksIm5iZiI6MTcxMTQyMjc4OSwicGF0aCI6Ii8xNDU4MDc5MzUvMzE2NzEzMDE0LWE1ODc2OWFiLTgxMjQtNDkxMy1iNmNmLTUyZTVkZGVhMTBkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQwMzEzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjU1ZmQyYWZkZTk2MTdlOTYxOTQ1NmUyN2FmYjJjMTYwZDMxMTk4M2I0YTVkYjBlNWY4ZjY0YjQxNWUwY2M2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IHLS8cMX9pu3A5O17zt50PCUnZChj30ImRJH3B_-rzY)

![Screenshot_2024-03-26-00-13-54-664_app mihon](https://github.com/keiyoushi/extensions-source/assets/157644160/0d0336cf-2693-4b46-af3a-89556d428510)

**Comment by paz-web** [comment]
Qual aplicativo você usa?

**Comment by nomaxsnx** [comment]
> Qual aplicativo você usa?

Mihon, desculpa pela demora

**Comment by paz-web** [comment]
O mesmo que eu tô usando e continua sem carregar as páginas deve ser alguma coisa com o meu celular

**Comment by ghost** [comment]
Tem uns "mangas" que carrega é outros que não carrega

**Comment by vetleledaal** [comment]
> O mesmo que eu tô usando e continua sem carregar as páginas deve ser alguma coisa com o meu celular

(TL) Tente procurar nas configurações para que você possa limpar o cache do capítulo. Deve ser algo como "Limpar o cache de capítulos".

**Comment by nomaxsnx** [comment]
Tente usar esse User-agents: Mozilla/5.0 (Linux; Android 10; HD1913) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.119 Mobile Safari/537.36 EdgA/122.0.2365.76


E depois testa!
R: não funcionou

Agora junto com user agentes e DNS
R: Coloca pra cloudfare

**Comment by paz-web** [comment]
Deu certo, obrigado pela ajuda

**Comment by ghost** [comment]
> Tente usar esse User-agents: Mozilla/5.0 (Linux; Android 10; HD1913) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.119 Mobile Safari/537.36 EdgA/122.0.2365.76
> 
> E depois testa! R: não funcionou
> 
> Agora junto com user agentes e DNS R: Coloca pra cloudfare

Mano vc me salvou muito obrigado ♥️
