### ISSUE TITLE
Earlymanga  images not loading on majority of manga chapters

### ISSUE THREAD

**Issue by LethargicCrocodile** [keiyoushi/tachiyomi-extensions-source#1869]
### Source information

EarlyManga 1.4.26

### Source language

English

### Steps to reproduce

Click on manga e.g. Beginning of the end
Select chapter e.g. 175.2
Images doesn't load
![Screenshot_20240314_022303_TachiyomiJ2K](https://github.com/keiyoushi/extensions-source/assets/159403984/d1668969-5f5d-4f6e-96fa-b3d2c5fb257c)

### Expected behavior

Click on manga e.g. Magic emperor
Select chapter
Images load
![Screenshot_20240314_022319_TachiyomiJ2K](https://github.com/keiyoushi/extensions-source/assets/159403984/0aaf1277-4a93-41f2-88ff-a55fa1eb96bc)

### Actual behavior

Images don't load for majority of the mangas and their chapters
Webview is fine for everything as seen in image of beginning of the end 175.2
[Screenshot_20240314_022507_TachiyomiJ2K](https://github.com/keiyoushi/extensions-source/assets/159403984/c57f467f-545b-4440-aed4-79fa45ba1c08)

### Mihon/Tachiyomi version

Mihon 0.16.4 , tachij2k 1.7.4

### Android version

13

### Other details

Images don't load for majority of the manga and chapters beside a few ive found like magic emperor which doesn't seem affected. But large majority have either 1 or 2 chapters that work or none at all.
Webview works fine for everything and tried another user agent but didn't work, uninstall and reinstall extension and clearing of data cache etc. Didn't work either along with trying another device had same issues.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KingBananaDuck** [comment]
I have same issue with the comick extension

**Comment by LethargicCrocodile** [comment]
though would post incase makes a fix any easier managed to find a source for an older  earlymanga version. that being 1.4.21 so though would test it and that version seems to work fine without issue. only change i can see (as not sure how to open up the code for it) is its using one of the sites mirrors that being earlycomic.com but all the mangas and their chapters work in the app only caveat i can find with it is the search is very narrow on this old version ie; if search "demon" shows like 12 results whereas current one shows like 40.
