### ISSUE TITLE
ComicK error 403

### ISSUE THREAD

**Issue by iMo-ali** [keiyoushi/tachiyomi-extensions-source#1872]
### Source information

ComicK v1.4.42

### Source language

ENGLISH 

### Steps to reproduce

Try searching or just browsing the source it will throw 403 error 

### Expected behavior

Should work after opening in WebView 

### Actual behavior

Only works on WebView but in the app it throw 403 again 
![Screenshot_20240314-171252](https://github.com/keiyoushi/extensions-source/assets/61813980/67a1ae51-afa9-492b-92fb-533c3f6ea0c0)
![Screenshot_20240314-171257](https://github.com/keiyoushi/extensions-source/assets/61813980/d0689df3-e691-42fa-ac3f-b50882ddeadb)

### Mihon/Tachiyomi version

J2k v1.7.4

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Hexishu** [comment]
I have the same sort of issue, but for me it says "failing to bypass Cloudflare", happens to nhentai somehow aswell, already cleared cache n everything + changed standard user agent... Now Idk anymore

**Comment by ArchCelestial** [comment]
It doesn't seem to be a cloud flare issue, it doesn't say that I am failing cloudflare at all.

**Comment by Norsze** [comment]
![image](https://github.com/keiyoushi/extensions-source/assets/66540317/4753ec3b-ca3e-4768-b1cf-794c20606d3a)

From their Discord, just so guys will understand where the problem is

**Comment by meotimdihia** [comment]
Please try again, I re-enabled API for third-party apps.

**Comment by Siegfredal** [comment]
Http 500 now. Catalog becone accessible though

> Please try again, I re-enabled API for third-party apps.

**Comment by meotimdihia** [comment]
@Siegfredal I fixed the problem now. It was occured because I changed these APIs to improve performance.

**Comment by iMo-ali** [comment]
> Please try again, I re-enabled API for third-party apps.

Can confirm its working thanks ❤️
