### ISSUE TITLE
Comick cloudflare

### ISSUE THREAD

**Issue by AbdelrahmanElnezamy121** [keiyoushi/tachiyomi-extensions-source#1873]
### Source information

Comick

### Source language

all

### Steps to reproduce

Browse frim comick tells me failed to bypass cloudflare 
Open web view there is not cloudflare

### Expected behavior

Browse normally

### Actual behavior

Failed to bypass cloudflare 

### Mihon/Tachiyomi version

0.16.4

### Android version

13

### Other details

....

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
#1872 we only need one issue, look before posting
