### ISSUE TITLE
Comick HTTP error 403

### ISSUE THREAD

**Issue by ArchCelestial** [keiyoushi/tachiyomi-extensions-source#1874]
### Source information

Comick 1.4.42

### Source language

All

### Steps to reproduce

Open the comick source in the app, I tried with both TachiJ2k and TachiyomiSY. 

### Expected behavior

I should be able to see the manga/manga in the app without an errot

### Actual behavior

In the app, the comick source says that there is a HTTP 403 error and asks to open the webview. The webview is fine 

### Mihon/Tachiyomi version

Tachiyomij2k 1.7.4

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ArchCelestial** [comment]
Didnt see the previous issue

**Comment by Norsze** [comment]
#1872 stop opening stuff for the same issue for the same source
