### ISSUE TITLE
The Comick Extension Shows "Failed To Bypass Cloudflare" Whenever I Try To Open A Chapter

### ISSUE THREAD

**Issue by Solitaria-Noctis** [keiyoushi/tachiyomi-extensions-source#1875]
### Source information

Comick 1.4.42

### Source language

English

### Steps to reproduce

1. Opened a chapter of a manhwa through the Comick extension.
2. Page stuck on the loading screen.
3. Chapter shuts down, and the message, "Failed To Bypass CloudFlare" pops up.

### Expected behavior

The loading screen should eventually produce the pages within a few seconds.

### Actual behavior

The loading screen appears stuck, and soon closes, and the pop-up, "Failed To Bypass CloudFlare" appears instead.

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
I swear you guys are blind #1872
