### ISSUE TITLE
Comick.cc moved to comick.io extension http error

### ISSUE THREAD

**Issue by Siegfredal** [keiyoushi/tachiyomi-extensions-source#1876]
### Source information

Comick 1.4.2

### Source language

Englisg

### Source new URL

Comick.io

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
#1872 source issues

**Comment by Siegfredal** [comment]
Oops duplicate. sorry. First time. Won't do it again
