### ISSUE TITLE
Enryumanga weird error 404 

### ISSUE THREAD

**Issue by SsimonO1** [keiyoushi/tachiyomi-extensions-source#1877]
### Source information

Enryumanga 1.4.30

### Source language

English

### Steps to reproduce

Open the extension through source screen 

### Expected behavior

Manga/manwha should pop up 

### Actual behavior

However it shows error 404 which normally means source website doesn't work anymore however when clicking on Web view u can still access the page 

### Mihon/Tachiyomi version

Tachiyomi Stable 0.15.3

### Android version

Android 13

### Other details

![Screenshot_20240314_121720_Tachiyomi](https://github.com/keiyoushi/extensions-source/assets/163418145/97eb5184-a0b1-4848-9064-0a1a7f06dcbf)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Site isn't completely dead, just very slow and with frequent timeouts. Will probably have to wait out the issues before anyone wants to touch it.
