### ISSUE TITLE
I get an HTTP 500 error when trying to open chapters from Comick

### ISSUE THREAD

**Issue by Bezemboy** [keiyoushi/tachiyomi-extensions-source#1879]
### Source information

Comick 1.4.42

### Source language

English

### Steps to reproduce

1. I tap on a chapter
2. The I get the error 500 and it doesn't load
3. Sometimes a chapter does load but none of some of the page will not load

### Expected behavior

That I just can open the chapters

### Actual behavior

I get an error or it will not load

### Mihon/Tachiyomi version

Mihon 0.16.4

### Android version

Android 14

### Other details

The website of Comick has no problems and will display all the images from all the chapters

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [ ] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
This is not an extension issue, the website API was down, it is back up now, also duplicate #1872

**Comment by Bezemboy** [comment]
The error is not a 403 but a 500

**Comment by Norsze** [comment]
If you open another issue for this I swear, read the comments the comick dev is literally there writing
