### ISSUE TITLE
Nexos Scans

### ISSUE THREAD

**Issue by Kyo-70** [keiyoushi/tachiyomi-extensions-source#188]
### Source name

Nexos Scans

### Source link

https://nexoscans.com/

### Source language

Portuguese

### Other details

There are also some 18+/NSFW works

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by OdisBy** [comment]
Working on it
