### ISSUE TITLE
An HTTP 500 error when opening chapters of Comick

### ISSUE THREAD

**Issue by Bezemboy** [keiyoushi/tachiyomi-extensions-source#1880]
### Source information

Comick 1.4.42

### Source language

English

### Steps to reproduce

1. I tap on a chapter
2. The I get the error 500 and it doesn't load
3. Sometimes a chapter does load but none of some of the page will not load

### Expected behavior

That it opens a chapter

### Actual behavior

It will not open a chapter

### Mihon/Tachiyomi version

Mihon 0.16.4

### Android version

Android 14

### Other details

Sometimes it does load an older chapter but will not load any pages. The website is working as expected

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Read the comments or get banned #1872

**Comment by Bezemboy** [comment]
Vut the link you send me is about a error 403 and mine is about a error 500

**Comment by Norsze** [comment]
Read the comments you dolt. READ

**Comment by Norsze** [comment]
It also works now so you can stop
