### ISSUE TITLE
SlimeRead: "MissingFieldException" and "JsonDecodingException" the error persist

### ISSUE THREAD

**Issue by nomaxsnx** [keiyoushi/tachiyomi-extensions-source#1885]
### Source information

SlimeRead 1.4.5

### Source language

Portugues

### Steps to reproduce

1 install the extension
2 open the extension
3 open any manga

### Expected behavior

![image](https://github.com/keiyoushi/extensions-source/assets/157644160/5611dd1c-ce6f-4b4a-b0f6-c6921e7134ea)

### Actual behavior

MissingFieldException

### Mihon/Tachiyomi version

1.16.4

### Android version

Android 13

### Other details

According to PR #1837 , the error still persists

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nomaxsnx** [comment]
![Screenshot_2024-03-14-16-18-07-652_app mihon](https://github.com/keiyoushi/extensions-source/assets/157644160/f4b3e3db-e6bc-4d43-a6df-7d07513c7abd)

**Comment by bapeey** [comment]
still happening? seems like they had issues with the "prod" api

**Comment by nomaxsnx** [comment]
> still happening? seems like they had issues with the "prod" api

Well the errors will now stop happening, it could be a possible site error, apparently
