### ISSUE TITLE
Bakai Http error 404

### ISSUE THREAD

**Issue by Nerannnn** [keiyoushi/tachiyomi-extensions-source#1887]
### Source information

Bakai 1.4.2

### Source language

Portuguese 

### Steps to reproduce

When I open the extension a black screen appears saying HTTP error 404, I have already done the entire procedure which involves uninstalling and reinstalling the extension and forcing the app to stop but it didn't work

### Expected behavior

the manga update normally

### Actual behavior

a black screen appears saying HTTP error 404

### Mihon/Tachiyomi version

0.15.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by OceaN90S** [comment]
![Screenshot_20240316-103128](https://github.com/keiyoushi/extensions-source/assets/156086953/cd7d63b7-1c58-4d56-ab36-7914e7169d84)
![Screenshot_20240316-103718](https://github.com/keiyoushi/extensions-source/assets/156086953/827801d6-1f24-4142-9a45-621a3292e537)
Extra information the 404 error needed but I noticed that the manga that were already in the library work normally
