### ISSUE TITLE
NicoManga : Cover doesn't load, and click chapter show http error 404 

### ISSUE THREAD

**Issue by DchanN** [keiyoushi/tachiyomi-extensions-source#189]
### Source information

NicoManga 1.4.1

### Source language

Japanese - 日本語

### Steps to reproduce

Browse -> Select NicoManga -> Browse / Latest

### Expected behavior

Show manga cover and load chapter manga

### Actual behavior

Cover doesn't load, and show http error 404 when select any chapter manga

### Tachiyomi version

Preview r6404

### Android version

Android 10

### Other details

In Webview cover and chaper loaf without problem,

https://github.com/keiyoushi/extensions-source/assets/101858971/845a700b-ba46-49ee-b7b2-491bf232610b

@CodeSpoof maybe can you check , is this problem happen to you too?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CodeSpoof** [comment]
I had some problems calling the sebsite on my phone, but a vpn solved it. Some issues with cloudflare at first, but not after i got it working everywhere else

**Comment by CodeSpoof** [comment]
Seems to be specific to some entries.
