### ISSUE TITLE
MHScans (Source Request)

### ISSUE THREAD

**Issue by lalalasupa0** [keiyoushi/tachiyomi-extensions-source#190]
### Source name

MHScans

### Source link

https://mhscans.com/

### Source language

Spanish

### Other details

NSFW: No

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Clouddark75** [comment]
I'm against this one! I know the owners. They barely make it to have the site up and running with all the traffic they have, it will be pretty dead if it gets added to Tachi, there are a lot of other sites that do have their content. It was the reason why it didn't make it into Tachi before.

**Comment by lalalasupa0** [comment]
> I'm against this one! I know the owners. They barely make it to have the site up and running with all the traffic they have, it will be pretty dead if it gets added to Tachi, there are a lot of other sites that do have their content. It was the reason why it didn't make it into Tachi before.

I don't see why MHScans being added to Tachi would be _so frowned upon._
A lot of people use Tachi (& forks), it can become more famous through Tachi, and, sum at least I do, is that I always go to the sites, for example, to read comments or discover other stuff in it.

But yeah, I can understand why someone wouldn't want it to be added anyway.
