### ISSUE TITLE
Naver series to Naver Webtoon

### ISSUE THREAD

**Issue by MVK121** [keiyoushi/tachiyomi-extensions-source#1905]
### Source name

Naver Series

### Source link

series.naver.com

### Source language

Korean

### Other details

This has been reported by the user YoRHaOS on discord. For the full conversation you can look it up. 

Manwha like 당신이 원하는 게 제 심장인가요 can't be found on the existing Naver extension because it uses comic.naver instead of m.comic.naver it was suggested on discord if Naver Series can be added under the existing Naver Webtoon extension 

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by MVK121** [comment]
It is a mistake. The existing extension can't be used to look up Manwha like 당신이 원하는 게 제 심장인가요 I was recommend by the support team to report it here. Apologies for the misunderstanding

**Comment by MVK121** [comment]
I edited the original request

**Comment by Norsze** [comment]
You have it a bit backwards, the source link is series.naver.com, not comic.naver.com. That is why the bot closed it. Cause the current extension already pulls titles from comic.naver.com, but not from series.naver.com

Change the source to the right link.

**Comment by MVK121** [comment]
Apologies for the time waste. I have edited it thank you

**Comment by Norsze** [comment]
You'll have to remake the same issue but with the right info, can't reopen issues.
