### ISSUE TITLE
Add back Dimanba

### ISSUE THREAD

**Issue by NeKoOuO** [keiyoushi/tachiyomi-extensions-source#1908]
### Source name

Dimanba

### Source link

https://www.dimanba.com

### Source language

Chinese 

### Other details
Still alive 
https://github.com/keiyoushi/extensions-source/issues/837

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
It's now the same as 嘀嗒漫画 (Dida Manhua).
