### ISSUE TITLE
Can't open input stream

### ISSUE THREAD

**Issue by Austmage** [keiyoushi/tachiyomi-extensions-source#1919]
### Source information

Mangalife 1.4.28 

### Source language

English

### Steps to reproduce

Step 1: downloading any chapters of any manga from any source
Step 2: downloads until for example 15/16 chapters
Step 3: sends me a notification that i have recieved the error "can't open input stream"

### Expected behavior

I followed the steps provided and added the extension repo, I've tried downloading the same manga from various sources as well, still hit with this issue, expected behaviour is that it should work as i don't think i did anything wrong, i even reinstalled.

### Actual behavior

Can't open input stream.

### Mihon/Tachiyomi version

0.16.4

### Android version

Samsung galaxy s21+

### Other details

Hello. I'm facing this issue where if i try to download any chapters from any manga, I'm notified that i have received a "Can't open input stream" error. I have found the source of this issue, where i have to go into settings > downloads > and turn off "save as CBZ archive". I can download any chapter now, but I'm hit with another issue, after downloading any chapters, when i click into a manga, it dosent show that the manga is downloaded.
I have went into my phone's files, and the downloaded chapters are there, saved as; for example, "chapter 72_tmp". I even pressed into the file and verified that there were images in the file. I have also tried the "invalidate download index" option, but it doesn't work as well.  My storage location for the files should be correct as well; i store them in /storage/emulated/0/mihon, where "mihon" is a folder i created for mihon to store it's files.
I also face the same issue on tachiyomi as well. The extension source I'm using is: https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json
I have deleted all files and reinstalled everything from scratch, turned on "save as cbz files" again, but still hit with the same issues. I have also went to mihon's discord, they told me the issue is with the extensions, that's why I'm here now.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
likely a network issue, come to our discord for help
