### ISSUE TITLE
MangaLek : Automatic link redirection

### ISSUE THREAD

**Issue by LoverFreedom** [keiyoushi/tachiyomi-extensions-source#1936]
### Source information

MangaLek 1.4.39

### Source language

Arabic 

### Source new URL

https://lekmanga.net/

### Other details

The link redirects automatically 
![Screenshot_٢٠٢٤٠٣١٧-٠١٤١٣٣_Mihon](https://github.com/keiyoushi/extensions-source/assets/162794866/e1bd921b-13b8-497e-8649-d5f5d748e336)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by BLACKxSUN** [comment]
@mohamedotaku if you have time can you take this task plz
