### ISSUE TITLE
Covers not updated

### ISSUE THREAD

**Issue by cruzerzix** [keiyoushi/tachiyomi-extensions-source#1941]
### Source information

Hentai2Read 1.4.14

### Source language

English

### Steps to reproduce

Open source Hentai2Read
Press Popular
Don't show covers, except previous favorited mangas
Press Recent
Don't show covers, except previous favorited mangas

You can read the chapter but the covers shows a broken file 

### Expected behavior

Press any thumbnail
Show manga covers

### Actual behavior

For any thumbnail: Don't show covers, except previous favorited mangas. Shows a broken image file 

### Mihon/Tachiyomi version

0.16.4

### Android version

12 (SDK31)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Search the issues before opening a new one, duplicate of #1776
