### ISSUE TITLE
ComicExtra: URL redirects/changed

### ISSUE THREAD

**Issue by Smol-Ame** [keiyoushi/tachiyomi-extensions-source#1951]
### Source information

ComicExtra 1.4.14

### Source language

English

### Source new URL

https://comicextra.org/

### Other details

Latest page doesn't load, Popular page does load but no pages found for chapters

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Site doesn't even work, not much that can be done from the extension side in these cases. Will probably have to wait it out.
![image](https://github.com/keiyoushi/extensions-source/assets/13540478/333b6ca3-c151-4de1-9b38-bab18bfa19d6)
