### ISSUE TITLE
Japscan: Opening Latest page crashes app

### ISSUE THREAD

**Issue by Smol-Ame** [keiyoushi/tachiyomi-extensions-source#1952]
### Source information

Japscan 1.4.44

### Source language

French

### Steps to reproduce

Go the source to search/view Popular/Latest
Popular page loads up, but Latest page crashes the app
![Screenshot_20240317_101836_Mihon](https://github.com/keiyoushi/extensions-source/assets/155411819/00057f24-454f-4821-a619-0e14030c784c)

### Expected behavior

Should load page & give error

### Actual behavior

Crashes the app

### Mihon/Tachiyomi version

Mihon 0.16.4 / TachiSY r550 equivalent

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Latest section for Japscan is not implemented, if that's what you mean ?
