### ISSUE TITLE
Omega Scans Extention not working

### ISSUE THREAD

**Issue by Yuit0** [keiyoushi/tachiyomi-extensions-source#1953]
### Source information

Omega Scans

### Source language

English

### Steps to reproduce

When going to "browse" then "Source" then Omega scans its just empty + it doesnt update the manga in library
![Screenshot_20240318_005140_Mihon](https://github.com/keiyoushi/extensions-source/assets/163790390/f64ce6e5-68f4-4d3a-858a-0bbf27cb3dc9)

### Expected behavior

It should be full with manga / manwha and update the manga / manwha when refreshed

### Actual behavior

Its empty like shown in the picture and wont update manga / manwha in library
![Screenshot_20240318_005140_Mihon](https://github.com/keiyoushi/extensions-source/assets/163790390/40fab961-d7a9-4c1f-867c-b34688faf945)

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Devilo96** [comment]
They change the Url to Org
