### ISSUE TITLE
Omega Scans

### ISSUE THREAD

**Issue by Enmadou** [keiyoushi/tachiyomi-extensions-source#1961]
### Source information

No results foiund

### Source language

english

### Steps to reproduce

first step - sources
second step - "click latest" 
third step - no result found

### Expected behavior

display latest chapters 

### Actual behavior

no result found

### Mihon/Tachiyomi version

Mihon - 0.16.4, Tachiyomi -0.15.3 

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #1953

Search the issues next time before opening a new request & ticking the acknowledgement that you did
