### ISSUE TITLE
OmegaScans not working

### ISSUE THREAD

**Issue by manavchaudhary1** [keiyoushi/tachiyomi-extensions-source#1965]
### Source information

Omega scans 1.4.1

### Source language

English

### Steps to reproduce

Just open the extension 

### Expected behavior

"No result Found"  Shown

### Actual behavior

Should open library

### Mihon/Tachiyomi version

Latest

### Android version

Android 11

### Other details

They updates their website .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [ ] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by manavchaudhary1** [comment]
Now i have checked !

**Comment by Norsze** [comment]
still duplicate of #1953
