### ISSUE TITLE
Omega Scans Url Change 

### ISSUE THREAD

**Issue by Devilo96** [keiyoushi/tachiyomi-extensions-source#1971]
### Source information

Omegascans

### Source language

English

### Source new URL

https://omegascans.org/

### Other details

Omega Scans Url change from .com to .org

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Stop opening new issue requests, you already saw there was one open & responded to it (#1953). Plus a contributor has already provided a fix that hasn't been implemented yet (#1969)
