### ISSUE TITLE
Asura Scans path for scans changed

### ISSUE THREAD

**Issue by TZR-Redstonemaniac** [keiyoushi/tachiyomi-extensions-source#1972]
### Source information

Asura Scans 1.4.32

### Source language

English

### Source new URL

asuratoon.com

### Other details

Now, if I want to open Omniscient Readers Viewpoint, the URL isn't "https://asuratoon.com/manga/omniscient-readers-viewpoint/" anymore, it's "https://asuratoon.com/manga/4555060900-omniscient-readers-viewpoint/", and this is for every scan from them. This only occurs when I try and update or use webview from my library, but not when I do it from the extension page.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Migrate your Asura titles to Asura to fix it

**Comment by AwkwardPeak7** [comment]
Enabled dynamic URLs in extension settings and refresh title
