### ISSUE TITLE
cubari: chapter is missing on the app but is available on the source.

### ISSUE THREAD

**Issue by 888lucky** [keiyoushi/tachiyomi-extensions-source#1973]
### Source information

Cubari 

### Source language

Multi

### Steps to reproduce

1.first step- copy and paste this link on the cubari extension, "cubari:gist/cmF3L0ltcGVyYXRvcldlZWJpbXVzL0tpbWktV2EtU3VraW5vc2F1cnVzL21hc3Rlci9TaW5uZXIlMjBvZiUyMHRoZSUyMEF6dXJlJTIwQWJ5c3MuanNvbg".   
2.second step- add manga to Library.
![Screenshot_2024-03-19-14-25-06-707_eu kanade tachiyomi sy](https://github.com/keiyoushi/extensions-source/assets/163991974/a118405d-aad2-4811-9767-095074904a79)

{manga link- [https://cubari.moe/read/gist/cmF3L0ltcGVyYXRvcldlZWJpbXVzL0tpbWktV2EtU3VraW5vc2F1cnVzL21hc3Rlci9TaW5uZXIlMjBvZiUyMHRoZSUyMEF6dXJlJTIwQWJ5c3MuanNvbg/](url)}

### Expected behavior

should contain all the chapters from the source site.

### Actual behavior

chapter 2 is missing on the app, but can be viewed on the webview of this source
![Uploading Screenshot_2024-03-19-12-34-31-130_eu.kanade.tachiyomi.sy.jpg…]()

### Mihon/Tachiyomi version

TachiyomiSY 1.10.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DokterKaj** [comment]
This is an issue with the gist, not the extension. The maker of the gist mistakenly made the URL of Ch 2 the same as Ch 3, and since Tachiyomi uniquely identifies chapters by their URL, it only displays it once. You can close this issue and ask the maker of the gist to correct Ch 2's URL.
