### ISSUE TITLE
Nhentai - Issue when downloading manga

### ISSUE THREAD

**Issue by Testinger** [keiyoushi/tachiyomi-extensions-source#1974]
### Source information

NHentai 1.4.40

### Source language

English

### Steps to reproduce

1. Browse or Pick some specific manga (added manga title sample in comment)
2. Download file

### Expected behavior

The file should be saved as cbz file, the download process finished, and showed on gallery as Downloaded

### Actual behavior

The data was saved, but not in .cbz format. the folder inside still have _tmp ending, the "|" (vertical glyph) character became "_" (underscore) character [EDIT : this is false alarm, some titles can be downloaded properly). The app notification shows "can't open InputStream" error, the (not cbz) file was not detected as Downloaded, and the download progress stuck at full bar but not downloaded.

### Mihon/Tachiyomi version

Stable 0.16.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Testinger** [comment]
Sorry, the vertical glyph thingy is false alarm. It just happens in some titles, but I have no idea what caused it. Some title examples that I caught including :

- (C89) [Kaminari-neko (Eitarou)] Yamikoi -Saimin- 3 (Nisekoi) [English] [mustbedreaming]
- [AKYS Honpo] Gal no Ongaeshi [English] [Fated Circle]
- [Ojo] Hatsujou! Namaiki JK | Horny! Cheeky JK [English] {5 a.m.}

**Comment by Norsze** [comment]
I don't have this issue, all of them worked fine. Can't reproduce

**Comment by boegill** [comment]
same issue for me but for all extension. basicly the problem started since the implosion started and we got to do repo and stuff. but on other device the download which storage location on SD card works fine as far as i see while other which has issue on internal memory

**Comment by AwkwardPeak7** [comment]
cannot reproduce, maybe your internet related issue; you can come to our discord for help
