### ISSUE TITLE
Magus manga

### ISSUE THREAD

**Issue by Elinosorry** [keiyoushi/tachiyomi-extensions-source#1978]
### Source information

Magus manga 1.4.33

### Source language

English

### Steps to reproduce

1. Use the extension
2. Enter a random entry
3. It says no chapters found

### Expected behavior

When entering the entries the chapters should appear

### Actual behavior

All the entries have no chapters

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by razhterize** [comment]
MagusManga have merged with kaiscans, thus making chapters in `vofeg.com` unavailable

**Comment by Norsze** [comment]
Seems to work fine now, I tried multiple entries and so did Jason and we got no errors
