### ISSUE TITLE
Omega Scans source no results 

### ISSUE THREAD

**Issue by blaizeris** [keiyoushi/tachiyomi-extensions-source#1979]
### Source information

Omega Scans 1.4.38

### Source language

English

### Steps to reproduce

1.Open extension
2.Open webview

### Expected behavior

Should open omega scans library

### Actual behavior

The source show no results found from omega scans but webview is still working 

### Mihon/Tachiyomi version

Tachiyomi 15.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
1) Next time search the issues before opening a new issue request
2) Don't blindly accept the acknowledgements like a clown
3) Update your extension, it's been fixed. Then migrate your titles from Omega to Omega

**Comment by blaizeris** [comment]
Well i'm not that well versed with github 
I tried searching for an issue, didn't find one so i made a request not knowing the issue was already being handled.
Apologies for not knowing how to use github properly i'll do better next time 

thanks for the help :)
