### ISSUE TITLE
Plot twist no fansub no muestra resultados 

### ISSUE THREAD

**Issue by Simpyke** [keiyoushi/tachiyomi-extensions-source#1982]
### Source information

Plot Twist No Fansub 1.4.1

### Source language

Español

### Steps to reproduce

1. abrir extensión y observar resultados
2. Explorar/ elegir título a seguir/ leer 

### Expected behavior

Al abrir la extensión se deberían observar los títulos con los que el scan cuanta para poder leer o en su caso seguir el mangan del agrado de cada uno

### Actual behavior

Al abrir la extensión esta no muestra ningún contenido

### Mihon/Tachiyomi version

Stable 0.15.3

### Android version

8.1.0

### Other details

![Screenshot_20240319-115053](https://github.com/keiyoushi/extensions-source/assets/150213898/56ee6426-94d8-4c69-9c98-7899472000ac)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KatoMegushua** [comment]
Same...

**Comment by Proxy-E23** [comment]
```
! Unexpected JSON token at offset 0: Expected start of the array '[', but had 'EOF' instead at path: $
JSON input: 0

```
Creo que este error debieron agregarlo en Other details
