### ISSUE TITLE
Tachiyomi

### ISSUE THREAD

**Issue by Elbia00** [keiyoushi/tachiyomi-extensions-source#1987]
### Source information

https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json

### Source language

All

### Source new URL

https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json

### Other details

https://github.com/Elbia00/Elbia.git

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Eagle1337** [comment]
You're asking us to change the link to the same link and give you credit?
