### ISSUE TITLE
Shinigami (ID), Http Error 429 when global update

### ISSUE THREAD

**Issue by 4lphards** [keiyoushi/tachiyomi-extensions-source#199]
### Source information

Shinigami 1.4.43

### Source language

Indonesia

### Steps to reproduce

1. Global Update
2. Update failed, error message: "HTTP error 429."

### Expected behavior

some comics are getting updates

### Actual behavior

come comics don't getting updates 

### Tachiyomi version

0.15.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by C0rvidae** [comment]
Can you provide an example of one comic that works and one comic that doesn't work please?

**Comment by 4lphards** [comment]
![WhatsApp Image 2024-01-13 at 21 09 14](https://github.com/keiyoushi/extensions-source/assets/116556151/6ada357e-1429-405b-891f-3a1ae5c4c942)
This is the first attempt when doing a global update

![WhatsApp Image 2024-01-13 at 21 09 36](https://github.com/keiyoushi/extensions-source/assets/116556151/7e49afdf-7e88-49fc-8e6c-927b91011681)
This is the second attempt.

![WhatsApp Image 2024-01-13 at 21 09 23](https://github.com/keiyoushi/extensions-source/assets/116556151/c93be18e-52a4-4590-9c04-e0a6e549b5e9)
This is the top list of my comics on Shinigami extension.

I have a total of 36 comics on Shinigami, only 4 comics **(Top 4 on my list)** managed to get an update, 32 of them failed to get an update due to Http Error 429 which is too many requests, If I am not mistaken.

**Comment by WEPOXS** [comment]
you just need a manual update 💀

**Comment by 4lphards** [comment]
I checked on this site,
https://tachiyomi.org/docs/guides/troubleshooting/common-issues

it says Report the issue to add rate limits and prevent future IP bans.

**Comment by WEPOXS** [comment]
I also experienced this, but when there is a new chapter it will still provide notification of new chapter updates, so just relax 

![Screenshot_20240114_115334_Tachiyomi.jpg](https://github.com/keiyoushi/extensions-source/assets/146017577/ab53b58f-e196-46e0-8c72-5cb29f1ab0e4)

like this one
