### ISSUE TITLE
Bato Couldn't Find Image

### ISSUE THREAD

**Issue by PlumBlossoms13** [keiyoushi/tachiyomi-extensions-source#2]
### Source information

Bato 1.4.32

### Source language

All

### Steps to reproduce

1. Open chapter on Bato
2. Instead of being able to read the chapter, gets "couldn't find script with image data" message

### Expected behavior

Should be able to read chapter

### Actual behavior

The chapter closes instead with above message

### Tachiyomi version

Tachiyomi J2K 1.7.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Closed by #1
