### ISSUE TITLE
Update Arven Scans URL and Name

### ISSUE THREAD

**Issue by JIINNN01** [keiyoushi/tachiyomi-extensions-source#2015]
### Source information

Arven Scans 1.4.30

### Source language

English

### Source new URL

https://vortexscans.com/

### Other details

Source changed their name and URL. Old URL redirects to the new site.
New Name - VORTEX SCANS

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Icons: [ic_launcher.zip](https://github.com/keiyoushi/extensions-source/files/14705900/ic_launcher.zip)

**Comment by Pentha12** [comment]
No update after a week

**Comment by Smol-Ame** [comment]
> No update after a week

Everything is maintained from contributors volunteering their time. It'll be worked on if possible & if someone is willing to. Please don't comment without reason or extra info to help contributors.

**Comment by ManiV97** [comment]
Can you please tell me any update..
