### ISSUE TITLE
المصدر لا يعمل

### ISSUE THREAD

**Issue by Safwam-daw** [keiyoushi/tachiyomi-extensions-source#2027]
### Source information

Mangalek 1.4.39

### Source language

العربية

### Steps to reproduce

The first step: open the source ، The problem here
Step two: Open the website, no problem

### Expected behavior

1- About open source manga is supposed to appear
2- When you open the site, the original site should appear

### Actual behavior

1- The manga does not appear and gives an error message
2- The site appears and there is no problem 

### Mihon/Tachiyomi version

App version: 0.14.7 (standard, c8d6859, 102, 2023-10-25T16:11Z) Android version: 12 (SDK 31) Android build ID: SP1A.210812.016.A217FXXSADWI1 Device brand: samsung Device manufacturer: samsung Device name: a21s Device model: SM-A217F Device product name: a21snnxx

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [ ] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Also, duplicate of #1936 or  #1999
