### ISSUE TITLE
Ler Mangas

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#2034]
### Source name

Ler Mangas

### Source link

https://lermangas.me

### Source language

Brazilian Portuguese

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by nomaxsnx** [comment]
thema: madara

**Comment by nomaxsnx** [comment]
icons:  [ic_launcher.zip](https://github.com/keiyoushi/extensions-source/files/14724861/ic_launcher.zip)

obs: apparently, you have to fix the logo (since it's coming out along with the text), I'm too lazy to mess with photoshop '-'.
