### ISSUE TITLE
Certain VyvyManga entries not working

### ISSUE THREAD

**Issue by SheepCommander** [keiyoushi/tachiyomi-extensions-source#204]
### Source information

VyvyManga 1.4.4

### Source language

English

### Steps to reproduce

First I added the one click extensions list, then i deleted all existing extensions then restarted app then installed VyvyManga again
1. Search "This is Obviously a Yuri Manhua" in Vyvyscans
2. Try to read it or download it
3. It gives an error in both cases (no pages found) (download failed), despite it working if you copy link then read in browser

(Weird note: tapping "open in web browser" causes the page to briefly open then immediately redirect you to Google.com. However, copying the link and opening it in a web browser works properly and gives you an 18+ popup)

### Expected behavior

Should be no error and content should load!

(Also web view probably shouldn't automatically redirect you to Google.com)

### Actual behavior

Error trying to load pages

### Tachiyomi version

0.15.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by SheepCommander** [comment]
This also happens on multiple other entries, but many other entries *do* work

**Comment by SnakeDoc83** [comment]
The web view redirect is due to javascript on the source's side forwarding you away from the page under certain circumstances. Their website is kind of cancerous; so entries not working are probably due to them trying to do shady redirects or defeat scrapers. If you can provide another example when you notice it and someone can take a look right away maybe they'll see something more, but honestly you're probably better off trying a different source.

**Comment by SheepCommander** [comment]
true vyvyscans does seem like a hell-on-earth dev experience, but it feels like it has a surprising amount of yuri that dynasty and MD dont have

**Comment by reygrey666** [comment]
I got the same problem, but in my case it can be solved by tap refresh before reading or downloading the stuff. I should do that everytime I open the app.

**Comment by Willowthebun** [comment]
Summer, Lemon, and Overlay is experiencing issues, not loading chapters and webview redirects to googles homepage

**Comment by SheepCommander** [comment]
you need to change the user agent

**Comment by SheepCommander** [comment]
Is this still an issue? I haven't used either of the new vyvymanga extensions yet

**Comment by vetleledaal** [comment]
> Is this still an issue?

Doesn't seem like it. Closing.
