### ISSUE TITLE
Lura toon erro

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#2049]
### Source information

Lura Toon 1.4.42

### Source language

Português (Brasil)

### Steps to reproduce

Não carrega nada fica dando erro 
![Screenshot_20240323-033007](https://github.com/keiyoushi/extensions-source/assets/157044539/9314d27c-a720-4d89-b7a3-841f1c448ed3)

### Expected behavior

O Webview funciona 
![Screenshot_20240323-033417](https://github.com/keiyoushi/extensions-source/assets/157044539/3ddba778-f1dd-485c-9144-e961daf6358c)

### Actual behavior

.

### Mihon/Tachiyomi version

Mihon 0.16.4

### Android version

Android 11

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
(TL) Houve um problema com a fixação OCSP, mas parece estar resolvido agora. Você pode confirmar se o problema foi corrigido em seu lado? Talvez seja necessário reiniciar o aplicativo ou limpar o cache nas configurações.

**Comment by nomaxsnx** [comment]
![Screenshot_2024-03-24-01-31-36-115_app mihon](https://github.com/keiyoushi/extensions-source/assets/157644160/894c81bd-31bb-4b31-a614-693a25dd905a)

**Comment by ghost** [comment]
Agora tá funcionando normalmente, obrigado
