### ISSUE TITLE
Error accessing madokami through tachiyomi j2k and sy 

### ISSUE THREAD

**Issue by gosndka** [keiyoushi/tachiyomi-extensions-source#2050]
### Source information

Madokami 1.4.8

### Source language

English

### Steps to reproduce

1. Install madokami extension
2. try to open the webview
3. if one has username and password, you can access the site.

### Expected behavior

After setting up all the above including login details a user can read manga from the site

### Actual behavior

But instead I get this kind of error

![316222486-156149e7-cd5c-47f6-ae35-357780edcb36](https://github.com/keiyoushi/extensions-source/assets/92586328/51f27549-0037-48e8-bba5-a003614e3b22)

### Mihon/Tachiyomi version

1.10.5

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
that is ssl error, you might need to install a certificate, come to our discord for help with that
