### ISSUE TITLE
Ninehentai - url changed to 9hentai.to to 9hentai.com

### ISSUE THREAD

**Issue by Shiroe256** [keiyoushi/tachiyomi-extensions-source#2063]
### Source information

Ninehentai 1.4.2

### Source language

English

### Source new URL

https://9hentai.com/

### Other details

HTTP 405. When I view it in webview the url changes from 9hentai.to to 9hentai.com. Please check if that is correct

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate/Part of #2046
