### ISSUE TITLE
nhentai.net is not available

### ISSUE THREAD

**Issue by JazzterSG** [keiyoushi/tachiyomi-extensions-source#2065]
### Source information

Nhentai 1.4.40

### Source language

Multi, English

### Source new URL

://nhentai.to

### Other details

just that.
you can also use other urls like ".name" etc. do what you want. 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
NH is working perfectly fine, do some troubleshooting or check in the Discord for help next time

Put a little more effort in before opening a request
