### ISSUE TITLE
Error 405

### ISSUE THREAD

**Issue by X2ZANDER** [keiyoushi/tachiyomi-extensions-source#2067]
### Source information

Ninehentai 1.4.2

### Source language

English

### Steps to reproduce

When I open the nine hentai it show http 405
When I open the web view it work and did not show 405 

### Expected behavior

When open the ninehentai, it should show a hentai 

### Actual behavior

When open the nine hentai, it show http 405

### Mihon/Tachiyomi version

0.6.14

### Android version

Android vivo Y15A

### Other details

When I open web site view , it work and not show any error but the extension show error
Btw sorry for my bad grammar
![Screenshot_20240324_015807]

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #2046 & #2063

Search the issues before opening a new one & blindly accepting the acknowledgement that you checked. Also don't blindly accept the acknowledgements without reading them
