### ISSUE TITLE
There is none turkish source

### ISSUE THREAD

**Issue by MythiGhost** [keiyoushi/tachiyomi-extensions-source#2070]
### Source name

Webtoontr

### Source link

https://webtoontr.net/

### Source language

Turkish

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Did you enable the Turkish language in your Extensions list & then enable it in your Sources list?

Tachi/Mihon has Multi & English enabled as default
