### ISSUE TITLE
Scylla Scans website is back up

### ISSUE THREAD

**Issue by vipzzx** [keiyoushi/tachiyomi-extensions-source#2090]
### Source information

Scylla Scans 1.4.9

### Source language

English 

### Steps to reproduce

Extension not loading at all

### Expected behavior

Should load

### Actual behavior

Should load

### Mihon/Tachiyomi version

Tachij2k 1.7.4

### Android version

Android 14

### Other details

Website has changed their formating too from previous formating.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Uses same theme as [en.cloudrecess](https://github.com/keiyoushi/extensions-source/tree/59c3a8d9acde0e967d31320ea93860bfa49bb542/src/en/cloudrecess/src/eu/kanade/tachiyomi/extension/en/cloudrecess) and [ar.hentaislayer](https://github.com/keiyoushi/extensions-source/tree/59c3a8d9acde0e967d31320ea93860bfa49bb542/src/ar/hentaislayer/src/eu/kanade/tachiyomi/extension/ar/hentaislayer) (this is a bit different)

**Comment by nobile01** [comment]
When checking the extension I get the error "Couldn't reach api.scyllascans.org: NXDOMAIN" but when I open on Webview, the site loads.
