### ISSUE TITLE
Not this time

### ISSUE THREAD

**Issue by Anasplus** [keiyoushi/tachiyomi-extensions-source#2094]
### Source information

MangaSwat 1.4.42

### Source language

Arabic

### Source new URL

https://swatmanhua.com/

### Other details

This source does not accept downloading, and The strangest thing is that it has a sign that an update is available, and the update in turn does not accept downloading

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Update your extension, the latest MangaSwat version is 1.4.47 & doesn't seem to have any issues.

**Comment by Anasplus** [comment]
![Screenshot_20240325-041738_Package installer](https://github.com/keiyoushi/extensions-source/assets/164819656/93ba8899-2901-4426-b9ed-286716e5027b)
this is the problem This is the problem I have 13 sources that do not accept the update

**Comment by Norsze** [comment]
If you can't update, then uninstall it and reinstall the extensions in question

**Comment by Smol-Ame** [comment]
^

If it still doesn't work, try giving it "Install unknown apps" permission again, and updating your app (if possible).

Otherwise, hop in the Keiyoushi Discord for troubleshooting

**Comment by Anasplus** [comment]
Thanks
