### ISSUE TITLE
Tenkaiscan not working

### ISSUE THREAD

**Issue by Urulokke** [keiyoushi/tachiyomi-extensions-source#2096]
### Source information

Tenkaiscan 1.4.35

### Source language

Español

### Steps to reproduce

Http 503, but the webview shows the page correctly

### Expected behavior

Show all the Mangas from the page

### Actual behavior

Shows an 503 http error 

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
Duplicate of #2149
