### ISSUE TITLE
Hentai2Read still buggy

### ISSUE THREAD

**Issue by blackheart911126** [keiyoushi/tachiyomi-extensions-source#2099]
### Source information

Hentai2Read 1.4.15

### Source language

English

### Steps to reproduce

1. Open extension
2. Some thumbnail still broken especially those in the library

### Expected behavior

Thumbnail shown

### Mihon/Tachiyomi version

TachiyomiJ2K 1.7.4

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Seems fine on my end, J2K & Mihon. Try clearing the extension's cookies (Browse Page > Extensions Tab > Extension Settings > Three-dots)

If not, try changing user-agent & restarting the app

**Comment by blackheart911126** [comment]
> Seems fine on my end, J2K & Mihon. Try clearing the extension's cookies (Browse Page > Extensions Tab > Extension Settings > Three-dots)
> 
> If not, try changing user-agent & restarting the app

May I know your user agent?

**Comment by AwkwardPeak7** [comment]
clear database in advanced settings

@blackheart911126 also don't post nsfw images

**Comment by Smol-Ame** [comment]
> May I know your user agent?

It's just a guess, and what works for someone might not work for you. I'm using the stock user-agent.

(Follow AwkwardPeak's solution over mine instead)

**Comment by blackheart911126** [comment]
> clear database in advanced settings
> 
> @blackheart911126 also don't post nsfw images

Sorry, tried to cut it off but didn't realized there's one NSFW there..

**Comment by blackheart911126** [comment]
> Seems fine on my end, J2K & Mihon. Try clearing the extension's cookies (Browse Page > Extensions Tab > Extension Settings > Three-dots)
> 
> If not, try changing user-agent & restarting the app

Tried on Mihon and it works.. but TachiyomiJ2K failed.. maybe TachiyomiJ2K needed update..

**Comment by blackheart911126** [comment]
> clear database in advanced settings
> 
> @blackheart911126 also don't post nsfw images

Tried on Mihon and worked perfectly.. Tried on TachiyomiJ2K and fails..
