### ISSUE TITLE
Covers not loading for entries already in the library in Hentai2Read

### ISSUE THREAD

**Issue by arponroyovi** [keiyoushi/tachiyomi-extensions-source#2102]
### Source information

Hentai2Read 1.4.15

### Source language

English

### Steps to reproduce

Open Any already existing titles/entries form library or through browse
Covers do not load even after refreshing library covers
![Screenshot_20240325-181952_Mihon](https://github.com/keiyoushi/extensions-source/assets/63045686/e493410b-11a4-4b4f-87e7-5bd22bb37d21)
![Screenshot_20240325-182043_Mihon](https://github.com/keiyoushi/extensions-source/assets/63045686/9046f0c7-4aa1-45cc-adef-c5696c5bb25b)

### Expected behavior

All covers should load
![Screenshot_20240325-182915_Mihon-01](https://github.com/keiyoushi/extensions-source/assets/63045686/a6c64834-724c-4198-b34c-1a8ca547a6ff)

### Actual behavior

Only covers of newer entries are loading.
The ones with black covers are already in the library 
![Screenshot_20240325-182959_Mihon-01](https://github.com/keiyoushi/extensions-source/assets/63045686/3cdaa7d0-b911-4471-b4fd-1a9181eb42aa)

### Mihon/Tachiyomi version

Mihon Stable 0.16.4

### Android version

Android 12

### Other details

While the titles that are not in the library are working fine after the latest update (1.4.15), any entry that was previously added to the library is still missing their covers 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arponroyovi** [comment]
I also asked discord support and AwkwardPeak7 said "guess cover parsing is broken in `mangaDetails` too"

**Comment by blackheart911126** [comment]
Hopefully they fix it.. hard to recognize the manga..
