### ISSUE TITLE
Clown Corps skips to chapter covers

### ISSUE THREAD

**Issue by quylaa** [keiyoushi/tachiyomi-extensions-source#2107]
### Source information

Clown Corps 1.4.1

### Source language

English

### Steps to reproduce

1. Open any page of Clown Corps
2. Swipe to the next page
3. It skips to the cover of the next chapter

Example: https://i.imgur.com/s4ygwcF.mp4 

### Expected behavior

Mihon should open and display the pages in the correct sequence.

### Actual behavior

Mihon only displays the chapter cover pages.

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by quylaa** [comment]
@altaccosc

**Comment by altaccosc** [comment]
I cannot reproduce this on Tachiyomi 0.15.3.
Perhaps Mihon has changed something in the order detection or something?

**Comment by altaccosc** [comment]
Although I may have an idea to fix it...

**Comment by altaccosc** [comment]
Let's see if this fixes it...

I think you can download the APK when the mods have decided that my PR is safe and allowed the build to run.
Once that's happened, please download it and let me know if it indeed fixed the issue :)

**Comment by AwkwardPeak7** [comment]
Disable "skip duplicate chapters" in reader settings

**Comment by quylaa** [comment]
> Disable "skip duplicate chapters" in reader settings

This fixed it. I wonder why each page is considered a duplicate chapter?

**Comment by altaccosc** [comment]
Because the names are "chapter 1 page 2" and "chapter 3 page 42" etc
Tachiyomi/Mihon gets a little confused by that.
I built a fix for that, but it wasn't accepted, sorry.
