### ISSUE TITLE
Need an unofficial extension making guideline

### ISSUE THREAD

**Issue by Livid96** [keiyoushi/tachiyomi-extensions-source#213]
### Describe why this should be added

Old guideline about creating an extension is no more..

- Please provide a new guideline about creating unofficial extension.

![Screenshot_20240113-164948](https://github.com/keiyoushi/extensions-source/assets/128045849/55fb0c78-a2a0-439b-b71f-eb7c61aaebe5)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
There is already one: https://github.com/keiyoushi/extensions-source/blob/main/CONTRIBUTING.md
