### ISSUE TITLE
COLAMANGA blocked the source 

### ISSUE THREAD

**Issue by NeKoOuO** [keiyoushi/tachiyomi-extensions-source#2133]
### Source information

COLAMANGA 1.4.18

### Source language

Chinese 

### Steps to reproduce

403 on webview 

### Expected behavior

 It should worked normally

### Actual behavior

The website blocked if you don't use normal browser 
![IMG_20240328_160246.jpg](https://github.com/keiyoushi/extensions-source/assets/111511925/d47c672e-4a65-4d50-bec5-d0ec0fefda43)
And it says 
"Please view with a normal browser, as some special browsers or tools may encounter issues. 
Opening multiple tabs simultaneously may also cause issues. 
Try to read with just one or two tabs open, as having multiple tabs open may lead to problems. 
Using Chrome (Google browser) on a computer or a mobile device generally should not cause this problem. 
If you have confirmed that there are no abnormal operations, please contact us via email for analysis and resolution. 
To conduct an analysis, provide the access IP: /dynamic/getaccessip 
Switching browsers may temporarily resolve the issue, but if the problem persists after switching, it likely means there is an issue with the way you are accessing the site. Please contact us via email for analysis, as otherwise it may result in the entire IP being blocked."

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Try adjusting the extension's settings to see if it helps, along with clearing the extension's cookies & clearing WebView cookies.

Also try changing the user-agent to see if that helps (if necessary)

**Comment by NeKoOuO** [comment]
> Try adjusting the extension's settings to see if it helps, along with clearing the extension's cookies & clearing WebView cookies.
> 
> Also try changing the user-agent to see if that helps (if necessary)

This extension didn't add custom user agent

But It worked again when I changed the network

**Comment by Smol-Ame** [comment]
> This extension didn't add custom user agent
> 
> But It worked again when I changed the network

Nice, and I meant the in-app user-agent (Mihon Settings > Advanced)

**Comment by NeKoOuO** [comment]
> Nice, and I meant the in-app user-agent (Mihon Settings > Advanced)

I know but i have already set yet  if i change it another source will not work

**Comment by a0193143** [comment]
I think the update checking process deosn't limit by the setting in extension, is this app side or extention side?
I set the 2 limit to the most conservative, but after checking updates for 20 books, still got a temporary ban.
