### ISSUE TITLE
请求添加新插件《污污漫画》

### ISSUE THREAD

**Issue by keqingf** [keiyoushi/tachiyomi-extensions-source#2134]
### Source name

污污漫画

### Source link

ww.wuwumanhua.site

### Source language

中文

### Other details

18+/NSFW = 是

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by keqingf** [comment]
或者说，如何开发一个插件，我尝试自己动手

**Comment by NeKoOuO** [comment]
@keqingf 
https://github.com/tachiyomiorg/extensions/blob/main/CONTRIBUTING.md
https://github.com/tachiyomiorg/extensions/blob/main/CODE_OF_CONDUCT.md

**Comment by NeKoOuO** [comment]
@keqingf 
[CONTRIBUTING.md](https://github.com/tachiyomiorg/extensions/blob/main/CONTRIBUTING.md)
[CODE_OF_CONDUCT.md](https://github.com/tachiyomiorg/extensions/blob/main/CODE_OF_CONDUCT.md)
你issue都不會用英文寫了 我猜有文檔你應該也看不懂
Also 你的網址少打一個w

**Comment by keqingf** [comment]
确实复制的时候少了一个w

**Comment by Norsze** [comment]
English for titles please

**Comment by NeKoOuO** [comment]
> English for titles please

Nah... I think he simply doesn't know how to change it

**Comment by Norsze** [comment]
> > English for titles please
> 
> Nah... I think he simply doesn't know how to change it

Nah he too stupid to get this repo is in English so the contributors can read it, as are you apparently, hate it when people use rude wordings like "nah" to just disregard people's opinion

**Comment by NeKoOuO** [comment]
> Nah he too stupid to get this repo is in English so the contributors can read it, as are you apparently, hate it when people use rude wordings like "nah" to just disregard people's opinion

I don't really care, in fact
You clearly don't understand what I am trying to express
Well, it takes one to know one calling someone stupid

**Comment by Norsze** [comment]
I agree, you'd know

**Comment by NeKoOuO** [comment]
> I agree, you'd know

Okay

**Comment by AwkwardPeak7** [comment]
Please don't start fights in issues, thank you.
