### ISSUE TITLE
Readallcomics (EN) - Downloads fail with one image left

### ISSUE THREAD

**Issue by Clydefrosch22** [keiyoushi/tachiyomi-extensions-source#2137]
### Source information

ReadAllComics 1.4.2

### Source language

English

### Steps to reproduce

For a while now, recent chapters on this extension failed their downloads one image short of completion, making chapters unreadable offline.

Old chapters seem to typically not be affected and the issue sometimes seems to fix itself at some point, i.e. Rise of the Powers of X 003 fails to download completely for me, so did 002 last month, but today, 002 can be loaded just fine.

Meanwhile Cable v5 002 from last month still fails one image short, so does the current 003 chapter.

Going by the tmp Folder, the issue seems to be with the cover pages, which arent downloaded and cant be viewed by opening the chapter in the app while online. Opening the chapter via webview shows the first image, though it is smaller than the other pages and might have different properties now, for some reason?

This may be intentional behavior to break apps like this, but considering that they still take 99% of the traffic, it might be something else (or they just assumed breaking the first page would break everything...)

Is there an option I dont know about, where tachiyomi ignores failed pages after x attempts or x amounts of time and just delivers what it could get, maybe with a placeholder "couldn't load image" file where it failed?

### Expected behavior

Should load all pages and be vieawble offline

### Actual behavior

One page doesnt load, prevents opening the chapter, might clog up download queue

### Mihon/Tachiyomi version

0.16.4 / 1.10.5

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Cover images are hosted on `s3.amazonaws.com`, while other pages are hosted on `2.bp.blogspot.com`, so there's probably something S3 expects header wise that the extension doesn't send. This kind of issue is usually fixed by adding the `Referer` header.

I can't actually reproduce the issue with the examples you provided, or any of the other comics I tested. Maybe there's only certain conditions when the check is done. Can you test with different VPNs or user-agents? Nothing else should significantly differ from my app to your app.

**Comment by Clydefrosch22** [comment]
i dont have vpn on my tablet, but I tried from both my home and my work wifi, both of which are quite far appart.
the user agent is what I assume is the standard, mozilla/5.0 [...] Firefox/121.0
I changed it to  a newer one Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0 but its not helping.
Do you have a specific one to suggest?

It's definitely not loading the first image of these two chapters, not when trying to download or when opening the chapter normally, I also tried deleting cookies, deleting extension data/cache, thinking that tachiyomi might have cached the assumed download paths and just keeps refering to a borked link list, but it's not helping either.
![Screenshot_20240328-224012_TachiyomiSY](https://github.com/keiyoushi/extensions-source/assets/21969634/267b0a7e-b442-4ce0-9cf1-a7af460f81d7)

Going through some of the recently updated comics of that extension, i couldn't find any more giving me issues right now though, at least for me right now, it only seems to happen to some chapters

**Comment by vetleledaal** [comment]
The only common thing between the chapters you mentioned is that they all have a cover page hosted on `s3.amazonaws.com`. You can try enabling DoH in the app, clearing chapter cache and retrying.

If it works- your browser is using DoH by default, and your normal DNS is blocking `s3.amazonaws.com`
If it doesn't work- no idea

You could also test by disabling DoH / secure DNS in your browser and try to load https://s3.amazonaws.com/comicgeeks/comics/covers/large-3348802.jpg?1711552892

**Comment by Clydefrosch22** [comment]
The image/link loaded perfectly fine in firefox, chrome and samsung browser and when opening it in webview, irregardless of settings

Disabling DNS over https in tachiyomi (it was set to cloudflare) seems to have fixed the problem, thank you.
