### ISSUE TITLE
Add filtering to Vyvy Manga

### ISSUE THREAD

**Issue by kana-shii** [keiyoushi/tachiyomi-extensions-source#2143]
### Source name

VyvyManga

### Source language

English

### Describe your suggested feature

Add filtering options like the ones from the site 
![image](https://github.com/keiyoushi/extensions-source/assets/79055104/474662a5-6aaf-42f4-84e6-bf769ac3f83d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by kana-shii** [comment]
There's no genre options on the update...

**Comment by AwkwardPeak7** [comment]
> There's no genre options on the update...

tap refresh in the filter sheet after loading popular/latest
