### ISSUE TITLE
AllHentai: chapter opening error

### ISSUE THREAD

**Issue by iostik** [keiyoushi/tachiyomi-extensions-source#215]
### Source information

AllHentai 1.4.43

### Source language

Russian

### Steps to reproduce

1. Click on any manga
2. Click on any chapter
3. Error: length=307731; index=-l

### Expected behavior

1. Click on any manga
2. Click on any chapter
3. Show pages

### Actual behavior

1. Click on any manga
2. Click on any chapter
3. Error: length=307731; index=-l

### Tachiyomi version

0.15.2

### Android version

any

### Other details

The problem appeared after the update, there is no error when rollback to the previous version of the extension (1.4.42).
Also this problem appeared in some manga in the ReadManga [ru] extension and in all manga in the MintManga [ru] extension. Rollback to previous version solves the problem in all cases

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by e-shl** [comment]
Fixed https://github.com/keiyoushi/extensions-source/pull/184
