### ISSUE TITLE
Nhentai Not Working

### ISSUE THREAD

**Issue by Kenn876** [keiyoushi/tachiyomi-extensions-source#2153]
### Source information

Nhentai 1.4.40

### Source language

"Multi"

### Steps to reproduce

1. Go to sources
2. Press Nhentai

### Expected behavior

Should be able to view the manga, doujins, etc.

### Actual behavior

It shows the following sentence - failed to connect to/104.27.207.92 (port 443) from/192.168.5.143 (port 59240) after 30000ms

### Mihon/Tachiyomi version

Tachiyomi 0.15.3

### Android version

Android 12

### Other details

Even if you open it in WebView it doesn't work
![Screenshot_20240329_231506](https://github.com/keiyoushi/extensions-source/assets/137243023/dbe68ac4-10c7-406a-b4ab-2ee087db2ae2)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
If it doesn't work in webview then maybe it is down and nothing can be done at the moment...

Back up now, was error 500 earlier

**Comment by vetleledaal** [comment]
Are you using PLDT? They blocked the site recently. You must use a VPN to access it.

**Comment by Kenn876** [comment]
> Are you using PLDT? They blocked the site recently. You must use a VPN to access it.

Wait really? Bro that's weak. Never used a VPN before. Do you have a recommendation on free VPN's? Why the hell would they block that?

**Comment by Kenn876** [comment]
If fucking PLDT goes after any of the other sites I swear man. They are gonna regret.
