### ISSUE TITLE
Add random UA to Lunar Scans

### ISSUE THREAD

**Issue by Serai616** [keiyoushi/tachiyomi-extensions-source#2155]
### Source name

Lunar Scans

### Source language

English

### Describe your suggested feature

Add random UA to Lunar Scans (lunarscan.org) due to cloudflare bypass not working.

### Other details

Ever since random UA was removed from Mangathemesia as it was advised to be added on a per source basis, I have been unable to access Lunar Scans.

The issue has always been a cloudflare issue, so I am unable to access any of the titles within it since.

I understand that it's been a long time since that PR was merged so why ask now? Well I was hoping someone else would notice it eventually that I wouldn't need to open up an issue myself.

Even before that PR was merged however, the site itself has always been a bit finicky in cloudflare bypassing where sometimes it doesn't work, making me fiddle with the random UA settings and clearing the source's cookies to get it working again, sometimes it just fixes itself the next day, it's a bit weird, however having no random UA completely breaks access to the source entirely for me.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
FYI you can change useragent in app settings

https://keiyoushi.github.io/docs/guides/troubleshooting#changing-your-user-agent

**Comment by BlackGrimReaper** [comment]
> FYI you can change useragent in app settings
> 
> https://keiyoushi.github.io/docs/guides/troubleshooting#changing-your-user-agent

The problem's fixed. Tested and it works.
