### ISSUE TITLE
Hentaivn enhanced their protection

### ISSUE THREAD

**Issue by leonminus** [keiyoushi/tachiyomi-extensions-source#2163]
### Source information

HentaiVN 1.4.31

### Source language

Vietnamese

### Steps to reproduce

Can't read bookmarked manga and access library even in webview mode

### Expected behavior

read and watch library as usual

### Actual behavior

failed to connect to hentaivn.tv/127.0.0.1:443

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 12

### Other details

I changed clone URL of Hentaivn: hentaivn.tv, hentaivn.blue, xhentai.com but none of them works

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
If you can't access the source, even in WebView, it's most likely because your internet is blocking the site.

Try switching networks (or try DNS over HTTPS in Mihon Settings > Advanced, or use a VPN), and also double-check the extension's settings (Browse Page > Extensions tab > Hentaivn settings) to see if that could help.

But otherwise, works on my end & seems to be just your internet having an issue with it.

**Comment by leonminus** [comment]
> If you can't access the source, even in WebView, it's most likely because your internet is blocking the site.
> 
> Try switching networks (or try DNS over HTTPS in Mihon Settings > Advanced, or use a VPN), and also double-check the extension's settings (Browse Page > Extensions tab > Hentaivn settings) to see if that could help.
> 
> But otherwise, works on my end & seems to be just your internet having an issue with it.

I had tried vpn in-app and 1.1.1.1, active bypass Cloudflare and changed user agent. But it keeps this error:
"Trang web hiện không khả dụng

Không thể tải trang web tại https://hentaivn.tv/ do:

net::ERR_CONNECTION_RESET"
In their Discord server seems like this web has been block by my internet called FPT. But when i open the web by chrome or my nation browser Coccoc it works normally. Anything else I can do ?

**Comment by Smol-Ame** [comment]
> I had tried vpn in-app and 1.1.1.1, active bypass Cloudflare and changed user agent. But it keeps this error: "Trang web hiện không khả dụng
> 
> Không thể tải trang web tại https://hentaivn.tv/ do:
> 
> net::ERR_CONNECTION_RESET" In their Discord server seems like this web has been block by my internet called FPT. But when i open the web by chrome or my nation browser Coccoc it works normally. Anything else I can do ?

The DNS over HTTPS isn't a VPN, you should try an actual on-device/on-network VPN instead. But if that didn't help, I would try switching networks (WiFi to mobile data, or vice-versa) and see if it's the same result.

I guess also try changing your user-agent (Mihon Settings > Advanced), but I don't think that would help too much since it does seem like an internet/ISP block

**Comment by leonminus** [comment]
> > I had tried vpn in-app and 1.1.1.1, active bypass Cloudflare and changed user agent. But it keeps this error: "Trang web hiện không khả dụng
> > Không thể tải trang web tại https://hentaivn.tv/ do:
> > net::ERR_CONNECTION_RESET" In their Discord server seems like this web has been block by my internet called FPT. But when i open the web by chrome or my nation browser Coccoc it works normally. Anything else I can do ?
> > The DNS over HTTPS isn't a VPN, you should try an actual on-device/on-network VPN instead. But if that didn't help, I would try switching networks (WiFi to mobile data, or vice-versa) and see if it's the same result.
> > I guess also try changing your user-agent (Mihon Settings > Advanced), but I don't think that would help too much since it does seem like an internet/ISP block 

Changed VPN to US and it works but cant use webview to change the option "server 2" and "server auto". A lot of manga missed some page and i have to change to "server 2" right on top of 1st page in web-view mode

**Comment by Smol-Ame** [comment]
> Changed VPN to US and it works but cant use webview to change the option "server 2" and "server auto". A lot of manga missed some page and i have to change to "server 2" right on top of 1st page in web-view mode

Sorry, that's about all that I know (in general) for internet related issues with extensions/sources. I don't know Vietnamese or the source myself, so I'm unable to provide any additional support for this.

Try experimenting with the VPN, along with attempting to switch servers in WebView, then go back into the app to your title, and refresh the title to see if it updates the chapter links (to view the images proper)

**Comment by leonminus** [comment]
> > Changed VPN to US and it works but cant use webview to change the option "server 2" and "server auto". A lot of manga missed some page and i have to change to "server 2" right on top of 1st page in web-view mode
> 
> Sorry, that's about all that I know (in general) for internet related issues with extensions/sources. I don't know Vietnamese or the source myself, so I'm unable to provide any additional support for this.
> 
> Try experimenting with the VPN, along with attempting to switch servers in WebView, then go back into the app to your title, and refresh the title to see if it updates the chapter links (to view the images proper)

Ok, i'll try. Thanks for helping

**Comment by AwkwardPeak7** [comment]
not really extension issue, use vpn to bypass isp block
