### ISSUE TITLE
New Extension MangaMTL

### ISSUE THREAD

**Issue by 4lexUnK** [keiyoushi/tachiyomi-extensions-source#2165]
### Source name

MangaMTL

### Source link

https://mangamtl.com/

### Source language

Spanish

### Other details

+18/NSFW = NO

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
the site "draws" mtl'd text on raw images, and the text is fetched through google translate api. Not really possible to make an extension for this.
