### ISSUE TITLE
Nettruyen url change

### ISSUE THREAD

**Issue by HuyHoang01** [keiyoushi/tachiyomi-extensions-source#2177]
### Source information

Nettruyen 1.4.32

### Source language

Vietnamese

### Source new URL

https://www.nettruyenamp.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Extension still works with the current domain. The domain you mentioned is run by someone else. If you want this added as a new extension you should open a source request issue.

**Comment by cuong-tran** [comment]
nettruyenff is blocked again (still accessible via some network)

Latest is nettruyenhh

![Screenshot_20240330_204148_Facebook.jpg](https://github.com/keiyoushi/extensions-source/assets/16017808/5c6b8467-fafb-4c6d-9690-15c8077fc8d7)

**Comment by HuyHoang01** [comment]
So i just check again and apparently nettruyenff works again
