### ISSUE TITLE
Hunter Scan (original) - Error HTTP 404

### ISSUE THREAD

**Issue by nomaxsnx** [keiyoushi/tachiyomi-extensions-source#2186]
### Source information

Hunter Scan 1.4.36

### Source language

Português 

### Steps to reproduce

1 install de extension
2 open
3 Error HTTP 404

### Expected behavior

![Screenshot_2024-03-30-12-15-26-042_app mihon](https://github.com/keiyoushi/extensions-source/assets/157644160/03a8ede0-dcc8-49f4-b0bc-23eaec952709)

### Actual behavior

After yesterday's maintenance on Hunter, the extension stopped working 

### Mihon/Tachiyomi version

App version: 0.16.4 

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
Theme changed again. Back to the **madara theme**
