### ISSUE TITLE
Add source: SamuraiScan secondary page

### ISSUE THREAD

**Issue by seba1107** [keiyoushi/tachiyomi-extensions-source#2188]
### Source name

SamuraiScan 2

### Source link

https://manhuaonline.org/

### Source language

Spanish

### Other details

It's the secondary page from the existing source "SamuraiScan"

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by mfloresz** [comment]
Samuraiscan.org is accessible but can no longer be read from there, it redirects to the new url mentioned above.

**Comment by seba1107** [comment]
> Samuraiscan.org is accessible but can no longer be read from there, it redirects to the new url mentioned above.

Some titles are still being uploaded to samuraiscan.org while others have been migrated to manhuaonline.org
