### ISSUE TITLE
Plot twist no fansub

### ISSUE THREAD

**Issue by KatoMegushua** [keiyoushi/tachiyomi-extensions-source#2201]
### Source information

Plot twist no fansub 1.4.2

### Source language

Spanish

### Steps to reproduce

1 install
2 use

### Expected behavior

Open and read

### Actual behavior

Unexpected JSON token at offset 0: Expected start of the array '[', but had 'EOF' instead at path: $
JSON input: 0

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Proxy-E23** [comment]
Estaba a punto de abrir un nuevo ticket pero me ganaste. Voy a comentar algo, no creo que valga la pena seguir actualizando esta extensión porque mirando el Discord del fansub, deliberadamente están provocando que la extensión falle cada vez que la actualizan. Entonces, a menos que encuentren una manera de que su sitio no detecte la extensión, será un ciclo interminable en el que arreglarán la extensión y, un par de horas después, volverá a fallar.
