### ISSUE TITLE
Rfdragon Scan - Takes too long to reply

### ISSUE THREAD

**Issue by nomaxsnx** [keiyoushi/tachiyomi-extensions-source#2203]
### Source information

Rf Dragon Scan 1.4.4

### Source language

Português 

### Steps to reproduce

1 install the extension
2 open the extension
3 Read some manga and wait  

### Expected behavior

![Screenshot_2024-03-31-15-16-44-843_app mihon](https://github.com/keiyoushi/extensions-source/assets/157644160/47267d53-b50a-4752-a49c-9c84374dafbe)

![Screenshot_2024-03-31-15-21-08-467_app mihon](https://github.com/keiyoushi/extensions-source/assets/157644160/fc126559-1778-4dc2-9583-5b453267454c)

![Screenshot_2024-03-31-15-21-12-732_app mihon](https://github.com/keiyoushi/extensions-source/assets/157644160/cc4a7e63-cfed-456d-972b-efa822f878d6)

### Actual behavior

Apparently it's taking a long time to respond, even with the internet on, mobile data

Although the site is working

The "popular" menu doesn't respond, only the recent one

### Mihon/Tachiyomi version

App version: 0.16.4 

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nomaxsnx** [comment]
![Screenshot_2024-03-31-15-58-37-223_app mihon-edit](https://github.com/keiyoushi/extensions-source/assets/157644160/786746e7-126f-4830-a113-e3cf12b778f4)

**Comment by Smol-Ame** [comment]
This doesn't seem like it's an extension issue, their site is just painfully slow to load anything.

Try changing your user-agent (Mihon Settings > Advanced), restart the app, and try using the extension again.

As for the title "This Hero is a Money Supremacist" , and any titles that are giving you this issue in your Library, try migrating it back into this source to update the URL. I am able to see this title & chapters on my end, and it seems yours is out of date.

**Comment by nomaxsnx** [comment]
> This doesn't seem like it's an extension issue, their site is just painfully slow to load anything.
> 
> Try changing your user-agent (Mihon Settings > Advanced), restart the app, and try using the extension again.
> 
> As for the title "This Hero is a Money Supremacist" , and any titles that are giving you this issue in your Library, try migrating it back into this source to update the URL. I am able to see this title & chapters on my end, and it seems yours is out of date.

I tried changing the user-agents, but it didn't work :-:.

I think I'll have to go to their DC and tell them why it's so slow

**Comment by nomaxsnx** [comment]
Site voltou ao normal, aparentemente ele mal configurado na parte melhoria e instabilidade
