### ISSUE TITLE
Manga Sect search and reading broken

### ISSUE THREAD

**Issue by morethanhater** [keiyoushi/tachiyomi-extensions-source#2205]
### Source information

Manga sect 1.4.1

### Source language

English 

### Steps to reproduce

1. Open browse section
2. Select Manga Sect
3. Recieve an error "no results found"

If you had added manga to library previously, then another problem occurs:
1. Select manga at library
2. Start reading any chapter
3. Recieve an error "too many follow-up requests"
![Screenshot_20240331_222425_TachiyomiJ2K](https://github.com/keiyoushi/extensions-source/assets/36857282/24949547-229b-4198-9b6b-67cea7a2b1df)
![Screenshot_20240331_222851_TachiyomiJ2K](https://github.com/keiyoushi/extensions-source/assets/36857282/83f04012-3a34-40c2-ab5a-5a4ff1436b4f)

### Expected behavior

Search and reading works

### Actual behavior

Search and reading doesn't work

### Mihon/Tachiyomi version

J2K 1.7.4

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Site redirects to https://mangasect.net, might be enough to update the `baseUrl`

**Comment by barrelltitor** [comment]
Unfortunately that wasn't enough, but I almost got it fixed 
![studio64_dI7ovY0UH9](https://github.com/keiyoushi/extensions-source/assets/108460132/5c7703c8-8786-4547-a7d5-727ef30cb966)


Looks like they completely changed the website, most of the code existing in the extension didn't work anymore
