### ISSUE TITLE
LXHenatai change URL

### ISSUE THREAD

**Issue by MakatoKishei** [keiyoushi/tachiyomi-extensions-source#2214]
### Source information

LXHentai 1.4.2

### Source language

Vietnamese 

### Source new URL

https://lxmanga88.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by MakatoKishei** [comment]
Basically, the name LXHentai is still correct but they changed their domain name from the old one to https://lxmanga88.com/ and this causes the extension on the app to not be accessible, so this is not an error so I hope you can change the domain name for it.

**Comment by MakatoKishei** [comment]
Basically, the name LXHentai is still correct but they changed their domain name from the old one to https://lxmanga88.com/ and this causes the extension on the app to not be accessible, so this is not an error so I hope you can change the domain name for it.

**Comment by vetleledaal** [comment]
The domain was already updated in #2013, so you should open a regular bug report with the issue you're encountering.
