### ISSUE TITLE
Error in source "Plot Twist No Fansub"

### ISSUE THREAD

**Issue by Elking69** [keiyoushi/tachiyomi-extensions-source#2217]
### Source information

Plot Twist No Fansub 1.4.2

### Source language

Spanish

### Steps to reproduce

When trying to use the source you can search for the mangas, but when you try to read them the chapters do not load and the following error message appears "Expected start of the array [, but had 'EOf' instead
 at path: $..."

Thanks...

Link: https://www.plotfansub.com/

![Screenshot_20240401_005933_TachiyomiJ2K](https://github.com/keiyoushi/extensions-source/assets/92276919/13fc4d73-3d0c-4381-894b-737295f9ccfc)

### Expected behavior

this should happen, when you find a manga and click on it, it should load the chapters and be able to see them.

### Actual behavior

this happened instead, when clicking on a manga, the following message appears and the chapters are not shown: "Expected start of the array [, but had 'EOf' instead at path: $."

### Mihon/Tachiyomi version

1.7.4 is TachiJ2K

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Still a duplicate of #2201

Check existing issues first before opening a new issue & blindly acknowledging that you did (twice)
