### ISSUE TITLE
Comick new chapters delaying issue

### ISSUE THREAD

**Issue by KeremDgGG** [keiyoushi/tachiyomi-extensions-source#2220]
### Source information

Comick 1.4.42

### Source language

Multi

### Steps to reproduce

1. Update the manga

### Expected behavior

Appearing of the new chapter that is available on Comick website

### Actual behavior

Doesn't appear/appears late

### Mihon/Tachiyomi version

Aniyomi r7513

### Android version

Android 14

### Other details

The new chapter is available on Comick, it appears when you look at the "Latest" section too (unless look with filtering and select only manga and last updated) but it doesn't appear when you update the manga, it appears in a later time

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
i believe thats how their api behavior
