### ISSUE TITLE
Mihon 

### ISSUE THREAD

**Issue by TURAN14531071** [keiyoushi/tachiyomi-extensions-source#2221]
### Source information

Manga gezgini 1.4.35

### Source language

Türkçe

### Steps to reproduce

Mihonda girince gözüküyor 

### Expected behavior

Tachiyomide ki gibi görünmesi gerekiyor 

### Actual behavior

Mihonda yeni gelen bölüm gözükmüyor 

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
You should probably translate your information to be in the same language as the one it is asked in, I don't even know if there is a Turkish speaking contributor, so if you want your issue to be possibly fixed faster consider using English

**Comment by vetleledaal** [comment]
Closing in favor of #2222
