### ISSUE TITLE
Mihon

### ISSUE THREAD

**Issue by TURAN14531071** [keiyoushi/tachiyomi-extensions-source#2222]
### Source information

All

### Source language

English 

### Steps to reproduce

new episodes do not appear

### Expected behavior

New episodes should appear like in tachiyomi

### Actual behavior

but and but new episodes do not appear in mihon

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 11

### Other details

It has been translated, sorry if there are any mistakes in my writing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
If it's working in Tachiyomi and not Mihon, it's not an extension issue. It is likely related to [smart updates](https://mihon.app/docs/faq/updates/smart#smart-updates), if not you should report the issue with Mihon.
