### ISSUE TITLE
Galaxy shoujo

### ISSUE THREAD

**Issue by Kinupsy-co** [keiyoushi/tachiyomi-extensions-source#2224]
### Source information

Galaxy manga 1.4.31

### Source language

Arabic

### Source new URL

https://flixscans.com/webtoons/romance/home

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Kinupsy-co** [comment]
The extension exists but the site link has changed so it no longer works

**Comment by Norsze** [comment]
But you have not provided a different URL, that is the same base URL
