### ISSUE TITLE
TenkaiScan

### ISSUE THREAD

**Issue by Blade1170** [keiyoushi/tachiyomi-extensions-source#2235]
### Source information

https://tenkaiscan.net/

### Source language

Español 

### Steps to reproduce

![Screenshot_2024-04-01-20-23-23-758_app mihon debug](https://github.com/keiyoushi/extensions-source/assets/157080940/69b2aa26-6870-4afc-8f1c-39d127a8275a)

### Expected behavior

Que cargue con normalidad

### Actual behavior

No cargo

### Mihon/Tachiyomi version

Mihon r6604

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Fixed in #2211
