### ISSUE TITLE
Can't download the extension 'hentai2read'

### ISSUE THREAD

**Issue by Warzoroog** [keiyoushi/tachiyomi-extensions-source#2238]
### Source information

Hentai2read 1.4.16

### Source language

English 

### Steps to reproduce

1.Going to extension
2.Download the extension 'hentai2read'
3.But it doesn't download 

### Expected behavior

It is supposed to download the extension 'hentai2read' 

### Actual behavior

It doesn't download 

### Mihon/Tachiyomi version

 Stable 0.16.4

### Android version

Android ver.8.1.0

### Other details

The older version of hentai2read can be installed 1.4.14
But in that version cover pages are broken
One can find the older version in the tachiyomi repo

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Uninstall the old Tachi extension from your phone, and if you're using a Samsung with Secure Folder (or any device that dupes installed apps), you need to uninstall it from Secure Folder as well

**Comment by Norsze** [comment]
not really anything we can fix codewise with the extension, this is on you and your phone
