### ISSUE TITLE
Manhwa-latino dont pass verification but webview works

### ISSUE THREAD

**Issue by Kratos43R** [keiyoushi/tachiyomi-extensions-source#2244]
### Source information

Manhwa-Latino 1.4.42

### Source language

Spanish

### Steps to reproduce

When you open the extension the content does not appear but the web view works

### Expected behavior

be able to search content

### Actual behavior

nothing appears

### Mihon/Tachiyomi version

Beta r6604

### Android version

Android 11

### Other details

I hope it can be solved because it is a fairly well-known and used extension. Greetings

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
They also put CF in other parts of the page, try opening it in a WebView and browsing around the page (by tapping the search icon, opening a manga/chapter, etc). If that doesn't work, wait for their protection to decrease or migrate to other sources
