### ISSUE TITLE
Update Hunters Scans

### ISSUE THREAD

**Issue by savnoch** [keiyoushi/tachiyomi-extensions-source#2246]
### Source information

Hunters Scans 1.4.36

### Source language

Brazilian Portuguese - Português (Brasil)

### Source new URL

https://huntersscan.xyz

### Other details

The old link is pt.huntersscans

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by neko223599** [comment]
![Screenshot_20240403-073957](https://github.com/keiyoushi/extensions-source/assets/51305889/df7ffc28-0c9f-455f-bc6a-b2b6f6345935)
Has no update
