### ISSUE TITLE
Add back Komga

### ISSUE THREAD

**Issue by THElegend5** [keiyoushi/tachiyomi-extensions-source#225]
### Source name

Komga

### Source link

https://demo.komga.org/

### Source language

English

### Other details

Add back Komga and the other self hosted sources here now that official extension repo has been archived. 

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by cfouche3005** [comment]
Also other selfhosted services (Kavita ...), basically all of the extensions supported by tachiyomi until the end

**Comment by RandomLegend** [comment]
Yeah please!

i just migrated from tachiyomi to mihon and my kavita extension didn't work. I uninstalled it only to find out it's gone from the repo...
