### ISSUE TITLE
LHTranslation: HTTP error 500

### ISSUE THREAD

**Issue by sovit042** [keiyoushi/tachiyomi-extensions-source#226]
### Source information

LHTranslation 1.4.33

### Source language

English

### Steps to reproduce

1. Download LHTranslation 
2. One the extension
3. You will see HTTP 500 error
 While the website is working perfectly fine in webview 

### Expected behavior

It should show the series available on the website 

### Actual behavior

It just show HTTP 500 but when u open webview the website is perfectly fine
![Screenshot_2024-01-14-03-20-44-128_eu kanade tachiyomi](https://github.com/keiyoushi/extensions-source/assets/101596014/2630ff35-701b-45dd-9130-078cace96770)
![Screenshot_2024-01-14-03-20-57-197_eu kanade tachiyomi](https://github.com/keiyoushi/extensions-source/assets/101596014/2eab2750-64de-4bca-9a28-21eb596b1deb)

### Tachiyomi version

0.15.2

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Noobforever18** [comment]
Http 500 it's also happening on my device

**Comment by sovit042** [comment]
Thats why I said extension broken

**Comment by beer-psi** [comment]
Can't load https://lhtranslation.net on a browser either. Is source down, or are they blocking access by using bogus error messages?

![image](https://github.com/keiyoushi/extensions-source/assets/92439990/c7a47627-899e-403d-a7a0-33b43d913a5f)

**Comment by Noobforever18** [comment]
Source down confirmed. Checked with multiple VPN and ips. Was up just a few hours ago though

**Comment by beer-psi** [comment]
Closing this issue then. We are not hosting any content, and are not responsible if source is down. Wait for source to go back up or migrate.

**Comment by sovit042** [comment]
Bro the website problem started today but the problem started 2 days ago

**Comment by beer-psi** [comment]
> Bro the website problem started today but the problem started 2 days ago

![HTTP.cat 500: Internal Server Error](https://http.cat/500)

HTTP 500 is not our fault.

**Comment by Noobforever18** [comment]
As far as I can see about error 500. It's on thier side. So let's just wait sovi. Mangadex works fine. Lh guys upload thier too

**Comment by sovit042** [comment]
Sorry typing mistake this 500 error problem is going on from 2 days aga when the website was running smoothly and the website problem we are talking about just started today thats why I said extension broken as the discord mods asked me to report it

**Comment by Noobforever18** [comment]
Let's wait for them to come back. And than see what happens. If it runs properly, problem solved and if it continues, hope we can report it again than

**Comment by Norsze** [comment]
![image](https://github.com/keiyoushi/extensions-source/assets/66540317/4d2b84cf-1cd0-40c4-ab89-71d62c6206b8)

from their announcement channel on discord

**Comment by sovit042** [comment]
![IMG_20240115_105458](https://github.com/keiyoushi/extensions-source/assets/101596014/c9372983-6ad2-40e1-b5e5-e75179d9c545)
![IMG_20240115_105542](https://github.com/keiyoushi/extensions-source/assets/101596014/3610a4c8-131d-433e-a548-d87c80050a9f)
Before the site problem
Thx for helping noobforever18 and beerpiss , lets hope it will run fine after the site returns

**Comment by Noobforever18** [comment]
It's back and it's working properly like it used to.
