### ISSUE TITLE
Manhwa-latino no funciona

### ISSUE THREAD

**Issue by Simpyke** [keiyoushi/tachiyomi-extensions-source#2262]
### Source information

Manhwa-Latino 1.4.42

### Source language

Español

### Steps to reproduce

1. Abrir extensión
2. Observar el contenido de la extensión
3. Elegir contenido y seguir contenido 
4. Dar seguimiento a el contenido seleccionado

### Expected behavior

Al abrir la extensión debería poder verse el contenido que hay por parte de la extensión 

### Actual behavior

Al abrir la extensión esta muestra erro de fallo de Cloudflare pero, al abrí por medio de webview esta funciona correctamente y no aparece ningún anuncio de problemas con cloudflare como anterior mente sucedía

### Mihon/Tachiyomi version

Stable 0.15.3

### Android version

8.1.0

### Other details

![Screenshot_20240404-180036](https://github.com/keiyoushi/extensions-source/assets/150213898/797fefb2-cb84-4d49-b7a8-589f0b9bb987)
![Screenshot_20240404-180026](https://github.com/keiyoushi/extensions-source/assets/150213898/1fc64d47-009f-4ce8-a65c-8dd21c8301df)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of closed issue #2244 , response by a fellow contributor:

"They also put CF in other parts of the page, try opening it in a WebView and browsing around the page (by tapping the search icon, opening a manga/chapter, etc). If that doesn't work, wait for their protection to decrease or migrate to other sources"


Simply, open WebView when you're on that source, pass the Cloudflare verification (if it loops/doesn't pass, change your user-agent in Tachi Settings > Advanced). Afterwards, while in WebView, click the search icon or other parts of the website, and pass that Cloudflare verification as well. Then you would go back into the app, to the source, and refresh the source's browse page or chapters page.
