### ISSUE TITLE
Happymh searching not working

### ISSUE THREAD

**Issue by Moko228** [keiyoushi/tachiyomi-extensions-source#2265]
### Source information

Happymh 1.4.9

### Source language

Chinese

### Steps to reproduce

1.Search for comic
2.Show HTTP 404
![Screenshot_20240405-153931842](https://github.com/keiyoushi/extensions-source/assets/154062292/fa790510-10f4-41f4-be41-a778cc9f0a55)
![Screenshot_20240405-153938575](https://github.com/keiyoushi/extensions-source/assets/154062292/b75551ac-fae9-47d3-a580-ec049d2da84a)
![Screenshot_20240405-153944726](https://github.com/keiyoushi/extensions-source/assets/154062292/ab017532-f622-4661-974c-67726d81b000)
![Screenshot_20240405-153954987](https://github.com/keiyoushi/extensions-source/assets/154062292/6757094e-d507-4fe1-97ea-5d70385f7ab2)

### Expected behavior

Show the searching result

### Actual behavior

Show HTTP 404

### Mihon/Tachiyomi version

Mihon 0.16.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #2264 , next time please search the issues before making a new request & acknowledging that you did

**Comment by vetleledaal** [comment]
#2264 was only created a few minutes before this one, they might've looked for an issue before writing this one
