### ISSUE TITLE
Requesting Source Lua Scans

### ISSUE THREAD

**Issue by Hinalover** [keiyoushi/tachiyomi-extensions-source#2274]
### Source name

Lua Scans

### Source link

https://luascans.com/

### Source language

English

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by ManiV97** [comment]
Can you please give an update?
Thank you.

**Comment by Norsze** [comment]
It will be done if and when someone feels like it.  No complaining will make it go faster, we do this for free, if you want faster service learn Kotlin and do it yourself

**Comment by Hinalover** [comment]
NVM Saw what happend in Discord. So you can discard this message.
