### ISSUE TITLE
SamuraiScan change URL

### ISSUE THREAD

**Issue by mfloresz** [keiyoushi/tachiyomi-extensions-source#2276]
### Source information

SamuraiScan 1.4.39

### Source language

Spanish

### Source new URL

https://manhuaonline.org/

### Other details

Samuraiscan.org is accessible but can no longer be read from there, it redirects to the new url mentioned above.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by mfloresz** [comment]
Samuraiscan.org is accessible but can no longer be read from there, it redirects to the new url mentioned above.

**Comment by seba1107** [comment]
Some titles are still being uploaded to samuraiscan.org while others have been migrated to manhuaonline.org
