### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by Pedropaulo015** [keiyoushi/tachiyomi-extensions-source#2285]
### Source information

Lura toon

### Source language

Português brasil

### Steps to reproduce

Quando baixo a extensão e Clico nela para entra nela aparece isso
![Screenshot_20240406-024759](https://github.com/keiyoushi/extensions-source/assets/166200660/61bd277b-4195-4d5a-ae35-e7f3797499c6)
Mais quando Clico em webvel o site entra normalmente mais a extensão não espero que possam me ajudar uso muito essa extensão e não é só ela a Hunters scans também apresenta o mesmo problema

### Expected behavior

Estava funcionando bem até agora quando abri o aplicativo mihon

### Actual behavior

Esse problema só começou agora

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 10

### Other details

![Screenshot_20240406-024759](https://github.com/keiyoushi/extensions-source/assets/166200660/445c16b6-d1bd-4154-b032-d02c5c425dc5)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate error of #2260

Please wait for a fix or migrate to a different source
