### ISSUE TITLE
Mihon Extension 

### ISSUE THREAD

**Issue by Stratify23** [keiyoushi/tachiyomi-extensions-source#2286]
### Source information

MangaGeko Not Working

### Source language

English

### Steps to reproduce

Added the extension repo. Mangageko doesn't show up on the mihon app. But it shows in the extension list.

### Expected behavior

Should see mangageko when searching in mihon

### Actual behavior

Mangageko does not show up

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 14 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Did you enable 18+ sources in Mihon Settings > Browse?

**Comment by Stratify23** [comment]
Oh it works now thanks
