### ISSUE TITLE
mangagezgini.com SSLHandshakeException: error

### ISSUE THREAD

**Issue by By-PorfecTo** [keiyoushi/tachiyomi-extensions-source#2295]
### Source information

Manga Gezgini 1.4.35

### Source language

Turkish

### Steps to reproduce

1

### Expected behavior

library and WebView working properly

### Actual behavior

Extension does not open, including WebView

### Mihon/Tachiyomi version

Tachiyomi 0.15.3

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
Extension works, something on your network or isp is blocking it.
Use Dns over https or Vpn to fix

come to our discord if you need further help
