### ISSUE TITLE
Source Request: manhwahentai.to

### ISSUE THREAD

**Issue by devil6venom** [keiyoushi/tachiyomi-extensions-source#2296]
### Source name

manhwahentai.to

### Source link

https://manhwahentai.to

### Source language

English

### Other details

18+ = Yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by devil6venom** [comment]
Uses theme same as madara i guess!

**Comment by MikeZeDev** [comment]
Madara indeed
