### ISSUE TITLE
add new source for "Vi" nettruyenxu

### ISSUE THREAD

**Issue by tuanbmt4152** [keiyoushi/tachiyomi-extensions-source#2297]
### Source name

NetTruyenXu

### Source link

https://nettruyenxu.com/

### Source language

Vietnamese "Vi"

### Other details

add new source

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
Same source as #1345 (https://comic24hzz.com/), only different mirror domain.
