### ISSUE TITLE
Lura toon opening chapters in .zip

### ISSUE THREAD

**Issue by JosephShay** [keiyoushi/tachiyomi-extensions-source#2305]
### Source information

Lura Toon 1.4.43

### Source language

Brazilian Portuguese

### Steps to reproduce

Currently, the extension is fully functional with your comics appearing normally, but it does not open the chapters of the comics within the application and, when accessed via webview, it downloads a .zip file. At the time of this post, all features in website are operational. 

What currently appears when you open the webview: https://luratoon.com/static/PeachScan/obras/17235/30/0.zip#page

### Expected behavior

Suddenly after updating the extension and the website stopped working.

### Actual behavior

No chapter images being loaded
![cf0ee086-4e91-4492-9bf6-a8e6a77a9942](https://github.com/keiyoushi/extensions-source/assets/48162671/401213e5-f124-49cd-a0bf-6989b609a909)

### Mihon/Tachiyomi version

Tachiyomi Stable 0.15.3

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
cannot reproduce, tell me specific comic/chapter where this happens. because the extension already supports those zip files.
![image](https://github.com/keiyoushi/extensions-source/assets/48650614/f63ee7d8-1e49-4b5a-b9a0-8c28b6fa5125)

**Comment by JosephShay** [comment]
https://luratoon.com/static/PeachScan/obras/17235/30/12.zip#page the same chapter. 

![image](https://github.com/keiyoushi/extensions-source/assets/48162671/abc7f652-7fcd-4ece-9e5c-1421f9f1b637) (this image cannot be loaded)

![image](https://github.com/keiyoushi/extensions-source/assets/48162671/01f43d7b-90fe-476b-bec4-fa50108dafc8) the webview

**Comment by AwkwardPeak7** [comment]
come to our discord for help
