### ISSUE TITLE
Source Request : doctruyen3q

### ISSUE THREAD

**Issue by tuanbmt4152** [keiyoushi/tachiyomi-extensions-source#2309]
### Source name

DocTruyen3q

### Source link

https://doctruyen3q.pro/

### Source language

Vietnamese

### Other details

Source Request : doctruyen3q

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Theme looks like WPComics, but unsure

**Comment by cuong-tran** [comment]
domain changed to: https://doctruyen3qvn.com/
