### ISSUE TITLE
TCBscans seems to be down or gone

### ISSUE THREAD

**Issue by millionsofplayers** [keiyoushi/tachiyomi-extensions-source#2311]
### Source name

TCB Scans

### Source language

English

### Source link

onepiecechapters.com

### Other details

The site used for tcb scans seems to be down. You should switch to the one linked in the one piece subreddits Manga discussions

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
That is not the base URL that TCB Scans uses. But the current main address does redirect you to some kind of backup.

**Comment by millionsofplayers** [comment]
Oh

So the tcb scans extension sends you to a random mirror with the same content?

**Comment by Norsze** [comment]
It is one of the mirrors they use, but the whole site seems to be down and using a backup https://tcb-backup.bihar-mirchi.com

**Comment by millionsofplayers** [comment]
Is there a way to switch the url the extension uses to the backup?

**Comment by Norsze** [comment]
should probably wait, since their site is probably just temporarily down

**Comment by Norsze** [comment]
The default url is https://tcbscans.com that is the link that will apparently redirect to their different backups. So probably change the url to that

**Comment by millionsofplayers** [comment]
How do I do that (or does the dev do that)

**Comment by Norsze** [comment]
dev does that, I just added it so the devs can find the info in this issue

**Comment by millionsofplayers** [comment]
How do I bypass the cloudflare protection

**Comment by millionsofplayers** [comment]
Going into webview sends me into a cloudflare loop and it doesn't work in regular view even if the user agent is the same as the one in mobile firefox

**Comment by Norsze** [comment]
![Screenshot_20240411_164747_Mihon.jpg](https://github.com/keiyoushi/extensions-source/assets/66540317/6b4e76ff-1ca5-4c88-bc88-b4a6195b266a)

![Screenshot_20240411_164804_Mihon.jpg](https://github.com/keiyoushi/extensions-source/assets/66540317/26577f3a-5db2-476a-a18a-0055df3f4056)

Seems like a skill issue, but I might be wrong

**Comment by millionsofplayers** [comment]
Did you have to manually change your user agent or did it just work for you

**Comment by Norsze** [comment]
I already have a different one cause MAL won't work otherwise

**Comment by millionsofplayers** [comment]
Ended up finding a user agent that works

**Comment by Taurdenga** [comment]
> Going into webview sends me into a cloudflare loop and it doesn't work in regular view even if the user agent is the same as the one in mobile firefox

I have the same issue, could you share which User Agent you ended up using to bypass Cloudflare looping? Thanks in advance!

**Comment by millionsofplayers** [comment]
`Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36 EdgA/115.0.1901.196`

**Comment by Taurdenga** [comment]
> `Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36 EdgA/115.0.1901.196`

Thanks for the quick reply! That did the trick for the me! :)
