### ISSUE TITLE
BoysLove seems to be down

### ISSUE THREAD

**Issue by mentlmelody** [keiyoushi/tachiyomi-extensions-source#2316]
### Source name

BoysLove

### Source language

English

### Source link

https://boyslove.me

### Other details

I get a timeout error when trying to access the source in-app. Webview also shows a timeout error but in desktop shows as a recently registered domain. Haven't been able to find any info of possible domain change.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by mentlmelody** [comment]
As of the 1.4.39 update, webview gives a 404 error.

**Comment by Smol-Ame** [comment]
Seems like their site is cleared/emptied, unless the site doesn't work on Firefox

Check the website, and if it's empty, nothing we can do about it (since there's nothing for the extension to grab)
