### ISSUE TITLE
Covers not loading for entries in traducciones amistosas 

### ISSUE THREAD

**Issue by Athrun0311** [keiyoushi/tachiyomi-extensions-source#2324]
### Source information

Traducciones amistosas 1.4.2

### Source language

Spanish 

### Steps to reproduce

Open extension
Covers do not load even after refreshing  in extension
![Screenshot_20240409_230604_app mihon](https://github.com/keiyoushi/extensions-source/assets/160463122/ec9b73f8-5ea2-466d-8d4d-f48420f40726)

### Expected behavior

Loading cover in manga reading
![Screenshot_20240409_230736_app mihon](https://github.com/keiyoushi/extensions-source/assets/160463122/579b4078-c61c-45d5-a90d-5791ac2ffa65)

### Actual behavior

The cover does not load when reading the manga.
![Screenshot_20240409_230613_app mihon](https://github.com/keiyoushi/extensions-source/assets/160463122/5b8c95db-a733-4f8c-9348-7cf33effe798)

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Can't reproduce, try clearing database in advanced settings

**Comment by Athrun0311** [comment]
Thanks.

**Comment by Norsze** [comment]
Same as bapeey, probably just a database clear in advanced settings to fix.
