### ISSUE TITLE
Zero 搬運網 not working 

### ISSUE THREAD

**Issue by Hohoakira** [keiyoushi/tachiyomi-extensions-source#233]
### Source information

Zh.zerobyw

### Source language

Chinese 

### Steps to reproduce

The extension doesn't load any content.
But in the WebView does load the website correctly.

### Expected behavior

The content load corretly

### Actual behavior

Content doesn't load

### Tachiyomi version

0.15.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Use a desktop User Agent string.

**Comment by stevenyomi** [comment]
UA set to desktop in #880.
