### ISSUE TITLE
Manga Falme : Link changed

### ISSUE THREAD

**Issue by a7mad115** [keiyoushi/tachiyomi-extensions-source#2330]
### Source information

Manga Flame 1.4.32

### Source language

Arabic

### Source new URL

https://mangaflame.org/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
The old domain, https://arisescans.com , is still up for me. Did they mention they were moving somewhere?

**Comment by Norsze** [comment]
Though it is strange that they only have 3 titles on their website and they are in English, not Arabic. So something is off

**Comment by a7mad115** [comment]
https://arisescans.com/ this is not there website and its English not Arabic.

there website is https://mangaflame.org/ and they never change it .
