### ISSUE TITLE
Cant install 1manga co extension

### ISSUE THREAD

**Issue by hatimurni** [keiyoushi/tachiyomi-extensions-source#2332]
### Source information

1manga.co 1.4.28

### Source language

English

### Steps to reproduce

I click install, but i cant see extension get installed in my extension list (i want to click trust to proceed instalation but it not appear in installed extension list)

Im already close and open app again but not work. I cant install 1manga.co extension.

Already tried update it by download extension apk but still not work

Im using newest mihon apk in android 11

### Expected behavior

It should be in my list installed extension, i should click trust to proceed instalation 

### Actual behavior

But it not installed, cant see it in my installed extension list, 

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
It's better to go to the Discord for these kinds of issues, as they are not really on our end and not something we can fix here on the Github. They are instead on your end where you need to fix something on your phone.

**Comment by Norsze** [comment]
Also did you check the pinned issue #109 ?
