### ISSUE TITLE
I can't load the current chapters

### ISSUE THREAD

**Issue by Vladraig** [keiyoushi/tachiyomi-extensions-source#234]
### Source information

Manhwas.net 1.4.10

### Source language

Spanish 

### Steps to reproduce

step 1. manually update a manhwa
step 2. I didn't update and I got a message "SocketException: Socket closed" and this one that said "StreamResetException: Stream was reset: CANCEL"

### Expected behavior

they should load the chapters
why an hour before it worked fine

### Actual behavior

I don't update the chapters

### Tachiyomi version

0.1.5.3

### Android version

Android 8.1

### Other details

the extension page has no problem

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Clear cookies in extension settings

**Comment by Vladraig** [comment]
> Borrar cookies en la configuración de la extensión

Thanks
