### ISSUE TITLE
raw1001

### ISSUE THREAD

**Issue by akir45** [keiyoushi/tachiyomi-extensions-source#2341]
### Source name

raw1001.co

### Source link

https://raw1001.co/

### Source language

japanese

### Other details

18+/NSFW = yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
~~Site redirects to https://raw1001.co/~~

https://raw1001.ac/

**Comment by vetleledaal** [comment]
Seems like the site has been down for the last week, so I'm closing this issue. If the site works for you or they changed domain don't hesitate to leave a comment.
