### ISSUE TITLE
Drake scans extension issue 

### ISSUE THREAD

**Issue by Rasun0** [keiyoushi/tachiyomi-extensions-source#2361]
### Source information

Drake scans 

### Source language

English 

### Steps to reproduce

firstly it was working but now it's not working on extension like we just click on extension and we can see the list of manwha manuha Manga etc but now it's only giving access through webview and showing error 404 check webview website still after coming from website it's remain same. 
![Screenshot_20240412_090141](https://github.com/keiyoushi/extensions-source/assets/139698115/d228b753-8352-4860-83a8-6d6d0e9bbcce)
![Screenshot_20240412_090138](https://github.com/keiyoushi/extensions-source/assets/139698115/031c6963-43d9-4a1c-9e4c-97fc00ccc5d2)
![Screenshot_20240412_090135](https://github.com/keiyoushi/extensions-source/assets/139698115/abde0f90-246d-47bf-9561-162e36ffc38c)

as u can see in the normal extension we r getting error but in webview it's working fine 

### Expected behavior

it should open on normal extension just like webview it's showing list of all Manga manwha etc. but it's only currently specific to webview. not how it should in extension. 
![Screenshot_20240412_091029](https://github.com/keiyoushi/extensions-source/assets/139698115/b66cf270-53cc-48c1-842e-b85f92bcb183)
tho it's a different extention but this how it should show. 

### Actual behavior

![Screenshot_20240412_090138](https://github.com/keiyoushi/extensions-source/assets/139698115/e264cbdc-be7e-49b2-85c7-c53c77cfc89c)
it's not opening in extension but only in webview 
![Screenshot_20240412_090141](https://github.com/keiyoushi/extensions-source/assets/139698115/e9d15bbe-963a-4ac8-810a-a6dd1ede8585)
on extension it's showing 404 error that it even after coming back from website it's still remain like this. 

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

mostly the main issue lies with extension it's showing error of 404 even after cleaning webview data cleaning cookie of extension and even after uninstall and reinstall the extention this issue remain. 
![Screenshot_20240412_090141](https://github.com/keiyoushi/extensions-source/assets/139698115/ebe59880-ed21-409e-98c4-7d6e0c297de7)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MrBasicX** [comment]
The website theme seems to have been changed to **"mangareader"** theme from **"madara"**.
