### ISSUE TITLE
Temple Scan (Es) "Couldn't reach unable to resolve host"

### ISSUE THREAD

**Issue by KatoMegushua** [keiyoushi/tachiyomi-extensions-source#2365]
### Source information

Temple Scan 1.4.34

### Source language

Spanish

### Steps to reproduce

Install and use

### Expected behavior

Use 
And view results

### Actual behavior

No view results

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Other details

![Screenshot_20240412_013940_Mihon](https://github.com/keiyoushi/extensions-source/assets/145884813/703449d9-e45b-4d8a-ae7d-92487f2cebe7)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Works on my end, could you go to Browse Page > Extensions tab > Temple Scan extension settings, then hit the top-right three-dots button & Clear Cookies?

Also try going into WebView to see if there's an error (and maybe swap networks to try again)

**Comment by KatoMegushua** [comment]
I cleared the cookies and changed networks, but it still shows the same error. However, accessing the WebView does work.

**Comment by bapeey** [comment]
Try enabling DoH in advanced settings

**Comment by AwkwardPeak7** [comment]
@KatoMegushua please don't post nsfw screenshots. 

if you need further help, come to our discord as extension is working
