### ISSUE TITLE
Multporn Loading and Downloading Problem

### ISSUE THREAD

**Issue by Kenn876** [keiyoushi/tachiyomi-extensions-source#2372]
### Source information

Multporn 1.4.4

### Source language

English 

### Steps to reproduce

1. Go to multporn
2. Pick a comic or view from own library
3. Press Download or try reading the comic

### Expected behavior

Should load properly when reading and downloading.

### Actual behavior

It takes forever to download. It loads by a millimeter every 5 minutes. 

### Mihon/Tachiyomi version

Tachiyomi 0.15.3

### Android version

Android 12

### Other details

My wifi is fine I can download and view comics and mangas fine in other sites. It's just multporn that's doing this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Seems to work as intended, works fast for me, don't see no rate limit in the code. I have to guess the problem is your network or device. Visit the Discord if you need support with finding the issue

**Comment by Kenn876** [comment]
> Seems to work as intended, works fast for me, don't see no rate limit in the code. I have to guess the problem is your network or device. Visit the Discord if you need support with finding the issue

I don't really use discord. Do you have a link? Could you send it please?

**Comment by Norsze** [comment]
It's on this Github page's front, if you read the description

https://github.com/keiyoushi/extensions-source
