### ISSUE TITLE
Anchira MissingFieldException

### ISSUE THREAD

**Issue by Kenn876** [keiyoushi/tachiyomi-extensions-source#2373]
### Source information

Achira 1.4.5

### Source language

English

### Steps to reproduce

1. Go to sources
2. Press Anchira
![Screenshot_20240412_233911](https://github.com/keiyoushi/extensions-source/assets/137243023/16765cd8-5cd4-4924-a216-0726b5a19e08)

### Expected behavior

Should show list of manga and be able to read them.

### Actual behavior

It keeps saying that Missing Field Exception and won't load.

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Update your extension. The current version is 1.4.11

**Comment by Kenn876** [comment]
> Update your extension. The current version is 1.4.11

I just updated it 1.4.5 though. How fast was the new update?

**Comment by Norsze** [comment]
1.4.5 was 3 months ago... You sure you added the right repo in the app?

**Comment by Smol-Ame** [comment]
> I just updated it 1.4.5 though. How fast was the new update?

If you just updated it to 1.4.5, then you're probably not using our repo.

It was last updated like a month ago
