### ISSUE TITLE
StayNightScan - PT

### ISSUE THREAD

**Issue by nomaxsnx** [keiyoushi/tachiyomi-extensions-source#2374]
### Source name

StayNight Scan

### Source link

https://www.staynscan.site

### Source language

Portugues

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Is this site even alive? The last update was 4 months ago and they only have 5 series, where 3 were last updated over 1 year ago

**Comment by nomaxsnx** [comment]
> Is this site even alive? The last update was 4 months ago and they only have 5 series, where 3 were last updated over 1 year ago

I just checked their dc, they're no longer alive, the last update was last year.

I didn't know, I'll close the issues.
