### ISSUE TITLE
URL change request for ZinChanManga 

### ISSUE THREAD

**Issue by monmonchi** [keiyoushi/tachiyomi-extensions-source#2378]
### Source information

ZinChanManga 1.4.36

### Source language

English

### Source new URL

https://zinchanmanga.com/

### Other details

The requested url is more updated rather than the current one. Thank you!

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Sites seem to be run by different people(?), although they use the same registrar inet.vn. The current site (.net) appears to have issues with garbled manga titles and emojis, so it might be better to switch to this domain (.com).
