### ISSUE TITLE
Drake Scans Chapter List Reversed

### ISSUE THREAD

**Issue by pepperlooni** [keiyoushi/tachiyomi-extensions-source#2395]
### Source information

Drake Scans 1.4.40

### Source language

English

### Steps to reproduce

Just open any from Drake Scans.

### Expected behavior

Sorting Settings the same but this one from EarlyManga has the latest chapter on top.
![image_2024-04-13_221556947](https://github.com/keiyoushi/extensions-source/assets/166928156/7a0e675b-3d26-484a-830b-c3cd8fd6c5f3)

### Actual behavior

Sorting Settings the same but this one from DrakeScans has the first chapter on top.
![image_2024-04-13_221613045](https://github.com/keiyoushi/extensions-source/assets/166928156/7da3ed5b-e263-4c46-bb19-34599c9fbfe9)

### Mihon/Tachiyomi version

TachiyomiSY Stable 1.10.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Not an extension issue, go look into WebView & you'll see it's how the source has listed it.

Flip the sort for that title (titles from that extension)

**Comment by pepperlooni** [comment]
I see. So Drake Scans themselves either made a mistake or intentionally reversed their chapter order. Thanks.
