### ISSUE TITLE
Cứu truyện : Source request

### ISSUE THREAD

**Issue by Keiget** [keiyoushi/tachiyomi-extensions-source#24]
### Source name

Cứu truyện

### Source link

https://cuutruyent9sv7.xyz/

### Source language

Vietnamese

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
I recommend using https://beer-psi.github.io/tachiyomi-unofficial-extensions for CuuTruyen, the site owners like to fuck with the extensions if it gets too much exposure.
