### ISSUE TITLE
itch.io - Source Request

### ISSUE THREAD

**Issue by chrrybmb64** [keiyoushi/tachiyomi-extensions-source#2401]
### Source name

itch.io

### Source link

https://itch.io/comics

### Source language

English

### Other details

NSFW content is hidden by default. Some comics are locked behind a paywall.

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Unstructured, and most comics are just PDF files, which Tachiyomi/Mihon doesn't support anyways.
