### ISSUE TITLE
Anchira: unable to fetch thumbnails

### ISSUE THREAD

**Issue by MediocreLegion** [keiyoushi/tachiyomi-extensions-source#2407]
### Source information

Anchira 1.4.11

### Source language

English

### Steps to reproduce

Open any anchira title and update the metadata

### Expected behavior

Thumbnails are properly fetched

### Actual behavior

No thumbnails are shown

![Screenshot_2024-04-14-00-03-19-802_eu kanade tachiyomi j2k](https://github.com/keiyoushi/extensions-source/assets/162182192/2b2ab3b1-fc42-4b9e-953d-7693838d5665)

### Mihon/Tachiyomi version

TachiyomiJ2K 1.7.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
Can't repro
![image](https://github.com/keiyoushi/extensions-source/assets/7104931/f3fc1f57-ab0d-466b-84ea-be0afc6ece84)

**Comment by MediocreLegion** [comment]
@BrutuZ If you already have the thumbnails on cache, it doesn't happen. You need to open any title and refetch the metadata for it to happen with these titles.

**Comment by BrutuZ** [comment]
Caching shouldn't be an issue here, I literally installed J2K for the first time ever to test this and #2408

**Comment by MediocreLegion** [comment]
Are logged into Anchira? I'm not using an account

**Comment by BrutuZ** [comment]
No.
Installed J2K > Trusted previously installed extension > opened Browse > Screenshot

**Comment by MediocreLegion** [comment]
Weird that it works for you. Tho, I suspected it was happening because of the default `thumb_index` being `1` instead of `0` here:
https://github.com/keiyoushi/extensions-source/blob/5108353ff986848501d404ba83e2f06bb6d94834/src/en/anchira/src/eu/kanade/tachiyomi/extension/en/anchira/AnchiraDto.kt#L26
combined with this `+1` in the code:
https://github.com/keiyoushi/extensions-source/blob/5108353ff986848501d404ba83e2f06bb6d94834/src/en/anchira/src/eu/kanade/tachiyomi/extension/en/anchira/Anchira.kt#L241-L242
This would affect titles that don't have a `thumb_index` field in the api response (that happens with titles in which the first page is the thumbnail), so the extension would try to fetch the second page instead of the first.

**Comment by MediocreLegion** [comment]
~~I'll reinstall anyway to confirm~~
Nope it didn't work

**Comment by MediocreLegion** [comment]
@BrutuZ Having tested the cdnUrl endpoints, I'm pretty sure the issue is indeed the default value being `1` instead of `0` for the titles without `thumb_index` in the api response.

**Comment by BrutuZ** [comment]
I just realized I already had that DTO change in my local build since 3 days ago when I first saw an entry without the `thumb_index` field. So yeah, you're absolutely right, reversed it just now to double-check and sure enough shit broke much like yours.

#2448 fixes it though
