### ISSUE TITLE
Anchira: titles with one author display the author list incorrectly

### ISSUE THREAD

**Issue by MediocreLegion** [keiyoushi/tachiyomi-extensions-source#2408]
### Source information

Anchira 1.4.11

### Source language

English

### Steps to reproduce

Open a title with only one author

### Expected behavior

Author list doesn't have a `,` at the beginning

### Actual behavior

Artist list starts with `,`

![Screenshot_2024-04-14-00-10-33-156_eu kanade tachiyomi j2k-edit](https://github.com/keiyoushi/extensions-source/assets/162182192/bea86242-25b2-4896-8053-01c6e10eeaf2)

### Mihon/Tachiyomi version

TachiyomiJ2k 1.7.4

### Android version

Android 12

### Other details

This issue only happens in titles with one author. Titles with multiple authors display correctly:

![Screenshot_2024-04-14-00-10-59-233_eu kanade tachiyomi j2k-edit](https://github.com/keiyoushi/extensions-source/assets/162182192/24cc36d8-9888-4268-87e7-86b51a2f76c9)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
Apparently J2K is joining the Artist and Author fields into one without accounting when one of them is empty. It seems to handle `null` and duplicates though, so it's an easy fix
