### ISSUE TITLE
Hizo Manga : error 404

### ISSUE THREAD

**Issue by DemonEmperor1** [keiyoushi/tachiyomi-extensions-source#2411]
### Source information

HizoManga 1.4.37

### Source language

Arabic

### Steps to reproduce

1- Entering the source 
2- Error 404

### Expected behavior

It should open

### Actual behavior

Error 404 should not appear because the site is busy

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12 

### Other details

A picture of the problem
![Screenshot_٢٠٢٤٠٤١٤-٠٩٣١٥٢_Mihon](https://github.com/keiyoushi/extensions-source/assets/161745216/4129c502-2197-42d2-8695-92cb7d67d5e2)

A picture of the site
![Screenshot_٢٠٢٤٠٤١٤-٠٩٣١٥٧_Mihon](https://github.com/keiyoushi/extensions-source/assets/161745216/5d71fc08-a43f-48b8-935b-f4cfa030fa77)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
does the site even have any manga? it is all novels as far as I can tell

**Comment by Norsze** [comment]
I also looked I can't find anything except text, looks like they are just hosting the translation with no scanlations. 

Inb4 we change this into a removal request...
