### ISSUE TITLE
Mangas No Sekai Blocked

### ISSUE THREAD

**Issue by AleixLopez17** [keiyoushi/tachiyomi-extensions-source#2420]
### Source information

Mangas No Senkai 1.4.49

### Source language

Spanish

### Steps to reproduce

Enter the extension
Open website
The page say u are blocked to the page

### Expected behavior

You enter the page and you see the mangas

### Actual behavior

You enter the page and not download the mangas and u open the website and say u are blocked

![Screenshot_2024-04-14-20-01-36-125_eu kanade tachiyomi](https://github.com/keiyoushi/extensions-source/assets/79077041/476d58ec-aef2-46e4-a7c7-391ced62444b)

### Mihon/Tachiyomi version

Tachiyomi 0.15.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Change your user agent in app settings

**Comment by br14n-sol** [comment]
Same problem

**Comment by br14n-sol** [comment]
> Change your user agent in app settings

it worked, thanks 🫡
