### ISSUE TITLE
Please add MandaloAsiNoma

### ISSUE THREAD

**Issue by KatoMegushua** [keiyoushi/tachiyomi-extensions-source#2424]
### Source name

MandaloAsiNoma

### Source link

https://mandaloasinoma.com/home

### Source language

Spanish

### Other details

18+/NSFW = yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
The site doesn't have a reader; it only provides links to other sites
