### ISSUE TITLE
Dead source: Coco Rip

### ISSUE THREAD

**Issue by br14n-sol** [keiyoushi/tachiyomi-extensions-source#2425]
### Source name

Coco Rip

### Source language

Spanish

### Source link

https://cocorip.net/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Was online 6th April ( https://web.archive.org/web/20240406021650/https://cocorip.net/ ), so I'd wait a few more days before declaring it as dead dead

**Comment by bapeey** [comment]
they announced that they would be uploading to another website (is dead too lol)
![image](https://github.com/keiyoushi/extensions-source/assets/90949336/e375ba50-95ea-4532-a01a-b50efb1d0751)

**Comment by br14n-sol** [comment]
> Was online 6th April ( https://web.archive.org/web/20240406021650/https://cocorip.net/ ), so I'd wait a few more days before declaring it as dead dead

@bapeey I don't know if you wait a little longer 😅

**Comment by br14n-sol** [comment]
> they announced that they would be uploading to another website ![image](https://private-user-images.githubusercontent.com/90949336/322330130-e375ba50-95ea-4532-a01a-b50efb1d0751.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNDYyNjAsIm5iZiI6MTcxMzE0NTk2MCwicGF0aCI6Ii85MDk0OTMzNi8zMjIzMzAxMzAtZTM3NWJhNTAtOTVlYS00NTMyLWEwMWEtYjUwZWZiMWQwNzUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDAxNTI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YzM4YWQyNjM0ZjQwYWY2NjZkYjA0YWI3OTY5NWFkNTI3YzkwMDIyNDFlYWViZmU1NTgzOWQ2MjZlZWE1YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gHOR6G6sHS5hi5AONunxJSGoIXD6Dnmwx9ndX33KB1k)

Ohh

**Comment by br14n-sol** [comment]
In this case I don't know how they handle name changes here, as it doesn't look like a simple url change

**Comment by bapeey** [comment]
nvm, in another post they said that the page will remain active, the new page is also down so probably they are just having issues
![image](https://github.com/keiyoushi/extensions-source/assets/90949336/c6faf52e-28e4-4455-9093-a64989af329b)

**Comment by br14n-sol** [comment]
> nvm, in another post they said that the page will remain active, the new page is also down so probably they are just having issues ![image](https://private-user-images.githubusercontent.com/90949336/322331498-c6faf52e-28e4-4455-9093-a64989af329b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNDcyOTYsIm5iZiI6MTcxMzE0Njk5NiwicGF0aCI6Ii85MDk0OTMzNi8zMjIzMzE0OTgtYzZmYWY1MmUtMjhlNC00NDU1LTkwOTMtYTY0OTg5YWYzMjliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDAyMDk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5YmZlZmM3OTA2ZjM0MDhkNDI3ZGNhN2VkN2E5Y2VkZjdiMWM4NTUzZTExZDc0ZTJhMjFhNGU3NjU3NTEwYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HoHrCDlcYXZPBYOrlwANxSENyBcqTbYct7MiUDEnG18)

Then I guess we can close this issue?

**Comment by bapeey** [comment]
Site is up again
