### ISSUE TITLE
Mangaoni error bad base-64

### ISSUE THREAD

**Issue by Luis6161** [keiyoushi/tachiyomi-extensions-source#2441]
### Source information

"Mangaoni 1.4.15"

### Source language

Spanish

### Steps to reproduce

1.enter to the mihon app
2.enter to the mangaoni extension
3.the chapter close and say bad base-64

### Expected behavior

"should the chapter and pages of the manga appear as usual"

### Actual behavior

"instead the chapter close and can't read and a notification appear and say bad base-64"

### Mihon/Tachiyomi version

"0.16.5"

### Android version

"android 11"

### Other details

![Screenshot_2024-04-15-00-31-48-340_app mihon](https://github.com/keiyoushi/extensions-source/assets/167060245/ec3dadf7-a6cc-476e-8d52-92da477d3628)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
#2439 should fix it

Please wait for the fix to be added into the repo (wait for an extension update)
