### ISSUE TITLE
Dead source: MidnightManga

### ISSUE THREAD

**Issue by br14n-sol** [keiyoushi/tachiyomi-extensions-source#2444]
### Source name

MidnightManga

### Source language

Spanish

### Source link

http://midnightmanga.com

### Other details

Error 404

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by br14n-sol** [comment]
Still with the same 404 error 🤔

**Comment by choppeh** [comment]
Is there  any notice about closing or migration domain from discord/telegram channel?

**Comment by choppeh** [comment]
> Is there any notice about closing or migration domain from discord/telegram channel?

I couldn't find a community on discord/telegram
