### ISSUE TITLE
Anchira: add support for the search filters

### ISSUE THREAD

**Issue by MediocreLegion** [keiyoushi/tachiyomi-extensions-source#2447]
### Source name

Anchira

### Source language

English

### Describe your suggested feature

Recently, Anchira added support for the `NOT` operator on searches, making it finally possible to fully add the filters when searching tags, artists, etc, in the extension.

### Other details

Full list of namespaces and operators can be found in the [about search](https://anchira.to/about/search) section on the site.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
Page shows that `NOT` is just prefixing the argument with a dash which you can already do in the corresponding filter field, what additional implementation would be necessary?

You can also just type advanced queries in the search field itself

**Comment by MediocreLegion** [comment]
Instead of having to type out the advanced query, let the extension handle it for you using filters, similar to what the other extensions allow you to do:

![Screenshot_2024-04-15-21-50-40-354_eu kanade tachiyomi j2k](https://github.com/keiyoushi/extensions-source/assets/162182192/c0349c65-0a44-45af-828c-8b1740347bfa)

**Comment by MediocreLegion** [comment]
I believe would just require a bit of parsing and formatting to add the `namespace:` or `-namespace:` at the beginning of each word in the filter

**Comment by BrutuZ** [comment]
~~It already works the same way, prepend the word with a dash and it becomes an exclusion~~

Nevermind, I type the query directly so don't really use the Filter tab for anything other than changing the sorting. My local build for the previous version of the site did have the separate fields so I forgot this one doesn't, just assumed they were hidden in one of the collapsibles.

In addition to not using filters I'd also like to keep my currently saved searches on SY and changing anything in that form would trash them, so I'll leave this one to someone else 😋

**Comment by Norsze** [comment]
Source died due to DMCA
