### ISSUE TITLE
Lalamanga can't connected

### ISSUE THREAD

**Issue by reygrey666** [keiyoushi/tachiyomi-extensions-source#2452]
### Source information

Lala Manga 1.4.35

### Source language

English

### Steps to reproduce

1. Open Lalamanga
2. HTTP 403, check website in Webview

### Expected behavior

1. Open Lalamanga
2. The content appears

### Actual behavior

1. Open Lalamanga
2. HTTP 403
3. Open in Webview
4. "Checking your browser before accessing..." page appear
5. The site content appear
6. Go back to Lalamanga extension
7. Still failed to load the contents

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 11

### Other details

Looks like Lalamanga purposely blocking Mihon

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Can't reproduce the issue. Browse works, chapter listing works, manga details works, page parsing works, filtering works.

Can you still reproduce the issue?

**Comment by reygrey666** [comment]
> Can't reproduce the issue. Browse works, chapter listing works, manga details works, page parsing works, filtering works.
> 
> Can you still reproduce the issue?

Hi, Thanks for the reply, and yes somehow the issue solved by itself. But looks like there's no update in 3 weeks on that site. I will close this issue :(
