### ISSUE TITLE
ReadManga (ru): Wrong CDN host

### ISSUE THREAD

**Issue by AlexMalevskii** [keiyoushi/tachiyomi-extensions-source#2454]
### Source information

ReadManga

### Source language

Russian

### Steps to reproduce

1. Browse
2. Sources
3. ReadManga
4. Open any manga
5. Start
6. Picture can't be loaded

### Expected behavior

1. Browse
2. Sources
3. ReadManga
4. Open any manga
5. Start
6. Pictures loading

### Actual behavior

1. Browse
2. Sources
3. ReadManga
4. Open any manga
5. Start
6. Picture can't be loaded
7. Open WebView
Hostname in application is https://p2m.rmr.rocks but real hostname is https://p8.rmr.rocks/

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
cannot reproduce
