### ISSUE TITLE
jinmantiantang

### ISSUE THREAD

**Issue by huajideshutiao** [keiyoushi/tachiyomi-extensions-source#2455]
### Source information

jinmantiantang v1.4.42

### Source language

Chinese

### Source new URL

18comic-eldenring.vip  分流1 18comic-eldenring.me  分流2 18comic-eldenring.xyz

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by YuGhi-bug** [comment]
same problem

**Comment by stevenyomi** [comment]
https://github.com/stevenyomi/source-domains/commits/gh-pages/jmcomic.txt
