### ISSUE TITLE
Can't download any extensions 

### ISSUE THREAD

**Issue by Cabars** [keiyoushi/tachiyomi-extensions-source#2458]
### Source information

Every extension 

### Source language

English

### Steps to reproduce

1.Try to download extensions 2. It says pending for a split second 3.It stops downloading all together 

### Expected behavior

I should be able to download the extensions and then use them.

### Actual behavior

Everytime I try to download an extension it's says pending for a split second and then stops

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
We can't do anything over your phone, network or ISP causing you issues. We can only fix the code in the extensions. You'll just have to download and install them manually from https://keiyoushi.github.io/extensions/
