### ISSUE TITLE
manhwax.org http 500 error

### ISSUE THREAD

**Issue by gan-of-culture** [keiyoushi/tachiyomi-extensions-source#2463]
### Source information

Manhwax 1.4.31

### Source language

English

### Steps to reproduce

1. Install newest version of manhwax extension
2. Goto "Browse" -> Sources -> click on Manhwax
3. Error appears

### Expected behavior

Mangas should appear and be browseable.

### Actual behavior

Error HTTP 500 is shown

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

Webview works.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
the website itself is having issues, nothing we can do
