### ISSUE TITLE
Add Webtoon Indonesia daily ticket 

### ISSUE THREAD

**Issue by D47290C1** [keiyoushi/tachiyomi-extensions-source#2464]
### Source name

Webtoon

### Source language

Indonesia

### Describe your suggested feature

Webtoon Indonesia recently add new feature called daily ticket. If you login via browser new chapter not showing (see attached image) and only showing if you login via webtoon app. New chapter can be unlocked using daily ticket ( 1 ticket will be available,reload everyday at 21:00 GMT+7)

Daily ticket can't be used to unlock 14 latest chapter

Chapter unlocked using daily ticket will be available for 14 days

### Other details

![IMG_20240414_064322](https://github.com/keiyoushi/extensions-source/assets/16864848/41af83f6-bcbd-44a2-a83f-29bf5d491d70)
![IMG_20240414_064348](https://github.com/keiyoushi/extensions-source/assets/16864848/be093709-bc14-4e67-98e9-1a28cec5fb20)
![Screenshot_2024-04-14-06-47-27-261_com naver linewebtoon](https://github.com/keiyoushi/extensions-source/assets/16864848/d23ea94f-fe7a-4fb0-bffa-0f31b74438c9)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
The extension uses the website, if they don't show up on the site then nothing we can do. We won't be using the app API.
