### ISSUE TITLE
Change url  ikigaiMangas

### ISSUE THREAD

**Issue by Athrun0311** [keiyoushi/tachiyomi-extensions-source#2492]
### Source information

Ikigai Mangas 1.4.4

### Source language

Spanish 

### Source new URL

https://lectorikigai.net

### Other details

![Screenshot_20240419_175000_com facebook katana](https://github.com/keiyoushi/extensions-source/assets/160463122/b4244b07-adf3-4109-bdc3-2615329a8ab1)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
https://ikigaimangas.com/ is still up, they just changed the theme
