### ISSUE TITLE
ConstellarComic : Source Request

### ISSUE THREAD

**Issue by ImperialXeno** [keiyoushi/tachiyomi-extensions-source#25]
### Source name

ConstellarComic

### Source link

https://constellarcomic.com/

### Source language

English

### Other details

NSFW = Yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by kirby1hero** [comment]
<img width="738" alt="image" src="https://github.com/keiyoushi/extensions-source/assets/56371129/00c67415-26ac-42c2-b721-f2fdd718341b">

Gonna be interesting
