### ISSUE TITLE
Error 404 Ikigai mangas

### ISSUE THREAD

**Issue by Kai890415** [keiyoushi/tachiyomi-extensions-source#2510]
### Source information

Ikigai mangas 1.4.5

### Source language

Spanish

### Steps to reproduce

It occurs since the last update that the 404 error jumps with any chapter that is tried to open. It's not a problem of the origin because I've already checked and it's fine 

### Expected behavior

Function properly 

### Actual behavior

Error 404 always occurs when trying to open 

### Mihon/Tachiyomi version

TachiJ2K 1.7. 4

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Try migrating your manga titles back into Ikigai to update the URL, then try to open said chapters in said migrated title

**Comment by Kai890415** [comment]
TheI tried it right now but the same error still exists
