### ISSUE TITLE
Ikigaimangas - dont work - change url api

### ISSUE THREAD

**Issue by danielblafer** [keiyoushi/tachiyomi-extensions-source#2513]
### Source information

Ikigai Mangas 1.4.6

### Source language

Spanish

### Steps to reproduce

the web has been updated, I think internally too, I opened an api url that I had saved for these cases and it is at 404.

I think we will have to look for the new url and update the code.

### Expected behavior

need to download the chapters

### Actual behavior

list and search for series, I don't think the api has changed much, maybe they relocated the one that lists the images of chapters

### Mihon/Tachiyomi version

0.14.7

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
the extension now doesn't use the api for the pages, whats the issue?

**Comment by kuvoid** [comment]
> the extension now doesn't use the api for the pages, whats the issue?

a.

I talked to what I remembered, re-downloaded and added the extension just in case.

but the result is the same, the only thing it doesn't do is download chapters.

![Screenshot_20240421-170041](https://github.com/keiyoushi/extensions-source/assets/44142877/2306c12b-6791-4ac5-8f59-e384e55a1f2e)

**Comment by bapeey** [comment]
Open WebView, select a display mode and try again, maybe I can add a interceptor for that

**Comment by kuvoid** [comment]
> Open WebView, select a display mode and try again, maybe I can add a interceptor for that

that worked! 
It is true that what prevented it was the display mode, thanks for help
