### ISSUE TITLE
IMHentai Search Not Working

### ISSUE THREAD

**Issue by Kenn876** [keiyoushi/tachiyomi-extensions-source#2515]
### Source information

IMHentai 1.4.14

### Source language

English

### Steps to reproduce

1. Go to source
2. Go to IMHentai
3. Search name of comic, manga, manhwa, etc

### Expected behavior

Should show results for the comic, manga, manhwa, etc.

### Actual behavior

Keeps saying "No results found"
![Screenshot_20240422_003109](https://github.com/keiyoushi/extensions-source/assets/137243023/b25e3f1e-f01b-4c2e-bbfe-0ec5d0dabe05)

### Mihon/Tachiyomi version

Tachiyomi 0.15.3

### Android version

Android 12

### Other details

I checked if the comic, manga, manhwa, etc is available in the site before looking for it in the extension source. Still doesn't show that the comic is there in the site extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
the specific title in your screenshot only available in Japanese & Korean while you are using English source so "no results" is expected.
Try enable all languages in Filters.
