### ISSUE TITLE
covers without images

### ISSUE THREAD

**Issue by Nerannnn** [keiyoushi/tachiyomi-extensions-source#2522]
### Source information

Bakai 1.4.3

### Source language

Portuguese 

### Steps to reproduce

the manga covers are not showing

### Expected behavior

![Screenshot_20240422-084352](https://github.com/keiyoushi/extensions-source/assets/135178613/5e7ca906-8bfa-49a3-b95f-d54ec94989d7)

### Actual behavior

![Screenshot_20240422-084335-828](https://github.com/keiyoushi/extensions-source/assets/135178613/43ab2e79-0226-47d8-885e-10a4d0266d80)

### Mihon/Tachiyomi version

0.15.2

### Android version

Android 11

### Other details

This problem isn't stopping me from reading the manga, it's just a bit annoying not knowing what I'm reading based on the manga cover

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
I can't reproduce this error. Please update the version to V0.15.3 or use the latest version of supported apps. You reported from V0.15.2.

**Comment by Nerannnn** [comment]
I just updated to version 0.15.3 but the covers still aren't showing up,
but honestly, even if you can't help me, it's still possible to read the
manga and I've been wanting to update my app for a while now, so anyway
thanks.

Em seg., 22 de abr. de 2024 11:16, Chopper ***@***.***>
escreveu:
