### ISSUE TITLE
Westmanga

### ISSUE THREAD

**Issue by nuginity15** [keiyoushi/tachiyomi-extensions-source#2536]
### Source information

West Manga 1.4.34

### Source language

Indonesia

### Source new URL

https://westmanga.net

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Current domain is still working. Create a source request issue instead.
