### ISSUE TITLE
BoyLove 香香腐宅: Scrambled source images now being used in new titles/chapters

### ISSUE THREAD

**Issue by morallkat** [keiyoushi/tachiyomi-extensions-source#254]
### Source information

BoyLove / 香香腐宅 1.4.9

### Source language

Chinese

### Steps to reproduce

1. Install the extension
2. Find a title that **have newly updated chapters after 2024**
3. Open in the app

### Expected behavior

The image should be displayed correctly and completely
E.g (part of normal image): 
![image](https://github.com/keiyoushi/extensions-source/assets/156603547/73329c81-d683-48fb-b161-09576f3b8462)

### Actual behavior

The image from source link now being scrambled, **for the new titles/chapters uploaded after 2024.**
On the website, it uses the script to rearrange the images after page loaded. But since the extension just grab the source image links, the app will only get the unprocessed images.

E.g (part of scrambled image):
![image](https://github.com/keiyoushi/extensions-source/assets/156603547/ba7bba9c-3545-4a8b-bb96-6e639cae1bfa)

### Tachiyomi version

0.15.3

### Android version

Android 14

### Other details

When inspecting the page, Some code that might be related to rearrange the image using HTML canvas were found.
<details>
<summary>Details</summary>

```js
function firstMergeImg(scrollTop) {

    var viewportData = $('#viewport0');
    var scrollTop = $(window).scrollTop();
    var itemofftop = $(viewportData).offset().top;
    var winHeight = window.innerHeight;
    var itemBottomOfftop = $(viewportData).offset().top + $(viewportData).height();
    var canvas0 = document.getElementById('viewport0');
    var ww0 = 1280;
    var hh0 = 1819;

    if (scrollTop + winHeight >= itemofftop && scrollTop <= itemBottomOfftop + 2000) {
        if ($(viewportData).hasClass('hasCanvas')) {

        } else {
            $(viewportData).addClass('hasCanvas');
            var num = 8;
            canvas0.width = ww0;
            canvas0.height = hh0;

            var context0 = canvas0.getContext("2d");
            var imgObject0 = new Image();
            do_mergeImg(context0, imgObject0, ww0, hh0, "/bookimages/path/to/source.webp?w=1280_1819", num);
            var canvasKeyW = $('#viewport0').width();
            var canvasKeyH = $('#viewport0').height();
            $('#viewport0').parents('.reader-cartoon-image').css('width', canvasKeyW);
            $('#viewport0').parents('.reader-cartoon-image').css('height', canvasKeyH);
        }

    } else {

        var context0 = canvas0.getContext("2d");
        $(viewportData).removeClass('hasCanvas');
        context0.clearRect(0, 0, ww0, hh0);

        var canvas0 = document.getElementById('viewport0');
        canvas0.width = 0;
        canvas0.height = 0;
    }
```

</details>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by HYChin** [comment]
Hi, any update of this bug ?

**Comment by beer-psi** [comment]
Since we're run by volunteers, making an issue does not imply that the problem will be fixed in a timely fashion. Please be patient.

**Comment by Morse069** [comment]
Hello is the issue fixed?

**Comment by beer-psi** [comment]
Please be patient, it is fixed when a volunteer contributes time to fix it.
