### ISSUE TITLE
Mangago stopped 

### ISSUE THREAD

**Issue by caduHD4** [keiyoushi/tachiyomi-extensions-source#2547]
### Source information

Mangago 1.4.14

### Source language

English 

### Source new URL

https://mangago.me

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Neen-ia** [comment]
The WebView is working fine but the homepage in tachiyomi and mihon is not displaying anything. Searched mangas are also not appearing
![Screenshot_2024-04-24-12-28-25-895_eu kanade tachiyomi](https://github.com/keiyoushi/extensions-source/assets/167951342/26bd380c-de23-4473-9416-f1e20c7dc933)
![Screenshot_2024-04-24-12-28-18-773_eu kanade tachiyomi](https://github.com/keiyoushi/extensions-source/assets/167951342/709c21cf-4faf-4ce3-b1fb-22eced7d0f20)
