### ISSUE TITLE
Mangago not working

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#2548]
### Source information

Mangago 1.4.14

### Source language

English 

### Steps to reproduce

Open Mangago source 

### Expected behavior

The source should work.

### Actual behavior

But the source doesn't work in the app. It only works in the WebView. 

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
I didn't find any errors. Need more information

**Comment by AwkwardPeak7** [comment]
please open issue with any specific errors you encounter
