### ISSUE TITLE
URL Changed

### ISSUE THREAD

**Issue by Lexuzz5** [keiyoushi/tachiyomi-extensions-source#2566]
### Source information

Oympus Scanlation

### Source language

Spanish/Español

### Source new URL

https://leelolympus.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #2557 as mentioned, along with duplicate of #2561, #2562, #2563, and #2564.

Search and check the existing issues before opening a new issue, and ignorantly acknowledging that you did.

Patiently wait for a future extension update.
