### ISSUE TITLE
Comick Extension Webview Not Functioning

### ISSUE THREAD

**Issue by ImpenetrableNoble** [keiyoushi/tachiyomi-extensions-source#2567]
### Source information

1.4.42

### Source language

English 

### Steps to reproduce

1. Open Tachiyomisy or Mihon application.

2. Navigate to the Comick Extension.

3. Select any manga source.

4. Attempt to load a manga chapter using the web view.

### Expected behavior

The webview should load the selected manga chapter from the chosen source, allowing seamless reading within the application.

### Actual behavior

The webview fails to load the manga chapter, leaving a blank or error page.

👇

![Screenshot_20240424_233613](https://github.com/keiyoushi/extensions-source/assets/104534608/1aeece48-d115-40f5-b99c-fe36360dbe58)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Other details

I'm sure that one potential reason for the webview failure could be a compatibility issue between the Comick Extension and Mihon application.

Like maybe, any recent updates or changes to the Comick Extension or the application itself could have inadvertently caused this malfunction.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Works fine for me, you should check the source's support/status next time before opening a new issue. HTTP 500 usually means something's wrong on the source's server (which they were having problems an hour earlier).

Go to Mihon Settings > Advanced, and clear cookies & WebView data. Maybe also go to Mihon Browse Page > Extension tab > Comick extension info, and clear the cookies within there too for extra measure.
