### ISSUE TITLE
MangaDogs update on Nine manga extension 

### ISSUE THREAD

**Issue by FranciscoGR04** [keiyoushi/tachiyomi-extensions-source#2569]
### Source information

NineManga

### Source language

Spanish 

### Steps to reproduce

When I want to read a chapter of any manga, an image appears that says "urgent! Please update" but instead of being the extension it is Manga dogs.

### Expected behavior

Read any manga 

### Actual behavior

An image asking to update Manga Dogs
![Screenshot_20240425_034558_Mihon](https://github.com/keiyoushi/extensions-source/assets/137955284/4c2c4571-00cc-464d-a0d9-b3b8ab5a7707)
![Screenshot_20240425_034552_Mihon](https://github.com/keiyoushi/extensions-source/assets/137955284/dd95ff50-f572-44bb-b531-53c7e14f08d8)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by archit9169** [comment]
Seems like an issue with the site  rather than an issue witht the extension.

![Screenshot_20240425_153406_Brave](https://github.com/keiyoushi/extensions-source/assets/23340961/0a35cce2-e716-49dd-9121-24bdf05cb83e)

Tried opening jn browser to see how it shows there, the same. On clicking the series from homepage of ninemanag it redirects to another website.

**Comment by archit9169** [comment]
`https://en.ninemanga.com/chapter/Welcome%20to%20Dungeon%20Hotel/15952260-1-1.html`

This one is the url that is being fetched by Tachiyomi.

`https://en.ninemanga.com/chapter/Welcome%20to%20Dungeon%20Hotel/15952260.html`

This one works fine when opening from the browser.

**Comment by archit9169** [comment]
Created a draft pull with the fix https://github.com/keiyoushi/extensions-source/pull/2570#issue-2263221931

I dont have android studio to do one of the checks in checklist. If someone can quickly check and progess the draft pull, that would be great.

**Comment by mohamedotaku** [comment]
> Created a draft pull with the fix [#2570 (comment)](https://github.com/keiyoushi/extensions-source/pull/2570#issue-2263221931)
> 
> I dont have android studio to do one of the checks in checklist. If someone can quickly check and progess the draft pull, that would be great.

it's good
