### ISSUE TITLE
ثاندر سكانز

### ISSUE THREAD

**Issue by aahazzbr99** [keiyoushi/tachiyomi-extensions-source#2577]
### Source name

ثاندر سكانز-Thunderscans

### Source link

https://ar-thunderscans.com

### Source language

arabic

### Other details

نعم

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by mohamedotaku** [comment]
did you chek [all.thunderscans](https://keiyoushi.github.io/extensions/#all.thunderscans)
this Source already exist
