### ISSUE TITLE
Drake Scans Chapter Pages Not Loading and Can't be Downloaded

### ISSUE THREAD

**Issue by Kenn876** [keiyoushi/tachiyomi-extensions-source#2579]
### Source information

Drake Scans 1.4.40

### Source language

English

### Steps to reproduce

1. Go to Drake Scans
2. Pick a manga or manhwa
3. Try and read chapters

### Expected behavior

Should show pages and can download chaptera.

### Actual behavior

It keeps saying "The page couldn't be loaded".

### Mihon/Tachiyomi version

Tachiyomi 0.15.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by fqrious** [comment]
I can't reproduce this issue

**Comment by mohamedotaku** [comment]
Domain changed
