### ISSUE TITLE
TCB URL change 

### ISSUE THREAD

**Issue by neildube** [keiyoushi/tachiyomi-extensions-source#2580]
### Source information

TCB Scans 1.4.7

### Source language

English 

### Source new URL

https://tcb-backup.bihar-mirchi.com

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
That's just their backup site iirc, but the extension should be working (and works on my end).

Go to WebView for your title or source, let it redirect to backup, then it should work. See #2320 comments for extra info
