### ISSUE TITLE
Gekkou Scans - shutdown

### ISSUE THREAD

**Issue by DFBR1208** [keiyoushi/tachiyomi-extensions-source#2587]
### Source name

Gekkou Scans 1.4.37

### Source language

Portuguese (Brazil)

### Source link

https://gekkou.site/

### Other details

@everyone <@&703023164925411398> 
Opa! 19 de abril, a scan completou 12 anos de vida. Não consegui postar antes, pois estava pensando em escrever este texto. Desde que fiz uma loucura lá em meados de 2012 ao abrir uma scan em um momento em que praticamente não havia ninguém fazendo isso, venho pensando no dia em que faria a postagem de despedida... E esse dia chegou.

A scan foi criada porque não havia ninguém traduzindo as obras que eu gostava, e essa filosofia persistiu até hoje. Primeiro veio Monster Musume (um ecchi divertido que estava quase um ano sem tradução na época, e logo se tornou viral, despertando o interesse até de grupos mais antigos na época em um mangá completamente aleatório. Depois veio "Girls of The Wild's", um webtoon com traços simples e estranhos com um protagonista lerdo, mas que, após meses, com os leitores dando uma chance, acabou se tornando popular (ainda me lembro da época em que os capítulos de Girls, um projeto coreano com um formato pouco conhecido no Brasil, tinha apenas 13 downloads, kkkkk). De lá para cá, comecei (junto com pessoas que tinham a mesma vontade) a trazer alguns webtoons e mangás que gostava, e mesmo sem muitas visualizações e comentários, continuei insistindo em suas traduções simplesmente por gostar das obras. Foi assim que a maioria de vocês veio parar aqui, por meio de Eleceed (da desenhista de Girls), Wind Breaker, Lookism, Ao Ashi, Jujutsu Kaisen, Blue Lock, entre outros. (ALÉM DOS MEUS QUERIDOS HENTÕES E ECCHIS)

Obviamente, não sou pretensioso a ponto de achar que o grupo era um fator que influenciava algum projeto a ser licenciado no Brasil apenas por apostar nele no início, mas quando isso acontecia, era bastante gratificante (comprem AO ASHI).

Esse momento inicial dos webtoons e mangás foi muito bom! Criar amizades, traduzir o que gosta mesmo sem nada em troca... Durou cerca de 7, 8 anos, mas em determinado momento TUDO mudou quando TUDO viralizou. Não apenas One Piece, Naruto e Bleach, mas todos os webtoons ficaram virais! (quando digo todos, é em um contexto geral: webtoons de RPG, isekai, manhuas de cultivação, etc.)

Basicamente, esse mercado cresceu muito mais do que qualquer pessoa esperava e hoje se tornou impossível manter um grupo e continuar com essas atividades de forma tranquila, afinal, mesmo que a obra não tenha uma versão em português ou seja simulpub, não sou eu quem decide o que é pirataria.

Sendo sincero, a longo prazo não vejo alternativa em continuar com o grupo, já que é um mercado que tende a crescer cada vez mais, e, com isso, inevitavelmente chamará atenção, nos colocando em risco desnecessário. A ideia inicial do grupo era totalmente despretensiosa.

Agradeço aos bons que foram essenciais nessa jornada e aos amigos que fiz, agradeço aos primeiros leitores de 2012 que deram seus feedbacks, e aos que acessavam a scan todos os dias. Foram 12 anos ininterruptos; talvez nenhuma outra scan tenha sobrevivido tanto tempo dessa forma, mas chegamos ao fim com o dever cumprido.
Nos vemos algum dia!

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
Official closing. Screenshot:

![Screenshot_2024-04-26-19-22-20-513_com discord](https://github.com/keiyoushi/extensions-source/assets/156493704/faa7291d-0128-4ae4-b03e-a061dad2380a)
