### ISSUE TITLE
YakshaScans chain validation failed

### ISSUE THREAD

**Issue by sovit042** [keiyoushi/tachiyomi-extensions-source#2593]
### Source information

YakshaScans 1.4.35

### Source language

English

### Steps to reproduce

1. Download YakshaScans extension and set as trusted
2. Open the extension and it will show SSLHandshakeException: Chain validation failed
![Screenshot_2024-04-27-02-26-26-379_app mihon](https://github.com/keiyoushi/extensions-source/assets/101596014/43e2cdf2-02a9-457c-b5d3-36e06201381c)

### Expected behavior

It should load the favourite series on YakshaScans 

### Actual behavior

It's showing SSLHandshakeException: Chain validation failed

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
The website itself is down.

**Comment by kktuin** [comment]
Same here webs works fine in webview

**Comment by ManiV97** [comment]
![Screenshot_20240427_100452](https://github.com/keiyoushi/extensions-source/assets/143166150/f517e3fc-d826-47f8-a612-032837e4650a)
The website is working

**Comment by KirinRaikage** [comment]
Ah indeed, the issue might be with Firefox-based browsers, it works fine with Chrome-based browsers.

**Comment by mohamedotaku** [comment]
This was a problem with the website, they have now fixed it.
