### ISSUE TITLE
MangaForFree.net not fetching all chapters

### ISSUE THREAD

**Issue by Bluesnake-42** [keiyoushi/tachiyomi-extensions-source#2628]
### Source information

MangaForFree.net 1.4.36 

### Source language

All

### Steps to reproduce

on the website MangaForFree.net , there are chapters that end with raw. for example Chapter 89 raw.
in the app, the extension does not show any chapters that end with raw.

### Expected behavior

the extension in the app should show all chapters that are available on the website

### Actual behavior

the extension is not showing chapter that end with raw 

### Mihon/Tachiyomi version

tachij2k 1.7.4

### Android version

android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
That's the expected behavior if you're browsing the English source. If you want raw chapters you need to use the source under Multi or 한국어. If they don't show up you can check if it's disabled by the filter in the top right corner.

![image](https://github.com/keiyoushi/extensions-source/assets/13540478/e5f9ec1c-5d09-4f99-9d07-0047a5c1a541)
