### ISSUE TITLE
Automatic Deletion of Downloaded Chapters from Bato.to Extension

### ISSUE THREAD

**Issue by unilimitx** [keiyoushi/tachiyomi-extensions-source#2629]
### Source information

Bato.to 1.4.35

### Source language

English

### Steps to reproduce

I downloaded a few chapters from Bato.to, but after 24 hours, all the chapters from that extension were automatically deleted. This issue has been ongoing for more than 2 years.

### Expected behavior

It's should be saved permanently 

### Actual behavior

But it's deleted after 24hrs after downloaded

### Mihon/Tachiyomi version

App version: 0.16.5

### Android version

Android 12

### Other details

Device: Samsung 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
That's not how that works. The extension can't delete downloaded chapters for you.

They're either:
1) The chapter name, URL, or something else was changed/updated from the source, causing it to unlink from your previously downloaded chapter
2) A side-effect of Android Scoped Storage

You should go to Mihon Settings > Advanced > Invalidate downloads index, so the app can recheck your downloads. You can also go to your File Manager > Mihon folder > Downloads, and check if the chapters are still downloaded/downloaded correctly. If they have "_tmp" in the name, then delete that or redownload those as it might be a broken/incompletely downloaded chapter.

**Comment by unilimitx** [comment]
I already checked the Bato.to folder after downloading:
- It was saved in CBZ format.
- I didn't enable anything in the delete chapters option except for ``` 'After reading automatically delete' set to 'From the fourth to the last read chapter'```
- The following day (after 24 hours), the manga folders were empty.
- However, the other extensions are working fine.

**Comment by AwkwardPeak7** [comment]
Extensions can't delete downloaded chapters, likely a misconfiguration or problem on your part. You can go to Mihon server to ask for help. (Don't mention extensions there)
