### ISSUE TITLE
Add mangahona.pl

### ISSUE THREAD

**Issue by SnieznyDaniel2115** [keiyoushi/tachiyomi-extensions-source#2635]
### Source name

MangaHoNa

### Source link

https://mangahona.pl

### Source language

Polish

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by SnieznyDaniel2115** [comment]
Oh and i can send you logos if needed
![Without_Background](https://github.com/keiyoushi/extensions-source/assets/131537943/7eeb9710-c8ab-4565-ba3b-d84b9959eb79)
![With_Background](https://github.com/keiyoushi/extensions-source/assets/131537943/7efc94cb-5409-4b92-b9dc-bda894e8663e)

**Comment by SnieznyDaniel2115** [comment]
i will do it myself

**Comment by AwkwardPeak7** [comment]
If you are gonna add it, just make a pull request, no need to close the issue

**Comment by vetleledaal** [comment]
Site has been suspended. Open another issue if the site is available elsewhere.

**Comment by SnieznyDaniel2115** [comment]
I contacted the owner and he will add new issue when site will be avalible
