### ISSUE TITLE
IMhentai error 

### ISSUE THREAD

**Issue by Kotowarenai** [keiyoushi/tachiyomi-extensions-source#2636]
### Source information

"for input strings" 

### Source language

All languages 

### Steps to reproduce

1. Search manga from the source
2. Poke "start reading" 
3. For input strings "random numbers and letters" appears
![Screenshot_20240428-022636](https://github.com/keiyoushi/extensions-source/assets/168333862/7c1517e4-2467-44b3-922f-af6410b6b6c2)

### Expected behavior

.

### Actual behavior

.

### Mihon/Tachiyomi version

TachiJ2K v1.7.4

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Seems fine on my end, what's your extension's version number?

(Next time put the version number into the "Source information" instead)

**Comment by Kotowarenai** [comment]
Sorry I'm new in this, the number version is 1.4.15
