### ISSUE TITLE
TecnoScan change their domain

### ISSUE THREAD

**Issue by DuZkDWN** [keiyoushi/tachiyomi-extensions-source#2645]
### Source information

Tecno Scan 1.4.36

### Source language

Spanish

### Steps to reproduce

1.Open Mihon
2.Go to extensions section
3.Find tecno scan and open them
4.Go to Open in Webview
5.Read and click in the link placed in the text

### Expected behavior

Open the Tecnoscan source

### Actual behavior

Not open the tecno scan source cause they are moved to other website

### Mihon/Tachiyomi version

Beta r6654

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Closing in favor of #2646
