### ISSUE TITLE
Cambio en Tecno

### ISSUE THREAD

**Issue by Striven100** [keiyoushi/tachiyomi-extensions-source#2646]
### Source information

Tecno Scan

### Source language

Español

### Source new URL

https://visortecno.com/

### Other details

Cambio de raw en tecno scan

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Same as #2645, but this issue has the correct label & new link
