### ISSUE TITLE
Slime read unable to resolve host(Duplicate)

### ISSUE THREAD

**Issue by Starkr1** [keiyoushi/tachiyomi-extensions-source#2661]
### Source information

SlimeRead 1.4.6

### Source language

Português ( Brasil)

### Steps to reproduce

First step, when I open the extension in the recent ones, I see unable to host no address associated with him, but the site is still there. 

### Expected behavior

The extension should open with the manga

### Actual behavior

![Screenshot_20240429-024426_Mihon](https://github.com/keiyoushi/extensions-source/assets/160334424/f5c836ea-fb29-4948-b100-5a7c7a007bf1)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 11

### Other details

![Screenshot_20240429-024426_Mihon](https://github.com/keiyoushi/extensions-source/assets/160334424/94be7f9a-a3ad-4902-a170-e83e1f88e481)
![Screenshot_20240429-025632_Mihon](https://github.com/keiyoushi/extensions-source/assets/160334424/e7eab275-9413-4888-b03f-03a226ab80a4)

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [ ] I have updated all installed extensions.
- [ ] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #2655, please search the existing issues before opening a new one & acknowledging that you did
