### ISSUE TITLE
Manhastro Source returning 404 error

### ISSUE THREAD

**Issue by anubishs** [keiyoushi/tachiyomi-extensions-source#2662]
### Source information

Manhastro 1.4.40

### Source language

Portuguese

### Steps to reproduce

1. Download source
2. Open almost any manga on it, using One Piece for ref.
3. 404 error when trying to read a chapter (webview is fine)

### Expected behavior

Chapter should open normally

### Actual behavior

404 error

### Mihon/Tachiyomi version

TachiyomiSY Stable 1.10.5

### Android version

Android 14

### Other details

I informed the issue on discord and they said that it's something with the source latest update and something broke. All was working fine before yesterday update

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
Error not present in the latest versions of the extension or TachiyomiSY.  

@anubishs Could you confirm that the bug is still there?

**Comment by choppeh** [comment]
@AwkwardPeak7 I have not been able to reproduce this error in any version of the supported apps. Could you close the issue?
