### ISSUE TITLE
Extension repo not showing extensions in Mihon

### ISSUE THREAD

**Issue by Abdulsalam-Selim** [keiyoushi/tachiyomi-extensions-source#2679]
### Source information

All Extensions

### Source language

All

### Steps to reproduce

Go to extension and get an update but no update.
Go to extension repo to confirm extension repo is working
New extensions are not showing

Old extensions are working fine and webview is working for all installed extension.
Some extension need update since the source is not working but I can't get an update since there's no new extension is showing up.

### Expected behavior

Uninstalled extensions should be showing up and new updates should also be showing

### Actual behavior

No updates and no uninstalled extensions are showing up. Only installed extension are showing up, all installed extensions are working with no problems 

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
No offense, you should consider asking in Discord support for Keiyoushi before opening a new issue. Try switching networks or use a VPN, some regions/ISPs block GitHub API, making the repo/extensions not visible.

If that doesn't work, remove the repo link you're currently using, and replace with the alternative repo URL instead: https://cdn.jsdelivr.net/gh/keiyoushi/extensions@repo/index.min.json
