### ISSUE TITLE
I can't update all comic at once

### ISSUE THREAD

**Issue by m0pInxxX** [keiyoushi/tachiyomi-extensions-source#268]
### Source information

Indonesia extension 

### Source language

Indonesia 

### Steps to reproduce

1. Refresh library 

### Expected behavior

My library up to date

### Actual behavior

My library not updating any comic

### Tachiyomi version

0.15.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Not an extension issue.

https://tachiyomi.org/docs/faq/library#why-is-global-update-skipping-entries

**Comment by m0pInxxX** [comment]
Ok thx to give me that info, now i can update my comic
