### ISSUE TITLE
Manga Cross无法读取章节

### ISSUE THREAD

**Issue by wuyingkonghuan** [keiyoushi/tachiyomi-extensions-source#2681]
### Source information

Manga Cross 1.4.5

### Source language

Japanese

### Steps to reproduce

![photo_2024-04-30_09-15-28](https://github.com/keiyoushi/extensions-source/assets/102913121/08db5c66-0ab6-4766-9c1c-29f2abb3b5e8)

### Expected behavior

![photo_2024-04-30_09-18-30](https://github.com/keiyoushi/extensions-source/assets/102913121/d3bd0e9a-ad28-40e0-9719-1ff1e16e28f6)

### Actual behavior

![photo_2024-04-30_09-18-31](https://github.com/keiyoushi/extensions-source/assets/102913121/b4048ac4-e4e0-4f78-bec3-1bbfbecbecc5)

### Mihon/Tachiyomi version

J2K1.7.4

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #2532 , search the existing issues first before opening a new issue & acknowledging that you did
