### ISSUE TITLE
miaoshang manhua has changed URL

### ISSUE THREAD

**Issue by hsiayuchih** [keiyoushi/tachiyomi-extensions-source#2682]
### Source information

miaoshang manhua 1.4.7

### Source language

Chinese

### Source new URL

https://www.miaoshangmanhua.cc/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FengTeLai** [comment]
Domain hijacking, wait for the webmaster to restore the site before doing subsequent actions.

**Comment by hsiayuchih** [comment]
> Domain hijacking, wait for the webmaster to restore the site before doing subsequent actions.

@FengTeLai Website has been restored.

**Comment by FengTeLai** [comment]
@stevenyomi 
![1716209111514](https://github.com/keiyoushi/extensions-source/assets/117538601/3d6ca688-b087-4df1-99b2-74d14a866643)
![1716209138289](https://github.com/keiyoushi/extensions-source/assets/117538601/7040d1e1-ca0e-450e-abc5-4e29d9d4a0ac)
Site is back up but showing 404 within the app

**Comment by NeKoOuO** [comment]
Source is down
