### ISSUE TITLE
Mangadex needs a block-manga-by-uuid option

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [keiyoushi/tachiyomi-extensions-source#2684]
### Source information

MangaDex

### Source language

English

### Steps to reproduce

In mangadex settings, continue adding every pedo group to the "block groups by uuid" list, which at the moment is 200+ too many over 1. Then try to update the chapter list for any remaining manga title... 

### Expected behavior

Titles with new chapters (as confirmed in webview) should have updated with those new chapters to the chapter list, unaffected by the blocked groups list since the titles still show up...

### Actual behavior

A "HTTP 414" error shows up instead and nothing updates, showing why having a block-by-manga-uuid feature would be a far better way of doing this since it only needs to be parsed when scrolling through titles, not chapters...

### Mihon/Tachiyomi version

Tachiyomi "1.10.5 ("No new updates available")"

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
[Http 414](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/414) means url is too long, so you have too many groups added to blocklist...

I am not sure what "block-by-manga-id" is supposed to achive? just don't add that manga to library

**Comment by neurodiverseEsoteric** [comment]
I don't want the manga to show up at all. Including browsing. Mangadex webview shows that there are unique ids for each managa entry, and have been for some time, so it's odd that such a feature wasn't already part of the extension? Either way, the blocklist should be as long as anyone wants it to be, even if it fills their hard drive to capacity...

**Comment by AwkwardPeak7** [comment]
1) the blacklist being too long is a technical limitation from Mangadex.

2) Mangadex doesn't provide any way to block certain manga in the api, and filtering them client side means you could end up with "no results" due to techinal limitation from the app that the results can't be empty 

besides, you can just filter out certain genres/tags that you don't want to see

**Comment by neurodiverseEsoteric** [comment]
Tag filtering also culls too many results due to false-positivies and the lack of boolean building (filter tag1 only when together with tag2). Whatever happened to adding onto the api, like photoshop and maya developers do?
