### ISSUE TITLE
mangaraw.ac

### ISSUE THREAD

**Issue by akir45** [keiyoushi/tachiyomi-extensions-source#2701]
### Source name

mangaraw.ac

### Source link

https://www.mangaraw.ac

### Source language

japanese

### Other details

18+　NFSW= yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Source has been down for 3 weeks. Closing.
