### ISSUE TITLE
Rizz Comic gives "Not Available in your Country'

### ISSUE THREAD

**Issue by Nate26-95** [keiyoushi/tachiyomi-extensions-source#2708]
### Source information

Rizz Comic 1.4.33

### Source language

English

### Steps to reproduce

1. Update library
2. Open anything
3. Fails to bypass cloudfair
4. Open website view
5. Gives 'Not Available in your Country's
6. Open in browser
7. Loads website and is readable

### Expected behavior

![Screenshot_2024-05-01-09-16-45-57_551f7f0ca926862b368845ce7ee433aa](https://github.com/keiyoushi/extensions-source/assets/106630464/bd81b265-afce-457d-bef1-abd2237b7160)

### Actual behavior

![Screenshot_2024-05-01-08-44-44-99_551f7f0ca926862b368845ce7ee433aa](https://github.com/keiyoushi/extensions-source/assets/106630464/684326f2-dd3d-41d2-9500-3cf8dbe7e189)

### Mihon/Tachiyomi version

Stable 0.16.5

### Android version

Android 14

### Other details

Rizz loads in app, I can see read chapters and unread chapters. It only happens when you update and view in webview

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Most likely Cloudflare, visit https://keiyoushi.github.io/docs/guides/troubleshooting#cloudflare for help on how to bypass Cloudflare or visit our Discord.
