### ISSUE TITLE
Change feature when touch a manga author's name

### ISSUE THREAD

**Issue by leonminus** [keiyoushi/tachiyomi-extensions-source#2716]
### Source name

Mihon 1.16.5

### Source language

Mihon1.16.5

### Describe your suggested feature

Like tag's interactive, allow me to search in library or copy into cache
I'd like that take place to author name's interactive 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Tachiyomi? TACHIYOMI?

Are you making some joke right now? This is not the Tachiyomi Github, cause that one died 4 months ago.

**Comment by leonminus** [comment]
> Tachiyomi? TACHIYOMI?
> 
> Are you making some joke right now? This is not the Tachiyomi Github, cause that one died 4 months ago.

Sorry sir just keep use both bcuse i have a lot of manga to migrate so i m mistaked that time 8))
