### ISSUE TITLE
PicaComic bad base-64

### ISSUE THREAD

**Issue by KuanKan410** [keiyoushi/tachiyomi-extensions-source#274]
### Source information

Picacomic 1.4.4

### Source language

Chinese

### Steps to reproduce

When tachiyomi is installed and the picacomic extension is opened first time, it works. But when I opened it second time, it shows "IllegalArgumentException: bad base-64", and get nothing.

### Expected behavior

It should shows manga from picacomic

### Actual behavior

The webview shows below
```
{
  "code": 400,
  "error": "1001",
  "message": "the format of accept header is invalid"
}
``` 

### Tachiyomi version

TachiyomiSY 1.10.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by mavnp** [comment]
Picacomic 1.4.2 don't have this problem,but I forget to save it(cry).
