### ISSUE TITLE
Manhwaclub site

### ISSUE THREAD

**Issue by xtprion** [keiyoushi/tachiyomi-extensions-source#2748]
### Source information

ManhwaClub 1.4.5

### Source language

English

### Source new URL

https://manhwaclub.net

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Are you sure this is the new domain for ManhwaClub? The current domain (`manhwa.club`) redirects to another domain (`manhwahentai.to`) which exists as ["Manhwa Hentai" in the English section](https://keiyoushi.github.io/extensions/#en.manhwahentai).

This new domain (`manhwaclub.net`) also uses a different theme, which usually indicate that the site is unrelated.
