### ISSUE TITLE
MangaTX

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#276]
### Source name

MangaTX

### Source language

English

### Source link

https://mangatx.com/

### Other details

It seems to be dead and the website seems to be gone too as it seems to have turned to some sort of scammy sponsorship website. I think they might now be called Manga Kick (https://mangakick.com/), but I'm not sure.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by domflamingo2** [comment]
The site is not dead, please close the issues

![image](https://github.com/keiyoushi/extensions-source/assets/75938421/650fe170-c5d0-491b-b026-3944d125213f)

**Comment by ghost** [comment]
> The site is not dead, please close the issues
> 
> ![image](https://private-user-images.githubusercontent.com/75938421/298600155-650fe170-c5d0-491b-b026-3944d125213f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NTc3MDksIm5iZiI6MTcwNTk1NzQwOSwicGF0aCI6Ii83NTkzODQyMS8yOTg2MDAxNTUtNjUwZmUxNzAtYzVkMC00OTFiLWIwMjYtMzk0NGQxMjUyMTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDIxMDMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiZDY1NDFjZDVjYTkyZjgwZmNiNjY5YWJlOGU3YmUxZTJlNmYzNjI1YmJhMWY4NDkyNWQwZDEwMzA4NGE1Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A2KgZFSk7WjUtZ30YlvI_Nc8fdKIasr1NS1rJv9pixY)

No, I won't as this is the issue that's currently happening with it. 
![kuva](https://github.com/keiyoushi/extensions-source/assets/33172909/46f55ffb-c52a-4f0a-9ea7-f14e1dbe9245)

**Comment by Riztard** [comment]
> The site is not dead, please close the issues
> 


thats different one(unoriginal)
![image](https://github.com/keiyoushi/extensions-source/assets/16263232/8c3ac2ac-abf4-4e3b-91d3-068e9c6bbfdb)
