### ISSUE TITLE
FMTEAM : No series list

### ISSUE THREAD

**Issue by Mourad-Saidomar** [keiyoushi/tachiyomi-extensions-source#2761]
### Source information

fr.fmteam 1.4.5

### Source language

French

### Steps to reproduce

Open Extension FMTEAM

### Expected behavior

This should display the series list

### Actual behavior

But it shows us that "No results found"
![Screenshot_20240502_123318_Mihon](https://github.com/keiyoushi/extensions-source/assets/131191008/cdb8dad4-dc9a-42ed-9864-07092f8bb419)
![Uploading Screenshot_20240502_123325_Mihon.png…]()
And yet, in WebView, the site works without error.

### Mihon/Tachiyomi version

16.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
No issues regarding displaying series on my side:
![Screenshot_20240502_134739_Mihon](https://github.com/keiyoushi/extensions-source/assets/11159175/d2cdee86-e81e-4c7e-8051-0893eb942181)

**Comment by Mourad-Saidomar** [comment]
J'ai testé sur mihon et tachiyomi mais toujours pas.
Quelles versions utilises-tu ?

Les problèmes des HTTP 503 vient du serveur mais j'accède au site après avoir passé le système de sécurité.
Donc je me demande comment tu as fait pour voir la liste des séries.

**Comment by KirinRaikage** [comment]
Mihon Stable 0.16.5, jamais eu d'erreur sur cette source là en tout cas. Peut être un pépin d'user agent, à voir.

**Comment by KirinRaikage** [comment]
Je viens de tester avec un VPN au Maroc (histoire de) je pense que y'a un blocage qui se fait en fonction de ta localisation : j'arrive à reproduire l'erreur. Et en le désactivant (donc retour en France) plus d'erreur et plus de bypass sécurité à faire.  Je te laisse tester ça et fermer l'issue si c'est OK pour toi ?

**Comment by KirinRaikage** [comment]
I think we can close this issue, folks. Investigation has shown that FMTEAM probably is geo-blocking outside of France.

**Comment by Mourad-Saidomar** [comment]
Okay.
Thanks for your help.
