### ISSUE TITLE
Bacakomik

### ISSUE THREAD

**Issue by julptk** [keiyoushi/tachiyomi-extensions-source#2762]
### Source information

Bacakomik 1.4.10

### Source language

Indonesian

### Steps to reproduce

a

### Expected behavior

 b

### Actual behavior

 c

### Mihon/Tachiyomi version

Mihon 0.16.3

### Android version

Android 10

### Other details

![Screenshot_20240502-163913_Komikku (1)](https://github.com/keiyoushi/extensions-source/assets/56266781/8ccde948-b944-4173-b6ef-f33c60e961f4)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by 0Ha16wA5** [comment]
Duplicate of #2396
