### ISSUE TITLE
Better chapter name handling for Manga-TR

### ISSUE THREAD

**Issue by kyoyacchi** [keiyoushi/tachiyomi-extensions-source#2776]
### Source name

Manga-TR

### Source language

Turkish

### Describe your suggested feature

The current chapters are looking like this;
![Screenshot_20240502-205540](https://github.com/keiyoushi/extensions-source/assets/63583961/5737b087-f0a1-4619-b39a-d8b2e162f202)

Can you make it look like others? Like "Bölüm 1", "Bölüm 2" etc... instead of using abbreviation of series name and chapter number.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
On mihon and others, tap the filter button and go to "display -> chapter number", on j2k I believe it's "hide chapter titles" after pressing filters

**Comment by kyoyacchi** [comment]
Ok..
