### ISSUE TITLE
Asura Scans URL Changed

### ISSUE THREAD

**Issue by Aragolt** [keiyoushi/tachiyomi-extensions-source#2778]
### Source information

AsuraScans 1.4.33

### Source language

English

### Source new URL

https://asuracomic.net

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by AshbornXS** [comment]
strange, https://asuratoon.com (the one on the extension) is working just fine

**Comment by Aragolt** [comment]
Interesting, for me that immediately redirects to https://asuracomic.net. The webviews redirect to it as well, though only to the  homepage.

**Comment by KairuDeibisu** [comment]
Same, I'm being redirected to the .net domain as well.

**Comment by StephenLeeY** [comment]
Facing same issue, put a PR to fix: #2790 . Believe that this issue only appears for people who are using the latest version of the Asura extension. Those who are using the old extension from the pre-Tachiyomi to Mihon move do not.

**Comment by Norsze** [comment]
I have the newest version so that is false. The issue is with DNS currently, best wait a day or two for it to stabilize cause Asura always shit itself when they mess with their domain
