### ISSUE TITLE
nhentai

### ISSUE THREAD

**Issue by hmamk** [keiyoushi/tachiyomi-extensions-source#2800]
### Source name

nhentai

### Source link

https://nhentai.net

### Source language

English 

### Other details

+18

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
In addition to the above, make sure you enable: Settings -> Browse -> NSFW (18+) source -> Show in sources and extensions lists
