### ISSUE TITLE
hentaiera

### ISSUE THREAD

**Issue by hmamk** [keiyoushi/tachiyomi-extensions-source#2802]
### Source name

hentaiera

### Source link

https://hentaiera.com

### Source language

English 

### Other details

+18

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by hmamk** [comment]
Where is the problem in adding this excellent site?  @keiyoushi-bot @vetleledaal

**Comment by Smol-Ame** [comment]
> Where is the problem in adding this excellent site? @keiyoushi-bo

It told you in the message, it's a duplicate of another source request.

**Comment by hmamk** [comment]
Does this mean that work will be done to add the site, because he did not give a clear answer  @Smol-Ame

**Comment by Smol-Ame** [comment]
> Does this mean that work will be done to add the site, because he did not give a clear answer  @Smol-Ame

It means someone else has requested it, and it's still open for someone/a contributor to work on. There's no guarantee, just have to wait till someone has the time & is willing to make it.

**Comment by hmamk** [comment]
Thank you for the clarification. This is the first time I have asked to add a site to this. I do not know how things are done, and I am sorry for the inconvenience.  
@Smol-Ame
