### ISSUE TITLE
an error image appears

### ISSUE THREAD

**Issue by denisbrunom** [keiyoushi/tachiyomi-extensions-source#2805]
### Source information

Hunter Scans 1.4.38

### Source language

Portuguese

### Steps to reproduce

I open home
open the manga
When I open the chapter it appears
sss-class gatcha hunter the images do not appear, when I click on open web view the message "ERROR 0004": unable to load the image appears

### Expected behavior

the image open

### Actual behavior

it appears
sss-class gatcha hunter the images do not appear, when I click on open web view the message "ERROR 0004": unable to load the image appears

### Mihon/Tachiyomi version

1.4.38

### Android version

android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
Source's problems,  so nothing to fix

![image](https://github.com/keiyoushi/extensions-source/assets/156493704/8fc135c2-5d8a-4534-93bb-d48243bbe449)
