### ISSUE TITLE
Manga does not load pages [mangadex]

### ISSUE THREAD

**Issue by Schellcunn** [keiyoushi/tachiyomi-extensions-source#2840]
### Source information

Mangadex

### Source language

English

### Steps to reproduce

This manga https://mangadex.org/title/4509fd84-c003-4c57-ab07-e207e6999dab/issho-ni-kurashite-ii-desu-ka starts to return "read at mangadex" image instead of correct pages at page 8 onwards

### Expected behavior

Correct manga pages should be displayed, they are displayed correctly when using webview

### Actual behavior

Wrong image is displayed

### Mihon/Tachiyomi version

App version: 0.16.5

### Android version

14

### Other details

-

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
does it still happen?

**Comment by Schellcunn** [comment]
At least to me, yes. for the newest chapter

**Comment by AwkwardPeak7** [comment]
try clearing chapter cache and try again

**Comment by Schellcunn** [comment]
Tested, doesn't help, cleared chapter cache, cookie and webview data and rebooted mihon, and problem is still happening

**Comment by Schellcunn** [comment]
Tested this without your repo, by calling their api with call result is the same as this bug, should probably be closed as mangadex issue:
`import requests
import os


chapter_id = "9dbb80bc-da29-4ab6-915e-b068667123d3"
base_url = "https://api.mangadex.org"
folder_path = f"[your path]/{chapter_id}"

r = requests.get(f"{base_url}/at-home/server/{chapter_id}")
r_json = r.json()

host = r_json["baseUrl"]
chapter_hash = r_json["chapter"]["hash"]
data = r_json["chapter"]["data"]
data_saver = r_json["chapter"]["dataSaver"]
os.makedirs(folder_path, exist_ok=True)
for page in data:
    r = requests.get(f"{host}/data/{chapter_hash}/{page}")

    with open(f"{folder_path}/{page}", mode="wb") as f:
        f.write(r.content)

print(f"Downloaded {len(data)} pages.")`

**Comment by Norsze** [comment]
Tested the chapter today and it works now.
Can you confirm @Schellcunn ?

**Comment by Schellcunn** [comment]
Tested, seems to work now

**Comment by Norsze** [comment]
Closing this in that case
