### ISSUE TITLE
Manga no Sekai broke again 

### ISSUE THREAD

**Issue by MrDfour** [keiyoushi/tachiyomi-extensions-source#2842]
### Source information

Manga no Sekai 1.4.50

### Source language

Spanish

### Steps to reproduce

Try to update list
Get error ! Expected URL scheme 'http' or 'https' but no scheme was found

### Expected behavior

Successfully retrieve new Manga chapters

### Actual behavior

! Expected URL scheme 'http' or 'https' but no scheme was found

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Other details

![Screenshot_20240504-231537_Material Files](https://github.com/keiyoushi/extensions-source/assets/103494853/045c912b-ee22-43e0-b7df-635b91bfcf1e)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
works fine for me, what series has the issue?

**Comment by MrDfour** [comment]
![Screenshot_20240504-235915_Material Files](https://github.com/keiyoushi/extensions-source/assets/103494853/12088a2e-a141-42cb-a471-9a8c5b862e73)
These ones, particularly. Wierd stuff because webview works now that I check yet trying to update them results in said error
Edit: scratch that. I retried now and they don't give the error anymore. Weird stuff

**Comment by bapeey** [comment]
> Edit: scratch that. I retried now and they don't give the error anymore. Weird stuff

maybe the site was down for a moment, you can check by changing the chapter list page, if it doesn't load, it's a site issue

**Comment by MrDfour** [comment]
> > Edit: scratch that. I retried now and they don't give the error anymore. Weird stuff
> 
> maybe the site was down for a moment, you can check by changing the chapter list page, if it doesn't load, it's a site issue

That was the weird part, I checked the webview and it was fine yet trying to do an update displayed a flair with said error. After opening the issue I didn't checked again because it was supposed to be related to site status since it was never down. It puzzles me but dunno, in case of that error popping up again I'll record a video to better showcase what steps I took to ensure site status, it may be of use if by any means this becomes a thing
