### ISSUE TITLE
Arab manga

### ISSUE THREAD

**Issue by Someoneees** [keiyoushi/tachiyomi-extensions-source#2852]
### Source name

mngaar

### Source link

https://mngaar.com/

### Source language

Arabic

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by mohamedotaku** [comment]
It's a mirror link for mangaae
https://mangaat.com/
https://mangaae.com/
https://mngaar.com/
