### ISSUE TITLE
Shadow Mangas: Source dead

### ISSUE THREAD

**Issue by br14n-sol** [keiyoushi/tachiyomi-extensions-source#2854]
### Source information

Shadow Mangas

### Source language

Spanish

### Steps to reproduce

- Try to update the chapter list of a manga:
Error No chapters

- Try to open a chapter:
Error No pages found

### Expected behavior

Successfully retrieve new Manga chapters and be able to read them.

### Actual behavior

- Error No chapters
- Error No pages found

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

- ![Screenshot_20240505_130051_Mihon](https://github.com/keiyoushi/extensions-source/assets/60621046/c0ccf2ee-4ac1-4726-9863-784443c25129)
- ![Screenshot_20240505_130450_Mihon](https://github.com/keiyoushi/extensions-source/assets/60621046/3e5a83be-8c34-4b53-bb42-014d828f214b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Domain is parked, you should migrate your manga to another extension. Only thing we can do is remove the extension.

**Comment by br14n-sol** [comment]
> Domain is parked, you should migrate your manga to another extension. Only thing we can do is remove the extension.

I don't understand exactly what you mean, to me it loads perfect in the browser 🤔

https://shadowmangas.com/

**Comment by vetleledaal** [comment]
Try flushing your DNS records, it was changed recently. See https://viewdns.info/propagation/?domain=shadowmangas.com 
91.195.240.12 is Sedo Domain Parking
104.21.1.146 & 172.67.129.109 is Cloudflare (where shadowmangas.com is/was available)

**Comment by br14n-sol** [comment]
> Try flushing your DNS records, it was changed recently. See https://viewdns.info/propagation/?domain=shadowmangas.com 91.195.240.12 is Sedo Domain Parking 104.21.1.146 & 172.67.129.109 is Cloudflare (where shadowmangas.com is/was available)

Ohhhh I see, I had to install Chrome, for some reason I couldn't clear the dns cache on brave 😅

Thank you for explaining 🫡

**Comment by bapeey** [comment]
source is up again
