### ISSUE TITLE
Nhentai

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#2865]
### Source information

Nhentai 1.4.40

### Source language

English 

### Steps to reproduce

İ don't know 

### Expected behavior

This extension work

### Actual behavior

This extension doesn't work. İt's not open.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ghost** [comment]
This plugin doesn't work no matter what I do. I tried changing VPN or changing user agent but it never works. Even the cloudflare section does not open when viewing via webview

**Comment by Smol-Ame** [comment]
Works on my end, seems more like a personal internet issue rather than Cloudflare issue. Try switching networks (mobile data to WiFi), adjusting the Mihon Settings > Advanced > DNS over HTTPS, or more attempts with the VPN (to different countries).

**Comment by devil6venom** [comment]
Working fine in me too!

Download warp 1.1.1.1 from playstore and use it. It have dns and vpn inbuilt and work for every sites available! I also use it as my country have banned this site ... but hey, who cares? We r not gonna leave it just because it's banned!! Ahahaha
