### ISSUE TITLE
ZinMangaIO Seems to be down

### ISSUE THREAD

**Issue by MikeZeDev** [keiyoushi/tachiyomi-extensions-source#2875]
### Source name

ZinMangaIO

### Source language

English

### Source link

https://zinmanga.io

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Achuabdu** [comment]
https://zinmanga.net/ seems to be exactly like zinmanga

**Comment by MikeZeDev** [comment]
There are tons of zinmanga, i am not looking for another, i just wanted to tell dev that this one is down :)
