### ISSUE TITLE
HTTP 404

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#2879]
### Source information

Sussy Scan 

### Source language

Português (Brasil)

### Steps to reproduce

Não carrega 

### Expected behavior

.

### Actual behavior

.

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 11 

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #2869

Next time search the issues before making a new issue request, and acknowledging that you did. Also fill in the details instead of leaving it blank for any future issue requests, or it might be rejected due to lack of information.

**Comment by ghost** [comment]
![Screenshot_20240507-015744](https://github.com/keiyoushi/extensions-source/assets/157044539/40ed93bd-c14a-468b-a30f-7ec76909441c)
