### ISSUE TITLE
Ninemangaen not working

### ISSUE THREAD

**Issue by AustinGF27** [keiyoushi/tachiyomi-extensions-source#2880]
### Source information

Ninemangaen 1.4.19

### Source language

English

### Steps to reproduce

1. Go on Ninemangaen extension
2. Open a manga
3. Select any latest chapter

### Expected behavior

It should load the chapter

### Actual behavior

All pages are replaced by a single image uploaded below
![Screenshot_2024-05-07-12-12-54-87_551f7f0ca926862b368845ce7ee433aa](https://github.com/keiyoushi/extensions-source/assets/142663870/0f52dfb4-d905-45b4-aedc-5690ca26e143)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

It has been like this for the past week
![Screenshot_2024-05-07-12-12-54-87_551f7f0ca926862b368845ce7ee433aa](https://github.com/keiyoushi/extensions-source/assets/142663870/f4f7f73b-bf15-4c8b-b77d-9ef89c672c13)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Update your extension and refresh the chapter list
