### ISSUE TITLE
Able to browse Nhentai via WebView, but unable to browse in app

### ISSUE THREAD

**Issue by Acxelion** [keiyoushi/tachiyomi-extensions-source#2882]
### Source information

Nhentai 1.4.40

### Source language

English

### Steps to reproduce

1. Change User String Agent
2. Change _DNS to HTTP_ to either CloudFlare or Google

### Expected behavior

When opening the extension to browse, a library of different works should be visible inside the app without opening WebView.

### Actual behavior

When opening the extension to browse, the app loads and eventually displays a "Failed to bypass CloudFlare" message. However, when opened via the in-app WebView, it's possible to browse the website's contents.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

The user agent string I'm currently using is the one found in this now closed issue(https://github.com/keiyoushi/extensions-source/issues/2311#issuecomment-2050443104)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Acxelion** [comment]
Can this issue be reopened? Because it does not seem like a CloudFlare issue because WebView works, but the in-app browsing cannot.

**Comment by AwkwardPeak7** [comment]
disable random ua from extension settings and try again

**Comment by Acxelion** [comment]
Thank you, that looks to have fixed it.
