### ISSUE TITLE
MangaGezgini Episode

### ISSUE THREAD

**Issue by Rip0000** [keiyoushi/tachiyomi-extensions-source#2889]
### Source information

MangaGezgini 1.4.37

### Source language

turkish

### Steps to reproduce

episode names do not appear and even if I download 1 episode it looks like all episodes have been downloaded, episode names appear in webwiev view
![resim_2024-05-08_190900803](https://github.com/keiyoushi/extensions-source/assets/111808841/d668e55a-a442-4a9d-8bc3-69931b9ac8ad)

### Expected behavior

episode names do not appear and even if I download 1 episode it looks like all episodes have been downloaded, episode names appear in webwiev view

### Actual behavior

episode names do not appear and even if I download 1 episode it looks like all episodes have been downloaded, episode names appear in webwiev view

### Mihon/Tachiyomi version

Tachiyomi 0.15.3

### Android version

android 10

### Other details

Same problem with #2777

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
did you refresh chapter list after updating the extension

**Comment by Rip0000** [comment]
it was fixed after updating the extension and then it was the same again
