### ISSUE TITLE
Cambio de url de Rightdark Scan

### ISSUE THREAD

**Issue by Simpyke** [keiyoushi/tachiyomi-extensions-source#2896]
### Source information

Rightdark Scan 1.4.37

### Source language

Español

### Source new URL

https://dark-scan.com/?fbclid=IwZXh0bgNhZW0CMTAAAR1W5qq5w5kfvOPfwjyGL7OgWA9lHGlCu1tSdBYist70iJDZ0-fVNzuKNos_aem_AfpCukmwIaXpUYnbAYI_4PcSFjhZncZoavaKJ2wg41yIsUjHiV1wAodbrkD3qNDuW6jc9dN0yUZS5SGwr3zhcoqT

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Huh? Under **English**? The source is very clearly Spanish...

**Comment by Smol-Ame** [comment]
Duplicate of closed #2893, check all issue requests before making a new one & acknowledging that you did

A contributor has already made a fix for the issue, please wait for a future extension update

**Comment by Norsze** [comment]
@Simpyke you will find it under **Rightdark Scan** under the **Espanõl** section
