### ISSUE TITLE
Tsuki Mangás: NullPointerException on browse

### ISSUE THREAD

**Issue by GMak9** [keiyoushi/tachiyomi-extensions-source#2897]
### Source information

Tsuki Mangás

### Source language

Brazilian Portuguese

### Steps to reproduce

By clicking 

### Expected behavior

See the latest releases

### Actual behavior

The following screen is appearing: Java.NullPointerException

### Mihon/Tachiyomi version

16.5

### Android version

Android 8.1.0

### Other details

![Screenshot_20240508-234741_TachiyomiJ2K](https://github.com/keiyoushi/extensions-source/assets/6896028/3338473c-7cbb-4a6b-9c28-eda876552f25)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nomaxsnx** [comment]
Pra min está funcionando normalmente.

Seria bom coloca imagens do Error pro desenvolver

**Comment by Carlota-gif** [comment]
Recomendo trocar o User Agent

Usa esse: Mozilla/5.0 (Linux; Android 10; HD1913) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.119 Mobile Safari/537.36 EdgA/122.0.2365.76

**Comment by vetleledaal** [comment]
Can't reproduce the issue. Does the site show in WebView for you? What is your User-Agent?

**Comment by GMak9** [comment]
> Recomendo trocar o User Agent
> 
> Usa esse: Mozilla/5.0 (Linux; Android 10; HD1913) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.119 Mobile Safari/537.36 EdgA/122.0.2365.76

Não parece ser um problema de "user agent", Eu já troquei e o mesmo persiste.

**Comment by GMak9** [comment]
> Can't reproduce the issue. Does the site show in WebView for you? What is your User-Agent?

The error occurs when trying to access the extension, just click on the "recent" for example. In WebView there are no apparent problems.

**Comment by Carlota-gif** [comment]
> > Recomendo trocar o User Agent
> > Usa esse: Mozilla/5.0 (Linux; Android 10; HD1913) AppleWebKit/537.36 (KHTML, como Gecko) Chrome/122.0.6261.119 Mobile Safari/537.36 EdgA/122.0.2365.76
> 
> Não parece ser um problema de "user agent", eu já troquei e o mesmo persiste.

Então eu não sei, o meu tava igual ao seu. Eu mudei o User agent e o DNS para Cloudflare e voltou ao normal. Depois eu desativei o DNS e continuou normal

**Comment by viminio** [comment]
Reinstala a extentão que volta

**Comment by choppeh** [comment]
The issue can be closed. The bug does not occur in the latest versions.
