### ISSUE TITLE
Dynasty Scans gives HTTP 503 Errors when launching a global library update

### ISSUE THREAD

**Issue by trout6516** [keiyoushi/tachiyomi-extensions-source#2899]
### Source information

Dynasty Scans

### Source language

English

### Steps to reproduce

Add any entry from Dynasty Series, Chapters or Anthologies.
Launch a global library update.

### Expected behavior

Update entries should appear and no errors should thrown out. 

### Actual behavior

Gives HTTP 503 errors in the logs. 
![Screenshot_20240509-110134](https://github.com/keiyoushi/extensions-source/assets/125774351/f77eef46-f382-41a3-90d5-e8ddf9656281)

### Mihon/Tachiyomi version

Kuukiyomi Preview R8075

### Android version

Android 14

### Other details

Dynasty recently improved their site and removed some api endpoints. The solution given in their discord was to hard reset the browser or clear the cache. However, clearing cookies, resetting webview data, clearing cache or reinstalling the extension in Kuukiyomi does not change the result. 
VPNs or DNS does not change the result. 
This issue does not affect any other extensions I use. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Aph-ra** [comment]
Commenting here to say I have the exact same error, and ONLY with Dynasty. Never had this with previous readers. I agree with the acknowledgements and have also attempted to clear the cache/cookies/reset webview data; this also happened with a fresh install regardless of doing those steps.
