### ISSUE TITLE
NyoPon

### ISSUE THREAD

**Issue by gabriidev** [keiyoushi/tachiyomi-extensions-source#2907]
### Source name

NyoPon Scan

### Source link

https://www.nyo-pon.com

### Source language

Spanish

### Other details

18+/NSFW = yes 
![IMG_20240428_123018_648](https://github.com/keiyoushi/extensions-source/assets/167422136/49467b9a-ce98-4d1e-b26f-8c3e55d567c9)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by gabriidev** [comment]
It's a test, don't take it seriously, thank you.

**Comment by cuong-tran** [comment]
Isn't it anime site? If it is, go to https://aniyomi.org/
