### ISSUE TITLE
DragonTea chapters won't open

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#2912]
### Source information

DragonTea 1.4.39

### Source language

English

### Steps to reproduce

Open Mihon and open any DragonTea manhua or comic
Click on a chapter to read

### Expected behavior

Open a chapter and start reading the chapter 

### Actual behavior

Open chapter and then get kicked out
Get error message
![Screenshot_20240509_212219](https://github.com/keiyoushi/extensions-source/assets/128992371/43fe6dee-bfd3-4d6b-8648-a6fa8bd3c8d1)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).

**Comment by Jhinnie99** [comment]
I have the same problem it was working 2 days ago 5/8/24 then it stops working yesterday
I have Android 11
![Screenshot_20240510_193301_Tachiyomi](https://github.com/keiyoushi/extensions-source/assets/144994468/29dee94e-39f1-4788-9acf-cd209a02a5e0)
