### ISSUE TITLE
Cloudflare verify Manhuafast

### ISSUE THREAD

**Issue by nightmare199x** [keiyoushi/tachiyomi-extensions-source#2919]
### Source information

Manhuafast

### Source language

English 

### Steps to reproduce

Can you bypass the cloudflare verify everytime i connect to the source?

### Expected behavior

Bypass cloudflare 

### Actual behavior

Cloudflare appear every time access to source.

### Mihon/Tachiyomi version

Newest

### Android version

Ios

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Follow the Cloudflare guide, there's no other way to bypass it: https://keiyoushi.github.io/docs/guides/troubleshooting#cloudflare

Also, if you're on something other than Tachi/Mihon that has the potential of passing Cloudflare (changing user-agents), then contact whoever maintains your application instead.
