### ISSUE TITLE
zinmanga.lat

### ISSUE THREAD

**Issue by Achuabdu** [keiyoushi/tachiyomi-extensions-source#2921]
### Source name

Zinmanga

### Source link

https://zinmanga.lat/manga

### Source language

English

### Other details

![Screenshot_2024-05-10-10-11-16-974_com opera browser afin](https://github.com/keiyoushi/extensions-source/assets/145904014/64d13273-ff2c-4916-bc85-413fd3e40991)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Achuabdu** [comment]
Source is not down

**Comment by Achuabdu** [comment]
![Screenshot_2024-08-26-17-56-40-733_com.android.chrome.jpg](https://github.com/user-attachments/assets/f33271f0-2e2e-4cf8-ba3d-5b6193eb6f75)

> Source is not down

**Comment by vetleledaal** [comment]
Domain is parked.
