### ISSUE TITLE
https://zinmanga.one/

### ISSUE THREAD

**Issue by Achuabdu** [keiyoushi/tachiyomi-extensions-source#2925]
### Source name

Zinmanga. Com

### Source link

https://zinmanga.one/

### Source language

English

### Other details

18+/NSFW=No

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Half the chapters don't work, no thumbnails work. I don't think it's worth adding.
