### ISSUE TITLE
CAMBIO DE URL DE MHSCANS

### ISSUE THREAD

**Issue by hANXITOO** [keiyoushi/tachiyomi-extensions-source#2947]
### Source information

MHScans 1.4.36

### Source language

español

### Source new URL

https://lectormh.com/

### Other details

el scan cambio de url 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
The chapters on the site is broken, changing just the domain in the extension doesn't help. The site also needs to fix it on their side.

**Comment by br14n-sol** [comment]
> The chapters on the site is broken, changing just the domain in the extension doesn't help. The site also needs to fix it on their side.

At least now that I have checked, the chapters load correctly.
