### ISSUE TITLE
[parsing error] mangareader cannot parse volumes

### ISSUE THREAD

**Issue by ig4e** [keiyoushi/tachiyomi-extensions-source#295]
### Source information

MangaReader 1.4.4

### Source language

English

### Steps to reproduce

* Open a manga that only has volumes (Banana fish)
* https://mangareader.to/banana-fish-67
* 
![Screenshot_2024-01-16-12-26-38-589_eu kanade tachiyomi sy](https://github.com/keiyoushi/extensions-source/assets/50212311/55bbe518-5f7b-4767-af00-ffddf30a278c)

You will get no chapters (لا فصول)

While there's clearly volumes (aka chapters)
![Screenshot_2024-01-16-12-27-53-129_eu kanade tachiyomi sy](https://github.com/keiyoushi/extensions-source/assets/50212311/5969d51f-6691-4b27-bf68-bea43873553e)

### Expected behavior

Volumes begin parsed as chapters

### Actual behavior

Volumes doesn't get parsed

### Tachiyomi version

App version: 1.10.1 (standard, c1af389, 61, 2024-01-14T02:17Z)

### Android version

Android 11

### Other details

App version: 1.10.1 (standard, c1af389, 61, 2024-01-14T02:17Z)
Preview build: 0
Android version: 11 (SDK 30; build RP1A.200720.011)
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: begonia (begonia)
Device model: Redmi Note 8 Pro
WebView: Android System WebView 120.0.6099.210

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Enable "Show volume entries in search result" in extension settings.
