### ISSUE TITLE
Happymh won't load

### ISSUE THREAD

**Issue by RadStorm04** [keiyoushi/tachiyomi-extensions-source#2951]
### Source information

Happymh 1.4.10

### Source language

Chinese

### Steps to reproduce

1.Go into source webview attempting cloudflare check yet no prompt was shown and the web page loads normally
2. Click on comic chapter, won't load

### Expected behavior

Loading normally

### Actual behavior

While attempting to read from app, couldn't load then shows "couldn't bypass cloudflare" message bubble

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 14

### Other details

I was using this user agent for quite a while without issues up until now

Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 QIHU 360ENT

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by NeKoOuO** [comment]
Change your User Agent 

Here's my

Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 QIHU 360ENT

**Comment by vetleledaal** [comment]
Duplicate of #2346?

**Comment by alan0507** [comment]
> Change your User Agent 
> 
> Here's my
> 
> Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 QIHU 360ENT

It seems that is not user agent problem , l use same user agent,usually when I open comic in webview,it will show cloudflare,but today it skip cloudflare verification

**Comment by salamander7456** [comment]
> > 更改您的用戶代理
> > 這是我的
> > Mozilla/5.0（Windows NT 10.0；WOW64）AppleWebKit/537.36（KHTML，如 Gecko）Chrome/86.0.4240.198 Safari/537.36 QIHU 360ENT
> 
> 看來不是用戶代理問題，我使用相同的用戶代理，通常當我在webview中打開漫畫時，它會顯示cloudflare，但今天它跳過cloudflare驗證

I also use this user agent. In the previous time, it is okay. But recently it is also do not work. And my problem is the same as yours. The WebView is working, but Mihon says it can't bypass cloud flare so that I can't download manga or read them on Mihon.

**Comment by Norsze** [comment]
You guys should probably look for user agents from browsers used a lot in your regions. Just a guess though

**Comment by sha-mao** [comment]
https://github.com/keiyoushi/extensions-source/assets/124576212/485649a4-6b16-42de-b528-c881ad5197fd

现在的情况

**Comment by Kxdiong** [comment]
It seems that the manga chapter links are incorrectly directed to Cloudflare
![IMG_20240511_192515](https://github.com/keiyoushi/extensions-source/assets/103210868/aa98dbff-7cda-4e40-98fd-6b3686afcf41)
I also tried to open in webview, and it displayed normally. However, the links in the chapters within the app still direct to Cloudflare as shown in the image

**Comment by Norsze** [comment]
I don't know guys, I set a different user agent and i reached the site in-app after passing cloudflare in webview.

![Screenshot_20240511_142101_Mihon.jpg](https://github.com/keiyoushi/extensions-source/assets/66540317/817f532d-39d6-4c28-b387-e7a0002d4e42)

![Screenshot_20240511_142211_Mihon.jpg](https://github.com/keiyoushi/extensions-source/assets/66540317/8723a0bf-08ac-4c4b-8fbd-021f7d022a23)

**Comment by Kxdiong** [comment]
> I don't know guys, I set a different user agent and i reached the site in-app after passing cloudflare in webview.

could u let me know which version of Happymh youre using? 1.4.10 ？

**Comment by shaunzzzz** [comment]
> I don't know guys, I set a different user agent and i reached the site in-app after passing cloudflare in webview.
> 
> 

Can you share your user string?

**Comment by Norsze** [comment]
> could u let me know which version of Happymh youre using? 1.4.10 ？

Yes 1.4.10

> Can you share your user string?

I prefer not to, since it has worked for me for a while, but there are multiple other user agents that work out there

**Comment by Kxdiong** [comment]
I think I ve found the reason.
the two links below are for the same manga, but one is the chapter link clicked inthe webview, and the other is the chapter link in the app.
It seems that happymh site has made some adjustments , which may have caused this issue.
### Webview
https://m.happymh.com/reads/wotianmingdafanpai/4365507
### App
https://m.happymh.com/v2.0/apis/manga/read?code=wotianmingdafanpai&cid=4365507&v=v2.13

**Comment by raine93** [comment]
Same issue here. Also using the same user agent. Hope there's a fix on this

**Comment by salamander7456** [comment]
yes，happymh always has this problem. When I don't use this user agent, I discovered that app and webview use two different links on happymh, the former one is not work. After I change the user agent, app is work so I don't pay attention to the link in app is changed or not. I really don't know why it's calling the API, the other resources don't.

**Comment by BabyNurse020517** [comment]
so for now we need to change user string or waiting for fix ?

**Comment by salamander7456** [comment]
I prefer not to change user agent. I used a lot of user agents, but they cannot solve the problem even some make it worse. Now I just continue focus on this issus web and read manga on other resources or WebView of happymh.

**Comment by BabyNurse020517** [comment]
any recommended source to replace happymh ?

**Comment by Norsze** [comment]
Know that recommending sources is not allowed on this GitHub or in the Discord

**Comment by salamander7456** [comment]
Maybe Manwa ,Baozi and Cocomamga are good choices, but there are some manga cannot find on other Chinese resources without happymh, that makes happymh Irreplaceable if we want to read some certain manga.

**Comment by junyaotan020517** [comment]
i am using cocmanga as well but cocmanga load so slow

**Comment by Norsze** [comment]
You guys I told you that it was not allowed, now we wait for someone to delete your comments and lock this, congrats

Also duplicate as Vetle said

**Comment by salamander7456** [comment]
it is, but better than no
