### ISSUE TITLE
Mangago will not update

### ISSUE THREAD

**Issue by LadyHaywood** [keiyoushi/tachiyomi-extensions-source#2952]
### Source information

1.4.13

### Source language

English

### Steps to reproduce

Go to Browes
Click on Extensions
Click to update Mangago

### Expected behavior

A successful install of the latest mangago extension

### Actual behavior

Just won't update

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Other details

I've tried using different forks of tachiyomi/mihon since I only use J2K and wanted to make sure it wasn't a them problem. I've also had a problem where it just wouldn't open but I've only got that to happen twice and haven't been able to reproduce that. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
possible duplicate https://github.com/keiyoushi/extensions-source/issues/2548

**Comment by vetleledaal** [comment]
Sounds like you're describing the issue in https://github.com/keiyoushi/extensions-source/issues/109#issuecomment-1894636873. It's one of the pinned issues.
