### ISSUE TITLE
NovelCool not showing pages on some mangas

### ISSUE THREAD

**Issue by camisama0907** [keiyoushi/tachiyomi-extensions-source#2957]
### Source information

NovelCool 1.4.3

### Source language

Spanish

### Steps to reproduce

1: Search ongoing manga
2: Select a manga
3: open chapter

### Expected behavior

Chapter is view as normal

### Actual behavior

With some mangas (nothing in common that i can find between them) the next image is shown instead of each page:

![novelcoolesproblm](https://github.com/keiyoushi/extensions-source/assets/156140767/8bd50013-3e31-4792-80b5-df66a4a713c8)

### Mihon/Tachiyomi version

TachiyomiJ2K 1.7.4

### Android version

Android 12

### Other details

This have happened for a while already, but as i said, it's hard to actually identify which mangas trigger this behavior.

The latest one that i've noticed is "_[La Presidenta Y La Chica M De Los Lirios.](https://es.novelcool.com/novel/La-Presidenta-Y-La-Chica-M-De-Los-Lirios.html)_" and checked with "_[La Historia Del Inesperado Encuentro Entre Una Chica Gal Y La Presidenta Del Consejo Estudiantil](https://es.novelcool.com/novel/La-Historia-Del-Inesperado-Encuentro-Entre-Una-Chica-Gal-Y-La-Presidenta-Del-Consejo-Estudiantil.html)_" but it happens with other titles as well

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
all the ones you mentioned are working as expected. when this happens make sure to check the chapter in webview since they could have the images like that there
