### ISSUE TITLE
mm-scans.org Seems to be Gone

### ISSUE THREAD

**Issue by CardinalBirb** [keiyoushi/tachiyomi-extensions-source#296]
### Source name

MMScans

### Source language

English

### Source link

https://mm-scans.org

### Other details

https://www.reddit.com/r/manhwa/comments/190b48k/mmscans_does_anyone_know_what_happened_to_them/

temporarily down maybe?

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
It is temporary it seems:
![image](https://github.com/keiyoushi/extensions-source/assets/66540317/a2990f36-acd0-43bd-ad59-1f336c79fede)

Pulled from their discord
