### ISSUE TITLE
肉漫屋无法打开

### ISSUE THREAD

**Issue by sha-mao** [keiyoushi/tachiyomi-extensions-source#2961]
### Source information

Roumanwu 1.4.8

### Source language

中文

### Steps to reproduce

直接打开观看

### Expected behavior

正常打开

### Actual behavior

打开时提示：服务器错误401

### Mihon/Tachiyomi version

tachiyomiSY stable 1.10.5

### Android version

澎湃OS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by NeKoOuO** [comment]
#2983
