### ISSUE TITLE
Nettruyen change URL

### ISSUE THREAD

**Issue by MakatoKishei** [keiyoushi/tachiyomi-extensions-source#2962]
### Source information

NetTruyen 1.4.35

### Source language

Vietnamese 

### Source new URL

https://nettruyencc.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Please see the conversation in #2887, if you have any additional information about this source & the validity of the source URL, please mention in there

**Comment by MakatoKishei** [comment]
> Please see the conversation in #2887, if you have any additional information about this source & the validity of the source URL, please mention in there

I would like to confirm that this is the current URL of NetTruyen, it may not be changed within a few weeks, so I hope you can update the URL again, sorry for doing it. sorry guys

**Comment by Karutovn** [comment]
> > Please see the conversation in #2887, if you have any additional information about this source & the validity of the source URL, please mention in there
> 
> I would like to confirm that this is the current URL of NetTruyen, it may not be changed within a few weeks, so I hope you can update the URL again, sorry for doing it. sorry guys

**English** : you can use unoriginal nettruyen (it's on the source)
**Vietnamese**: Bro có thể dùng source unoriginal nhé (btw admin nettruyen như kiểu đem con bỏ chợ ý) nhà dịch cx chỉ có 1 thông báo th

**Comment by vetleledaal** [comment]
`nettruyencc.com` is not the same as the current extension. Open a feature request to override the baseUrl as a setting or make a source request for this site.

**Comment by MakatoKishei** [comment]
> > > Please see the conversation in #2887, if you have any additional information about this source & the validity of the source URL, please mention in there
> > 
> > 
> > I would like to confirm that this is the current URL of NetTruyen, it may not be changed within a few weeks, so I hope you can update the URL again, sorry for doing it. sorry guys
> 
> **English** : you can use unoriginal nettruyen (it's on the source) **Vietnamese**: Bro có thể dùng source unoriginal nhé (btw admin nettruyen như kiểu đem con bỏ chợ ý) nhà dịch cx chỉ có 1 thông báo th

**English:** I've installed the unoriginal source but still can't access it, but all I know is that nettruyen has just been through two generations of owners, the official revival date is unknown. Probably in about a month it will be stable again, Net Truyen is like phimmoi, it can't die
**Vietnamese:** Đã cài source unoriginal rồi nhưng mà vẫn không vào được, nhưng mà chỉ biết là giờ nettruyen mới qua 2 đời chủ thôi, ngày hồi sinh chính thức thì chưa rõ. Chắc tầm 1 tháng nữa thì sẽ về ổn định lại, NetTruyen như phimmoi ấy mà, không chết nổi được
![Uploading image.png…]()

**Comment by Karutovn** [comment]
> > > > Please see the conversation in #2887, if you have any additional information about this source & the validity of the source URL, please mention in there
> > > 
> > > 
> > > I would like to confirm that this is the current URL of NetTruyen, it may not be changed within a few weeks, so I hope you can update the URL again, sorry for doing it. sorry guys
> > 
> > **English** : you can use unoriginal nettruyen (it's on the source) **Vietnamese**: Bro có thể dùng source unoriginal nhé (btw admin nettruyen như kiểu đem con bỏ chợ ý) nhà dịch cx chỉ có 1 thông báo th
> 
> **English:** I've installed the unoriginal source but still can't access it, but all I know is that nettruyen has just been through two generations of owners, the official revival date is unknown. Probably in about a month it will be stable again, Net Truyen is like phimmoi, it can't die
> **Vietnamese:** Đã cài source unoriginal rồi nhưng mà vẫn không vào được, nhưng mà chỉ biết là giờ nettruyen mới qua 2 đời chủ thôi, ngày hồi sinh chính thức thì chưa rõ. Chắc tầm 1 tháng nữa thì sẽ về ổn định lại, NetTruyen như phimmoi ấy mà, không chết nổi được
> ![Uploading image.png…]()
> 

**English**: Nettruyenco extension just work fine, so you can use this, and for now nettruyen don't have anything activities to translator and user for now (I think a part ò reason from Japanese television)
**Vietnamese**: em thấy nettruyenco dùng oke á (nettruyen bế quan lâu lắm r mà chx thấy động tĩnh gì chắc là bo bị bế pên đài bebe nhật ý mà)
