### ISSUE TITLE
Lura Toon: Access Denied with Cloudflare

### ISSUE THREAD

**Issue by kyhapi** [keiyoushi/tachiyomi-extensions-source#2965]
### Source information

Lura Toon 1.4.44

### Source language

Português ( Brasil )

### Steps to reproduce

1. access Lura Toon
2. Failed to bypass cloudflare
When accessing the WebView, a page appears informing that cloudflare has blocked access
![Screenshot_20240511-080528](https://github.com/keiyoushi/extensions-source/assets/147045416/f32b9f31-e6fe-47b9-887c-6023e91f8f45)
![Screenshot_20240511-080002](https://github.com/keiyoushi/extensions-source/assets/147045416/020e3578-2a71-416a-ba9e-2fb6986ccf27)

### Expected behavior

The manga was supposed to appear

### Actual behavior

the message "Failed to bypass cloudflare" appears

### Mihon/Tachiyomi version

Beta r6674

### Android version

Android 13

### Other details

I noticed that they blocked access even when using one browsers

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kyhapi** [comment]
the cloudflare troubleshoot section does not show how to resolve this issue

**Comment by Norsze** [comment]
Huh? I can see and view it in the app

![Screenshot_20240511_141606_Mihon.jpg](https://github.com/keiyoushi/extensions-source/assets/66540317/2f4bc152-5fdc-47f1-814c-70b197bebef0)

![Screenshot_20240511_141626_Mihon.jpg](https://github.com/keiyoushi/extensions-source/assets/66540317/5fd40d94-46e7-42f6-9f67-ba9514dda430)

![Screenshot_20240511_141653_Mihon.jpg](https://github.com/keiyoushi/extensions-source/assets/66540317/2bebe425-f76b-49da-9eaf-61d57f4846e9)

**Comment by choppeh** [comment]
I changed the user agent to mobile and this was fixed for me. PR #2967 

Maybe it's not enough

**Comment by kyhapi** [comment]
> Huh? Posso ver e visualizar no aplicativo
> 
> ![Captura de tela_20240511_141606_Mihon.jpg](https://private-user-images.githubusercontent.com/66540317/329780497-2f4bc152-5fdc-47f1-814c-70b197bebef0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzY2NTAsIm5iZiI6MTcxNTQzNjM1MCwicGF0aCI6Ii82NjU0MDMxNy8zMjk3ODA0OTctMmY0YmMxNTItNWZkYy00N2YxLTgxNGMtNzBiMTk3YmViZWYwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDE0MDU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ODZkN2NmMDhmMjU1ZjZhMDI3ZDAyMDNjYTE1MGI2NWZmMmM5NTA2ZDNlMjU3ODc5YjI1NzM0NjUwYTI3N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5ypWKG-DpKaWYROlMgBjTSV8lTUPRLtcR_KPcSxQ-Qw)
> 
> ![Captura de tela_20240511_141626_Mihon.jpg](https://private-user-images.githubusercontent.com/66540317/329780505-5fd40d94-46e7-42f6-9f67-ba9514dda430.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzY2NTAsIm5iZiI6MTcxNTQzNjM1MCwicGF0aCI6Ii82NjU0MDMxNy8zMjk3ODA1MDUtNWZkNDBkOTQtNDZlNy00MmY2LTlmNjctYmE5NTE0ZGRhNDMwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDE0MDU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4YWY3OTcyYzYyYzkwMTFlNDMyNjlhNjQ4MmJkMjRjNWJiZWNhOGRiOThjMDQ0Yzg5MTRlNDFkZTIwMzQyM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VHOI3QANX4q0_DSqJcQz6SofcrOZ6qWn7x1g8xwnjSo)
> 
> ![Captura de tela_20240511_141653_Mihon.jpg](https://private-user-images.githubusercontent.com/66540317/329780507-2bebe425-f76b-49da-9eaf-61d57f4846e9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzY2NTAsIm5iZiI6MTcxNTQzNjM1MCwicGF0aCI6Ii82NjU0MDMxNy8zMjk3ODA1MDctMmJlYmU0MjUtZjc2Yi00OWRhLTllYWYtNjFkNTdmNDg0NmU5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDE0MDU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NmExMGIxNDgzNWI0Nzk4YzBiYWRmZmM4OTFkZWUzZDQ5ZTE1OTAzZGU2NDdkODZlZmY5YWEzOWRmNzUwNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O8m57L5sUHMa2bY-ANWlhnszgz-KTWNTThxNodivk2w)

unfortunately it's blocked here, last week there was also another user talking about this problem on #2705 

https://github.com/keiyoushi/extensions-source/assets/147045416/9b3e574b-2638-47ae-b3f2-080a480ce286
