### ISSUE TITLE
Drake Scans: Broken images in new chapters

### ISSUE THREAD

**Issue by JIINNN01** [keiyoushi/tachiyomi-extensions-source#2968]
### Source information

Drake Scans 1.4.41

### Source language

English

### Steps to reproduce

1. Open Drake Scans in Mihon.
2. Go to the Latest tab.
3. Open the most recent CH they released.

### Expected behavior

The chapter should load properly.

### Actual behavior

The chapter has bunch of broken images mixed with some working images. 

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Other details

When attempting to download the chapter, it throws an HTTP error 429. This issue seems to occur only with recently released chapters. After some time, they start loading properly again. For instance, some chapters that I encountered issues with hours ago are now loading fine. However, the latest CH site released displays broken images, while it works perfectly on the browser. I'll provide some screenshots below. By the time you look into it, the specific title's CH may be loading fine. I suggest checking the most recent chapter they've released.
![Screenshot_20240511-182325-175](https://github.com/keiyoushi/extensions-source/assets/164266304/b43e96fd-1dbf-4194-9d4b-bb76f942fce9)
![Screenshot_20240511-182329](https://github.com/keiyoushi/extensions-source/assets/164266304/b44e6bbc-e4fa-4fc7-aaea-c335527eaaf3)
![Screenshot_20240511-182342-756](https://github.com/keiyoushi/extensions-source/assets/164266304/2781839f-14ec-4f7f-89bd-2266ba962a02)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by sovit042** [comment]
Yeah I just came to report this its happening to each and every latest chapter plz fix it

**Comment by Anurag69** [comment]
Yeah same happening with for 10000 years manhwa from this site. I think the site owners are putting it knowingly to break the flow for app readers just like asura scans did previously

**Comment by Norsze** [comment]
/edit-title "Drake Scans: Broken images in new chapters"
