### ISSUE TITLE
some of the doujin or manga in that extension can't read or download 

### ISSUE THREAD

**Issue by amirulfaiz98** [keiyoushi/tachiyomi-extensions-source#2970]
### Source information

HentaiRead 1.4.40

### Source language

English

### Steps to reproduce

1. Select any latest doujin or manga
2. Click on chapter or download

### Expected behavior

1. Shows the chapter or download it

### Actual behavior

1. No pages found or not downloaded

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Duplicate of #2902
