### ISSUE TITLE
App crashes, wen searching with DigitalComicMuseum installed

### ISSUE THREAD

**Issue by gothsome** [keiyoushi/tachiyomi-extensions-source#2972]
### Source information

DigitalComicMuseum

### Source language

English 

### Steps to reproduce

I can searching in the pinned repo, but when i switch to all the App chrashes

### Expected behavior

No crash 

### Actual behavior

App crashes

### Mihon/Tachiyomi version

Beta R6647

### Android version

13

### Other details

App version: 0.16.5-6674 (standard, https://github.com/mihonapp/mihon/commit/dbcc4a7d714cf36b48a41d6074ef671f3c039823, 7, 2024-05-04T21:34:28Z)
Android version: 13 (SDK 33; build TKQ1.221013.002 test-keys)
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: nabu (nabu_eea)
Device model: 21051182G
WebView: Android System WebView 124.0.6367.123

java.lang.Throwable: java.lang.NoSuchMethodError: No direct method (Ljava/lang/String;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lokhttp3/MultipartBody$Builder; or its super classes (declaration of 'okhttp3.MultipartBody$Builder' appears in base.apk!classes3.dex)
at eu.kanade.tachiyomi.extension.en.digitalcomicmuseum.DigitalComicMuseum.searchMangaRequest(DigitalComicMuseum.kt:72)
at eu.kanade.tachiyomi.source.online.HttpSource$$ExternalSyntheticLambda5.call(Unknown Source:27)
at rx.internal.operators.OnSubscribeDefer.call(SourceFile:2)
at rx.internal.operators.OnSubscribeDefer.call(SourceFile:1)
at rx.Observable.unsafeSubscribe(Unknown Source:9)
at rx.internal.operators.OnSubscribeMap.call(SourceFile:4)
at rx.internal.operators.OnSubscribeMap.call(SourceFile:1)
at rx.internal.operators.OnSubscribeLift.call(SourceFile:4)
at rx.internal.operators.OnSubscribeLift.call(SourceFile:1)
at rx.Observable.subscribe(SourceFile:24)
at tachiyomi.core.common.util.lang.RxCoroutineBridgeKt.awaitSingle(Unknown Source:27)
at eu.kanade.tachiyomi.source.online.HttpSource.getSearchManga(Unknown Source:4)
at eu.kanade.tachiyomi.ui.browse.source.globalsearch.SearchScreenModel$search$3$1$1$page$1.invokeSuspend(Unknown Source:34)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
at kotlinx.coroutines.DispatchedTask.run(Unknown Source:110)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
at java.lang.Thread.run(Thread.java:1012)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(Screen#691dc89e-b45b-491a-b3a8-1477f83eb89e:eu.kanade.tachiyomi.ui.browse.source.globalsearch.GlobalSearchScreenModel:default), StandaloneCoroutine{Cancelling}@762db04, Dispatchers.IO]

--------- beginning of system
05-10 14:20:14.075 27703 27703 E MiuiMultiWindowUtils: initFreeFormResolutionArgs failed, device is nabu
05-10 14:20:37.747 27711 27711 E MiuiMultiWindowUtils: initFreeFormResolutionArgs failed, device is nabu
--------- beginning of main
05-10 15:39:08.884 27711 27711 E FileUtils: err write to mi_exception_log
05-10 15:39:09.047 27711 27711 E FileUtils: err write to mi_exception_log
05-10 15:39:09.087 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.119 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.160 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.178 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.193 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.201 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.209 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.221 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.229 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.235 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.244 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.253 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.261 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.269 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.276 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.287 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.293 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.303 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.310 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.320 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.328 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.335 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.345 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.354 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.361 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.369 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.379 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.387 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.393 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:11.577 27711 27711 E FileUtils: err write to mi_exception_log
05-10 15:39:11.668 27711 27711 E FileUtils: err write to mi_exception_log
05-10 15:39:11.692 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Known issue, please disable or uninstall that extension for now until either an extension update or an app update

**Comment by Norsze** [comment]
This is known and limited to the Beta of that app, and there is already a fix that has been merged, will be in the next beta release

**Comment by gothsome** [comment]
> This is known and limited to the Beta of that app, and there is already a fix that has been merged, will be in the next beta release

Tank you!

**Comment by AwkwardPeak7** [comment]
already fixed in beta r6685
