### ISSUE TITLE
Volumes from MangaFire

### ISSUE THREAD

**Issue by AbdelrahmanElnezamy121** [keiyoushi/tachiyomi-extensions-source#2974]
### Source name

MangaFire

### Source language

English

### Describe your suggested feature

Add the feature to show and download [Volumes] of any manga from MangaFire

### Other details

![Untitled](https://github.com/keiyoushi/extensions-source/assets/156478893/07b78edb-5686-4c3d-be11-5cababe77ded)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #2520

Just in case, if & when that issue gets a fix, remember to go to your Mangafire extension settings, and enable the setting for volumes. Again, do it whenever it gets a fix for that issue
