### ISSUE TITLE
Ad gif between every images Starbound scans

### ISSUE THREAD

**Issue by Plaanteverte** [keiyoushi/tachiyomi-extensions-source#2975]
### Source name

Starbound scans

### Source language

French

### Describe your suggested feature

Between every image of a chapter there is an annoying gif added that say « read next chapter only at kewnscans.org », it shouldn’t be there.
![IMG_2125](https://github.com/keiyoushi/extensions-source/assets/169561266/7dc82df3-3308-49b0-b122-96324a1d8733)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
closing in favour of #2976
