### ISSUE TITLE
Cypher Scans Download Problem 

### ISSUE THREAD

**Issue by sovit042** [keiyoushi/tachiyomi-extensions-source#298]
### Source information

Cypher Scans 1.4.27

### Source language

English

### Steps to reproduce

1. Open the Cypher scans extension 
2. Open any series
3. Download any chapter

### Expected behavior

After starting a download it should download normally just like how it happens with other extensions

### Actual behavior

You will notice it takes house to download a chapter and at the end download fails showing no network connection available.

![Screenshot_2024-01-16-17-38-32-090_eu kanade tachiyomi](https://github.com/keiyoushi/extensions-source/assets/101596014/5bad31ce-2167-4a4e-ac0c-f05f92adbb09)

### Tachiyomi version

0.15.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by sovit042** [comment]
Its been 3 days but no one to help 🙂

**Comment by sovit042** [comment]
I colsed it as there was no response for sk many days and opend a new one no #357

**Comment by SnakeDoc83** [comment]
Can't reproduce. If they're still in your download queue cancel them and try again.

**Comment by sovit042** [comment]
I tried everything like cache , useragent and other and on ur very first download it may have worked fine try downloading 2-3 chapter and here even the discord mods are suffering this problem
![IMG_20240119_121811](https://github.com/keiyoushi/extensions-source/assets/101596014/b75d09c9-e8a5-491b-9126-f8ef5bfd90f7)

**Comment by SnakeDoc83** [comment]
Website shows they're changing web hosting now. You'll have to wait and see if they're any better once they're back up.
