### ISSUE TITLE
Tapas not working

### ISSUE THREAD

**Issue by euijoonyeo** [keiyoushi/tachiyomi-extensions-source#2985]
### Source information

Tapas 1.4.20

### Source language

English

### Steps to reproduce

When I enter tapas extension it shows that there is no result but in webview it work fine 
![Screenshot_20240512_161634_TachiyomiJ2K](https://github.com/keiyoushi/extensions-source/assets/101834402/150d24e8-d8ad-488e-a541-deba9d6cc61f)

### Expected behavior

. 

### Actual behavior

.

### Mihon/Tachiyomi version

Tachiyomi 0.15.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #2450

Search the existing issues first before you open a new one, and acknowledge that you did
