### ISSUE TITLE
Mangahub: failed to open pages

### ISSUE THREAD

**Issue by hellariusobi** [keiyoushi/tachiyomi-extensions-source#299]
### Source information

Mangahub 1.4.32

### Source language

English

### Steps to reproduce

1. Open Mangahub extension
2. Open any series
3. Open any chapter

### Expected behavior

after opening a chapter it should appear the chapter page. 

### Actual behavior

The chapter won't open and a message appears "hostname api.mghubcbdn.com not verified"

### Tachiyomi version

Mihon 0.16.0

### Android version

Android 12

### Other details

![IMG_20240116_201342](https://github.com/keiyoushi/extensions-source/assets/95006149/582a12d4-41e9-4a58-b8a1-8e5cf27fd93b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by muhmuhhum** [comment]
the url has changed and is now mghcdn.com if this helps for faster fix i cant fix it myself at the moment cause i dont have time
