### ISSUE TITLE
RoliaScan

### ISSUE THREAD

**Issue by Fuzzythegoatq** [keiyoushi/tachiyomi-extensions-source#2994]
### Source name

Roliascan

### Source link

https://roliascan.com/

### Source language

English

### Other details

Read your favorite manhwa, manhua, comics with highest quality. the girl from a random chatting, huashan sect greatest genius, my crazy boss....

(I personally use this for Questim release fast asf)
18+ No

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Stop opening new requests for this, you already have this one open.

All the work is done by contributors volunteering their time, and there's no guarantee. Just be patient or use another source.
