### ISSUE TITLE
3600000 Beauty (gravure)

### ISSUE THREAD

**Issue by 0Ha16wA5** [keiyoushi/tachiyomi-extensions-source#2997]
### Source name

3600000 Beauty

### Source link

https://3600000.xyz/

### Source language

All

### Other details

18+/NSFW = yes

Gravure photography site with Japanese and Chinese models.

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by fqrious** [comment]
Can you provide app icons? The site uses a generic wordpress icon, I used [this](https://github.com/fqrious/extensions-source/blob/3600000.xyz/src/all/beauty3600000/res/mipmap-xxxhdpi/ic_launcher.png) in my code

**Comment by 0Ha16wA5** [comment]
I don't have one neither, but I believe using the default color scheme (#ffffff background, #FF4F4F text) will be easier for visibility. @fqrious 

Thank you for your code commit, anyway.
