### ISSUE TITLE
Upstream extensions

### ISSUE THREAD

**Issue by isavl** [keiyoushi/tachiyomi-extensions-source#3]
### Describe why this should be added

Hi.

Why upstream close extensions repository with description - Extensions are no longer available out-of-the-box?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by TehNut** [comment]
https://tachiyomi.org/news/2024-01-09-extensions-removal

**Comment by isavl** [comment]
Sorry but i little misunderstand. What alternative to removed extensions? Setup local custom tachidesk/lanraragi/komga/kavita server and write (reimplement what lose tachiyomi) for them plugins for grabbing manga?

**Comment by Norsze** [comment]
I don't know if I understand you, this is the alternative. You are literally in the repository. Everything is here.

**Comment by isavl** [comment]
Ahhh, legal troubles, classic  https://www.reddit.com/r/Tachiyomi/comments/18zh6gg/january_2024_jinxed_it/  :(
