### ISSUE TITLE
MangaGeko latest titles not scrolling continuously

### ISSUE THREAD

**Issue by Shanmukha-ds** [keiyoushi/tachiyomi-extensions-source#3000]
### Source information

MangaGeko 1.4.21

### Source language

English

### Steps to reproduce

1. Open the latest released chapters in MangaGeko
2. Scroll down

### Expected behavior

It should scroll continuously

### Actual behavior

It is stopping after loading a certain number of titles. and if a title is updated recently it will kick the last chapter out of the loaded titles

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

the URL for latest releases has changed. It has `&filter=New` added at the end

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by NidPlays** [comment]
Seems to be working now.
