### ISSUE TITLE
NicoManga : NullPointerExeption: null

### ISSUE THREAD

**Issue by DchanN** [keiyoushi/tachiyomi-extensions-source#301]
### Source information

NicoManga 1.4.2

### Source language

Japanese - 日本語

### Steps to reproduce

Browse -> NicoManga -> Browse/latest 

### Expected behavior

Show manga catalog

### Actual behavior

Show NullPointerExeption: null

### Tachiyomi version

Mihon r6442

### Android version

Android 10

### Other details

https://github.com/keiyoushi/extensions-source/assets/101858971/8cb05d9b-82af-4a40-a9c3-69807556925e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
NOTE: This source seems to be using the FMReader theme.
