### ISSUE TITLE
Kitsune manga

### ISSUE THREAD

**Issue by Azouar2418** [keiyoushi/tachiyomi-extensions-source#3012]
### Source name

Kitsune manga

### Source link

https://kmanga.c1.is/public/

### Source language

Arabic

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
uses FuzzyDoodle theme

**Comment by vetleledaal** [comment]
Domain appears to not be registered. Closing.
