### ISSUE TITLE
Demon Sect Auto Login

### ISSUE THREAD

**Issue by AshbornXS** [keiyoushi/tachiyomi-extensions-source#3017]
### Source name

Demon Sect

### Source language

Brazilian Portuguese

### Describe your suggested feature

They recently changed the website to work only if logged in, so would be cool to have options on the extension settings to set the account automatically, because if logged on webview after some time it gets disconnected, some older extensions had that option so I don't think it's unreasonable, but if it is thanks anyways

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
You need to check the “Keep me signed in” box
