### ISSUE TITLE
Repo

### ISSUE THREAD

**Issue by Xinnnnnmm** [keiyoushi/tachiyomi-extensions-source#3018]
### Source information

124.0

### Source language

Indonesia

### Steps to reproduce

![eu kanade tachiyomi extension id westmanga](https://github.com/keiyoushi/extensions-source/assets/169820287/92671441-cf5b-4312-9592-f8666a8f47ff)

### Expected behavior

Dibenarkan

### Actual behavior

Dibenarkan

### Mihon/Tachiyomi version

1.7.4

### Android version

Android 11

### Other details

Dibenarkan

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
I don't get it what exactly are you reporting?
