### ISSUE TITLE
Immortal updates address change 

### ISSUE THREAD

**Issue by sofari23** [keiyoushi/tachiyomi-extensions-source#3021]
### Source information

Immortal updates 1.4.42

### Source language

English 

### Steps to reproduce

1. Open mihon and go to browse
2. Select immortal updates 
3. Press lates

### Expected behavior

It should load the list of manhwa available 

### Actual behavior

It doesn't load just says check website in browser 

### Mihon/Tachiyomi version

0.16.5-6685 

### Android version

Android 14

### Other details

![Screenshot_2024-05-14-21-17-25-799_app mihon debug](https://github.com/keiyoushi/extensions-source/assets/152812391/f23e541d-2975-4d80-8568-bca58863f7f0)
![Uploading Screenshot_2024-05-14-21-17-18-765_org.adblockplus.browser.jpg…]()

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Apparently, the domain redirect is temporary, check their Discord server for any future updates about this.

As for now, install & migrate any Immortal titles to the **Mortals Groove** source

![Screenshot_20240514_114145.jpg](https://github.com/keiyoushi/extensions-source/assets/155411819/b0d99049-33a0-456d-bf58-039d4e2178e2)

Maybe leave open to redirect future mentions of this issue/domain swap until they finish maintenance

**Comment by ManiV97** [comment]
Mortal groove is added as a new extension. 
Search and add the extension.

**Comment by sofari23** [comment]
Thank you

**Comment by JIINNN01** [comment]
> Thank you 

Close the issue
