### ISSUE TITLE
Tres daos scan don't load content 

### ISSUE THREAD

**Issue by Kratos43R** [keiyoushi/tachiyomi-extensions-source#3026]
### Source information

Tres daos scan 1.4.36

### Source language

Spanish 

### Steps to reproduce

The content don't load in the app but webview is working

### Expected behavior

.

### Actual behavior

.

### Mihon/Tachiyomi version

0.16.5-6685

### Android version

Android 12

### Other details

I hope you can solve it. Greetings !

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
?duplicate #3027
