### ISSUE TITLE
Prazeres Violentos

### ISSUE THREAD

**Issue by KaraSupergirl** [keiyoushi/tachiyomi-extensions-source#3032]
### Source name

Prazeres Violentos

### Source link

https://prazeresviolentos.com/

### Source language

Portuguese 

### Other details

Password: casadeprazeres

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by viminio** [comment]
Qual é a senha do site?

**Comment by KaraSupergirl** [comment]
Password: casadeprazeres

Em dom., 19 de mai. de 2024 12:16, Viminio SM ***@***.***>
escreveu:

**Comment by KaraSupergirl** [comment]
Great! Thank you ;3

Em qui., 23 de mai. de 2024 07:54, AwkwardPeak7 ***@***.***>
escreveu:
