### ISSUE TITLE
Mangacross change the url

### ISSUE THREAD

**Issue by GoruIV** [keiyoushi/tachiyomi-extensions-source#3035]
### Source information

Manga Cross 1.4.5

### Source language

Japan

### Source new URL

https://championcross.jp

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate/part of #2532
