### ISSUE TITLE
HentaiLib updated the website design and url samples so Tachiyomi has troubles

### ISSUE THREAD

**Issue by KorobP** [keiyoushi/tachiyomi-extensions-source#3039]
### Source information

HentaiLib 1.4.44

### Source language

English, Russian

### Steps to reproduce

1. Open new design at the same url hentailib.me or old design at old.hentailib.me/old
2. "Null" error
3. Open webview
4. Opens successfully

### Expected behavior

HentaiLib.me should be parsed

### Actual behavior

Null error instead of succesful parse

1. Trying to update manhwa
![photo_3_2024-05-15_19-04-57](https://github.com/keiyoushi/extensions-source/assets/169925200/1aaa2b7f-be70-4211-bdac-add1648a92c6)

2. Trying to open HentaiLib.me
![photo_2_2024-05-15_19-04-57](https://github.com/keiyoushi/extensions-source/assets/169925200/a8b9e44e-7b83-44a7-be52-f668cc0b96ba)

3. Open WebView
![photo_1_2024-05-15_19-04-57](https://github.com/keiyoushi/extensions-source/assets/169925200/bd6790ff-e491-4678-8851-4e17984e8a7f)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #2998

Search the existing issues before opening a new one & acknowledging that you did
