### ISSUE TITLE
NetTruyen

### ISSUE THREAD

**Issue by KidVih** [keiyoushi/tachiyomi-extensions-source#3041]
### Source information

NetTruyen 1.4.35

### Source language

vietnam

### Source new URL

https://nettruyencc.com/

### Other details

https://nettruyencc.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Please see the discussion in #2887

**Comment by Karutovn** [comment]
**English** : Nettruyencc is not the official link please see #2962 and #2887 
**Vietnamese**: Nettruyencc khongo phair source chính thức của nettruyen (để biết thêm thông tin anh có thể xem #2962 vaf #2887 nhé)
