### ISSUE TITLE
The Portuguese source Slime Read is not displaying content.

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#3044]
### Source information

SlimeRead 1.4.8

### Source language

Portuguese

### Steps to reproduce

When opening the source it does not show the files only an error message.

### Expected behavior

I expected it to show the cover of the files.

### Actual behavior

![Screenshot_2024-05-15-14-57-39-653_eu kanade tachiyomi](https://github.com/keiyoushi/extensions-source/assets/169321265/c4183df4-3cfa-4e2d-a829-db6aff43a39c)

Currently it only opens in WebView.
![Screenshot_2024-05-15-15-37-28-746_app mihon debug](https://github.com/keiyoushi/extensions-source/assets/169321265/ab67e7f4-5cce-4f73-8e2f-843a32a2c35b)

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Was a site issue with their popular ranking, its fixed now

**Comment by EvaldoCeBr** [comment]
Thanks!
