### ISSUE TITLE
Lura Toon: No pages found

### ISSUE THREAD

**Issue by HyungSilver** [keiyoushi/tachiyomi-extensions-source#3046]
### Source information

Lura Toon 1.4.45

### Source language

Português (Brasil)

### Steps to reproduce

Ao entrar em qualquer capítulo da extensão dá erro pois fala que não encontrou páginas mas no site está aparecendo normalmente 
![Screenshot_20240515_144740_Mihon](https://github.com/keiyoushi/extensions-source/assets/98929917/094470c0-fc43-4977-ae5a-7a4c8f6b50bc)

### Expected behavior

Ao tentar abrir o capítulo deveria aparecer as páginas mas em todas as obras da erro pois não encontra nenhum capítulo 

### Actual behavior

quando clico na página que quero ler aparece um pop up dizendo "Nenhuma Página Encontrada"

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Edit title to "Lura Toon: No pages found"

**Comment by viminio** [comment]
I think it's because they blocked the link
https://luratoon.com/static/PeachScan/obras/XXXXX/

Previously, you just had to go to the link of the work and download it zipped to show Tachyiomi with the example link
https://luratoon.com/static/PeachScan/obras/32158/01/1.zip

**Comment by viminio** [comment]
> I think it's because they blocked the link https://luratoon.com/static/PeachScan/obras/XXXXX/
> 
> Previously, you just had to go to the link of the work and download it zipped to show Tachyiomi with the example link https://luratoon.com/static/PeachScan/obras/32158/01/1.zip

I tried it now and simply downloaded the zip. Now they're going to say I was lying kek

**Comment by nomaxsnx** [comment]
![Screenshot_2024-05-15-17-25-18-556_app mihon](https://github.com/keiyoushi/extensions-source/assets/157644160/9bc50b7e-9cbb-4cb4-9b80-875addd553d6)

🤔

**Comment by HyungSilver** [comment]
![Screenshot_20240515_152711_Brave](https://github.com/keiyoushi/extensions-source/assets/98929917/36cf1497-9c62-4002-8823-52171bae7671)

**Comment by nomaxsnx** [comment]
Se eu tiver certo, a lura toon fez uma página de criptografia que só pode acessar pelo que link que eles passam no Discord a cada sábado eles resetam o link e faz outro

Por causa que quase levarem uma DMCA (Estúdio do Eleceed) tem que ver se o nanotecnologia está tbm nesse meio.

**Comment by HyungSilver** [comment]
![Screenshot_20240515_152806_Mihon](https://github.com/keiyoushi/extensions-source/assets/98929917/6ddf3c53-5454-418d-a9c5-b0768e79c80c)
abrindo o site aparece normalmente mas pelo aplicativo dá erro

**Comment by HyungSilver** [comment]
acho que não pois a neox/nexo mudava o link semanalmente e por conta disso as obras mostrava na extensão como não favoritada mas na lura permanecem

**Comment by viminio** [comment]
A lura fez uma forma de dificultar o download, quando vc carrega o site ele baixa um zip que dps que é extraido ele gera png afif e svg, é uma bagunça completa pra evitar que façam download, para baixar eu utilizei esse script aqui

A obra era MESTRE ESPADACHIM CRIADO PELAS ESTRELAS
Captulo 41

var files = [
    "/static/PeachScan/obras/17232/41/0.zip",
    "/static/PeachScan/obras/17232/41/1.zip",
    "/static/PeachScan/obras/17232/41/2.zip",
    "/static/PeachScan/obras/17232/41/3.zip",
    "/static/PeachScan/obras/17232/41/4.zip",
    "/static/PeachScan/obras/17232/41/5.zip",
    "/static/PeachScan/obras/17232/41/6.zip",
    "/static/PeachScan/obras/17232/41/7.zip",
    "/static/PeachScan/obras/17232/41/8.zip",
    "/static/PeachScan/obras/17232/41/9.zip",
    "/static/PeachScan/obras/17232/41/10.zip",
    "/static/PeachScan/obras/17232/41/11.zip"
];

files.forEach(function(fileUrl) {
    var link = document.createElement('a');
    link.href = fileUrl;
    link.download = fileUrl.split('/').pop();
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
});

// Recarregar a página após o download dos arquivos
setTimeout(function() {
    location.reload();
}, 3000); // Recarrega a página após 3 segundos (3000 milissegundos)

**Comment by viminio** [comment]
> A lura fez uma forma de dificultar o download, quando vc carrega o site ele baixa um zip que dps que é extraido ele gera png afif e svg, é uma bagunça completa pra evitar que façam download, para baixar eu utilizei esse script aqui
> 
> A obra era MESTRE ESPADACHIM CRIADO PELAS ESTRELAS Captulo 41
> 
> var files = [ "/static/PeachScan/obras/17232/41/0.zip", "/static/PeachScan/obras/17232/41/1.zip", "/static/PeachScan/obras/17232/41/2.zip", "/static/PeachScan/obras/17232/41/3.zip", "/static/PeachScan/obras/17232/41/4.zip", "/static/PeachScan/obras/17232/41/5.zip", "/static/PeachScan/obras/17232/41/6.zip", "/static/PeachScan/obras/17232/41/7.zip", "/static/PeachScan/obras/17232/41/8.zip", "/static/PeachScan/obras/17232/41/9.zip", "/static/PeachScan/obras/17232/41/10.zip", "/static/PeachScan/obras/17232/41/11.zip" ];
> 
> files.forEach(function(fileUrl) { var link = document.createElement('a'); link.href = fileUrl; link.download = fileUrl.split('/').pop(); document.body.appendChild(link); link.click(); document.body.removeChild(link); });
> 
> // Recarregar a página após o download dos arquivos setTimeout(function() { location.reload(); }, 3000); // Recarrega a página após 3 segundos (3000 milissegundos)

Dps só renomear os arquivos .s pra .svg e converter para jpg tudo

**Comment by nomaxsnx** [comment]
> > A lura fez uma forma de dificultar o download, quando vc carrega o site ele baixa um zip que dps que é extraido ele gera png afif e svg, é uma bagunça completa pra evitar que façam download, para baixar eu utilizei esse script aqui
> > A obra era MESTRE ESPADACHIM CRIADO PELAS ESTRELAS Captulo 41
> > var files = [ "/static/PeachScan/obras/17232/41/0.zip", "/static/PeachScan/obras/17232/41/1.zip", "/static/PeachScan/obras/17232/41/2.zip", "/static/PeachScan/obras/17232/41/3.zip", "/static/PeachScan/obras/17232/41/4.zip", "/static/PeachScan/obras/17232/41/5.zip", "/static/PeachScan/obras/17232/41/6.zip", "/static/PeachScan/obras/17232/41/7.zip", "/static/PeachScan/obras/17232/41/8.zip", "/static/PeachScan/obras/17232/41/9.zip", "/static/PeachScan/obras/17232/41/10.zip", "/static/PeachScan/obras/17232/41/11.zip" ];
> > files.forEach(function(fileUrl) { var link = document.createElement('a'); link.href = fileUrl; link.download = fileUrl.split('/').pop(); document.body.appendChild(link); link.click(); document.body.removeChild(link); });
> > // Recarregar a página após o download dos arquivos setTimeout(function() { location.reload(); }, 3000); // Recarrega a página após 3 segundos (3000 milissegundos)
> 
> Dps só renomear os arquivos .s pra .svg e converter para jpg tudo

Baixar não e o problema o problema é que o maldito do "Empresário", faz isso pra quebra a extensão

**Comment by DollynDeveloper** [comment]
Alguma previsão sobre se será feito uma atualização na extensão para retorno de funcionamento?

**Comment by ProTankerAlfa** [comment]
> > > A lura fez uma forma de dificultar o download, quando vc carrega o site ele baixa um zip que dps que é extraido ele gera png afif e svg, é uma bagunça completa pra evitar que façam download, para baixar eu utilizei esse script aqui
> > > A obra era MESTRE ESPADACHIM CRIADO PELAS ESTRELAS Captulo 41
> > > var files = [ "/static/PeachScan/obras/17232/41/0.zip", "/static/PeachScan/obras/17232/41/1.zip", "/static/PeachScan/obras/17232/41/2.zip", "/static/PeachScan/obras/17232/41/3.zip", "/static/PeachScan/obras/17232/41/4.zip", "/static/PeachScan/obras/17232/41/5.zip", "/static/PeachScan/obras/17232/41/6.zip", "/static/PeachScan/obras/17232/41/7.zip", "/static/PeachScan/obras/17232/41/8.zip", "/static/PeachScan/obras/17232/41/9.zip", "/static/PeachScan/obras/17232/41/10.zip", "/static/PeachScan/obras/17232/41/11.zip" ];
> > > files.forEach(function(fileUrl) { var link = document.createElement('a'); link.href = fileUrl; link.download = fileUrl.split('/').pop(); document.body.appendChild(link); link.click(); document.body.removeChild(link); });
> > > // Recarregar a página após o download dos arquivos setTimeout(function() { location.reload(); }, 3000); // Recarrega a página após 3 segundos (3000 milissegundos)
> > 
> > 
> > Dps só renomear os arquivos .s pra .svg e converter para jpg tudo
> 
> Baixar não e o problema o problema é que o maldito do "Empresário", faz isso pra quebra a extensão

Me chamar de maldito é maldade, leia no site, qual o problema em fazer isso? E quebrar a extensão é um dos objetivos, os capítulos ficam na metade do tamanho normal, carrega mais rápido para os leitores e gasta menos banda larga : )

**Comment by viminio** [comment]
> > > > A lura fez uma forma de dificultar o download, quando vc carrega o site ele baixa um zip que dps que é extraido ele gera png afif e svg, é uma bagunça completa pra evitar que façam download, para baixar eu utilizei esse script aqui
> > > > A obra era MESTRE ESPADACHIM CRIADO PELAS ESTRELAS Captulo 41
> > > > var files = [ "/static/PeachScan/obras/17232/41/0.zip", "/static/PeachScan/obras/17232/41/1.zip", "/static/PeachScan/obras/17232/41/2.zip", "/static/PeachScan/obras/17232/41/3.zip", "/static/PeachScan/obras/17232/41/4.zip", "/static/PeachScan/obras/17232/41/5.zip", "/static/PeachScan/obras/17232/41/6.zip", "/static/PeachScan/obras/17232/41/7.zip", "/static/PeachScan/obras/17232/41/8.zip", "/static/PeachScan/obras/17232/41/9.zip", "/static/PeachScan/obras/17232/41/10.zip", "/static/PeachScan/obras/17232/41/11.zip" ];
> > > > files.forEach(function(fileUrl) { var link = document.createElement('a'); link.href = fileUrl; link.download = fileUrl.split('/').pop(); document.body.appendChild(link); link.click(); document.body.removeChild(link); });
> > > > // Recarregar a página após o download dos arquivos setTimeout(function() { location.reload(); }, 3000); // Recarrega a página após 3 segundos (3000 milissegundos)
> > > 
> > > 
> > > Dps só renomear os arquivos .s pra .svg e converter para jpg tudo
> > 
> > 
> > Baixar não e o problema o problema é que o maldito do "Empresário", faz isso pra quebra a extensão
> 
> Me chamar de maldito é maldade, leia no site, qual o problema em fazer isso? E quebrar a extensão é um dos objetivos, os capítulos ficam na metade do tamanho normal, carrega mais rápido para os leitores e gasta menos banda larga : )

Fico muito triste que tenha me banido do seu discord sem nem perguntar nada, é uma pena, me pediram pra ajudar vcs a bloquearem isso ai. Fiz o download de todas as obras, e mesmo se vc criptografar os arquivos vou continuar baixando, quanto mais dificil mais divertido é. Boa sorte ao tentar barrar agora

**Comment by HyungSilver** [comment]
já arrumou?
