### ISSUE TITLE
Luratoon is having problems

### ISSUE THREAD

**Issue by DollynDeveloper** [keiyoushi/tachiyomi-extensions-source#3047]
### Source information

Lura Too 1.4.45

### Source language

Portuguese Brazil

### Steps to reproduce

The extension has "no pages found" or even "failed to bypass Cloudflare" issues for recently released chapters.

Example: Guia de Sobrevivência do Extra da Academia
Chapters: 01-24 (working); 25 (not working)

### Expected behavior

Open the manga and access new chapters being able to read them without any problems. 

### Actual behavior

Returns error message, making it impossible to read. 

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 10

### Other details

The extension was working normally until yesterday, however it unexpectedly stopped working. I've tested it on other devices and the problem remains.  

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Duplicate of #3046

**Comment by Smol-Ame** [comment]
Duplicate of #3046

Search the existing issues before opening a new one, and acknowledging that you did

**Comment by DollynDeveloper** [comment]
I apologise for this, I did not pay attention and I recognise the mistake. Again, a thousand pardons.

**Comment by Norsze** [comment]
It's fine, as long as you don't do it multiple times, good that you understand
