### ISSUE TITLE
[Mangadex] Duplicating manga chapters during global updates

### ISSUE THREAD

**Issue by serveral1** [keiyoushi/tachiyomi-extensions-source#305]
### Source information

Mangadex 1.4.192

### Source language

English

### Steps to reproduce

1. Add any random entry from mangadex to library
2. Start global update
3. See duplicated chapters

### Expected behavior

No duplicate chapters to appear during global update.

### Actual behavior

"New unread" duplicate chapters appear on the chapter list, including those that were marked as read before (they are duplicated and marked as unread)

### Tachiyomi version

TachiyomiSy 1.10.1

### Android version

Android 10

### Other details

To clarify, this isn't an issue about chapters from other translation teams/language sources appearing, but instead the same chapter from the same translator team randomly appearing duplicated and marked as unread for some unknown reason.
![Screenshot_20240116-140155](https://github.com/keiyoushi/extensions-source/assets/10162026/848e4ae4-21b5-4d67-91b4-e77f48ab95c2)
This only started happening after the new extensions repo update (and after adding this repo to my app) and no other sources that I use have this issue, only mangadex. I'm not logged to my mangadex account through the app and have no sync/trackers setting enabled.
Again this only seems to happen during global updates, as whenever I manually update an entry myself, the issue doesn't appear. I've tried clearing the database before and re-adding the entries back again to clear the issue to no avail as the global update keeps messing around the lists with duplicate chapters.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kaosjr** [comment]
Can confirm this also happens on Stable 0.15.3 on Android 13. Extension hasn't been updated after the new repo was added. 
![Screenshot_20240116_231146_Tachiyomi](https://github.com/keiyoushi/extensions-source/assets/16449077/f6eb6534-4445-4e58-b4cb-794b21ac320a)

**Comment by beer-psi** [comment]
The MangaDex extension has not been updated since it was migrated here, so I'm willing to bet this is an issue with the app itself.

**Comment by beer-psi** [comment]
Confirmed app issue, wait for an update.

**Comment by serveral1** [comment]
> Confirmed app issue, wait for an update.

sorry to bother, but is there an issue/PR/commit in reference to this bug that could be linked here? or is that not possible due to the new MO of not cross-linking extensions with the app to avoid other "issues".

just asking because I've tried to look for something myself but have found nothing so far on SY/Mihon
