### ISSUE TITLE
It says that cannot find the website

### ISSUE THREAD

**Issue by FlechaFofao** [keiyoushi/tachiyomi-extensions-source#3050]
### Source information

Lura Toon 1.4.45

### Source language

Português (Brasil)

### Steps to reproduce

1. Open the source;
2. Search for "Nanotecnologia Marcial";
3. Try to read the last chapters (205,206,207);
4.  You should see the issue here, besides the webview showing that is has a working page for the chapters mentioned, it says that cannot find the site of the chapter when you try to read them.
5. I'm sorry for my bad english.

### Expected behavior

The extension should be able to link the chapter in the app to the chapter in the scan.

### Actual behavior

It says that cannot find the website

### Mihon/Tachiyomi version

Tachyiomi 0.15.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #3046

Search the existing issues before opening a new issue, and acknowledging that you did

**Comment by FlechaFofao** [comment]
I'm sorry, I'm new at this github
