### ISSUE TITLE
Manhuascan

### ISSUE THREAD

**Issue by Itsyua** [keiyoushi/tachiyomi-extensions-source#3059]
### Source information

Manhuascan 1.4.8

### Source language

English 

### Source new URL

https://kaliscan.com

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Pjppy2** [comment]
One of the mirror URLs for this source, Mangajinx, also changed. The current url it changed to is https://mgjinx.com/ .
