### ISSUE TITLE
MangaTale 1.4.32 "Page not Found" Error

### ISSUE THREAD

**Issue by VrZeta** [keiyoushi/tachiyomi-extensions-source#3060]
### Source information

MangaTale 1.4.32

### Source language

Indonesia 

### Steps to reproduce

1. Download any their project comic latest chapter 
2. Read any chapter, chapter immediately close and "Page not Found" show in the bottom
![Screenshot_2024-05-17-01-59-01-07_551f7f0ca926862b368845ce7ee433aa](https://github.com/keiyoushi/extensions-source/assets/156036525/b1528022-4cab-401e-9480-64354ddebe37)

### Expected behavior

Chapter image show up and Read smoothly downloaded chapter without loading

### Actual behavior

Chapter immediately close and "page not found" error show even though it has been downloaded

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 13

### Other details

1. There are no errors in the chapter at all when read online or from webview

2. This error only occurs with the comics they work on.  Mirrored comics don't have this problem when downloaded

3. The only chapters that have this error are the chapters released in 2024, 2023 and below do not have this error

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
I was able to reproduce the issue. Not exactly sure what the issue is though.
Steps:
1. Tap Sources
2. Tap MangaTale
3. Tap "The Greatest Estate Developer"
4. Tap download next to "Chapter 139"
5. ... wait for download to complete
6. Tap "Chapter 139"
8. Observe "No pages found"

Could reproduce the issue for chapters: 140, 139, 137 Fix, 136, 134, 132, 130. There are probably more, but you need to download the chapter before trying to open it.
