### ISSUE TITLE
Traducciones Moonlight

### ISSUE THREAD

**Issue by ashliepolanco** [keiyoushi/tachiyomi-extensions-source#3067]
### Source information

Traducciones Moonlight 1.4.38

### Source language

Español

### Source new URL

https://traduccionesmoonlight.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ashliepolanco** [comment]
It's a new domain, the other one no longer works when you tried to access it.

**Comment by Norsze** [comment]
as you can see your "new domain" is already a part of the extension, in fact it has been for 3 months, guess you don't check it often

**Comment by ashliepolanco** [comment]
I just did it and it doesn't load the url I passed is your new domain 
![Screenshot_20240516_194230_Ykai](https://github.com/keiyoushi/extensions-source/assets/156876433/7898312d-556e-4f02-af6e-4000ef5b3ca7)

**Comment by Norsze** [comment]
nothing wrong with the URL, but the extension might be broken for other reasons, if you don't know you should just make a general bug report
