### ISSUE TITLE
MangaJinx URL Change

### ISSUE THREAD

**Issue by Pjppy2** [keiyoushi/tachiyomi-extensions-source#3068]
### Source information

ManhuaScan 1.4.8

### Source language

English

### Source new URL

https://mgjinx.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Duplicate of #3059

**Comment by Smol-Ame** [comment]
On top of duplicate issue for same extension, where did you get this new link from? Do you have any info/announcements/mentions that can corroborate proof that this link is to be used, over the one mentioned in #3059?

Unless you wrote the wrong extension/source info into the details above

**Comment by Pjppy2** [comment]
Mangajinx was added in as a mirror for Manhuascan in #849 so I assumed it was a source for it. When using the Mangajinx mirror for the Manhuascan extension, I noticed the link changed from Mangajinx to Mgjinx.

**Comment by Smol-Ame** [comment]
> Mangajinx was added in as a mirror for Manhuascan in #849 so I assumed it was a source for it. When using the Mangajinx mirror for the Manhuascan extension, I noticed the link changed from Mangajinx to Mgjinx.

Ah okay, in that case, could you comment this mirror URL change in the 3059 issue request, so it gets fixed/updated together whenever a contributor has the time to work on it?

**Comment by Pjppy2** [comment]
I commented it now, thanks!
