### ISSUE TITLE
Nettruyen URL change

### ISSUE THREAD

**Issue by huyndb** [keiyoushi/tachiyomi-extensions-source#3069]
### Source information

NetTruyen

### Source language

Vietnamese

### Source new URL

https://nettruyencc.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Next time, search the existing issues before opening a new issue & acknowledging that you did.

Also see the discussion in #2887
