### ISSUE TITLE
Olympus

### ISSUE THREAD

**Issue by Striven100** [keiyoushi/tachiyomi-extensions-source#3070]
### Source information

esolympussacnlation

### Source language

Español

### Steps to reproduce

No puedo acceder a la extension ni a los manhwas en mi biblioteca.
![Screenshot_20240516-213629_Tachiyomi](https://github.com/keiyoushi/extensions-source/assets/138946506/0657a710-07f7-4291-ae0d-9218fa30bb81)

### Expected behavior

Nose, supongo q deberia funcionar

### Actual behavior

No se si cambio la raw, pero creo q es otra cosa

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #3062

Search the existing issues next time before creating a new one, and acknowledging that you did. For now, wait for a future extension update.

**Comment by Norsze** [comment]
Duplicate of #3062
