### ISSUE TITLE
DIFFERENT URL

### ISSUE THREAD

**Issue by saengohe** [keiyoushi/tachiyomi-extensions-source#3071]
### Source name

Olympus Scanlation

### Source language

Spanish

### Source link

Https://olympusv2.gg

### Other details

The source change website to https://leerolymp.com

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of https://github.com/keiyoushi/extensions-source/issues/3062

Literally reported a few times now, search the existing issues next time before creating a new one, and acknowledging that you did. For now, wait for a future extension update.

**Comment by Norsze** [comment]
Duplicate of #3062

it goes to the same address as 3062 when you continue to the site from the landing page
