### ISSUE TITLE
NetTruyen switch to new URL

### ISSUE THREAD

**Issue by Ikitryu** [keiyoushi/tachiyomi-extensions-source#3075]
### Source information

Netruyen 1.4.35

### Source language

Vietnamese

### Source new URL

https://nettruyenloli.com/

### Other details

The old URL current extension using is death. The real site have switch to new site which is https://nettruyenloli.com/.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of many, search the existing issues before you open a new one & acknowledge that you did.

See the discussion in #2887

Also, if you can, where are you getting this information that this is the "real site"? If you have screenshots/announcements/messages that helps with figuring out the link, please comment it in over there
