### ISSUE TITLE
Cambio de URL Olympus Scan

### ISSUE THREAD

**Issue by Emmanuel250701** [keiyoushi/tachiyomi-extensions-source#3076]
### Source information

OlympusScalanation 1.4.8

### Source language

Español

### Source new URL

https://leerolymp.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
For future issue requests, search the existing issues next time before creating a new one, and acknowledging that you did. For now, wait for a future extension update.
