### ISSUE TITLE
Anchira Bugged

### ISSUE THREAD

**Issue by blackheart911126** [keiyoushi/tachiyomi-extensions-source#3079]
### Source information

Anchira 1.4.13

### Source language

English

### Steps to reproduce

1. Click on read chapter
2. Kicked out with reminders at the bottom

### Expected behavior

Opens normally and readable

### Actual behavior

![IMG_20240517_145241](https://github.com/keiyoushi/extensions-source/assets/113771133/d6da64de-0fb8-41e1-bc41-5608f09811b6)

### Mihon/Tachiyomi version

TachiyomiJ2K 1.7.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Kantotero** [comment]
I also have a problem in anchira, upon opening extension it leads to 
`unexpected JSON...`![Screenshot_2024-05-18-21-32-28-125.jpg](https://github.com/keiyoushi/extensions-source/assets/125627064/95e87652-48bf-4515-9bea-dbd9d0c85c2a)
