### ISSUE TITLE
Ikigai Mangas change URL

### ISSUE THREAD

**Issue by saengohe** [keiyoushi/tachiyomi-extensions-source#3085]
### Source information

Ikigai Mangas

### Source language

Spanish

### Source new URL

https://nocbro.xyz/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by yoo07** [comment]
I would suggest not updating the URL, "nocbro" seems more like a temporary URL while they decide on the new one, they haven't made an official announcement about the URL change on their discord yet.

**Comment by VannevarB** [comment]
@yoo07 They changed the url again. It's "http://visorikigai.net" now

**Comment by saengohe** [comment]
> @yoo07 They changed the url again. It's "http://visorikigai.net" now

When you select a chapter it redirects to nocbro.xyz

**Comment by VannevarB** [comment]
> > @yoo07 They changed the url again. It's "http://visorikigai.net" now
> 
> When you select a chapter it redirects to nocbro.xyz

Webview

![Screenshot_2024-05-17-18-31-23](https://github.com/keiyoushi/extensions-source/assets/61358702/b2c8abd0-4118-499e-9a24-863bfdf1be79)

**Comment by saengohe** [comment]
> > > @yoo07 They changed the url again. It's "http://visorikigai.net" now
> > 
> > 
> > When you select a chapter it redirects to nocbro.xyz
> 
> Webview
> 
> ![Screenshot_2024-05-17-18-31-23](https://private-user-images.githubusercontent.com/61358702/331735872-b2c8abd0-4118-499e-9a24-863bfdf1be79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5ODIzMzksIm5iZiI6MTcxNTk4MjAzOSwicGF0aCI6Ii82MTM1ODcwMi8zMzE3MzU4NzItYjJjOGFiZDAtNDExOC00OTllLTlhMjQtODYzYmZkZjFiZTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDIxNDAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3MWExM2U2ZjBlM2FlYWViNmRhYzdkNGUyMjlmNTc1ZjE1Y2I4Nzc0NWRlNmY3N2IxMGNlOTQzZDE4ODBiNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AowlnW-1eLP10HNJAk47vQeYwBXHpPVJJ4PL9PSCYnk)

![Screenshot_20240517-154022](https://github.com/keiyoushi/extensions-source/assets/44875169/7dcbfd33-a2e5-4533-b03d-0d3505c1cd8c)

It is when a chapter is selected, not the manga itself

**Comment by yoo07** [comment]
> > @yoo07 They changed the url again. It's "http://visorikigai.net" now
> 
> When you select a chapter it redirects to nocbro.xyz

As I said, it is only a suggestion, "nocbro" is clearly a name they chose to get out of the problem they had with the previous domain, they still have not made any announcement in their discord about the domain change.
