### ISSUE TITLE
Problemas na lura toon

### ISSUE THREAD

**Issue by Pedropaulo015** [keiyoushi/tachiyomi-extensions-source#3088]
### Source information

Lura toon

### Source language

Português brasil

### Steps to reproduce

As imagens não carregam eu já resolvi o cloudflare no capitulo mais continua a mesma coisa

### Expected behavior

Quando resolvesse o cloudflare as imagens deveriam carregar

### Actual behavior

Mais elas não estão carregando

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 10

### Other details

![Screenshot_20240517-144705](https://github.com/keiyoushi/extensions-source/assets/166200660/94fae4fc-2a6b-48ef-82b6-2ce6b6735c11)
![Screenshot_20240517-143338](https://github.com/keiyoushi/extensions-source/assets/166200660/74c5370d-66e2-4fe6-8e89-6d73243a7a49)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
What is your extension version of Lura toon?

**Comment by bapeey** [comment]
~~seems like a site issue~~, nvm was a region block

**Comment by DollynDeveloper** [comment]
Chapters are being blocked as soon as they are opened
![Screenshot_20240517-163430_Kuukiyomi](https://github.com/keiyoushi/extensions-source/assets/72720834/1148f9c0-bed6-4697-bf8d-ebe8ae4dd8a1)
It seems that now Cloudflare verification is only present when accessing chapters

**Comment by DollynDeveloper** [comment]
> What is your extension version of Lura toon?

The problem is happening in the latest version of the extension, the same one that was updated yesterday (The problem is happening in the latest version of the extension, the same one that was updated yesterday (1.4.46)

**Comment by Pedropaulo015** [comment]
> Qual é a sua versão de extensão do Lura toon?

1.4.46

**Comment by Pedropaulo015** [comment]
> Os capítulos estão sendo bloqueados assim que são abertos Parece que agora a verificação Cloudflare só está presente ao acessar os capítulos ![Captura de tela_20240517-163430_Kuukiyomi](https://private-user-images.githubusercontent.com/72720834/331713073-1148f9c0-bed6-4697-bf8d-ebe8ae4dd8a1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NzUxMzIsIm5iZiI6MTcxNTk3NDgzMiwicGF0aCI6Ii83MjcyMDgzNC8zMzE3MTMwNzMtMTE0OGY5YzAtYmVkNi00Njk3LWJmOGQtZWJlOGFlNGRkOGExLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDE5NDAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZWRjYzdkNWI3YjI4YWY3NDFlODhhOWIzZjEzNDdjYmZiODU4ZjFkNzE1Mjc5MjhmZDRiY2Q1MzkzOWY1YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6k_N9uENUSbMI6RxbAd_jwUxTWwxOvqcLEO0Y8HnzOE)

Sim isso mesmo

**Comment by Pedropaulo015** [comment]
Tem algum geito de resolver

**Comment by Pedropaulo015** [comment]
> > Qual é a sua versão de extensão do Lura toon?
> 
> O problema está acontecendo na última versão da extensão, a mesma que foi atualizada ontem (O problema está acontecendo na última versão da extensão, a mesma que foi atualizada ontem (1.4.46)

Sim

**Comment by Pedropaulo015** [comment]
Sim é na versão mais recentes 1.4.46 como posso resolver é uma das
extensões que mais uso

Em sex, 17 de mai de 2024 16:38, DollynDeveloper ***@***.***>
escreveu:

**Comment by nomaxsnx** [comment]
> Chapters are being blocked as soon as they are opened ![Screenshot_20240517-163430_Kuukiyomi](https://private-user-images.githubusercontent.com/72720834/331713073-1148f9c0-bed6-4697-bf8d-ebe8ae4dd8a1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5OTAyMzksIm5iZiI6MTcxNTk4OTkzOSwicGF0aCI6Ii83MjcyMDgzNC8zMzE3MTMwNzMtMTE0OGY5YzAtYmVkNi00Njk3LWJmOGQtZWJlOGFlNGRkOGExLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDIzNTIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZGYyNjJhMGY5MDQ1YjNkMzYwNzgxODU2ZjNkZTZkMzUwN2EzNDg5ZGYxYTEyZmZiMzI0ODExZDExMTQzZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JtO3VV0OhCdIVFjq-5P3ilIi9lnwFtYud37IGtebEVI) It seems that now Cloudflare verification is only present when accessing chapters

Usa o app na playstore chamado: "1.1.1.1" da cloudfare, depois de iniciar reiniciar o app e pronto.

**Comment by Pedropaulo015** [comment]
Ok obrigado

Em sex, 17 de mai de 2024 20:53, nomaxsnx ***@***.***>
escreveu:

**Comment by Pedropaulo015** [comment]
Eu fiz como vc disse mais não funcionou

Em sex, 17 de mai de 2024 21:33, Pedro Paulo Pereira Da Costa <
***@***.***> escreveu:

**Comment by Pedropaulo015** [comment]
Continuou com o mesmo problema

Em sex, 17 de mai de 2024 21:49, Pedro Paulo Pereira Da Costa <
***@***.***> escreveu:

**Comment by Pedropaulo015** [comment]
Versão 1.4.46

Em sáb, 18 de mai de 2024 11:45, AwkwardPeak7 ***@***.***>
escreveu:
