### ISSUE TITLE
Add to library problem

### ISSUE THREAD

**Issue by AkuStranger** [keiyoushi/tachiyomi-extensions-source#3091]
### Source information

Bato.to 1.4.36

### Source language

Multi

### Steps to reproduce

1. Search
2. Add to library 
3. Not show on library tab

### Expected behavior

1. Search
2. Add to library
3. Shown on library tab

### Actual behavior

1. Search
2. Add to library
3. Shown on migrate tab

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 11

### Other details

Also happen to other  extensions

![Screenshot_2024-05-18-04-47-34-60](https://github.com/keiyoushi/extensions-source/assets/81702563/231de0b4-2a0b-4bd3-ad6b-c06832363973)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
If something isn't showing up on your Library Page, check the filters on the Library page (three-lines button at the top), like "Downloaded Only"

**Comment by AkuStranger** [comment]
![Screenshot_2024-05-18-04-57-11-85_551f7f0ca926862b368845ce7ee433aa](https://github.com/keiyoushi/extensions-source/assets/81702563/6147aa54-055e-4fe4-a826-dee559823e2e)

![Screenshot_2024-05-18-04-57-33-63_551f7f0ca926862b368845ce7ee433aa](https://github.com/keiyoushi/extensions-source/assets/81702563/8c8645c5-4b64-44ed-9046-6608a967f827)

Like I said before it showing on migrate page.. i tried remove and add again still showing on migrate page..

**Comment by Smol-Ame** [comment]
> Like I said before it showing on migrate page.. i tried remove and add again still showing on migrate page..

No offense, just wanting to check because it has happened before, are you trying to search/look for a manga/entry called "@" in your Library?

Whatever you add from the extensions will show up in the Library page, on whatever category you placed the entry in. The only thing that should affect what you see in the Library is either filters or an incorrect name that you're searching.

**Comment by AkuStranger** [comment]
> No offense, just wanting to check because it has happened before, are you trying to search/look for a manga/entry called "@" in your Library?

No.. it's example.. i just wanna show you that i didn't check anything when you ask to check filter..

**Comment by Smol-Ame** [comment]
> No.. i just wanna show you that i didn't check anything when you ask to check filter..

I bring up the "@" because you have something in the Library search
![Screenshot_20240517_140752_Firefox Nightly](https://github.com/keiyoushi/extensions-source/assets/155411819/ac5ddab2-3e5e-4ac7-950e-ea767e1c47e4)

**Comment by AkuStranger** [comment]
![Screenshot_2024-05-18-05-10-30-57](https://github.com/keiyoushi/extensions-source/assets/81702563/38541d9e-a394-40ce-ba22-03e54ecf7bd1)
This is actual manga/entry that doesn't showing on library..

![Screenshot_2024-05-18-05-11-55-49_551f7f0ca926862b368845ce7ee433aa](https://github.com/keiyoushi/extensions-source/assets/81702563/a3a99264-3500-4e9c-92ea-0ec3e67f17a3)
Another example.. it show already in library.. but show on migrate page not library page

**Comment by Smol-Ame** [comment]
Did you see what I said above your reply? Have you cleared that "@" & try searching your Library for those entry names?

**Comment by Norsze** [comment]
Most likely cause is still that you have filtered it in your library, I have no issues adding it so it is very much isolated to you and your phone

https://github.com/keiyoushi/extensions-source/assets/66540317/ab4fb9ef-e010-46d5-aa34-83a16e6342b6

**Comment by AkuStranger** [comment]
> Did you see what I said above your reply? Have you cleared that "@" & try searching your Library for those entry names?

Yes.. already did that just now.. thanks.. i need to learn how to use this mihon app more..s
