### ISSUE TITLE
Manga from Batoto not showing cover art in library 

### ISSUE THREAD

**Issue by Illythia** [keiyoushi/tachiyomi-extensions-source#310]
### Source information

Bato.to 1.4.34

### Source language

Multi

### Steps to reproduce

1. Open app
2. Go to library
3. Cover art not loading

### Expected behavior

Covers should be loading
![Screenshot_2024-01-17-03-15-55-10_76d0f6352040d5ab219b0498c33ac39d](https://github.com/keiyoushi/extensions-source/assets/129698114/e88eb63c-f691-4915-a42c-93af8b135346)
![Screenshot_2024-01-17-03-15-39-39_76d0f6352040d5ab219b0498c33ac39d](https://github.com/keiyoushi/extensions-source/assets/129698114/36c1474e-655a-4217-ade3-dbed89a6f852)

### Actual behavior

Cover art is not loading while it is for other sources

### Tachiyomi version

Mihon preview r6442

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by aboudiom59** [comment]
Just reload the manga and the cover will come. Bato.to has kinda had that for a while, if the manga is updated during a library update you have like two hours for the cover to atomically load before you have to manually update the manga. If you don't want that just disable the metadata update in the library settings

**Comment by AwkwardPeak7** [comment]
bato's image urls are temporary, so they expire over time. Either refresh those titles manually or go to settings > advanced > clear database; and settings > advanced  > refresh library covers.
