### ISSUE TITLE
[PT-BR] LuraToon: New file extension

### ISSUE THREAD

**Issue by viminio** [keiyoushi/tachiyomi-extensions-source#3104]
### Source information

Lura Toon

### Source language

Português (Brasil)

### Steps to reproduce

1.Download LuraToon
2.Open LuraToon Extensions
3.Try view newer mangás (after 1.4.46) (Example: O Começo Depois do Fim)
![image](https://github.com/keiyoushi/extensions-source/assets/62722905/665ba177-b281-4730-9695-c06f68ac49d4)
4.Error
![image](https://github.com/keiyoushi/extensions-source/assets/62722905/60602c8d-780c-49da-8ee4-7dd124800a58)

### Expected behavior

In previous chapters of the url variable

`'/static/PeachScan/obras/31169/01/0.zip', '/static/PeachScan/obras/31169/01/1.zip', '/static/PeachScan/obras/31169/01/2.zip', '/static/PeachScan/obras/31169/01/3.zip', '/static/PeachScan/obras/31169/01/4.zip', '/static/PeachScan/obras/31169/01/5.zip', '/static/PeachScan/obras/31169/01/6.zip'`

.s (in this case svg) and avif files were received
![image](https://github.com/keiyoushi/extensions-source/assets/62722905/27ea4af8-62cc-4b95-b1ac-c28aca4fd010)

### Actual behavior

In current chapters of the url variable

`(/static/PeachScan/obras/31169/177/0.zip', '/static/PeachScan/obras/31169/177/1.zip', '/static/PeachScan/obras/31169/ 177/2.zip', '/static/PeachScan/obras/31169/177/3.zip', '/static/PeachScan/obras/31169/177/4.zip', '/static/PeachScan/obras/31169 /177/5.zip', '/static/PeachScan/obras/31169/177/6.zip', '/static/PeachScan/obras/31169/177/7.zip', '/static/PeachScan/obras/ 31169/177/8.zip', '/static/PeachScan/obras/31169/177/9.zip', '/static/PeachScan/obras/31169/177/10.zip', '/static/PeachScan/obras /31169/177/11.zip', '/static/PeachScan/obras/31169/177/12.zip', '/static/PeachScan/obras/31169/177/13.zip', '/static/PeachScan/ obras/31169/177/14.zip', '/static/PeachScan/obras/31169/177/15.zip', '/static/PeachScan/obras/31169/177/16.zip', '/static/PeachScan /obras/31169/177/17.zip', '/static/PeachScan/obras/31169/177/18.zip'])`

The files are the same however with their extension removed
![image](https://github.com/keiyoushi/extensions-source/assets/62722905/6fb8b441-434e-4ada-9739-0d1f028e6ea5)

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 11

### Other details

Script if you need to download the files to test

```
urls.forEach(function(fileUrl) {
    var link = document.createElement('a');
    link.href = fileUrl;
    link.download = fileUrl.split('/').pop();
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
});
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #3088

Proposed fix with #3090
