### ISSUE TITLE
HTTP 521 EarlyManga

### ISSUE THREAD

**Issue by Sachin-Bhat** [keiyoushi/tachiyomi-extensions-source#3105]
### Source information

EarlyManga 1.4.27

### Source language

English

### Steps to reproduce

1. Install the extension
2. Search for something within the extension.

### Expected behavior

Ideally if the results exist, it should return the relevant result.

### Actual behavior

While searching the extension, I get the following error instead: "HTTP 521, check website in webview."

### Mihon/Tachiyomi version

Mihon Stable 0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
That's a source-related issue, not extension-related. If you look in WebView or go to your own browser, you'll see their page is down.

HTTP 500s are usually source-related server issues, and you can also use sites like this to verify if it's down for you or everybody: https://downforeveryoneorjustme.com/earlymanga.org
