### ISSUE TITLE
Problema "Ahorro de datos"

### ISSUE THREAD

**Issue by AlexZaratee** [keiyoushi/tachiyomi-extensions-source#3106]
### Source information

Ikigai mangas

### Source language

Spanish

### Steps to reproduce

Buenos dias gente, no quiero hacer largo la charla entinces para empezar la extensión "Ikigai mangas" no me deja ver los manhwas, ni mangas que tengo en mi biblioteca, al entrar a la web de la extensión, hay un problema que dice ahorro de datos, si no presiono este botón y cambio a episodios completos, no me deja ver, y el problema esta aquí, cuando salgo se reinicia y no me deja leer nada a menos que esté en la web, intente borrar cookies y limpiar los datos de webView, pero no me sirve.

### Expected behavior

Gracias por leer esto y espero su pronta respuesta y solución a este problema que me quito 90 manhwas ;(

### Actual behavior

![Screenshot_20240518_093306_Samsung Internet](https://github.com/keiyoushi/extensions-source/assets/159848183/30d25d23-5d65-4dba-b296-b2ca6e27674e)

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 14

### Other details

![Screenshot_20240518_092947_Tachiyomi](https://github.com/keiyoushi/extensions-source/assets/159848183/1fb1c7c7-852a-44f4-ae25-1294327194c6)
![Screenshot_20240518_093018_Tachiyomi](https://github.com/keiyoushi/extensions-source/assets/159848183/dd75509c-f56d-4507-aef2-a58d485fa298)

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AlexZaratee** [comment]
> ### Source information
> Ikigai mangas
> 
> ### Source language
> Spanish
> 
> ### Steps to reproduce
> Buenos dias gente, no quiero hacer largo la charla entinces para empezar la extensión "Ikigai mangas" no me deja ver los manhwas, ni mangas que tengo en mi biblioteca, al entrar a la web de la extensión, hay un problema que dice ahorro de datos, si no presiono este botón y cambio a episodios completos, no me deja ver, y el problema esta aquí, cuando salgo se reinicia y no me deja leer nada a menos que esté en la web, intente borrar cookies y limpiar los datos de webView, pero no me sirve.
> 
> ### Expected behavior
> Gracias por leer esto y espero su pronta respuesta y solución a este problema que me quito 90 manhwas ;(
> 
> ### Actual behavior
> ![Screenshot_20240518_093306_Samsung Internet](https://private-user-images.githubusercontent.com/159848183/331804821-30d25d23-5d65-4dba-b296-b2ca6e27674e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMzk5MzIsIm5iZiI6MTcxNjAzOTYzMiwicGF0aCI6Ii8xNTk4NDgxODMvMzMxODA0ODIxLTMwZDI1ZDIzLTVkNjUtNGRiYS1iMjk2LWIyY2E2ZTI3Njc0ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQxMzQwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDVjNWM4MGQ4MWNhNzY3NTU2YWM5MzgwNTViZmViNDE3YTIyZGRkNzM2YTc3NjlmYTljODUwYjJkZDNiMmU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sgi5uCPYgmMzwrwk-C5GcayiZITk3kI3eK09G5bdUp0)
> 
> ### Mihon/Tachiyomi version
> 0.15.3
> 
> ### Android version
> Android 14
> 
> ### Other details
> ![Screenshot_20240518_092947_Tachiyomi](https://private-user-images.githubusercontent.com/159848183/331804585-1fb1c7c7-852a-44f4-ae25-1294327194c6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMzk5MzIsIm5iZiI6MTcxNjAzOTYzMiwicGF0aCI6Ii8xNTk4NDgxODMvMzMxODA0NTg1LTFmYjFjN2M3LTg1MmEtNDRmNC1hZTI1LTEyOTQzMjcxOTRjNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQxMzQwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDUwN2QwNGE3MGRmZmI5ODQ2ZjM1ZmZhNjg1YjJhNDZjYWU5MDhlMWZmZWEzYTI1MmM3OWI2ZmM0ODNjOWI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7PT1tHcsNX5us0nkdvs00DRGy9Ez_yMFAFicuC9avjs) ![Screenshot_20240518_093018_Tachiyomi](https://private-user-images.githubusercontent.com/159848183/331804636-dd75509c-f56d-4507-aef2-a58d485fa298.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMzk5MzIsIm5iZiI6MTcxNjAzOTYzMiwicGF0aCI6Ii8xNTk4NDgxODMvMzMxODA0NjM2LWRkNzU1MDljLWY1NmQtNDUwNy1hZWYyLWE1OGQ0ODVmYTI5OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQxMzQwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NjQzY2RkN2Y2NjRlMmNhMDJhNGFiNjk5OTY1YTM4M2Q3YTU2YjZiNTlkZmQ4M2VkYjJhMDM2NDk3NDk0NzU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dOuc_NCIRrzqyp_CsDQp_5H1znA00xC4hBew2Uqt-XE)
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
> * [x]  I have updated all installed extensions.
> * [x]  I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
> * [x]  If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
> * [x]  I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #3085

Search the existing issues before opening a new issue, and acknowledging that you did.
