### ISSUE TITLE
El boton "Ahorro de datos"

### ISSUE THREAD

**Issue by AlexZaratee** [keiyoushi/tachiyomi-extensions-source#3107]
### Source information

Ikigai mangas

### Source language

Spanish

### Steps to reproduce

Buenos dias gente, no quiero hacer largo la charla entinces para empezar la extensión "Ikigai mangas" no me deja ver los manhwas, ni mangas que tengo en mi biblioteca, al entrar a la web de la extensión, hay un problema que dice ahorro de datos, si no presiono este botón y cambio a episodios completos, no me deja ver, y el problema esta aquí, cuando salgo se reinicia y no me deja leer nada a menos que esté en la web, intente borrar cookies y limpiar los datos de webView, pero no me sirve.

### Expected behavior

Gracias por leer esto y espero su pronta respuesta y solución a este problema que me quito 90 manhwas, por cierto no me peguen si estoy enviando esto denuevo solo que puse por error el botón que dice que ya se soluciono el problema Xd

### Actual behavior

![Screenshot_20240518_093306_Samsung Internet](https://github.com/keiyoushi/extensions-source/assets/159848183/30d25d23-5d65-4dba-b296-b2ca6e27674e)

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 14

### Other details

![Screenshot_20240518_092947_Tachiyomi](https://github.com/keiyoushi/extensions-source/assets/159848183/1fb1c7c7-852a-44f4-ae25-1294327194c6)
![Screenshot_20240518_093018_Tachiyomi](https://github.com/keiyoushi/extensions-source/assets/159848183/dd75509c-f56d-4507-aef2-a58d485fa298)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #3085 / Part of #3106
