### ISSUE TITLE
Anchira not loading list

### ISSUE THREAD

**Issue by enricofish** [keiyoushi/tachiyomi-extensions-source#3108]
### Source information

1.4.13

### Source language

English

### Steps to reproduce

1. Open Anchira source, both main and recent
2. See unexpected JSON token error, list doesn't load

### Expected behavior

List should open and load

### Actual behavior

![Screenshot_20240518-153933_Mihon](https://github.com/keiyoushi/extensions-source/assets/7489114/4d698751-cfe1-4716-806b-f5748616ab46)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #3079

Search the existing issues before opening a new issue, and acknowledging that you did.

**Comment by enricofish** [comment]
I'm sorry but it didn't seem a duplicate, since the issue from the other day was correctly fixed and anyways it was appearing upon opening an entry from the list, while in this case the list is not populating at all.
But again I'm sorry for posting a duplicate. The correct behaviour should have been to post a message/update in the issue opened the other day?

**Comment by Smol-Ame** [comment]
> I'm sorry but it didn't seem a duplicate, since the issue from the other day was correctly fixed and anyways it was appearing upon opening an entry from the list, while in this case the list is not populating at all. But again I'm sorry for posting a duplicate. The correct behaviour should have been to post a message/update in the issue opened the other day?

It was fixed the other day & broke again the next. Wait for an extension update as the proposed fix was just implemented into the repo

**Comment by enricofish** [comment]
> > I'm sorry but it didn't seem a duplicate, since the issue from the other day was correctly fixed and anyways it was appearing upon opening an entry from the list, while in this case the list is not populating at all. But again I'm sorry for posting a duplicate. The correct behaviour should have been to post a message/update in the issue opened the other day?
> 
> It was fixed the other day & broke again the next. Wait for an extension update as the proposed fix was just implemented into the repo

Understood, sorry for the inconvenience of creating a duplicate and thank you for your patience!
