### ISSUE TITLE
1st Kiss Manga

### ISSUE THREAD

**Issue by ryunosuke21** [keiyoushi/tachiyomi-extensions-source#311]
### Source name

1st Kiss Manga

### Source link

https://1st-kissmanga.net

### Source language

English

### Other details

1st kiss manga lost most of its websites and this is the new one. Needs an update and probably remove all the dead one's from the repo. Attached is an image of the website: 

Old version used to be named 1stKissDashManga now its 1st-KissManga

![image](https://github.com/keiyoushi/extensions-source/assets/145036687/51f1c8ff-978c-43ba-8ed1-653d41994124)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by OoLunar** [comment]
Bumping for attention, none of my comics update anymore
