### ISSUE TITLE
Luratoon - change url pt br

### ISSUE THREAD

**Issue by nomaxsnx** [keiyoushi/tachiyomi-extensions-source#3115]
### Source information

Lura toon 1.4.47

### Source language

Português 

### Source new URL

https://lura-toons.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by DollynDeveloper** [comment]
Even after the domain change, it continues to work normally here. Try clearing your app's cache and the Webview.
