### ISSUE TITLE
Tsuki Mangas has problems

### ISSUE THREAD

**Issue by DollynDeveloper** [keiyoushi/tachiyomi-extensions-source#3116]
### Source information

Tsuki Mangás 1.4.5

### Source language

Portuguese Brazil

### Steps to reproduce

The extension is experiencing similar issues to the previous version of Lura Toon (page loading error). 

The preview in the Webview is without any problems, but in the reader, it continues to have problems, given by IP blocking. 
![Screenshot_20240518-210559_Kuukiyomi](https://github.com/keiyoushi/extensions-source/assets/72720834/9623082b-6c14-4d49-8435-7c1da7a9fcc7)
![Screenshot_20240518-210923_Kuukiyomi](https://github.com/keiyoushi/extensions-source/assets/72720834/bf21145d-9ccd-44d5-b3c9-f47c4b0ab292)

### Expected behavior

That the images made available on the site were uploaded without problems in the law

### Actual behavior

There is blockage in certain There is blocking in certain imagens, Independent of the work read.regardless of the work read. Certain images load normally, unlike others. 

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nomaxsnx** [comment]
Br: pra min está funcionando normalmente, tenta instalar o app chamado: "1.1.1.1" da cloudfare depois abre o app e inicia depois reiniciar o app e tenta de novo pra ver se funcionou

**Comment by DollynDeveloper** [comment]
> Br: pra min está funcionando normalmente, tenta instalar o app chamado: "1.1.1.1" da cloudfare depois abre o app e inicia depois reiniciar o app e tenta de novo pra ver se funcionou

Fiz o teste com a VPN, mas tá parecendo que meu IP foi bloqueado haha.

**Comment by nomaxsnx** [comment]
Eu tava lendo esse mangá 

![Screenshot_2024-05-19-21-45-53-350_app mihon](https://github.com/keiyoushi/extensions-source/assets/157644160/24ed3d77-2cb2-48e6-abdc-d932edb31d4d)

No decorrer da leitura acontece esse Error

![Screenshot_2024-05-19-21-43-45-688_app mihon](https://github.com/keiyoushi/extensions-source/assets/157644160/c7dda1fc-4756-4654-8c5a-644e53490fd0)

Quando eu vou em: "Webview"

Aparece isso

![Screenshot_2024-05-19-21-44-27-436_app mihon](https://github.com/keiyoushi/extensions-source/assets/157644160/c0ae3d83-0231-4bbc-98ae-83dd868105d9)


Aparentemente o cloudfare está bloqueando o acesso da leitura 

Só volta ao normal quando eu insisto em "tentar novamente" várias vezes e ae sim o manga volta

**Comment by GMak9** [comment]
Mude seu user-agent.

**Comment by HyungSilver** [comment]
> Eu tava lendo esse mangá
> 
> ![Screenshot_2024-05-19-21-45-53-350_app mihon](https://private-user-images.githubusercontent.com/157644160/331913151-24ed3d77-2cb2-48e6-abdc-d932edb31d4d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NTY4OTYsIm5iZiI6MTcxNjY1NjU5NiwicGF0aCI6Ii8xNTc2NDQxNjAvMzMxOTEzMTUxLTI0ZWQzZDc3LTJjYjItNDhlNi1hYmRjLWQ5MzJlZGIzMWQ0ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxNzAzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTllMmVlMGFjZjVjNWI2NGI1ODgwMTIxOGY4YTgwMGRlNDAxNGFlZDk4NzJlODYxMTNlMGI3YTQ1ZmRhNmUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FfOjqc7WoI1Pn0lmaPoGQNF6GIhjzj_cAiWe1AnzUgs)
> 
> No decorrer da leitura acontece esse Error
> 
> ![Screenshot_2024-05-19-21-43-45-688_app mihon](https://private-user-images.githubusercontent.com/157644160/331912997-c7dda1fc-4756-4654-8c5a-644e53490fd0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NTY4OTYsIm5iZiI6MTcxNjY1NjU5NiwicGF0aCI6Ii8xNTc2NDQxNjAvMzMxOTEyOTk3LWM3ZGRhMWZjLTQ3NTYtNDY1NC04YzVhLTY0NGU1MzQ5MGZkMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxNzAzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzkxYThhZGE4NGE4ZTdiYWRkYjEzYWEzYmVkNGUyOWEyNTg5MjcyMjRjNjYzMjQ0YTUyZDg2MjhiYjg1ZTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PE70syJBqmW0QDAuLVFgywjecmNo-cps-EOT_iSI8Us)
> 
> Quando eu vou em: "Webview"
> 
> Aparece isso
> 
> ![Screenshot_2024-05-19-21-44-27-436_app mihon](https://private-user-images.githubusercontent.com/157644160/331913048-c0ae3d83-0231-4bbc-98ae-83dd868105d9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NTY4OTYsIm5iZiI6MTcxNjY1NjU5NiwicGF0aCI6Ii8xNTc2NDQxNjAvMzMxOTEzMDQ4LWMwYWUzZDgzLTAyMzEtNGJiYy05OGFlLTgzZGQ4NjgxMDVkOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxNzAzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDkxODRkZDJiYTUzZWJiOWI5YTE2ZWUwNDkzZWFiNGUwYjM1NjJmM2VmODE3MDQxYjNjNzAyOWI3ZDRiZTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v9heBifx1yF7c4omNfAgZkv7fmH9MgJtSlLHNsO1-xA)
> 
> Aparentemente o cloudfare está bloqueando o acesso da leitura
> 
> Só volta ao normal quando eu insisto em "tentar novamente" várias vezes e ae sim o manga volta

mano isso só tá rolando no tachiyomi, no mihon da de ler legal só mudar o user agent

**Comment by HyungSilver** [comment]
recomendo migrar pra la, cria um backup antes e restaura no mihon

**Comment by nomaxsnx** [comment]
Então, como falarão que e pra mudar apenas os "user agent", podem fechar o "Issues".

**Comment by GMak9** [comment]
Se os problemas foram resolvidos com as soluções propostas recomendo fechar.

If the problems have been solved with the proposed solutions, I recommend closing.
