### ISSUE TITLE
Nexo não existe mais

### ISSUE THREAD

**Issue by HyungSilver** [keiyoushi/tachiyomi-extensions-source#3118]
### Source name

Nexo Scans

### Source language

Português (Brasil)

### Source link

nexoscans.net

### Other details

apagaram após a caça as bruxas

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by viminio** [comment]
Segundo eles eles pretendem voltar

**Comment by choppeh** [comment]
When the source returns, a new extension can be requested
