### ISSUE TITLE
Mangasco source link update

### ISSUE THREAD

**Issue by OleJehan98** [keiyoushi/tachiyomi-extensions-source#3121]
### Source information

MangaSco 1.4.38

### Source language

English

### Source new URL

Mgsco.org

### Other details

Just found it since it redirects me
![Screenshot_20240519-121024](https://github.com/keiyoushi/extensions-source/assets/127155940/3c5eb5b5-3cfc-4650-8344-05c880fd5f1d)
![Screenshot_20240519-121028](https://github.com/keiyoushi/extensions-source/assets/127155940/9ac611a8-1f61-413e-aef0-b4ad1ccf5fe8)

### Acknowledgements

- [X] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Laplace9** [comment]
Was about to open a ticket

**Comment by KiLLxSwitchZ** [comment]
When will it get fixed??

**Comment by Smol-Ame** [comment]
> When will it get fixed??

Everything is done & maintained by volunteers/contributors, there's no guarantee of a fix, just whenever someone has the time & is willing to propose a fix to the repo. Please be patient & don't comment unnecessarily unless you have additional info that could provide help to the issue.
