### ISSUE TITLE
Luminous Scans Chapter Update Bug

### ISSUE THREAD

**Issue by emukus** [keiyoushi/tachiyomi-extensions-source#3123]
### Source information

Luminous Scans 1.4.36

### Source language

English

### Steps to reproduce

Update entry for Legend of the Northern Blade

### Expected behavior

Show a new unread chapter, if new chapter exists
Do nothing, if no new chapter exists

### Actual behavior

The chapter titled "Chapter Return Date" is re-loaded & marked as a new unread chapter, despite having been uploaded back on Nov 6, 2022.

This behavior repeats itself periodically after a day or so no matter how many times you mark the chapter as read.

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 9

### Other details

I believe it has something to do with the site constantly changing the urls of its mangas as mentioned in https://github.com/keiyoushi/extensions-source/pull/44

My reason for the speculation is that the behavior does not occur every single time you update the title. So I assume it only happens if you update the manga after the url is changed yet again (which happens quite frequently, every 24hrs or so).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
it happens because they change urls often, nothing much we can do about it
