### ISSUE TITLE
early manga changed domain 

### ISSUE THREAD

**Issue by catalin1234532** [keiyoushi/tachiyomi-extensions-source#3125]
### Source information

earlymanga 1.4.21

### Source language

english

### Source new URL

https://earlym.org/home

### Other details

If i open webview it redirects me to the right one, but in app the library says "no Results fiind"
the changed was earlycomic.com to earlym.org

### Acknowledgements

- [X] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by catalin1234532** [comment]
![Screenshot_2024-05-19-10-02-25-633_com google android packageinstaller](https://github.com/keiyoushi/extensions-source/assets/127130874/21715ecd-2f60-4818-9aa7-ae68e25efec8)
![Screenshot_2024-05-19-10-02-36-262_eu kanade tachiyomi](https://github.com/keiyoushi/extensions-source/assets/127130874/36e493ac-52a4-48a8-a392-f9dfedb2a21e)
![Uploading Screenshot_2024-05-19-10-03-02-001_eu.kanade.tachiyomi.jpg…]()

**Comment by Smol-Ame** [comment]
Works on my end, at least loading up the entries & chapter list inside the app/source. What is your current EarlyManga extension version number?

Also, check your WebView for any extra info/errors, and also note that they are just coming out maintenance. A quick browse over their site, they have some broken chapters/pages in titles, so don't expect it all to be running smooth for now.

**Comment by catalin1234532** [comment]
my version is 1.4.21, also on webview i dont have any errors but in app it doesnt work.
i dont expect to run smoth, i want to work partially at least.
thanks for a quick answer and i am sorry for grammatical mistakes, english is not my first language.
![Uploading Screenshot_2024-05-19-10-03-02-001_eu.kanade.tachiyomi.jpg…]()

**Comment by catalin1234532** [comment]
![Screenshot_2024-05-19-10-33-45-163_eu kanade tachiyomi](https://github.com/keiyoushi/extensions-source/assets/127130874/1b6cef71-7c00-4261-aaf4-34b3d5136273)

**Comment by catalin1234532** [comment]
![Screenshot_2024-05-19-10-35-42-091_eu kanade tachiyomi](https://github.com/keiyoushi/extensions-source/assets/127130874/c0cf267a-68bb-4f81-99a3-867c8c6670c9)

**Comment by Smol-Ame** [comment]
Are you sure you're using our extensions, or did you get the extension version number incorrectly?

Our EarlyManga is currently 1.4.27, and from the background of your Extensions tab screenshot, it seems you are severely out of date for most of your extensions compared to our repo's version of the same extensions.

**Comment by catalin1234532** [comment]
![Screenshot_2024-05-19-10-41-50-979_eu kanade tachiyomi](https://github.com/keiyoushi/extensions-source/assets/127130874/0db978df-49c3-4384-9478-d989f7e9d892)
![Screenshot_2024-05-19-10-40-17-655_eu kanade tachiyomi-edit](https://github.com/keiyoushi/extensions-source/assets/127130874/14564a19-5fc5-47c8-81b4-27fb1ea0947e)
i dont know, i may done Something wrong when i started using repos

**Comment by Smol-Ame** [comment]
I think I know what's going on. I believe you still have the old Tachiyomi version of the extensions installed, which conflicts with our version of the same extensions. Please uninstall your extensions & reinstall them again in the app, which will install our version instead.

If you have any questions about this, or need additional help, please reach out in the Keiyoushi Discord server, in the repo-support channel.

**Comment by catalin1234532** [comment]
i will try what You said

**Comment by catalin1234532** [comment]
it is working but i will need tot migrate everything, thank you for your help.

**Comment by Smol-Ame** [comment]
> it is working but i will need tot migrate everything, thank you for your help.

Nice, just another friendly reminder that you need to uninstall all your old extensions & install the same extensions again, or those extensions won't update correctly.
