### ISSUE TITLE
MangaGezgini Download

### ISSUE THREAD

**Issue by Rip0000** [keiyoushi/tachiyomi-extensions-source#3164]
### Source information

MangaGezgini 1.4.38

### Source language

turkish

### Steps to reproduce

I get an error when downloading episodes of the series

### Expected behavior

I get an error when downloading episodes of the series

### Actual behavior

I get an error when downloading episodes of the series

### Mihon/Tachiyomi version

Tachiyomi 0.15.3

### Android version

android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Well since the expected and actual behaviour is the same there is no error right?

**Comment by Norsze** [comment]
If this is cloudflare you are better off asking in our discord as Cloudflare generally has no permanent "fix"

**Comment by AwkwardPeak7** [comment]
?blurb cf
