### ISSUE TITLE
Add NetTruyen (unoriginal) : NetTruyenLoli

### ISSUE THREAD

**Issue by haruki-takeshi** [keiyoushi/tachiyomi-extensions-source#3190]
### Source name

NetTruyenLoli

### Source link

https://nettruyenloli.com

### Source language

Vietnamese

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by haruki-takeshi** [comment]
Due to NetTruyen original site currently down, after checking, this source is better performance until now.

**Comment by haruki-takeshi** [comment]
please help to add this asap.

**Comment by haruki-takeshi** [comment]
please arrange to add this location soon.

**Comment by Smol-Ame** [comment]
Don't comment bump unless you have extra info that could help a contributor out. If a contributor has the time & is willing to work on it, it'll be worked on.

**Comment by dominhhieu1405** [comment]
Changed to NetTruyenSSR.com

**Comment by vetleledaal** [comment]
The site in the original request (nettruyenloli.com) appears to be blank, so I'm closing this issue.

@dominhhieu1405 
Since all these `nettruyen**` sites are clones of each other it would be better to create a separate issue for this.
