### ISSUE TITLE
Newtoki Unable to update and read chapters

### ISSUE THREAD

**Issue by FengTeLai** [keiyoushi/tachiyomi-extensions-source#3196]
### Source information

Newtoki 1.4.32

### Source language

Korean

### Steps to reproduce

Updated chapters
Can't bypass cloudflare

### Expected behavior

updates and readings

### Actual behavior

Cloudflare passes validation
But can't update chapters and read in the app

https://github.com/keiyoushi/extensions-source/assets/117538601/6c0363d3-91e9-4e46-97ef-4c4cf97f6d74

![Screenshot_20240523_141715_eu kanade tachiyomi](https://github.com/keiyoushi/extensions-source/assets/117538601/a573d796-0af3-464a-883a-13766267b868)

### Mihon/Tachiyomi version

0.15.3

### Android version

HarmonyOS 4.0

### Other details

Huawei phone

Using User Agents

Mozilla/5.0 (Linux; Android 10; HD1913) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.72 Mobile Safari/537.36 EdgA/124.0.2478.104

Still can't update chapters and read chapters

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FengTeLai** [comment]
Now that the webview is validated by cloudflare
But the in-app is still not updating chapters and reading them

**Comment by Smol-Ame** [comment]
Just curious, works fine on my end. Try migrating that title back into NewToki to see if it updates the info. I don't use this source or know Korean, but it seems your title/version of the title, the first letter is missing a stroke compared to the one I found on the extension.

**Comment by FengTeLai** [comment]
@Smol-Ame 
All works of newtoki can not be viewed and updated.
Verification result is a problem with Huawei mobile browser, every page has to be verified once cloudflare
Other browsers only need to verify once and can read and update normally
The app can't change the default browser, so when you click on the webview, you can only jump through the Huawei browser。
this problem can't be solved now.
