### ISSUE TITLE
Mangafreak is broken 

### ISSUE THREAD

**Issue by sofari23** [keiyoushi/tachiyomi-extensions-source#32]
### Source information

Mangafreak 1.4.9

### Source language

English 

### Steps to reproduce

1. Navigate to mangafreak extension
2. Try reading any manga/manhwa in app or WebView 

### Expected behavior

You should be able to read manga

### Actual behavior

Instead am stuck on endless cloudfare loop

### Tachiyomi version

0.15.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by C0rvidae** [comment]
Tried it, [Cloudflare error](https://tachiyomi.org/docs/guides/troubleshooting/#cloudflare)
```
Did these methods not work?
Wait for the source to lower its protection or switch to different sources.
```

**Comment by sofari23** [comment]
It's been that way the whole of last year

**Comment by NotNeko-Chan** [comment]
I got stuck in the Cloudflare loop a while ago.

Try changing your default user agent string.

Search google for "What is my user agent string?"

Paste the result into the box in Settings -> Advanced -> Networking

**Comment by beer-psi** [comment]
Refer to the **Solving Cloudflare issues** section at https://tachiyomi.org/docs/guides/troubleshooting/#cloudflare. If it doesn't work, migrate to other sources or wait until they lower their protection.
