### ISSUE TITLE
KissLove HTTP404

### ISSUE THREAD

**Issue by Kimio318** [keiyoushi/tachiyomi-extensions-source#3200]
### Source information

KissLove 1.4.14

### Source language

Japanese

### Steps to reproduce

1.“Browse”-"Sources"-"KissLove - Latest"-Random click a manga
2.Refresh the manga chapter list
3.Show“Http404, check website in WebView”
4.Enter"WebView", Normally display webpage for the manga, and reading the latest chapter.

### Expected behavior

The latest chapters should have appeared after refreshing。

### Actual behavior

Show“Http404, check website in WebView”

### Mihon/Tachiyomi version

Mihon beta r6697 and Tachiyomi Preview r6421

### Android version

Android 13

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #3197

Search existing issues before opening a new issue, and acknowledging that you did
