### ISSUE TITLE
MangaTak : It converts to an anime site

### ISSUE THREAD

**Issue by OtakuArab** [keiyoushi/tachiyomi-extensions-source#3202]
### Source name

MangaTak 

### Source language

Arabic

### Source link

https://mangatak.com

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
Redirect to https://arabanimeranker.com/
```
HTTP/1.1 302 Moved Temporarily
CF-RAY: 8898209a0b3a2564-GIG
Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection: keep-alive
Content-Length: 143
Content-Type: text/html
Date: Sat, 25 May 2024 20:03:11 GMT
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Location: https://arabanimeranker.com/
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=59Vq8gN9OOANSsiYtkwpDjrBEzESy%2BCgep3YJLRMqHSe2FEBVvS88rx3JidLj69fiCIkcQV22WvO1Uzf7yol7OoJ8tAkE1Hfl72kn8JzcAgj3whZekG3ANlcycXGUM4%3D"}],"group":"cf-nel","max_age":604800}
Server: cloudflare
Vary: Accept-Encoding
alt-svc: h3=":443"; ma=86400

```
