### ISSUE TITLE
Kisslove

### ISSUE THREAD

**Issue by Tato1995a** [keiyoushi/tachiyomi-extensions-source#3206]
### Source information

Kisslove 1.4.14

### Source language

Japanese

### Steps to reproduce

1 Upgraded 
2 The following error is displayed
![Screenshot_20240523_185554_HTML Viewer](https://github.com/keiyoushi/extensions-source/assets/167379963/8c44d146-4848-487c-8711-add940ad6d6f)

### Expected behavior

Updates normally

### Actual behavior

Error in the update
![Screenshot_20240523_185554_HTML Viewer](https://github.com/keiyoushi/extensions-source/assets/167379963/784cf722-e795-41dd-9773-db978a923d9b)

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #3197

Search the existing issues first before opening a new one, and acknowledging that you did
