### ISSUE TITLE
Webtoon Hatti download issue

### ISSUE THREAD

**Issue by hasanturkylmz** [keiyoushi/tachiyomi-extensions-source#3212]
### Source information

Webtoon Hatti 1.4.38

### Source language

Turkish

### Steps to reproduce

I can read the chapter normally, but when I get to the end of the chapter it shows the error "The image couldn't be loaded". This does not prevent me from reading, but when I try to download the chapters, the download cannot be completed and gives an error.

### Expected behavior

Episodes should be downloaded without error.

### Actual behavior

It gives an error at the end of the download and the download does not complete.

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 14

### Other details

![Screenshot_20240524_162235_Mihon](https://github.com/keiyoushi/extensions-source/assets/83721178/983099b5-1c31-4225-8e92-1b83f2fd1c0c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
They deliberately put fake images to mess with Mihon/tachiyomi/Hakuneko. Its most likely the same problem all over again.
