### ISSUE TITLE
Nettruyen [Domain Change[

### ISSUE THREAD

**Issue by victay44** [keiyoushi/tachiyomi-extensions-source#3227]
### Source information

Nettruyen 1.4.35

### Source language

Vietnamese

### Steps to reproduce

1/ Install Nettruyen extension from the repo.
2/ Cannot access nettruyen or add titles because its domain (nettruyentt.com) is down.

### Expected behavior

Can add titles normally.

### Actual behavior

Nettruyentt.com is down but a new domain is back, nettruyencc.com
please help to update the extension to the new domain. Thanks .

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
nettruyencc is a copycat site. Refer to discussion in #2887
