### ISSUE TITLE
SlimeRead Could Not Find Script URL (WebView Normal)

### ISSUE THREAD

**Issue by Padahjj** [keiyoushi/tachiyomi-extensions-source#3234]
### Source information

SlimeRead 1.4.9

### Source language

Portuguese

### Steps to reproduce

1. Open the extension
2. Look for the work
3. The error appears

### Expected behavior

The works should appear.

### Actual behavior

The error "Could Not Find Script URL" appears.
![20240525_212415](https://github.com/keiyoushi/extensions-source/assets/87540723/9f4da70f-1040-4cf1-a149-1bd8dc3cc56c)

### Mihon/Tachiyomi version

TachiJ2K 1.7.4

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Open WebView and pass the cloudflare challenge

**Comment by Padahjj** [comment]
> Open WebView and pass the cloudflare challenge

I try to pass it and it keeps loading infinitely.

**Comment by bapeey** [comment]
Referer to cloudflare section in the [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/#cloudflare)

**Comment by Padahjj** [comment]
> Referer to cloudflare section in the [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/#cloudflare)

I have the user agent, I changed it to the latest one last week.

**Comment by bapeey** [comment]
keep trying, you can try using your browser user agent from this [link](https://www.whatismybrowser.com/detect/what-is-my-user-agent/). If nothing works wait for the source to lower its protection or use other sources

**Comment by Padahjj** [comment]
> keep trying, you can try using your browser user agent from this [link](https://www.whatismybrowser.com/detect/what-is-my-user-agent/)
okay, I'll keep trying, thank you :)
