### ISSUE TITLE
Request to add "Champion Cross" as a new source (originally Manga Cross)

### ISSUE THREAD

**Issue by RekhytsSlippers** [keiyoushi/tachiyomi-extensions-source#3246]
### Source name

チャンピオンクロス

### Source link

https://championcross.jp/

### Source language

Japanese

### Other details

Site migrated from Manga Cross to Champion Cross

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #2532 

Search the existing issues before opening a new issue, and acknowledging that you did.
