### ISSUE TITLE
PewPice : Dead Source

### ISSUE THREAD

**Issue by OtakuArab** [keiyoushi/tachiyomi-extensions-source#3249]
### Source name

PewPice

### Source language

Arabic

### Source link

https://pewpiece.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
The source is under maintenance. 

Is there any other information?
