### ISSUE TITLE
Manga lek

### ISSUE THREAD

**Issue by Mohamed9789** [keiyoushi/tachiyomi-extensions-source#3251]
### Source information

Mangalek مانجا ليك

### Source language

Arabic 

### Steps to reproduce

I keep getting banned and unbanned from mangalek even if i didn't open the extension.
And if i wanna read or download something, i can access few chapters then it asks to solve captcha .
The problem solves for a short period and then comes back again.
Sometimes manhwa doesn't get updated, and i get the message "there no chapters in this source" 
Or something with the context
![Screenshot_2024-05-26-16-32-40-38_551f7f0ca926862b368845ce7ee433aa](https://github.com/keiyoushi/extensions-source/assets/66431487/326b72a3-1c5b-424c-baa4-3394ef899067)

### Expected behavior

The extension to work properly!

### Actual behavior

I keep getting banned and unbanned from mangalek even if i didn't open the extension.
And if i wanna read or download something, i can access few chapters then it asks to solve captcha .

### Mihon/Tachiyomi version

0.16.5

### Android version

13

### Other details

I hope you can find a solution for my problem.
Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
?blurb cf

**Comment by Mohamed9789** [comment]
Ok, i will try 
Thanks
