### ISSUE TITLE
mangaworld extension change url

### ISSUE THREAD

**Issue by L4stix** [keiyoushi/tachiyomi-extensions-source#326]
### Source information

mangaworld 1.4.7

### Source language

italian

### Source new URL

https://www.mangaworld.ac/

### Other details

They change urls often so there is a need to check every 2/3 months

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TheZ3ro** [comment]
This domain is already expired it seems

**Comment by vetleledaal** [comment]
> This domain is already expired it seems

Seems fine to me, maybe your ISP is blocking the site? Or the site is blocking you.

https://archive.ph/t76m2

**Comment by TheZ3ro** [comment]
Now it seems to be working fine!
