### ISSUE TITLE
Manhastro lento no carregamento das paginas

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#3265]
### Source information

Manhastro 1.4.41

### Source language

Português (Brasil)

### Steps to reproduce

demorando para carregar as páginas das obras que estou lendo, as vezes o capítulo volta pro início do nada enquanto você está lendo 

é só essa extensão que tá dando esse problema 

### Expected behavior

Carrega normalmente

### Actual behavior

.

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 11

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by GMak9** [comment]
It is possibly being shut down by an operation by Brazil's public prosecutor's office and federal police. Operation 404.
