### ISSUE TITLE
Update Remanga (ExRemanga)

### ISSUE THREAD

**Issue by Bloodhaod** [keiyoushi/tachiyomi-extensions-source#3268]
### Source information

"1.4.86"

### Source language

"RU"

### Steps to reproduce

1. Открытие любой манги с расширения remang
2. Открытие главы
3. Вместо главы, показывает изображение о том что надо обновить ExManga
![Screenshot_2024-05-28-10-08-45-61_a603e4da04bada03cae438f177815547](https://github.com/keiyoushi/extensions-source/assets/64723873/7824661e-fb2d-4f6b-95de-07d6f61923b3)

### Expected behavior

Открывается глава с изображением иллюстраций

### Actual behavior

Глава не показывает пишет что надо установить последнюю версию ExManga

### Mihon/Tachiyomi version

App version: 1.10.5 (TachiyomiSY)

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
The Remanga (RU) extension is no longer supported within this repository & won't be added back [due to legal reasons](https://github.com/github/dmca).

Migrate your titles to a different source.
