### ISSUE TITLE
Could you please add epub format support for komga extension?

### ISSUE THREAD

**Issue by beavermarine** [keiyoushi/tachiyomi-extensions-source#3270]
### Source name

komga

### Source language

all

### Describe your suggested feature

Komga server have already support the epub format, but komga extension still only support zip/cbz format now. Could you please add epub format support for komga extension?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
The Komga extension already supports ePubs, but only epubs that only have images in them. ePubs with text are not supported and will not be supported.
