### ISSUE TITLE
Request manga.ovh

### ISSUE THREAD

**Issue by maxmoroz97** [keiyoushi/tachiyomi-extensions-source#3276]
### Source name

manga.ovh

### Source link

https://manga.ovh/

### Source language

"Russian"

### Other details

Don't have 18+
NSFW (blood?) - yes 

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by e-shl** [comment]
The owner site's forbade adding this source

**Comment by maxmoroz97** [comment]
Thank you for your interest and for asking about the possibility of adding a site 
Have a nice day
