### ISSUE TITLE
Manga-Mate cannot pass verification in webview

### ISSUE THREAD

**Issue by ZerOri** [keiyoushi/tachiyomi-extensions-source#3286]
### Source information

Manga-Mate 1.4.31

### Source language

Japanese

### Steps to reproduce

I find that the extension cannot pass the webview verification under normal circumstances, and prompts that the verification failed. However, if I open [**manga-mate.org**](url) in the webview of a browser or other app, it can pass the verification normally. What's going on? Is mihon's webview targeted by the website?Does anyone know the cause of the problem?

### Expected behavior

Verification succeeded in webview

### Actual behavior

Verification failed in webview

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

android 13

### Other details

1.[**manga-mate.org**](url) extension does not require webview verification when logging in with Japanese nodes.
2.Customizing the user agent in the extended settings will not pass the verification, but if you set mihon's user agent to the mobile user agent, it can work as well.But this will cause another extension I'm using to stop working.
3.Of the dozen or so extensions I use, only manga mate does this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Works fine on my end.

* If you open WebView & see a giant warning saying that you're blocked, you might need to use a VPN to bypass to region block
* Afterwards, or if you only see a Cloudflare verification checkbox, check it & see if it passes and loads the source's website
* If it doesn't load, change your user-agent (Mihon Settings > Advanced)
 * Search up "latest user-agent"
 * Copy and paste any user-agent into your Mihon app
 * Restart the app & try passing WebView verification again
 * If it doesn't work, redo the process till it works (do not limit yourself to any OS, browser, device, or amount of UAs, keep changing till it works)

For more help, please reach out in the Keiyoushi Discord repo-support channel.
