### ISSUE TITLE
flix scans issues 

### ISSUE THREAD

**Issue by Rasun0** [keiyoushi/tachiyomi-extensions-source#3287]
### Source information

Flix scans 1.4.6

### Source language

English 

### Steps to reproduce

flix scans extension is showing an error of http 404 even after finishing what it says it doesn't solved .
![Screenshot_20240529_085226](https://github.com/keiyoushi/extensions-source/assets/139698115/c3e39bbd-5465-49b4-beea-e928ea852be4)
even after doing what it sat webview it doesn't solved not for one title but all titles it's showing that .
![Screenshot_20240529_081814](https://github.com/keiyoushi/extensions-source/assets/139698115/5070d140-c4aa-48a8-8acc-d23e5c7ee775)
but when we visit website it's OK no issues works fine 
![Screenshot_20240529_085305](https://github.com/keiyoushi/extensions-source/assets/139698115/891df693-0b99-4aba-9573-13b7f4fa8cf5)
![Screenshot_20240529_085516](https://github.com/keiyoushi/extensions-source/assets/139698115/5fa7a23e-3e94-4797-b5a7-6c3602b9bb5b)

### Expected behavior

it should show and work as It was working normal showing chapter instead of error . after clicking on titles and should show list of chapters like this 
![Screenshot_20240529_085930](https://github.com/keiyoushi/extensions-source/assets/139698115/bac6f202-2fc5-43d0-b04b-929106e99496)

### Actual behavior

but it's instead of showing chapter list it's showing error 404 
![Uploading Screenshot_20240529_085226.jpg…]
like this .

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

it's showing an error in it's all titles but working fine in webview 
![Screenshot_20240529_085305](https://github.com/keiyoushi/extensions-source/assets/139698115/6ab1bb7d-6e48-4f9e-9796-f42a247c1498)
![Screenshot_20240529_085226](https://github.com/keiyoushi/extensions-source/assets/139698115/e8136e70-57bd-4c8b-8b02-3db27cd9f663)
![Screenshot_20240529_085516](https://github.com/keiyoushi/extensions-source/assets/139698115/a011ab85-7890-4614-bf2e-376e7ba6a4f4)
![Screenshot_20240529_081814](https://github.com/keiyoushi/extensions-source/assets/139698115/77220a4c-37a2-4fc2-ac1d-c5feb807a221)
![Screenshot_20240529_081814](https://github.com/keiyoushi/extensions-source/assets/139698115/f976f73d-f150-4ac0-8101-e19d643ce606)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Rasun0** [comment]
flix scans domain changed https://ayoub-zrr.xyz/
to https://flixscans.net/

**Comment by vetleledaal** [comment]
Closing in favor of #3540
