### ISSUE TITLE
Mangas no sekai

### ISSUE THREAD

**Issue by Tato1995a** [keiyoushi/tachiyomi-extensions-source#3301]
### Source information

Mangas No Sekai 1.4.50

### Source language

Spanish

### Steps to reproduce

1 The library is updated
2 An error occurs during the update.
3 The title that causes the error is opened and has the following error message
![Screenshot_20240529_225742_HTML Viewer](https://github.com/keiyoushi/extensions-source/assets/167379963/115cf08b-8709-4b2a-a45f-fcc2bb7441ee)

### Expected behavior

The library is updated normally

### Actual behavior

The following error is displayed
![Screenshot_20240529_225742_HTML Viewer](https://github.com/keiyoushi/extensions-source/assets/167379963/bde4e7da-b5a4-4274-937d-63d2fe15453c)

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Site API is down right now
![image](https://github.com/keiyoushi/extensions-source/assets/90949336/a09d5d1d-36c8-4b5c-8ed9-aee67f6c1f43)

**Comment by Proxy-E23** [comment]
> Site API is down right now
> ![image](https://github.com/keiyoushi/extensions-source/assets/90949336/a09d5d1d-36c8-4b5c-8ed9-aee67f6c1f43)
> 

![Screenshot_20240530-202833_Mihon.png](https://github.com/keiyoushi/extensions-source/assets/79614894/2114ca12-f3c8-49a0-9d21-e87cbeb09a2f)

In webview works fine

![Screenshot_20240530-202848_Mihon.png](https://github.com/keiyoushi/extensions-source/assets/79614894/875a46d5-2859-4a63-b46a-ac088911939c)

**Comment by bapeey** [comment]
It seems like their API rejects non logged users, create an account and log in in WebView

**Comment by Proxy-E23** [comment]
> It seems like their API rejects non logged users, create an account and log in in WebView

You are right, when i log is solved

**Comment by Athrun0311** [comment]
Thanks
