### ISSUE TITLE
COMIC FUZ

### ISSUE THREAD

**Issue by jn1106** [keiyoushi/tachiyomi-extensions-source#3306]
### Source name

COMIC FUZ

### Source link

https://comic-fuz.com/

### Source language

Japanese

### Acknowledgements

- [x] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
Dev hints : Protobuf with POST method, AES encrypted pictures, API
