### ISSUE TITLE
HentaiRead "Stop This image was hotlinked" issue

### ISSUE THREAD

**Issue by shuukenji92** [keiyoushi/tachiyomi-extensions-source#3307]
### Source information

HentaiRead 1.4.41

### Source language

English

### Steps to reproduce

1. Press any Manga that has the HentaiRead extension can be in the Extension Browser or own Saved Catalog (except downloaded)
2. Choose any chapter of the Manga/Doujin to read

### Expected behavior

Would be able to read said Chapter or Manga

### Actual behavior

Accessable but "Stop This image was hotlinked" in both the Saved Catalog and on the Extension search appears.

![Screenshot_2024-05-30-11-18-43-94_afd66b7916d19a60815f56273408b73e](https://github.com/keiyoushi/extensions-source/assets/86971859/96385d00-20c9-413e-9922-fbe6af1e7c61)

### Mihon/Tachiyomi version

Mihon 0.15.3 and used others like Tachiyomi [OG], Tachiyomi Sy and etc. for cross reference

### Android version

Android 10

### Other details

- Accessed it yesterday it was fine.
- I have accessed it via both the site and Webview both are accesible and its extension can be saved viewed and read like a normal chapter but images are all replaced by"Stop This image was hotlinked" 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
Got that randomly on covers too. Its because the CDN dont like having a referrer for fetching images. Make the request looks like its a browser fetching an \<img> tag 😉 .

**Comment by shuukenji92** [comment]
> Got that randomly on covers too. Its because the CDN dont like having a referrer for fetching images. Make the request looks like its a browser fetching an <img> tag 😉 .

So is it a bug or can it be bypassed or what? Im genuinely curious on what actually caused that suddenly
