### ISSUE TITLE
Lura Toon: Add Deep link: "/static/".

### ISSUE THREAD

**Issue by nomaxsnx** [keiyoushi/tachiyomi-extensions-source#3316]
### Source name

Lura Toon

### Source language

Português

### Describe your suggested feature

Lura Toon has 2 private links:: https://lura-toons.com/static/def7fcbd-ef0f-4e05-80d8-ee2d05478946/ and https://lura-toons.com/static/f1c5d3bf-acd7-442d-b467-da6f835ca732/

I would like you to make a link capture in: “/static/”, every Saturday or Sunday they change the “URL” to prevent the ADMCA of the dos manhua mentioned above.

I would like you to add a manual support, in the settings to change the url manually, because there is no way to do it automatically.

obs: to access the site, it has to be a brazilian vpn.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
~you can manually put `slug:static/f1c5d3bf-acd7-442d-b467-da6f835ca732` in the search bar~

**Comment by nomaxsnx** [comment]
> you can manually put `slug:static/f1c5d3bf-acd7-442d-b467-da6f835ca732` in the search bar

oooh, thanks, it's going to be a pain, changing all the time.

**Comment by AshbornXS** [comment]
using that slug method only half works, it founds the thing you are searching and its possible to update it and add to your library, but when you try to open a chapter it changes the url to an invalid one, maybe isn't a problem with the extension but the website? bcz using a normal browser it works just fine

if helps, its changing the url from: `/static/f1c5d3bf-acd7-442d-b467-da6f835ca732/[chapter number here]/`
to: `/e58c89bc-b63f-4c6d-bdc7-8542cd9948b11/[chapter number here]/`
