### ISSUE TITLE
Lag When Scrolling 

### ISSUE THREAD

**Issue by Kenn876** [keiyoushi/tachiyomi-extensions-source#3317]
### Source information

Surya Scans 1.4.33, Manhwa Freak 1.4.36

### Source language

English

### Steps to reproduce

1. Go to Surya Scans or Manhwa Feak
2. Select "The Villainous Warrior" manhwa
3. Choose chapters 38 to 40

### Expected behavior

Should scroll down smoothly 

### Actual behavior

When you scroll down it lags in certain spots. If yo keep scrolling back to the spots it lags a lot.

### Mihon/Tachiyomi version

Tachiyomi 0.15.3

### Android version

Android 12

### Other details

Only happens when you read in long strips and long strips with gaps. There is no issue with the wifi when it happened.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
Download the chapter with "split tall images" option.

This happens because the images on website are too long. Plus this is app issue

**Comment by Kenn876** [comment]
> Download the chapter with "split tall images" option.
> 
> This happens because the images on website are too long. Plus this is app issue

How do I down loading using split tall images option? I've never encountered this kind of problem so I wasn't sure what to do.

**Comment by Kenn876** [comment]
> > Download the chapter with "split tall images" option.
> > This happens because the images on website are too long. Plus this is app issue
> 
> How do I down loading using split tall images option? I've never encountered this kind of problem so I wasn't sure what to do.



> > Download the chapter with "split tall images" option.
> > This happens because the images on website are too long. Plus this is app issue
> 
> How do I down loading using split tall images option? I've never encountered this kind of problem so I wasn't sure what to do.

Where can I find the split image download option?

**Comment by AwkwardPeak7** [comment]
In the downloads settings....

Come to our discord if you need further help

**Comment by Kenn876** [comment]
> In the downloads settings....
> 
> Come to our discord if you need further help

I found it thanks for the help
