### ISSUE TITLE
Lura Toon: Domain Change

### ISSUE THREAD

**Issue by AshbornXS** [keiyoushi/tachiyomi-extensions-source#3320]
### Source information

Lura Toon 1.4.50

### Source language

Brazilian Portuguese

### Source new URL

https://luratoons.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by EvaldoCeBr** [comment]
![Screenshot_2024-06-01-11-53-27-585_app mihon debug](https://github.com/keiyoushi/extensions-source/assets/169321265/4886d34b-a0b5-4573-acaf-480b6f0c2d3a)
![Screenshot_2024-06-01-11-54-02-525_com android chrome](https://github.com/keiyoushi/extensions-source/assets/169321265/b56c88fe-f5ae-4e9b-91a3-4defd8aa09f6)
