### ISSUE TITLE
Nexoscan, lermanga and gekkouscan

### ISSUE THREAD

**Issue by EnzooFelixDev** [keiyoushi/tachiyomi-extensions-source#3322]
### Source name

nexoscan, lermanga, gekkouscan

### Source language

Brazilian Portuguese - Português (Brasil)

### Source link

Doesnt have, the website is down

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Search the existing issues, both open & closed, before making an issue request & acknowledging that you did. Also, try to separate issues per source, but in this case:

Nexo - Read #3118 & make a source request if they are back online
Lermanga - Apparently was DMCA'd, see #2611
Gekkou Scans - Apparently they shut down, see #2587

**Comment by EnzooFelixDev** [comment]
Thanks
