### ISSUE TITLE
Demon Sect: No Results founded

### ISSUE THREAD

**Issue by EnzooFelixDev** [keiyoushi/tachiyomi-extensions-source#3324]
### Source information

Demon Sect 1.4.42

### Source language

Brazilian Portuguese - Português (Brasil)

### Steps to reproduce

1. Click in the "Demon Sect" extension font

### Expected behavior

Normally, all from this scan appear 

### Actual behavior

![Screenshot_20240531_182810_Mihon](https://github.com/keiyoushi/extensions-source/assets/171385042/fdb3101a-8f06-44bb-a79c-717eab55ee85)

Dont appear

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Gutis-007** [comment]
Currently, to use the website you need to log in to the website, to resolve this in the app, just open the webview, log in and return to the APP and it will work

**Comment by HyungSilver** [comment]
é só fazer login depois voltar que resolve
