### ISSUE TITLE
Night Scans missing? 

### ISSUE THREAD

**Issue by Azurelightpkk** [keiyoushi/tachiyomi-extensions-source#3344]
### Source information

Night scans

### Source language

English

### Steps to reproduce

The source tab? 

### Expected behavior

Night Scans to be available 

### Actual behavior

Missing Night Scans extension

### Mihon/Tachiyomi version

Tachiyomi YS 1.10.2

### Android version

Android 14

### Other details

The extension used to be available but it has suddenly disappeared from the source list. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Night scans is in the [repo](https://keiyoushi.github.io/extensions/#en.nightscans). If you can't find it in your app that is not our problem really, since it exists in the repo.

If you need help finding it go to the Discord.
