### ISSUE TITLE
SlimeRead erro

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#3348]
### Source information

SlimeRead 1.4.10

### Source language

Português (Brasil)

### Steps to reproduce

![Screenshot_20240601-230601](https://github.com/keiyoushi/extensions-source/assets/157044539/449b9cab-18f4-48e6-80ab-bea2847c2527)

### Expected behavior

.

### Actual behavior

.

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 11

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Site is down

**Comment by nomaxsnx** [comment]
website this maintenance

**Comment by nomaxsnx** [comment]
After you come back, I recommend that you join their discord to follow the warnings

**Comment by ghost** [comment]
Tá off não![Screenshot_20240602-033918](https://github.com/keiyoushi/extensions-source/assets/157044539/d14f8b69-2d43-494a-a677-8b8290a98152)
