### ISSUE TITLE
Lura Toon Private Links

### ISSUE THREAD

**Issue by AshbornXS** [keiyoushi/tachiyomi-extensions-source#3358]
### Source information

Lura Toon 1.4.52

### Source language

Brazilian Portuguese

### Steps to reproduce

1. Install the extension
2. Open the phone settings page of the extension app
3. Give the deep link access to the extension
4. Open `https://luratoons.com/static/f1c5d3bf-acd7-442d-b467-da6f835ca732/` using Mihon
5. Try opening any chapter

### Expected behavior

It should open the chapter going through the urls

### Actual behavior

It gets stuck at `https://luratoons.com/e58c89bc-b63f-4c6d-bdc7-8542cd9948b11/[chapter number here]/`, apparently that url should redirect you to `https://luratoons.com/static/f1c5d3bf-acd7-442d-b467-da6f835ca732/[chapter number here/` but on the extension it gets stuck

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Other details

commented about that on #3316, there was marked as closed with a pull request but that didn't fixed the issue, just basically removed the slug method

maybe that is a problem with the website itself, I just want some clarification if is something fixable or not, or maybe if I'm just being dumb and doing something wrong

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
looks like full manga url as referer is needed for chapter url to not return 404

**Comment by AshbornXS** [comment]
build myself to try and that worked just fine! thank you
