### ISSUE TITLE
Dream Scan: bad locale used (pt-br -> pt-BR)

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#3362]
### Source information

Portuguese Brazilian

### Source language

Portuguese

### Steps to reproduce

One of the font options is with one font only and the rest are in the other option.
![Screenshot_2024-06-02-11-41-51-847_app mihon](https://github.com/keiyoushi/extensions-source/assets/169321265/6113010c-2ca1-47de-a398-468ba82c1fc2)
![Screenshot_2024-06-02-11-42-25-959_app mihon](https://github.com/keiyoushi/extensions-source/assets/169321265/d501f103-7f3b-440c-b48b-bb3d1022311e)
![Screenshot_2024-06-02-11-44-51-162_app mihon](https://github.com/keiyoushi/extensions-source/assets/169321265/f07c44d1-cf25-4a37-ac1b-5155a0dfc44d)

### Expected behavior

All fonts in Brazilian Portuguese should be together.

### Actual behavior

One font stands alone in the options.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
App issue, report to them

**Comment by AwkwardPeak7** [comment]
turns out it was a little oopsie on our end
