### ISSUE TITLE
Source Argos Comics, it doesn't open the popular tab, just the recent one.

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#3363]
### Source information

Argos Comics 1.4.37

### Source language

Portuguese Brazilian 

### Steps to reproduce

An error message appears when trying to open. Opens only through WebView.
![Screenshot_2024-06-02-12-40-51-975_app mihon debug](https://github.com/keiyoushi/extensions-source/assets/169321265/f3660651-fb39-42f9-b939-90d252cd4f2f)
![Screenshot_2024-06-02-12-40-59-475_app mihon debug](https://github.com/keiyoushi/extensions-source/assets/169321265/9ab64ff7-8189-4bbd-a2b2-ce7b3af59cc1)

### Expected behavior

I expected it to show the content of the site.

### Actual behavior

An error message only appears.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by HyungSilver** [comment]
![Screenshot_20240602_112405_Mihon](https://github.com/keiyoushi/extensions-source/assets/98929917/eb8f6b1d-e79c-4023-b605-ef9d6218d79b)
tá normal aqui

**Comment by EvaldoCeBr** [comment]
Voltou aqui!

**Comment by EvaldoCeBr** [comment]
it returned!

**Comment by EvaldoCeBr** [comment]
> ![Screenshot_20240602_112405_Mihon](https://github.com/keiyoushi/extensions-source/assets/98929917/eb8f6b1d-e79c-4023-b605-ef9d6218d79b)
> tá normal aqui

The recent tab always works, the problem is in the popular one.
