### ISSUE TITLE
jinman tian tang manhwa cant load  禁漫天堂

### ISSUE THREAD

**Issue by BabyNurse020517** [keiyoushi/tachiyomi-extensions-source#3366]
### Source information

jinman tiantang 1.4.42

### Source language

chinese

### Steps to reproduce

**jmcomic.me will automatic change to other links 18comic.vip**

### Expected behavior

jmcomic.me will automatic change to other links 18comic.vip

### Actual behavior

jmcomic.me will automatic change to other links 18comic.vip

### Mihon/Tachiyomi version

0.16.5

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
> jmcomic.me will automatic change to other links 18comic.vip

Try switching to another domain according to your location.

**Comment by BabyNurse020517** [comment]
i solve the cloudflare for 18comic.vip from browser but it still cannot solve

**Comment by Nuero987** [comment]
> > jmcomic.me will automatic change to other links 18comic.vip
> 
> Try switching to another domain according to your location.

Only chromium browser can visit the mainland domain, neither webview nor webkit. Is it caused by jmcomic's TLS setting?
