### ISSUE TITLE
No novels

### ISSUE THREAD

**Issue by Nerannnn** [keiyoushi/tachiyomi-extensions-source#337]
### Source information

Tsudoku traduções 1.4.36

### Source language

Portuguese 

### Steps to reproduce

For some reason, the novels that are available on this extension's website are not appearing in the extension, while the manga are appearing normally

### Expected behavior

all available works on the site appear in the extension

### Actual behavior

only the manga appears

### Tachiyomi version

0.15.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Tachiyomi and Mihon do not support reading novels.
