### ISSUE TITLE
Mangadex - author name search didn't work

### ISSUE THREAD

**Issue by afiif257** [keiyoushi/tachiyomi-extensions-source#3371]
### Source information

tachiyomi-all.mangadex-v1.4.193

### Source language

Multi

### Steps to reproduce

1. Open Browse > Sources > Mangadex
2. Use search and enter author name

### Expected behavior

The author name should be seen, as in the webview
![Screenshot_20240603-075458](https://github.com/keiyoushi/extensions-source/assets/35552196/3b04b882-1d62-4a3b-8c52-449056f58e5c)
And it shows related link and manga if clicked
![Screenshot_20240603-075508](https://github.com/keiyoushi/extensions-source/assets/35552196/27343f49-2c77-449d-9033-3a405381deab)

### Actual behavior

It shows "No results found"
![Screenshot_20240603-075430](https://github.com/keiyoushi/extensions-source/assets/35552196/b376046b-9e0a-4327-be4d-0281a2490905)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
I believe this is a limitation in the [Mangadex API](https://api.mangadex.org/docs/03-manga/search/).

~~Not even Neko, which is specifically for Mangadex can search the site with author names~~ 

seems like it can but it requires its own separate search field which would require support from the app. It is a very specific addition for a very specific source, which is why it will probably not be added.

So if you wanna search authors, you are better off using Neko.

**Comment by Norsze** [comment]
![Screenshot_20240603_032418_Firefox.jpg](https://github.com/keiyoushi/extensions-source/assets/66540317/e86fab29-b071-4c2b-9ecc-c2ee803ccf11)

Notice the lack of a `GET author`
