### ISSUE TITLE
Fmovies URL change 

### ISSUE THREAD

**Issue by GGGS9119** [keiyoushi/tachiyomi-extensions-source#3374]
### Source information

FMovies 14.23

### Source language

English 

### Source new URL

Fmovies24.to

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
We don't have anime/movie extensions

**Comment by GGGS9119** [comment]
It's in the anime extensions

**Comment by Smol-Ame** [comment]
> It's in the anime extensions

**We** don't have anime extension, and we're not an app

Go contact whoever maintains your anime extensions instead
