### ISSUE TITLE
Manga no sekai no load chapter

### ISSUE THREAD

**Issue by Athrun0311** [keiyoushi/tachiyomi-extensions-source#3378]
### Source information

Manganosekai 1.4.50

### Source language

Spanish 

### Steps to reproduce

Se busca manga dentro de la extension. No aparece la lista de capitulos de cualquier manga

### Expected behavior

Debe aparecer la lista de capitulos, para leer los mangas

### Actual behavior

No aparece la lista de capitulos
![Screenshot_20240603_024944_app mihon](https://github.com/keiyoushi/extensions-source/assets/160463122/15e96b8a-2a0e-45ca-929c-958ed0d17bc4)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 11

### Other details

Los capitulos si figuran en su web 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #3301 

Search the existing issues first before opening a new one, and acknowledging that you did. ~~Wait for a future fix (extension update)~~

**Comment by Smol-Ame** [comment]
Correction, read the issue linked above for the current fix, but the message still stands
