### ISSUE TITLE
Tojimangas 

### ISSUE THREAD

**Issue by ashliepolanco** [keiyoushi/tachiyomi-extensions-source#3386]
### Source name

Tojimangas

### Source link

https://tojimangas.com/

### Source language

Spanish 

### Other details

18+/NSFW = yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by ingridsterphane** [comment]
How do I know when they will add this site? I would really like to read it

**Comment by Smol-Ame** [comment]
@ingridsterphane when the issue gets closed as completed. Next time/for future reference, follow the issue rather than commenting (if you aren't commenting any useful info that will help contributors), which unnecessarily emails anyone involved with the issue & pings the server channel.
