### ISSUE TITLE
Newtoki WebView validation data cannot be returned to APP

### ISSUE THREAD

**Issue by FengTeLai** [keiyoushi/tachiyomi-extensions-source#3394]
### Source information

Newtoki 1.4.32

### Source language

Korean

### Steps to reproduce

Click WebView to validate cloudflare
Validate Successfully
Manga catalog and content data still can't be successfully refreshed

### Expected behavior

Updated manga catalog and chapter contents

### Actual behavior

It has been verified successfully, but the APP can't receive the verification data.
Manga catalog and content data still can't be successfully refreshed

### Mihon/Tachiyomi version

0.16.5

### Android version

HarmonyOS 3.0

### Other details

![1](https://github.com/keiyoushi/extensions-source/assets/117538601/6c2fdc55-be97-4e7c-a763-4ea9be81bec3)
![2](https://github.com/keiyoushi/extensions-source/assets/117538601/9f8145d0-8a02-4435-9853-97c2217812e6)
![3](https://github.com/keiyoushi/extensions-source/assets/117538601/d298ba68-1775-42fd-93a4-ee45ec1f213b)
![4](https://github.com/keiyoushi/extensions-source/assets/117538601/c9987aa9-ef70-434c-a1af-59c1f45a147a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FengTeLai** [comment]
@Smol-Ame 
What's happening now is that I've adjusted the version of the browser that comes with Huawei and reverted back to only having to authenticate once to be able to view the full site content properly, but tachiyomi and mihon are still suggesting that they can't be bypassed.

I don't understand why this is still happening and had to come here to ask.

**Comment by Smol-Ame** [comment]
Could you join the Keiyoushi Discord server and message in the repo-support channel? Just to make this a bit easier & quicker to troubleshoot for you

**Comment by GMak9** [comment]
This is the same issue described here #3541
When using Random UA: The WebView UA is not the same as the one used in the source, so the validation becomes invalid. Random UA = Random Validation.

**Comment by FengTeLai** [comment]
Huawei phones need to look for the webview kernel app, uninstall the current copyright and return to factory settings to fix this issue.
