### ISSUE TITLE
Updating of extensions not working

### ISSUE THREAD

**Issue by necropower** [keiyoushi/tachiyomi-extensions-source#341]
### Source information

Bato,to and others

### Source language

English

### Steps to reproduce

The list of extendions to be update is shown but when i try to update, nothing is done

### Expected behavior

To update the extensions then they should disappear from the update list

### Actual behavior

They dont update and dont disappear 

### Tachiyomi version

0.15.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by aboudiom59** [comment]
Did you try to first uninstall and then reinstall the extension? if your previous version came from tachiyomi android won't install it. I know it sounds weird but that's how it works. In general, it would be better to uninstall and then reinstall all your extensions.
