### ISSUE TITLE
Mangalib don't load pages

### ISSUE THREAD

**Issue by Workotyagi** [keiyoushi/tachiyomi-extensions-source#3410]
### Source information

MangaLib 1.4.100

### Source language

Russian

### Steps to reproduce

1. Update parser
2. Open any title on mangalib
3. Try to open any chapter (in app or webview)

### Expected behavior

You can read any chapter of any title

### Actual behavior

In app you that it can't load image
On webview you see 404
![photo_2024-06-04_15-09-50](https://github.com/keiyoushi/extensions-source/assets/129949407/c8b88e42-af17-43f7-b2b0-fb31932f76f0)
![photo_2024-06-04_15-09-45](https://github.com/keiyoushi/extensions-source/assets/129949407/f57dcf38-9011-40b9-800f-3f13be7b92d9)

### Mihon/Tachiyomi version

Beta r6710

### Android version

Android 13

### Other details

Same problem on HentaiLib, butb on hentailib i  can download chapters

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by GregerForever** [comment]
You need to change the domain in the settings to [test-front.mangalib.me](test-front.mangalib.me). Then you need to log in to this site and close the application and disable the process. Then use this [guide](https://4pda.to/forum/index.php?showtopic=805780&view=findpost&p=130590554) to migrate title from old lib to new lib. It is recommended to use TachiyomiSY for this guide. This guide is the same for both Mangalib and HentaiLib and Yaoilib.

**Comment by Workotyagi** [comment]
> You need to change the domain in the settings to [test-front.mangalib.me](test-front.mangalib.me). Then you need to log in to this site and close the application and disable the process. Then use this [guide](https://4pda.to/forum/index.php?showtopic=805780&view=findpost&p=130590554) to migrate title from old lib to new lib. This guide is the same for both Mangalib and HentaiLib and Yaoilib.

Ok, changing domain helps for 404 error, but i can't load any page in app. And i also migrate all titles

**Comment by Workotyagi** [comment]
So complete solution is this:

1. Change domain in extension setting to https://test-front.mangalib.me
2. Change image server to compression (or test) 
3. Restart the app
4. Profit
