### ISSUE TITLE
Immortal Update change domain

### ISSUE THREAD

**Issue by Ayoon58** [keiyoushi/tachiyomi-extensions-source#3411]
### Source information

en.immortalupdates 1.4.42

### Source language

English

### Source new URL

https://mortalsgroove.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/keiyoushi/extensions-source/issues/3021.
Use search before please 🙏

**Comment by Smol-Ame** [comment]
Read comment in #3021 for fix

Also search the existing issues first, both open & closed, before opening a new one, and acknowledging that you did.
