### ISSUE TITLE
MangaSwat: Some images show distorted 

### ISSUE THREAD

**Issue by Saud-97** [keiyoushi/tachiyomi-extensions-source#3413]
### Source information

MangaSwat

### Source language

Arabic

### Steps to reproduce

1. Make sure the extension URL is correct (via ext. settings). Current URL is "normoyun.com/"
2. View or download the Chapter 14 of "The Lazy Swordmaster" https://normoyun.com/manga/the-lazy-swordmaster/the-lazy-swordmaster-5
3. Notice how the image quality is different in app compared to browser quality.
4. Notice chapter 15 shows normally so this issue might be related to the specific images in Chapter 14

### Expected behavior

Should have the same quality as when viewed in browser.

### Actual behavior

Images are distorted.
Screenshot from app (tested on Mihon and multiple forks J2K, SY) Compared with browser quality

<p float="left">
  <img src="https://github.com/keiyoushi/extensions-source/assets/39028181/e443c9fc-05d0-4d59-9870-009ff3c36e23" width="30%" />
  <img src="https://github.com/keiyoushi/extensions-source/assets/39028181/8102dd04-eb5b-4532-bbc1-9418940dc393" width="35%"  height="100%"/> 
</p>

### Mihon/Tachiyomi version

Latest versions of both forks

### Android version

Android 13

### Other details

If this is an app issue let me know. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
the mentioned chapter have gifs for images, which the app tries to render but since it is a long strip and gifs aren't supposed to be like that, it turns out wierd.

you can report this to the app but I doubt they will fix this type of edge case

**Comment by Saud-97** [comment]
Thanks for the explanation. I will just ignore this case as it was the first time in my 2 years of use that I saw this issue. Have a good one.
