### ISSUE TITLE
Mangago source giving error

### ISSUE THREAD

**Issue by Dhwani1i** [keiyoushi/tachiyomi-extensions-source#3420]
### Source information

Mangago 1.4.15

### Source language

English

### Steps to reproduce

1. For eg I search for a comic let's say missing love in mangago
2. When I open a chapter of it, it doesn't load any images instead shows error that images aren't able to load 
3. But some of the comics don't have this issue 

### Expected behavior

Mangago should load the comics correctly with images

### Actual behavior

Many manhwas or manhuas load correctly while some of them give issue ie the image don't load for them at all. It's a problem with extension since I have tried multiple apps but same behaviour is there by mangago
![Screenshot_2024-06-05-09-25-56-18_a603e4da04bada03cae438f177815547](https://github.com/keiyoushi/extensions-source/assets/115367019/5e50bf48-fed5-4848-93bb-271ef1d81dd9)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Dhwani1i** [comment]
I have been encountering this issue for months now. Tried manually deleting the extension, reinstalling it using the apk download in this repo, also tried many other apps besides mihon but nothing worked

**Comment by Smol-Ame** [comment]
Related/duplicate of #2548

Any specific chapter of "Missing Love"? If your screenshot is about a chapter with 46 pages for "Missing Love", chapters 4, 23, 32, and 54 loaded up fine. Also, while going through all the chapters, at least 30 different chapters started loading up before I backed out to check the next one, so it doesn't seem like there's an issue.

**Comment by Dhwani1i** [comment]
> Any specific chapter of "Missing Love"?
> 
> Also, issue duplicate/related to #2548
None of the chapters is working and this isn't problem with a single comic
Yes I saw the duplicate issue but it didn't describe the actual problem properly and since I have been facing this problem for many days, I wanted to describe it in detail.

**Comment by Dhwani1i** [comment]
> Related/duplicate of #2548
> 
> Any specific chapter of "Missing Love"? If your screenshot is about a chapter with 46 pages for "Missing Love", chapters 4, 23, 32, and 54 loaded up fine. Also, while going through all the chapters, at least 30 different chapters started loading up before I backed out to check the next one, so it doesn't seem like there's an issue.

I don't know then why my device specifically is showing the problem, I cannot load ch either of the chapters you mentioned. And I have tried many things but not able to solve it yet..

**Comment by Smol-Ame** [comment]
> I don't know then why my device specifically is showing the problem, I cannot load ch either of the chapters you mentioned. And I have tried many things but not able to solve it yet..

Go into the reader where it shows this issue, then go into the WebView to see if there's any extra info/errors that show up (button at the top-right corner of the reader)

Also, if you can, please join our Keiyoushi Discord server and message in the repo-support channel

**Comment by Dhwani1i** [comment]
> > I don't know then why my device specifically is showing the problem, I cannot load ch either of the chapters you mentioned. And I have tried many things but not able to solve it yet..
> 
> Go into the reader where it shows this issue, then go into the WebView to see if there's any extra info/errors that show up (button at the top-right corner of the reader)
> 
> Also, if you can, please join our Keiyoushi Discord server and message in the repo-support channel

The webview is working fine.. I can view the pages using webview which aren't loaded in reader. 
Ah alrighty i will have to search for the link to invite first ..

**Comment by Dhwani1i** [comment]
> > I don't know then why my device specifically is showing the problem, I cannot load ch either of the chapters you mentioned. And I have tried many things but not able to solve it yet..
> 
> Go into the reader where it shows this issue, then go into the WebView to see if there's any extra info/errors that show up (button at the top-right corner of the reader)
> 
> Also, if you can, please join our Keiyoushi Discord server and message in the repo-support channel

Could you share the invite to discord server please?

**Comment by Smol-Ame** [comment]
> Could you share the invite to discord server please?

https://discord.gg/3FbCpdKbdY , listed on keiyoushi website & this GitHub repo

**Comment by Dhwani1i** [comment]
> > Could you share the invite to discord server please?
> 
> https://discord.gg/3FbCpdKbdY , listed on keiyoushi website & this GitHub repo

Thank you :)

**Comment by AwkwardPeak7** [comment]
cannot reproduce, clear chapter cache and try to downlad the chapter, send any error that appears in the notifications from the downloader

**Comment by Dhwani1i** [comment]
> cannot reproduce, clear chapter cache and try to downlad the chapter, send any error that appears in the notifications from the downloader

I am unable to download any chapter i mean it just keeps loading for downloading but it doesn't get downloaded. But it seems the issue was solved with vpn. It was neither the issue of extension nor phone . Thank you.
