### ISSUE TITLE
The extension is not working

### ISSUE THREAD

**Issue by lognim** [keiyoushi/tachiyomi-extensions-source#3422]
### Source information

Newtoki/Manatoki 1.4.32

### Source language

Korean

### Steps to reproduce

1. I open the extension. 
2. Doesn't show any comic covers. 
3. I've done solve the captcha. 
4. I re-open the extension but it doesn't work either. 

### Expected behavior

When I open the extension, it rapidly shows the comic cover. 

### Actual behavior

Doesn't show the comic cover, whether how many I've tried, it doesn't work. 
![Screenshot_20240605-173948](https://github.com/keiyoushi/extensions-source/assets/125033036/fc1de89a-527b-4d21-a968-a62e0af22876)

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Loads on my end. Try clicking around in WebView into the search or manhwa pages to see if any other verification pop-up.

If none, try switching your user-agent to a different one, restart the app, and check WebView verification. Then see if it loads in-app afterwards


Otherwise, duplicate of #3394

**Comment by lognim** [comment]
I tried all the methods but it didn't work somehow. Like I switch all the
user-agent for WebView verification, even I logged in my account in Webview
to prevent captcha, just like before.

I hope you understand.
