### ISSUE TITLE
IMHentai can't showing any media on every content since mid-May 2024

### ISSUE THREAD

**Issue by Lavinsado** [keiyoushi/tachiyomi-extensions-source#3423]
### Source information

IMHentai 1.4.16

### Source language

Multi

### Steps to reproduce

1. Click IMHentai sources
2. Click any content since mid-May 2024
3. Click read
4. Media can't be shown and popping "The image couldn't be loaded"
5. Image also can't be shown on webview and popping "404 not found" indicating wrong redirected URL

### Expected behavior

App / webview should be showing image on each content 

### Actual behavior

Media not shown on app view and web view. Popping "The image couldn't be loaded" on app view and "404 Not Found" on web view

### Mihon/Tachiyomi version

Tachiyomi 0.15.3

### Android version

Android 12

### Other details

URL on content before mid-May 2024 can shown the image / media
URL example : https://imhentai.xxx/gallery/1193136/
Screenshot webview : 

URL on content on and after mid-May 2024 got added syntax. Showing non-existent media 
URL example : https://m8.imhentai.xxx/027/53zae8vik4/1.jpg
Screenshot webview : 
![Screenshot_2024-06-05-19-10-12-21_afd66b7916d19a60815f56273408b73e](https://github.com/keiyoushi/extensions-source/assets/59469663/575c0810-6120-44f2-8825-666dde70551c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Lavinsado** [comment]
Re-installing app from clean slate fixed the issues and clear database

**Comment by AwkwardPeak7** [comment]
@Lavinsado please don't post nsfw images on github

closing since issue was fixed for you
