### ISSUE TITLE
Manhastro - erro

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#3424]
### Source information

Manhastro 1.4.41

### Source language

Português (Brasil)

### Steps to reproduce

![Screenshot_20240605-092912](https://github.com/keiyoushi/extensions-source/assets/157044539/bcacdd6e-cdc2-41ee-b5e6-bada50a23d3b)
Está assim desde ontem

### Expected behavior

.

### Actual behavior

.

### Mihon/Tachiyomi version

Tachiyomi SY 1.10.5

### Android version

Android 11

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
could be a dupe, too lazy to use translator : https://github.com/keiyoushi/extensions-source/issues/3265

**Comment by ghost** [comment]
?

**Comment by ghost** [comment]
> poderia ser um idiota, preguiçoso demais para usar o tradutor : #3265

???

**Comment by nomaxsnx** [comment]
Por favor @QuagZy , fecha essa Issue ou #3265, pois e considerado dupe de Issues

obs: percebi que tbm esta lento o Manhastro, como a MangasChan parou de Atualizar, possivelmente um monte trafico veio pro manhastro e a host não esta tanto conta de varias pessoas acessando.

**Comment by ghost** [comment]
> Por favor @QuagZy , fecha essa Issue ou #3265, pois e considerado dupe de Issues
> 
> obs: percebi que tbm esta lento o Manhastro, como a MangasChan parou de Atualizar, possivelmente um monte trafico veio pro manhastro e a host não esta tanto conta de varias pessoas acessando.

Ok

**Comment by GMak9** [comment]
Possibly another action of Operation 404 in Brazil.

**Comment by nomaxsnx** [comment]
> Possibly another action of Operation 404 in Brasil

The second police operation against piracy has ended, with no plans for a third operation. 

Also, there was no mention of Manhastro in the news.

**Comment by AwkwardPeak7** [comment]
site and extensions are working, timeout can either be source being down or your network acting up
