### ISSUE TITLE
When updating a font, it disappears from those installed and appears next to those that were not installed.

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#3425]
### Source information

All of them.

### Source language

Portuguese Brazilian and Multiple.

### Steps to reproduce

When I click on update a font, instead of installing the update it apparently uninstalls the font, forcing me to install it again.

### Expected behavior

That install the update without uninstalling the source.

### Actual behavior

It is necessary to reinstall the source when trying to update.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
See: [Cannot install updated extensions](https://github.com/keiyoushi/extensions-source/issues/109)
