### ISSUE TITLE
Pages are not loading (HentaiLib)

### ISSUE THREAD

**Issue by Bloodhaod** [keiyoushi/tachiyomi-extensions-source#3427]
### Source information

HentaiLib 1.4.45

### Source language

Russian 

### Steps to reproduce

1. Choosing a hent
2. Chapter opening

### Expected behavior

a scan will appear (picture)

### Actual behavior

the image is not loading
![Screenshot_2024-06-05-23-46-53-83_a603e4da04bada03cae438f177815547](https://github.com/keiyoushi/extensions-source/assets/64723873/6163529d-7857-4922-b978-9cdc35983101)

### Mihon/Tachiyomi version

TachiyomiSY 1.10.5

### Android version

13

### Other details

Important! In one hentai, some chapter does not load the cortines completely, but another chapter loads everything perfectly (loads only the last 3-4 chapters). Also, in another hentai, all chapters are loaded normally. In hentai, where pictures are not loaded when opening a chapter, if opened via the web, it will write that there is no such page, but at the same time if you open the hentai itself and select this chapter, it will load normally. Also, in MangaLib, he does not see the chapters, writes that they are not there, but at the same time they are on the site (it seems that all chapters are loaded everywhere) and YaoiLib I am logged in to the site, but when opening the chapter he writes that I need to log in. UPD I noticed that in hentailib he loads the chapters every other time.

![Screenshot_2024-06-05-23-55-46-79_a603e4da04bada03cae438f177815547](https://github.com/keiyoushi/extensions-source/assets/64723873/6504d0e5-67ba-44b1-8d5b-f6ac5a36595f)

![Screenshot_2024-06-06-00-15-41-89_a603e4da04bada03cae438f177815547](https://github.com/keiyoushi/extensions-source/assets/64723873/846db295-5b28-40e3-bae5-92cd11be29f4)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nedius** [comment]
If images are not loading did you tried to switch image server ?
Second image server right now does not want to work sometimes

**Comment by Bloodhaod** [comment]
I have just noticed that I have chosen 2 servers instead of 1, I completely forgot about this feature. I will change it now and hope that there will not be this problem. But in Mangalib, depending on the selected server it depends whether it can see the chapters? It’s just that I have one server there, and I don’t think the server choice affects the uploading of the chapters themselves, not the content in them. I changed the server, but the chapters never show up.

**Comment by Bloodhaod** [comment]
> If images are not loading did you tried to switch image server ? Second image server right now does not want to work sometimes

I have just noticed that I have chosen 2 servers instead of 1, I completely forgot about this feature. I will change it now and hope that there will not be this problem. But in Mangalib, depending on the selected server it depends whether it can see the chapters? It’s just that I have one server there, and I don’t think the server choice affects the uploading of the chapters themselves, not the content in them. I changed the server, but the chapters never show up.

**Comment by nedius** [comment]
Mangalib domain should be changed to https://test-front.mangalib.me
To remove potential error it is advised to login by webview and restart app

Testing myself in emulator all works, with test subdomains.
HentaiLib works with https://hentailib.me domain

404 error will be fixed in #3442

**Comment by Bloodhaod** [comment]
I changed the link now everything works.
