### ISSUE TITLE
Low resolution image

### ISSUE THREAD

**Issue by chanwhun09** [keiyoushi/tachiyomi-extensions-source#3428]
### Source information

Manganato 1.4.7

### Source language

English

### Steps to reproduce

![Screenshot_2024-06-06-00-38-30-665_app mihon](https://github.com/keiyoushi/extensions-source/assets/144926600/2718eb9f-f591-4c99-8f93-de7cb755a5ee)k

### Expected behavior

The reader should be HD 

### Actual behavior

The reader is blurry ang low resolution 

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Looks fine on my end (see first picture), if you have the chapter downloaded, delete the chapter.
Afterwards, go to Mihon Settings > Data and storage > Clear chapter cache

If that doesn't work, try switching the image server on the source website in WebView (see second picture), then do the same Clear chapter cache step

![Screenshot_20240605_105514_Mihon](https://github.com/keiyoushi/extensions-source/assets/155411819/455d994c-c974-42dd-949c-2591dea81fba)
![Screenshot_20240605_105746_Mihon](https://github.com/keiyoushi/extensions-source/assets/155411819/6178e76d-9bec-4c39-97e0-846a63903ae1)

**Comment by chanwhun09** [comment]
![Screenshot_2024-06-06-08-08-09-005_app mihon](https://github.com/keiyoushi/extensions-source/assets/144926600/954ac137-bbce-4b35-afdc-6e4c4798af70)

Still blur, but on web view its fine, it's only in the app that it's low res

**Comment by Smol-Ame** [comment]
Could you go to your Mihon More Page > About, tap the version number & paste the copied info here?

Also have you tried downloading the chapter to see if it shows up clearly?

**Comment by chanwhun09** [comment]
App version: 0.16.5 (standard, 2a01a2a, 6, 2024-04-09T09:58:14Z)
Android version: 14 (SDK 34; build UKQ1.231207.002 release-keys)
Device brand: POCO
Device manufacturer: Xiaomi
Device name: munch (munch_eea)
Device model: 22021211RG
WebView: Android System WebView 125.0.6422.83

**Comment by AwkwardPeak7** [comment]
come to our discord for further help. this kind of issue can happen if you are using a custom rom

**Comment by chanwhun09** [comment]
Okay
