### ISSUE TITLE
Komikcast double page

### ISSUE THREAD

**Issue by Hahagun1** [keiyoushi/tachiyomi-extensions-source#3440]
### Source information

Komikcast

### Source language

Indonesia

### Steps to reproduce

1.open any manga in komikcast
2.every page double up

### Expected behavior

Komikcast manga should show up only 1 page

### Actual behavior

Komikcast duplicate every page on any manga or manhwa
![Screenshot_2024-06-06-15-55-49-293_xyz luft tachiyomi mi](https://github.com/keiyoushi/extensions-source/assets/132212796/5a7c0435-d5c4-4b10-862b-af27644f46d9)

### Mihon/Tachiyomi version

Aniyomi 0.15.3.0

### Android version

Android 13

### Other details

Every manga or manhwa page will double

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
update your extension

**Comment by Hahagun1** [comment]
Thanks.. issue has been resolved 👍🏻
![Screenshot_2024-06-06-16-09-35-257_xyz luft tachiyomi mi](https://github.com/keiyoushi/extensions-source/assets/132212796/efe35336-be12-41a2-9797-1a239512839c)
