### ISSUE TITLE
Manga Toshokan Z gives NullPointerException:Null

### ISSUE THREAD

**Issue by lukos2004** [keiyoushi/tachiyomi-extensions-source#3447]
### Source information

Manga Toshokan Z 1.4.1

### Source language

Japanese

### Steps to reproduce

Open any tab to reproduce after installing source.

### Expected behavior

Should show manga available.

### Actual behavior

Gives error NullPointerException:Null

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

![Screenshot_2024-06-06-22-04-16-408_app mihon](https://github.com/keiyoushi/extensions-source/assets/171483719/405f935b-02de-49c2-8fb0-61fb7a14d373)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
it works with desktop useragents

**Comment by lukos2004** [comment]
Reseting the user agent back to default resolved the issue.

**Comment by lukos2004** [comment]
Reseting the user agent back to default resolved the issue.
