### ISSUE TITLE
HTTP Error 403 Hunters Scans.

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#3448]
### Source information

Hunters Scans 1.4.38

### Source language

Portuguese Brazilian 

### Steps to reproduce

When doing a search, HTTP Error 403 appears.
![IMG_20240606_181557](https://github.com/keiyoushi/extensions-source/assets/169321265/3b87890d-0e4f-4a3c-9bd0-1b1d7892b64a)

### Expected behavior

Search results appear.

### Actual behavior

Http Error 403 appears.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
They all work. Check WebView for any errors & let the page load. Then go back to the app & try searching again.

Consider joining the Keiyoushi Discord server & ask in repo-support for these basic errors before opening a whole issue request (three of them in this case).

This applies to #3449 and #3450.

**Comment by Smol-Ame** [comment]
Forgot to add picture as proof:

![Screenshot_20240606_143150_Mihon.png](https://github.com/keiyoushi/extensions-source/assets/155411819/3a123bbe-4af2-4a7f-bc64-04bb3cb1e2bf)
