### ISSUE TITLE
Http Error 403 Sagrado Império da Britannia.

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#3449]
### Source information

Sagrado Imperio da Britannia 1.4.36

### Source language

Portuguese Brazilian 

### Steps to reproduce

When doing a search, Http Error 403 appears.
![IMG_20240606_181557](https://github.com/keiyoushi/extensions-source/assets/169321265/b7481acb-e757-4227-8785-3e2ac08941c2)

### Expected behavior

Show search results.

### Actual behavior

Http Error 403 appears.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nomaxsnx** [comment]
![Screenshot_2024-06-06-18-37-11-127_app mihon](https://github.com/keiyoushi/extensions-source/assets/157644160/7b0595ea-6b8d-4306-b318-d0233893f4b6)
