### ISSUE TITLE
Http Error 403 SSSScanlator.

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#3450]
### Source information

SSSScanelator 1.4.32

### Source language

Portuguese Brazilian 

### Steps to reproduce

When performing a search, the error Http Error 403 appears.
![IMG_20240606_181557](https://github.com/keiyoushi/extensions-source/assets/169321265/8a07f00f-90d2-4702-b773-246b1145ee9c)

### Expected behavior

Search results appear.

### Actual behavior

The Http Error 403 error appears.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nomaxsnx** [comment]
![Screenshot_2024-06-06-18-37-08-617_app mihon](https://github.com/keiyoushi/extensions-source/assets/157644160/4e32bd31-07e5-4df5-a8fe-a8e175f554a5)
