### ISSUE TITLE
Mangas No Sekai

### ISSUE THREAD

**Issue by Proxy-E23** [keiyoushi/tachiyomi-extensions-source#3453]
### Source information

Mangas No Sekai 1.4.50

### Source language

Spanish

### Steps to reproduce

Attempt to open any manga and check the chapters.

### Expected behavior

Show the available chapters of the manga.

### Actual behavior

Shows the following error
![Screenshot_20240606-215951_Mihon](https://github.com/keiyoushi/extensions-source/assets/79614894/17265290-3194-4ae5-a943-8c414d83ac6f)

### Mihon/Tachiyomi version

0.16.3

### Android version

12

### Other details

The login is not saved in the webview I think that is the main reason for the failure

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Create an account and log in to WebView

**Comment by Proxy-E23** [comment]
> Create an account and log in to WebView

Ok, I've figured out what the issue is. The login in the webview wasn't being saved. I logged in multiple times, and it seems it's saved now.

I don't know why the login was not saved, even though I was checking the remember option.
