### ISSUE TITLE
Ikigai esta atrasado en recientes

### ISSUE THREAD

**Issue by Reydelasombras** [keiyoushi/tachiyomi-extensions-source#3469]
### Source name

Ikigaimangas

### Source language

español

### Describe your suggested feature

Poner para que este al en recientes, esta atrasado 2 manhwas

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
can be a site cache issue, also if that series are nsfw make sure you enable the option in extension settings
