### ISSUE TITLE
Mangasee extension not working.

### ISSUE THREAD

**Issue by fam007e** [keiyoushi/tachiyomi-extensions-source#3479]
### Source information

Mangasee

### Source language

English

### Steps to reproduce

Opening `mangasee` from the `browse` option.

### Expected behavior

Loading the mangas.

### Actual behavior

Shows error: 
```
Hostname mangasee123.com not verified:
certificate: sha256/w2mSbZLALZM2sGWBFRw6LwT00ANegpHnIQ/jckE3rRI= DN: CN=defaultcontent.com
subjectAltNames: [defaultcontent.com]
```

### Mihon/Tachiyomi version

v8.8.1-AZ

### Android version

Android 11

### Other details

The app used is Tachiyomi-AZ

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Works fine for me, loading popular titles, chapter list and pages in chapters.

Something else is probably broken

**Comment by AwkwardPeak7** [comment]
works fine, the error mentioned can be a temporary server issue
