### ISSUE TITLE
"No pages found" on Olympus Scanlation and Temples Scan; occurred with RavenManga too and was resolved in a source update smh

### ISSUE THREAD

**Issue by lalalasupa0** [keiyoushi/tachiyomi-extensions-source#3482]
### Source information

Olympus Scanlation 1.4.9 - Temple Scan 1.4.36

### Source language

Spanish (both)

### Steps to reproduce

Open chapter

### Expected behavior

Should show pages

### Actual behavior

"No pages found" message

### Mihon/Tachiyomi version

Yokai Nightly Build 1.8.3.4-b5194 and TachiyomiSY Preview r561

### Android version

Android 12

### Other details

Edit: The Olympus issue was fixed with an user agent, so ignore the info abt it.

It is NOT an issue of Yokai or TSY, I have already reported this on both and both sides concluded that it was source error, maybe compatibility or something like that idk
It is also not a issue of user agents

This error does NOT happen in Mihon

This issue happened with RavenManga too but it was fixed in the last update

In Olympus this issue seems to be more serious because the pages don't load in webview either no matter the webview version (maybe it's the web's job lol), while with Temples at least they do load in webview, the same with RavenManga

I have only used Yokay and TSY, so I don't know if it happens in any other fork

Oh yeah, it doesn't happen all the time with Temple, it happens to me specifically with the pornhwa "La Vida De Un Caballero Sabio".

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
If your Temple Scan extension version is correct, you are out of date. Our repo's version is 1.4.41

Also, have you tried migrating whatever titles that aren't working back into the same extension (Olympus back into Olympus) to update the URL?

Also also, for the "La Vida De Un Caballero Sabio", are you able to find it in your browser (just to check if it still exists on their site)? Not sure if Temple has an issue on their site with searching (or just Firefox moment), but I'm unable to search for that title.

**Comment by Reydelasombras** [comment]
También ikigai

**Comment by Smol-Ame** [comment]
> También ikigai

@Reydelasombras did you do what bapeey said in your issue request?

**Comment by lalalasupa0** [comment]
> If your Temple Scan extension version is correct, you are out of date. Our repo's version is 1.4.41
> 
> Also, have you tried migrating whatever titles that aren't working back into the same extension (Olympus back into Olympus) to update the URL?
> 
> Also also, for the "La Vida De Un Caballero Sabio", are you able to find it in your browser (just to check if it still exists on their site)? Not sure if Temple has an issue on their site with searching (or just Firefox moment), but I'm unable to search for that title.

> If your Temple Scan extension version is correct, you are out of date. Our repo's version is 1.4.41

I'm talking abt the spanish one, not the eng

> have you tried migrating whatever titles that aren't working back into the same extension (Olympus back into Olympus)

Yeah, quite a few times in the past. Anyway, I went into a manga that's not in my library inside the source and it's just the same

> for the "La Vida De Un Caballero Sabio", are you able to find it in your browser (just to check if it still exists on their site)?

https://templescanesp.net/ver/la-vida-de-un-caballero-sabio
Here is it, again, Ig you're using the english ver of the source

>> Source language
> Spanish

I didn't even knew Temple had an english web lol

**Comment by lalalasupa0** [comment]
> También ikigai

Checa webview, aveces la página te pregunta unas cosas y eso interrumpe las imágenes

**Comment by Smol-Ame** [comment]
> I'm talking abt the spanish one, not the eng
* Ah, my apologies, I forget that its split/different than the EN version.

> https://templescanesp.net/ver/la-vida-de-un-caballero-sabio Here is it, again, Ig you're using the english ver of the source
* Thanks, maybe a contributor could give you a more definite answer, but it seems like on their website, most of the chapters for this title seems to have incomplete/hidden chapter info
* For example, Chapter 32 and 41 has thumbnails on the source's page, and chapter links (in the code) which you can read using the extension, but the others ones don't
* Seems like a source issue or intentional (idk how they usually do stuff)

> Yeah, quite a few times in the past. Anyway, I went into a manga that's not in my library inside the source and it's just the same
* Could you give me a title and chapter number to check?

**Comment by bapeey** [comment]
Can't reproduce the Olympus issue, the source change the url often so try migrating from Olympus to Olympus

**Comment by lalalasupa0** [comment]
> > I'm talking abt the spanish one, not the eng
> 
> * Ah, my apologies, I forget that its split/different than the EN version.
> 
> > https://templescanesp.net/ver/la-vida-de-un-caballero-sabio Here is it, again, Ig you're using the english ver of the source
> 
> * Thanks, maybe a contributor could give you a more definite answer, but it seems like on their website, most of the chapters for this title seems to have incomplete/hidden chapter info
> * For example, Chapter 32 and 41 has thumbnails on the source's page, and chapter links (in the code) which you can read using the extension, but the others ones don't
> * Seems like a source issue or intentional (idk how they usually do stuff)
> 
> > Yeah, quite a few times in the past. Anyway, I went into a manga that's not in my library inside the source and it's just the same
> 
> * Could you give me a title and chapter number to check?

"Caballero en Eterna Regresión" - Ch. 0 (or any other, that's how it is for me), I just tried them rn

**Comment by lalalasupa0** [comment]
> Can't reproduce the Olympus issue, the source change the url often so try migrating from Olympus to Olympus

It's not that, I just tried some mangas that are not in my library, meaning there is nothing even to migrate
And make sure you're using Yokai or TachiyomiSY, not Mihon

**Comment by Smol-Ame** [comment]
Works on my end, at least on SY

Double-check your SY Settings, such as "DNS over HTTPS" (turn off or adjust) or "Data Saver" (turn off or adjust)

**Comment by lalalasupa0** [comment]
> Works on my end, at least on SY
> 
> Double-check your SY Settings, such as "DNS over HTTPS" (turn off or adjust) or "Data Saver" (turn off or adjust)

The Data Server thing doesn't do anything for me. Could you give details of your DNS over HTTPS and user agent? I want to try them to see (on SY)

**Comment by Smol-Ame** [comment]
> The Data Server thing doesn't do anything for me. Could you give details of your DNS over HTTPS and user agent? I want to try them to see (on SY)

I don't have Data Saver or DNS over HTTPS enabled, and for the user-agent, what works for someone might not work for you.

Here's mine if you want to try I guess: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) FxQuantum/128.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Mobile Safari/537.36

**Comment by lalalasupa0** [comment]
> > The Data Server thing doesn't do anything for me. Could you give details of your DNS over HTTPS and user agent? I want to try them to see (on SY)
> 
> I don't have Data Saver or DNS over HTTPS enabled, and for the user-agent, what works for someone might not work for you.
> 
> Here's mine if you want to try I guess: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) FxQuantum/128.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Mobile Safari/537.36

That's it. Your user agent fixed Olympus. In both Yokai and TSY
And it fixes the source Traducciones Amistosas too, deamn

And btw, the Temple Scan's issue is still there, ig I should not close this until is done?

**Comment by Smol-Ame** [comment]
> That's it. Your user agent fixed Olympus. In both Yokai and TSY And it fixes the source Traducciones Amistosas too, deamn
* Glad it helps, but for future reference, search "latest user-agent" online, if any source has an issue with Cloudflare or issues loading I guess
 
> And btw, the Temple Scan's issue is still there, ig I should not close this until is done?
* Yeah, leave it open, a wonderful contributor has proposed a fix for the issue, and when it gets approved, this issue will close by itself
