### ISSUE TITLE
Ikigai nsfw

### ISSUE THREAD

**Issue by Reydelasombras** [keiyoushi/tachiyomi-extensions-source#3483]
### Source name

Ikigaimangas

### Source language

español

### Source link

https://visorikigai.net

### Other details

El contenido nsfw dice "páginas no Encontradas"

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
1) Wrong tag, source isn't down
2) Duplicate of your own issue, #3469
3) Did you even read what bapeey said to do, or my message telling you to read?
4) See pictures, seems to be fine, enable the extension's setting & then Mihon Settings > Advanced > Clear database

![Screenshot_20240608_124639_Mihon](https://github.com/keiyoushi/extensions-source/assets/155411819/addf8acf-8c74-4919-84dd-90a5e7964a35)
![Screenshot_20240608_124715_Mihon](https://github.com/keiyoushi/extensions-source/assets/155411819/831ab230-f246-4016-b711-e0e3f5e7f43b)
![Screenshot_20240608_124709_Mihon](https://github.com/keiyoushi/extensions-source/assets/155411819/f4ee11c2-633c-4aa5-888f-836efa71abd1)

**Comment by bapeey** [comment]
Can't reproduce, make sure you have your extension updated or if the images exists on webview

**Comment by Reydelasombras** [comment]
Acabo de ver y es en la app Yokai que no encuentra imágenes, en el resto si.
