### ISSUE TITLE
quero pedir a adição de uma extensão para um site com diversos mangas, manwhas e manhuas

### ISSUE THREAD

**Issue by ArthurGomesp** [keiyoushi/tachiyomi-extensions-source#3485]
### Source name

Tsuki mangas

### Source link

https://tsuki-mangas.com

### Source language

prtugues Brasil - PT-BR

### Other details

![WhatsApp Image 2024-06-08 at 17 35 42](https://github.com/keiyoushi/extensions-source/assets/72204367/594c5081-dfe1-4e06-88b5-6f29e2fd4dca)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by ArthurGomesp** [comment]
A extenção não esta funcionado, a extenção nem aparece no app

**Comment by Smol-Ame** [comment]
> A extenção não esta funcionado, a extenção nem aparece no app

Did you make sure to enable 18+ sources in your Mihon Settings > Browse page?

**Comment by ArthurGomesp** [comment]
Não estava ativado, obrigado pela ajuda!
