### ISSUE TITLE
Quero pedir a correção de uma fonte no pt br brasileiro 

### ISSUE THREAD

**Issue by Darkrever2** [keiyoushi/tachiyomi-extensions-source#3488]
### Source information

Demon Sect

### Source language

Português Brasil

### Source new URL

https://dsectcomics.org/

### Other details

![android-icon_background](https://github.com/keiyoushi/extensions-source/assets/172154149/1074ec0f-1d2c-40d9-a7eb-fed47b6db2f3)
![android-icon_foreground](https://github.com/keiyoushi/extensions-source/assets/172154149/a206c0da-cdad-4149-95ec-ac257d72fc2c)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Darkrever2** [comment]
O domínio do site foi alterado a pouco tempo!

**Comment by Smol-Ame** [comment]
> O domínio do site foi alterado a pouco tempo!

You gave the same link as the one the extension uses. See comments in #3324 if you are having issues.

Also for future reference, no NSFW pictures in the issue reports.
