### ISSUE TITLE
Não consigo baixar as extensões 

### ISSUE THREAD

**Issue by Denisshc** [keiyoushi/tachiyomi-extensions-source#3497]
### Source information

https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json

### Source language

Português Br 

### Steps to reproduce

Quando vou baixar qualquer extensão dá erro , e aparece um tela falando que pode ter bugs ou travamentos

### Expected behavior

Queria poder baixar as extensões 

### Actual behavior

Ao invés de conseguir acessar as fontes , tá dando esse problema 

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
come to our discord for help. also you posted your password...

**Comment by Denisshc** [comment]
Manda o link do Discord
