### ISSUE TITLE
Kaiscan.org 

### ISSUE THREAD

**Issue by Zack7292** [keiyoushi/tachiyomi-extensions-source#3500]
### Source information

Kai scans

### Source language

English

### Source new URL

https://kaiscans.org/

### Other details

kaiscans.com seems to still exist ? on computer, it redirect me to .org but if i use open inw beview in mihon, it opens it, but the current url lack chapters (for example, villains are destined to die only goes to 144 on .com while .org goes to 150)
all the series seem to be the exact same other then that 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Try migrating your Kai Scans manga back into Kai Scans to update the URL, to see if that helps

**Comment by Zack7292** [comment]
seems like  villains are destined to die has 2 entries for some reaosn, one that goes up to 144 and another one that has the rest... thank you :)
