### ISSUE TITLE
Source email address change

### ISSUE THREAD

**Issue by YamiRomao** [keiyoushi/tachiyomi-extensions-source#3501]
### Source information

Mangas no sekai 1.4.50

### Source language

Spanish

### Steps to reproduce

I open mihoh, I go to the extension mangas no sekai, I open a manga and I get the error 
Missing Field Exception: Field 'manga' is required

for type with serial name

'eu.kanade.tachiyomi.extension.es.mangasnosekai.

PayloadDto', but it was missing at path: $

### Expected behavior

Open the manga without problem

### Actual behavior

Error
Missing Field Exception: Field 'manga' is required

for type with serial name

'eu.kanade.tachiyomi.extension.es.mangasnosekai.

PayloadDto', but it was missing at path: $
![Screenshot_20240609-143807_Mihon](https://github.com/keiyoushi/extensions-source/assets/172212156/a1773959-82f2-4e40-b11a-2a03efdd3b85)

### Mihon/Tachiyomi version

0.16.5

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of closed #3453

See the comments in that issue for the fix, also search the existing issues (both open & closed), before opening a new one & acknowledging that you did.
