### ISSUE TITLE
Mangas no Sekai

### ISSUE THREAD

**Issue by KatoMegushua** [keiyoushi/tachiyomi-extensions-source#3505]
### Source information

Mangas No Sekai 1.4.50

### Source language

Spanish

### Steps to reproduce

Install and use

### Expected behavior

Install and no read manga

### Actual behavior

No read manga

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Other details

![Screenshot_20240609_175731_Mihon](https://github.com/keiyoushi/extensions-source/assets/145884813/0231f50a-4572-465e-bf2e-80e7fc663a2e)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of closed https://github.com/keiyoushi/extensions-source/issues/3453

See the comments in that issue for the fix, also search the existing issues (both open & closed), before opening a new one & acknowledging that you did.

**Comment by Athrun0311** [comment]
Debes crearte una cuenta de la pagina web de manga  no sekai y logearte.
