### ISSUE TITLE
Mangadex Deeplink not Working

### ISSUE THREAD

**Issue by mnhyim** [keiyoushi/tachiyomi-extensions-source#3509]
### Source information

Mangadex 1.4.193

### Source language

English

### Steps to reproduce

1. Randomly search manga in Google Chrome
2. Click the link
3. The link opened in browser instead of Mihon

### Expected behavior

The app should open with the manga.

### Actual behavior

The link didnt redirect to the app and the manga is shown on the browser

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 12 

### Other details

I just tested the latest **Mangadex extension (1.4.193)** on the latest **Mihon (0.16.5)** and the deeplinking doesnt work, when I tried to open Mangadex link it didnt redirect to the apps. I tried using older **Mihon version (0.16.0)** and it works perfectly, I'm not sure whether to report this issue to Mihon or the extension devs so I'll just leave it here.

PS. I alread allowed the extension to open supported links.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Did you enable it in your Mangadex extension? Phone Settings > App list > "Tachiyomi: Mangadex" > Set as default/open supported links

**Comment by mnhyim** [comment]
Yes, I did.

![image](https://github.com/keiyoushi/extensions-source/assets/34624746/a7078a2a-8ceb-4623-b19f-9876b34a7aa8)

**Comment by mnhyim** [comment]
Yes, I did.

![91cb3fb0-8d67-4bab-91a1-e4a233bfc167](https://github.com/keiyoushi/extensions-source/assets/34624746/572cef71-a59b-4c64-b45d-45050394c367)

**Comment by Smol-Ame** [comment]
Hmm, not sure then. Double-check Mihon app info that it's allowed to "Open supported links", and whatever browser you are using has permission to open in external apps (inside whatever browser's settings)

**Comment by AwkwardPeak7** [comment]
Extension still supports deep links, just have to manually verify them in settings. This kind of behaviour in modern androids is thanks to google...
you can use a link manager like [this](https://github.com/ivaniskandar/shouko)

for further help, come to our discord server
