### ISSUE TITLE
HentaiNexus Extension Currently Broken

### ISSUE THREAD

**Issue by Rockstarmoon** [keiyoushi/tachiyomi-extensions-source#3510]
### Source information

HentaiNexus - en.hentainexus version 1.4.9 

### Source language

English

### Steps to reproduce

Install the Extension "HentaiNexus"
Click on Browse towards "Sources"
List of the Manga Appears
Click on Doujin in this case "Let's Make a Baby! by Shiranai Hitoshi" 
Click on Chapter

### Expected behavior

Install the Extension "HentaiNexus"
Click on Browse towards "Sources"
List of the Manga Appears
Click on Doujin in this case "Let's Make a Baby! by Shiranai Hitoshi" 
Click on Chapter
Doujin Chapter Opens without errors

### Actual behavior

Install the Extension "HentaiNexus"
Click on Browse towards "Sources"
List of the Manga Appears
Click on Doujin in this case "Let's Make a Baby! by Shiranai Hitoshi" 
Click on Chapter
Doujin Chapter Opens to a Unexpected JSON Token Error
![438124922_825532496120851_8991775598502628033_n](https://github.com/keiyoushi/extensions-source/assets/110475326/f21a30b8-8305-4119-9d0a-aa07d7532e1e)

### Mihon/Tachiyomi version

Mihon Version 0.16.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #3508, and don't show NSFW images in issue requests please

Also, search the existing issues before opening a new one, and acknowledging that you did.

**Comment by AwkwardPeak7** [comment]
Duplicate of #3508
