### ISSUE TITLE
HentaiNexus - Doujin's with the same Name will be considered already downloaded despite different Authors

### ISSUE THREAD

**Issue by Rockstarmoon** [keiyoushi/tachiyomi-extensions-source#3511]
### Source information

HentaiNexus - en.hentainexus version 1.4.9

### Source language

English

### Steps to reproduce

Install the Extension "HentaiNexus"
Click on Browse towards "Sources"
List of the Manga Appears
Search "Good Luck Charm" on the Search Bar.
Three Listings will appear:
1. Good Luck Charm by Iwasaki Yuuki
2. Good Luck Charm by Wabara Hiro
3. Good Luck Charm by  NaPaTa
Save them all on the Library.
Try to download one of them.

### Expected behavior

Install the Extension "HentaiNexus"
Click on Browse towards "Sources"
List of the Manga Appears
Search "Good Luck Charm" on the Search Bar.
Three Listings will appear:
1. Good Luck Charm by Iwasaki Yuuki
2. Good Luck Charm by Wabara Hiro
3. Good Luck Charm by  NaPaTa
Save them all on the Library.
Try to download one of them.
Only one will be considered already downloaded.

### Actual behavior

Install the Extension "HentaiNexus"
Click on Browse towards "Sources"
List of the Manga Appears
Search "Good Luck Charm" on the Search Bar.
Three Listings will appear:
1. Good Luck Charm by Iwasaki Yuuki
2. Good Luck Charm by Wabara Hiro
3. Good Luck Charm by  NaPaTa
Save them all on the Library.
Try to download one of them.
All of them will be considered already downloaded.

### Mihon/Tachiyomi version

Mihon Version 0.16.5

### Android version

Android 13

### Other details

Can't make a example of a download screenshot since the extension is currently broken.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
this is an app issue. [mihon#371](https://togithub.com/mihonapp/mihon/issues/371)
