### ISSUE TITLE
flixscans.site changed to flixscans.org

### ISSUE THREAD

**Issue by AthanFields** [keiyoushi/tachiyomi-extensions-source#3529]
### Source information

FlixScans 1.4.6

### Source language

English

### Source new URL

https://flixscans.org/webtoons/action/home

### Other details

The source has divided the site in two different base url, the action part and the romance section. The following are the urls:
https://flixscans.org/webtoons/action/home
https://flixscans.org/webtoons/romance/home

The site has Cloudflare protection.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by AthanFields** [comment]
It's this extension the points to the wrong url.

The source main page:
![Screenshot_2024-06-11-18-06-04-466_app mihon](https://github.com/keiyoushi/extensions-source/assets/22866962/d2223b8e-65df-4743-beca-152f4ceda321)
The Cloudflare protection:

![Screenshot_2024-06-11-18-06-14-102_app mihon](https://github.com/keiyoushi/extensions-source/assets/22866962/365daa32-7c14-4606-ac7e-760179131c8b)

The WebView which loads the new site:
![Screenshot_2024-06-11-18-06-25-279_app mihon](https://github.com/keiyoushi/extensions-source/assets/22866962/10080e89-3fb0-4b3d-93bb-283906609a4c)

The extension info page:
![Screenshot_2024-06-11-18-10-34-850_app mihon](https://github.com/keiyoushi/extensions-source/assets/22866962/15c10ec6-c44a-44ef-a1ed-857d2b7b17f4)

**Comment by Smol-Ame** [comment]
Known issue, either wait for a fix or migrate to a different source.

The extension needs to be completely redone due to changes from the source apparently.

**Comment by AthanFields** [comment]
Thanks for the response, will do.
