### ISSUE TITLE
Remove LuraToon

### ISSUE THREAD

**Issue by nomaxsnx** [keiyoushi/tachiyomi-extensions-source#3530]
### Source name

Lura toon 1.4.53

### Source language

Português 

### Source link

https://lura-toons.com/

### Other details

Thanks to the damned "Empresário", Luraton stopped being free, you can only read it now by paying, I don't know the extension allows you to read paid works (although it's not even theirs). 

![Screenshot_2024-06-11-20-31-29-116_com discord](https://github.com/keiyoushi/extensions-source/assets/157644160/848c396e-e6dd-46f8-9adb-9248c1df0ee9)

![Screenshot_2024-06-11-20-31-34-026_com discord](https://github.com/keiyoushi/extensions-source/assets/157644160/4ab0eac6-ade9-43b5-a2b3-d96df8a55143)

![Screenshot_2024-06-11-20-31-38-489_com discord](https://github.com/keiyoushi/extensions-source/assets/157644160/220bca9e-e151-42c3-ba05-117c00b3ab34)

To read from now on, you have to pay 7 reais (brl) a month

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by gamespvp93** [comment]
I don't think it's necessary to remove the extension. I believe it would be better to update it. This way, whoever is using Mihon would only need to log in to the website through the extension and use Mihon normally. I think now that the website is paid, there is no problem in using Mihon, as there are no ads on both the website and the app.

**Comment by Norsze** [comment]
The main issue is that a dev would have to sub just to test it. If no one wants to do it then you unfortunately ain't getting anything

**Comment by HyungSilver** [comment]
cobrar para ler pirataria kkk essa é nova, devia era arrumar uma forma de burlar isso

**Comment by EvaldoCeBr** [comment]
There is no reason to end the source.  As already said, just update the source to a login system and log in to the website in the same way as DemonSect.  If you have a login and password, great, if you don't, look for other means!

**Comment by nomaxsnx** [comment]
Even with the login system (whose create and say login), I always see chapter shows that there is no chapter. 

When I go to web views and click on the chapter, it returns to the site's home menu.

**Comment by nomaxsnx** [comment]
![Screenshot_2024-06-12-19-39-52-099_app mihon](https://github.com/keiyoushi/extensions-source/assets/157644160/251d4afa-18fe-49a0-bc8f-248cbec6cfed)

**Comment by choppeh** [comment]
🙄🫤😑🤐😶.

**Comment by bapeey** [comment]
> When I go to web views and click on the chapter, it returns to the site's home menu.

If it doesn't work on the site itself, don't expect it to work in the extension as well. Maybe users will require a special account

**Comment by nomaxsnx** [comment]
> > When I go to web views and click on the chapter, it returns to the site's home menu.
> 
> If it doesn't work on the site itself, don't expect it to work in the extension as well. Maybe users will require a special account

Yes, special account and paying 7 reais (brl) per month, but I'm already migrating and then I'll delete the extension because of this luratoon mess, almost every scan in the world will take all their works. 

I'll leave the issues open for you to decide what to do.

Because I'm going to report all their works to the DMCA (it may take a while, but one day it will come).

**Comment by AwkwardPeak7** [comment]
since it was not removed, users with issues who have site's premium account can open new issue
