### ISSUE TITLE
Mangas Online PTBR trocou de dominio

### ISSUE THREAD

**Issue by IvanDrakko** [keiyoushi/tachiyomi-extensions-source#3532]
### Source information

apk/tachiyomi-pt.mangasonline-v1.4.30.apk

### Source language

Portugues Brasil

### Source new URL

https://mangaonline.biz/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
There are two extensions with similar names
  - Mang**ás** Online (https://mangasonline.cc) - Not working
  - Manga Online (https://mangaonline.biz) - Working

Mang**ás** Online (https://mangasonline.cc) seems to be down.

**Comment by choppeh** [comment]
This source is down

**Comment by choppeh** [comment]
> ### Source new URL
> 
> https://mangaonline.biz/

This url is implemented at https://keiyoushi.github.io/extensions/#pt.mangaonline
