### ISSUE TITLE
Slime Read gives http error 504, when searching or trying to open a file.

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#3534]
### Source information

SlimeRead 1.4.8

### Source language

Portuguese Brazilian 

### Steps to reproduce

When trying to search when opening a chapter, Source Slime Read gives http error 504.
![Screenshot_2024-06-12-15-20-33-746_app mihon](https://github.com/keiyoushi/extensions-source/assets/169321265/4ad256d0-b159-43ab-a574-76aa98af531e)
![Screenshot_2024-06-12-15-19-42-863_app mihon](https://github.com/keiyoushi/extensions-source/assets/169321265/6dfca95d-c48f-4be4-be33-ffb4114baea3)

### Expected behavior

Show search results and open image files from the source.

### Actual behavior

An error occurs when trying to open a file or when performing a global search.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Check WebView or in your own browser to see if you can load up a chapter from anything. I wasn't able to when I tried. If you can't load up a chapter in your browser, I think their servers are having an issue

**Comment by EvaldoCeBr** [comment]
> Check WebView or in your own browser to see if you can load up a chapter from anything. I wasn't able to when I tried. If you can't load up a chapter in your browser, I think their servers are having an issue

WebView working!
![Screenshot_2024-06-12-15-42-20-054_app mihon](https://github.com/keiyoushi/extensions-source/assets/169321265/0ec5b4a7-913b-4b9c-8320-cacb60d0c47a)

**Comment by EvaldoCeBr** [comment]
The source sometimes works and sometimes doesn't!
