### ISSUE TITLE
Dmc scan cant read / download chapter

### ISSUE THREAD

**Issue by samanta-widjaja** [keiyoushi/tachiyomi-extensions-source#3537]
### Source information

DMC scan 1.4.10

### Source language

English

### Steps to reproduce

1. Update chapter list, and the new chapter show up
2. Download / read chapter from app not working, says no page
3. From webview is fine and the chapter is not an advance chapter which must pay

### Expected behavior

Can read / download

### Actual behavior

Can't read / download

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Just curious, what's the title & chapter that's giving you this issue?

**Comment by samanta-widjaja** [comment]
I tried it again just now and it's fine. Thank you
