### ISSUE TITLE
Mangás Chan is Down

### ISSUE THREAD

**Issue by GMak9** [keiyoushi/tachiyomi-extensions-source#3543]
### Source name

Mangás Chan

### Source language

Brazilian Portuguese

### Source link

https://mangaschan.net/

### Other details

Web page not available, [error 403](https://foradoar.org/mangaschan.net)

The webpage could not load at the  address because:
net::ERR_NAME_NOT_RESOLVED

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
Official close.

<img width="300px" src="https://github.com/keiyoushi/extensions-source/assets/156493704/a69d361c-7b31-41b8-b469-5f3b060c5c32" />

**Comment by GMak9** [comment]
Infelizmente, disponibilizar conteúdo de fan-pra-fan está insustentável no Brasil, após o advento dos manhwas as empresas dententoras dos seus respectivos direitos, como a tappytoon, vem se dedicando incansávelmente à por um fim nestas tentativas, o número de reclamações/requisições na [lumen](https://lumendatabase.org/) para ações no Brasil cresceu vertiginosamente nos últimos 3 anos.
