### ISSUE TITLE
Ler Mangá Online is Down

### ISSUE THREAD

**Issue by GMak9** [keiyoushi/tachiyomi-extensions-source#3544]
### Source name

Ler Mangá Online

### Source language

Brazilian Portuguese

### Source link

https://lermangaonline.com.br/

### Other details

Web page not available
The web page could not be loaded at the address because:

net::ERR_NAME_NOT_RESOLVED

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
There's https://lermangaonline.blog/, but I'm not sure if it's the same source.

**Comment by GMak9** [comment]
They are not the same, although it is only possible to change the domain.

**Comment by choppeh** [comment]
> https://lermangaonline.blog/,

Yes, maybe it's not the same owner. I checked the domain metadata
