### ISSUE TITLE
Crear Notificaciones

### ISSUE THREAD

**Issue by Striven100** [keiyoushi/tachiyomi-extensions-source#3557]
### Describe why this should be added

Algunas fuentes o algunos mangas/manhwas no se actualizan ni muestran notificaciones aunque actualizes tu biblioteca. A mi me gusta tener las notificaciones en mi celular para que me recuerde leer mis mangas cuando tenga tiempo. Pero, si no se actualizan no dejan notificaciones. Estaria bueno tener una opcion que te deje notificaciones de los capitulos no leídos para leerlos despues.

### Other details

![Screenshot_20240613-225217_Tachiyomi](https://github.com/keiyoushi/extensions-source/assets/138946506/077e9faf-2921-4a1a-86dd-93aa85836173)
![Screenshot_20240613-225234_Tachiyomi](https://github.com/keiyoushi/extensions-source/assets/138946506/2a922f7c-d01e-4f71-b393-a4caafc04238)
![Screenshot_20240613-225223_Tachiyomi](https://github.com/keiyoushi/extensions-source/assets/138946506/14271388-3338-48e3-80ca-03d324328d1a)
![Screenshot_20240613-225526_Tachiyomi](https://github.com/keiyoushi/extensions-source/assets/138946506/cd9dd6a9-ccf1-44c2-94e2-b67be26bf88a)
![Screenshot_20240613-225440_Chrome](https://github.com/keiyoushi/extensions-source/assets/138946506/2dadc19c-7c94-4301-b0f2-ad4afa783baf)

Esta es una idea que vengo pensando desde hace tiempo, espero que ayude.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Las extensiones no pueden dejar notificaciones, deberías hacer tu solicitud en el repositorio de la app que estés usando.
