### ISSUE TITLE
Flix scans changed their domain

### ISSUE THREAD

**Issue by JustCBear** [keiyoushi/tachiyomi-extensions-source#3558]
### Source name

Flix scans

### Source language

English

### Source link

flixscans.org

### Other details

They changed their domain to ayoub-zrr.xyz

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #3540

Search the existing issues first before opening a new one, and acknowledging that you did.
