### ISSUE TITLE
HentaiNexus sometimes didnt show picture cover

### ISSUE THREAD

**Issue by PahleviEins** [keiyoushi/tachiyomi-extensions-source#3562]
### Source information

HentaiNexus 1.4.10

### Source language

English

### Steps to reproduce

1. Open Tachiyomi
2. Select Browse
3. Select HentaiNexus
4. Select Manga
5. Cover didnt show

### Expected behavior

When select manga at HentaiNexus, cover pictureshowing. And even its not showing, after refreshing at selected manga the cover showing up

### Actual behavior

When select manga at HentaiNexus, cover picture didnt showing even after refresh

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 14 (HyperOS Xiaomi)

### Other details

![hn](https://github.com/keiyoushi/extensions-source/assets/111588366/aeeef8e1-c158-45ce-8621-445e1a6ae51e)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MediocreLegion** [comment]
Looking at the webpages, the thumbnails are not in a `.card-image img` anymore, I think that the extension is actually fetching the first page of the title instead, but I'm not sure why the behavior is inconsistent when fetching.
