### ISSUE TITLE
HentaiNexus: unable to fetch some thumbnails

### ISSUE THREAD

**Issue by MediocreLegion** [keiyoushi/tachiyomi-extensions-source#3566]
### Source information

HentaiNexus 1.4.10

### Source language

English

### Steps to reproduce

Open HentaiNexus and browse a bit

### Expected behavior

Every title has a thumbnail

### Actual behavior

A few titles appear without a thumbnail

### Mihon/Tachiyomi version

TachiSY 1.10.5

### Android version

Android 13

### Other details

Looking at the webpages, the thumbnails are not in a `.card-image img` anymore, I think that the extension is actually fetching the first page of the title instead, but I'm not sure why the behavior is inconsistent when fetching.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #3562

Search the existing issues first before opening a new one, and acknowledging that you did.

If you want, you could comment in the other issue with the "Other details" you wrote, in case it helps a contributor out with the issue, along with getting notified if there's extra troubleshooting or any fixes for the issue

**Comment by MediocreLegion** [comment]
Oh sorry, I searched it a couple of days ago but only really had time to write the issue now. I'll close this issue and add the comment on the other issue.

**Comment by MediocreLegion** [comment]
Actually, searching `is:issue is:open nexus` still returns nothing, that's why I didn't see it, I should have searched the full name instead.
