### ISSUE TITLE
New domain changed, Sussy Scan.

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#3567]
### Source information

Sussy Scan 1.4.37

### Source language

Portuguese Brazilian 

### Source new URL

https://old.sussytoons.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by nomaxsnx** [comment]
https://old.sussytoons.com e https://sussytoons.com

Suporte pra 2 url pois provavelmente irão remover esse: "old".

**Comment by EvaldoCeBr** [comment]
> https://old.sussytoons.com e https://sussytoons.com
> 
> Suporte pra 2 url pois provavelmente irão remover esse: "old".

Will both URLs be supported?

**Comment by Behemoths15** [comment]
> https://old.sussytoons.com e https://sussytoons.com
> 
> Suporte pra 2 url pois provavelmente irão remover esse: "old".

It's Un necessary, the owner has confirmed that the domain with "old" will be the final one.

**Comment by Jefferson199809** [comment]
O problema persiste não está dando pra ler nada nessa extensão

**Comment by EvaldoCeBr** [comment]
> O problema persiste não está dando pra ler nada nessa extensão 

Ainda não lançaram a atualização.

**Comment by Jefferson199809** [comment]
Tem alguma previsão para a atualização?

**Comment by EvaldoCeBr** [comment]
> Tem alguma previsão para a atualização?
> 

Amigo, como o sistema é mantido por voluntários que ajudam em seu tempo livre não existe prazo fixo para nenhum serviço. Desaconselho a fazer qualquer tipo de cobrança, pois alguns podem responder ao seu questionamento de maneira rude!

**Comment by Jefferson199809** [comment]
Me desculpe
