### ISSUE TITLE
Cypher Scans extension Download function not working

### ISSUE THREAD

**Issue by sovit042** [keiyoushi/tachiyomi-extensions-source#357]
### Source information

Cypher Scans 1.4.27

### Source language

English

### Steps to reproduce

1. Open the Cypher scans extension
2. Open any series you like
3. Click on the download button on any chapter and wait and the download will fail eventually 

### Expected behavior

After starting a download it should download normally just like how it happens with other extensions

### Actual behavior

You will notice it takes house to download a chapter and at the end download fails showing no network connection available.
![Screenshot_2024-01-19-01-26-09-051_eu kanade tachiyomi](https://github.com/keiyoushi/extensions-source/assets/101596014/33b2063e-597c-48d3-9b6e-cf83a33da35c)

### Tachiyomi version

0.15.3

### Android version

Android 10

### Other details

I reported this problem before waited for ur response for 4 days but no reply so I am deleting and posting again plz help

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by NotBlankyu** [comment]
Don't open the same issue multiple times to bump it . 
Also can't replicate it, downloads fine for me

**Comment by beer-psi** [comment]
Do not bump issues by closing the old one and opening a new one. Furthermore, requests and issues here are meant as a suggestion for developers, not something developers *must* look into in a specific timeframe.

**Comment by sovit042** [comment]
Bro I thought they missed that post by mistake so I reported it again I am sorry if it created problem for you
