### ISSUE TITLE
Can't load Asura scans

### ISSUE THREAD

**Issue by Ashlyn07** [keiyoushi/tachiyomi-extensions-source#3584]
### Source information

1.4.34

### Source language

English - EN

### Steps to reproduce

1. Open Tachiyomi SY
2. Open said source

### Expected behavior

i can load list of manga in said source

### Actual behavior

can't load it and it say : "SocketTimeoutException: timeout" and I can't load it in webview too

### Mihon/Tachiyomi version

Tachiyomi SY 1.10.5

### Android version

Android 11

### Other details

Sometimes I can load it but it takes a long time, this problem has been happening for me for 5 days.

I can open it normally on Chrome but not on Mihon and Tachiyomi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Ashlyn07** [comment]
![Screenshot_2024-06-15-21-39-18-98_a603e4da04bada03cae438f177815547](https://github.com/keiyoushi/extensions-source/assets/85921518/cb8c6bd3-2432-4542-b3ce-f2ef56d25c3d)
![Screenshot_2024-06-15-21-54-59-29_551f7f0ca926862b368845ce7ee433aa](https://github.com/keiyoushi/extensions-source/assets/85921518/c03c1995-fc06-4341-ad89-946b53fdd7de)

**Comment by ssujsh** [comment]
my asura scans has also been very buggy. I always get a timeout whenever trying to load a manhwa wondering if you also have the same problem?

**Comment by ARiyou2000** [comment]
> my asura scans has also been very buggy. I always get a timeout whenever trying to load a manhwa wondering if you also have the same problem?

Have you tried changing your internet connection or tying connection over a VPN? specially if your from country such as Iran, this could solve your issue.

**Comment by Norsze** [comment]
Closing this as it is essentially a different/new extension since they made a new website
