### ISSUE TITLE
Trocaram o URL da extensão Sussy Scan 

### ISSUE THREAD

**Issue by Astatrevo** [keiyoushi/tachiyomi-extensions-source#3588]
### Source information

Sussy Scan 1.4.37

### Source language

Português Brasil - PT-BR

### Source new URL

https://old.sussytoons.com/

### Other details

![Screenshot_20240615-135436](https://github.com/keiyoushi/extensions-source/assets/172918910/787fc4e7-1d76-47a3-9865-6d5546d4ccbc)

### Acknowledgements

- [X] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Astatrevo** [comment]
I'm not the one who wrote the other complaint, I just asked them to update it because I was trying to read it and couldn't

**Comment by Norsze** [comment]
@Astatrevo 

> I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open or closed issue.

You checkmarked this, if you can't read English and don't know how to translate stuff maybe you should stay off this repository 

> Pesquisei os problemas existentes e este é um ticket novo, NÃO duplicado ou relacionado a outro problema aberto ou fechado.

Você marcou isto, se você não sabe ler inglês e não sabe como traduzir coisas, talvez você deva ficar fora deste repositório
