### ISSUE TITLE
Slime Read does not show content in the popular tab (button).

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#3590]
### Source information

SlimeRead 1.4.11

### Source language

Portuguese Brazilian 

### Steps to reproduce

When opening the source it does not show the content of the popular tab (button). The content appears in the WebView and in the recent tab normally.

![Screenshot_2024-06-15-17-20-35-451_app mihon](https://github.com/keiyoushi/extensions-source/assets/169321265/edb8156c-fbe3-4073-aa8b-7a850d2177b6)
![Screenshot_2024-06-15-17-20-38-822_app mihon](https://github.com/keiyoushi/extensions-source/assets/169321265/a7fa61f3-45b5-4d4b-8435-a8dbe6c458b8)
![Screenshot_2024-06-15-17-20-28-969_app mihon](https://github.com/keiyoushi/extensions-source/assets/169321265/348fea09-3f86-4502-a69a-430cca480d5b)

### Expected behavior

The content of the popular tab appears.

### Actual behavior

The content of the popular tab does not appear.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Other details

Recent maintenance and migration has been performed on the host.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
As already say in #3044, its a site issue, wait for them to fix
