### ISSUE TITLE
Manhastro Timeout Error - (WebView Normal)

### ISSUE THREAD

**Issue by Padahjj** [keiyoushi/tachiyomi-extensions-source#3594]
### Source information

Manhastro 1.4.41

### Source language

Brazilian Portuguese

### Steps to reproduce

1. Open the extension
2. Search for a work 

### Expected behavior

The works should appear when you open the extension.

### Actual behavior

Timeout error appears.

![20240615_194042](https://github.com/keiyoushi/extensions-source/assets/87540723/cf1c1768-ccd0-4369-99dc-8619ed606c6b)

### Mihon/Tachiyomi version

1.7.4

### Android version

Android 14

### Other details

I cleaned everything, cookies, cache etc, but this error is still appearing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by GMak9** [comment]
If you are using tachiJ2K, this error is occurring. The default recommendation is to change the UA, but I recommend migrating to Mihon or TachiSY.
