### ISSUE TITLE
Domain changed FlowerManga (PT-BR Source)

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#3604]
### Source information

FlowerManga.com 1.4.36

### Source language

Portuguese Brazilian 

### Source new URL

https://flowermangas.com

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by EvaldoCeBr** [comment]
Sorry I couldn't find another ticket in the search, can you tell me what it is?

**Comment by vetleledaal** [comment]
The issue closer mistakenly thought the name of the extension (FlowerManga.com) was the new URL.
