### ISSUE TITLE
Trocaram URL da extensão sussy scan

### ISSUE THREAD

**Issue by Felpzomior** [keiyoushi/tachiyomi-extensions-source#3609]
### Source information

Sussy scan 1.4.38

### Source language

Português Brasil - PT-BR

### Source new URL

old.sussytoons.com

### Other details

![Screenshot_20240616_102253_Mihon](https://github.com/keiyoushi/extensions-source/assets/172983611/d76c4c46-e8c1-4a6e-8405-c4aaba21db58)
![Screenshot_20240616_102321_Mihon](https://github.com/keiyoushi/extensions-source/assets/172983611/dc617001-4889-4659-ae20-bc6b8f5ab0d0)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
The domain was recently changed in  #3577. If you're experiencing an issue with the extension you should open a bug report explaining the issue in more detail.
