### ISSUE TITLE
MyReadingManga Unbale to grab selector

### ISSUE THREAD

**Issue by CactusTheGuy** [keiyoushi/tachiyomi-extensions-source#361]
### Source information

MyReadingManga 1.4.49

### Source language

Multi

### Steps to reproduce

1. Enter the MyReadingManga source (bypass the cloudflare)
2. Wait for it to done loading
3. After it done loading, press "Filter" at the top middle screen
4. Press "Reset" on the left screen several times
5. Press any selector below the "Sort by" selector
![Screenshot_2024-01-19-05-39-49-277_app mihon](https://github.com/keiyoushi/extensions-source/assets/75614340/27655ffc-a718-46b9-bb72-e9b644cef3ad)

### Expected behavior

The selector have more than 2 selections

### Actual behavior

The selector only have 2 to select that is "Any" and "Press Reset to try again"

### Tachiyomi version

Mihon 0.16.1

### Android version

MIUI 14 Android 13

### Other details

This does not happen to all of others extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Duplicate of #314
