### ISSUE TITLE
demon sect is not downloading the chapters

### ISSUE THREAD

**Issue by Gucost** [keiyoushi/tachiyomi-extensions-source#3616]
### Source information

Demon sect 1.4.43

### Source language

Português brasil PT-BR

### Steps to reproduce

extension is not downloading chapters to read offline. However, it is possible to read the page without downloading

### Expected behavior

You can download the chapters to read offline

### Actual behavior

However, don't download all the pages, just the first and last
![Screenshot_2024-06-17-00-02-17-463_app mihon](https://github.com/keiyoushi/extensions-source/assets/173020717/d89ca041-cc6a-4a22-b4ab-d87103f87629)
![Screenshot_2024-06-17-00-02-23-131_app mihon](https://github.com/keiyoushi/extensions-source/assets/173020717/c6b4f25b-ae93-4725-921c-75301535a788)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by EvaldoCeBr** [comment]
.

**Comment by Gucost** [comment]
Of the 34 pages, only 6 were downloaded

**Comment by AshbornXS** [comment]
that's fucking annoying, had like, 40+ chapters downloaded just to realize that the downloads are bugged

**Comment by TwiceHit** [comment]
I tried and is dowloading all pages, but most of the pages are with .bin extension for some reason, i renamed to jpg and worked fine

**Comment by Gucost** [comment]
Could you show me how you do it? TwiceHit

**Comment by Smol-Ame** [comment]
Just wait for an extension update, there's a proposed fix for this issue already

**Comment by Gucost** [comment]
Ok thanks
