### ISSUE TITLE
Sources missing bookmarkings on chapters

### ISSUE THREAD

**Issue by lalalasupa0** [keiyoushi/tachiyomi-extensions-source#3617]
### Source information

Luminous 1.4.36

### Source language

English

### Steps to reproduce

open manga
look at the chapters you know you bookmarked last time you opened the source

### Expected behavior

I should be able to see them

### Actual behavior

No bookmarks at all

### Mihon/Tachiyomi version

Yokai Nightly r5296

### Android version

Android

### Other details

![Screenshot_20240616_220227_Ykai Nightly](https://github.com/keiyoushi/extensions-source/assets/101371218/de247e6b-3324-4b54-b135-0561863c8f9a)
Proof; this screenshot is from the manhwa Legend of the Northern Blade. Who in their right mind wouldn't have chapters bookmarked (as favorites or whatever) there?

It has also happened to me with BokugenTranslation (ES), Mangas No Sekai (ES), and _many_ others; I can't remember their names
Happens more often in Luminous tho

*Not an app (fork) issue
*Idk the period of time in which the bookmarkings disappear
*Not a website issue (the site doesn't update the chapters at all)
Also asked in discord some time ago and came to nothing

I truly hope i'm not the only one with this problem

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
They changed chapter urls often which leads to bookmarks being lost, nothing we can do about it
