### ISSUE TITLE
Manhastro is apparently possessed

### ISSUE THREAD

**Issue by Shido33** [keiyoushi/tachiyomi-extensions-source#3621]
### Source information

Manhastro 1.4.41

### Source language

Portugues Brasil

### Steps to reproduce

1 crashes when trying to read the chapters
2 and very slow
3 the extension does not work at night

### Expected behavior

I hope it stops crashing and you can read the manga at any time

### Actual behavior

The mangas are difficult to load and keep freezing, causing the app to restart, making it impossible to read

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Other details

At night the extension does not carry any manga in it, so there is nothing to look for any manga there

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Edit title to "Manhastro is apparently possessed"

**Comment by AwkwardPeak7** [comment]
please provide more information

**Comment by GMak9** [comment]
Hello, I've been using the latest preview versions of both, Mihon and TachiSY, and I noticed that two problems occur in these versions:
1.: Problem in "Webtoon reading mode: Long strip and long strip with gaps", the possible solution at the moment is to use the "paged" reading mode 
2.: The extensions are slow, even the local files, but in the end it won't take long to use, in some cases it never seems like it will load. There is no solution for this case. Will have to wait for updates from Mihon.

*In neither case does a crash occur
