### ISSUE TITLE
The Blank Redirection 

### ISSUE THREAD

**Issue by dhanrahl** [keiyoushi/tachiyomi-extensions-source#3624]
### Source information

The Blank Scanlation 1.4.37

### Source language

English 

### Steps to reproduce

Opening source 

### Expected behavior

Should open source 

### Actual behavior

Redirects to discord invite link. 

### Mihon/Tachiyomi version

TachiyomiYS 1.10.5

### Android version

Android 13

### Other details

Tried different user agents but all direct to discord on all platforms. May be something they've done intentionally, or by accident; Unsure if that matters for the purposes of this extension. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
site is down

**Comment by dhanrahl** [comment]
I was able to open the site exactly once before I made the ticket, which is what led me to submit it. I suppose it might have loaded from cache which led to confusion. Thanks for the update.
