### ISSUE TITLE
Quero pedir uma nova extensão que surgiu no português Brasileiro 

### ISSUE THREAD

**Issue by Maryyyyy90** [keiyoushi/tachiyomi-extensions-source#3626]
### Source name

Mangá kun

### Source link

https://mangakun.com/

### Source language

Português Brasil - PT-BR

### Other details

![Screenshot_20240617_224336_Chrome](https://github.com/keiyoushi/extensions-source/assets/173117784/bbdf6274-1867-4dbc-8bda-60f302e27cf8)
![Screenshot_20240617_224401_Mihon](https://github.com/keiyoushi/extensions-source/assets/173117784/bef46ace-5183-4341-801b-30a187eaa6a9)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
This source doesn’t have a reader.
