### ISSUE TITLE
Bato.to not loading, kept showing SSL Error

### ISSUE THREAD

**Issue by bloodfalcon2001** [keiyoushi/tachiyomi-extensions-source#3632]
### Source information

Bato.to 1.4.36

### Source language

Multi

### Steps to reproduce

1. Open Mihon
2. Goes to Browse tab
3. Click on Sources
4. Click on Bato.to extension Sources

### Expected behavior

Loading of manga list on Bato.to should happen

### Actual behavior

Always showing SocketException: Connection Reset and cannot load manga list. On my tablet, it shows "SSLHandshakeException: SSL handshake aborted: ssl=0x6f5f6989c8: I/O error during system call, Connection reset by peer"

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
your isp/router is blocking you, change to a different mirror in extension settings or use a vpn
