### ISSUE TITLE
Adicionar a fonte nova da One Piece Ex

### ISSUE THREAD

**Issue by DeBoaBaby** [keiyoushi/tachiyomi-extensions-source#3635]
### Source name

One Piece Ex

### Source link

https://opexcast.com.br

### Source language

Português Brasil (PT-BR)

### Other details

![Screenshot_20240618_153330_Brave](https://github.com/keiyoushi/extensions-source/assets/159880989/c834018d-1ec2-4db0-854b-8ce9e2a1f102)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
This source doesn’t have a reader.

**Comment by Norsze** [comment]
Can't make a manga extension if there is no manga reader or any pages.
