### ISSUE TITLE
Sussy Scan (PT-BR Source) changed the domain.

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#3636]
### Source information

Sussy Scan 1.4.38

### Source language

Portuguese Brazilian 

### Source new URL

https://oldi.sussytoons.com

### Other details

When you enter https://old.sussytoons.com through the browser or WebView, you are redirected to https://oldi.sussytoons.com.  It is still possible to access the works through the app, but the works are only updated at this last address.

![Screenshot_2024-06-18-19-49-36-028_app mihon](https://github.com/keiyoushi/extensions-source/assets/169321265/caae7893-5585-4cb1-ac5c-ff07e0da51a6)
![Screenshot_2024-06-18-19-50-30-402_com android chrome](https://github.com/keiyoushi/extensions-source/assets/169321265/daf1dcbe-c525-4aa1-8891-86c518122eac)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Pedropaulo015** [comment]
Esse problema tá me incomodando queria ler os novos capítulos das obras mais não tá dando ainda no aplicativo

**Comment by EvaldoCeBr** [comment]
> Esse problema tá me incomodando queria ler os novos capítulos das obras mais não tá dando ainda no aplicativo

Há 2 dias mudaram novamente de domínio. Mas o mais curioso é que ainda dá para acessar as obras desatualizadas pelo app e ler.

**Comment by HyungSilver** [comment]
> > Esse problema tá me incomodando queria ler os novos capítulos das obras mais não tá dando ainda no aplicativo
> 
> Há 2 dias mudaram novamente de domínio. Mas o mais curioso é que ainda dá para acessar as obras desatualizadas pelo app e ler.

pse o problema é q não atualiza por conta do domínio novo
