### ISSUE TITLE
Diskus Scan (PT-BR Source) extension takes time to update chapters for download.

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#3637]
### Source information

Diskus Scan 1.4.39

### Source language

Portuguese Brazilian 

### Steps to reproduce

When the release appears on the scan website, it takes more than 2 hours to appear for download on the app, even when updating the source page.

### Expected behavior

That I could download the chapters as soon as the scan released them.

### Actual behavior

You need to wait more than 2 hours to update the source page and download.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by EvaldoCeBr** [comment]
![Screenshot_2024-06-18-22-02-43-367_app mihon](https://github.com/keiyoushi/extensions-source/assets/169321265/ebbc9e53-e50a-456b-9f32-827dfa8c99d9)
![Screenshot_2024-06-18-22-03-18-192_com android chrome](https://github.com/keiyoushi/extensions-source/assets/169321265/119fccf4-e36c-4380-93b7-129e96cf42c5)

**Comment by bapeey** [comment]
The extension takes the chapters from de manga page, not from the reader, this should be a site issue

**Comment by EvaldoCeBr** [comment]
> The extension takes the chapters from de manga page, not from the reader, this should be a site issue

Are they putting the link on Discord that goes directly to the reader, so you can read it without problems, and they only update the website page hours later, which is when the app has access to the files?

**Comment by choppeh** [comment]
This is the behavior of this site, so I don't think it's a problem.

It takes time to update the chapter list
