### ISSUE TITLE
Shinigami error 429 when updating libraries

### ISSUE THREAD

**Issue by kitsu2** [keiyoushi/tachiyomi-extensions-source#3640]
### Source information

Shinigami 1.4.57

### Source language

Indonesia

### Steps to reproduce

1.Update library 
2.And shinigami extension shows Error 429

### Expected behavior

Doesn't show Error 429

### Actual behavior

Shows Error 429

### Mihon/Tachiyomi version

0.16.5

### Android version

13

### Other details

When updating comics from the shinigami extension there are several comics that can be updated 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kitsu2** [comment]
![Uploading Screenshot_20240619-141400.jpg…]()

**Comment by Smol-Ame** [comment]
HTTP 429 usually means you hit a rate-limit, so you've been temporarily blocked from the source. Switch networks or use a VPN to see if that helps, otherwise, wait a few hours and try again then (and just in case, download less/download in batches)

Also you hit send too fast so your screenshot didn't fully upload

**Comment by kitsu2** [comment]
> a

I have used another network and the results are still the same, can't you lower the speed?

**Comment by kitsu2** [comment]
![Uploading Screenshot_20240619-141400.jpg…]()

**Comment by Smol-Ame** [comment]
> I have used another network and the results are still the same, can't you lower the speed?

In the code, it looks like there's already a rate-limit on our end to make it usable. Maybe a contributor/maintainer could give you a more definite answer later

**Comment by kitsu2** [comment]
Can this problem not be solved?
