### ISSUE TITLE
Lavinia Fansub: Identical chapter pages

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#3641]
### Source information

Lavinia Fansub 1.4.36

### Source language

Turkish 

### Steps to reproduce

Open lavinia fansub
Go to any series.

### Expected behavior

The chapter number should appear and it should download the wanted chapter. 

### Actual behavior

But the chapter number of the series does not appear. When you try to download any chapter of the series, it downloads all the chapter of the series and all the downloaded chapters are identical.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
cannot reproduce
