### ISSUE TITLE
Dark scans

### ISSUE THREAD

**Issue by Mohamed9789** [keiyoushi/tachiyomi-extensions-source#3642]
### Source information

Dark scans

### Source language

English 

### Source new URL

https://darkscans.net/

### Other details

Url change to
https://darkscans.net/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by forr34** [comment]
darkscans's new link is darkscans.net ???

**Comment by bapeey** [comment]
Seems like https://rightdark-scan.com is the other Dark Scan that was removed in #2894 that also has a [mirror](https://dark-scan.com). Both sites has the same content and last update was in April 7th, maybe is not active because is a secondary page from a Spanish scanlator.

The correct url for this Dark Scan is https://darkscans.net as forr34 said

**Comment by Mohamed9789** [comment]
> Seems like https://rightdark-scan.com is the other Dark Scan that was removed in #2894 that also has a [mirror](https://dark-scan.com). Both sites has the same content and last update was in April 7th, maybe is not active because is a secondary page from a Spanish scanlator.
> 
> The correct url for this Dark Scan is https://darkscans.net as forr34 said

Sorry i didn't know
I thought the website url is changed cause i tried multiple times to open the website and it didn't open like the url is closed

**Comment by Mohamed9789** [comment]
> Seems like https://rightdark-scan.com is the other Dark Scan that was removed in #2894 that also has a [mirror](https://dark-scan.com). Both sites has the same content and last update was in April 7th, maybe is not active because is a secondary page from a Spanish scanlator.
> 
> The correct url for this Dark Scan is https://darkscans.net as forr34 said

Sorry i didn't know
I thought the website url is changed cause i tried multiple times to open the website and it didn't open like the url is closed.

I just have tried now and it give me error 404 but the website still working
![Screenshot_2024-06-20-11-54-55-62_551f7f0ca926862b368845ce7ee433aa](https://github.com/keiyoushi/extensions-source/assets/66431487/7d71e7bd-0838-43b0-9071-669bb9ceccae)

**Comment by JannisJo** [comment]
Yes, pretty sure it should be darkscans.net
