### ISSUE TITLE
Omegascans under maintenance

### ISSUE THREAD

**Issue by Anonsbanon** [keiyoushi/tachiyomi-extensions-source#3646]
### Source information

Omega scans

### Source language

English

### Steps to reproduce

1. Open new on omega scans, dosent show new realeses.
2. Open webview, instead of normal site it is a discord invite.

### Expected behavior

New realeses should show webview would open omegascans Website.

### Actual behavior

New realeses wont show webview opens a invite to omega scans discord.

### Mihon/Tachiyomi version

Mihon stable 0.16.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KenjieDec** [comment]
Their Discord server says that the site is undergoing maintenance.
![image](https://github.com/keiyoushi/extensions-source/assets/65448230/05f66592-289c-4e06-908a-bf372a45c804)

**Comment by Norsze** [comment]
Edit title to "Omegascans under maintenance"

**Comment by Norsze** [comment]
Source is back online
