### ISSUE TITLE
Blackout Comics - 1.4.3

### ISSUE THREAD

**Issue by Yukizi** [keiyoushi/tachiyomi-extensions-source#3647]
### Source information

Blackout Comics - 1.4.3 (PT-BR Source) shows the same image for all works.

### Source language

Português 

### Steps to reproduce

1 - install the extension
2 - open
3 - Create an account to access the works
4 - read chapter

### Expected behavior

read chapter

### Actual behavior

When you click to read any chapter of any work, an image appears that prevents people from reading in the application.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by EvaldoCeBr** [comment]
When opening any file in the source this image appears:

![Screenshot_2024-06-22-16-20-53-504_app mihon](https://github.com/keiyoushi/extensions-source/assets/169321265/f48d6c9c-37fa-4af8-85f4-ebd0c9d6f495)

**Comment by EvaldoCeBr** [comment]
> ### Source information
> Blackout Comics
> 
> ### Source language
> Português
> 
> ### Steps to reproduce
> 1 - install the extension 2 - open 3 - Create an account to access the works 4 - read chapter
> 
> ### Expected behavior
> read chapter
> 
> ### Actual behavior
> When you click to read any chapter of any work, an image appears that prevents people from reading in the application.
> 
> ### Mihon/Tachiyomi version
> 0.16.5
> 
> ### Android version
> Android 12
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
> * [x]  I have updated all installed extensions.
> * [x]  I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
> * [x]  If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
> * [x]  I will fill out all of the requested information in this form.

You could put the title like this: Blackout Comics - 1.4.3 (PT-BR Source) shows the same image for all works.

**Comment by EvaldoCeBr** [comment]
A ideia que dei era pra por no título. Em Source Information vc pode deixar: Blackout Comics 1.4.3
