### ISSUE TITLE
Omegascans.org

### ISSUE THREAD

**Issue by manavchaudhary1** [keiyoushi/tachiyomi-extensions-source#3650]
### Source name

Omega scans 1.4.42

### Source language

English

### Source link

https://omegascans.org

### Other details

Site redirect to discord invite link

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by ShanaNyaa** [comment]
Issue already mentioned in #3646
