### ISSUE TITLE
Namicomi?

### ISSUE THREAD

**Issue by Itsyua** [keiyoushi/tachiyomi-extensions-source#3657]
### Source name

Namicomi

### Source link

https://namicomi.com/en

### Source language

English and more

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Itsyua** [comment]
That was 3 months ago i just nvm..

**Comment by Norsze** [comment]
It was, yet you making a duplicate won't make it more relevant for us, this is a ticket system, one ticket per issue or there will be unregulated chaos of duplicates and at the end we'll just abandon the whole project cause of the lack of regulation and system. This is for both the contributors and users, stick to the rules you accept when you send in an issue and actually do what you said you did

**Comment by Itsyua** [comment]
Sorry..
