### ISSUE TITLE
Páginas não está carregando 

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#3664]
### Source information

SSSScanlator 1.4.32

### Source language

Português (Brasil)

### Steps to reproduce

As páginas não estão carregando 
![Screenshot_20240620-173848](https://github.com/keiyoushi/extensions-source/assets/157044539/0f4c2a14-0b50-4195-b3fb-ca4d929e60d3)

### Expected behavior

As páginas tinha que carregar 

### Actual behavior

Não está carregando as páginas 

### Mihon/Tachiyomi version

Tachiyomi SY 1.10.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nomaxsnx** [comment]
Depois de um tempo ficando insistindo, pra carregar o site

Voltou, 429 (muita gente usando o site, pode ter sido sobrecarregado)

**Comment by ghost** [comment]
> Depois de um tempo ficando insistindo, pra carregar o site
> 
> Voltou, 429 (muita gente usando o site, pode ter sido sobrecarregado)

Acabei de ver no Discord deles, eles trocam a URL do site

**Comment by ghost** [comment]
Acho que ainda não atualizaram a extensão

**Comment by choppeh** [comment]
> > Depois de um tempo ficando insistindo, pra carregar o site
> > Voltou, 429 (muita gente usando o site, pode ter sido sobrecarregado)
> 
> Acabei de ver no Discord deles, eles trocam a URL do site

O dominio continua o msm da extensão, cloudflare do meu lado tá atrapalhando :face_with_diagonal_mouth: :
