### ISSUE TITLE
Problemas para instalar leercapitulo

### ISSUE THREAD

**Issue by Striven100** [keiyoushi/tachiyomi-extensions-source#3665]
### Source information

LeerCapituli

### Source language

Español

### Steps to reproduce

Me dirijo a Explorar<Extensiones<LeerCapitulo.
Descargo el apk.
Instalo la extension.
Cierro la app, pero cuando vuelvo a abrirla no aparece la extension.

### Expected behavior

Deberia poder instalarla como todas las demas extensiones

### Actual behavior

Cuando me fijo me dice que la descargue denuevo

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 10

### Other details

Nose porque. Creo q es algo de mi porque lei los issues y otros pueden usarla.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Verifica si realmente esta instalada en tu lista de aplicaciones (en la configuración del telefono), para poder ayudarte mejor únete al [server de discord](https://discord.gg/3FbCpdKbdY)

**Comment by kuvoid** [comment]
es posible que estés filtrando extensiones solo en español, comprueba en Extensiones si la tienes, sí es así, ábrela y marca Español y la tendrás en la lista de fuentes

**Comment by Striven100** [comment]
No creo q sea eso.
![Screenshot_20240620-214256_Package installer](https://github.com/keiyoushi/extensions-source/assets/138946506/de3a307a-53d3-42cf-a6dd-36106dc5e721)
![Screenshot_20240620-214252_Package installer](https://github.com/keiyoushi/extensions-source/assets/138946506/c6352059-75f8-45be-ac85-f9e1a2a935c1)

**Comment by AwkwardPeak7** [comment]
make sure you uninstall old tachi extensions before trying to install ones from here, for further help come to our discord as stated previously
