### ISSUE TITLE
SSS Scanlator (PT-BR Source) gives HTTP Error 409 when downloading.

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#3666]
### Source information

SSSScanlator 1.4.32

### Source language

Portuguese Brazilian 

### Steps to reproduce

When downloading on SSS Scanlator gives HTTP Error 409 when downloading. When opening in WebView or on the scan website, the files open normally.

![Screenshot_2024-06-20-20-55-18-555_app mihon](https://github.com/keiyoushi/extensions-source/assets/169321265/5cc30bfe-7092-4a80-b122-9f3d4b4bf421)
![IMG_20240620_205643](https://github.com/keiyoushi/extensions-source/assets/169321265/922460c8-2b23-46d8-9f6c-9b34b2e12c81)
![Screenshot_2024-06-20-20-52-17-764_app mihon](https://github.com/keiyoushi/extensions-source/assets/169321265/486ca8b0-930c-4acf-9109-383ee8156a4e)

### Expected behavior

Being able to read the chapters of the works and being able to download them to read offline.

### Actual behavior

You can't read it directly in the app or download it.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #3664

It's not the first time I told you this, search the existing issues, both open & closed, before opening a new issue & acknowledging that you did.
