### ISSUE TITLE
Spyfakku "No results found"

### ISSUE THREAD

**Issue by towermom9** [keiyoushi/tachiyomi-extensions-source#3670]
### Source information

Spyfakku 1.4.1

### Source language

English

### Steps to reproduce

1. install spyfakku
2. Trust spyfakku
3. open spyfakku

### Expected behavior

it should show all available manga in the main page

### Actual behavior

it just says "No results found"

### Mihon/Tachiyomi version

Mihon 0.16.5 stable

### Android version

Android 14 "HyperOS"

### Other details

![Screenshot_2024-06-21-10-13-41-246_app mihon](https://github.com/keiyoushi/extensions-source/assets/70556779/659f24a6-2036-441f-80e4-d1e3e49850c6)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by 0Ha16wA5** [comment]
The domain is changed from `spy.fakku.cc` to `fakku.cc`

**Comment by towermom9** [comment]
> The domain is changed from `spy.fakku.cc` to `fakku.cc`

but it automatically redirects, I thought it wouldn't matter

**Comment by towermom9** [comment]
fixed in #3712
