### ISSUE TITLE
Demon Sect False(?) Cloudflare Error

### ISSUE THREAD

**Issue by AshbornXS** [keiyoushi/tachiyomi-extensions-source#3672]
### Source information

Demon Sect 1.4.44

### Source language

Brazilian Portuguese

### Steps to reproduce

1. Open the extension
2. Pass cloudflare by opening it on webview
3. Try reloading the extension

### Expected behavior

it should pass cloudflare as shown in the webview and the fetch the manga from the extension

### Actual behavior

it keeps giving cloudflare error even though everything is alright on the webview

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Other details

tried cleaning cookies, changing UA and even reinstalling the extension, DoH is already enabled

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ghost** [comment]
Aqui está funcionando 
![Screenshot_20240621-030742](https://github.com/keiyoushi/extensions-source/assets/157044539/5e8923d7-58de-4172-94d6-1e9a5d2442df)

**Comment by AwkwardPeak7** [comment]
?blurb cf

**Comment by AwkwardPeak7** [comment]
try navigting to the popular/latest url in webview and passing cloudflare there, like `https://dsectcomics.org/manga/?m_orderby=views`

**Comment by AshbornXS** [comment]
tried that and worked one time, now it is the same as before, it passes on webview but on the app it keeps giving cloudflare error, maybe it's a problem with only me? idk, kinda strange since even after changing the UA the same thing happens
