### ISSUE TITLE
Source Request in PT BR

### ISSUE THREAD

**Issue by rodolfoadams** [keiyoushi/tachiyomi-extensions-source#3691]
### Source name

Central Novel

### Source link

centralnovel.com

### Source language

Portuguese - Brazilian

### Other details

Light novels in PTBR

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
Tachiyomi/Mihon doesn't support novels
