### ISSUE TITLE
komikcast.lol (id.komikcast) domain changed to komikcast.moe

### ISSUE THREAD

**Issue by Yefita** [keiyoushi/tachiyomi-extensions-source#3692]
### Source information

Komik Cast 1.4.57

### Source language

Indonesia

### Source new URL

https://komikcast.moe

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Kunaguero110** [comment]
Up sir
