### ISSUE TITLE
Tsuki Mangás: HTTP error 429 (Too Many Requests)

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#3695]
### Source information

Tsuki Mangás 1.4.5

### Source language

Português (Brasil)

### Steps to reproduce

Fica dando erro quando vou atualizar as obras, 
![Screenshot_20240622-015339](https://github.com/keiyoushi/extensions-source/assets/157044539/661386ad-7494-460b-902f-21cc264f4dce)

Também quando vou migrar também fica dando erro
![Screenshot_20240622-015851](https://github.com/keiyoushi/extensions-source/assets/157044539/c7a7125d-eb23-4111-897a-a2c341f0cd21)

### Expected behavior

Funcionar normalmente 

### Actual behavior

Fica dando erro

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Error 429 usually means you're downloading too much from the site. Did you confirm that the site works in WebView? Might need to change the rate limit in the extension if you're constantly running into this issue.

**Comment by choppeh** [comment]
RateLimit is set. The isse can be closed.
