### ISSUE TITLE
domain changed from .lol to .moe

### ISSUE THREAD

**Issue by kii1122** [keiyoushi/tachiyomi-extensions-source#3699]
### Source information

komik cast

### Source language

Indonesia 

### Source new URL

https://komikcast.moe/

### Other details

the domain changed yesterday, initially when opened it said "SocketException: Connection reset"when I tried the website it still didn't work, then a few hours later the admin of the website posted information on Facebook that their domain had changed from .lol to .moe
then I tried it on Google and it worked,but it hasn't changed in mihon

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by kii1122** [comment]
and this is not a duplicate

**Comment by kii1122** [comment]
it's not a duplicate

Pada Sab, 22 Jun 2024 4.52 PM, keiyoushi-bot ***@***.***>
menulis:

**Comment by vetleledaal** [comment]
It is a duplicate of #3692, which was fixed 2 hours ago. If you already updated to Komik Cast 1.4.58 and are having issues the correct template is 'issue report', not 'URL change report'

**Comment by kii1122** [comment]
Ok, thanks.
you're right this is fixed,hehe thanks man

Pada Sab, 22 Jun 2024 5.18 PM, Vetle Ledaal ***@***.***>
menulis:
