### ISSUE TITLE
Hentaivn false to bypass Cloudflare

### ISSUE THREAD

**Issue by leonminus** [keiyoushi/tachiyomi-extensions-source#3707]
### Source information

HentaiVN 1.4.33

### Source language

Vietnamese

### Steps to reproduce

Can't read or view in webview

### Expected behavior

Work as usual

### Actual behavior

"Bỏ qua Cloudflare thất bại"

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
?blurb cf
