### ISSUE TITLE
no extensions are seen or used  

### ISSUE THREAD

**Issue by Ctt7** [keiyoushi/tachiyomi-extensions-source#3709]
### Source information

All

### Source language

all 

### Steps to reproduce

1. open the application 
2.  go to extensions
3. only downloaded extensions are seen
4.  When trying to use them, a string validation error appears 
![Screenshot_20240617_142215_Mihon](https://github.com/keiyoushi/extensions-source/assets/173583466/473fb802-7f43-43e7-b3b8-60eed7a3ca11)

### Expected behavior

see an extension or that allows you to use the downloaded ones 

### Actual behavior

nothing is displayed and the downloaded ones are not useful 
![Screenshot_20240617_142222_Mihon](https://github.com/keiyoushi/extensions-source/assets/173583466/4815ccf3-331c-442b-8bfd-2478337d549b)

### Mihon/Tachiyomi version

App version: 0.16.5 (standard, 2a01a2a, 6, 2024-04-09T09:58:14Z) ) 

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
This could be internet-related issue, user-error issue, or device-related issue

Come to our Keiyoushi Discord repo-support channel for more help
