### ISSUE TITLE
KissLove is very slow to retrieve chapter list

### ISSUE THREAD

**Issue by KiRa937** [keiyoushi/tachiyomi-extensions-source#3716]
### Source name

KissLove

### Source language

Japanese

### Describe your suggested feature

Currently updating one manga title can take up to 1 minute. Is it possible to optimize chapter list update?

### Other details

This is one of the best sources for raw japanese manga. With dozens of titles from this source one global update can take quite some time to fully perform.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
cannot reproduce, the chapter list is relatively fast. maybe your internet was being slow or the site was just slow at the time.
