### ISSUE TITLE
Manhastro: latest updates don't show, chapter progress resets

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#3717]
### Source information

Manhastro 1.4.41

### Source language

Português (Brasil)

### Steps to reproduce

Não está aparecendo as últimas atualizações da extensão, extensão no app 
![Screenshot_20240623-115051](https://github.com/keiyoushi/extensions-source/assets/157044539/50a3af26-2763-4e54-8acc-09146f17826a)

Também tem um erro que os capítulos lidos ficam resetando, como se eu não tivesse lido ele

https://github.com/keiyoushi/extensions-source/assets/157044539/aaf5dce3-5706-48b9-9c68-0df89912fa64

### Expected behavior

Aparecer as atualizações normalmente 

Não resetar os capítulos lidos 

### Actual behavior

Não está mostrando as atualizações na mesma ordem do webview 

Fica resetando os capítulos já lidos 

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ghost** [comment]
Acabei esquecendo de colocar a do webview 
![Screenshot_20240623-115028](https://github.com/keiyoushi/extensions-source/assets/157044539/7d479cbf-4026-4efc-8a20-2637e870d345)



Foi mal ai

**Comment by EvaldoCeBr** [comment]
Aqui ta mostrando as últimas atualizações, vê ai novamente pra vc!

**Comment by Norsze** [comment]
The reason they reset is cause the source keeps changing the address for the chapters. Don't know if anything can be done about that. I imagine that is also the reason for the messed "recent" order, not sure though, too lazy to download it and look

**Comment by choppeh** [comment]
> The reason they reset is cause the source keeps changing the address for the chapters. Don't know if anything can be done about that. I imagine that is also the reason for the messed "recent" order, not sure though, too lazy to download it and look

Maybe the reason is that the ```mangaSubString``` has recently changed

I didn't reference this issue in #3732  because I'm not sure

**Comment by EvaldoCeBr** [comment]
> > The reason they reset is cause the source keeps changing the address for the chapters. Don't know if anything can be done about that. I imagine that is also the reason for the messed "recent" order, not sure though, too lazy to download it and look
> 
> Maybe the reason is that the `mangaSubString` has recently changed
> 
> I didn't reference this issue in #3732 because I'm not sure

Obg! Parece que resolveu!

**Comment by ghost** [comment]
> > > The reason they reset is cause the source keeps changing the address for the chapters. Don't know if anything can be done about that. I imagine that is also the reason for the messed "recent" order, not sure though, too lazy to download it and look
> > 
> > 
> > Maybe the reason is that the `mangaSubString` has recently changed
> > I didn't reference this issue in #3732 because I'm not sure
> 
> Obg! Parece que resolveu!

A biblioteca de mangá ainda tá bugado pra mim, o outro bug dos capítulos abaixo dos 100 resetando ainda não testei

**Comment by ghost** [comment]
Pra mim tem horas que fica assim quando eu atualizo a biblioteca de "mangás"


https://github.com/keiyoushi/extensions-source/assets/157044539/1e776ebe-6a13-406b-9a55-0a3d96e5714d

**Comment by EvaldoCeBr** [comment]
> abaixo

É verdade, achei que tinha concertado, mas os recentes do app, não estão condizendo com o WebView.

**Comment by choppeh** [comment]
> Pra mim tem horas que fica assim quando eu atualizo a biblioteca de "mangás"
> screen-20240627-191447.mp4

Há algum problema na fonte e não na extensão, nesse momento acabei de carregar o mesma obra  **_Return To Player_** e não são exidos os 50 primeiros caps. 

![image](https://github.com/keiyoushi/extensions-source/assets/156493704/e6a9ff79-412e-41f0-baa0-34d13ecc3283)

**Comment by ghost** [comment]
> > Pra mim tem horas que fica assim quando eu atualizo a biblioteca de "mangás"
> > screen-20240627-191447.mp4
> 
> Há algum problema na fonte e não na extensão, nesse momento acabei de carregar o mesma obra **_Return To Player_** e não são exidos os 50 primeiros caps.
> 
> ![image](https://private-user-images.githubusercontent.com/156493704/344205149-e6a9ff79-412e-41f0-baa0-34d13ecc3283.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1OTU4NzgsIm5iZiI6MTcxOTU5NTU3OCwicGF0aCI6Ii8xNTY0OTM3MDQvMzQ0MjA1MTQ5LWU2YTlmZjc5LTQxMmUtNDFmMC1iYWEwLTM0ZDEzZWNjMzI4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOFQxNzI2MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjFlNjhjYTliMGUyMGU4OTcxOGIzM2I5YzNjODg3NTBhMDY3MWZiYTBhMzZhODcwZDcxNzAxYjgzNmMxZDEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xVs-3eAh4Pa_nZogkWJy8ja7qNdtiQzmfCB_7IZSLTk)

Se a obra tiver mais de 100 capítulos vc precisa de uma conta no site para aparecer os capítulos abaixo do 100

**Comment by choppeh** [comment]
> Acabei esquecendo de colocar a do webview 

The latest one is OK, the extension uses the URL https://manhastro.com/lermanga/?m_orderby=latest instead of the home page.

**Comment by choppeh** [comment]
For chapters that have been reset, you need to check the "Lembrar-me" checkbox to stay logged in.
