### ISSUE TITLE
Blackout Comics - 1.4.3 (PT-BR Source) shows the same image for all works

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#3728]
### Source information

Blackout Comics 1.4.3

### Source language

Portuguese Brazilian 

### Steps to reproduce

When opening any work, the same image always appears in all of them.

![Screenshot_2024-06-24-13-11-45-818_app mihon](https://github.com/keiyoushi/extensions-source/assets/169321265/c43c5ca0-a41a-42e9-9caa-d0502e3053eb)

### Expected behavior

View original content.

### Actual behavior

The same image appears for all works.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #3647
