### ISSUE TITLE
The order scanlator

### ISSUE THREAD

**Issue by paz-web** [keiyoushi/tachiyomi-extensions-source#373]
### Source name

the Order Scanlator 

### Source link

https://theorderscan.online/

### Source language

PT BR 

### Other details

18+/= YES

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Site has been down for 2 weeks, closing this issue. You can open another source request if they reappear elsewhere.
