### ISSUE TITLE
Error 403 Sagrado Imperio da Britannia

### ISSUE THREAD

**Issue by GoodManBR** [keiyoushi/tachiyomi-extensions-source#3733]
### Source information

Sagrado Imperio da Britannia 1.4.36

### Source language

Portuguese Brazilian

### Steps to reproduce

When doing a search, Http Error 403 appears
![20240624_194944](https://github.com/keiyoushi/extensions-source/assets/167632870/8f3ef080-336c-4c52-a113-ae073b09b817)

### Expected behavior

Show search results.

### Actual behavior

Http Error 403 appears.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
It works fine. You need to check WebView and let the page load, then retry searching

Also duplicate of #3449 (with answer linked in comments)

**Comment by GoodManBR** [comment]
I checked the WebView and let the page load and it actually worked, thank you very much for your help.

**Comment by choppeh** [comment]
> I checked the WebView and let the page load and it actually worked, thank you very much for your help.

Close this issue
