### ISSUE TITLE
Nettruyenfull

### ISSUE THREAD

**Issue by kingtham** [keiyoushi/tachiyomi-extensions-source#3735]
### Source name

Nettruyen

### Source link

https://nettruyenfull.com/
https://nettruyenaa.com/
https://nhattruyenvn.com/
https://nettruyenviet.com/

### Source language

Vietnamese

### Other details

New nettruyen, sfw.

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
only one source per request only
