### ISSUE TITLE
Shinigami ID

### ISSUE THREAD

**Issue by Ktslovers99** [keiyoushi/tachiyomi-extensions-source#3737]
### Source information

Shinigami 1.4.57

### Source language

Indonesia

### Source new URL

https://shinigamitoon.app/

### Other details

Change domain shinigami ID shinigamitoon.id to shinigamitoon.app

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by WEPOXS** [comment]
https://github.com/keiyoushi/extensions-source/issues/1552

Can't you add this feature?

**Comment by Smol-Ame** [comment]
> Can't you add this feature?

Just FYI, sometimes when sources switch URL, they might change the websites theme or other portions of stuff, which breaks the extension, so sometimes it's not enough to just switch URLs and call it a day.

I don't know much more about this, and maybe it'll work currently, but if other parts get change, someone has to rewrite the code for the extension. (And looking at the code for Shinigami, looks like it needs some extra lines to get things to work/show up)

**Comment by WEPOXS** [comment]
> > Can't you add this feature?
> 
> Just FYI, sometimes when sources switch URL, they might change the websites theme or other portions of stuff, which breaks the extension, so sometimes it's not enough to just switch URLs and call it a day.
> 
> I don't know much more about this, and maybe it'll work currently, but if other parts get change, someone has to rewrite the code for the extension. (And looking at the code for Shinigami, looks like it needs some extra lines to get things to work/show up)

Ahhh, I see too bad that can't be done  🥲
but that's okay, thanks for the info 🙌
