### ISSUE TITLE
YakshaScans: ConnectException

### ISSUE THREAD

**Issue by Salinda001** [keiyoushi/tachiyomi-extensions-source#3742]
### Source information

YakshaScans 1.4.36

### Source language

English

### Steps to reproduce

Website is working but Extension is not connecting. Connection error.

![Screenshot_2024-06-26-04-34-55-867-edit_eu kanade tachiyomi yokai](https://github.com/keiyoushi/extensions-source/assets/130073141/1e9ba001-0ba2-4ac9-b9c0-3feaaaad6207)

### Expected behavior

Should show the manga lists..

### Actual behavior

Showing Java.exception........Connection Error!

### Mihon/Tachiyomi version

Yokai v1.8.4.1

### Android version

Android 12

### Other details

Yes I checked on other version of Tachiyomi, Mihon, Aniyomi etc... The extension worked the same.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Sounds like an issue with your ISP. Can you try with another network (mobile/wifi) or a VPN?
