### ISSUE TITLE
Quero adicionar uma nova extensão que surgiu no português brasileiro 

### ISSUE THREAD

**Issue by Natatsufx** [keiyoushi/tachiyomi-extensions-source#3744]
### Source name

Remangas 

### Source link

https://remangas.net/

### Source language

Português Brasil-Pt-Br

### Other details

![Screenshot_20240625_221257_Chrome](https://github.com/keiyoushi/extensions-source/assets/173861068/c75b3a8f-0584-40af-80ab-8737b25e2c3a)
![Screenshot_20240625_221314_Tachiyomi](https://github.com/keiyoushi/extensions-source/assets/173861068/a390b221-7150-4601-89b1-cd9c70810f82)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Don't open another issue request, the bot literally told you that it's within the repo.

Either you don't have Portuguese Brazilian enabled in your Tachiyomi Browse Page, for both your "Extensions" and "Sources" tab, or you don't have 18+ extensions enabled for your app, Tachiyomi Settings > Browse.

Also, don't acknowledge that you searched when you clearly didn't

**Comment by nomaxsnx** [comment]
Mano já tem a extensão, fecha a issues
