### ISSUE TITLE
Mangakakalot extension - wrong source

### ISSUE THREAD

**Issue by JCAntunes95** [keiyoushi/tachiyomi-extensions-source#3749]
### Source information

Mangakakalot 1.4.8

### Source language

English

### Steps to reproduce

Install Mangakakalot extension.
Open any manga.

### Expected behavior

Extension source should be Mangakakalot and nit Manganato 

### Actual behavior

The extension is sourcing from Manganato instead of Mangakakalot.

### Mihon/Tachiyomi version

0.16.5

### Android version

13

### Other details

This seems to be an issue with the extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
> This seems to be an issue with the extension.

It's not. Go to your own browser and visit the site itself, or check WebView in the app. Also, if I remember correctly, they're sister sites or something

**Comment by JCAntunes95** [comment]
Ah, I understand that they are sister sites, but it is still weird that opening Mangakakalot's WebView when on a manga page sends me to Manganato's site and not Mangakalot.

**Comment by Smol-Ame** [comment]
> Ah, I understand that they are sister sites, but it is still weird that opening Mangakakalot's WebView when on a manga page sends me to Manganato's site and not Mangakalot.

Just how they operate, nothing we can do about it

**Comment by JCAntunes95** [comment]
Upon further inspection it seems that opening the WebView in the extension menu it correctly opens Mangakakalot's site, but once you open in WebView on a manga page it sends you to Manganato.

I guess I'll close the issue, but that is some weird behaviour on their end
