### ISSUE TITLE
Lector español 

### ISSUE THREAD

**Issue by ashliepolanco** [keiyoushi/tachiyomi-extensions-source#3751]
### Source name

Lector español

### Source link

https://lectorespanol.com/

### Source language

Spanish

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Site is a rebrand of [Manhua Español](https://github.com/keiyoushi/extensions-source/blob/main/src/es/manhuaespanol/src/eu/kanade/tachiyomi/extension/es/manhuaespanol/ManhuaEspanol.kt), most slugs keep the same
