### ISSUE TITLE
Hentai Teca: Access denied

### ISSUE THREAD

**Issue by godestroyer666** [keiyoushi/tachiyomi-extensions-source#3752]
### Source information

Hentai Teca 1.4.37

### Source language

Portuguese

### Steps to reproduce

1. Access denied
2. You do not have access to hentaiteca.net.

### Expected behavior

Access allowed

### Actual behavior

Access denied

### Mihon/Tachiyomi version

J2K 1.7.4

### Android version

Android 13

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Are you able to provide more info (more detailed steps, specific titles/chapters, screenshots) or a screen recording of this issue? Just a reminder, no NSFW images please, you can mention names, but nothing graphic if possible.

Currently, I've checked a handful of different titles & chapters from both old & new, and I don't see this "access denied". Maybe the site was down/locked/under maintenance when you tried to use it, or maybe internet-related (ISP blocked) or source-related (region/Cloudflare block).

**Comment by godestroyer666** [comment]
Em qui., 27 de jun. de 2024 04:10, Smol Ame ***@***.***>
escreveu:

**Comment by godestroyer666** [comment]
I use tachij2k, and it says access denied, but the original tachiyomi is
normal, as you can see in image 1 and 2

Em qui., 27 de jun. de 2024 06:46, Christian Luccato <
***@***.***> escreveu:

**Comment by Smol-Ame** [comment]
I don't see any images in your issue request or comments. On J2K, go to J2K Settings > Advanced > DNS over HTTPS, and changing or turning that off. Afterwards, restart the app, and see if that helps. If not, maybe it's a Cloudflare block, but I don't think I've seen/heard it say "access denied" before. Try changing your user-agent in J2K Settings > Advanced, remember to restart the app & check WebView afterwards as well.

**Comment by choppeh** [comment]
> I don't see any images in your issue request or comments. On J2K, go to J2K Settings > Advanced > DNS over HTTPS, and changing or turning that off. Afterwards, restart the app, and see [...]

J2k is using an old user agent, so access is denied
