### ISSUE TITLE
Kiryuu download became .bin file

### ISSUE THREAD

**Issue by MadameVerre** [keiyoushi/tachiyomi-extensions-source#3756]
### Source information

Kiryuu 1.4.36

### Source language

Indonesia

### Steps to reproduce

When downloading the chapter it comes with the .bin extension, making the app unable to recognize it and leaving it as if there was no page

### Expected behavior

When downloading the chapter it should come in supported extensions (example: .jpg, .png, .avif ...)

### Actual behavior

the downloaded file comes in .bin

### Mihon/Tachiyomi version

TachiyomiSY 1.10.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by samanta-widjaja** [comment]
klikmanga also the same

**Comment by VrZeta** [comment]
Same happen (Kiryuu ext) with Mihon 0.16.5 (Android 13)
