### ISSUE TITLE
Galaxy Manga and Flix Scans : Access error 

### ISSUE THREAD

**Issue by OtakuArab** [keiyoushi/tachiyomi-extensions-source#3757]
### Source information

Galaxy Manga 1.4.34 , Flix Scans 1.4.6

### Source language

Arabic , English 

### Steps to reproduce

1- Access to the source 
2- The direct access error appears

### Expected behavior

It should show suggestions for the manhwa 

### Actual behavior

It should show suggestions for the manha 

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Other details

Of course, the problem was found in the latest update of the sources on Monday. Previously, other than the domain was working, but this problem appeared.
![Screenshot_٢٠٢٤٠٦٢٦-١٧٢٥٤٣_Mihon](https://github.com/keiyoushi/extensions-source/assets/161339329/9ce65de8-33d5-407d-9b36-69d8621c8e75)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Part of/duplicate of #3287 / #3540
