### ISSUE TITLE
Title url changing

### ISSUE THREAD

**Issue by TeachDian** [keiyoushi/tachiyomi-extensions-source#376]
### Source information

Rizz Comic 1.4.2

### Source language

English

### Source new URL

https://rizzcomic.com/

### Other details

the url is still the same "https://rizzcomic.com/" but the library title don't update even if you remove it. it's like the problem with asura scans extension, but asura scans extension have the toggle in the settings to continue to use the entry even the changes in url. 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
The extension already tries to find new url. Restart app if you are seeing old urls
