### ISSUE TITLE
Merlin Shoujo: No results found.

### ISSUE THREAD

**Issue by kyoyacchi** [keiyoushi/tachiyomi-extensions-source#3760]
### Source information

Merlin Shoujo 1.4.30

### Source language

Turkish (Türkçe)

### Steps to reproduce

Try using the Merlin Shoujo extension.

### Expected behavior

It should work

### Actual behavior

It says no results found
![Screenshot_20240626-223706](https://github.com/keiyoushi/extensions-source/assets/63583961/c4eee25e-aec0-451c-9444-6f3db7fee9e8)

![Screenshot_20240626-223517](https://github.com/keiyoushi/extensions-source/assets/63583961/a88e0559-507f-4d42-ad48-79b167c5e4a3)

### Mihon/Tachiyomi version

1.7.4

### Android version

Android 11

### Other details

I think they've changed the website template 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Seems like "Merlin Shoujo" redirects to "Merlin Scans" now, please install & migrate to "Merlin Scans"

Edit: They merged into one, see screenshot below or join their Discord server

![image](https://github.com/keiyoushi/extensions-source/assets/155411819/e846ba16-3057-43b5-9489-aee567fdcb50)

**Comment by kyoyacchi** [comment]
> Seems like "Merlin Shoujo" redirects to "Merlin Scans" now, please install & migrate to "Merlin Scans"
> 
> Edit: They merged into one, see screenshot below or join their Discord server
> 
> ![image](https://private-user-images.githubusercontent.com/155411819/343370287-e846ba16-3057-43b5-9489-aee567fdcb50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NDE2MDQsIm5iZiI6MTcxOTQ0MTMwNCwicGF0aCI6Ii8xNTU0MTE4MTkvMzQzMzcwMjg3LWU4NDZiYTE2LTMwNTctNDNiNS05NDg5LWFlZTU2N2ZkY2I1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQyMjM1MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGZiNzFlZmQwNjk1ODVmODZkMmJmYjhhZGMxODgzZjk4OWRjYWVjNDQ4ZGMwMzM5ODZmOGE4YjU1MmZiZWJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.493oQg7SqSNd5pBDdxWCqQbee7HILKJQ5EC4CBhsBJo)

I see, should i close this issue then?

**Comment by Smol-Ame** [comment]
> I see, should i close then issue then?

No, it's fine. Someone can reference/close this when they remove the unnecessary/old extension (I would've done it by now, but my app won't load)
