### ISSUE TITLE
MangaGeko extension experiencing chapter loading issues

### ISSUE THREAD

**Issue by popopiko** [keiyoushi/tachiyomi-extensions-source#3779]
### Source information

MangaGeko EN 1.4.24

### Source language

English

### Steps to reproduce

1. Open a chapter of a manga/manhwa/manhua that's using the MangaGeko extension
2. This error (or an error similar to it), will show up.
![image_2024-06-27_175642314](https://github.com/keiyoushi/extensions-source/assets/173263233/7b2714cf-0c58-47e9-ae2b-ac0a8a5a195b)

### Expected behavior

The chapter loads.

### Actual behavior

This error pops up. Also got tested separately on Mihon and it seems it's broken there as well.
![image_2024-06-27_175738576](https://github.com/keiyoushi/extensions-source/assets/173263233/607d9065-26dd-4702-9cd2-8f7b04bd927a)

### Mihon/Tachiyomi version

Suwayomi-Server v1.1.1

### Android version

Windows 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Seems to work fine on Mihon. Open WebView & make sure it passes Cloudflare verification, afterwards, go back & refresh list and you should be able to use it.

**Comment by vetleledaal** [comment]
Looks like an issue with your ISP. You can try enabling DoH or use a VPN. See the troubleshooting guide if you're stuck: https://tachiyomi.org/docs/guides/troubleshooting/common-issues#unable-to-resolve-host-connection-failed-failed-to-connect-to-timeout-connection-reset
