### ISSUE TITLE
No pages found for chapter

### ISSUE THREAD

**Issue by Hazzardousgamer** [keiyoushi/tachiyomi-extensions-source#3781]
### Source information

TCB scans 1.4.7

### Source language

English

### Steps to reproduce

Try downloading latest chapter of one piece

### Expected behavior

Chapter should download

### Actual behavior

No pages found error message

### Mihon/Tachiyomi version

0.16.5

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Seems like they're using a different website to host that chapter's pages compared to all the other chapters on their own site (disguised as some college site, probably so they don't get DMCA'd)
