### ISSUE TITLE
Tsuki Mangás: Some chapter pages fail to load

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#3787]
### Source information

Tsuki Mangás 1.4.5

### Source language

Português (Brasil)

### Steps to reproduce

Algumas vezes as páginas não carregam, tem que ficar insistindo muito pra carregar, no webview está carregando normalmente

Aplicativo 
![Screenshot_20240627-183110](https://github.com/keiyoushi/extensions-source/assets/157044539/31cab028-ab17-4a32-8774-184ad5c26fc5)

Webview
![Screenshot_20240627-183145](https://github.com/keiyoushi/extensions-source/assets/157044539/f58060c1-f64d-4365-8949-b10baee303ec)

### Expected behavior

Carregar as páginas normalmente

### Actual behavior

Tem horas que não carrega, tem que fechar é abrir o aplicativo novamente

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by QuagZy** [comment]
https://github.com/keiyoushi/extensions-source/assets/157044539/9919d2a9-d42e-472f-9635-ef7eb44646d3

**Comment by ghost** [comment]
O problema tá na extensão mesmo não no site, o site tá carregando os capítulos normalmente.

EXTENSÃO:

https://github.com/keiyoushi/extensions-source/assets/157044539/70b513b7-7f3e-4a67-84f1-2f023da463e0

SITE:

https://github.com/keiyoushi/extensions-source/assets/157044539/f1adc004-59e4-40db-9bdf-3ebeb80931c6

**Comment by choppeh** [comment]
I couldn't reproduce this error.  Maybe the same problem as #3695

**Comment by AwkwardPeak7** [comment]
feel free to comment/open new issue if issue still persists

**Comment by ghost** [comment]
> feel free to comment/open new issue if issue still persists

Ainda está dando esse erro de não carregar as páginas, também está dando o erro do Cloudflare
![Screenshot_20240808-191948](https://github.com/user-attachments/assets/3d374f47-f381-41fa-8afd-3bdeaceb3087)
