### ISSUE TITLE
SlimeRead extension gives error 

### ISSUE THREAD

**Issue by Maddigow** [keiyoushi/tachiyomi-extensions-source#3789]
### Source information

Slimeread 1.4.12

### Source language

Português Brasil

### Steps to reproduce

just try to read or search for something and the HTTP error 504 will appear 

If it doesn't happen the first time, try again and the error will persist, the same goes for when the error happens, just keep clicking try again until it works  

### Expected behavior

In the case of a search, the expectation is that it will show the results of the search and in the case of reading, the expectation is that it will load the chapters and pages correctly, without the need to try again for the same to happen. 

### Actual behavior

Error 504 appears, if you click on the try again button (an undetermined number of times) it will work, the search results appear much less items (and sometimes nothing appears, when something appears on the website) in relation to the results site search 

### Mihon/Tachiyomi version

0.16 5

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
500 errors are usually some server issue with the source, nothing we can really do about it. Maybe check WebView for errors or let it load fully before attempting to search

**Comment by Maddigow** [comment]
the webview works perfectly

**Comment by nomaxsnx** [comment]
Manutenção

![Screenshot_2024-06-30-22-08-22-791_com discord-edit](https://github.com/keiyoushi/extensions-source/assets/157644160/e2a93f81-ad16-4352-b87f-5cff79f7d171)

Por isso que vai fica dando esse error: "504".

De vez enquanto funciona a extensão

**Comment by Maddigow** [comment]
Aaah, entendi mano.  Valeu!

**Comment by choppeh** [comment]
> Aaah, entendi mano. Valeu!

@Maddigow não vejo necessidade de manter essa issue aberta. Caso esse update no site precise alterar algo na extensão, é bom abrir uma issue relatando o problema especifico
