### ISSUE TITLE
FleksyScans site is closed due to DMCA

### ISSUE THREAD

**Issue by Patriarch9307** [keiyoushi/tachiyomi-extensions-source#3791]
### Source name

FleksyScans

### Source language

English 

### Source link

https://flexscans.com

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Just curious, since sometimes these things are temporary, do you have any screenshots/images of said DMCA or any announcements from them, like a notice on their site or a Discord announcement from their server (if applicable)?

**Comment by Patriarch9307** [comment]
![Screenshot](https://github.com/keiyoushi/extensions-source/assets/108529338/7c8e5cff-1aa1-4e4d-8e2b-9069a5c97e5c)

**Comment by Smol-Ame** [comment]
Got it, thanks for info
