### ISSUE TITLE
Arthur Scan (PT-BR Source) downloads the same page for all works.

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#3809]
### Source information

Arthur Scan 1.4.40

### Source language

Portuguese Brazilian 

### Steps to reproduce

When I download a page appears that informs the website and Discord of the scan, or a page not found appears.

![Screenshot_2024-06-29-10-09-34-539_app mihon](https://github.com/keiyoushi/extensions-source/assets/169321265/d2cae2db-3c9b-4ba5-94b9-4df09360cad3)

### Expected behavior

You can download the chapter and read it.

### Actual behavior

It is only possible to read directly without downloading.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
I can't reproduce this error.  The extension works fine for me.

- Clear the extension data:
More > Settings > Advanced > Clear database. Select Arthur Scan (PT-BR) and click Delete


And test again.

**Comment by EvaldoCeBr** [comment]
> I can't reproduce this error.  The extension works fine for me.
> 
> - Clear the extension data:
> More > Settings > Advanced > Clear database. Select Arthur Scan (PT-BR) and click Delete
> 
> 
> And test again.
> 

Segui os passos que indicou mas o erro persiste, não é em todos os capítulos, mas se você der uma olhada em Super WECHAT por exemplo nos últimos episódios, quando põe pra baixar e espera terminar o download acabar para abrir o arquivo, aparece apenas aquela imagem que postei. Agora se for carregando enquanto está lendo da para ler normal.
