### ISSUE TITLE
Ler Mangas: WebView redirects to invalid intent:// scheme

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#3810]
### Source information

Ler Mangas 1.4.36

### Source language

Português (Brasil)

### Steps to reproduce

O webview fica dando esse erro que eu vou mostrar no vídeo abaixo

https://github.com/keiyoushi/extensions-source/assets/157044539/ba704a0d-d901-4b25-b4c1-2fd93ec7e808

### Expected behavior

Webview funcionando perfeitamente 

### Actual behavior

Webview dando erro

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 11 

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
we can't really fix webview
