### ISSUE TITLE
Vyvymanga http error 403 when trying to retrive chapter list

### ISSUE THREAD

**Issue by xseno123** [keiyoushi/tachiyomi-extensions-source#3813]
### Source information

Vyvymanga 1.4.5

### Source language

english

### Steps to reproduce

1. Go to vyvymanga extension
2. manga list will load
3. check any manga it will not load the list and report error: http 403

### Expected behavior

Clicking on a manga should give list of chapter

### Actual behavior

Returns error 403

### Mihon/Tachiyomi version

TachiyomiJ2k 1.7.4 

### Android version

Android 14

### Other details

I suspect that it happens due to their switcing/redirecting from vyvymanga.net to vymanga.net. If you open the extension via webbrowser you are redireted to vymanga.net

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Seems to work fine, check WebView to make sure you pass Cloudflare verification and it should load up without issue.

**Comment by AwkwardPeak7** [comment]
cannot reproduce, make sure to pass cloudflare in webview
