### ISSUE TITLE
Asura Scans cloudflare

### ISSUE THREAD

**Issue by SooarynAC** [keiyoushi/tachiyomi-extensions-source#3814]
### Source information

Asura Scans 1.4.34

### Source language

English

### Source new URL

https://asuratoon.com/

### Other details

The other URL is under cloudflare and isn't working

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
It works fine, go into WebView, check if it passes Cloudflare. If it doesn't, go to your app settings > Advanced, and change your user-agent.

Restart app after changing, check WebView to see if it passes. If it doesn't, repeat

**Comment by SooarynAC** [comment]
It works only in webview, I even tried restarting the phone after changing my user-agent but it always fails to bypass cloudflare.

**Comment by SooarynAC** [comment]
But either way, isn't this other URL the correct one? At least it's the one in all their manhwa headers.

**Comment by Smol-Ame** [comment]
I'm not too sure which ones which, and there's like four different sites as far as I know. But the current link works after passing Cloudflare verification.

It's a bit hard to say what could be the issue on your end currently, so I'll shotgun approach it here.
* If your manhwa opens to Asuratoon in WebView, migrate them back into Asura Scans to update the URL
* Make sure "Automatically update dynamic URLs" is enabled for the extension, in Mihon Browse Page > Extensions tab > Asura Scans > Language settings
* Go to Mihon Settings > Advanced, clear cookies
* As mentioned before, change user-agent works (as I have tried it and like ten other support requests has tried), you might need to try a handful before you find one that works for you
 * Remember to restart the app after changing the user-agent, and check WebView to make sure it passes

**Comment by Norsze** [comment]
They are both the same site, they are identical. One of them is probably a mirror of the other. Doesn't matter much though since they both work

Also it is not the one in all their headers, they use asurascans.com which just bounces you to either asuratoon or asuracomic, don't know if they bounce you depending on geo location to split the traffic.

**Comment by SooarynAC** [comment]
They are the same, but one of them doesn't have cloudflare. And I tried everything to get it working, it's broken specifically for Asura Scans, other cloudflare protections are bypassed fine :(

**Comment by Norsze** [comment]
Works fine for me

**Comment by Norsze** [comment]
Closing this issue as #4167 is the main culprit here
