### ISSUE TITLE
ChoChoX

### ISSUE THREAD

**Issue by DeBoaBaby** [keiyoushi/tachiyomi-extensions-source#3821]
### Source name

ChoChoX

### Source link

https://chochox.com/porno/

### Source language

Spanish

### Other details

18+/NSFW = yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by DeBoaBaby** [comment]
?

**Comment by Smol-Ame** [comment]
Don't comment bump, all the work is done by contributors volunteering their time. There's no guarantee that it'll be added/added soon, just whoever has the time & is willing to work on this open request.

**Comment by danielblafer** [comment]
?

**Comment by DeBoaBaby** [comment]
Why Close?

**Comment by DeBoaBaby** [comment]
> ### Source name
> ChoChoX
> 
> ### Source link
> https://chochox.com/porno/
> 
> ### Source language
> Spanish
> 
> ### Other details
> 18+/NSFW = yes
> 
> ### Acknowledgements
> * [x]  I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> * [x]  I have written a meaningful title with the source name.
> * [x]  I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
> Why Close?

You closed it yourself. You tell me.
