### ISSUE TITLE
Quero pedir a adição de uma no extensão que surgiu

### ISSUE THREAD

**Issue by Art-1-sc** [keiyoushi/tachiyomi-extensions-source#3823]
### Source name

MangaDex

### Source link

https://mangadex.org/title/b3a16bc0-bfe4-4020-a825-18b49fd85aba/sorry-i-like-you

### Source language

Multiplas

### Other details

![Screenshot_20240630-092818](https://github.com/keiyoushi/extensions-source/assets/174252463/825b1488-be6d-4728-8a4c-f11d114c88e7)
![Screenshot_20240630-092613](https://github.com/keiyoushi/extensions-source/assets/174252463/c2fba0e6-0fba-4253-b7ba-5f586718d90d)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
If it doesn't show for you, make sure you enable nsfw/18+ extensions in the settings

**Comment by Art-1-sc** [comment]
Sorry, I couldn't find this extension on my device, I've been to the all
section and still haven't found it, I'll try to solve it another way

Em dom., 30 de jun. de 2024 09:34, Vetle Ledaal ***@***.***>
escreveu:
