### ISSUE TITLE
Quero pedir a adição de uma nova extensão que surgiu no português brasileiro

### ISSUE THREAD

**Issue by Nicollasoip** [keiyoushi/tachiyomi-extensions-source#3824]
### Source name

central novel 

### Source link

https://centralnovel.com/

### Source language

Português-brasileiro-PT-BR

### Other details

![Screenshot_20240630-093706](https://github.com/keiyoushi/extensions-source/assets/174253020/beb8b81d-346f-4d77-8b4b-ccc0f339b2e7)
![Screenshot_20240630-093608](https://github.com/keiyoushi/extensions-source/assets/174253020/95727b13-bfee-423a-88cc-19bb4e1fa073)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
Tachiyomi/Mihon doesn't support novels
