### ISSUE TITLE
Failed to load image error +18 extensión

### ISSUE THREAD

**Issue by Luis6161** [keiyoushi/tachiyomi-extensions-source#3826]
### Source information

"tmohentai 1.4.7"

### Source language

Spanish

### Steps to reproduce

Enter to mihon.
Open the tmohentai extension.
Any manga that open say Failed to load image.

### Expected behavior

Enter mihon.
Open the extensión tmohentai.
Open any manga and show normaly.

### Actual behavior

When open the tmohentai extension cant read anything because a full black Failed to load image apear

### Mihon/Tachiyomi version

"mihon 0.16.5"

### Android version

"android 11"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Our extension is version 1.4.8, and it seems to work on my end.

* Double-check the extension, make sure there isn't an update waiting for you to download & install
* If there isn't an update, and it's still at 1.4.7, double-check that you actually have our repo in your app, then uninstall the extension & reinstall said extension
