### ISSUE TITLE
Quero pedir a adição de uma nova extensão que surgiu no português brasileiro 

### ISSUE THREAD

**Issue by ElisandroBala** [keiyoushi/tachiyomi-extensions-source#3828]
### Source name

Leitor de mangá

### Source link

https://leitordemanga.com/

### Source language

Português Brasil - PT-BR 

### Other details

![Screenshot_20240701-001636](https://github.com/keiyoushi/extensions-source/assets/174281215/22cb3c36-f1b3-4c60-aa47-25e5548ee15d)
![Screenshot_20240701-001619](https://github.com/keiyoushi/extensions-source/assets/174281215/51117453-5f02-4c80-9c0a-886b3a5c7d92)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Double-check that you have Brazilian Portuguese enabled in both your Extensions tab & Sources tab for the Browse page
