### ISSUE TITLE
Nico Nico Seiga updated to new domain

### ISSUE THREAD

**Issue by Nogooduser** [keiyoushi/tachiyomi-extensions-source#3832]
### Source information

NicoVideo Seiga

### Source language

Japanese

### Source new URL

https://sp.manga.nicovideo.jp/

### Other details

Nico Seiga had a bunch of DDOS attacks and technical issues recently (has been down for weeks now) and ultimately ended up changing their domain from https://seiga.nicovideo.jp/ to https://sp.manga.nicovideo.jp

This is a permanent change and not a temporary DDOS countermeasure, as detailed in their article [here](https://info.nicomanga.jp/entry/20240625/) where they even ask people to update their bookmarks. 

This should get the extension working again (don't think the backend changed) 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ringosham** [comment]
Yeah I'll need to rewrite the whole thing. Good news is their API is open now.

Due to the domain changes, everyone should expect to migrate once when the new version is pushed.
