### ISSUE TITLE
Adicionar site em português à fonte Manytoon

### ISSUE THREAD

**Issue by DeBoaBaby** [keiyoushi/tachiyomi-extensions-source#3836]
### Source name

Manytoon

### Source link

https://pt.manytoon.com

### Source language

Português PT-BR 

### Other details

18+/NSFW = yes

![Screenshot_20240701_174127_Brave](https://github.com/keiyoushi/extensions-source/assets/159880989/32fe5f3f-7e8a-43a4-af9e-74dae315a626)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
Only the web page is in Portuguese, all the content is in English.

The extension is already implemented https://keiyoushi.github.io/extensions/#en.manytoon
