### ISSUE TITLE
Error 400 siikomik

### ISSUE THREAD

**Issue by ShoujoLover** [keiyoushi/tachiyomi-extensions-source#3851]
### Source information

Siikomik 1.4.37

### Source language

Indonesian

### Steps to reproduce

1. Open ext
2. Http 400 error: check website in webview
3. Open webview Functioning normally
1. Open comic and chapter
2. Http error 404

### Expected behavior

Functions normally for both extensions and comics being read

### Actual behavior

Http 400: check website in webview
![Screenshot_2024-07-03-16-24-10-660_eu kanade tachiyomi j2k](https://github.com/keiyoushi/extensions-source/assets/157118563/0762be3d-210b-4893-8170-a85b04a46015)

Http error 404
![Screenshot_2024-07-03-16-24-42-238_eu kanade tachiyomi j2k](https://github.com/keiyoushi/extensions-source/assets/157118563/3728ceec-abd9-4cc9-bd42-5499e727da8d)

### Mihon/Tachiyomi version

J2k 1.7.4

### Android version

13

### Other details

I think the error was caused by hosting migration and changing the website theme

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
~~From a quick peek at their site, it seems like they removed or lost their chapters & manga pages.~~

~~Click into their pages & chapters, and you'll see what I mean (especially the title in your screenshot)~~

:/ Nevermind me, as I sent the message & went back to check some more, their chapters reappeared

**Comment by choppeh** [comment]
Theme changed
