### ISSUE TITLE
Ichiromanga

### ISSUE THREAD

**Issue by ShoujoLover** [keiyoushi/tachiyomi-extensions-source#3852]
### Source name

Ichiromanga

### Source link

https://www.ichiromanga.my.id/

### Source language

Indonesia

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Using ~KumaReader blogger~ MangaThemesia WP theme
Edit : 10/09/24

**Comment by ShoujoLover** [comment]
> Using KumaReader blogger theme

I think it Change to Madara now
