### ISSUE TITLE
surya moving

### ISSUE THREAD

**Issue by mneko** [keiyoushi/tachiyomi-extensions-source#3858]
### Source information

Surya Scans

### Source language

English

### Source new URL

http://genztoons.com

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
It's a Source Request. 

Surya Scans it's OK

**Comment by mneko** [comment]
> It's a Source Request.
> 
> Surya Scans it's OK

Huh, they posted that they were shutting down the surya domain but the post disappeared

**Comment by lcd047** [comment]
> Surya Scans it's OK

It isn't OK.  At the very least they changed the site's format, the extension stopped working.

**Comment by choppeh** [comment]
> It isn't OK. At the very least they changed the site's format, the extension stopped working.

Um, I just saw the link redirect.
