### ISSUE TITLE
Damon sect não dá pra ver as obras 

### ISSUE THREAD

**Issue by Jefferson199809** [keiyoushi/tachiyomi-extensions-source#3877]
### Source information

Damon sect

### Source language

Português-br

### Source new URL

https://dsectcomics.org/

### Other details

Abri o webView e o site está funcionando mas n da pra ver as obras pelo aplicativo 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
You made a source request instead of an issue request.

But I believe you need to log into Demon Sect in WebView, then the titles will appear in the extension as mentioned in #3324
