### ISSUE TITLE
Comik cast

### ISSUE THREAD

**Issue by Raflysys** [keiyoushi/tachiyomi-extensions-source#3881]
### Source information

Komik Cast 1.4.59

### Source language

Bahasa Indonesia 

### Source new URL

https://komikcast.cz/

### Other details

Cara memperbarui versi terbarunya bagaimana? 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
> Cara memperbarui versi terbarunya bagaimana?

(TL) Versi Komik Cast 1.4.59 adalah versi terbaru. Anda perlu menunggu seseorang mengirimkan perbaikan, kemudian perbaikan tersebut perlu disetujui oleh seorang maintainer.
\-\-\-\-
Komik Cast 1.4.59 is the latest version. You need to wait for someone to submit a fix, afterwards the fix needs to be approved by a maintainer.

**Comment by Kunaguero110** [comment]
Damn so loong
