### ISSUE TITLE
Please  fix this plugin.

### ISSUE THREAD

**Issue by Steve1innnn** [keiyoushi/tachiyomi-extensions-source#3889]
### Source information

Jinman Tiantang 1.4.43

### Source language

ZH

### Steps to reproduce

Unable to enter the introduction and open the interface of the comics
![Screenshot_20240706_215016_Tachiyomi](https://github.com/keiyoushi/extensions-source/assets/174052567/f7a0fb29-5251-4e33-bace-5f00dde41bd2)

### Expected behavior

You can open comics and watch them.

### Actual behavior

Sometimes he shows up without cloudflare.
![Screenshot_20240706_215032_Tachiyomi](https://github.com/keiyoushi/extensions-source/assets/174052567/f9c16c0a-ae12-4138-a35d-24009197b219)

### Mihon/Tachiyomi version

tachiyomi0.15.3 and mihon0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
?blurb cf
