### ISSUE TITLE
Cypher Scans domain change for newer chapters

### ISSUE THREAD

**Issue by Pwnager12345** [keiyoushi/tachiyomi-extensions-source#3898]
### Source information

Cypher Scans 1.4.30

### Source language

English

### Source new URL

erosscans.xyz

### Other details

The extension still works with the older chapters. Only the newer chapters just show a page saying to go read on erosscans.xyz instead of the chapter.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
Cypher Scans  is OK,  https://erosscans.xyz/  is a new source request.
