### ISSUE TITLE
Scanlators & Authors included in the Dynasty Scans Source

### ISSUE THREAD

**Issue by nopeha** [keiyoushi/tachiyomi-extensions-source#391]
### Source name

Dynasty Scans

### Source link

https://dynasty-scans.com/scanlators & https://dynasty-scans.com/authors

### Source language

English

### Other details

Much like the Dynasty Scans source already has Issues, Chapters, etc., include Authors and Scanlators as well.

Fetching the Scanlators work would be easiest, as not all have websites they post to (which would be preferred for a source to be made from), instead they post directly to certain sources.

Authors is less viable, but I think it would also be useful.

(I think both of these would be good for the MDex source as well, especially Scanlators for a similar reason. But I don't know if MDex is built in a way that makes it easy.)

For me, I see both being setup similar to how the Doujins part of the extension sorts things.

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Wrong issue template used, should have been a feature request.
