### ISSUE TITLE
Quero pedir a adição de uma nova extensão que surgiu no português brasileiro 

### ISSUE THREAD

**Issue by Renan4036y66y** [keiyoushi/tachiyomi-extensions-source#3910]
### Source name

LERMANGAS

### Source link

https://lermangas.me/

### Source language

Português brasil-PT-BR 

### Other details

![Screenshot_20240707-143407](https://github.com/keiyoushi/extensions-source/assets/174956518/10f4f283-9457-436c-b4ca-fc8f31218777)
![Screenshot_20240707-143437](https://github.com/keiyoushi/extensions-source/assets/174956518/7ae1dae6-c79d-49b6-9926-a790d5872032)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Renan4036y66y** [comment]
Por favor

**Comment by Smol-Ame** [comment]
> Por favor

It's already in our repo, either you need to split the name "Ler Manga" or you didn't enable Brazilian Portuguese in the app's Browse Page > Extensions tab (and Source tab)
