### ISSUE TITLE
SHINIGAMI ID

### ISSUE THREAD

**Issue by Ktslovers99** [keiyoushi/tachiyomi-extensions-source#3911]
### Source information

Shinigami 1.4.58

### Source language

Indonesia

### Source new URL

https://shinigamitoon.xyz/

### Other details

Change domain from https://shinigamitoon.app/ to https://shinigamitoon.xyz/

### Acknowledgements

- [X] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Kunaguero110** [comment]
Up sir

**Comment by Hannaichi** [comment]
changed again to https://shinigami01.com/
