### ISSUE TITLE
Web view error mangalib

### ISSUE THREAD

**Issue by 0kolya0** [keiyoushi/tachiyomi-extensions-source#3912]
### Source information

Mangalib 1.4.102

### Source language

Russian 

### Steps to reproduce

![S40707-22090614](https://github.com/keiyoushi/extensions-source/assets/36767025/0da55250-b548-44ab-9090-ed93b6bb8c91)
![S40707-22102561](https://github.com/keiyoushi/extensions-source/assets/36767025/c69ed953-050d-46a6-ac3c-94364ea7134b)
![S40707-22092829](https://github.com/keiyoushi/extensions-source/assets/36767025/5db18d8a-86a6-4788-b5d3-586ca6817917)
![S40707-22104414](https://github.com/keiyoushi/extensions-source/assets/36767025/82f75cdd-030b-45aa-977e-562316a50936)
Most likely this is due to an incorrect link.

### Expected behavior

Should be open: 1) for the case when you opened a manga: The main page of the title. 2) if the page is open, then open the same one in web view mode

### Actual behavior

![S40707-22104414](https://github.com/keiyoushi/extensions-source/assets/36767025/04b296eb-38f8-4214-b408-ead5ecc13229)

### Mihon/Tachiyomi version

App version: 1.10.5 (standard, 31f967235, 68, 2024-06-01T22:29:05Z) Preview build: 561 Android version: 9 (SDK 28; build Flyme 7.2.3.1G) Device brand: meizu Device manufacturer: meizu Device name: 16s (meizu_16s) Device model: 16s WebView: Chrome 126.0.6478.122

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by GregerForever** [comment]
Change domain to test-front.mangalib.me . The mangalib.me site has not yet been updated to the new version
