### ISSUE TITLE
MangaHen Only Showing Preview Pages

### ISSUE THREAD

**Issue by mrtear** [keiyoushi/tachiyomi-extensions-source#3916]
### Source information

MangaHen 1.4.1

### Source language

English

### Steps to reproduce

1. Open MangaHen Manga
2. Start Read
3. Only Shows 16 Pages (Preview Pages) For Every Manga That You Read

### Expected behavior

extention should show all the pages of added manga not previews.
check attached ss of another source of that manga
![another-source](https://github.com/keiyoushi/extensions-source/assets/91820779/5c738188-655a-4228-b638-fd35917c5c4a)

### Actual behavior

Only Shows 16 Pages (Preview Pages) For Every Manga That You Read
![Manga-hen](https://github.com/keiyoushi/extensions-source/assets/91820779/47f84310-1acf-4352-ad88-c30867488932)

### Mihon/Tachiyomi version

TachiyomiSY Beta 561

### Android version

Android 14

### Other details

PLEASE ADD/FIX THESE THINGS IN THE EXTENTSION ALSO | @KenjieDec 

- Please change the settings to only shows the **title in english** (check above SS's + attached SS below)
- Also change the progress from **Unknown to Completed** for every manga
![Mangahen](https://github.com/keiyoushi/extensions-source/assets/91820779/3a8d0891-90d1-41f3-8d3a-80b1d14c9d2e)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
@mrtear please don't ping contributors, issues get fixed whenever someone have the time and want to do it.

**Comment by mrtear** [comment]
> @mrtear please don't ping contributors, issues get fixed whenever someone have the time and want to do it.

sorry my bad.
