### ISSUE TITLE
Estou abrindo esse pedido por uma nova extensão em PT-BR

### ISSUE THREAD

**Issue by Xavierbrazil** [keiyoushi/tachiyomi-extensions-source#3924]
### Source name

Centralnovel

### Source link

https://centralnovel.com/

### Source language

Português brasileiro PT-BR

### Other details

![Screenshot_2024-07-08-23-32-02-958_app mihon](https://github.com/keiyoushi/extensions-source/assets/175076602/b2e93187-0d10-4fe9-8002-e926c29a7933)
![Screenshot_2024-07-08-23-36-01-067_com android chrome](https://github.com/keiyoushi/extensions-source/assets/175076602/c1f3ffd7-683e-4ef5-858c-38f69df3b184)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicado do fechado #3691 e fechado #3824

(Google Translate) Conforme mencionado no problema existente, que você deveria pesquisar antes de abrir e reconhecer que o fez, o aplicativo Tachi/Mihon não oferece suporte a romances/livros.

Edit: Whoops, forgot to switch translation language
