### ISSUE TITLE
Diskus Scan updates work only through a link.

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#3927]
### Source information

Diskus Scan 1.4.39

### Source language

Portuguese Brazilian 

### Steps to reproduce

The works become out of date and the link to access the recent ones cannot be accessed from the WebView, only from the normal browser.

![Screenshot_2024-07-09-11-16-10-873_app mihon](https://github.com/keiyoushi/extensions-source/assets/169321265/81807ee4-e829-48bb-94f9-e094aba77e64)
![Screenshot_2024-07-09-11-16-17-406_app mihon](https://github.com/keiyoushi/extensions-source/assets/169321265/fd51bd62-f72d-4b19-8633-793d774a7615)
![Screenshot_2024-07-09-11-17-19-245_com android chrome](https://github.com/keiyoushi/extensions-source/assets/169321265/f682bdb1-a4ca-4c09-97cb-7140933048b1)
![Screenshot_2024-07-09-11-17-26-424_com android chrome](https://github.com/keiyoushi/extensions-source/assets/169321265/abb567f3-0cac-42dd-828f-dea45174cde3)

### Expected behavior

Read the works as soon as they come out.

### Actual behavior

You have to wait many hours for the WebView to update, or access it via a link in a normal browser.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by EvaldoCeBr** [comment]
You can only access the new chapter using this link, or wait many hours for the website to update.

![IMG_20240709_113723](https://github.com/keiyoushi/extensions-source/assets/169321265/ca5012cd-be37-4f13-810f-f68c32a87fa0)

**Comment by AwkwardPeak7** [comment]
website issue if chapter doesn't show up on manga page
