### ISSUE TITLE
SamuraiScan no anda

### ISSUE THREAD

**Issue by Striven100** [keiyoushi/tachiyomi-extensions-source#3932]
### Source information

es.manhuaonline

### Source language

Español

### Steps to reproduce

No puedo acceder a los capitulos ni actualizar la pagina.

### Expected behavior

Creo q cambiaron el nombre de la raw pero sigue mostrando los manhwas, solo no me deja leerlos. (por las dudas, es spanish.visorsmr.com)

### Actual behavior

![Screenshot_20240709-184523_Tachiyomi](https://github.com/keiyoushi/extensions-source/assets/138946506/aa5bc4a6-4ead-4ac4-8e92-0ad29f1744f1)
![Screenshot_20240709-184517_Tachiyomi](https://github.com/keiyoushi/extensions-source/assets/138946506/a9bdcf7c-c8d5-4b19-a5e2-f7a8c7416c95)

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #3926
