### ISSUE TITLE
New Shinigami Url

### ISSUE THREAD

**Issue by lukibilek** [keiyoushi/tachiyomi-extensions-source#3936]
### Source information

Shinigami

### Source language

Indonesia

### Source new URL

https://shinigami01.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #3911 

Search the existing issues first before opening a new one, and acknowledging that you did when you didn't.
