### ISSUE TITLE
Imperiodabritannia Error Load Manga in app

### ISSUE THREAD

**Issue by nomaxsnx** [keiyoushi/tachiyomi-extensions-source#3940]
### Source information

Sagrado Império da Britannia 1.4.35

### Source language

Português

### Steps to reproduce

1. Open extension
2. Open any manga
3.  Wait now

### Expected behavior

On their website it shows that there's a chapter, but when you load it into the app it says there's no chapter

It doesn't even work on webview, it keeps loading but the chapters don't appear, you have to go to google 

### Actual behavior

![Screenshot_2024-07-10-12-05-48-710_app mihon](https://github.com/keiyoushi/extensions-source/assets/157644160/8e1992a6-9444-48a0-ae48-c75764e09283)
![Screenshot_2024-07-10-12-05-57-410_app mihon](https://github.com/keiyoushi/extensions-source/assets/157644160/28c7025a-ff39-46e7-9ed1-6021f861d233)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nomaxsnx** [comment]
Update: Apparently you have to read from the home page now, can't you just classify the "home" and "manga" pages together? 

![Screenshot_2024-07-10-12-11-34-720_com discord-edit](https://github.com/keiyoushi/extensions-source/assets/157644160/80ebbc39-7e88-469a-b821-301d4160256e)

**Comment by choppeh** [comment]
The issue can be closed. Extension is Ok.
