### ISSUE TITLE
NekoScans 

### ISSUE THREAD

**Issue by ashliepolanco** [keiyoushi/tachiyomi-extensions-source#3946]
### Source information

NekoScans 1.4.30

### Source language

Spanish

### Source new URL

https://nekoscanlationlector.blogspot.com/?m=1

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Theme changed to ZeistManga
