### ISSUE TITLE
Sussy Scan - Socket Timeout Exception: timeout

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#3948]
### Source information

Sussy Scan 1.4.39

### Source language

Português (Brasil)

### Steps to reproduce

![Screenshot_20240710-233027](https://github.com/keiyoushi/extensions-source/assets/157044539/476dfbd3-8333-40ea-8cf9-a52bdeab91b7)

No Webview está normal

### Expected behavior

Estar funcionando perfeitamente

### Actual behavior

Está dando o erro  Socket Timeout Exception: timeout

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Seems fine on my end, maybe it was a temporary source/site issue or just your internet
* Go to Mihon Settings > Advanced, and "Clear WebView data" and "Clear Cookies"
* If that doesn't work, try switching networks, try Mihon Settings > Advanced > DNS over HTTPS, or maybe a VPN
