### ISSUE TITLE
No scheme was found

### ISSUE THREAD

**Issue by PlaywithKen** [keiyoushi/tachiyomi-extensions-source#3949]
### Source information

Mangago 1.4.15

### Source language

English

### Source new URL

mangago.me

### Other details

![Discord](https://github.com/keiyoushi/extensions-source/assets/175274444/a3286090-a909-48ed-8493-f74ba836efdf)

It keeps doing this if i read directly from the app but i can read it at site, i cant also download the chapter
![Screenshot_20240711_103435_Mihon](https://github.com/keiyoushi/extensions-source/assets/175274444/66e39536-e1c6-4049-b605-9f39a4ef003f)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
1) You opened a source request instead of an issue request
2) Duplicate of #3914, wait for a fix or migrate to a different source
