### ISSUE TITLE
koharu.to

### ISSUE THREAD

**Issue by sixfoldsquealer** [keiyoushi/tachiyomi-extensions-source#3951]
### Source name

Koharu

### Source link

https://koharu.to

### Source language

English

### Other details

18+/NSFW = Yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by mrtear** [comment]
First thing that came to my mind after cheking this source.
![TachiyomiSY](https://github.com/keiyoushi/extensions-source/assets/91820779/1496f130-0702-40fb-8e42-1c689c3e8298)

Site has its own inbuilt great features. Like block tags through extenstion settings
![img_1](https://github.com/keiyoushi/extensions-source/assets/91820779/36c57381-8e9e-4044-9777-a980e871b81e)

Chapters Quality 
![img_2](https://github.com/keiyoushi/extensions-source/assets/91820779/bd1056ef-9f8d-4af5-a872-1834628e8c82)

nhentai features in TachiSY:
Shows Page counts in description
Show chapters previews while checking.

Well everything is possible if its handled by a pro developer. At time like this I wish I knew how make extenstions.

**Comment by Solovertical** [comment]
@KenjieDec  Add supported link/Opening link in koharu . if you haven't like panda chaika

**Comment by KenjieDec** [comment]
> @KenjieDec Add supported link/Opening link in koharu . if you haven't like panda chaika

Hello, I don't quite understand what you're trying to suggest. Could you please clarify/provide some context? Thank you.

**Comment by vetleledaal** [comment]
Probably referring to [URL intent filters](https://github.com/keiyoushi/extensions-source/blob/main/CONTRIBUTING.md#url-intent-filter)

**Comment by mrtear** [comment]
@KenjieDec (sry for tagging) | Can you also consider these things if its possible:

1.  Adding this for koharu in extenstion settings.

- { in koharu case [artist] (circle/magazine thing) is used }

![img_1](https://github.com/user-attachments/assets/3af98b8d-0360-4092-b438-3aba47bbca96)

2. Add posted date rather that shows always TODAY while viewing entries
![img_2](https://github.com/user-attachments/assets/846f9ee9-93f9-45bb-83e9-c9ac12231e00)

3. Some useful settings like these
![img_3](https://github.com/user-attachments/assets/b59dc9a7-85c3-4bfc-b4b6-07cb335870bd)
