### ISSUE TITLE
Remanga extension not loading chapters

### ISSUE THREAD

**Issue by Rin1487** [keiyoushi/tachiyomi-extensions-source#396]
### Source information

Remanga 1.4.82

### Source language

Russian

### Steps to reproduce

Try to open or download any manga chapter 

### Expected behavior

Chapter opening or downloading

### Actual behavior

Instead app shows notification
 with error like on screenshot 
![Screenshot_2024-01-20-01-44-59-278-edit_eu kanade tachiyomi](https://github.com/keiyoushi/extensions-source/assets/55631077/5fef208b-40c5-4db2-a36f-da61cd128cd4)

### Tachiyomi version

TachiyomiSY 1.10.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ArpeksMenethil** [comment]
Russian:
Если скачивать главы с ExManga (т.е. платную, что ты не покупал), то он откроет/скачает её нормально
А открытые/уже купленные главы он выдает такую ошибку

Google Translate:
If you download chapters from ExManga (i.e. a paid one that you didn’t buy), then it will open/download it normally
And open/already purchased chapters it gives the following error
[tachiyomi_crash_logs.txt](https://github.com/keiyoushi/extensions-source/files/13996309/tachiyomi_crash_logs.txt)
