### ISSUE TITLE
La podrían añadir

### ISSUE THREAD

**Issue by Blade1170** [keiyoushi/tachiyomi-extensions-source#3966]
### Source name

Anonimustls

### Source link

https://anonimustls.com/

### Source language

Español 

### Acknowledgements

- [x] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Uses MangaEsp theme, api url is ' https://api.anonimustls.com'
