### ISSUE TITLE
Step1 not defined error in readcomiconline source

### ISSUE THREAD

**Issue by ferdinerdo** [keiyoushi/tachiyomi-extensions-source#3968]
### Source information

readcomiconline 1.4.18

### Source language

English

### Steps to reproduce

1. Open Mihon
2. Select a series from my library from the source readcomiconline
3. Select a chapter from the series

### Expected behavior

Should open so I can read the chapter.

### Actual behavior

Opens a black screen and loads for a bit before quitting with the error message 'step1 not defined'.

Tried downloading chapters but they also don't work, tries to download for a bit but quits before any actual downloading is done. Ends up with a red exclamation mark.

I opened the webview and the page for the series works, but whenever I try to access the chapters it pulls me out to a default Google search bar screen. I tried going on my default browser and it works there.

Tried other extensions and they work fine too.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
You're two versions behind the current ReadComicOnline extension in our repo, which already got that issue fixed. Uninstall your old RCO, and reinstall it
