### ISSUE TITLE
MangaSwat : url change

### ISSUE THREAD

**Issue by OtakuArab** [keiyoushi/tachiyomi-extensions-source#3969]
### Source information

MangaSwat 1.4.48

### Source language

Arabic

### Source new URL

https://t1manga.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Just an FYI that you can change the base URL in the extension's settings (Tachi/Mihon Browse Page > Extensions tab > MangaSwat)
