### ISSUE TITLE
Kuaikuai Manhua 3: Failed to load images, failed to display covers

### ISSUE THREAD

**Issue by roundcount** [keiyoushi/tachiyomi-extensions-source#397]
### Source information

Kuaikuai Manhua 1.4.6

### Source language

Chinese

### Steps to reproduce

1. Open "Kuaikuai Manhua 3 (快快漫画3)";
2. Search for a comic;
3. Choose any one and start reading.

### Expected behavior

Covers and images can be displayed normally.

### Actual behavior

1. Failed to display covers;
![Screenshot_20240120_033959](https://github.com/keiyoushi/extensions-source/assets/30615130/a38b69de-f6a2-47ec-80e5-055ae7b53dbe)
2. Failed to load images, but the number of images in a chapter seems to be correct;
![Screenshot_20240120_032011](https://github.com/keiyoushi/extensions-source/assets/30615130/b1fa072f-9344-47ac-9871-f65e080297f2)
3. WebView shows an empty page, the URL seems to be a certain image (not sure if it is correct).
![Screenshot_20240120_032904](https://github.com/keiyoushi/extensions-source/assets/30615130/fe38eef0-575a-46e5-ae54-09e938c30a60)

### Tachiyomi version

Mihon 0.16.1 and Tachiyomi 0.15.3

### Android version

Android 14

### Other details

I opened the URL shown in the WebView on my PC's Chrome, and an image in WebP format is immediately downloaded, which seems to be sized correctly but won't open in Chrome and the image viewer (corrupted?).
![CorruptedImage](https://github.com/keiyoushi/extensions-source/assets/30615130/ad5165be-bd8f-4bb2-8efd-f995daea2572)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by SnakeDoc83** [comment]
Seems like the website is dead

**Comment by beer-psi** [comment]
Closed by #690

**Comment by ZerOri** [comment]
图源站点已经挂了几个月了，站长大概是不打算维护了。
