### ISSUE TITLE
Still getting no pages found for chapter

### ISSUE THREAD

**Issue by iamkroot** [keiyoushi/tachiyomi-extensions-source#3972]
### Source information

TCB Scans 1.4.8

### Source language

English

### Steps to reproduce

Open One Piece, try to read latest chapter (1120)

### Expected behavior

Should open the pages

### Actual behavior

Getting a "No pages found for chapter" 

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 14

### Other details

Related #3781, supposed to be fixed in 1.4.8 but still getting the same error. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
~Pull down on the chapter list and update it, and yes I did read it, right when it came out, worked fine.~
Whoops seems they changed the url after a while to stop the DDOS. 

Be early and get it or be late and wait.

**Comment by iamkroot** [comment]
Hmm I'm confused. The `.me` URL is still opening. Clicking on the chapter redirects to the weird URL. As long as we can open the `.me` URL, why can't we follow all the redirects to get to the chapter?

Or are they changing the page DOM and causing our extractor to break?

**Comment by Smol-Ame** [comment]
As mentioned in #3781, might be TCB's way to avoid getting bonked by using a separate/fake college site to host the chapter. Looking at their previous chapters, seems they moved it back onto their site once the heat has died down.

And their redirect link (at least the ending portion) to the fake site is different compared to before. So extension is probably trying to grab the from the wrong link.

**Comment by Norsze** [comment]
The page code is not the same, the images are not at the same spot inn the code as the previous one or the normal domain. Imagine telling a robot to pull the text from a book when a sentence starts with *ME*, and then someone goes in and changes them all to *YOU*. Any change will mess it up

**Comment by AwkwardPeak7** [comment]
now the chapter is on their own site...
