### ISSUE TITLE
Drake scans domain changed

### ISSUE THREAD

**Issue by aki-code** [keiyoushi/tachiyomi-extensions-source#3977]
### Source information

Drake scans 1.4.42

### Source language

English 

### Steps to reproduce

1. Open the extension via latest tab
2. You will observe nothing loading unable to reach host
![Screenshot_20240712-151537](https://github.com/user-attachments/assets/99379527-bd7e-49f1-a42d-de083e7f037a)

### Expected behavior

It should load manga previews

### Actual behavior

Nothing appearing 

### Mihon/Tachiyomi version

Version 0.16.5-6768

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Source changed domain URLs

Don't close this, but if you go into WebView, and let it load, then back out of WebView, you should be able to load stuff up (until the extension gets updated with new URL)

**Comment by aki-code** [comment]
> Source changed domain URLs
> 
> Don't close this, but if you go into WebView, and let it load, then back out of WebView, you should be able to load stuff up (until the extension gets updated with new URL)

Still same, nothing working. Yes, they change it to drake comic

**Comment by Smol-Ame** [comment]
> Still same, nothing working. Yes, they change it to drake comic 

Don't know why you'd thumbs down when I'm trying to provide a possible workaround. Fresh app, works immediately, try going to Mihon Settings > Advanced, and "Clear Cookies" and "Clear WebView Data". Maybe also Mihon Settings > Data and storage, and "Clear Chapter Cache" as well.

![Screenshot_20240712_032310_Mihon.png](https://github.com/user-attachments/assets/768a9826-2199-418c-a7e3-0c789a55b6ca)

![Screenshot_20240712_032314_Mihon.png](https://github.com/user-attachments/assets/4d1c9ad8-d0d2-4797-a09e-d4992ffc7372)

**Comment by aki-code** [comment]
Thank you.. aah sorry for that thumbs down.. as it was not working for me. Now, i got it properly explained.

**Comment by aki-code** [comment]
> > Still same, nothing working. Yes, they change it to drake comic
> 
> Don't know why you'd thumbs down when I'm trying to provide a possible workaround. Fresh app, works immediately, try going to Mihon Settings > Advanced, and "Clear Cookies" and "Clear WebView Data". Maybe also Mihon Settings > Data and storage, and "Clear Chapter Cache" as well.
> 
> ![Screenshot_20240712_032310_Mihon.png](https://private-user-images.githubusercontent.com/155411819/348226847-768a9826-2199-418c-a7e3-0c789a55b6ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3OTI1MDIsIm5iZiI6MTcyMDc5MjIwMiwicGF0aCI6Ii8xNTU0MTE4MTkvMzQ4MjI2ODQ3LTc2OGE5ODI2LTIxOTktNDE4Yy1hN2UzLTBjNzg5YTU1YjZjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQxMzUwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05N2VmMGJkODQ5YjkwZDQ2OGEyNzIzYzZhNmU1NmU0ZWI1ZDYzMGJkZDA3ODI3Njg2NTVjMGYxZjZhMjc1OTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5wiOa9IPRYZeItqZXFnFSNEuPt_bgriuTJ9J-s0eMIU)
> 
> ![Screenshot_20240712_032314_Mihon.png](https://private-user-images.githubusercontent.com/155411819/348226877-4d1c9ad8-d0d2-4797-a09e-d4992ffc7372.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3OTI1MDIsIm5iZiI6MTcyMDc5MjIwMiwicGF0aCI6Ii8xNTU0MTE4MTkvMzQ4MjI2ODc3LTRkMWM5YWQ4LWQwZDItNDc5Ny1hMDllLWQ0OTkyZmZjNzM3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQxMzUwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWJiNTQ1YzNkNTk2NmEwY2MwMWZlZjk5NjZhNjQ5OWZjN2I1OGU1ZDM2NDM1NzY5MDA3YjliOGY2ZDkzN2YwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WFWKdw78_josC02wCJkUDnTb8oam4R2fwENiUTzJWhY)

![Screenshot_20240712-191941](https://github.com/user-attachments/assets/3c5e2a07-aa3d-4e49-b7bc-ce5bc4a14b8e)
Worked for few minutes then again
