### ISSUE TITLE
Eu queria pedir a adição de uma nova extensão no aniyomi 

### ISSUE THREAD

**Issue by Joaopdr18** [keiyoushi/tachiyomi-extensions-source#3980]
### Source name

Newzect

### Source link

https://newzect.com/

### Source language

Português - PT-BR

### Other details

![Screenshot_20240712-134105](https://github.com/user-attachments/assets/593d2fd0-e204-4c0d-a5f1-995cd99fcefa)
![Screenshot_20240712-131708](https://github.com/user-attachments/assets/704218d5-fa37-4887-9dc1-ceb50ee1ac4a)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Keiyoushi its a manga extensions repo, we don't do anime extensions
