### ISSUE TITLE
Doujins: Stream was reset: CANCEL

### ISSUE THREAD

**Issue by Gostik21** [keiyoushi/tachiyomi-extensions-source#3982]
### Source information

Doujins 1.4.5

### Source language

English 

### Steps to reproduce

Open extension or added in library manga

### Expected behavior

manga list will be shown

### Actual behavior

StreamResetException: stream was reset: CANCEL 

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kyoyacchi** [comment]
Try using vpn

**Comment by Gostik21** [comment]
I got this text with vpn

**Comment by kyoyacchi** [comment]
> I got this text with vpn

Hmm weird, it works fine with vpn on my side

**Comment by Gostik21** [comment]
> > I got this text with vpn
> 
> Hmm weird, it works fine with vpn on my side

乁( ⁰͡ Ĺ̯ ⁰͡ ) ㄏ, i used 2 vpn app and the text is still the same. I also tried different countries

**Comment by kyoyacchi** [comment]
> > > I got this text with vpn
> > 
> > 
> > Hmm weird, it works fine with vpn on my side
> 
> 乁( ⁰͡ Ĺ̯ ⁰͡ ) ㄏ, i used 2 vpn app and the text is still the same. I also tried different countries

are u using protonvpn? Maybe you can try clearing your cookies by going "Settings - Advanced - (Network) "clear cookies". I am using TachiyomiJ2K btw, you can try j2k too if you want
J2K:
![Screenshot_20240715-143749](https://github.com/user-attachments/assets/38325953-4f79-4973-a27c-c51c5a368de1)

**Comment by Gostik21** [comment]
I use Nomad VPN. Сlearing cookies helped. Thanks

**Comment by kyoyacchi** [comment]
> I use Nomad VPN. Сlearing cookies helped. Thanks

Glad to hear that:)

**Comment by choppeh** [comment]
This issue can be closed.
