### ISSUE TITLE
Say hentai

### ISSUE THREAD

**Issue by HutaoNya** [keiyoushi/tachiyomi-extensions-source#3988]
### Source name

Say hentai

### Source link

https://sayhentai.one/

### Source language

Tiếng việt

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Wrong request type (but someone will fix it later probably), for future reference, any URL changes for extensions you should choose "Domain changed"

(Unless you didn't know that this source is already in our repo, reminder to enable Vietnamese in your app's Browse Page, both Sources tab & Extensions tab)
