### ISSUE TITLE
Tsuki Mangás Cloudflare erro

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#3990]
### Source information

Tsuki Mangás 1.4.5

### Source language

Português (Brasil)

### Steps to reproduce

Não tá carregando os mangás na extensão fica dandoo erro "falha ao contornar o Cloudflare"

https://github.com/user-attachments/assets/cfc13f9b-800e-4394-9a43-fd898a1786d3

### Expected behavior

Aparecer as obras normalmente 

### Actual behavior

falha ao contornar o Cloudflare

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Loads on my end. After loading into the site in WebView, try clicking into a manga or try searching to see if there's any extra Cloudflare verification. Afterwards, back out of WebView and retry/refresh the Latest/Popular page.

If that doesn't work, try going into Mihon Settings > Advanced, and "Clear cookies" along with "Clear WebView data", then repeat the steps above.

**Comment by ghost** [comment]
> Loads on my end. After loading into the site in WebView, try clicking into a manga or try searching to see if there's any extra Cloudflare verification. Afterwards, back out of WebView and retry/refresh the Latest/Popular page.
> 
> If that doesn't work, try going into Mihon Settings > Advanced, and "Clear cookies" along with "Clear WebView data", then repeat the steps above.

Não funcionou, só está funcionando quando eu uso um aplicativo para mudar o dns da rede wi-fi, isso tá estranho, vou testar em outro celular pra ver

**Comment by ghost** [comment]
> > Loads on my end. After loading into the site in WebView, try clicking into a manga or try searching to see if there's any extra Cloudflare verification. Afterwards, back out of WebView and retry/refresh the Latest/Popular page.
> > If that doesn't work, try going into Mihon Settings > Advanced, and "Clear cookies" along with "Clear WebView data", then repeat the steps above.
> 
> Não funcionou, só está funcionando quando eu uso um aplicativo para mudar o dns da rede wi-fi, isso tá estranho, vou testar em outro celular pra ver

![IMG_20240713_084034_381](https://github.com/user-attachments/assets/c7f868c3-8542-46e7-be31-38abe4c77f5e)
 No celular da minha mãe também tá assim

**Comment by danroxha** [comment]
@QuagZy Change your user-agent in More > Settings > Advanced > "Default user agent string". And try @Smol-Ame's instructions above again

**Comment by AwkwardPeak7** [comment]
?blurb cf
