### ISSUE TITLE
Mangakakalot entries fails library update check

### ISSUE THREAD

**Issue by imli700** [keiyoushi/tachiyomi-extensions-source#4]
### Source information

Mangakakalot 1.48

### Source language

English

### Steps to reproduce

Update library

### Expected behavior

The library should update without errors

### Actual behavior

The following error occurs:
```
! HTTP error 404
  # Mangakakalot (EN)
    - I Am A Hero
    - Komi-San Wa Komyushou Desu
    - One Piece
```

### Tachiyomi version

0.15.2

### Android version

Android 11

### Other details

The webview from the Extension tab works normally without bugs. However, opening the webview from the series in the Library tab gives `No input file specified`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Eagle1337** [comment]
Migrate mangakakalot to mangakakalot.

**Comment by FourTOne5** [comment]
Mangakakalot changes manga url every so often. Only solution is to migrate from mangakakalot to mangakakalot.
