### ISSUE TITLE
"No chapters found" error on all manga using MangaDex

### ISSUE THREAD

**Issue by KMisthebomb** [keiyoushi/tachiyomi-extensions-source#4]
### Source information

MangaDex 1.4.192

### Source language

All

### Steps to reproduce

1. Open MangaDex from the Browse tab
2. Tap on any comic

### Expected behavior

The chapters should be listed

### Actual behavior

No chapters are listed and a popup saying "No chapters found" appears.

### Tachiyomi version

0.15.0

### Android version

Android 11

### Other details

Other official extensions work properly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Can't reproduce. Please provide more info

**Comment by KMisthebomb** [comment]
I'm running the app on a Pixel 2. I've tried reinstalling the extension but to no avail. Tried clearing cookies & WebView data. Also VPN'd from Japan to the US but didn't change anything. Is there any other info I should supply?

**Comment by KMisthebomb** [comment]
Not sure what happened, but I uninstalled the app and extensions and reinstalled everything and it works now.
