### ISSUE TITLE
Nhentai Extension Not Installing

### ISSUE THREAD

**Issue by NotNeko-Chan** [keiyoushi/tachiyomi-extensions-source#40]
### Source information

Nhentai v1.4.39

### Source language

All

### Steps to reproduce

1. Uninstall all previous versions of Nhentai extension
2. Install extension via downloading

### Expected behavior

Extension should install like normal

### Actual behavior

![Screenshot_20240109_082043_SAI](https://github.com/keiyoushi/extensions-source/assets/144128702/4a07d06a-0fcd-4a7c-818b-029c90642e38)

### Tachiyomi version

0.15.1

### Android version

Android 14

### Other details

Also tried installing through pc, but the installation never completed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by C0rvidae** [comment]
This is mentioned in the official [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/)
**Data backup, uninstall, and fresh installation are required.**

**Comment by NotNeko-Chan** [comment]
> This is mentioned in the official [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/) **Data backup, uninstall, and fresh installation are required.**

The issue occurs even after re-installing

**Comment by ardittristan** [comment]
You have to uninstall and reinstall the extension, not tachiyomi. This repo uses a different signing key than the previous tachiorg repo

**Comment by NotNeko-Chan** [comment]
> You have to uninstall and reinstall the extension, not tachiyomi. This repo uses a different signing key than the previous tachiorg repo

That was the first thing I did, as the Bato.to extension wouldn't work without reinstalling from this repo. I assumed that Nhentai would be the same, so I uninstalled the Nhentai extension before I even re-downloaded it.

It was one of the things that threw me off since I made sure that I had cleared the old completely from my phone.

I double checked the Android/data folder by connecting my phone to my PC after the install kept getting aborted, and while it wasn't there, I was still unable to install the new extension.

**Comment by beer-psi** [comment]
GitHub issues are not for support. Please join [our Discord server](https://discord.gg/3FbCpdKbdY) instead.

**Comment by NotNeko-Chan** [comment]
> GitHub issues are not for support. Please join [our Discord server](https://discord.gg/3FbCpdKbdY) instead.

No problem. Wasn't really looking for support as I could have just used a different extension. Just saw something that about 30 min. of troubleshooting didn't immediately.
