### ISSUE TITLE
Leercapitulo no cargar imágenes 

### ISSUE THREAD

**Issue by BastiVader** [keiyoushi/tachiyomi-extensions-source#4003]
### Source information

Leercapitulo 1.4.9

### Source language

Español

### Steps to reproduce

Entro a Leercapitulo
Elijo el manga/manwha 
Entro al capítulo 
Aparece "time out"
Entro a la web
Aparece el capitulo 

### Expected behavior

Entro a Leercapitulo
Elijo el manga/manwha 
Entro al capítulo 
Leo el capítulo 

### Actual behavior

Entro a Leercapitulo
Elijo el manga/manwha 
Entro al capítulo 
Aparece "time out"
Entro a la web
Aparece el capitulo 

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Xush00** [comment]
es posible que fuera tu conexión, está funcionando bien. abrí 5 capítulos de obras diferentes y todas cargaron
.![Screenshot_2024-07-14-11-01-31-326_eu.kanade.tachiyomi.png](https://github.com/user-attachments/assets/8c6c1c9b-dbe6-4947-95ad-5ace8f4543b6)
