### ISSUE TITLE
Berserker Scan está caído 

### ISSUE THREAD

**Issue by RomanY96** [keiyoushi/tachiyomi-extensions-source#4007]
### Source name

Berserker Scan

### Source language

Español 

### Source link

https://ragnascan.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
Based in https://www.facebook.com/p/Berserker-scan-100069971025696/, author's comments is redirect users to other sources.
