### ISSUE TITLE
CrotPedia

### ISSUE THREAD

**Issue by Fula10** [keiyoushi/tachiyomi-extensions-source#4009]
### Source name

CrotPedia

### Source link

https://103.74.5.104/

### Source language

Indonesia

### Other details

18+/NSFW = yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by 0Ha16wA5** [comment]
Website inaccessible

**Comment by vetleledaal** [comment]
Duplicate of #1116
