### ISSUE TITLE
Union Mangás

### ISSUE THREAD

**Issue by EUSOUOMIORDOMUNDI** [keiyoushi/tachiyomi-extensions-source#401]
### Source name

Union Mangás

### Source link

https://unionmangasbr.org/

### Source language

Brazilian portuguese - português (Brasil)

### Other details

18+/NSFW= yes
![Screenshot_2024-01-19-20-45-59-885_com android chrome](https://github.com/keiyoushi/extensions-source/assets/157127832/85bf7986-3064-4239-856c-8b973f39d85f)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Duplicate of #36
