### ISSUE TITLE
拷貝漫畫 - copymanga.tv

### ISSUE THREAD

**Issue by KiRa937** [keiyoushi/tachiyomi-extensions-source#4010]
### Source name

拷貝漫畫

### Source link

https://www.copymanga.tv/

### Source language

Chinese

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Mihua33** [comment]
https://github.com/stevenyomi/copymanga
