### ISSUE TITLE
Source request

### ISSUE THREAD

**Issue by ohakidev** [keiyoushi/tachiyomi-extensions-source#4011]
### Source name

Hentaithai

### Source link

https://hentaithai.com/doujin

### Source language

Thailand

### Other details

NSFW = yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by ohakidev** [comment]
Pls reopen it not on list in extension

**Comment by Smol-Ame** [comment]
> Pls reopen it not on list in extension

Don't comment bump & don't open another issue when you already have #1381 

All the work is done by contributors volunteering their time. There's no guarantee or deadline/timeframe on when it'll be made into an extension.
