### ISSUE TITLE
Manga Galaxy changed its URL

### ISSUE THREAD

**Issue by ManiV97** [keiyoushi/tachiyomi-extensions-source#4020]
### Source information

Manga Galaxy 1.4.39

### Source language

English 

### Source new URL

https://mangagalaxy.org/

### Other details

Manga Galaxy changed its URL from https://mangagalaxy.me/ to https://mangagalaxy.org/
![Screenshot_20240715_075013](https://github.com/user-attachments/assets/ddbe4258-0cba-4231-8f34-c3d05ed388b7)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
now uses the same theme as vortex scan; (iken?)
