### ISSUE TITLE
ReadComicOnline.li does not load

### ISSUE THREAD

**Issue by TheWrightStuff1994** [keiyoushi/tachiyomi-extensions-source#4026]
### Source information

ReadComicOnline 1.4.20

### Source language

English

### Steps to reproduce

1. Open extension
2. Tried to load comics

### Expected behavior

Loads the comics

### Actual behavior

Nothing appears says there is "java.io.IOException: Failed to bypass Cloudflare" when there isn't I check the website myself

### Mihon/Tachiyomi version

TachiyomiJ2K v1.7.4

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by eyck-dev** [comment]
Can confirm this issue, tried every single user-agent out there, no change. When accessed in web view there is no cloudflare check, even on desktop cant find any cloudflare screen. This issue could be in the extension.

**Comment by AwkwardPeak7** [comment]
Open webview and go to "Comic List" from the ribbon and pass cloudflare check

**Comment by Xori71** [comment]
> Open webview and go to "Comic List" from the ribbon and pass cloudflare check

How do I pass the Cloudflare check?

**Comment by eyck-dev** [comment]
> > Open webview and go to "Comic List" from the ribbon and pass cloudflare check
> 
> How do I pass the Cloudflare check?

you should get a page that asks you tap at the captcha and most of the times it loads the webpage after that, make sure you arent redirected to ad website, if that happens close it and re open it then tap "comic list" and you should get the cloudflare page.

**Comment by Xori71** [comment]
> > > Open webview and go to "Comic List" from the ribbon and pass cloudflare check
> > 
> > 
> > How do I pass the Cloudflare check?
> 
> you should get a page that asks you tap at the captcha and most of the times it loads the webpage after that, make sure you arent redirected to ad website, if that happens close it and re open it then tap "comic list" and you should get the cloudflare page.

Isn’t Captcha different from Cloudflare? If it wanted me to solve the Captcha, Mihon would give me the Captcha toast message.

**Comment by eyck-dev** [comment]
> Open webview and go to "Comic List" from the ribbon and pass cloudflare check

still get no pages found

@Xori71 yes i did not mean captcha but the cloudflare message

**Comment by Xori71** [comment]
> > Open webview and go to "Comic List" from the ribbon and pass cloudflare check
> 
> still get no pages found
> 
> @Xori71 yes i did not mean captcha but the cloudflare message

Yeah, I did it as well, and the issue persists.

**Comment by trancephormer** [comment]
For me the cloudflare check is passing, but the actual comics do not load and the "no pages found" error toast is popping up. I cleared the check by going into websview and comic list and i can search for and add comics in the extension but clicking on chapter gives the error toast. The comic chapters. are viewable in the webview too.

**Comment by Xori71** [comment]
> For me the cloudflare check is passing, but the actual comics do not load and the "no pages found" error toast is popping up. I cleared the check by going into websview and comic list and i can search for and add comics in the extension but clicking on chapter gives the error toast. The comic chapters. are viewable in the webview too.

Yup, exactly the same for me. (Just making it clear, in case my previous replies didn’t)

**Comment by vetleledaal** [comment]
> > still get no pages found
>
>  [...] and the issue persists.

> > [...] the actual comics do not load and the "no pages found" error toast is popping up.
>
> Yup, exactly the same for me. 

This is separate from the issue reported here. Getting past the Cloudflare page is a solved issue (troubleshooting guide, change User-Agent). Please redirect discussion around the 'no pages found' issue here: #4028
