### ISSUE TITLE
Quero pedir uma adição de uma nova extensão que surgiu no Português Brasileiro

### ISSUE THREAD

**Issue by DRochaz** [keiyoushi/tachiyomi-extensions-source#4027]
### Source name

CentralNovel

### Source link

https://centralnovel.com/series/

### Source language

Português Brasil - PT-BR

### Other details

![Screenshot_2024-07-15-11-12-57-561_app mihon](https://github.com/user-attachments/assets/71805604-daba-4a14-96fa-54a2eb048b20)
![Screenshot_2024-07-15-11-04-53-127_com opera browser](https://github.com/user-attachments/assets/d2371f4f-a6d8-4902-80fa-d990dc6e5a3f)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
Novels not supported (unless they are images).
