### ISSUE TITLE
Readcomiconline.li "No pages found"

### ISSUE THREAD

**Issue by trancephormer** [keiyoushi/tachiyomi-extensions-source#4028]
### Source information

Readcomiconline.li

### Source language

English

### Steps to reproduce

Click on any chapter
"No pages found" error toast pops up

### Expected behavior

Chapter should open normally 

### Actual behavior

Comics are viewable and searchable (passed cloudflare check in webview and comics list) but clicking on chapter gives error toast "no pages found"
Comic chapters are viewable in webview as well 

### Mihon/Tachiyomi version

0.16.5(6)

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AlexandrRucodainii** [comment]
Hello, i updated the extension following the merge of  #4041 and tried to open a comic. I still can't open any comics in app itself with the error message "Failed to find image URLs", but it opens fine in the WebView
![image](https://github.com/user-attachments/assets/6260e9f2-5320-46f5-a1a0-5d8ca4d40711)
![image](https://github.com/user-attachments/assets/e62def3e-9a66-4747-a875-5f846e55d9fa)

**Comment by TheWrightStuff1994** [comment]
Yeah it still does not work... "Failed to find URLs"

**Comment by AlexandrRucodainii** [comment]
> Yeah it still does not work... "Failed to find URLs"

Just got fixed in the new update!

**Comment by TheWrightStuff1994** [comment]
> > Yeah it still does not work... "Failed to find URLs"
> 
> Just got fixed in the new update!

Yeah you are correct I had to go to Mihon where it updated again to 1.4.22 and now I can read comics but can't look at the Popular or Latest pages still

**Comment by AlexandrRucodainii** [comment]
> > > Yeah it still does not work... "Failed to find URLs"
> > 
> > 
> > Just got fixed in the new update!
> 
> Yeah you are correct I had to go to Mihon where it updated again to 1.4.22 and now I can read comics but can't look at the Popular or Latest pages still

That's the issue with cloudflare protection. Go to the WebView and go to the Comics List page, which should trigger the check

**Comment by TheWrightStuff1994** [comment]
> > > > Yeah it still does not work... "Failed to find URLs"
> > > 
> > > 
> > > Just got fixed in the new update!
> > 
> > 
> > Yeah you are correct I had to go to Mihon where it updated again to 1.4.22 and now I can read comics but can't look at the Popular or Latest pages still
> 
> That's the issue with cloudflare protection. Go to the WebView and go to the Comics List page, which should trigger the check

Thanks it works now!

**Comment by shadynak** [comment]
> > > > > Yeah it still does not work... "Failed to find URLs"
> > > > 
> > > > 
> > > > Just got fixed in the new update!
> > > 
> > > 
> > > Yeah you are correct I had to go to Mihon where it updated again to 1.4.22 and now I can read comics but can't look at the Popular or Latest pages still
> > 
> > 
> > That's the issue with cloudflare protection. Go to the WebView and go to the Comics List page, which should trigger the check
> 
> Thanks it works now!

Hello! This fix does load up the list of comics but there's a new Java IO Integers recasting error on trying to download from the site (https://www.reddit.com/r/mangarockapp/s/lDaSNBUGzq)

**Comment by Smol-Ame** [comment]
> Hello! This fix does load up the list of comics but there's a new Java IO Integers recasting error on trying to download from the site (https://www.reddit.com/r/mangarockapp/s/lDaSNBUGzq)

Known issue, the source broke the extension again after the recent update. Wait for a future extension update, but it might be better to use/migrate to a better source.
