### ISSUE TITLE
Hitomi.la Downloads enhancement

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#4030]
### Source name

hitomi.la

### Source language

English

### Describe your suggested feature

Feature request to add option to choose between native encoded image format: avif and jxl over default webp for downloads.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
option for avif can be added but jxl is broken on the site, no jxl link works

**Comment by ghost** [comment]
> option for avif can be added but jxl is broken on the site, no jxl link works

that's fine as well! just avif is okay
