### ISSUE TITLE
Ancient Comics (Pt-Br Source) shows the chapters backwards.

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#4031]
### Source information

Ancient Comics 1.4.30

### Source language

Portuguese Brazilian 

### Steps to reproduce

The chapters appear in reverse order, and when each chapter ends it does not automatically move on to the next.

![Screenshot_2024-07-15-18-04-00-882_app mihon](https://github.com/user-attachments/assets/c67764f7-4b0d-4c15-8118-93839f379144)

### Expected behavior

Read chapters without having to manually switch to another chapter.

### Actual behavior

I have to manually scroll through the chapters because they are in reverse order.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Change the sort order for the manga entry?

This is just how the source themselves have their chapter list
![Screenshot_20240715_142015_Firefox Nightly.png](https://github.com/user-attachments/assets/656c5718-6d80-44b3-b050-f2a4cfc87579)
