### ISSUE TITLE
MangaFire WAF security

### ISSUE THREAD

**Issue by DDRook** [keiyoushi/tachiyomi-extensions-source#4035]
### Source information

MangaFire 1.4.6

### Source language

All

### Steps to reproduce

Try to update, or open ANY pages for extension

### Expected behavior

Should update, download, or open manga or site

### Actual behavior

Null error on tachiyomi view, or WAF Security error on webview

### Mihon/Tachiyomi version

App version: 0.16.5 (standard, 2a01a2a, 6, 2024-04-09T09:58:14Z) Android version: 14 (SDK 34; build UP1A.231005.007.S908WVLS6EXF8) Device brand: samsung Device manufacturer: samsung Device name: b0q (b0qcsx) Device model: SM-S908W WebView: Android System WebView 126.0.6478.134

### Android version

Android 14

### Other details

When accessing site direct from browser or computer no issues with WAF security. Only when accessing through tachiyomi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
As mentioned before in the Keiyoushi Discord repo-support channel:

![Screenshot_20240715_201953](https://github.com/user-attachments/assets/10423655-e71b-469f-acb5-34312683a2f7)

* Go to Mihon Settings > Advanced
 * Clear cookies + Clear WebView Data
 * Change your user-agent (search "latest user-agent", copy & paste any into your app, restart, check WebView)

**Comment by DDRook** [comment]
Damn, I've done the CCC and webview stuff, any known useragents that seem to be working?

**Comment by Smol-Ame** [comment]
> Damn, I've done the CCC and webview stuff, any known useragents that seem to be working?

There isn't a specific user-agent that works for everybody, especially due to differences in source, region, and Cloudflare protection level.

Search up "latest user-agents", go to any of the sites, copy & paste a new user-agent into Mihon, restart Mihon & check WebView to see if it passes, if it doesn't pass, repeat

**Comment by DDRook** [comment]
I'm looking for web browser user agents, right? Not OS user agents?

**Comment by Smol-Ame** [comment]
> I'm looking for web browser user agents, right? Not OS user agents?

Any browser, any OS, and any device, whatever makes it work for you. Remember to restart the app after changing the UA & checking WebView to see if it works/passes

**Comment by DDRook** [comment]
looks like im not gonna get any luck, ive used every one i can find and i pass through the WAF but opening any other of their pages prompts the WAF again and i still get the Json error/Null error

**Comment by vetleledaal** [comment]
Try using one of the User-Agents @ https://www.useragents.me/ 
I will be closing this issue as others are unable to reproduce it.

If you are still facing issues after changing the User-Agent, please provide a specific entry and chapter this issue occurs on so it can be tested. For example, Jujutsu Kaisen - Chapter 271 loads just fine for me.
