### ISSUE TITLE
DMC scan no pages found

### ISSUE THREAD

**Issue by samanta-widjaja** [keiyoushi/tachiyomi-extensions-source#4036]
### Source information

DMC scan 1.4.10

### Source language

English

### Steps to reproduce

1. Update chapter list, and the new chapter show up
2. Download / read chapter from app not working, says no page
3. From webview is fine 

### Expected behavior

Can read / download

### Actual behavior

Can't read / download

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
the website seems dead, do you know if they changed domain?

**Comment by samanta-widjaja** [comment]
![Screenshot_2024-08-08-00-42-09-366_com opera browser](https://github.com/user-attachments/assets/6ea5873f-f791-4b2c-9737-3d9438eef35e)

**Comment by Achuabdu** [comment]
https://didachapters.blogspot.com/?m=1

**Comment by Achuabdu** [comment]
![Uploading Screenshot_2024-08-18-06-22-02-991_com.android.chrome.jpg…]()

**Comment by Achuabdu** [comment]
![Uploading Screenshot_2024-08-18-09-49-46-368_com.android.chrome.jpg…]()

**Comment by Achuabdu** [comment]
![Screenshot_2024-08-18-09-49-46-368_com android chrome](https://github.com/user-attachments/assets/6e3885d8-2748-43ff-8966-921335efbbbc)

**Comment by AwkwardPeak7** [comment]
closing in favor of #4675
