### ISSUE TITLE
Não está carregando a fonte

### ISSUE THREAD

**Issue by Leklek185** [keiyoushi/tachiyomi-extensions-source#4037]
### Source information

Tsuki Mangás

### Source language

Português Brasileiro PT-BR

### Steps to reproduce

A página do Tsuki Mangás não está carregando os mangás

### Expected behavior

![Screenshot_20240716-014002_Mihon](https://github.com/user-attachments/assets/56765f3b-dd12-4001-b269-3fe6ce2aff2f)

### Actual behavior

![Screenshot_20240716-013953_Mihon](https://github.com/user-attachments/assets/b9139c94-9eeb-47a0-a349-b631a47f44e0)

### Mihon/Tachiyomi version

0.16.5

### Android version

0.9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
It tells you in the error, it failed to pass Cloudflare. Go into WebView & pass the Cloudflare verification. If the Cloudflare verification loops, or it doesn't pass the verification, go to your Mihon Settings > Advanced, and then change the "user-agent".

Search "latest user-agents" on Google, then go to any of the sites, copy & paste any of the user-agents from those sites into your app. Afterwards, restart Mihon, check WebView to see if it passes, if it doesn't, repeat the steps.
