### ISSUE TITLE
MangSwat: url change

### ISSUE THREAD

**Issue by Etsh72** [keiyoushi/tachiyomi-extensions-source#4045]
### Source name

MangSwat

### Source language

Arabic

### Source link

https://swatoon.com/

### Other details

Please fix this extension 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
Duplicate of #4099
