### ISSUE TITLE
InariManga

### ISSUE THREAD

**Issue by BastiVader** [keiyoushi/tachiyomi-extensions-source#4050]
### Source information

InariManga 1.4.40

### Source language

Español

### Source new URL

https://nakamatoon.com/

### Other details

Creo que cambio de nombre y sitio 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Seems like that site is just a wrapper, all series are redirecting to `https://inaripikav.org` or `https://ukiyotoon.com/`
