### ISSUE TITLE
save custom tag filter like tachiyomisy

### ISSUE THREAD

**Issue by ikhoeyZX** [keiyoushi/tachiyomi-extensions-source#406]
### Source name

nhentai

### Source language

all

### Describe your suggested feature

![Screenshot_20240120_092049_Mihon](https://github.com/keiyoushi/extensions-source/assets/79812109/2a9fc5c4-03e1-4d11-a0d8-832c3fe04626)
tachiyomiSY have buildin some extension with some extra feature like save tag (in nhentai), so does it's possible add to all or some extension?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
Not possible through the extension. You can request this feature to the app you are using.
