### ISSUE TITLE
Manga galaxy url change/update required

### ISSUE THREAD

**Issue by van2kot** [keiyoushi/tachiyomi-extensions-source#4068]
### Source information

"Manga Galaxy 1.4.39"

### Source language

English 

### Source new URL

https://mangagalaxy.org/home

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by van2kot** [comment]
The issue was closed but not solved previously

**Comment by Smol-Ame** [comment]
> The issue was closed but not solved previously

No, this issue was closed because it's been reported already & is waiting for future fix to close the mentioned issue. For future reference, search the existing issues before opening a new one, and acknowledging that you did when you didn't.
