### ISSUE TITLE
Lỗi không load được

### ISSUE THREAD

**Issue by HutaoNya** [keiyoushi/tachiyomi-extensions-source#4069]
### Source information

SayHentai 1.4.8

### Source language

Tiếng việt

### Steps to reproduce

![Screenshot_2024-07-17-15-04-07-877_app mihon](https://github.com/user-attachments/assets/2a258855-f988-4416-99ba-83a580a5e176)

### Expected behavior

![Screenshot_2024-07-17-15-04-07-877_app mihon](https://github.com/user-attachments/assets/ffbca7b6-16e2-4d60-b9ce-2d65a2625ffb)

### Actual behavior

![Screenshot_2024-07-17-15-04-07-877_app mihon](https://github.com/user-attachments/assets/92e0af8c-894a-4a05-9fee-c593bc665e11)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 10

### Other details

![Screenshot_2024-07-17-15-04-07-877_app mihon](https://github.com/user-attachments/assets/8413b753-8a7c-4b66-b3df-66b9ef95a3d5)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Why'd you upload four of the same screenshot?

Go into WebView, check for errors/Cloudflare verification. If you can't pass Cloudflare verification/it's looping, change your user-agent in Mihon Settings > Advanced. Remember to restart Mihon after changing the UA, and checking WebView afterwards to see if it passes.

If there's no errors, try going to Mihon Settings > Data and storage, and "Clear chapter cache" in there, maybe throw in "Clear cookies" + "Clear WebView data" in Mihon Settings > Advanced for good measure. Also, what's the entry's name & chapter that you are having this issue? Don't send any NSFW images in here, just the name & chapter number.

**Comment by HutaoNya** [comment]
Every chapter has the same error as in the picture and it's just a story on sayhentai 1.4.8 and it doesn't load. I tried other stories and it's the same.😢😢

**Comment by Smol-Ame** [comment]
Sounds like an internet related issue then, did you check WebView for errors?

If it doesn't load in WebView at all:
* Switch networks (mobile data to WiFi, vice-versa)
* Use a VPN
* Enable/disable DNS over HTTPS in Mihon Settings > Advanced

**Comment by HutaoNya** [comment]
not you I tried using vpn DNS HTTPS in advanced but only sayhentai is the problem I use 3g wifi all is fine the network problem is not I even tried the user agent but it doesn't work and when I go to the webView it reads normally just In mihon application every sayhentai is suffered

**Comment by vetleledaal** [comment]
What entry and chapter is not working for you? I was able to load "Ân huệ trời ban!" Chapter 14 just fine.

**Comment by Norsze** [comment]
tried multiple entries I see nothing wrong and he never responded, closing this.
