### ISSUE TITLE
Readcomiconline.li Java.lang error

### ISSUE THREAD

**Issue by trancephormer** [keiyoushi/tachiyomi-extensions-source#4073]
### Source information

Readcomiconline.li

### Source language

English

### Steps to reproduce

Click on chapter after the latest update to the extension 1.4.22

### Expected behavior

Chapter should open normally

### Actual behavior

Failing with error after the new update to v1.4.22
Fails with error - "Java.lang.integer cannot be cast to Java.lang"
![Screenshot_20240717-193617_Mihon_1](https://github.com/user-attachments/assets/4810a223-af66-4878-9da3-d59fa9ed39ac)

### Mihon/Tachiyomi version

0.16.5(6)

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Pempo01** [comment]
Why are there so many issues with readcomiconline? It seems that whenever the devs solve an issue, something else immediately crops up. Is the website that protective?

**Comment by AwkwardPeak7** [comment]
They are intentionally breaking it. Migrate to better sources.

**Comment by FinSnow** [comment]
> They are intentionally breaking it. Migrate to better sources.

Sadly they are the only source that quickly updates their comics .. all other available sources are much slower and some don't have all the western comics.

**Comment by watashinosoulsociety** [comment]
> They are intentionally breaking it. Migrate to better sources.

Name some better sources bro ? Most of the sources have very bad quality of comics
