### ISSUE TITLE
Komga novel support

### ISSUE THREAD

**Issue by IMJoyJ** [keiyoushi/tachiyomi-extensions-source#4085]
### Source name

Komga

### Source language

N/A

### Describe your suggested feature

Komga has supported novel(epub) for a while but this plugin still can't read them properly.
Have to use WebView.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #3270

Tachi/Mihon can't do novels/text epubs
