### ISSUE TITLE
ReadComicOnline "No pages found"

### ISSUE THREAD

**Issue by JudgeDreddpool** [keiyoushi/tachiyomi-extensions-source#4092]
### Source information

ReadComicOnline 1.4.24

### Source language

English

### Steps to reproduce

1. Choose any comic series
2. Select any issue and open

### Expected behavior

The comic should open as normal and be readable.

### Actual behavior

The comic doesn't load and you're booted back to the comics page with the error "No pages found".

### Mihon/Tachiyomi version

Preview r7801

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by JudgeDreddpool** [comment]
![Screenshot_20240718-162745_Aniyomi](https://github.com/user-attachments/assets/834b0c86-6e96-4114-9abc-013a89db0e3c)

**Comment by kinglugus90** [comment]
It aint getting fixed. The RCO devs keep breaking it.

**Comment by JudgeDreddpool** [comment]
Seriously? How the hell are they breaking it, cause I must be missing something here.
