### ISSUE TITLE
Suspicious code in ReadComicOnline source?

### ISSUE THREAD

**Issue by minijackson** [keiyoushi/tachiyomi-extensions-source#4093]
### Describe why this should be added

I've looked at https://github.com/keiyoushi/extensions-source/commit/44853b51e1ab7f33e2965510f9ad65aedf8c9c05 before upgrading the ReadComicOnline source, and thought the changes looked suspicious: I'm not sure I see any reason for the ReadComicOnline source to execute obfuscated Javascript code. I might be wrong, though, can anyone help in analyzing what this code does?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by minijackson** [comment]
cc @AwkwardPeak7 as committer

**Comment by AwkwardPeak7** [comment]
It was an attempt to prevent them from breaking it so easily, which they did anyway.

**Comment by minijackson** [comment]
I see, to prevent them to override defined functions / variables? Would it be possible to obfuscate the code at build time or runtime so that the source stays auditable?

**Comment by minijackson** [comment]
I'm sorry @AwkwardPeak7 but I still find fetching and running code from a repo only you manage suspicious…

**Comment by AwkwardPeak7** [comment]
@minijackson you are free to not use the extension

**Comment by minijackson** [comment]
That is true, but I am still concerned about the security of devices of people who might not be active in this GitHub repo.

**Comment by beer-psi** [comment]
It's a sandboxed QuickJS environment, you can't do shit in there. It's not full-blown WebView JS. The worst thing you can probably do in there is cause an OOM and crash the app.
