### ISSUE TITLE
The domain of the page changed

### ISSUE THREAD

**Issue by Senkunsito** [keiyoushi/tachiyomi-extensions-source#4102]
### Source information

 Matraz scan 1.4.37

### Source language

spanish

### Source new URL

https://panconcola.com/

### Other details

cannot read chapters or update

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #4100
