### ISSUE TITLE
Extension Webtoonscan is not working

### ISSUE THREAD

**Issue by necropower** [keiyoushi/tachiyomi-extensions-source#4107]
### Source information

Webtoonscan 1.4.36

### Source language

English and japanese

### Steps to reproduce

You just need to search for any manga or use the 'popular or 'recent ' tabs... it always gives a socket timeout  exception

### Expected behavior

A List of mangas

### Actual behavior

Timeout

### Mihon/Tachiyomi version

0.16.5

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
Cannot reproduce, maybe was a hiccup from the site
