### ISSUE TITLE
Senshi Manga

### ISSUE THREAD

**Issue by Tato1995a** [keiyoushi/tachiyomi-extensions-source#4113]
### Source information

Senshi Manga 1.4.2

### Source language

Spanish 

### Steps to reproduce

1 Daily update is performed
2 Error occurs when updating senshi manga titles
![348501608-71f64700-8635-46c6-84fd-550731fdceb0](https://github.com/user-attachments/assets/ea25c7a8-4775-4085-b79d-9034a0fbb843)

### Expected behavior

Updates normally

### Actual behavior

The extension does not open any titles
![348501636-8f166a62-bd50-4cec-8e7b-f0da85100dfb](https://github.com/user-attachments/assets/1b2552a4-c0dd-46cd-bd82-6f5b38f2405b)

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 14

### Other details

Apparently they changed servers

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Update your extension, latest version is 1.4.3

**Comment by Tato1995a** [comment]
> Update your extension, latest version is 1.4.3



> Actualice su extensión, la última versión es 1.4.3

If you are right I put wrong version is 1.4.3 and if you can review it please that version is failing by server change thanks
