### ISSUE TITLE
Readcomiconline.li bug "the image couldn't be loaded"

### ISSUE THREAD

**Issue by Pempo01** [keiyoushi/tachiyomi-extensions-source#4115]
### Source information

ReadComicOnline 1.4.26

### Source language

English

### Steps to reproduce

1. Choose any comic series
2. Select any issue and open

### Expected behavior

Comic should open and be readable

### Actual behavior

Comic opens in blank and message "The image couldn't be loaded" pops up alongside the options to retry and open in webview

### Mihon/Tachiyomi version

Tachiyomi Stable 15.3

### Android version

Android 11

### Other details

Solving webview captcha doesn't solve the issue.
Chainging user agent string doesn't solve the issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
RCO is actively breaking our extension, please wait for a fix (but expect it to break), but you might be better off migrating to a different source

**Comment by Pempo01** [comment]
Yes, I've noticed. I'd love to change sources, but none have the quality or quantity of RCO. Of course I'll be patient and wait to see if the devs can do anything about it (although they have already done so much.)

**Comment by onorino** [comment]
I'm trying to access the same source from windows subsystem for Android but I'm stuck in bypassing cloudflare.
I open the webview and the page for human confirmation appears but no matter how may times I try. to confirm the page reloads by itself.

By opening the same page from native windows browser (chrome, Firefox or edge) the bypass works perfectly.

Already tried to clear data of webview but no success.

Anything else I can try?

**Comment by Norsze** [comment]
@onorino You can go to our [website](https://keiyoushi.github.io/docs/guides/troubleshooting#cloudflare) for troubleshooting cloudflare issues. You're better off going to the Discord for help, these issue tickets are for stuff that needs patches to be fixed. They are not really optimal or supposed to be used for giving support

**Comment by onorino** [comment]
Already tried  everything, this is the reason why I wrote here.

I suspect it is an issue of the app preventing usage from Android emulator for Windows as it seems running on native Android devices works as expected.

Strange as I had no issues for years with the same source…

> @onorino You can go to our [website](https://keiyoushi.github.io/docs/guides/troubleshooting#cloudflare) for troubleshooting cloudflare issues. You're better off going to the Discord for help, these issue tickets are for stuff that needs patches to be fixed. They are not really optimal or supposed to be used for giving support
