### ISSUE TITLE
ReadM & MangaMonks dead

### ISSUE THREAD

**Issue by Smol-Ame** [keiyoushi/tachiyomi-extensions-source#4116]
### Source name

ReadM & MangaMonks

### Source language

English

### Source link

https://readm.today & https://mangamonks.com

### Other details

Mentioned in the repo-support channel

![Screenshot_20240719-210550](https://github.com/user-attachments/assets/9475cedd-9fe7-4107-8113-d7839659bdc5)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Really should be two separate issues, but maybe it's ok this once?

**Comment by thebloodyauthor** [comment]
should be, but it was announced that they were closing all affiliated sites.

**Comment by ghazraoui** [comment]
is there anyway to get data on our readlist for readm ? lost all my bookmarks and where I was in the stories...

**Comment by Smol-Ame** [comment]
> is there anyway to get data on our readlist for readm ? lost all my bookmarks and where I was in the stories...

No? Extension doesn't keep track of your read/bookmarks, it would be on the app side. If you don't have a backup that contains said data, and that data was removed/wiped from your current app data, then you're out of luck.
