### ISSUE TITLE
Covers

### ISSUE THREAD

**Issue by Ixarabxi** [keiyoushi/tachiyomi-extensions-source#4125]
### Source information

Comick-mangalife-freemangatop

### Source language

English

### Steps to reproduce

1- added the extension to the tachimanga app on ios all sources 2-add works to the favorites and the covers appear different from the original websites covers

### Expected behavior

The app should give the same cover to the works as the original websites

### Actual behavior

I get the wrong covers for a random works

### Mihon/Tachiyomi version

Tachimanga v3.2

### Android version

Ios 17.5

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [ ] I have written a short but informative title.
- [ ] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [ ] I have updated all installed extensions.
- [ ] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [ ] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
- your screenshots literally show same exact cover image....
- we also don't officially support tachimanga, check on mihon and if it happens there, make separate issues

**Comment by Ixarabxi** [comment]
Sorry i uploaded the same photo by mistake 
This is the problem
![IMG_8749](https://github.com/user-attachments/assets/a6bc3ddb-dcfe-4e68-a093-95051793dcac)
![IMG_8751](https://github.com/user-attachments/assets/7debb91d-7888-4ebb-a0cf-ea6396ff33b6)

**Comment by Smol-Ame** [comment]
Seems to be pulling the right cover image for that title on Mangalife (on my end). Check if your app has a way to refresh library covers in the app setting. Give another example of this issue, which manga & which extension?

**Comment by Ixarabxi** [comment]
Yes there is updated covers but still has the same problem
I have tried deleting and downloading - different sources all of them the same problem
Is there is app compatible with the extension in the app store? Ios

![IMG_8752](https://github.com/user-attachments/assets/1a734481-3a45-4d5c-936c-cc580dad1731)
![IMG_8753](https://github.com/user-attachments/assets/2abeafae-9954-4c7d-b0e3-51f25e7ddf80)
