### ISSUE TITLE
No extension to uninstall and update extension issue.

### ISSUE THREAD

**Issue by JomfruJager** [keiyoushi/tachiyomi-extensions-source#4129]
### Source information

MangaDex 1.4.193

### Source language

English

### Steps to reproduce

1. First i update my Tachiyomi to latest version, but i didn't know about uninstalling extension before that.
2. I updated my tachiyomi to 0.15.3 and my extensions disappeared from my library.
3. And now when im trying to download my extension (MangaDex), i see update not install option, even after uninstall Tachiyomi and clear all data 10 times 

### Expected behavior

After uninstall Tachiyomi, i can install all previous extension from my previous Tachiyomi app.

### Actual behavior

My Tachiyomi app remember after clear all data and uninstall what extension i had and i cant to install any previos extension on my phone, only the new one i didn't use before.

### Mihon/Tachiyomi version

Tachiyomi 0.15.3 and Mihon 0.16.5

### Android version

Android 12

### Other details

I updated my Tachiyomi app before uninstall all extensions and now i have big problem, i don't see any of my extension i can't install any of my previous extension, because i see only update not install option. On extensions i didn't use i see install and this extensions work fine but my old one don't want to install themselves, even after uninstall Tachiyomi more then 10 times, clear all data every time. And the best is this that, i have this problem on Mihon app even but i did never use Mihon before. :C
![Screenshot_20240720-112126_Mihon](https://github.com/user-attachments/assets/b9e153fc-57d4-4caf-8e9d-a6f069ca304d)
![Screenshot_20240720-112132_Mihon](https://github.com/user-attachments/assets/f69618d3-3512-4440-9bc9-de39b65753d5)
![Screenshot_20240720-114013_Tachiyomi](https://github.com/user-attachments/assets/c59b47d7-3939-4fae-8c1e-cb68efe4ceda)
![Screenshot_Mihon_Bato to](https://github.com/user-attachments/assets/75c38255-c730-4d4c-9d7c-c8ecf47757ff)
![Screenshot_Mihon_MangaDex](https://github.com/user-attachments/assets/8fbbbbef-c36c-4a70-8921-c1506a4bf4f2)
![Screenshot_Tachiyomi_Bato to](https://github.com/user-attachments/assets/f7753ebc-0f26-419d-9ccb-339a6eb6e2c1)
![Screenshot_Tachiyomi_MangaDex](https://github.com/user-attachments/assets/04796790-66cf-4f2d-ad8f-f949c5a2de01)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Extensions are installed on-device as apps, they aren't stored in Tachiyomi app data so clearing the app data doesn't nothing.

Join the Keiyoushi Discord server and ask for help in the repo-support channel, this will make it easier to help figure this issue out for you.

**Comment by AwkwardPeak7** [comment]
Move to [Mihon](https://mihon.app/) as tachi is dead, come to our discord for further help.

**Comment by JomfruJager** [comment]
I SEE NOW 
I WUV YOU!!! Smol-Ame for  explanation how extensions work and i joined discord earlier so thanks for invite and im going to use Mihon now, THX for your work guys.
See Ya on discord 
Bye-Bye 

> Extensions are installed on-device as apps, they aren't stored in Tachiyomi app data so clearing the app data doesn't nothing.
> 
> Join the Keiyoushi Discord server and ask for help in the repo-support channel, this will make it easier to help figure this issue out for you.
