### ISSUE TITLE
No results found 

### ISSUE THREAD

**Issue by El-Nice** [keiyoushi/tachiyomi-extensions-source#4140]
### Source information

Rocks Manga 1.4.36

### Source language

Arabic

### Steps to reproduce

When i search any manga i shows me no results found or when i open the source it shows me no results found 

### Expected behavior

Should show results 

### Actual behavior

Does not show up any mangas but when i use the webview it works good

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #4117 that you opened yesterday

**Comment by El-Nice** [comment]
> Duplicate of #4117 that you opened yesterday

thanks I forgot that I opened it
