### ISSUE TITLE
JManga -> 漫画 raw: update domain

### ISSUE THREAD

**Issue by mrtear** [keiyoushi/tachiyomi-extensions-source#4145]
### Source information

JManga 1.4.7

### Source language

Japanese

### Source new URL

https://mangaraw.onl/home1

### Other details

Url (home page) Changed Again (added /home1)
[JManga](https://jmanga.vip) -> [漫画 raw](https://mangaraw.onl/home1)

- Theme changed
- Browse with filters
- Entries comes with alternative titles
- description in JA & En (not every)
- Not dedicated search page (dropdown search)

![image](https://github.com/user-attachments/assets/619a7881-9f92-493e-b696-28c312f0eb7b)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Duplicate of #3397
