### ISSUE TITLE
Hizo Manga

### ISSUE THREAD

**Issue by Kinupsy-co** [keiyoushi/tachiyomi-extensions-source#4146]
### Source name

Hizo Manga 1.4.3

### Source link

https://hizomanga.net/

### Source language

Arabic

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
This website only have novels, Mihon/Tachiyomi doesn't support novels
