### ISSUE TITLE
mgkomik

### ISSUE THREAD

**Issue by mozzaru** [keiyoushi/tachiyomi-extensions-source#4147]
### Source information

mgkomik 1.4.50

### Source language

Id

### Steps to reproduce

Error 521 and there is no list of the latest comic updates

### Expected behavior

.

### Actual behavior

.

### Mihon/Tachiyomi version

yokai last

### Android version

Android 11

### Other details

![Screenshot_2024-07-21-19-46-49-50_21015a41200050f19d2d2db913bd7dc1](https://github.com/user-attachments/assets/fb2f8445-293f-49a3-83db-933faa032a3b)
![Screenshot_2024-07-21-19-46-53-21_21015a41200050f19d2d2db913bd7dc1](https://github.com/user-attachments/assets/f7b31106-9ce9-40bc-8b8a-ccf1bc3340c1)
![Screenshot_2024-07-21-19-46-45-33_21015a41200050f19d2d2db913bd7dc1](https://github.com/user-attachments/assets/639fc0f8-46db-41be-a160-e80241bde0ec)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Works fine on my end

HTTP 5## errors are usually site/server issues from the source, especially since their website looks broken in your screenshot, not an extension issue. You can check the source in your own browser when these things happen to confirm if it's a source-related issue.
