### ISSUE TITLE
[JA] Add MangaRaw.ac | 漫画 raw

### ISSUE THREAD

**Issue by mrtear** [keiyoushi/tachiyomi-extensions-source#4148]
### Source name

MangaRaw.ac

### Source link

https://mangaraw.ac/

### Source language

Japanese

### Other details

18+/NSFW = YES
Site provides Alterntive Title, Genre/Tag, Descrption only
![image](https://github.com/user-attachments/assets/879cc456-500f-4052-ad84-ae4fc0870799)

P.S., Dont ignore this if you think its same cuz of its name. Site has latest chapters for diff entries.

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Site appears to be broken. Closing.
