### ISSUE TITLE
Site was changed and isn't working properly anymore, cant open the mangas and can't download too

### ISSUE THREAD

**Issue by briantgosling** [keiyoushi/tachiyomi-extensions-source#4155]
### Source name

999hentai

### Source language

Multi/English

### Source link

https://animeh.to/

### Other details

N/A

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #4151 

Search the existing issues before opening a new one, and acknowledging that you did
