### ISSUE TITLE
AnimeSama default source -> colorless

### ISSUE THREAD

**Issue by pekatour** [keiyoushi/tachiyomi-extensions-source#4156]
### Source name

AnimeSama

### Source language

French

### Describe your suggested feature

It seems that by default AnimeSama selects the color version of the manga (I only check One Piece). Thus it is not necessarily the most up to date version of the manga.
Would it be possible to take the colorless version instead?

### Other details

No

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by pekatour** [comment]
@CriosChan I hate to ping people like this, but I think this should be an easy fix ? I checked the code, I don't know Kotlin but I think I have identified the place : 
https://github.com/keiyoushi/extensions-source/blob/eb1b3ebdd51135b5cb8516144d12a110ba148161/src/fr/animesama/src/eu/kanade/tachiyomi/extension/fr/animesama/AnimeSama.kt#L103

One Piece has a different URL for the "black and white" version, hardocing the url like that gives the colored version

**Comment by CriosChan** [comment]
It wasn't easy, but it should work in this version, so you can choose which version (color or not) you want to read.

**Comment by CriosChan** [comment]
The final version will be different. There won't be two mangas, but just one, with both chapters present. You can, however, make the color version disappear if you don't want it by going to the filters at top right and in "Scanlator" you can choose to exclude the color version.
![anime_sama_select_version](https://github.com/user-attachments/assets/77eb5fda-112f-431e-b994-dea22acb4e1a)

**Comment by pekatour** [comment]
TYSM for your efforts!
