### ISSUE TITLE
Asura scan

### ISSUE THREAD

**Issue by MoeHKhant** [keiyoushi/tachiyomi-extensions-source#4160]
### Source information

Asura Scans 1.4.58

### Source language

Multi

### Source new URL

https://asura-scan.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
They are currently down and on lock down until things are stable, no changes should be made until they are stable. This might very well be a fake site you have given us considering the circumstances.
