### ISSUE TITLE
Asura Scans site rewritten

### ISSUE THREAD

**Issue by KevinSilvester** [keiyoushi/tachiyomi-extensions-source#4167]
### Source information

Asura Scans 1.4.34

### Source language

English

### Steps to reproduce

**Scenario 1**
1. Navigate to the "Sources" page in the "Browse" tab.
2. Select "Asura Scans"
3. Complete the CloudFlare captcha in WebView
4. Exit WebView
5. Click the "Refresh" button

OR

**Scenario 2**
1. Open any manhwa saved in the library from "Asura Scans"
2. Complete the CloudFlare captcha in WebView
3. Exit WebView
4. Attempt to refresh manhwa for new chapters

### Expected behavior

**Scenario 1**
List of all manhwa to be shown with titles and cover images

**Scenario 2**
Number of chapters to update if there are new chapters else nothing changes

### Actual behavior

**Scenario 1**
A blank screen with "No results found" is shown

**Scenario 2**
Displays the loading spinner for a long time then shows a toast notification saying "Unknown error"

### Mihon/Tachiyomi version

Mihon v1.16.5 | TachiJ2K 1.7.4

### Android version

Android 13

### Other details

The Asura Scans site seems to have gotten a complete rewrite using Next.js and Tailwindcss.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Dizzylead** [comment]
Have same problem. Was able to replicate across apps + repos

**Comment by tsunaproxD** [comment]
Yeah, asura is dead for me... All my reads are in asura T.T

**Comment by KevinSilvester** [comment]
The new site seems to be slower as well.
Refreshing for new chapters will take 20+ seconds per manhwa.

**Comment by crest1993** [comment]
+1 seems like they move the server
![Screenshot_20240723-104627](https://github.com/user-attachments/assets/f537af43-47ad-4c49-80c6-a7a4b962b77c)
