### ISSUE TITLE
readcomiconline switched to .li and the one inextension is .li

### ISSUE THREAD

**Issue by 3asba-3asba** [keiyoushi/tachiyomi-extensions-source#4170]
### Source information

readcomiconline 1.4.26

### Source language

english

### Source new URL

https://readcomiconline.li/

### Other details

current readcomic.ru gives out a 400 error when loading chapters cuz its the wrong link

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
ReadComicsOnine.ru is a different extension (1.4.11) than ReadComicOnline (1.4.26), which uses the .li link already.

RCO.ru is working fine, meanwhile RCO is broken because RCO is actively breaking our extensions, wait for a fix if you use RCO 1.4.26, otherwise migrate to a different source.
