### ISSUE TITLE
NHATTRUYEN URL change (Nhattruyenup.com -> Nhattruyenvn.com)

### ISSUE THREAD

**Issue by Nyarunaa** [keiyoushi/tachiyomi-extensions-source#4173]
### Source information

Nhattruyen 1.4.23

### Source language

Vietnamese - Tiếng Việt

### Source new URL

https://nhattruyenvn.com/

### Other details

Nhattruyen URL change and this it not duplicate or something like that, this is new one, pls fix it.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Nyarunaa** [comment]
This is not a duplicate because the previous article was by nettruyen, not by nhattruyen

**Comment by Norsze** [comment]
nhattruyen is also listed in that request

**Comment by Norsze** [comment]
The bot wouldn't react if the exact URL wasn't already present in a request or existing extension
