### ISSUE TITLE
Json and Cloudflare problem

### ISSUE THREAD

**Issue by Lofikoi** [keiyoushi/tachiyomi-extensions-source#4174]
### Source information

999Hentai

### Source language

English

### Steps to reproduce

When trying to search or read on the source it doesn't work, not even work or don't show the cover.
I can't read or download on the source anymore.

### Expected behavior

The source should be able to dl and read.
But do none.

### Actual behavior

Nothing work on the source.

### Mihon/Tachiyomi version

Latest.

### Android version

Android 14 latest

### Other details

Just wanted to say thank you and have a great day.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Duplicate of #4151
