### ISSUE TITLE
[Koharu] how to refresh all titles when settings changed

### ISSUE THREAD

**Issue by papaj-na-wrotkach** [keiyoushi/tachiyomi-extensions-source#4176]
### Source information

Koharu 1.4.3

### Source language

English

### Steps to reproduce

1. have some books in library from Koharu
2. switch "Remove additional information in title" option from Koharu/English settings page 
3. refresh any book (swiping from top or from three dots menu)

### Expected behavior

Title should change to reflect new setting.

### Actual behavior

Title remains unchanged.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Other details

The option description says
> Remove anything in brackets from manga titles.
Reload manga to apply changes to loaded manga.

I assume that "reload" means refresh as in go to the book view and refresh by swiping from top. I can't find another option allowing to refresh metadata.

Clearing cache doesn't help.

Please tell me what am I doing wrong and what do you mean by "reload manga".

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
For things in your library => remove from library, refresh, add back to library 
For everything else => clear database in advanced settings 


This is kind of an app bug/feature so yeah

**Comment by papaj-na-wrotkach** [comment]
Thanks, I might open an issue on the app repo.
