### ISSUE TITLE
Update url for Fmovies

### ISSUE THREAD

**Issue by Suvam2002** [keiyoushi/tachiyomi-extensions-source#4179]
### Source information

Fmovies 14.25

### Source language

English 

### Source new URL

https://www.fmovies.do/

### Other details

Site url got updated. Please change it in the repo. 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
We don't provide anime extensions
