### ISSUE TITLE
Requesting extension for Netmovies

### ISSUE THREAD

**Issue by Suvam2002** [keiyoushi/tachiyomi-extensions-source#4180]
### Source name

Netmovies

### Source link

https://web.netmovies.to/

### Source language

English 

### Other details

Excellent source for movies/ tv shows/ anime.
Please add.

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
We don't provide anime extensions
