### ISSUE TITLE
The Asura Scans Site is the wrong URL

### ISSUE THREAD

**Issue by RaydenXVII** [keiyoushi/tachiyomi-extensions-source#4185]
### Source information

Asura Scans 1.4.34

### Source language

English

### Source new URL

https://asuratoon.com/

### Other details

the official Asura Scans site is (https://asuratoon.com/) not https://asuracomic.net/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #4167 

Search the existing issues before opening a new one, and acknowledging that you did when you didn't at all.
