### ISSUE TITLE
Asura scans no pages found

### ISSUE THREAD

**Issue by UnknownBeing1** [keiyoushi/tachiyomi-extensions-source#4186]
### Source information

Asura scans 1.4.34

### Source language

English

### Steps to reproduce

Choose any entry from asura scans source then click any chapter it gives no pages found or if you try to search also says nothing found 

### Expected behavior

When clicked on a chapter it should simply load the chapter and when you search it should show results 

### Actual behavior

 And when clicked on a chapter it says no pages found and when searched it says nothing found

### Mihon/Tachiyomi version

Yokai  1.8.4.3 and tachiyomi Sy 1.10.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of https://github.com/keiyoushi/extensions-source/issues/4167

Search the existing issues before opening a new one, and acknowledging that you did when you didn't at all.
