### ISSUE TITLE
Asura Scans changed it's source link

### ISSUE THREAD

**Issue by GustavoCastilhoLucena** [keiyoushi/tachiyomi-extensions-source#4187]
### Source name

Asura Scans

### Source link

https://asuracomic.net/

### Source language

English

### Other details

the source link changed from "asuratoon.com" to "asuracomic.net"

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of https://github.com/keiyoushi/extensions-source/issues/4167

Search the existing issues before opening a new one, and acknowledging that you did when you didn't at all.

**Comment by GustavoCastilhoLucena** [comment]
I thought that the bug was  a different one, sry

**Comment by Norsze** [comment]
@GustavoCastilhoLucena  It all stems from the site being new, the URL is still the same, they use both

**Comment by GustavoCastilhoLucena** [comment]
Oh Ok
