### ISSUE TITLE
Asura Scans showing Nothing

### ISSUE THREAD

**Issue by XY0511** [keiyoushi/tachiyomi-extensions-source#4188]
### Source information

Asura Scans 1.4.34

### Source language

English

### Steps to reproduce

1. Go to Extension list
2. Select Asura Scans
3. Wait to Load

### Expected behavior

1. Go to Extension list
2. Select Asura Scans
3. Wait to Load
4. Content Shows

### Actual behavior

1. Go to Extension list
2. Select Asura Scans
3. Wait to Load
4. Nothing Shows

### Mihon/Tachiyomi version

App version: 0.16.5  

### Android version

Android 13

### Other details

![Screenshot_20240724-012211](https://github.com/user-attachments/assets/c5ce0058-3324-4f1c-a212-1078b5004b76)
![Screenshot_20240724-012214](https://github.com/user-attachments/assets/4dcb3b13-54ae-433e-8f39-383a8c9b7654)
![Screenshot_20240724-012219](https://github.com/user-attachments/assets/6517d0a4-7c66-4122-a6ed-a933967a8b68)
![Screenshot_20240724-012223](https://github.com/user-attachments/assets/ae151691-ec23-499d-b47f-bd85408bec94)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
duplicate of #4167

**Comment by Smol-Ame** [comment]
Duplicate of https://github.com/keiyoushi/extensions-source/issues/4167, it's literally pinned on the issues page.

Search the existing issues before opening a new one, and acknowledging that you did when you didn't at all.
