### ISSUE TITLE
Lua Scans URL change

### ISSUE THREAD

**Issue by Gerardalbert21** [keiyoushi/tachiyomi-extensions-source#4190]
### Source information

Lua Scans 1.4.34

### Source language

English 

### Source new URL

https://luacomic.net/

### Other details

Last one was [Luacomic.com ](https://luacomic.com/) and it still works, but it was stolen, and now they have https://luacomic.net/ as their only domain

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Just curious & for more info, any screenshots like Discord announcements about this "stolen" page since the old luascans link redirects to the current URL?

**Comment by Gerardalbert21** [comment]
![image](https://github.com/user-attachments/assets/c995d751-5d37-4da7-9bc6-4554bf9d3564)
