### ISSUE TITLE
Asura Scans : No results or pages found

### ISSUE THREAD

**Issue by ariiiq** [keiyoushi/tachiyomi-extensions-source#4191]
### Source information

en.asurascans 1.4.34

### Source language

English

### Steps to reproduce

1. Open up browse and open asura scans sources
2. Back to library to read any mangas

### Expected behavior

There should be any manhwas or manhuas on the asura scans sources, and pages on any added manhwa or manhuas

### Actual behavior

(No manhwas or manhuas on tachi/mihon's search)
![image](https://github.com/user-attachments/assets/321dc366-8dbc-404e-8130-e6b2d5841507)

(No pages found on any added manhwas or manhuas)
![image](https://github.com/user-attachments/assets/83aebda0-8bc7-493f-bb70-c82cd5015d31)

### Mihon/Tachiyomi version

Mihon Stable 0.16.5

### Android version

Android 14

### Other details

Cannot download any manhwas or manhuas, and sometimes getting NullPointerException: null while refreshing any added comics to get updates or updating the cover's profile. Webview works properly but last few days it might just be asura scans doing maintenance to their websites

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of https://github.com/keiyoushi/extensions-source/issues/4167, it's literally pinned on the issues page.

Search the existing issues before opening a new one, and acknowledging that you did when you didn't at all.
