### ISSUE TITLE
Asura Scans null pointer exception

### ISSUE THREAD

**Issue by masdabazz** [keiyoushi/tachiyomi-extensions-source#4194]
### Source information

Asura Scans 1.4.34

### Source language

English

### Steps to reproduce

Update any manga/manwha from asura scans.

### Expected behavior

Update manga/manwha with new chapters or not do anything if there is nothing new.

### Actual behavior

Comes up with error:
Null pointer exception null

### Mihon/Tachiyomi version

0.16.5

### Android version

Andriod 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of https://github.com/keiyoushi/extensions-source/issues/4167, it's literally pinned on the issues page.

Search the existing issues before opening a new one, and acknowledging that you did when you didn't at all.

**Comment by masdabazz** [comment]
It says that they moved the servers and the issue was closed, so I assumed that done.

**Comment by masdabazz** [comment]
My bad, are they still working on it?

**Comment by Smol-Ame** [comment]
> My bad, are they still working on it?

Asura might be finished/stabilized with their website changes, but the extension has yet to be updated to work with the new changes. Wait for a fix or migrate to a different source

**Comment by masdabazz** [comment]
When the fix happens do I have to download the extensions from the keiyoushi website again, or will it update automatically in mihon?

**Comment by Smol-Ame** [comment]
> When the fix happens do I have to download the extensions from the keiyoushi website again, or will it update automatically in mihon?

If you're using our repo/extension, it'll show up in the Extensions tab as an update available for the extension.

**Comment by masdabazz** [comment]
ok thank you for all your help

**Comment by Smol-Ame** [comment]
> ok thank you for all your help

Sorry for the extra reply, ideally you should have added our repo link into your application to receive updates for your extensions. Go to the website again & click on the button to add into your app. It should automatically redirect & add the repo link in. Otherwise, if you don't have the repo in your app, you will have to manually download it off our site when there's a new update.

**Comment by masdabazz** [comment]
is the link https://https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json?

**Comment by Smol-Ame** [comment]
> is the link https://https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json?

Yep, you should have that link in your app's Extension repos page. Please come to Keiyoushi Discord repo-support channel if you need more help/have any other questions.

**Comment by masdabazz** [comment]
ok. again thank you for all your help. you explained everything amazingly

**Comment by Norsze** [comment]
One too many https:// but yes
