### ISSUE TITLE
crunchyroll

### ISSUE THREAD

**Issue by paz-web** [keiyoushi/tachiyomi-extensions-source#4195]
### Source name

crunchyroll

### Source link

https://www.crunchyroll.com/pt-br/

### Source language

Todos 

### Other details

Fiz essa sugestão para saber se e possível deixar igual a da scan BR lura toon

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
We don't do anime extensions.
