### ISSUE TITLE
Asura Scans extension not working

### ISSUE THREAD

**Issue by rickyjara96** [keiyoushi/tachiyomi-extensions-source#4196]
### Source information

Asura Scans 1.4.34

### Source language

English 

### Steps to reproduce

Nothing appears on the asura scans extension. When trying to open a chapter I get null pointer error

### Expected behavior

There should be manwhuas to read none show up

### Actual behavior

Can't seem to find anything when opening asura scans extension

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of https://github.com/keiyoushi/extensions-source/issues/4167, it's literally pinned on the issues page.

Search the existing issues before opening a new one, and acknowledging that you did when you didn't at all.

**Comment by rickyjara96** [comment]
Sorry couldn't find that one
