### ISSUE TITLE
Fix Asura scans extension for new website

### ISSUE THREAD

**Issue by ThatGothJohn** [keiyoushi/tachiyomi-extensions-source#4197]
### Source information

Asura Scans 1.4.34

### Source language

English 

### Source new URL

https://asuracomic.net/

### Other details

The sight URL hasn't changed, however they've updated their website and the scraping no longer works, showing a "no results found" when attempting to access the source via Mohon, downloading chapters for series already in the library returns "no pages found"
Accessing the site via webview and in a browser work fine.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of https://github.com/keiyoushi/extensions-source/issues/4167, it's literally pinned on the issues page.

Search the existing issues before opening a new one, and acknowledging that you did when you didn't at all.
