### ISSUE TITLE
Null pointer exception when refreshing

### ISSUE THREAD

**Issue by D3vilmack** [keiyoushi/tachiyomi-extensions-source#4199]
### Source information

Asura Scans 1.4.34

### Source language

English

### Steps to reproduce

When i try to refresh a manga, it says NullPointerException: null
![Uploading Screenshot_20240724_013001_Mihon.jpg…]()

### Expected behavior

Refresh of the saved manga

### Actual behavior

No refresh, with a message NullPointerException: Null

### Mihon/Tachiyomi version

16.5

### Android version

Android 13

### Other details

Asura extension not workin, when i press the webview it  works but in the app doesn't. 
![Screenshot_20240724_020903_Mihon](https://github.com/user-attachments/assets/d648135e-fb12-4bf2-a610-4b4eb9772ec4)
![Screenshot_20240724_020911_Mihon](https://github.com/user-attachments/assets/b2a80389-2642-46aa-9686-12de58228520)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of https://github.com/keiyoushi/extensions-source/issues/4167, it's literally pinned on the issues page.

Search the existing issues before opening a new one, and acknowledging that you did when you didn't at all.

**Comment by D3vilmack** [comment]
Sorry dont really know how to use github
