### ISSUE TITLE
erro "JSON"

### ISSUE THREAD

**Issue by Xavierbrazil** [keiyoushi/tachiyomi-extensions-source#4202]
### Source information

Não sei como explicar mas, esse erro "JSON" me impede de abrir uma obra 

### Source language

Português brasileiro PT-BR

### Steps to reproduce

1. Eu abro a extensão slimeRead
2. Tento abrir a obra 
3. A capítulo não carrega e a mensagem de errao segue
![Screenshot_2024-07-23-23-06-29-836_app mihon debug](https://github.com/user-attachments/assets/036852b9-41cb-4b6a-8d16-7d497e920a69)

### Expected behavior

Apenas não posso ler capitulo algum dessa obra, oque é diferente para outras do mesmo site

### Actual behavior

Oque deveria acontecer é que eu poderia ler normalmente eu acho 

### Mihon/Tachiyomi version

0.16.5

### Android version

 Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
Vc tá tentando ler novel, não tem suporte. A fonte disponibiliza algumas novels como imagem, então essas são abertas pelo app, mas não há suporte pra novels.

Novels are not supported
