### ISSUE TITLE
Asura Scans site rewritten 

### ISSUE THREAD

**Issue by Wasimakram1923** [keiyoushi/tachiyomi-extensions-source#4204]
### Source information

Asura Scans 1.4.34

### Source language

English 

### Source new URL

https://asuracomic.net/

### Other details

Asura Scan site was rewritten and now it's now accessible from extension repo
![Screenshot_2024-07-24-12-00-58-95_afd66b7916d19a60815f56273408b73e](https://github.com/user-attachments/assets/a1605a9e-15ed-4866-98be-4e3e79e4633b)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of https://github.com/keiyoushi/extensions-source/issues/4167, it's literally pinned on the issues page.

Search the existing issues before opening a new one, and acknowledging that you did when you didn't at all.
