### ISSUE TITLE
Asura scans not working 

### ISSUE THREAD

**Issue by Gojodatebayo** [keiyoushi/tachiyomi-extensions-source#4205]
### Source information

Asura Scans 1.4.34

### Source language

English 

### Steps to reproduce

1. Open extension 
2. Shows no results even though it works on webview 
![IMG_20240724_120509](https://github.com/user-attachments/assets/aff3ab06-036f-47f4-a3c4-811648048725)

### Expected behavior

It should show the mangad it has 

### Actual behavior

Showa no results and doesn't update mangas

### Mihon/Tachiyomi version

Mihon App version: 0.16.5 (standard, 2a01a2a, 6, 2024-04-09T09:58:14Z) Android version: 14 

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of https://github.com/keiyoushi/extensions-source/issues/4167, it's literally pinned on the issues page.

Search the existing issues before opening a new one, and acknowledging that you did when you didn't at all.
