### ISSUE TITLE
Asura Scans

### ISSUE THREAD

**Issue by Wasimakram1923** [keiyoushi/tachiyomi-extensions-source#4208]
### Source name

Asura Scans 1.4.34

### Source link

https://asuracomic.net/

### Source language

English 

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
What is your problem? Stop opening duplicate issues over and over.

**Comment by Wasimakram1923** [comment]
The solution to the problem given in previous issues not working can you provide a different solution as Asura scans updated their site

**Comment by Norsze** [comment]
There are no solutions given yet, issues don't provide solutions, now stop opening new issues when you have no clue what you are talking about
