### ISSUE TITLE
Sites that change base url frequently 

### ISSUE THREAD

**Issue by Daviid-P** [keiyoushi/tachiyomi-extensions-source#4209]
### Source name

Asura

### Source language

English

### Describe your suggested feature

baseUrl should be saved or allowed to be overwritten from extension settings.

### Other details

Many sites get taken down and pop-up later just changing the TLD or the whole domain altogether.

If we could easily update the domain in the extension's settings we would not need to release an update just to update the domain.

Example:
asuratoon.com
asuracomic.net
asura.gg
asura.nacm.xyz
asurascans.com

Many other sites have this problem due to DMCA and will continue.

Maybe it should be a general setting for all extensions, and when the extension initializes it requests a json from the extension's repo with the current domains. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
This is not something we want to encourage unless absolutely necessary. And most times a domain option won't fix issues either way, as in this example you have here

**Comment by Daviid-P** [comment]
Sure, currently the whole site has changed and it's not a simple domain change but most of the times, it is. And it happens a lot with multiple extensions.

**Comment by Norsze** [comment]
More options just lead to more likely ways the extension can malfunction or for user error to occur. Unless necessary, cause they switch every week, it is discouraged.

People have already opened dozens of the same issues without reading the pinned stuff, they are not much smarter when stuff is hidden in an extension.

I see your comment below and it's an instant more user error warning, even if you don't see it,  I see it. I hang out in support enough to know this is a bad idea.

**Comment by Daviid-P** [comment]
In my opinion this configuration should be optional, there's the baseUrl configured as usual and then an interceptor that checks if there's any user defined one.

Regular users don't need to change anything and wouldn't notice the change, experienced users that don't want to wait for an extension update can manually change the domain.

Then next extension update the user defined domain gets deleted because it's assumed the update fixed the domain.
