### ISSUE TITLE
Asura scans not working 

### ISSUE THREAD

**Issue by AryanMithbawkar** [keiyoushi/tachiyomi-extensions-source#4210]
### Source information

Asura scans

### Source language

English

### Steps to reproduce

1. Open the extension in tachiyomi

### Expected behavior

Work normally

### Actual behavior

Shows no result found but works in webview and not updating manhus 

### Mihon/Tachiyomi version

1.4.34

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Duplicate of #4167

**Comment by Norsze** [comment]
Duplicate of #4167
