### ISSUE TITLE
Reaper-Scans (Unoriginal)

### ISSUE THREAD

**Issue by EluZet** [keiyoushi/tachiyomi-extensions-source#4212]
### Source name

Reaper-Scans

### Source link

https://reaper-scans.com/

### Source language

English

### Other details

This is NOT a duplicate.
https://reaper-scans.com/ has different manwhas than https://reaperscans.com/
(see [Descent of the Demon Master](https://reaper-scans.com/manga/descent-of-the-demon-master/) and others.)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Edit title to "Reaper-Scans (Unoriginal)"
