### ISSUE TITLE
Aaurascans not working

### ISSUE THREAD

**Issue by Mister382** [keiyoushi/tachiyomi-extensions-source#4216]
### Source information

Website working but shows null in mihon

### Source language

English

### Steps to reproduce

After opening the asurascans extension in mihon it is showing no results found
But when i open it in view in webpage,webpage is loading without any problem

### Expected behavior

Manhwas should open when extension is opened

### Actual behavior

Error showing no results are found 

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Duplicate of #4167
