### ISSUE TITLE
TempleScan: change theme

### ISSUE THREAD

**Issue by SamSensei** [keiyoushi/tachiyomi-extensions-source#4217]
### Source information

templescans v1.4.41

### Source language

English 

### Steps to reproduce

1. add any comic to library from this source.
2. Wait for new chapter to be added on source
3. Open added comic tile in library 
4. Manually refresh chapter list
5. Latest chapter should be added in the list of chapters

### Expected behavior

On manually updating chapter list of existing comic in library from this source, new chapter should be added in the list of chapters.

### Actual behavior

Chapter list remains same as old instead of adding new chapter to the list as show in webview

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Other details

Comic URL is same and on opening source in mihon it shows comic already added in Library 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by SamSensei** [comment]
Bus still exists after extension updated to v1.4.42

**Comment by AwkwardPeak7** [comment]
paid chapters get filtered out, if you want them disable the filtering in extension setting

**Comment by SamSensei** [comment]
Updated extension setting to display paid chapters, still list not updated to latest chapters.
Able to read chapter in webview but chapter not showing in library

**Comment by AwkwardPeak7** [comment]
make sure to restart the app, for further help come to our discord

**Comment by SamSensei** [comment]
Now On manual refreshing it shows http 404 error, but web view is working fine. No change in URL.

**Comment by noctaia** [comment]
Same here.
HTTP error 404 with or without displaying the paid chapters
