### ISSUE TITLE
Asura Scans No Result Found

### ISSUE THREAD

**Issue by nah595** [keiyoushi/tachiyomi-extensions-source#4219]
### Source information

Asura Scans 1.4.34

### Source language

English

### Steps to reproduce

1. Press latest on asura scans
2. Should get a result but i get no result
3. Webview works fine
4. Sorry for my bad english

### Expected behavior

Should get result about the latest update and asura scans library

### Actual behavior

I get no result

### Mihon/Tachiyomi version

Tachiyomi 0.15.3 & Mihon 0.16.5

### Android version

Android 11

### Other details

Both Tachiyomi and Mihon get the same result when i try to use asura scans. No result found

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of https://github.com/keiyoushi/extensions-source/issues/4167, it's literally pinned on the issues page.

Search the existing issues before opening a new one, and acknowledging that you did when you didn't at all.
