### ISSUE TITLE
Tsuki manga não abre

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#4222]
### Source information

Tsuki mangás 1.4.5

### Source language

Português (Brasil)

### Steps to reproduce

Não está abrindo a extensão no aplicativo é nem no webview

https://github.com/user-attachments/assets/60807f94-f753-4370-8e55-115bb6ba4de7

### Expected behavior

Funcionar direito 

### Actual behavior

Não abre nem no aplicativo nem no webview

### Mihon/Tachiyomi version

Mihon 016.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MariaSan-tos** [comment]
É um problema com o CloudFlare.
Primeiro, tente abrir na WebView e fazer o captcha até o final, se a página carregar normalmente volte para o aplicativo e pronto.

Se o Captcha não funcionar, entre em "Configurações", vá em "Avançado", clique em " User Agent Padrão" e cole isso: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/126.0.2592.113` . Depois, volte para a extenção, faça o Captcha e pronto.

Esse é o User Agent que funcionou para mim contra o CloudFlare (o mais recente do Edge), se não funcionar ainda, você pode testar outras opções de User Agents clicando aqui: https://www.whatismybrowser.com/guides/the-latest-user-agent/

**Comment by choppeh** [comment]
cf

**Comment by ghost** [comment]
> É um problema com o CloudFlare. Primeiro, tente abrir na WebView e fazer o captcha até o final, se a página carregar normalmente volte para o aplicativo e pronto.
> 
> Se o Captcha não funcionar, entre em "Configurações", vá em "Avançado", clique em " User Agent Padrão" e cole isso: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/126.0.2592.113` . Depois, volte para a extenção, faça o Captcha e pronto.
> 
> Esse é o User Agent que funcionou para mim contra o CloudFlare (o mais recente do Edge), se não funcionar ainda, você pode testar outras opções de User Agents clicando aqui: https://www.whatismybrowser.com/guides/the-latest-user-agent/

O meu só funciona quando eu uso um aplicativo pra mudar o DNS do celular, senão fica dando erro é não carrega

**Comment by choppeh** [comment]
Issue can be closed. 
It's a Clouflare issue.

**Comment by Norsze** [comment]
?blurb cf
