### ISSUE TITLE
The source isn't working anymore "null" is what it says

### ISSUE THREAD

**Issue by 101Hippo** [keiyoushi/tachiyomi-extensions-source#4227]
### Source information

Asura scans 1.4.34

### Source language

English

### Steps to reproduce

1.open the source 2.search for Amy manga 3.read or download any manga you already have in the library (not downloaded)

### Expected behavior

1.should open normally and provide results for recent or top manga 2.should provide results of what you're searching for if it is there or say there's no result 3.should open or start downloading normally.

### Actual behavior

1.only opens to say "no results found" and this is what happens for the 2nd point as well,
3.gives a message saying "NullPointerException: null" with this same spacing between words.

### Mihon/Tachiyomi version

"0.16.5"

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of https://github.com/keiyoushi/extensions-source/issues/4167, it's literally pinned on the issues page.

Search the existing issues before opening a new one, and acknowledging that you did when you didn't at all.

**Comment by 101Hippo** [comment]
This is literally in trouble shooting and the method of bypassing firecloud doesn't work thus is why I opened the issue,well thank you anyway.
