### ISSUE TITLE
Genz Toons (Surya Scans) URL Change 

### ISSUE THREAD

**Issue by Gerardalbert21** [keiyoushi/tachiyomi-extensions-source#4228]
### Source information

Genz Toons 1.4.34

### Source language

English 

### Source new URL

Elarctoons.biz

### Other details

![image](https://github.com/user-attachments/assets/9a4bef6a-207f-48b6-a1ca-dc7e9900e7fb)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Current Surya site works & doesn't redirect to any of those sites. Elarc already exists as an extension within the repo. I believe you're just misinterpreting their announcement/message

**Comment by Gerardalbert21** [comment]
Their site don't seem to work anymore https://genztoons.com/ and when you go to their last URL https://suryatoon.com/ a message show the second site that we see on the discord post. So I guess there's a good chance this is their new site.

**Comment by Smol-Ame** [comment]
Works fine with GenZ link, ask for help in Keiyoushi Discord repo-support channel

![Screenshot_20240724_233344_Mihon.png](https://github.com/user-attachments/assets/60d94e55-b8ce-463d-82c0-02673e321cfc)
