### ISSUE TITLE
Http error 522 from Comick

### ISSUE THREAD

**Issue by RobindaCoast** [keiyoushi/tachiyomi-extensions-source#4229]
### Source information

Comick 1.4.46

### Source language

English

### Steps to reproduce

1. Open a chapter any comic from the Comick source

### Expected behavior

The comic should load and display

### Actual behavior

The comic never finishes loading, taking about 15 seconds before eventually timing out with the error code "HTTP error 522"

### Mihon/Tachiyomi version

Aniyomi 0.16.4.3

### Android version

Android 8.1.0

### Other details

What is notable is that the Comick website and chapters on it load perfectly well within Webview with no issues whatsoever.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
The site is currently running off a backup so api is broken at the moment
