### ISSUE TITLE
Asura Scans not working

### ISSUE THREAD

**Issue by qsurge** [keiyoushi/tachiyomi-extensions-source#4237]
### Source name

Asura Scans

### Source language

English

### Source link

https://asuracomic.net/

### Other details

Any and all existing mangas are throwing null pointer exception or something similar, it is not loading for any manga in asura scans
![1](https://github.com/user-attachments/assets/ed5f4643-a787-450a-9931-8762b3aeeb68)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Actually check existing issues

**Comment by qsurge** [comment]
i think it same and not the same issue.

**Comment by qsurge** [comment]
if you feel it is same, you can close it...

**Comment by Norsze** [comment]
It is the same issue, it is all related to their new website. So even if this was a different issue it is moot as they have a new website and any previous issues go out the window. Doesn't matter if there was mold in your old house if you tore it down and built a new one on top
