### ISSUE TITLE
Read history entries clear themselves for Asura Scans

### ISSUE THREAD

**Issue by Tektiv** [keiyoushi/tachiyomi-extensions-source#424]
### Source information

Asura Scans 1.4.58

### Source language

English

### Steps to reproduce

1. Get a manhwa from Asura Scans
2. Read a chapter

### Expected behavior

- The chapter is count as read
- An entry about it can be found on History tab
- The manhwa comes first in the library, when sorted by "Last read"

### Actual behavior

Not at first, but after a few days

- ✔️  The chapter is count as read 
- :x: An entry cannot be found on History tab 
- :x: The manhwa comes last in the library, when sorted by "Last read"

### Tachiyomi version

Mihon 0.16.1

### Android version

Android 14

### Other details

Had the issue for a few months  
Asked Mihon's support but I have been advised to ask here

At first thought about URLs changing for Asura Scans, but the setting "Permanent Manga URL" is already enabled

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
Asura changes chapter URLs often so app thinks that they are new chapters.
