### ISSUE TITLE
Https 404

### ISSUE THREAD

**Issue by Nier78204** [keiyoushi/tachiyomi-extensions-source#4240]
### Source information

Manga Tube 1.4.2

### Source language

German 

### Steps to reproduce

According to extensions, the page can be reached offline via the Web Viewer. 

### Expected behavior

The titles should update safely and download new chapters. 

### Actual behavior

Error 404 happens even though the page is accessible and nothing happens more 

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #4112
