### ISSUE TITLE
I got issues in slimeread extension.

### ISSUE THREAD

**Issue by lucasmths01** [keiyoushi/tachiyomi-extensions-source#4241]
### Source information

Slimeread 1.4.12

### Source language

Português-Brasil

### Steps to reproduce

1. Install Source

3. Try search or see the feed

4. Got error 418
![Screenshot_20240725_152838_TachiyomiSY](https://github.com/user-attachments/assets/89ee95eb-7048-4d0d-886d-f0123251398b)

5. If I try access in webview got error
![Screenshot_20240725_152842_TachiyomiSY](https://github.com/user-attachments/assets/5e359240-52d9-405e-9e59-1a04a17fb9c1)

6. If I try access in chrome access normally
![Screenshot_20240725_152851_Chrome](https://github.com/user-attachments/assets/9ab4da81-4ab1-4fd5-9c36-1813b6d7029c)

I try clean cache, change network, etc but don't have success

### Expected behavior

You should search/access the source normally

### Actual behavior

I got error 418

### Mihon/Tachiyomi version

1.10.5

### Android version

Android 14

### Other details

TachiyomiSY

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by EvaldoCeBr** [comment]
No results appear in the popular tab.

![Screenshot_2024-07-25-20-35-20-358_app mihon](https://github.com/user-attachments/assets/8970607f-99e9-4d98-aaec-5a18a66dc7ca)

**Comment by choppeh** [comment]
The issue can be closed. Extension is OK!
