### ISSUE TITLE
Mangá Ninja Webview erro

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#4243]
### Source information

Mangá Ninja 1.4.36

### Source language

Português (Brasil)

### Steps to reproduce

O Webview abre mas logo depois da um erro como mostra no vídeo abaixo

https://github.com/user-attachments/assets/c9869e06-11f5-479a-8faa-8ae992d5f7c2

### Expected behavior

Webview funcionando

### Actual behavior

Webview dando erro 

### Mihon/Tachiyomi version

Tachiyomi SY 1.10.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Can't really fix WebView/random redirects from the site

Are you having an issue with the extension itself?

**Comment by ghost** [comment]
> Can't really fix WebView/random redirects from the site
> 
> Are you having an issue with the extension itself?

A extensão não deu nenhum problema
