### ISSUE TITLE
Domain Change 

### ISSUE THREAD

**Issue by sofari23** [keiyoushi/tachiyomi-extensions-source#4248]
### Source information

Lua Scans 1.4.34

### Source language

English 

### Steps to reproduce

1. Open mihon or any fork you are using 
2. Select lua Scans and start browsing 
3. The extension loads manga but it's not luascans it's just a duplicate using the same name since luascans changed to luacomics

### Expected behavior

Expected behavior is being able to browse in the original lua Scans 

### Actual behavior

But what happens is since luascans changed to luacomics you can't access it through the extension, what you access is duplicate site posing as luascans 

### Mihon/Tachiyomi version

Mihon r6778

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #4190
