### ISSUE TITLE
Search in AsuraScans fails if title contains ' 

### ISSUE THREAD

**Issue by ehsan18t** [keiyoushi/tachiyomi-extensions-source#4249]
### Source information

AsuraScans

### Source language

English

### Steps to reproduce

1. Search or try migrate a entry with `'` in title. It will fail.
2. Try again after removing the either side of `'`. It will succeed.

### Fails
![Screenshot_2024-07-26-09-13-58-119_eu kanade tachiyomi sy](https://github.com/user-attachments/assets/b93ad550-1f60-439c-be3d-c02fd8e3d108)

### Succeed
![Screenshot_2024-07-26-09-14-06-388_eu kanade tachiyomi sy](https://github.com/user-attachments/assets/ec6d14dd-e951-4c07-9357-7a1ba562b217)

### Expected behavior

Should be able to succeed with `'` in title.

### Actual behavior

Fails if `title/search params` contains `'`.

### Mihon/Tachiyomi version

TachiyomiSY B561 (Mihon Preview r6761) 

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Works fine, might be the style of `'` your keyboard/keyboard language writes out

![Screenshot_20240725_202534_Chai](https://github.com/user-attachments/assets/73f29fd5-e353-4030-97f2-4d2f490e8431)

**Comment by AwkwardPeak7** [comment]
It's the difference between ' and ’... 
And the search uses their website's search, which have always been known to be wonky like this.

**Comment by ehsan18t** [comment]
Ah, my bad. Happend this when I was migrating. So I didn't check as I didn't type the title. Seems like they changed some of the title after moving site.
