### ISSUE TITLE
NullPointerExeption: null

### ISSUE THREAD

**Issue by Sjob-inc** [keiyoushi/tachiyomi-extensions-source#4253]
### Source information

https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json

### Source language

English

### Steps to reproduce

When I refresh it gives me the error code NullPointerExeption: null 

### Expected behavior

New chapters should appear 

### Actual behavior

![Screenshot_2024-07-25-11-48-11-739_app mihon](https://github.com/user-attachments/assets/a5270225-5398-4d70-85a2-49f7b37e6119)
![Screenshot_2024-07-25-11-48-07-171_com android chrome](https://github.com/user-attachments/assets/c2373b61-9b64-4176-b67b-a438a763f5e1)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Why did you put our repo link as the Source information?

If you are using our repo, this issue has been fixed with the latest extension update for Asura Scans (1.4.35).

Come to the Keiyoushi Discord repo-support channel if you have further issues.
