### ISSUE TITLE
Problems with Russian extensions

### ISSUE THREAD

**Issue by Mwnxnm** [keiyoushi/tachiyomi-extensions-source#4254]
### Source information

Unable to install Russian extensions in 0.16.5

### Source language

Russian 

### Steps to reproduce

When downloading Mihon and adding a repository, I want to download a Russian extension like "Mangalib", but when downloading the extension, I get the message "Unable to install, conflicts with another package".There is no problem with English extensions. I tried to remove all remnants of Tachiyomi and other readers, but nothing worked. What should I do in this situation?

### Expected behavior

There should be no problem downloading Russian extensions

### Actual behavior

Instead, I have problems downloading Russian extensions

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Come to the Keiyoushi Discord repo-support server for troubleshooting, makes it easier to communicate
