### ISSUE TITLE
Asura Scan(s) URL change

### ISSUE THREAD

**Issue by Shiro-sheep** [keiyoushi/tachiyomi-extensions-source#4257]
### Source information

Asura Scans 1.4.36

### Source language

English

### Source new URL

https://asura-scan.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
This is a fake site using the brand of a well recognized scanlator to market themselves

**Comment by Shiro-sheep** [comment]
Oh my bad ^^'

**Comment by AwkwardPeak7** [comment]
you can open a source request for this as a separate extension
