### ISSUE TITLE
Mangadex extension is missing 

### ISSUE THREAD

**Issue by michaelkenway** [keiyoushi/tachiyomi-extensions-source#4258]
### Source name

Mangadex

### Source link

https://mangadex.org/

### Source language

English

### Other details

I've just recently changed the repo into this, but I find out that the **Mangadex** extension is missing. This is not the case for _ThePbone's_ repo, so I wonder why.
![Screenshot_20240726_161903_TachiyomiSY](https://github.com/user-attachments/assets/af60965e-403a-41a0-9544-87bdb5f0f3aa)
![Screenshot_20240726_162103_TachiyomiSY](https://github.com/user-attachments/assets/7bb0e825-5db2-4ba5-b0fb-c5b418fb059d)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
Come to our discord for help
