### ISSUE TITLE
Nekopost open in browser wrong page

### ISSUE THREAD

**Issue by l2eused** [keiyoushi/tachiyomi-extensions-source#4261]
### Source information

Nekopost 1.4.11

### Source language

Thai

### Steps to reproduce

1. download and install extension
2. open any manga page
3. press "open in browser" button

### Expected behavior

should be open in nakopost manga page

### Actual behavior

it's open in api page instead

### Mihon/Tachiyomi version

10.0.5 SY Preview

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
The "open in browser" ain't supposed to be used for reading though, it is only supposed to be used for troubleshooting, bypassing cloudflare and getting the source to work in app

**Comment by l2eused** [comment]
Sorry, I might give wrong info cause misunderstood. I meaning the button "Webview" in manga info page that should be open that manga in frontend webview not api page webview. but if it unnecessary to fix (or it use for things that you say above) please tell me. I will close this issue.
