### ISSUE TITLE
Spy.fakku 1.4.3 not working 

### ISSUE THREAD

**Issue by Sundogg17** [keiyoushi/tachiyomi-extensions-source#4263]
### Source information

Spy.fakku 1.4.3

### Source language

English 

### Steps to reproduce

Open extension and or do normal search. Extension does not display any titles. Click on extension alone, open webview and works fine. 

### Expected behavior

To display titles via search, and open titles to read or save ro lib.

### Actual behavior

The extension does not display anything but a error. However webview still works fine.
![Screenshot_20240726_083055_TachiyomiJ2K](https://github.com/user-attachments/assets/7cbee14d-fbf8-4cb8-9678-09796fce35c6)

### Mihon/Tachiyomi version

Tachij2k 1.7.4

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KenjieDec** [comment]
Their website says that: `fakku.cc is currently under tmp management until the original staff can take it back`

**Comment by Sundogg17** [comment]
I'm sorry, bur what does that mean?

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by KenjieDec** [comment]
NVM, they seem to require an API key to access their API now.

**Comment by Sundogg17** [comment]
What does that mean? Lol

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AwkwardPeak7** [comment]
GitHub issues are for dev related things, you don't need to understand it

**Comment by Sundogg17** [comment]
Roger that.  Thank you. Hopefully goes back up

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
