### ISSUE TITLE
Read comics online

### ISSUE THREAD

**Issue by Sundogg17** [keiyoushi/tachiyomi-extensions-source#4264]
### Source information

Readcomiconline 1.4.26

### Source language

English

### Steps to reproduce

Open extension and or do normal search. Extension does display titles. However titles do not open, message "image cant he loaded displays".
Click on extension alone, open webview and works fine.

![Screenshot_20240726_083725_TachiyomiJ2K](https://github.com/user-attachments/assets/92ec64d5-6124-4f19-acdb-0f5079a3fe0b)
![Screenshot_20240726_083818_TachiyomiJ2K](https://github.com/user-attachments/assets/bee4a9ce-dccd-4cac-aaa6-238f4668966f)
 

### Expected behavior

To search tiles, display tiles, to read or save to library 

### Actual behavior

Shows titles, but does not let you read them

### Mihon/Tachiyomi version

Tachij2k 1.74 

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #4115 

RCO is actively breaking our extensions, wait for a fix (but expect it to break), but you might be better off migrating to a different/better source

**Comment by Sundogg17** [comment]
No way, this extension is awesome. I hope there is a fix.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
