### ISSUE TITLE
Mangahot

### ISSUE THREAD

**Issue by Sundogg17** [keiyoushi/tachiyomi-extensions-source#4265]
### Source information

Mangahot 1.4.1

### Source language

English 

### Steps to reproduce

Open extension and or do normal search. Extension does not display any titles. Click on extension alone, open webview and does not work.

### Expected behavior

Should display titles, read, save to library 

### Actual behavior

Does nit display or show results. Does not open webview

![Screenshot_20240726_085423_TachiyomiJ2K](https://github.com/user-attachments/assets/be2fa456-df2f-446e-8446-197bf084170d)
![Screenshot_20240726_085427_TachiyomiJ2K](https://github.com/user-attachments/assets/3fce76ab-a351-453e-a34f-874cb04d44be)

### Mihon/Tachiyomi version

Tachij2k 1.74 

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Looks like a dead site
