### ISSUE TITLE
Asura no chapters found

### ISSUE THREAD

**Issue by Xyndra** [keiyoushi/tachiyomi-extensions-source#4267]
### Source information

Asura Scans

### Source language

English 

### Steps to reproduce

Just open any manga

### Expected behavior

Show chapters

### Actual behavior

doesn't 

### Mihon/Tachiyomi version

0.16.4.3

### Android version

Android 14

### Other details

It had a 502 shortly before.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
They broke their site, open in WebView or your own browser & you'll see this. Not extension-related issue

**Comment by Norsze** [comment]
They broke their own site, visit it

**Comment by Xyndra** [comment]
I literally did and the chaps are there

**Comment by Norsze** [comment]
They just fixed it congrats

**Comment by Xyndra** [comment]
Yes but after the site fix it broke the plugin

**Comment by Norsze** [comment]
Clear cookies and webview data, also go to the discord first next time

**Comment by Xyndra** [comment]
I just cleared cookies+webview and restarted and problem remains

**Comment by Smol-Ame** [comment]
> I just cleared cookies+webview and restarted and problem remains

Damn, they changed selectors during/after fixing their site. Wait for a fix or migrate to a different/better source

**Comment by tsunaproxD** [comment]
> I just cleared cookies+webview and restarted and problem remains

Yeah, I update the extension and do those and nothing work :(

**Comment by Divyam-Naudiyal** [comment]
Is the extension fixed as my webview is working not the extension

**Comment by Smol-Ame** [comment]
> Is the extension fixed as my webview is working not the extension

Did you update your extension?

**Comment by Divyam-Naudiyal** [comment]
> > Is the extension fixed as my webview is working not the extension
> 
> Did you update your extension?

My version is 1.4.58

**Comment by Smol-Ame** [comment]
> My version is 1.4.58

That's an old old version, come to Keiyoushi Discord repo-support channel for help with this

**Comment by tsunaproxD** [comment]
My asura is working now, thx 😊

**Comment by Divyam-Naudiyal** [comment]
> > My version is 1.4.58
> 
> That's an old old version, come to Keiyoushi Discord repo-support channel for help with this

I have also a version of 1.4.37

**Comment by Divyam-Naudiyal** [comment]
> 1.4.37

It was working fine couple a minute ago now it showing obsolete extension and no chapter founds

**Comment by Smol-Ame** [comment]
> It was working fine couple a minute ago now it showing obsolete extension and no chapter founds

As mentioned @Divyam-Naudiyal , come to the Keiyoushi Discord repo-support channel for help. Makes it easier to communicate

**Comment by Divyam-Naudiyal** [comment]
> > It was working fine couple a minute ago now it showing obsolete extension and no chapter founds
> 
> As mentioned @Divyam-Naudiyal , come to the Keiyoushi Discord repo-support channel for help. Makes it easier to communicate

Can share the link for discord

**Comment by Smol-Ame** [comment]
> Can share the link for discord

It's on the top of the README for the repo GitHub page
