### ISSUE TITLE
Rocks Manga: No results found

### ISSUE THREAD

**Issue by OtakuArab** [keiyoushi/tachiyomi-extensions-source#4271]
### Source information

Rocks Manga 1.4.36

### Source language

Arabic

### Steps to reproduce

Access to source - error No results found

### Expected behavior

The results should appear because the site is running
![Screenshot_٢٠٢٤٠٧٢٧-٠٠٤١٥١_Mihon](https://github.com/user-attachments/assets/f887acd0-f09f-4b38-8486-31fbb9a78d89)

### Actual behavior

An error has appeared. No results found
![Screenshot_٢٠٢٤٠٧٢٧-٠٠٤١٤٦_Mihon](https://github.com/user-attachments/assets/98dd4f0b-9fae-4b0c-b790-be76ca9c0a24)

### Mihon/Tachiyomi version

bata 6778

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #4117
