### ISSUE TITLE
No chapters found in Asura Scans

### ISSUE THREAD

**Issue by kuroko14** [keiyoushi/tachiyomi-extensions-source#4274]
### Source information

Asura Scans 1.4.36

### Source language

English

### Steps to reproduce

1. Open Asura Scans
2. Go to any Manhwa

### Expected behavior

Chapters should loaded

### Actual behavior

No chapters found

### Mihon/Tachiyomi version

Beta r6778

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #4267

Search the existing issues first before opening a new issue, and acknowledging that you did when you didn't
