### ISSUE TITLE
Kai Scans is now Lua Scans (Unoriginal)

### ISSUE THREAD

**Issue by Zethzune** [keiyoushi/tachiyomi-extensions-source#4276]
### Source information

Kaiscans 1.4.34

### Source language

English

### Steps to reproduce

Open kaiscans 

### Expected behavior

With chapters 

### Actual behavior

No chapters
Webview getting redirect to luascans

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Kai Scans redirects to current Lua Scans extension link, additional info about this in #4190

**Comment by Norsze** [comment]
Kaiscans archived their old domain and are now operating as a fake Lua Scans site at luacomic.com

**Comment by Tatsuya1221** [comment]
The current plugin leads to "luacomic.com, the luascans.com and luacomic.com names were hacked and taken from the original site owner, the current site for luascans is luacomic.net
