### ISSUE TITLE
Asura is saying that there are no chapters found

### ISSUE THREAD

**Issue by ArchCelestial** [keiyoushi/tachiyomi-extensions-source#4286]
### Source information

Asura Scans 1.4.36

### Source language

English

### Steps to reproduce

I tried to update the manhwa, but it says there are no chapters found, which doesn't make sense since on Asura, there are clearly chapters there. Additionally, the manhwa is not updating the new chapters either. You can still read whatever chapters were there originally.

### Expected behavior

Should show new chapters

### Actual behavior

Says no chapters found

### Mihon/Tachiyomi version

TachiSY Preview r561

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ArchCelestial** [comment]
Here's an example
![Screenshot_20240727_070601_Komikku](https://github.com/user-attachments/assets/4a3dd3af-8b59-42ec-a766-cb2737ed5116)

**Comment by ArchCelestial** [comment]
Vs on Asura
![Screenshot_20240727_071047_Komikku](https://github.com/user-attachments/assets/78743504-a140-4335-a4a5-71dcb3dbfd6d)

**Comment by Norsze** [comment]
Update your extension
