### ISSUE TITLE
Toonily stopped functioning like normal

### ISSUE THREAD

**Issue by Imnewhere12** [keiyoushi/tachiyomi-extensions-source#4287]
### Source information

Toonily version 1.4.18

### Source language

English

### Steps to reproduce

1. Click on browse
2. Click on Toonily source
3. No results are shown for latest or browse
4. Click on arrow next to latest to move into source 
5. Http 500 error is given with error check in webview
6. Click check in webview
7. Error connecting to database
8. Click 3 dots to check via browser
9. Opens fine via browser
![Screenshot_20240727_065355_TachiyomiSY](https://github.com/user-attachments/assets/3d54bb48-7363-4f68-b759-6e0aa085971b)
![Screenshot_20240727_065507_TachiyomiSY](https://github.com/user-attachments/assets/e1b7dc9e-2547-4875-9518-2bb6a7de3e82)
![Screenshot_20240727_065639_TachiyomiSY](https://github.com/user-attachments/assets/aacb8cae-4177-4053-9846-bb65056dc75a)
![Screenshot_20240727_065744_Samsung Internet](https://github.com/user-attachments/assets/1272cf92-9fc2-4930-a783-16286b202890)

### Expected behavior

When clicking into source manga should be shown.

### Actual behavior

Error when trying to view through source or saved manga.

### Mihon/Tachiyomi version

Tachiyomi R561

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
It works again

**Comment by Swadian-Knight** [comment]
I am having this error now.

**Comment by Norsze** [comment]
@bone-grinder28 Not our issue, their servers and site is just bad
