### ISSUE TITLE
AsuraScans Chapters not loading

### ISSUE THREAD

**Issue by zaraaf** [keiyoushi/tachiyomi-extensions-source#4294]
### Source information

Asura Scans 1.4.35

### Source language

English

### Steps to reproduce

1. Open Asura Scans Source
2. Choose Manwha that you don't have in your library

### Expected behavior

A list of chapters should be displayed that can be clicked on and read

### Actual behavior

No chapters are displayed and "No chapters found" error is produces

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 14

### Other details

If you open the manwha in webview it comes up fine with chapters and all.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Update your extension
