### ISSUE TITLE
Gri Melek Lastpage Not Downloaded

### ISSUE THREAD

**Issue by Rip0000** [keiyoushi/tachiyomi-extensions-source#4297]
### Source information

Gri Melek 1.4.43

### Source language

turkish

### Steps to reproduce

lastpage not downloaded

### Expected behavior

lastpage not downloaded

### Actual behavior

lastpage not downloaded

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

android 10

### Other details

There is a fake image at the end of the page, so the download is not completed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Fake images should already be filtered out.

Do you have a specific chapter I can test with? 'Any' doesn't help, as I can't reproduce it with `Stepmother’s Friends` and `Bölüm 147 FİNAL`.

**Comment by Rip0000** [comment]
The problem was solved automatically, there is no problem at the moment, so I am closing the issue, thank you.
