### ISSUE TITLE
Failed to Get Extension List

### ISSUE THREAD

**Issue by a0repo** [keiyoushi/tachiyomi-extensions-source#43]
### Source information

All

### Source language

All

### Steps to reproduce

When tried to install any extension or clicking the Browse→Extension small pop up will appears say "Failed to Get Extension List".

### Expected behavior

On original tachiyomi got no problem, i can install any extension normally.

### Actual behavior

On other tachiyomi apps i can't even browse any extensions.

### Tachiyomi version

15.2

### Android version

Android 11

### Other details

This happened on Tachi SY, Tachimanga(iOS) already tried using any DNS but gave nothin.
![Screenshot_20240110-024744_TachiyomiSY](https://github.com/keiyoushi/extensions-source/assets/153779538/57d3acb0-e2bd-4a8e-b05f-167da4c5d647)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
Actually use your brain cells. Does this look like app support to you?

**Comment by a0repo** [comment]
> Actually use your brain cells. Does this look like app support to you?

sorry, I'm not sure whether this was an app issue or source issue. so make one to app issue?

**Comment by FourTOne5** [comment]
It works on one doesn't on another. What else can it be except an app issue?

**Comment by a0repo** [comment]
> It works on one doesn't on another. What else can it be except an app issue?

Ok, sorry for makin mistake. I was thinking that your repo can be used with other tachi, sorry for bothering. ty

**Comment by valeryan** [comment]
@a0repo I am sure you will notice that you get that message regardless of using this extension list or not. Most derivative applications such as SY, AZ, TachiManga, etc have a bug that they wait for the official extension list and timeout with an exception if it's not found. Authors of those applications have to update to address this new broken world we live in. Have patience those apps will get updated. 

If you are using SY here is a workaround:
1. installing the main Tachiyomi app
2. add this extension list
3. install the sources you wish to use through Tachiyomi. 
4. open SY again and you will see the source in your list
5. add it as trusted, you can now use that source but it will be listed as "Unofficial Source" or something like that.
