### ISSUE TITLE
Asurascans 

### ISSUE THREAD

**Issue by oshiozondi** [keiyoushi/tachiyomi-extensions-source#4309]
### Source information

Asurascan1.4.58

### Source language

English 

### Source new URL

https://asuracomic.net/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by oshiozondi** [comment]
It keeps showing no results found

**Comment by AwkwardPeak7** [comment]
Uninstall the old extension and install the new one, for further help, come to our discord

**Comment by pogora** [comment]
Works. You should remove the PBone source repo, that one is no longer maintained.
Plug in v 1.4.37 has the updated url.
