### ISSUE TITLE
Ancient Comics (Pt-Br Source) shows no content.

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#4317]
### Source information

Ancient Comics 1.4.31

### Source language

Portuguese Brazilian 

### Steps to reproduce

It doesn't show the content in the app only in the WebView.

![Screenshot_2024-07-28-22-31-48-405_app mihon](https://github.com/user-attachments/assets/560a8534-e034-4a22-b435-b7ff01527e83)
![Screenshot_2024-07-28-22-32-01-777_app mihon](https://github.com/user-attachments/assets/2a8498a3-29e1-44d1-854e-f71e60955b00)

### Expected behavior

Show content in the app.

### Actual behavior

You can only see the content in WebView.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
@EvaldoCeBr Ancient is changing their website. Visit their discord channel.

**Comment by EvaldoCeBr** [comment]
> @EvaldoCeBr Ancient is changing their website. Visit their discord channel.

@choppeh Maintenance is over and the extension is not working.

**Comment by choppeh** [comment]
Theme change (madara)
