### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by ISEE7227** [keiyoushi/tachiyomi-extensions-source#4321]
### Source name

https://tecnoscans.xyz

### Source language

English 

### Describe your suggested feature

New website for the extension library 😊  https://tecnoscans.xyz/

### Other details

Please add this website please.🙏 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
Already exists, next time use the source request template for such issues
