### ISSUE TITLE
[Source request] Serpentes Comics

### ISSUE THREAD

**Issue by Kungairo** [keiyoushi/tachiyomi-extensions-source#4323]
### Source name

Serpentes Comics

### Source link

https://serpentescomics.com.br

### Source language

Português Brasil - PT-BR

### Other details

![photo_2024-07-29_09-33-55](https://github.com/user-attachments/assets/229f7f76-4d0b-44af-849e-96d52db7d2e2)
![photo_2024-07-29_09-35-19](https://github.com/user-attachments/assets/23e6d1ec-990c-4106-a939-b0fad95a3a3f)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
website is down, feel free to open new issue when they are back
