### ISSUE TITLE
Manga-scan (FR)-pages don't load

### ISSUE THREAD

**Issue by ElCacciatore** [keiyoushi/tachiyomi-extensions-source#4331]
### Source information

Manga-scan 1.4.15

### Source language

French

### Steps to reproduce

Open manga
Open chapter
Pages don't load
![Screenshot_2024-07-29-22-46-12-882_app mihon](https://github.com/user-attachments/assets/3fb86b31-387c-4166-8162-5d9c39630298)
![Screenshot_2024-07-29-22-46-54-362_app mihon](https://github.com/user-attachments/assets/f1b09f0e-4a0b-4a08-9c4d-792617aadfd5)

### Expected behavior

Pages load and you can read

### Actual behavior

Pages don't load, you can't read

### Mihon/Tachiyomi version

Mihon 0.16.15

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Most likely just an URL change to do, domain changed from .com to .net, will try to get it fixed today or tomorrow.
