### ISSUE TITLE
Add status to description

### ISSUE THREAD

**Issue by mm12** [keiyoushi/tachiyomi-extensions-source#4332]
### Source name

MangaDex

### Source language

Any

### Describe your suggested feature

Almost identical to alternative titles, add an option to include the current status in the description. While this may _seem_ to be unneeded due to filtering in the base app, MD had other status types that are not searchable in it: 
- Hiatus
- Cancelled
- Finished Publishing

Adding these to the description would allow these to be searchable. 

### Other details

If I get time, I can probably implement this myself. If someone else can do it before then, please do so. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
This should be an issue to the app, allowing filtering based on status. Adding status in description is kind of an hack...

**Comment by mm12** [comment]
> This should be an issue to the app, allowing filtering based on status. Adding status in description is kind of an hack...

While I do kinda agree, not every extension implements them, and when this was brought up in the past, that was a given reason not to. I believe that is why Alt titles are also implemented in the extension. 

I so think the base app should have things like field filtering though (things like `status:ongoing` and `indesc:abc`) instead of just searching all of everything...

**Comment by AwkwardPeak7** [comment]
https://togithub.com/mihonapp/mihon/issues/1054
