### ISSUE TITLE
ReadComicOnline doesn't work

### ISSUE THREAD

**Issue by cowboydroptop** [keiyoushi/tachiyomi-extensions-source#4334]
### Source information

ReadComicOnline 1.4.26

### Source language

English

### Steps to reproduce

1. Tap on chapter that is not downloaded from a series from the extension and it keeps loading and after a while it says "couldn't bypass cloudfare"
2. Chapter doesn't load and go to webview of the seried to try to fix the problem 
3. In salmon pink it says "Tap here for help with cloudfare" and I have to verify
4. Back to the chapter after verification it says "The image couldn't be loaded"
5. Tap on webview on the page and it says "400. That's an error. Your client has issued a malformed or illegal request. That's all we know."

### Expected behavior

The chapter should show up as normal, even after verification

### Actual behavior

Forced to do verification to no avail. Can't read chapter of any series that isn't downloaded

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

Changing user agent string doesn't work. I tried multiple different ones but alas.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #4115
