### ISSUE TITLE
Ngomik: Change Domain

### ISSUE THREAD

**Issue by Hannaichi** [keiyoushi/tachiyomi-extensions-source#4338]
### Source information

Ngomik 1.4.32

### Source language

Indonesian

### Source new URL

https://ngomik.mom

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by blitzboy01** [comment]
geo blocked
