### ISSUE TITLE
MangaDex source show no results

### ISSUE THREAD

**Issue by smartacephale** [keiyoushi/tachiyomi-extensions-source#4343]
### Source information

MangaDex 1.4.193

### Source language

English

### Steps to reproduce

Search for  _DDT_ or _Miminashi-Hohichi_ (this title on [mangadex](https://mangadex.org/title/3ba57f94-f3f6-4cd4-ba04-ed1c6268fbee/ddt))

### Expected behavior

Should show results

### Actual behavior

Show no results

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
Enable erotica content rating in extension settings

**Comment by smartacephale** [comment]
it helped, thanks, also it's stupid to set nsfw disabled by default since app is illegal anyway and most of users, even if they under 18... oh god should this really be said...

**Comment by Norsze** [comment]
Ok, now take that and walk over to the Mangadex forums and tell them the same
