### ISSUE TITLE
Demon Sect erro 

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#4347]
### Source information

Demon Sect 1.4.44

### Source language

Português (Brasil)

### Steps to reproduce

A Demon Sect não Funciona no aplicativo, mas está funcionando no Webview 

Aplicativo 
![Screenshot_20240730-132911](https://github.com/user-attachments/assets/f979d9f9-c998-4639-8e91-eb6d6057cc09)

Webview 
![Screenshot_20240730-132921](https://github.com/user-attachments/assets/a160aa91-aa7c-4c3f-a005-327309280540)

### Expected behavior

Funcionando normalmente a extensão 

### Actual behavior

A extensão não está carregando normalmente

### Mihon/Tachiyomi version

Mihon 016.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Pedropaulo015** [comment]
Pra mim tá acontecendo a mesma coisa
