### ISSUE TITLE
Atualização Demon Sect

### ISSUE THREAD

**Issue by HyungSilver** [keiyoushi/tachiyomi-extensions-source#4349]
### Source information

Demon Sect 1.4.44

### Source language

Português (Brasil)

### Steps to reproduce

o site teve atualização na página inicial causando problemas ao tentar entrar na extensão 

### Expected behavior

ao abrir a extensão deveria aparecer a obra

### Actual behavior

ao abrir a extensão dá "nenhum resultado encontrado"

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by HyungSilver** [comment]
![Screenshot_20240730_113202_Mihon](https://github.com/user-attachments/assets/a501fcf0-10ce-47a5-b313-9223bc325126)
![Screenshot_20240730_113213_Mihon](https://github.com/user-attachments/assets/cd0c8145-868d-452d-8d01-42b4079733c1)

**Comment by Norsze** [comment]
Duplicate of #4347
