### ISSUE TITLE
A fonte Demon Sect não está carregando no aplicativo e nem novos capítulos

### ISSUE THREAD

**Issue by Kungairo** [keiyoushi/tachiyomi-extensions-source#4350]
### Source information

Demon Sect 1.4.44

### Source language

Português Brasil - PT-BR

### Steps to reproduce

Quando eu clico na fonte de Demon Sect, o aplicativo não carrega a fonte e diz "Nenhum resultado encontrado". O mesmo vale para os capítulos que eu tenho baixado dessa fonte. Apesar de eu conseguir entrar para ler eles, são apenas aqueles que consigo ler porque já os instalei. Mas há um erro caso eu tente atualizar os manhwas ou manhua e direi no último tópico com a imagem do erro.
![photo_2024-07-30_13-37-13](https://github.com/user-attachments/assets/bfc1f2e5-83ee-4c18-9f4f-6701ddb9c6b9)

### Expected behavior

O que deveria acontecer era eu abrir a fonte no aplicativo e carregar os manhwas/manhua, mas não acontece. Nem os capítulos dos que tenho baixado estão aparecendo, os novos no caso. Porque eu fui ver e já tinha capítulos novos dos manhwas/manhua no site deles dos que eu já tenho instalado.

### Actual behavior

Agora, o que realmente acontece é o seguinte. Primeiro que quando eu tento entrar na fonte para ver os manhwas/manhua para ler, não há resultados nenhum, como nessa imagem aqui:
![photo_2024-07-30_13-37-13](https://github.com/user-attachments/assets/293e00c9-c89a-422c-981b-89b7ff7b7140)
O segundo problema está quando eu tento atualizar os capítulos dos manhwas/manhua que tenho baixados. O erro é esse:
![photo_2024-07-30_13-39-47](https://github.com/user-attachments/assets/244b2fcd-5878-44b3-840c-b78c0d7185ae)
Não sei o que significa, mas não pode ser algo como que realmente não exista capítulos novos, porque na verdade há sim. No sites deles está até o 92 esse manhwa. O que significa que o erro é outro, mas eu não sei.

### Mihon/Tachiyomi version

0.16.5

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Duplicate of #4347
