### ISSUE TITLE
Hyperdex(EN): Add the type "Manga" in the filter as genre or type

### ISSUE THREAD

**Issue by Palloxin** [keiyoushi/tachiyomi-extensions-source#4353]
### Source name

Hyperdex

### Source language

English

### Describe your suggested feature

Add the missing tag "Manga" in the filter section.

### Why
It's useful to pick japanese entries since the website is a mix.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by weebsamachan** [comment]
Is it just me or does the hyperdex extension not exist...

**Comment by KenjieDec** [comment]
There is no genre 'Manga' on Hiperdex ( I assume that 'Hyperdex' is just a typo of 'Hiperdex' )
![image](https://github.com/user-attachments/assets/541863f4-f726-46cc-a3bc-3e094c828f69)

Or are you referring to another extension?

**Comment by Palloxin** [comment]
@KenjieDec 
Right, i didnt check. On the website it is a "Type"
https://hiperdex.com/manga/hirasaka-hinako-ga-ero-kawaii-koto-wo-ore-dake-ga-shitteiru/
![Screenshot_20240806-143327_1_1](https://github.com/user-attachments/assets/23fdbb7a-5d8a-4517-b6c2-4b26ef9c1f32)
But on tachiyomi it is showed together with the genres:
![Screenshot_20240806-143546_1_1](https://github.com/user-attachments/assets/8e90c568-eb45-477b-a668-e7b10d2f2f92)
Since the extension has already "manhwa" in the genre list i don't think it would be a problem to add it in the genre list. If you want to make a type section, that's fine too.

**Comment by AwkwardPeak7** [comment]
genre filters are fetched from the site, and there is not "manga" genre there. There is also no way to search by type alone. so can't really be added
