### ISSUE TITLE
Asura Scans needs to be updated 

### ISSUE THREAD

**Issue by Evile216** [keiyoushi/tachiyomi-extensions-source#4354]
### Source information

Asura Scans 1.4.58

### Source language

English 

### Source new URL

https://asuracomic.net/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
You are using a version of the extension that was replaced in January...

**Comment by Smol-Ame** [comment]
Come to the Keiyoushi Discord repo-support channel if you can't figure it out/have any other questions
