### ISSUE TITLE
Reaper Scans new rewritten website 

### ISSUE THREAD

**Issue by bauripalash** [keiyoushi/tachiyomi-extensions-source#4355]
### Source information

Reaper Scans 1.4.49

### Source language

English

### Source new URL

https://reaperscans.com/

### Other details

Reaper Scans have rewritten their website, thus the extension is no longer working

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Wrong issue request, you can make another one with the right issue request (issue report), but nothing can be done until they finish up & stabilize.

**Comment by bauripalash** [comment]
> Wrong issue request, you can make another one with the right issue request (issue report), but nothing can be done until they finish up & stabilize.

@Smol-Ame which one is appropriate?

**Comment by Smol-Ame** [comment]
> @Smol-Ame which one is appropriate?

As mentioned in my previous message, issue report

**Comment by bauripalash** [comment]
> > @Smol-Ame which one is appropriate?
> 
> As mentioned in my previous message, issue report

Thank you. I opened a new issue
