### ISSUE TITLE
Reaper Scans New Website 

### ISSUE THREAD

**Issue by bauripalash** [keiyoushi/tachiyomi-extensions-source#4356]
### Source information

Reaper Scans 1.4.49

### Source language

English

### Steps to reproduce

Open any comic from the aforementioned source. Or even open the webview.

### Expected behavior

Show chapters.

### Actual behavior

404 Not Found.

### Mihon/Tachiyomi version

Mihon Beta r6789 or any other

### Android version

Android 13

### Other details

Reaper Scans have rewritten their website, thus the extension is no longer working.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bauripalash** [comment]
@webmsgr The cover images are not visible on search, only if I open some entry then the image is visible in search and other places.

![Screenshot_20240802_162921_Mihon](https://github.com/user-attachments/assets/273fe67a-8b18-48e0-a421-804e98c5bf58)

> I blurred the entry names in the screenshot

**Comment by AwkwardPeak7** [comment]
please open a new issue instead of commenting on existing one
