### ISSUE TITLE
Reaperscans changed site layout

### ISSUE THREAD

**Issue by TheTaterLord** [keiyoushi/tachiyomi-extensions-source#4357]
### Source information

Reaperscans 1.4.49

### Source language

English

### Steps to reproduce

Download and install source navigate to any manage 404 will be returned as the sites layout has changed

### Expected behavior

Should be able to view the manga/mamhua

### Actual behavior

Get 404 page does not exist error

### Mihon/Tachiyomi version

0.15.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #4356 

Search the existing issues for before opening a new one, and acknowledging that you did when you didn't
