### ISSUE TITLE
Manganato not showing pages

### ISSUE THREAD

**Issue by masdabazz** [keiyoushi/tachiyomi-extensions-source#4364]
### Source information

Manganato 1.4.7

### Source language

English

### Steps to reproduce

Click on any entry that is from manganato

### Expected behavior

Pages of chapter that I am on should show.

### Actual behavior

1st page shows but the rest does not. It comes up with : The image couldnt be loaded        Retry   Open Webview.

When I press open in webview nothing happens, however when I click webview on the page of the entry (not the individual chapter),
it goes to the webpage just fine, and I can click on the chapters in the webpage and they load.

Also, when I go on an individual chapter, tap the screen for options, go on the three vertical dots then open in webview, the chapter webpage opens up. 

### Mihon/Tachiyomi version

0.16.5

### Android version

Andriod 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Come to the Keiyoushi Discord repo-support channel for help/troubleshooting
