### ISSUE TITLE
Demon sect não esta funcionando

### ISSUE THREAD

**Issue by EnzooFelixDev** [keiyoushi/tachiyomi-extensions-source#4368]
### Source information

Demon sect Scan

### Source language

Brazilian Portuguese - Português (Brasil)

### Steps to reproduce

Demon sect não esta funcionando no app, so na webview

### Expected behavior

Conseguir ler normalmente pelo mihon

### Actual behavior

![Screenshot_20240731_184646_Mihon](https://github.com/user-attachments/assets/763cc5ec-acef-4370-9e43-bc5a390854ff)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #4347
