### ISSUE TITLE
wfwf341

### ISSUE THREAD

**Issue by Kinupsy-co** [keiyoushi/tachiyomi-extensions-source#4377]
### Source name

wfwf341 1.4.1

### Source link

https://wfwf341.com/

### Source language

Korea

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by bauripalash** [comment]
The url has already changed to `https://wfwf342.com/`

**Comment by MikeZeDev** [comment]
Duplicate issue: https://github.com/keiyoushi/extensions-source/issues/3987 . Should be closed.
Well its hard to find wfw using search feature to be honest.
