### ISSUE TITLE
Extension dont work 

### ISSUE THREAD

**Issue by UserKiyotaka** [keiyoushi/tachiyomi-extensions-source#4388]
### Source information

Asura Scans

### Source language

English 

### Steps to reproduce

![Screenshot_20240803-031625](https://github.com/user-attachments/assets/d9258890-fdb0-4bec-8ee6-4ccef0b988a7)

### Expected behavior

Should show the series available 

### Actual behavior

Don't show the series
![Screenshot_20240803-031625](https://github.com/user-attachments/assets/878d4fbf-0d81-4f01-9e40-49f9660b6b2b)

### Mihon/Tachiyomi version

0.16.5

### Android version

android 12

### Other details

tried everything in help section 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
It works

Come to the Keiyoushi Discord repo-support channel for help & easier communication
