### ISSUE TITLE
Changement du nom de la version d'extension 

### ISSUE THREAD

**Issue by sakke32** [keiyoushi/tachiyomi-extensions-source#4389]
### Source information

fr.epsilonscan 1.4.37

### Source language

Français 

### Source new URL

https://epsilonscan.to/

### Other details

On ne peut rien télécharger, l'URL source a complètement changé 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
La source a la bonne URL, et elle fonctionne chez moi, pense à nettoyer la base de données pour Epsilon Scan dans les paramètres ou autre.

**Comment by Norsze** [comment]
Kirin is right [it is already that URL](https://github.com/keiyoushi/extensions-source/blob/main/src%2Ffr%2Fepsilonscan%2Fsrc%2Feu%2Fkanade%2Ftachiyomi%2Fextension%2Ffr%2Fepsilonscan%2FEpsilonScan.kt#L9).

**Comment by sakke32** [comment]
Malgré tout cela sa marche toujours pas, les images ne s'affichent pas je ne peux rien télécharger. J'ai vidé le cache sa marche toujours pas. Pourriez vous s'il vous plaît m'envoyer l'extension qui marche chez vous ? Parce que moi je comprends plus rien, les autres extension marche sauf celui d'Epsilon scan to. Je suis désespérée. Aider moi s'il vous plaît.

**Comment by KirinRaikage** [comment]
Tu peux essayer ce qui'il y a dans https://mihon.app/docs/guides/troubleshooting/
Je crois qu'Epsilon Scan bloque certains user agents, donc tu peux essayer de suivre cette étape de ce lien. 
Sinon, essaie TOUTES les autres étapes de ce lien.

**Comment by sakke32** [comment]
Sa marche toujours pas 😭, j'ai fait comme le dit le lien mais rien, les images ne s'affichent pas. Vous pourriez s'il vous plaît m'envoyer l'extension revérifier du 4 juillet. Moi j'utilise toujours l'extension donner sur la plateforme Reddit. Mais si vous pouvez pas ce n'est pas grave. Merci quand même d'avoir pris votre temps pour m'aider.😁

**Comment by KirinRaikage** [comment]
Envoie-moi un DM sur Discord : KirinRaikage

**Comment by sakke32** [comment]
Je vous ait déjà envoyé un coucou, mon nom d'utilisateur est sakke32
