### ISSUE TITLE
YaoiLib: Add all translations

### ISSUE THREAD

**Issue by ghostsmuffins** [keiyoushi/tachiyomi-extensions-source#4400]
### Source name

YaoiLib 1.4.27

### Source language

Russian

### Describe your suggested feature

This source allows for translation variants, but whenever a newer translation drops from the second translation variant it replaces the first one in the app, which is really uncomfortable when I prefer the translation variant that came out first. I suggest adding all translations.

### Other details

Might be an issue for both of the other sources in the Lib family (MangaLib, HentaiLib) but I only observed it in person with YaoiLib.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by romshke** [comment]
Browse -> extensions -> yaoilib -> gear button next to русский -> способ выбора переводчиков -> select все переводы (друг за другом)

![Screenshot_2024-08-13-10-44-02-69_a603e4da04bada03cae438f177815547.jpg](https://github.com/user-attachments/assets/690b25a1-ce36-4dad-b53b-810e06275c8a)


Same for other lib extensions

**Comment by romshke** [comment]
To hide other translations use scanlator filter

![IMG_20240813_110244.jpg](https://github.com/user-attachments/assets/8eb2bafa-9865-41b4-bed6-6e5574888ebf)
