### ISSUE TITLE
ReadComicOnline not showing loading pages through the extension

### ISSUE THREAD

**Issue by ASGWP** [keiyoushi/tachiyomi-extensions-source#4409]
### Source information

ReadComicOnline 1.4.26

### Source language

English

### Steps to reproduce

1-Open any comic and open any chapter from the extension
2-Wait until the chapter loads
3-An error appears saying the followong "The image couldn't be loaded"

### Expected behavior

The chapter should load normally and the error shouldn't appear

### Actual behavior

The chapter doesn't load and an error appear

### Mihon/Tachiyomi version

Tachiyomi -> 0.15.3 / Mihon -> 0.16.5

### Android version

Android 11

### Other details

When you try to open webveiw from within the chapter, an "error 400" page appears. But, When you open the comic in webveiw before choosing a chapter, you can open any chapter in the website after seeing some ads. (I attached a video to show you what I mean)

https://github.com/user-attachments/assets/54a92d49-02e5-4c04-bf60-569186cf76d4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #4115 

Search the existing issues before opening a new issue, and acknowledging that you did when you didn't
