### ISSUE TITLE
MangaSee: Chapter pages in certain mangas "The image cannot be loaded"

### ISSUE THREAD

**Issue by iotaide** [keiyoushi/tachiyomi-extensions-source#4416]
### Source information

MangaSee v1.4.36

### Source language

English

### Steps to reproduce

i. Open certain manga series and any of its chapters
ii. Loading results to error "The image cannot be loaded"

### Expected behavior

The chapter should load normally and no error should occur

### Actual behavior

The chapter doesn't load normally and results to "The image cannot be loaded"

### Mihon/Tachiyomi version

Mihon v0.16.5

### Android version

Android v8.1

### Other details

The weird thing is that the issue only happens to _certain_ mangas (Blue Box, Ruri Dragon, etc.), and also whenever I try the chapter webview version it also doesn't load the pages properly. 

But the other weird thing is that the pages load normally in my browser app (Chrome) and I can read there just fine, whereas using mihon or the chapter webview of the manga results to the issue. Though, I'm not sure whether the problem is with the extension or mihon. (Might also just be having an old phone)

Changing user-agent strings, clearing caches and webview data doesn't seem to solve the issue I'm having.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
cannot reproduce, I tried those manga you mentioned, works fine.

> Might also just be having an old phone

that is possible if your phone isn't able to decode some images

try downloading the chapters?

come to our discord for further help
