### ISSUE TITLE
Relax ratelimit of MangaSee

### ISSUE THREAD

**Issue by weebsamachan** [keiyoushi/tachiyomi-extensions-source#4423]
### Source name

MangaSee

### Source language

English

### Describe your suggested feature

The loading of thumbnails in this extension is very slow (1 request in 2 seconds). Maybe it could be relaxed to 2 requests per second for the whole extension or just thumbnails? (although doing so for just thumbnails would require making changes to the Mihon source code...).

### Other details

I have already tried relaxing it per source code and there do not appear to be any immidiate problems with cloudflare...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
Iirc the ratelimit was put in by tachi extension maintainers since MangaSee admin asked them to (since it was causing too much load on their site), otherwise they would have started blocking/breaking the extension.

**Comment by weebsamachan** [comment]
I guess relaxing the ratelimit for just thumbnails (since they are small) might also lead to problems with the mangasee admin then.
