### ISSUE TITLE
[PT-BR] Blackout Comics: No results found

### ISSUE THREAD

**Issue by viminio** [keiyoushi/tachiyomi-extensions-source#4426]
### Source information

Blackout Comics

### Source language

Portuguese (Brazilian)

### Steps to reproduce

1. Open extension
2. Login
3. Open Manga
4. Start reading
5. Error

### Expected behavior

Load chapters

### Actual behavior

No chapter loads

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 11

### Other details

![image](https://github.com/user-attachments/assets/9c2cfa3a-f20c-424c-a89e-418c05c910cd)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by viminio** [comment]
I'm downloading it manually with the following code

function pageListParse(document) {
  return Array.from(document.querySelectorAll("div.img-capitulos canvas"))
    .map((item, index) => ({
      index: index,
      url: item.getAttribute("w78b4861f0"),
    }));
}

function downloadImage(url, index) {
  const link = document.createElement("a");
  link.href = url;
  link.download = `image-${index}.jpg`; // Nome do arquivo para download
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

async function downloadAllImages() {
  const images = pageListParse(document);
  images.forEach((image) => {
    downloadImage(image.url, image.index);
  });
}

// Executar a função para baixar todas as imagens
downloadAllImages();

**Comment by AwkwardPeak7** [comment]
please censor nsfw images
