### ISSUE TITLE
No page found Asura scan

### ISSUE THREAD

**Issue by Gamermemer** [keiyoushi/tachiyomi-extensions-source#4429]
### Source information

Asura Scan

### Source language

English

### Steps to reproduce

Open app
Open manhwa
Open chapter
No page found

### Expected behavior

Open app
Open manhwa
Open chapter
Page found 

### Actual behavior

Open app
Open manhwa
Open chapter
No page found

### Mihon/Tachiyomi version

Tachiyomi stable0.15.3

### Android version

Android 11

### Other details

![Screenshot_20240805_230529_Tachiyomi](https://github.com/user-attachments/assets/d6926c80-03c8-4021-962e-e10599cd3541)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Deem3** [comment]
It had been working well 2 or 3 days ago. But now when i try to read manhwa. It's showing no page found

**Comment by Turhvjbufv** [comment]
> It had been working well 2 or 3 days ago. But now when i try to read manhwa. It's showing no page found

Known, a fix is being worked on, wait.
Don't spam here for nothing

**Comment by zaraaf** [comment]
Will i have to migrate again? ive migrated 3x now with asurascans and its been 100+ manhwa each time lol

**Comment by Turhvjbufv** [comment]
> Will i have to migrate again? ive migrated 3x now with asurascans and its been 100+ manhwa each time lol

Probably not, but wait until the fix is out, if it's needed they will say it

**Comment by Xyndra** [comment]
It's unlikely since mangas are recognized, only pages are not
