### ISSUE TITLE
AsuraScans: No pages found when opening chapters.

### ISSUE THREAD

**Issue by midi1996** [keiyoushi/tachiyomi-extensions-source#4431]
### Source information

Asura Scans 1.4.38

### Source language

English

### Steps to reproduce

1. Open any entry
2. Pick a chapter

### Expected behavior

Chapter images to load

### Actual behavior

Getting an error: "No pages found"

### Mihon/Tachiyomi version

0.16.5 (6)

### Android version

Android 13/14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by midi1996** [comment]
Duplicate of #4429 . Issues were made at the same time.

**Comment by AwkwardPeak7** [comment]
Duplicate of #4429
