### ISSUE TITLE
Asura scans no pages found error

### ISSUE THREAD

**Issue by Gojodatebayo** [keiyoushi/tachiyomi-extensions-source#4433]
### Source information

Asura Scans 1.4.38

### Source language

English 

### Steps to reproduce

Show no pages found in the chapters even though it is there in web view
![Screenshot_2024-08-06-00-25-55-35_a603e4da04bada03cae438f177815547](https://github.com/user-attachments/assets/fc0f7186-8631-4653-a4ef-22f16cb3d812)

### Expected behavior

It should open the chapter

### Actual behavior

It shows no pages found 

### Mihon/Tachiyomi version

TachiyomiSY App version: 1.10.5 (standard, 6c563d7, 65, 2024-03-02T20:42Z) 

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #4429
