### ISSUE TITLE
Error code 525

### ISSUE THREAD

**Issue by Kerg01** [keiyoushi/tachiyomi-extensions-source#4439]
### Source information

Ikigai 1.4.13

### Source language

Español

### Steps to reproduce

https://github.com/user-attachments/assets/85eea92a-c59e-4cf7-979c-c0d116f79eb0

### Expected behavior

Debería poder entregar al capítulo deseado y leer el manga.

### Actual behavior

Manda error 525, incluso en webview.
![Screenshot_2024-08-05-19-43-22-875_app mihon debug](https://github.com/user-attachments/assets/11100b75-e2bc-438d-b10b-e78266c063b4)
![Screenshot_2024-08-05-19-45-14-362_app mihon debug](https://github.com/user-attachments/assets/1d0bb779-7c77-4e70-b17d-6c620b0bc3e0)

### Mihon/Tachiyomi version

0.16.5 y 0.16.5-6793

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #4430
