### ISSUE TITLE
Asura scans issue 

### ISSUE THREAD

**Issue by oitse1** [keiyoushi/tachiyomi-extensions-source#4442]
### Source information

 Asura scans v. 1.4.38

### Source language

English 

### Steps to reproduce

1. Pick title 
2. Pick chapter 
3. No pages found 

### Expected behavior

When on clicking on chapter, page of said novel should pop up

### Actual behavior

Says no pages found 

### Mihon/Tachiyomi version

App version: 0.15.3 (standard, a9c7cbf, 119, 2024-01-13T19:03Z) Android version: 13 (SDK 33; build CPH2197_11_F.66) Device brand: OPPO Device manufacturer: OPPO Device name: OP4F39L1 (CPH2197) Device model: CPH2197 WebView: Android System WebView 127.0.6533.64

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Update your extension
