### ISSUE TITLE
Solo leveling arise - mangadex

### ISSUE THREAD

**Issue by Sundogg17** [keiyoushi/tachiyomi-extensions-source#4462]
### Source information

Mangadex 1.4.193

### Source language

English 

### Steps to reproduce

Chapters do not appear in list. They appear on webview.

### Expected behavior

To show available chapters 

### Actual behavior

Does not show. 

![Screenshot_20240806_082450_TachiyomiJ2K](https://github.com/user-attachments/assets/2b55972f-e83c-47f0-b282-a34a24fdec04)
![Screenshot_20240806_082456_TachiyomiJ2K](https://github.com/user-attachments/assets/4c5361cc-2b47-455b-8a90-aaa6d8109771)

### Mihon/Tachiyomi version

Tachij2k 1.74 

### Android version

17

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
As you can see with the arrow icon in webview, English chapters are external, not on MangaDex.

**Comment by Sundogg17** [comment]
So official pub means external?

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Smol-Ame** [comment]
> So official pub means external?

Usually, for Mangadex, since they don't host those chapters themselves, the extension can't access/read said chapters. Use a different source or those publisher sources instead
