### ISSUE TITLE
manhwatop.to

### ISSUE THREAD

**Issue by Achuabdu** [keiyoushi/tachiyomi-extensions-source#4468]
### Source name

manhwatop.to

### Source link

https://manhwatop.to/

### Source language

English 

### Other details

Previously when manhwatop.to was requested mangatop.to was added
![Screenshot_2024-08-06-23-16-10-794_com android chrome](https://github.com/user-attachments/assets/ecd75b1b-32c4-4e3b-993a-1952e05ebe7a)
![Uploading Screenshot_2024-08-06-23-16-10-794_com.android.chrome.jpg…]()

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Fixed by #4451
