### ISSUE TITLE
Mangabuddy fail to download or see chapters but by using webview we can see it

### ISSUE THREAD

**Issue by Achuabdu** [keiyoushi/tachiyomi-extensions-source#4487]
### Source information

Mangabuddy 1.4.16

### Source language

English 

### Steps to reproduce

1st when downloading or trying to read error (failed to connect )
![Screenshot_2024-08-07-22-01-26-812_eu kanade tachiyomi sy](https://github.com/user-attachments/assets/dc930485-b1d1-4417-93b6-cebc6c7b72e5)
![Screenshot_2024-08-07-22-01-46-772_eu kanade tachiyomi sy](https://github.com/user-attachments/assets/436354b1-ec9c-44d6-8666-9953c84b6156)

### Expected behavior

![Screenshot_2024-08-07-22-01-46-772_eu kanade tachiyomi sy](https://github.com/user-attachments/assets/a6b83777-e859-4e79-a0ea-359ee851ef01)

### Actual behavior

![Screenshot_2024-08-07-22-01-26-812_eu kanade tachiyomi sy](https://github.com/user-attachments/assets/cf3bbf4c-f346-4e2c-9e9e-46b8ed8cc74b)
![Screenshot_2024-08-07-22-02-36-370_eu kanade tachiyomi sy](https://github.com/user-attachments/assets/7d389eeb-2217-4456-98e9-302dbd8a1af2)

### Mihon/Tachiyomi version

Tachiyomi sy 1.10.5

### Android version

Android 14

### Other details
I have checked it using webview it's working but otherwise it's not showing 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Seems to work fine on my end, come to the Keiyoushi Discord repo-support channel for help/troubleshooting

**Comment by Achuabdu** [comment]
> Seems to work fine on my end, come to the Keiyoushi Discord repo-support channel for help/troubleshooting

Yh when I uninstall and install it's working
