### ISSUE TITLE
Epik manga closed

### ISSUE THREAD

**Issue by Thekages** [keiyoushi/tachiyomi-extensions-source#449]
### Source name

Epik Manga

### Source language

Turkish

### Source link

https://www.epikmanga.com

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by domflamingo2** [comment]
I've just seen the manga version and the novel version '-'.
