### ISSUE TITLE
Mangaplus requires login

### ISSUE THREAD

**Issue by hiddensea** [keiyoushi/tachiyomi-extensions-source#4490]
### Source information

 MANGA Plus by SHUEISHA 1.4.51 

### Source language

English

### Steps to reproduce

1. Add source
2. Attempt to view episodes of manga inbetween the first and last 3

### Expected behavior

Titles should be viewable 

### Actual behavior

Chapters shown as missing. When WebView is opened, MP shows a promotion for the app instead, with no option to log in
![Screenshot_20240807_202851_Mihon](https://github.com/user-attachments/assets/ea197dfe-6196-410a-94d4-e2657e8f7892)
![Screenshot_20240807_202745_Chrome](https://github.com/user-attachments/assets/f7ead213-0ec0-470e-9465-64ab934dccb5)

### Mihon/Tachiyomi version

App version: 0.16.5 

### Android version

Android 14

### Other details

I know this is out of mihons control, however I am looking to see if there is any other way to import chapters from this website

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
There's no way for us to get those hidden chapters, here's an old response of the same question:

![Screenshot_20240807_125450.png](https://github.com/user-attachments/assets/c6d44eab-f7b1-4d49-9959-e2383d4f1a7d)
