### ISSUE TITLE
[PT-BR] Blackout Comics: 500: webview detected(?)

### ISSUE THREAD

**Issue by viminio** [keiyoushi/tachiyomi-extensions-source#4492]
### Source information

Blackout Comics

### Source language

Portuguese (Brazilian)

### Steps to reproduce

1. Open extension
2. Login
3. Error

### Expected behavior

Load mangas

### Actual behavior

![image](https://github.com/user-attachments/assets/4c8c6a88-8f54-498a-853d-34800ad48d15)

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
500 errors are server side, nothing we can do about it

**Comment by viminio** [comment]
> 500 errors are server side, nothing we can do about it

This error only occurs when you log in via the application

**Comment by viminio** [comment]
Is there any way to "hide the app" in the webview to log in?
