### ISSUE TITLE
ManhuaPlus.org (unoriginal)

### ISSUE THREAD

**Issue by scarletM00n** [keiyoushi/tachiyomi-extensions-source#45]
### Source name

manhuaplus alternative site

### Source link

https://manhuaplus.org/

### Source language

English

### Other details

no nsfw

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Gabriel062323** [comment]
yip

**Comment by Secozzi** [comment]
Uses the same theme as mangasect
