### ISSUE TITLE
Reaperscanstr closed

### ISSUE THREAD

**Issue by Thekages** [keiyoushi/tachiyomi-extensions-source#450]
### Source name

Reaper Scans

### Source language

Turkish

### Source link

https://reaperscanstr.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by domflamingo2** [comment]
The site is not dead, please close the issues

**Comment by beer-psi** [comment]
> The site is not dead, please close the issues

Reaper Scans (Turkish) is definitely dead though...
