### ISSUE TITLE
Improve the method of acquiring the baseurl.

### ISSUE THREAD

**Issue by whylalacantuse** [keiyoushi/tachiyomi-extensions-source#4501]
### Source name

BAIMANGU

### Source language

ZH

### Describe your suggested feature

Hello, I've noticed that some websites have more than one URL, where sometimes one URL cannot be accessed while others can. Additionally, there are certain plugins that allow manual changes to URLs (such as BAIMANGU and VOMIC). I wonder if it would be possible to create a universal code block for the baseurl section that allows for modifications of the URL?I also attempted experimenting on my own using LLM, but I'm completely clueless when it comes to programming. Issues arise due to discrepancies in environment settings, versions, formats, etc., which makes it hard to validate the effectiveness of the code. I'd like to contribute somehow, but I'm unsure what role I could play...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
Not from the team, but just my POV as a fellow scrapper developer : 

The problem with allowing url changing on every extension is that it may prevent the devs to know that the url has changed.
Moreover, it may cause issues diagnosis problem if user forgot he changed url.
Lastly, i'd say a good percentage of websites that changed url also need other changes, so it wont work regardless of the url update.

I think they add the option when they are annoyed with a website that changes url every time but i think its fine as an exception .

**Comment by Norsze** [comment]
I think MikeZeDev is pretty spot on, usually it requires more than just a URL change. You also don't want users to fuck it all up by changing the URL of a working extension and then come complain and waste everyone's time by their own user error. 

Unless the site switches each day, then there is really no need, a contributor, with minimal knowledge will fix a URL change pretty fast and confirm it is the actual site and not a copycat site.

All the tools are there to do it yourself, if you want to do it yourself, but as long as it's the extensions in this repo, we want to keep the user errors down cause they will just cause false user reports both here on GitHub and on Discord.

**Comment by whylalacantuse** [comment]
Got it, really appreciate your replies.
