### ISSUE TITLE
Diskus Scan (PT-Br Source) Error

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#4515]
### Source information

Diskus Scan 1.4.39

### Source language

Portuguese Brazilian 

### Steps to reproduce

When entering the source it displays an error.

![Screenshot_2024-08-08-11-17-23-088_app mihon](https://github.com/user-attachments/assets/89abeaba-96a5-4ed9-abec-aa7f27f27879)

### Expected behavior

View source content.

### Actual behavior

When opening, an error appears.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by domflamingo2** [comment]
![image](https://github.com/user-attachments/assets/a1748cbf-f11b-4032-930b-d904e3c6a084)

![image](https://github.com/user-attachments/assets/de0c7405-6dd3-4700-b220-7aaaa1d8207d)

![image](https://github.com/user-attachments/assets/c83334db-83cd-45f4-9acf-9c194679d8e3)

As I don't know the Kotlin language, apparently the site isn't using any proxy.

I just have to wait for some dev to solve this error.

Or it could be a proxy error on the site itself.


"override val client = super.client.newBuilder()
    .proxy(Proxy.NO_PROXY) // Bypass system-wide proxy settings
    .rateLimit(2, 1, TimeUnit.SECONDS)
    .build()
"?
