### ISSUE TITLE
Sussy Scan páginas não está carregando

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#4518]
### Source information

Sussy Scan 1.4.39

### Source language

Português (Brasil)

### Steps to reproduce

As páginas das obras não está carregando na extensão, No Webview está carregando normalmente. 

https://github.com/user-attachments/assets/97c9dee0-efe8-4179-a62d-02bc906b37d1

### Expected behavior

A extensão estar funcionando normalmente 

### Actual behavior

Não estar carregando as páginas

### Mihon/Tachiyomi version

TachiyomiSY 1.10.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Seems to load up fine on my end, try going to SY Settings > Data and storage, and "Clear cache"

If that doesn't work, try migrating the title back into Sussy Scan

**Comment by ghost** [comment]
> Seems to load up fine on my end, try going to SY Settings > Data and storage, and "Clear cache"
> 
> If that doesn't work, try migrating the title back into Sussy Scan

Tá do mesmo jeito ainda 😓

**Comment by Smol-Ame** [comment]
> Tá do mesmo jeito ainda 😓

Do you have Data Saver enabled in SY Settings > Advanced? I know that could cause issues too. Try turning it off, clearing chapter cache, and restart the app.

**Comment by ghost** [comment]
> > Tá do mesmo jeito ainda 😓
> 
> Do you have Data Saver enabled in SY Settings > Advanced? I know that could cause issues too. Try turning it off, clearing chapter cache, and restart the app.

Muito obrigado pela ajuda
