### ISSUE TITLE
Different JManga Than Already Exists (?)

### ISSUE THREAD

**Issue by cristiannn-b** [keiyoushi/tachiyomi-extensions-source#4519]
### Source name

JManga

### Source link

https://jmanga.org/home/

### Source language

日本語

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by 0Ha16wA5** [comment]
Duplicate of #3337
