### ISSUE TITLE
 Pls fix chinese extension boylove

### ISSUE THREAD

**Issue by Morse069** [keiyoushi/tachiyomi-extensions-source#452]
### Source information

Boylove 1.4.9

### Source language

Chinese

### Steps to reproduce

Jumble image
![Screenshot_2024-01-21-23-40-46-63_afd66b7916d19a60815f56273408b73e](https://github.com/keiyoushi/extensions-source/assets/121346796/6a19941d-fcdb-4080-be72-aa810b345da6)
 in new updated chapter
No issue in the webview
No issue in the past chapter

### Expected behavior

Corrected images

### Actual behavior

![Uploading Screenshot_2024-01-21-23-40-46-63_afd66b7916d19a60815f56273408b73e.jpg…]()

### Tachiyomi version

0.14.0

### Android version

Android 10

### Other details

Same issue in Mihon 0.16.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Duplicate of #254
