### ISSUE TITLE
ethylene scans

### ISSUE THREAD

**Issue by Itsyua** [keiyoushi/tachiyomi-extensions-source#4521]
### Source name

Ethylene scans

### Source link

https://ethylene.mangadex.com/

### Source language

English 

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
this is a blog style website, and they link to MangaDex for actual chapters, read there
