### ISSUE TITLE
Asura scan is not loading 

### ISSUE THREAD

**Issue by ronalhvaldez** [keiyoushi/tachiyomi-extensions-source#4524]
### Source information

Asura scan 

### Source language

English 

### Steps to reproduce

1. Click on asura
2. Http 404

### Expected behavior

It should show the manhwas

### Actual behavior

It doesn't show the manhwas 

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Works fine on my end, come to the Keiyoushi Discord repo-support channel for help/troubleshooting
