### ISSUE TITLE
MangaLib: Not loading images.

### ISSUE THREAD

**Issue by nullcat0ru** [keiyoushi/tachiyomi-extensions-source#4532]
### Source information

MangaLib 1.4.104

### Source language

Russian

### Steps to reproduce

1. Open any title on mangalib.
2. After a couple pages/or almost immediately you'll encounter an error that the images couldn't be loaded.

### Expected behavior

You can read any chapter of any title

### Actual behavior

In app you that it can't load image
On webview you see that access to the mixlib website is restricted. (i.e. I don't have access to it, and it's most likely because the URL where the images are stored has been changed.)
![photo_2024-08-09_14-20-33](https://github.com/user-attachments/assets/e68d61c4-3893-414d-83ef-539b17a082f4)
![photo_2024-08-09_14-20-34](https://github.com/user-attachments/assets/49c0f40a-84d1-40c2-b405-e9f24b1448b7)

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
In the extension settings, switch to the "compress" server (third choice) and clear chapter cache. Their other servers may be broken on their side

**Comment by nullcat0ru** [comment]
> In the extension settings, switch to the "compress" server (third choice) and clear chapter cache

I have done this several times, but, I have now done it again and the error has disappeared as if it never happened, and hence - all images are now displayed. Issue closed, and thanks for your help!
