### ISSUE TITLE
issue in mangaswat source latest tab

### ISSUE THREAD

**Issue by Doo77m** [keiyoushi/tachiyomi-extensions-source#4562]
### Source information

Mangaswat 1.4.51

### Source language

Arabic

### Steps to reproduce

It supposed to appear the latest chapters when click on latest tab

### Expected behavior

It supposed to appear the latest chapters when click on latest tab

### Actual behavior

It appers the last added tittles not chapters

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 

### Other details

Hi everybody
This issue has been around from a while and feel weird that no one talk about this so here I am
The issue is It supposed to appear the latest chapters when click on latest tab but instead it appears the last added tittles
Thanks in advance to whoever steps forward to solve this

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Sinator01** [comment]
أرجو ان تكتب لي تعليقا عندما تجد حلا لهذه المشكلة pleas let a comment when you can fix it 🙏

**Comment by Doo77m** [comment]
> أرجو ان تكتب لي تعليقا عندما تجد حلا لهذه المشكلة pleas let a comment when you can fix it 🙏

ان كنت من فريق التطوير والبرمجة فياليت تساعد😭

**Comment by Doo77m** [comment]
Reopen

**Comment by Smol-Ame** [comment]
Issues are fixed by contributors volunteering their time, there's no guarantee that it'll be fixed/fixed soon. Be patient, otherwise, migrate to a different source

**Comment by Doo77m** [comment]
But nothing changed
Why close as completed

**Comment by Smol-Ame** [comment]
@Doo77m it was fixed. Don't crosspost messages if you don't understand, it's just extra spam & pings to everyone on the issue.

Make sure your extension is updated, otherwise, it's working as intended.

![Screenshot_20240813_005441_Mihon.png](https://github.com/user-attachments/assets/33de78a7-b53e-4c08-9ec8-f8524c3666be)

![20240813_010005.jpg](https://github.com/user-attachments/assets/848f9023-aeed-4bee-85b9-4f04639250a2)

**Comment by Doo77m** [comment]
> @Doo77m it was fixed. Don't crosspost messages if you don't understand, it's just extra spam & pings to everyone on the issue.
> 
> Make sure your extension is updated, otherwise, it's working as intended.
> 
> ![Screenshot_20240813_005441_Mihon.png](https://private-user-images.githubusercontent.com/155411819/357326096-33de78a7-b53e-4c08-9ec8-f8524c3666be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1Mzc0MTIsIm5iZiI6MTcyMzUzNzExMiwicGF0aCI6Ii8xNTU0MTE4MTkvMzU3MzI2MDk2LTMzZGU3OGE3LWI1M2UtNGMwOC05ZWM4LWY4NTI0YzM2NjZiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QwODE4MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03N2QzZjkxMzZjZmYzZWU3M2E3N2NhNmVkNDcxN2QyMGVmNmRlMmEyNTAwYjU2MGY5MjcxZjU3MjUxNWZiYzEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Inq914RxjUi4a2atl5LMcjYV8Jl_O87N1Ce94Ph6F38)
> 
> ![20240813_010005.jpg](https://private-user-images.githubusercontent.com/155411819/357326121-848f9023-aeed-4bee-85b9-4f04639250a2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1Mzc0MTIsIm5iZiI6MTcyMzUzNzExMiwicGF0aCI6Ii8xNTU0MTE4MTkvMzU3MzI2MTIxLTg0OGY5MDIzLWFlZWQtNGJlZS04NWI5LTRmMDQ2MzkyNTBhMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QwODE4MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWM4NTM1YWQ5OWFjMzc1ZDE2NGNiNDI2YmM1Y2Q5NzAzYjg0OGIzYzA0NTI2ZWZhYTA3ZDgxMTg0YzYzOTM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.88sXvkrxoJ2FiZRmbxZfV89Iya6b6PMaXy_9ALT1TLw)

Their search page is not working properly
The new updates appear on the home page, not what you mentioned
If you don’t believe me then check their discord

**Comment by Norsze** [comment]
Then make a new issue for search

**Comment by AwkwardPeak7** [comment]
It's not our problem if their site isn't working

**Comment by Doo77m** [comment]
I already said what I had to say
The rest on you whether if you want fix it or not
Goodbye.
