### ISSUE TITLE
Fox White is down and website is closed

### ISSUE THREAD

**Issue by mariodac** [keiyoushi/tachiyomi-extensions-source#457]
### Source name

Fox White

### Source language

Portuguese Brazil

### Source link

https://foxwhite.com.br/

### Other details

Error displayed: net::ERR_NAME_NOT_RESOLVED
![Screenshot_2024-01-21-13-47-11-540_eu kanade tachiyomi sy](https://github.com/keiyoushi/extensions-source/assets/38120268/ab690d50-d5a7-40ba-a843-5cca3c11eb59)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by domflamingo2** [comment]
Foxwhie está mudando de domínio
