### ISSUE TITLE
Quero pedir adição de um nova fonte no idioma PT Brasileiro 

### ISSUE THREAD

**Issue by SmMoraes** [keiyoushi/tachiyomi-extensions-source#4572]
### Source name

TSUKI

### Source link

https://tsuki-mangas.com/

### Source language

Português Br

### Other details

Sim

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
It's already within the repo, go enable Brazilian Portuguese in the Language Filter for both your Extension tab & Source tab in your app.
