### ISSUE TITLE
ReadComicOnline extension doesnt work 

### ISSUE THREAD

**Issue by TLiley2** [keiyoushi/tachiyomi-extensions-source#4574]
### Source information

1.4.26

### Source language

English 

### Steps to reproduce

1.) Open comic chapter
2.) Page doesn't loads image

### Expected behavior

1.) Open comic chapter
2.) Page loads image

### Actual behavior

1.) Open comic chapter
2.) Page doesn't loads image

### Mihon/Tachiyomi version

0.16.4.3-7801

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of https://github.com/keiyoushi/extensions-source/issues/4115

Search the existing issues before opening a new issue, and acknowledging that you did when you didn't
