### ISSUE TITLE
YANP Fansub (New link)

### ISSUE THREAD

**Issue by KaraSupergirl** [keiyoushi/tachiyomi-extensions-source#4575]
### Source information

Yanp Fansub 1.4.37

### Source language

Portuguese

### Source new URL

https://trisalyanp.com

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
old domain is still working for me

**Comment by kana-shii** [comment]
> old domain is still working for me

the admins are currently deleting the old domain stuff (chapters/manga) and passing them to the new one.
it will only work until they finish moving everything
