### ISSUE TITLE
Diskus Scan (PT-Br Source) No results found.

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#4579]
### Source information

Diskus Scan 1.4.40

### Source language

Portuguese Brazilian 

### Steps to reproduce

When I open the extension it says: No results found.

![Screenshot_2024-08-12-11-59-14-915_app mihon](https://github.com/user-attachments/assets/6ec21dcc-29a7-42f8-b8dd-9bc83f8389a1)

### Expected behavior

Show the contents of the source.

### Actual behavior

It appears: No results found.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nomaxsnx** [comment]
![Screenshot_2024-08-12-12-28-32-964_app mihon](https://github.com/user-attachments/assets/5dbf1ea7-238e-47ef-b994-e60fae2a2600)
![Screenshot_2024-08-12-12-27-19-468_app mihon](https://github.com/user-attachments/assets/be6f0556-9b2c-4f3a-9fda-dff0defa274a)

**Comment by domflamingo2** [comment]
you can still read the saved manhua, but you can't access the extension to add new manhua to the library
