### ISSUE TITLE
Obsolete Extension

### ISSUE THREAD

**Issue by berthzbr** [keiyoushi/tachiyomi-extensions-source#458]
### Source name

Asuracomics

### Source language

English

### Source link

https://asuratoon.com

### Other details

![Screenshot_2024-01-22-00-50-50-005_eu kanade tachiyomi sy-edit](https://github.com/keiyoushi/extensions-source/assets/157305137/82b2c361-a79d-46cc-9ac4-7509949e98e1)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
Uninstall this and install the new asura extension
