### ISSUE TITLE
Mangageko stuck in cloudflare loop

### ISSUE THREAD

**Issue by Hazzardousgamer** [keiyoushi/tachiyomi-extensions-source#4587]
### Source information

MangaGeko 1.4.25

### Source language

English

### Steps to reproduce

Try completing cloudfare test

### Expected behavior

Should pass and get access to website

### Actual behavior

Stuck looping

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Follow the cloudflare guide https://keiyoushi.github.io/docs/guides/troubleshooting#cloudflare
