### ISSUE TITLE
Drope Scan: Website link redirects to invitation on discord

### ISSUE THREAD

**Issue by mariodac** [keiyoushi/tachiyomi-extensions-source#459]
### Source name

Drope Scan

### Source language

Portuguese Brazil

### Source link

https://dropescan.com

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by domflamingo2** [comment]
Drop Scan, não caiu, apenas estão fazendo novo site, mas de qualquer forma vai muda tudo ate o tema do site, irei deleta.
