### ISSUE TITLE
No puedo instalar una extension

### ISSUE THREAD

**Issue by Striven100** [keiyoushi/tachiyomi-extensions-source#4590]
### Source information

LeerCapitulo

### Source language

Español

### Steps to reproduce

No puedo instalar la extension apk de leercapitulo.com

### Expected behavior

Puedo instalar todas las demas, y tengo el idioma de español bien config

### Actual behavior

![Screenshot_20240812-123502_Package installer](https://github.com/user-attachments/assets/dc2ed9c4-78d2-4eb2-8e3c-f5c2500b7663)

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
As Awkward told you __two__ months ago, come to the __Keiyoushi Discord server, repo-support channel__ for help with this issue. It makes it easier to communicate.

![Screenshot_20240812_095405_Firefox Nightly](https://github.com/user-attachments/assets/93b2f22c-da48-43ba-98fa-ceba8f4d9975)

**Comment by AwkwardPeak7** [comment]
https://discord.gg/keiyoushi
