### ISSUE TITLE
Diskus Scan. (PT-Br Source) No results found (again)!

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#4592]
### Source information

Diskus Scan 1.4.41

### Source language

Portuguese Brazilian 

### Steps to reproduce

When opening the source, result not found appears.
![Screenshot_2024-08-12-22-56-30-311_app mihon](https://github.com/user-attachments/assets/d065febe-aed9-4b40-9ea7-e824564d4ced)

### Expected behavior

Show the contents of the source.

### Actual behavior

Shows content not found.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by EvaldoCeBr** [comment]
@ch

**Comment by AwkwardPeak7** [comment]
@EvaldoCeBr don't ping random people or contributors

**Comment by Pedropaulo015** [comment]
Também tá acontecendo comigo não tá carregando nada só na webvew

**Comment by EvaldoCeBr** [comment]
Precisamos de ajuda!
