### ISSUE TITLE
Blackout Comics (PT-Br Source), No results found.

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#4600]
### Source information

Blackout Comics 1.4.6

### Source language

Portuguese Brazilian 

### Steps to reproduce

Even when logging into the source settings, the message appears: No results found.
![Screenshot_2024-08-13-15-10-29-541_app mihon](https://github.com/user-attachments/assets/4a59293c-17dd-46d4-81b1-f5750528ee3a)
![Screenshot_2024-08-13-15-10-09-248_app mihon](https://github.com/user-attachments/assets/7f1a3f01-75d1-4bef-a47b-21be5633dfae)

### Expected behavior

View Source files.

### Actual behavior

Can't access the files.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by viminio** [comment]
The reason for this error is that the login stopped working

**Comment by EvaldoCeBr** [comment]
> The reason for this error is that the login stopped working 

The same error is occurring in another source that does not have a login and password to enter.

**Comment by Yukizi** [comment]
For me the login works. The chapters are updated normally but it is not possible to open any chapters.

**Comment by EvaldoCeBr** [comment]
> For me the login works. The chapters are updated normally but it is not possible to open any chapters.

Sim da pra por a senha direto nas configurações da fonte. E as obras salvas atualizam, mas não aparecem obras na fonte. A Diskus também está com o mesmo problema!

**Comment by EvaldoCeBr** [comment]
Precisamos de ajuda!

**Comment by viminio** [comment]
> > For me the login works. The chapters are updated normally but it is not possible to open any chapters.
> 
> Sim da pra por a senha direto nas configurações da fonte. E as obras salvas atualizam, mas não aparecem obras na fonte. A Diskus também está com o mesmo problema!

Rename this issues to Login fix not work
