### ISSUE TITLE
Infernal Void Scans has changed layout (again) 

### ISSUE THREAD

**Issue by lcd047** [keiyoushi/tachiyomi-extensions-source#4603]
### Source information

Infernal Void Scans 1.4.38

### Source language

English

### Steps to reproduce

List all manga or latest manga. Also update a manga already in library. 

### Expected behavior

WebView works fine, so the actual lists should be returned. Updating an existing manga should also work. 

### Actual behavior

The lists returned are empty. Updating an existing manga returns 404.

### Mihon/Tachiyomi version

TachiyomiSY Preview r562

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Open one of their manga pages in WebView/your own browser

**Comment by lcd047** [comment]
Ah, it seems to be broken on server side, sorry.
