### ISSUE TITLE
Oppai Stream Subtitles No Longer Working

### ISSUE THREAD

**Issue by kam712398** [keiyoushi/tachiyomi-extensions-source#4605]
### Source information

Oppai Stream 14.4

### Source language

English

### Steps to reproduce

1. Start video 2. Check option and audio tab

### Expected behavior

There use to be subtitles that existed here.

### Actual behavior

Subtitles aren't there anymore

### Mihon/Tachiyomi version

Aniyomi preview R7801

### Android version

Android 14

### Other details

I am assuming they changed the implementation of how they use subtitles on oppai stream.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Keiyoushi doesn't have any anime extensions

**Comment by kam712398** [comment]
Sorry, I just realized I went to the wrong repo.
