### ISSUE TITLE
Blacktoon (KO)

### ISSUE THREAD

**Issue by davidfelipesanto** [keiyoushi/tachiyomi-extensions-source#4607]
### Source name

Blacktoon

### Source link

https://blacktoon315.com/

### Source language

Korean

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
@davidfelipesanto Why'd you put the repo link as the source request title? Change it to something better/more relevant

Also, does the site even work? Or is it region-locked for Korea or something? I'm unable to view any pictures/chapters on the site

**Comment by Smol-Ame** [comment]
@davidfelipesanto stop opening duplicate issues, fix the title in this one and wait.
