### ISSUE TITLE
Ama website scans is down displaying error net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by mariodac** [keiyoushi/tachiyomi-extensions-source#461]
### Source name

Ama scan

### Source language

Portuguese Brazil

### Source link

https://amascan.com

### Other details

![Screenshot_2024-01-21-13-58-47-383_eu kanade tachiyomi sy](https://github.com/keiyoushi/extensions-source/assets/38120268/42a6d267-c6af-4d02-82ae-91fe49c05f28)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by domflamingo2** [comment]
Website down
