### ISSUE TITLE
SlimeRead: HTTP 502

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#462]
### Source information

SlimeRead  1.4.2

### Source language

Português (Brasil)

### Steps to reproduce

Erro HTTP 502

![Screenshot_20240121-141953](https://github.com/keiyoushi/extensions-source/assets/157044539/327cdeaf-d168-423e-acc8-b829624e444e)

### Expected behavior

.

### Actual behavior

.

### Tachiyomi version

1.10.2

### Android version

Android 11

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by domflamingo2** [comment]
![Screenshot_2024-01-21-14-59-13-303_app mihon](https://github.com/keiyoushi/extensions-source/assets/75938421/c6ed955b-6be1-48d6-a3dd-ed0d1f0fe111)


Its work for me
