### ISSUE TITLE
Problem with opening chapters leercapitulo

### ISSUE THREAD

**Issue by Scaredeadth** [keiyoushi/tachiyomi-extensions-source#4628]
### Source information

1.4.9

### Source language

Español 

### Steps to reproduce

Opening any chapter, whether old or new, as well as accessing the page from the application, the error occurs.
![Screenshot_2024-08-14-14-29-02-679_eu kanade tachiyomi](https://github.com/user-attachments/assets/906eae0d-1f6f-420a-aa25-2f3d8cc1dec2)
![Uploading Screenshot_2024-08-14-14-28-54-286_eu.
![Screenshot_2024-08-14-14-28-54-286_eu kanade tachiyomi](https://github.com/user-attachments/assets/aea65c1a-58d2-4f59-b17c-e65fc57d97b7)
kanade.tachiyomi.jpg…]()

### Expected behavior

Load the chapter or chapters, the main page is checked from browsers and no error occurs 

### Actual behavior

The extension loads the pages correctly and when accessing the browser, it also shows the selected chapter.

### Mihon/Tachiyomi version

0.15.3

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Related #4627

**Comment by Yvlion21** [comment]
@Scaredeadth 
Me podrías decir el nombre de tu fuente de tipografía que tienes en la imagen que compartiste o donde conseguirlo, gracias.
Could you tell me the font that you use in the image you share? Or where do I can find it? Thanks

**Comment by Scaredeadth** [comment]
:v @Yvlion21 se llama ROBLOX 
![Screenshot_2024-08-14-20-37-02-055_com android thememanager](https://github.com/user-attachments/assets/6f379af2-ad37-4110-9cd8-1e23c9d83aae)

**Comment by Yvlion21** [comment]
> :v @Yvlion21 se llama ROBLOX ![Screenshot_2024-08-14-20-37-02-055_com android thememanager](https://private-user-images.githubusercontent.com/128567481/358064151-6f379af2-ad37-4110-9cd8-1e23c9d83aae.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTIwMTgsIm5iZiI6MTcyMzY5MTcxOCwicGF0aCI6Ii8xMjg1Njc0ODEvMzU4MDY0MTUxLTZmMzc5YWYyLWFkMzctNDExMC05Y2Q4LTFlMjNjOWQ4M2FhZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQwMzE1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzNkM2U5NDYwYjgwOWQwMzRkNTRjZGEwNzkzNjQ5ODE5NmMwNDNjNTViZDE1ZGRmMjJhNGMwMWM4Zjc4MjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LNHvkMmp4mE2xDXG-45R6KpdRwrq2YB61uxq-Yu2Nt4)

Gracias!! 
Thanks!!
