### ISSUE TITLE
Dead sources

### ISSUE THREAD

**Issue by mariodac** [keiyoushi/tachiyomi-extensions-source#463]
### Describe why this should be added

**Source name**
Animaregia

**Source language**
Portuguese Brazil

**Source link**: https://animaregia.net/

Animaregia website is down with error 502

![Screenshot_2024-01-21-14-01-54-481_eu kanade tachiyomi sy](https://github.com/keiyoushi/extensions-source/assets/38120268/d538d825-b75c-4dd9-a1ec-91e04b3ece5a)

---

**Source name**
Baixarhentai

**Source language**
Portuguese Brazil

**Source link**: https://leitura.baicarhentai.net

Baixarhentai is down and redirects to another websites

https://github.com/keiyoushi/extensions-source/assets/38120268/0a89382d-252a-405c-b394-5e4174f76e8a

---

**Source name**
Hentaisphere

**Source language**
English 

**Source link**: https://hentaisphere.com/

Hentaisphere website is not available, error: net::ERR_SSL_UNRECOGNIZED_NAME_ALERT

![Screenshot_2024-01-21-14-10-50-780_eu kanade tachiyomi sy](https://github.com/keiyoushi/extensions-source/assets/38120268/2596d2f2-1a5f-4fb0-9677-0c5dc93225d7)

---

**Source name**
projetoscanlator.

**Source language**
Portuguese Brasil 

**Source link**: https://projetoscanlator.com

projetoscanlator website is down with error 502

![Screenshot_2024-01-21-14-46-28-859_eu kanade tachiyomi sy](https://github.com/keiyoushi/extensions-source/assets/38120268/c077ddd0-ba72-4e0a-b849-b39ead3b917d)

---

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by domflamingo2** [comment]
AnimaRagia commit #447

**Comment by mariodac** [comment]
> AnimaRagia commit #447

"Animaregia" not "animaragia"

**Comment by domflamingo2** [comment]
O bot definiou como "not planned", kkkkkkk, depois eu deleto as extensões .

**Comment by mariodac** [comment]
> O bot definiou como "not planned", kkkkkkk, depois eu deleto as extensões .

Já abri uma duas separado

**Comment by domflamingo2** [comment]
> > O bot definiou como "not planned", kkkkkkk, depois eu deleto as extensões .
> 
> Já abri uma duas separado

Sim, de qualquer jeito, os cara demora 1 anos pra fazer isso.
