### ISSUE TITLE
ReadComicOnline extension keeps saying HTTP error 404

### ISSUE THREAD

**Issue by shane-kanyi** [keiyoushi/tachiyomi-extensions-source#4634]
### Source information

ReadComicOnline

### Source language

English 

### Steps to reproduce

1. Download an issue of a comic from ReadComicOnline source or click on it to view 
 

### Expected behavior

The issue is downloaded and/or I can view the issue.

### Actual behavior

The download doesn't happen and I get an error notification saying HTTP Error 404 
When trying to view it says cannot fetch pages and when I click on webview it says HTTP Error 404

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #4115

Search the existing issues for before opening a new one, and acknowledging that you did
