### ISSUE TITLE
It's having issues with human verification page 

### ISSUE THREAD

**Issue by Novaboy007** [keiyoushi/tachiyomi-extensions-source#4638]
### Source information

Toongod 

### Source language

English 

### Steps to reproduce

Has per the instructions given on website I have performed it but the human verification page of toongod gets stuck on it and keep getting reload again and again till it  shows error due to slow internet connection even I have high internet 5G connection 

### Expected behavior

It should start working like other extensions 

### Actual behavior

Has mentioned above 

### Mihon/Tachiyomi version

App version: 0.16.5 

### Android version

Android version: 14

### Other details

None 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
It does work like any other extension. Cloudflare/sources can change what user-agent they block whenever they want. Follow the Cloudflare guide, either through the giant button at the top (see picture below), or through the Keiyoushi Website's [troubleshooting guide](https://keiyoushi.github.io/docs/guides/troubleshooting#cloudflare)

![Screenshot_20240815_093347_Mihon](https://github.com/user-attachments/assets/539403b4-ca10-4800-b49d-22bd54ac5feb)
