### ISSUE TITLE
mangayaro change url

### ISSUE THREAD

**Issue by VQA-06** [keiyoushi/tachiyomi-extensions-source#4651]
### Source information

mangayaro 1.4.31

### Source language

Indonesia

### Source new URL

https://mangayaro.id/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Their site is down or deleted, check in your own browser. Nothing we can do.

![Screenshot_20240816_122825_Firefox Nightly](https://github.com/user-attachments/assets/ef24ce59-03bb-48c0-9574-896c4dd330fd)
