### ISSUE TITLE
Gölge Bahçesi missing manga list issue

### ISSUE THREAD

**Issue by Forza06** [keiyoushi/tachiyomi-extensions-source#4662]
### Source information

Gölge Bahçesi 1.4.30

### Source language

Turkish

### Steps to reproduce

1- I click on the most recently uploaded episodes
2- The listed mangas are incomplete, the mangas on the site are more

### Expected behavior

only adult mangas on the site are listed in the app 

### Actual behavior

all mangas should be listed 

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
The extension just shows what the site shows, and the extension is pulling the data from `/manga/?status=&type=&order=update`.

If that's not correct, is there a better page to get the list of updated manga from?
