### ISSUE TITLE
Mangasee not working 

### ISSUE THREAD

**Issue by Rinhak** [keiyoushi/tachiyomi-extensions-source#4663]
### Source information

Mangasee 1.4.36

### Source language

English

### Steps to reproduce

1. Open any manga from Mangasee source
2. After opening it crashes saying "HTTP Error 502."

### Expected behavior

Chapters would open normally.

### Actual behavior

Crashes showing "HTTP Error 502".

### Mihon/Tachiyomi version

0.16.5 (Mihon)

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
5xx errors are server side, nothing we can do about it. also they are back now
