### ISSUE TITLE
Girls Love Manga! - Dead Site.

### ISSUE THREAD

**Issue by Eagle1337** [keiyoushi/tachiyomi-extensions-source#468]
### Source name

Girls Love Manga!

### Source language

English

### Source link

Girls Love Manga!

### Other details

The Site is dead,  Tachi pulls a 404,  web view/browser pulls a 403.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
It's back up, although there's no content on the site. Closing.
