### ISSUE TITLE
AnimeXnovel

### ISSUE THREAD

**Issue by paz-web** [keiyoushi/tachiyomi-extensions-source#4687]
### Source name

AnimeXnovel 

### Source language

PT BR

### Source link

https://www.animexnovel.com/

### Other details

O site deles está normal mais a extensão não tá funcionando 

![Screenshot_20240818-215216](https://github.com/user-attachments/assets/925e6e61-5c23-4d3b-90b0-e043e4ae962e)
![Screenshot_20240818-215221](https://github.com/user-attachments/assets/efd8ab83-bd99-4b99-9bcd-2a150233be6b)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Someone will change it later (not sure if you can), but this would be an issue request rather than a "Source is down"/dead source report. It would be a dead source report if the site is deleted or stopped working outside of the extension.
