### ISSUE TITLE
Solicitar login, error de login 

### ISSUE THREAD

**Issue by Leon0000oooo** [keiyoushi/tachiyomi-extensions-source#4698]
### Source name

blackoutcomics 1.4.6

### Source language

Português PT-BR

### Describe your suggested feature

Preciso entrar no WebView e fazer login no site para  ter acesso aos mangas, o site está exigindo login e sempre que tenho logar, dar erro e eu já tentei de várias soluções cabíveis que aprendi aqui no suporte, e não consegui arrumar.
![Screenshot_2024-08-20-17-38-09-193_app mihon](https://github.com/user-attachments/assets/0ca1a7c0-62d8-4b0b-8397-5843bec1711e)
![Screenshot_2024-08-20-17-38-31-318_app mihon](https://github.com/user-attachments/assets/c3114644-8119-4569-892a-f2671886f828)

### Other details

Agradeço o maravilhoso trabalho que vem fazendo. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
Duplicate: #4600
