### ISSUE TITLE
Mantraz scan: The domain of the page changed 

### ISSUE THREAD

**Issue by Senkunsito** [keiyoushi/tachiyomi-extensions-source#4708]
### Source information

Matraz scan 1.4.38

### Source language

Spanish

### Source new URL

 https://artessupremas.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
The old domain still works. Did they announce somewhere that they were moving?
