### ISSUE TITLE
MangaSwat URL Change 

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#4711]
### Source information

"ar.mangaswat 1.4.52"

### Source language

"Arabic"

### Source new URL

"https://healteer.com/"

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
For those who are waiting for the extension to update the baseURL in the extension:

You can manually override it in the extension's settings yourself, so you can continue to use the extension until it gets updated.

* Go to your Browse Page > Extensions tab > MangaSwat settings, and override the URL with the one mentioned above.
* Restart your app after applying the new URL, so the change takes effect.

**Comment by ghost** [comment]
Not working and can't read anything

**Comment by Smol-Ame** [comment]
They've changed links again, https://healteer.com, that's why when you open the source in WebView, they redirect you to a Google search of their new name. Don't be lazy, and there's a reason why you can override the URL in the extension's settings. Follow the steps above whenever this happen, but put the new link into the override & restart the app.

Works on my end

**Comment by ghost** [comment]
Ok got it

**Comment by Smol-Ame** [comment]
Keep the issue open, so whoever has this issue can see how to temporarily fix it. Also, whenever a contributor has the time can see the open issue & update the link.

Just edit your request with the new URL
