### ISSUE TITLE
Animated glitch Scans are changing site to agscomics

### ISSUE THREAD

**Issue by AryanMithbawkar** [keiyoushi/tachiyomi-extensions-source#4718]
### Source name

Animated glitch scans

### Source language

English 

### Source link

https://anigliscans.xyz/

### Other details

They have changed their site to https://agscomics.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Achuabdu** [comment]
![Screenshot_2024-08-23-05-48-45-963_com android chrome](https://github.com/user-attachments/assets/daf8da31-ccb0-460b-b450-c0313176eae7)

**Comment by Achuabdu** [comment]
It's not changed they made two separate websites

**Comment by AryanMithbawkar** [comment]
![IMG_20240824_214026](https://github.com/user-attachments/assets/ba05ba90-ccff-46fa-aae6-f42f2411718a)
pointing to new site

**Comment by AryanMithbawkar** [comment]
No they may be closing old one as no manhua is uploading on it just one slide
