### ISSUE TITLE
The Anitube extension has stopped working on Aniyomi. But the site is still up. 

### ISSUE THREAD

**Issue by Rafilipes** [keiyoushi/tachiyomi-extensions-source#4723]
### Source name

https://raw.githubusercontent.com/almightyhak/aniyomi-anime-repo/main/index.min.json

### Source language

Português Brasil - PT-BR 

### Source link

https://www.anitube.vip/

### Other details

![LDPlayer 23_08_2024 06_41_57](https://github.com/user-attachments/assets/7f72206a-226d-4427-a9e0-cd96438e2bd4)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
1) That's not our repo & don't share third-party repos here
2) That's not our extension, and Keiyoushi doesn't do anime extensions

**Comment by Rafilipes** [comment]
> 1. Este não é nosso repositório e não compartilhe repositórios de terceiros aqui
> 2. Essa não é nossa extensão, e Keiyoushi não faz extensões de anime

I'm sorry I made a mistake in the creators
