### ISSUE TITLE
Source Manga Dõjõ not yet added

### ISSUE THREAD

**Issue by Rafilipes** [keiyoushi/tachiyomi-extensions-source#4724]
### Source name

Mangá Dõjõ 

### Source link

https://mangadojo.netlify.app/

### Source language

Português Brasil - PT-BR 

### Other details

![Captura de ecrã 2024-08-23 070156](https://github.com/user-attachments/assets/e5df5de2-3042-4c38-b465-a383a926d6f5)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
They link to mangadex for actual chapters, so use that extension
