### ISSUE TITLE
Hunters Scans (PT-Br Source) change url.

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#4726]
### Source information

Hunters Scans 1.4.39

### Source language

Portuguese Brazilian 

### Steps to reproduce

It doesn't show all the works. And the ones it does show are repeated!

### Expected behavior

See all works.

### Actual behavior

It only shows some works and repeats in the source.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by domflamingo2** [comment]
![image](https://github.com/user-attachments/assets/a2a5f48f-49db-4c02-9cc9-83bf56c643d5)

PT: por favor troca o titulo acima, pois eles trocaram de domínio e na labels coloca: "domain change".
EN: please change the title above, as they have changed domains and the labels say: “domain change”.
