### ISSUE TITLE
SetsuScans Imaizumi series

### ISSUE THREAD

**Issue by user1705** [keiyoushi/tachiyomi-extensions-source#4736]
### Source information

Setsu Scans 1.4.38

### Source language

English

### Source new URL

https://kurumizaka.online/

### Other details

WebView link;
https://setsuscans.com/manga/imaizumins-house-is-a-place-for-gals-to-gather/
![image](https://github.com/user-attachments/assets/e0bfd4f7-f42b-4f9f-b102-fd282a6f9c3c)

Redirect to;
https://kurumizaka.online/
![image](https://github.com/user-attachments/assets/1d3be1c5-8aca-4af3-9a0c-6529b11ae69e)

P/S: ONLY Imaizumi series is affected as the other manga on SetsuScans works fine.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Can't reproduce the issue. Maybe it was an ad redirect? The series works fine in the extension and through WebView for me.
