### ISSUE TITLE
Add Comikey.com (free episodes)

### ISSUE THREAD

**Issue by Snyret** [keiyoushi/tachiyomi-extensions-source#474]
### Source name

Comikey

### Source link

comikey.com

### Source language

Multi

### Other details

18+/NSFW= No

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by SnakeDoc83** [comment]
Do you mean comikey.com? Because comickey doesn't seem right.

**Comment by Snyret** [comment]
> Do you mean comikey.com? Because comickey doesn't seem right.

Yep, sorry about the typo
