### ISSUE TITLE
Godamanga

### ISSUE THREAD

**Issue by Bipolar708** [keiyoushi/tachiyomi-extensions-source#475]
### Source name

Godamanga

### Source link

https://godamanga.art/ or https://en.baozimh.org/

### Source language

English

### Other details

Please🙏anybody

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by dngonz** [comment]
There is already a [source](https://keiyoushi.github.io/extensions/#en.goda) for that, https://godamanga.art/  is like a news web site and [en.baozimh.org/](https://en.baozimh.org/) redirects to [https://manhuascans.org/](https://manhuascans.org/)
