### ISSUE TITLE
ReadAllComics lacks Latest feature

### ISSUE THREAD

**Issue by goofyahhbaby** [keiyoushi/tachiyomi-extensions-source#4750]
### Source name

ReadAllComics

### Source language

English

### Describe your suggested feature

The ReadAllComics source doesn't have a Latest option like most sources. It loads fast and they're all in high quality. The Latest option would make it the perfect source. It would be great if it were added one day.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
The website doesn't have a popular comics section, so popular in app gives latest comics.

**Comment by Smol-Ame** [comment]
They don't have a latest section/their site's search can't filter.

Plus, seems like it's already the site's Latest with the homepage being recently updated.

![Screenshot_20240824_224829_Mihon.png](https://github.com/user-attachments/assets/f6f24259-3e1d-4422-8140-c8f9bef67d62)

![20240824_224838.jpg](https://github.com/user-attachments/assets/49d2dedc-8c1e-4874-b563-3bd9b8014342)
