### ISSUE TITLE
Mantraz Scan (ES) URL change

### ISSUE THREAD

**Issue by JSebastianMarin** [keiyoushi/tachiyomi-extensions-source#4759]
### Source information

Mantraz Scan 1.4.38

### Source language

Spanish

### Source new URL

https://artessupremas.com/

### Other details

Mantraz Scan (ES) URL change to https://artessupremas.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LordPoc** [comment]
Duplicated issue #4708
