### ISSUE TITLE
Mangakakalot

### ISSUE THREAD

**Issue by kutemeikito** [keiyoushi/tachiyomi-extensions-source#4769]
### Source name

Mangakakalots (unoriginal)

### Source language

English

### Source link

https://ww8.mangakakalot.tv/

### Other details

Domain has changed to 
https://ww8.mangakakalot.tv/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Achuabdu** [comment]
U have to change the label to source request

**Comment by Achuabdu** [comment]
The only source of mangakakalot which is down now is mangakakalots(unoriginal)1.4.6.  (Mangakakalots.com)

**Comment by Achuabdu** [comment]
> The only source of mangakakalot which is down now is mangakakalots(unoriginal)1.4.6. (Mangakakalots.com) I think u r updateing this extension

**Comment by kutemeikito** [comment]
ahh my bad

im updated the mangakaklot

**Comment by kutemeikito** [comment]
should i update in mangakakalots?

**Comment by Achuabdu** [comment]
> should i update in mangakakalots?

I think it will be better

**Comment by kutemeikito** [comment]
got it

**Comment by Achuabdu** [comment]
> got it

Thanks

**Comment by kutemeikito** [comment]
i've updated, you can see on pr

**Comment by Achuabdu** [comment]
Tnxs
