### ISSUE TITLE
Manga demon 

### ISSUE THREAD

**Issue by Sundogg17** [keiyoushi/tachiyomi-extensions-source#4770]
### Source information

Manga demon  1.4.12

### Source language

English 

### Steps to reproduce

Open repo, nothing displays. 
Go to webview, it works.
Individual titles also do not open

![Screenshot_20240826_085610_TachiyomiJ2K](https://github.com/user-attachments/assets/e9b4d12a-f1ff-4199-ac3d-96522d4e75fb)

![Screenshot_20240826_085614_TachiyomiJ2K](https://github.com/user-attachments/assets/2a5059dd-40fc-45f2-a7e8-820e319b2242)

### Expected behavior

Open and see mangas

### Actual behavior

Shows no results

### Mihon/Tachiyomi version

Tachij2k 1.74 

### Android version

17

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by LordPoc** [comment]
Domain Change
Old = https://mgdemon.org
New = https://demonicscans.org/

**Comment by Spectrald** [comment]
Follow up please

**Comment by Sundogg17** [comment]
Are you asking me?

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by LordPoc** [comment]
The site is changed how it works, and thus it is not a simple domain change. I can't fix this, thus someone else needs to do it.

**Comment by Sundogg17** [comment]
Umm it looks like the domain name changed. https://demonicscans.org/

I'm not 100% sure how to answer the rest. On the app when u open manga demon, it doesn't display anything, while webview works normal.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by LordPoc** [comment]
Yes, the domain is changed, but the way you go through the website is also different. And I am not experienced enough to change it to the point it works.

**Comment by Sundogg17** [comment]
Ohh, is there someone who can tag team this?

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Norsze** [comment]
Guys, this comment section is for development talk. Or getting more info on an issue. If you don't know how to make an extension or have anything to add to the issue, just wait and don't fill up the chat, we (the moderators) can see you making non productive comments.

Wait for someone who can fix it, they will find it themselves, make a PR and close this issue. 

Your contribution, if you don't know extension development and you don't have any more info to add, ends at "make an issue report".
