### ISSUE TITLE
Extension HentaiZone 

### ISSUE THREAD

**Issue by DariusPrime2** [keiyoushi/tachiyomi-extensions-source#4771]
### Source information

HentaiZone 1.4.33

### Source language

Français 

### Steps to reproduce

1- J'installe l'extension en question. Je vais dans ''souces'' et je l'ouvre. Rien ne s'affiche. Ça tourne mais ne charge pas les scan

### Expected behavior

Cela devrait normalement charger les scan sur l'extension avec leur chapitre

### Actual behavior

Au lieu de cela, l'extension ne charge aucun webtoon. Ça ne montre rien après avoir tourné et tourné plusieurs secondes 

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Hello, 
Tu as pensé à suivre ce qui est indiqué dans le [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/), notamment la partie user agent ? Tu dois être bloqué par Cloudflare, essaie d'ouvrir le site en WebView également => Si le site s'ouvre en WebView (si tu passes Cloudflare) c'est bon signe, sinon essaie d'autres user agent. Fin bref, essaie d'abord user agent et puis si ça ne marche pas, essaie d'autres choses dans le troubleshooting guide.
En tout cas, l'extension marche niquel.

**Comment by DariusPrime2** [comment]
J'ai essayé tout ça mais ça ne marche pas. Quand j'entre dans le WebView ça tourne en rond sur le recapchat.

**Comment by KirinRaikage** [comment]
Continue d'essayer d'autres user agents, c'est la clé pour passer le recaptcha pour cette extension.

**Comment by DariusPrime2** [comment]
Comment changer d'autres agents ?

**Comment by KirinRaikage** [comment]
C'est indiqué dans le guide

**Comment by DariusPrime2** [comment]
Troubleshooting guide c'est ça ?

**Comment by KirinRaikage** [comment]
Oui, regarde le premier message que j'ai envoyé ^^
