### ISSUE TITLE
Reaper Scans no pages error but webview works

### ISSUE THREAD

**Issue by Koinzell234** [keiyoushi/tachiyomi-extensions-source#4775]
### Source information

Reaper Scans 1.4.54

### Source language

English

### Steps to reproduce

1. Click new chapter. (Solo Resurrection is what I was trying to read)
2. No pages error pops up
3. Click webview 
4. Webview works fine as if no issue

### Expected behavior

Clicking new chapter loads the chapter.

### Actual behavior

Clicking new chapter gives no pages error.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android  version 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Ericcrash** [comment]
Seems like chapters uploaded before today load fine, but new chapters get the error
