### ISSUE TITLE
Quero a adição de uma extenção

### ISSUE THREAD

**Issue by Erickghj** [keiyoushi/tachiyomi-extensions-source#4777]
### Source name

Manga Oline

### Source link

https://mangaonline.biz/

### Source language

Português Brasil-PT-BR

### Other details

![Screenshot_20240826_174423_Chrome Beta](https://github.com/user-attachments/assets/a8e87bae-f987-4079-87e1-a9f2f99d3bdb)
![Screenshot_20240826_174106_Mihon](https://github.com/user-attachments/assets/20af9d8f-f918-4222-b91b-a2d778e07af6)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Read what the bot said, and actually search the existing extensions as mentioned in the acknowledgments, when you clearly didn't.

* Make sure you have Brazilian Portuguese language enabled for both your Sources tab & Extensions tab
* Make sure you have 18+ sources enabled in Mihon Settings > Browse page
* In your Mihon screenshot (in #4776), you wrote the link incorrectly, but usually you should just search the extension name (in your case, Manga Online)
