### ISSUE TITLE
Omega Scans: Premium Chapter Toggle or Auto Detect

### ISSUE THREAD

**Issue by SodiumPoisoning** [keiyoushi/tachiyomi-extensions-source#4786]
### Source name

Omega Scans

### Source language

English

### Describe your suggested feature

Currently, early access chapter do not appear in app even if you are logged in and have premium access.

If there was a toggle in settings so they would show up or a way it could auto detect that you have access to the chapters, that would be great.

I know other extensions (The Blank?) do the second option by default.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
There is a setting to display paid chapters, you would have to login through the username/password in settings 

![Screenshot_20240827-162320_Yōkai](https://github.com/user-attachments/assets/7dca2237-0090-4d66-9ed1-5176b93e7c88)

> I know other extensions (The Blank?) do the second option by default.

That wasn't intentionally made that way, interesting...
