### ISSUE TITLE
Rio2 Manga Dead Source

### ISSUE THREAD

**Issue by usuratonkachii** [keiyoushi/tachiyomi-extensions-source#4792]
### Source name

Rio2 Manga

### Source language

English

### Source link

https://rio2manga.net/

### Other details

Source dead or moved.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Already removed in #4622, it should show as 'obsolete' if you have it installed and you have added the right repo. Obsolete extensions should be uninstalled as they might cause issues.
