### ISSUE TITLE
6manhua  not working properly

### ISSUE THREAD

**Issue by hsiayuchih** [keiyoushi/tachiyomi-extensions-source#4805]
### Source information

1.4.10

### Source language

chinese

### Steps to reproduce

The comic won't load properly, it shows “No pages found”, but it normal display in the webview!
![1](https://github.com/user-attachments/assets/3d25f6d7-bff0-4f14-adf3-7932beee6df6)
![2](https://github.com/user-attachments/assets/004a467f-100e-4f69-9f77-31756cf82bfa)

### Expected behavior

normal display

### Actual behavior

not working properly

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by hsiayuchih** [comment]
@AlphaBoom  Can you help me see what's causing this, please?🙏

**Comment by Smol-Ame** [comment]
@hsiayuchih don't ping contributors to bump your issue request. Contributors volunteer their own time & willingness to look and fix any issues they see fit, and aren't required to work on any specific issues.

Wait patiently or migrate to a different source, don't beg.

**Comment by hsiayuchih** [comment]
> @hsiayuchih don't ping contributors to bump your issue request. Contributors volunteer their own time & willingness to look and fix any issues they see fit, and aren't required to work on any specific issues.
> 
> Wait patiently or migrate to a different source, don't beg.

Okay, thanks.
It's a shame there isn't a proper tutorial for this, otherwise I think I could try to do the fix myself or add the sources I want!
