### ISSUE TITLE
Argos comic error SSL

### ISSUE THREAD

**Issue by nomaxsnx** [keiyoushi/tachiyomi-extensions-source#4812]
### Source information

Argos Comic 1.4.40

### Source language

Português

### Steps to reproduce

1 install the extension Argos Comic
2 Search Pico Marcial
3 Reload manhua

### Expected behavior

![Screenshot_2024-08-28-10-46-18-031_app mihon](https://github.com/user-attachments/assets/63c8fa33-30c0-4199-ae8c-d1626e06a15a) 

### Actual behavior

Error SSL

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
Works when the webview is opened first

**Comment by nomaxsnx** [comment]
> Works when the web view is opened first

Mesmo acessando o web view acontece esse error ainda, pelo pico Marcial acontece, os outro ainda não sei

**Comment by EvaldoCeBr** [comment]
Aqui tb ta dando erro!
