### ISSUE TITLE
Xoxo Comics isn't loading images. 

### ISSUE THREAD

**Issue by Redeyesinferno** [keiyoushi/tachiyomi-extensions-source#4814]
### Source information

XOXO Comics 1.4.9

### Source language

English

### Steps to reproduce

1. Open up whatever Series in the extension.
2. Click whichever Chapter.
3. Image doesn't load.

### Expected behavior

It should load the Issue images.

### Actual behavior

It shows that the images can't be loaded.

### Mihon/Tachiyomi version

Mihon v0.16.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ScottMorris1927** [comment]
Can confirm issue as well.

**Comment by valos** [comment]
Weird. Images are received correctly, but the HTTP status code is incorrect (404 instead of 200).

**Comment by ruipmfernandes** [comment]
I confirm this issue

**Comment by Teosas** [comment]
confirm as weel

**Comment by Smol-Ame** [comment]
Stop commenting here if you don't have any extra info/details that will help a contributor.

Unnecessary messages that email every user on this issue request, and pings the Keiyoushi Discord channel
