### ISSUE TITLE
Mangahere http error 500

### ISSUE THREAD

**Issue by masdabazz** [keiyoushi/tachiyomi-extensions-source#4819]
### Source information

Mangahere 1.4.19

### Source language

English

### Steps to reproduce

Update any mangahere entry

### Expected behavior

Update entry with no problems

### Actual behavior

Comes up with HTTP error 500, yet when I open entry in webview it comes up with it

### Mihon/Tachiyomi version

0.16.5

### Android version

Andriod 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by valos** [comment]
Have you tried to change user agent?
https://mihon.app/docs/guides/troubleshooting/#changing-your-user-agent

**Comment by masdabazz** [comment]
yes that doesnt work

**Comment by masdabazz** [comment]
its seems to be a new website url, because in the webview it says that its taking me to a new mangahere.

**Comment by masdabazz** [comment]
so im guessing thats something that has to be changed on your side?

**Comment by Smol-Ame** [comment]
Here's a temporary workaround to this issue:
* Open Mangahere in WebView
* In WebView, it should give you two pop-ups, close the first pop-up & the second pop-up should be about redirecting to the "new Mangahere", go to the new Mangahere
* Back out of WebView and the results should load in the Latest/Popular tab, along with chapters
* If the chapters in the entry don't load, refresh the chapter list, or check their website to see if they have deleted the chapters during their website changes

**Comment by shinobs** [comment]
Hello, thanks for the fix. On my end, it works partially. If I close the application, I have to clear the cookies again and each time I open the app.
