### ISSUE TITLE
ReadComicOnline is not working

### ISSUE THREAD

**Issue by Mirza-Man** [keiyoushi/tachiyomi-extensions-source#4822]
### Source information

ReadComicOnline

### Source language

English

### Steps to reproduce

![image](https://github.com/user-attachments/assets/5844b576-299a-4db9-9418-68276c583916)

### Expected behavior

Entries from the extension should open to give us the pages of the comic book.

### Actual behavior

The page doesn't open, and neither does it in WebView.

### Mihon/Tachiyomi version

Aniyomi 0.16.4.3-7801

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Duplicate of #4115
