### ISSUE TITLE
adult webtoon down

### ISSUE THREAD

**Issue by capitanjal** [keiyoushi/tachiyomi-extensions-source#483]
### Source name

en.adultwebtoon 1.4.34

### Source language

english

### Source link

https://adultwebtoon.com

### Other details

The main site works but the rest gives 404 err

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by domflamingo2** [comment]
The site is not dead, please close the issues
