### ISSUE TITLE
3Hentai

### ISSUE THREAD

**Issue by ImAlwaysHorni** [keiyoushi/tachiyomi-extensions-source#485]
### Source name

3HENTAI

### Source link

https://3hentai.net/

### Source language

MULTI

### Other details

18+/NSFW=YES

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
@ImAlwaysHorni don't post nsfw screenshots on GitHub.

**Comment by 0Ha16wA5** [comment]
https://github.com/komikku-app/komikku-extensions/commit/1c375b22506245aa10e1b9c4abd3b090d2fb9be7

https://github.com/komikku-app/komikku-extensions/issues/10

Should be merged here
