### ISSUE TITLE
Manga Demon changed to DemonicScans

### ISSUE THREAD

**Issue by Dat1Zpic** [keiyoushi/tachiyomi-extensions-source#4852]
### Source information

Demonic Scans 

### Source language

English 

### Source new URL

https://demonicscans.org/

### Other details

Manga Demon changed it's domain to Demonic Scans.

### Acknowledgements

- [X] I have updated all installed extensions.
- [ ] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Duplicate of #4770 

Search the existing issues first before opening a new one, and acknowledging that you did when you didn't
