### ISSUE TITLE
Mangahere update fail

### ISSUE THREAD

**Issue by Sundogg17** [keiyoushi/tachiyomi-extensions-source#4853]
### Source information

Manga here 1.4.19

### Source language

English 

### Steps to reproduce

Tey to update, fails to update

### Expected behavior

To go to extension and update, and install

### Actual behavior

Click on uodate, and it won't update 

### Mihon/Tachiyomi version

Tachij2k 1.74 

### Android version

17

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Duplicate of #4819 

Search the existing issues first before opening a new one, and acknowledging that you did when you didn't. The fix is live, update extension

**Comment by Norsze** [comment]
For support with updating extensions go to the Discord

**Comment by Sundogg17** [comment]
This is different...that one is shown closed. This is is about extension uodate. Two different things

**Comment by Norsze** [comment]
@Sundogg17  Go to discord for extension update support, the github can't fix you having issues with your phone installing an app

**Comment by Sundogg17** [comment]
Yes, got it to work. :)
Though same issue with extension showing http 500. I assume I guys are still working in it. Sorry for the confusion in my end.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Norsze** [comment]
@Sundogg17  if you managed to update to 1.4.20 you need to go to advanced settings and clear cookies for the extension to work

**Comment by VirtueCoding** [comment]
After I update to 1.4.20 and clearing cookies, it works for a while.

Now I think they are patching it again? It does not work again even after clearing cookies and cache.

**Comment by Smol-Ame** [comment]
@AbuGosok their site's search is having an issue, not extension-related at the moment.

Also, for future reference, don't comment on a closed/resolved issue/fix (especially since it unnecessarily pings everyone in this issue request), come to the Keiyoushi Discord repo-support channel for questions (which this one was discussed about a few hours ago)
