### ISSUE TITLE
Manga Demon URL change

### ISSUE THREAD

**Issue by MikrySoft** [keiyoushi/tachiyomi-extensions-source#4862]
### Source information

Manga Demon 1.4.12

### Source language

English

### Source new URL

https://demonicscans.org/

### Other details

WebView shows new URL for Manga Demon. Kind of funny I need to mark that "I have opened WebView and checked that the source URL has not changed yet." on a source URL change ticket.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Update your extension

Also, the "I have opened WebView and checked that the source URL has not changed yet." check means you checked that it's not loading into the new link, or it takes a redirect from the current link.
