### ISSUE TITLE
Page Not Found error on kewn scans

### ISSUE THREAD

**Issue by LeoAjju** [keiyoushi/tachiyomi-extensions-source#4869]
### Source information

Kewn Scans 1.4.6

### Source language

English

### Steps to reproduce

Add any title (like Became a Contractual daughter of a soon to be ruined family) from kewn scans to your library and try to read it in app. Opens up blank for a short while then closes up to a page not found error, also occurs if trying to download the chapter.

### Expected behavior

Should open up to the chapter image files and able to bypass the ads placed as an overlay on each webpage of the scans site which needs to be closed after a short timer.

### Actual behavior

Shows a No pages Found error

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

The extension opens up in webview which shows the website has an ad overlay on each webpage which has a short timer required to be close before interating with anything on the page. Might be the reason the chapter image files are not being accessed by the extension crawler

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by asdkant** [comment]
Can confirm this is also happening with kewn 1.4.6 and TachiyomiJ2K 1.7.4
