### ISSUE TITLE
Flame comics arrows. 

### ISSUE THREAD

**Issue by nad1991** [keiyoushi/tachiyomi-extensions-source#4870]
### Source information

Flame Comics 1.4.32 

### Source language

English

### Steps to reproduce

1. Open any chapter. 

### Expected behavior

Viewer should only show chapter pages. 

### Actual behavior

Web elements (carets/arrows) are getting mixed with chapter pages. Image attached. 
![Screenshot_2024-08-31-12-35-37-59_551f7f0ca926862b368845ce7ee433aa](https://github.com/user-attachments/assets/c817d789-fab5-4fd4-ae7c-64764468bfd9)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nad1991** [comment]
So I probably found the issue: they've added a radio to the site inside "readerarea" id, with both carets' images (left/right-chevron.png) inside paragraph (p) tags, which seems to be what the extension is looking for.

As a side note, recently there's also an issue with duplicate images, and in my case, these duplicates are all inside this big (and broken) paragraph section as well so it might be related.

**Comment by Koinzell234** [comment]
I can second the duplicate pages. From what I have seen it's only duplicating pages for newer releases. Older chapters seem to be fine just the newer ones seem to duplicate from my experience.

**Comment by snorlaxthepokemon** [comment]
Yes I am seeing duplicate pages along with these arrows

**Comment by krakerz** [comment]
Can confirm this too

**Comment by Smol-Ame** [comment]
No need to confirm the issue, just give it a thumbs up (or follow the issue if you want updates) to avoid pinging/emailing everyone involved in the issue unnecessarily
