### ISSUE TITLE
Error in Demon Sect extension (Seita Celestial)

### ISSUE THREAD

**Issue by Shadow903** [keiyoushi/tachiyomi-extensions-source#4871]
### Source information

Demon Sect 1.4.46

### Source language

Português

### Steps to reproduce

1- Open extension
2- Press "Open in WebView"
3- Opens on a non-Demon Sect website.

### Expected behavior

When you open the extension, you should be able to read the site's works.

### Actual behavior

The extension opens on a Japanese sales website.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Other details

The Demon Sect website does not redirect to the sales site in question. I have used the same link that I saved on a word page and have never been redirected to another type of site.
![IMG-20240831-WA0004](https://github.com/user-attachments/assets/443ba4bf-22cb-4718-aaaf-921fdf3655b8)
![IMG-20240831-WA0005](https://github.com/user-attachments/assets/c05a1338-1e14-40f4-a601-c2afe6099db1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Seems fine on my end. Try going to Mihon Settings > Advanced, and "Clear cookies" + "Clear WebView data"

**Comment by Shadow903** [comment]
I cleared the cookies and data from WebView and it continues to send to the sales site

**Comment by Smol-Ame** [comment]
Just checking, do you have DNS over HTTPS enabled in Mihon Settings > Advanced?

**Comment by Shadow903** [comment]
It is deactivated, which of these options do I put.
![IMG-20240831-WA0010](https://github.com/user-attachments/assets/0076dd62-37a2-4e02-a42d-9e6e8c2db2dc)
![IMG-20240831-WA0009](https://github.com/user-attachments/assets/b10b8020-ba00-4ec9-b24b-410627e4aa90)

**Comment by Smol-Ame** [comment]
I'm not sure what the issue would be then.

If you want, try switching to any of those options (remember to restart your app after changing it), and see if it helps (but this might interfere with other sources, so turn it off if it doesn't help).

**Comment by Shadow903** [comment]
I tried all the options and none of them worked

**Comment by nomaxsnx** [comment]
![Screenshot_2024-08-31-17-39-57-519_app mihon](https://github.com/user-attachments/assets/135f4310-5db9-4046-9fd3-781c8076e970)

**Comment by Shadow903** [comment]
The problem has to do with the "Default user agent string". If I use my own it shows the store's website but if I use what Mihon already provides the extension works fine.

**Comment by Smol-Ame** [comment]
I kind of thought that might be the issue, but the only times I've seen a site behave differently with a different/specific user-agent, it would only cause the Latest and/or Popular page to not load correctly. I checked with my own user-agent & the default user-agent and didn't encounter this issue, so I didn't think of to mention it.

Anyways, shouldn't be an extension-relayed issue then, you just need to find/use a different user-agent then.

**Comment by choppeh** [comment]
Resolved: #4891. 

Issue can be closed
