### ISSUE TITLE
Mangahere Error 500

### ISSUE THREAD

**Issue by masdabazz** [keiyoushi/tachiyomi-extensions-source#4875]
### Source information

Mangahere 1.4.20

### Source language

English

### Steps to reproduce

Update entry from mangahere, or click on extension

### Expected behavior

update or view with no issues

### Actual behavior

This version works, however everytime you close the app it resets, you have to clear cookies and webview data and then redirect to the direct link on webview.

### Mihon/Tachiyomi version

0.16.5

### Android version

Andriod 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by morethanhater** [comment]
Trying to search for anything or read any chapter ends up with error 500

Clearing cookies helps for awhile
Guess it's a problem with the source (website), not extension

**Comment by masdabazz** [comment]
so theres nothing that can be done?

**Comment by TheKingTermux** [comment]
Error code 5xx is an server side error, soo not an extension problem
