### ISSUE TITLE
EarlyManga error 500 when filtering by latest, updated date or upload date

### ISSUE THREAD

**Issue by Bullseye1966** [keiyoushi/tachiyomi-extensions-source#488]
### Source information

1.4.22

### Source language

English

### Steps to reproduce

1. Click latest on the EarlyManga extension on the menu or whilst on it and it will produce error 500
2. Whilst on the extension filtering by updated date or added date also provides this error 

### Expected behavior

Click latest and the page should show all the current latest updated manga from the site or filtering by updated date should provide the same and added date should show in order from the added timestamp for the manga ascending or descending.

### Actual behavior

Upon doing these actions the error 500 will be produced but when using Web view filtering by another type such as views or ratings it works. Browsers also work as intended 
![Screenshot_20240122_130715_Mihon](https://github.com/keiyoushi/extensions-source/assets/140194300/09101a5d-47e1-44cb-8219-35b9efcf9799)
![Screenshot_20240122_130721_Mihon](https://github.com/keiyoushi/extensions-source/assets/140194300/828c93bc-6ba4-4a00-a829-a99e5b542614)

### Tachiyomi version

Mihon - stable 0.16.1, tachiyomi - 0.15.3

### Android version

13

### Other details

Tried using both latest stable mihon and tachiyomi versions and same issue is apparent.
Other extensions work fine using these filters and is only with EarlyManga i have found this issue
Cleared cache, webview data etc. and tried another user client agent with no resolution.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
The extension uses `Updated date` sort option on `https://earlym.org/hot-manga`, which isn't working right now, so it is a site issue

**Comment by Bullseye1966** [comment]
Reinstalling the extension using both methods doesn't fix the issue

**Comment by Bullseye1966** [comment]
> The extension uses `Updated date` sort option on `https://earlym.org/hot-manga`, which isn't working right now, so it is a site issue

Ok, thank you
