### ISSUE TITLE
Please add snowmtl extension

### ISSUE THREAD

**Issue by 00watcherb** [keiyoushi/tachiyomi-extensions-source#4884]
### Source name

Snow machine translations

### Source link

https://snowmtl.ru/

### Source language

English

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Saucemaster1** [comment]
I agree this one will be a great add

**Comment by Smol-Ame** [comment]
@Saucemaster1 don't comment bump unless you have extra info that helps contributors. Also, while we're here, reminder to search the existing issues for before opening a new one, and acknowledging that you did when you didn't.

**Comment by corehard** [comment]
Hope you can add this. thank you!
