### ISSUE TITLE
Kappa beast

### ISSUE THREAD

**Issue by Sundogg17** [keiyoushi/tachiyomi-extensions-source#4885]
### Source information

Kappa beast 1.4.30

### Source language

English 

### Steps to reproduce

Open source and see titles

### Expected behavior

To open and show all titles available 

### Actual behavior

Some titles don't show up in repo, however they show up in the webview. 

### Mihon/Tachiyomi version

Tachij2k 1.74 

### Android version

17

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
give example

**Comment by Sundogg17** [comment]
Some are

I'm fine being the second gf
If I help sisters who hate boys

**Comment by Sundogg17** [comment]
It wasn't closed to reopen for for bump. The issue was no longer relevant. With the old ticket, some titles were not working. The website just updated/redesigned there who page. Now non of the titles show. So it wasn't on purpose to close and reopen. The ticket didn't seem relevant to the new changes on website.

Sorry if i did something wrong. I was just trying to keep it relevant and up to date information.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
