### ISSUE TITLE
Chain validation error on arcane

### ISSUE THREAD

**Issue by Hazzardousgamer** [keiyoushi/tachiyomi-extensions-source#4889]
### Source information

Arcane 1.4.36

### Source language

English

### Steps to reproduce

Try updating series from source

### Expected behavior

Series should update

### Actual behavior

Chain validation failed

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
From a discussion in Keiyoushi Discord repo-support channel, and checking earlier myself, it seems like this was a source-related issue with their website.

If you tried to load the page in your own browser earlier. you might've been met with an error/warning that their website had missing certificate (to authenticate the site). It seems at this moment, they have fixed their certificate issue & now their website loads up correctly in-browser. The extension seems to work as well.
