### ISSUE TITLE
Mangaeffect

### ISSUE THREAD

**Issue by Sundogg17** [keiyoushi/tachiyomi-extensions-source#4892]
### Source information

Mangaeffect 1.4.37

### Source language

English 

### Source new URL

https://www.mangaread.org/

### Other details

Looks like it change just today.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment]
they closed and merge with mangaread #4900
