### ISSUE TITLE
Wrong Resetscan url link on repo

### ISSUE THREAD

**Issue by ffuentesm** [keiyoushi/tachiyomi-extensions-source#4894]
### Source information

Reset Scans 1.4.41

### Source language

English

### Source new URL

https://resetscan.com/

### Other details

The curent sourse URL is for an outdates website of similar name. https://reset-scans.co/
The icon of the websites are different, and the repo is using the icon of the powerbutton which is the "real" reset scan.
![Screenshot_20240902_215437_Chrome](https://github.com/user-attachments/assets/83bcbf89-c1c1-46b6-81dd-42ec963d4e53)
![Screenshot_20240902_215409_Chrome](https://github.com/user-attachments/assets/af37eb78-d077-450a-ac31-4ab3137b17e7)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Read comments in closed #4820 

Or look at Reset Scan's own Discord server yourself before you make a claim

**Comment by ffuentesm** [comment]
If the old URL got dropped, why did it just get an update last week? If both URLs are being used, I suggest making two instances of it. 
![Screenshot_20240902_220542_Chrome](https://github.com/user-attachments/assets/46e575fa-7681-4902-83b2-c207b72f7540)

**Comment by Smol-Ame** [comment]
Take it up with them instead for uploading out of the blue there. It seems like their old site literally only has five manga titles, and the one you sent is the only one that got an update since July.

**Comment by Smol-Ame** [comment]
Nevermind, did the research for you

![Screenshot_20240902_193327.png](https://github.com/user-attachments/assets/55bb7441-bc75-43d1-9ee3-99c8155e9350)

![Screenshot_20240902_193205.png](https://github.com/user-attachments/assets/64fee99d-7faa-457b-be88-50fe668db2d4)

**Comment by AwkwardPeak7** [comment]
#5197
