### ISSUE TITLE
Manga District domain error following Cloudfare  issue

### ISSUE THREAD

**Issue by mag0bei** [keiyoushi/tachiyomi-extensions-source#4895]
### Source information

Manga District 1.4.43

### Source language

English

### Steps to reproduce

I have a Cloudfare issue with Manga District source version 1.4.43. However, when I'm trying to fix it in webview, I get "net::ERR_NAME_NOT_RESOLVED" page
![Screenshot_20240903_044758_TachiyomiSY](https://github.com/user-attachments/assets/de98c49e-5a29-423a-853e-855511b1e79c)
![Screenshot_20240903_044609_TachiyomiSY](https://github.com/user-attachments/assets/5902b80c-4fb4-470f-992d-eccf61246cae)

### Expected behavior

Webview page opening on source website so that I can solve Cloudfare issue

### Actual behavior

net::ERR_NAME_NOT_RESOLVED page

### Mihon/Tachiyomi version

TachiyomiSY Preview r564

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by mag0bei** [comment]
This is actually a domain error issue. Cloudflare just highlighted it

**Comment by Smol-Ame** [comment]
Nothing we can do about it, if their site is legitimately dead, let us know (and share any announcements they might've had)
