### ISSUE TITLE
Crystal Comics (PT-Br Source) Error HTTP 404

### ISSUE THREAD

**Issue by EvaldoCeBr** [keiyoushi/tachiyomi-extensions-source#4903]
### Source information

CrystalComics 1.4.36

### Source language

Portuguese Brazilian 

### Steps to reproduce

When going to the recent tab, the HTTP 404 error appears.

![Screenshot_2024-09-03-15-13-38-899_app mihon](https://github.com/user-attachments/assets/c318f558-afaa-4513-997d-a13c81a7880f)

### Expected behavior

Open without error.

### Actual behavior

HTTP Error 404.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by dngonz** [comment]
Works for me, no error shown up. Could you elaborate more?

**Comment by EvaldoCeBr** [comment]
> Works for me, no error shown up. Could you elaborate more?

It stopped giving problems..
