### ISSUE TITLE
Title links to webnovel instead of comic

### ISSUE THREAD

**Issue by WarkahScott** [keiyoushi/tachiyomi-extensions-source#4906]
### Source information

Reaper Scans 1.4.55

### Source language

English

### Steps to reproduce

Open a title with both a comic and novel, e.g. "the martial god who regressed back to level 2"

### Expected behavior

Should be able to read the comic

### Actual behavior

The chapters show "no pages found" and opening in webview links to the webnovel 

### Mihon/Tachiyomi version

Stable 0.15.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Seems fine on my end. Remember to migrate all of your **Reaper Scans** entries back into **Reaper Scans**

Join the Keiyoushi Discord repo-support server if you need more help, and read through the status-updates channel on the Discord for mandatory steps/important info

**Comment by WarkahScott** [comment]
Very weird, I thought everything was migrated since it was the only title acting up but that seems to have fixed it, thanks.
