### ISSUE TITLE
YaoiScan HTTP 500 error 

### ISSUE THREAD

**Issue by Clary22** [keiyoushi/tachiyomi-extensions-source#4910]
### Source information

YaoiScan 1.4.36

### Source language

English 

### Steps to reproduce

After opening the app
1. Click on Browser
2. Sources 
3. YaoiScan “Latest”

### Expected behavior

The latest titles should show up.

### Actual behavior

Instead it shows the HTTP 500 error, ones I open the webview the page seems to fine and does shows the latest titles.
![Screenshot_20240903_203816_Mihon_Original](https://github.com/user-attachments/assets/97de2702-620c-4082-bb37-446908279711)

### Mihon/Tachiyomi version

Stable 0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Their website might work, but try searching something in their website, either in WebView or your own browser

![Screenshot_20240903_175631_Mihon](https://github.com/user-attachments/assets/dac3f1fe-cef4-443c-a195-d6c2f9170569)


Website database/server issue, nothing we can do about it

**Comment by Clary22** [comment]
Oh, thank you for checking, have a wonderful week.

**Comment by TheKingTermux** [comment]
Error 5xx is server side error, not an extension problem

**Comment by Clary22** [comment]
Okay, is working now, thank you for your help.
