### ISSUE TITLE
MangaEffect is unable to display any manga list, showing HTTP 400 Error

### ISSUE THREAD

**Issue by grim0rapper** [keiyoushi/tachiyomi-extensions-source#4915]
### Source information

Browse -> Source

### Source language

English

### Steps to reproduce

Browse -> Source -> MangaEffect [Latest] 

### Expected behavior

The list of latest updated manga is previewed

### Actual behavior

It's just showing HTTP 400 Error despite the webpage is available using WebView

### Mihon/Tachiyomi version

Tachiyomi ver. 0.15.3

### Android version

Android 11

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Duplicate of #4900
