### ISSUE TITLE
Nox Scans

### ISSUE THREAD

**Issue by Rip0000** [keiyoushi/tachiyomi-extensions-source#4917]
### Source information

Nox Scans 1.4.30

### Source language

turkish

### Steps to reproduce

1. I open the application
2- Open Any Manhwa from Nox Scans Extension
3- When I Try to Read, It Gives a Page Not Found Error

### Expected behavior

page not found 

### Actual behavior

It opens the page in web view, but in the application it gives a page not found error.

### Mihon/Tachiyomi version

Tachiyomi 0.15.3

### Android version

android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Are you able to view said chapter in WebView on your own browser?

I am unable to see any chapter's pages in WebView, not sure if it's a region thing. But if you are unable to see pages as well, then it's a source-related issue at the moment, no extension-related.

**Comment by Rip0000** [comment]
In web view, the sections are opened in the browser, but when I open it in the application, it cannot find the section.

**Comment by Thekages** [comment]
I have the same problem. I view it in webview, enter the chapter and click verify. The chapter opens, then I enter from Mihon and get the page not found error.

**Comment by ghost** [comment]
Same problem here. I don't think so it's a regional thing becasue I tried with a vpn and pages still loading normally in webview.

**Comment by Bastankara** [comment]
@Smol-Ame  I think it is not opening because it is asking for verification because webview is asking for verification that it is not a robot.
