### ISSUE TITLE
Blackout scan: domain changed

### ISSUE THREAD

**Issue by Joselucas3325** [keiyoushi/tachiyomi-extensions-source#4926]
### Source information

Blackout scan

### Source language

Brasil

### Source new URL

https://toptoon.com.co/

### Other details

![Screenshot_20240904_192145_Mihon](https://github.com/user-attachments/assets/4b947bca-89fc-4974-b6e6-40c3cbb0cb04)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Error code 5xx is an server side error ~soo not an extension problem~

**Comment by Smol-Ame** [comment]
> Error code 5xx is an server side error soo not an extension problem

Bad title, but correct issue request (for new URL)

**Comment by TheKingTermux** [comment]
> Bad title, but correct issue request (for new URL)

Ahh sorry my bad

**Comment by Norsze** [comment]
Sorry, kei bot still not back, so I can't fix titles

**Comment by EvaldoCeBr** [comment]
#4741 They already have an open ticket.
