### ISSUE TITLE
previous favorite items from nhentai.net error: nhentai.net SERVFAIL. - website works

### ISSUE THREAD

**Issue by Wyld-One** [keiyoushi/tachiyomi-extensions-source#4927]
### Source information

using NHentai multi 1.4.46

### Source language

all

### Steps to reproduce

Loaded backup.
Found nhentai entry.
Tried to view
Error : here
Tap web view, get html page of appropriate comic.

Further note nhentai ext also failing all searches on nhentai.net

Can't search for NHentai.net comics at all.have to find and try.

### Expected behavior

Should show comic thumbnail & allow downloads

### Actual behavior

nhentait.net: SERVFAIL

### Mihon/Tachiyomi version

0.15.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Works fine, you're probably looking at old data from previous attempts to access their site when they were down.

Go to Mihon Settings > Advanced, and "Clear cookies" + "Clear WebView data", and maybe also "Clear chapter cache" in Mihon Settings > Data and storage if needed.

**Comment by Norsze** [comment]
Their DNS is probably just a bit slower than what you're using, switch DNS over HTTPS to Cloudflare or Google if Smol-Ame's instructions don't help

**Comment by Wyld-One** [comment]
Thanks for looking into it I figure it's probably either one it was Cache lag somewhere.

By the way it was using cloudflare & https DNS look up

I'm about to set up my own bind9 DNS look up service because of all the nonsense isps and so-called 'protectors of the internet censorship' idiots put in
