### ISSUE TITLE
A pair of 2+ closed.

### ISSUE THREAD

**Issue by nad1991** [keiyoushi/tachiyomi-extensions-source#4931]
### Source name

A Pair Of 2

### Source language

English

### Source link

po2scans.com

### Other details

Their website has been dead for a while and they mentioned recently in their discord (pinned) it's officially closed and they're moving  their stuff to mangadex.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Bigotaku** [comment]
![Screenshot_2024-09-06-08-38-09-50_40deb401b9ffe8e1df2f1cc5ba480b12~2](https://github.com/user-attachments/assets/08eb4d06-4d91-4e73-9c4e-9e2738e7c01c)
Proof👆
