### ISSUE TITLE
Ikigai mangas no carga capitulos 

### ISSUE THREAD

**Issue by BastiVader** [keiyoushi/tachiyomi-extensions-source#4934]
### Source information

Ikigai 1.4.15

### Source language

Español

### Steps to reproduce

Entro a la fuente Ikigai mangas
Elijo el manga
Entro al capítulo 
Entro al capítulo 
Aparece error 525
Entro a la web y el capitulo aparece perfectamente 

### Expected behavior

Entro a la fuente Ikigai mangas
Elijo el manga
Entro al capítulo 
Entro al capítulo 
Leo el capítulo 

### Actual behavior

Entro a la fuente Ikigai mangas
Elijo el manga
Entro al capítulo 
Entro al capítulo 
Aparece error 525
Entro a la web y el capitulo aparece perfectamente 

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
They changed domains, refer to #4929
