### ISSUE TITLE
Mg Komik

### ISSUE THREAD

**Issue by biyassn** [keiyoushi/tachiyomi-extensions-source#4939]
### Source name

https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json

### Source language

bahasa Indonesia 

### Source link

https://mgkomik.id/

### Other details

gagal menembus cloudflare

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
?blurb cf

**Comment by Smol-Ame** [comment]
1) Wrong issue request, source is not down
2) Why did you put the repo link as the Source name? For future reference, put the extension's name & version number, like it shows in the example before you type anything
3) Come to the Keiyoushi Discord repo-support server for basic troubleshooting
4) For Cloudflare related issues, you can go to the Keiyoushi website or use the literal button shown above in WebView for help/guide to pass Cloudflare (see first picture)

Extension works fine

![Screenshot_20240905_094037_Mihon.png](https://github.com/user-attachments/assets/059fc2b7-a5ac-4f4e-a95c-53adecbb50a6)

![Screenshot_20240905_094146_Mihon.png](https://github.com/user-attachments/assets/5b991df9-9376-401b-b9f8-cfd9d1885ee6)

**Comment by Norsze** [comment]
Visit the Cloudflare guide https://keiyoushi.github.io/docs/guides/troubleshooting#cloudflare
