### ISSUE TITLE
Mangago: The image couldn't be loaded issue

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#4946]
### Source information

Mangago 1.4.16

### Source language

English 

### Steps to reproduce

Open source 
Go any series

### Expected behavior

All pages of the series must be loaded.

### Actual behavior

But only the first 5 pages are loaded.

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Looked through like 10 different chapters in 7 different titles, everything seemed to load up fine.

Check WebView for errors, give a list of specific titles/chapters that are doing this (which might just be #4005), or come to the Keiyoushi GitHub for troubleshooting

**Comment by Norsze** [comment]
No this is related to how the site displays chapters in some way. It shows chapters in chunks of pages (generally seems to be 5 images per "page"). So every image not on the 1st page fails to load.

![Screenshot_20240908_142423_Mihon.jpg](https://github.com/user-attachments/assets/1d435fc5-5957-4a67-ad1c-66602e5e4b11)

List in screenshot shows all pages, but page 1 shows images 1-5, page 2 shows 2-6, 3 shows 3-7 etc
The extension seems to show only the from page 1 images 1-5.

Note though, they also do 1 image per page on most titles. These titles work as expected
