### ISSUE TITLE
Chapters Not Updating on Mangakakalot

### ISSUE THREAD

**Issue by wajlflwr** [keiyoushi/tachiyomi-extensions-source#495]
### Source information

Mangakakalot

### Source language

English

### Steps to reproduce

1. Open any manga from Mangakakalot
2. Swipe down so it will update
3. Alternatively, open WebView

### Expected behavior

Library should update and website should open normally.

### Actual behavior

Message appears: "No chapters found". It is still possible to open and read previous chapters. But it won't update.

WebView takes me to a website that only says "Index".

### Tachiyomi version

Stable 1.10.2

### Android version

Android 12

### Other details

Experienced same issue on Tachiyomi and Mihon apps.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Mangakakalot URL format changed, migrate entries from Mangakakalot to Mangakakalot.
