### ISSUE TITLE
VoidScans.co is dead

### ISSUE THREAD

**Issue by Dagraenion** [keiyoushi/tachiyomi-extensions-source#4968]
### Source name

Void Scans

### Source language

English

### Source link

voidscans.co

### Other details

It seems they changed domain name to: hivetoon.com
![17257702420806427128492025243081](https://github.com/user-attachments/assets/def1adfb-0ed2-4135-8807-47a280e9d6db)

![Screenshot_20240908_123746_TachiyomiSY](https://github.com/user-attachments/assets/a45b3128-c11b-46f2-8e4e-5db5db4eab8f)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
hivetoon.com is a seperate extension

**Comment by Bigotaku** [comment]
> hivetoon.com is a seperate extension

Both are same people. They "rebranded " as hive.
