### ISSUE TITLE
Mangatale

### ISSUE THREAD

**Issue by ShoujoLover** [keiyoushi/tachiyomi-extensions-source#4986]
### Source information

Mangatale 1.4.33

### Source language

Indonesia

### Source new URL

Mangatale.id

### Other details

Change url .co to .id

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Kunaguero110** [comment]
Up sir
