### ISSUE TITLE
Flame scans cloudflare issue 

### ISSUE THREAD

**Issue by Monkedoesweed** [keiyoushi/tachiyomi-extensions-source#4987]
### Source information

Flame scans

### Source language

English

### Steps to reproduce

1.Open extension 
2. Extension gives cloudflare error
3. Open WebView 
4. WebView is stuck on cloudflare verification look

### Expected behavior

Redirected to website instead of cloudflare verification look

### Actual behavior

Verification loop

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Refer to the Solving Cloudflare issues section at https://keiyoushi.github.io/docs/guides/troubleshooting#cloudflare. If it doesn't work, migrate to other sources or wait until they lower their protection.

**Comment by Monkedoesweed** [comment]
Got the issue fixed by deleting cashe in WebView
