### ISSUE TITLE
[Kurage Bunch] error when refreshing chapter list

### ISSUE THREAD

**Issue by leones00** [keiyoushi/tachiyomi-extensions-source#4993]
### Source information

Kurage Bunch 1.4.5

### Source language

"Japanese"

### Steps to reproduce

Try to refresh comics (update library) on Kurage Bunch.

### Expected behavior

App updating the list of new chapters.

### Actual behavior

App showing this message: "NullPointerException: null".

### Mihon/Tachiyomi version

Mihon stable 0.16.5

### Android version

Android 12

### Other details

I can still read previous chapter from non-updated list.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by SplitterTriplets** [comment]
I am also having this issue.

**Comment by vetleledaal** [comment]
Issue is in the GigaViewer class, `chapterListParse()`. It looks like `readableProductList` / `firstListEndpoint` / `latestListEndpoint` is all missing from the page.

It's better if someone already familiar with GigaViewer could work on it.
