### ISSUE TITLE
Extension repos

### ISSUE THREAD

**Issue by YahyeDeero** [keiyoushi/tachiyomi-extensions-source#5]
### Source information

All sources of url

### Source language

All languages

### Steps to reproduce

1. Go to the browser 
2. Tap on browser 
3. Tap and inter extension repos
4. Then add your extension
Well that's what is supposed but not working, i did everything, i added a URL then ended it with "index.min.json" tried to tap on the new extension but not working :( 

### Expected behavior

The new feature "Extension repos" supposed to add extensions to tachiyomi and work.

### Actual behavior

But instead it's not working nor showing anything, i did what i could by searching, going to the settings or checking over and over the steps u mentioned dozens of times and boom nothing is working; it's as if this new feature "Extension repos" doesn't exists. If you know something pls help me, i used tachiyomi for several years and wanted such feature. Thanks for reading :)

### Tachiyomi version

0.15.0

### Android version

Android 11

### Other details

Help pls i am begging you 🙏

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by YahyeDeero** [comment]
> `Tachiyomi:
> 
> ```
> Go to More → Settings → Browse
> Tap on "Extension repos" and then "Add" button at bottom
> Input "https://raw.githubusercontent.com/keiyoushi/tachiyomi-extensions/repo/index.min.json"
> Enjoy!
> ```
> 
> TachiyomiSY:
> 
> ```
> Go to More → Settings → Browse
> Tap on "Edit repos" and then "Add" button at bottom
> Input "keiyoushi/tachiyomi-extensions"
> Enjoy!
> ```
> 
> TachiyomiAZ:
> 
> ```
> Go to Settings → Browse
> Tap on "Edit repos" and then "+" button at bottom
> Input "keiyoushi/tachiyomi-extensions"
> Enjoy!
> ```
> 
> Others:
> 
> ```
> If you're not using any of the above fork then manually download and update extensions from https://github.com/keiyoushi/tachiyomi-extensions/tree/repo/apk
> ```
> 
> `

I did every step and the result is the new extension is just some word and not working, i tap on it but also not working or even opening 😐

**Comment by AntsyLich** [comment]
make sure to refresh the extension list

**Comment by YahyeDeero** [comment]
> make sure to refresh the extension list

I literally did it now

**Comment by YahyeDeero** [comment]
> > make sure to refresh the extension list
> 
> I literally did it now

But nothing is working
Quick question how many extension i can add using extension repo

**Comment by YahyeDeero** [comment]
> Try restarting the app. If it does not still work, could you provide bit more information? Because it is working fine for me

Should i get the extension i added in the browser or in the settings.

**Comment by YahyeDeero** [comment]
![Screenshot_20240107-134042_Tachiyomi](https://github.com/keiyoushi/tachiyomi-extensions-source/assets/98815320/f1e581bb-2186-4076-a856-0369f87cf401)
This is all what it is showing

**Comment by YahyeDeero** [comment]
> > > Try restarting the app. If it does not still work, could you provide bit more information? Because it is working fine for me
> > 
> > 
> > Should i get the extension i added in the browser or in the settings.
> 
> If you had for example the obsolete MangaDex extension already installed, it will stop being obsolete when you add the repo. For Bato.to extension there was an update

Hmm.... so u mean i can't add other external extensions except the ones that are already in tachiyomi there!

**Comment by AntsyLich** [comment]
You need add repo index url not extension urls. Those are sperate things...

**Comment by YahyeDeero** [comment]
> > > > > Try restarting the app. If it does not still work, could you provide bit more information? Because it is working fine for me
> > > > 
> > > > 
> > > > Should i get the extension i added in the browser or in the settings.
> > > 
> > > 
> > > If you had for example the obsolete MangaDex extension already installed, it will stop being obsolete when you add the repo. For Bato.to extension there was an update
> > 
> > 
> > Hmm.... so u mean i can't add other external extensions except the ones that are already in tachiyomi there!
> 
> You can if there is 3rd party developer who has made an extension for the source you want. Webtoons won't be having one though most likely as most of it is paywalled content. If you want to use Webtoons, you should use their official app instead.

Thanks mate 😊 you are very active and eager to answer my useless questions 🥲 
 Mmmmm.... i am kinda confused, how many extensions i can add; are they many other like bato.to who is kinda easy to just add

**Comment by AntsyLich** [comment]
Please join the discord if you need additional support. GitHub issues is not intended for support usage. Thank you.
