### ISSUE TITLE
Random Scan mudou de nome e URL 

### ISSUE THREAD

**Issue by paz-web** [keiyoushi/tachiyomi-extensions-source#500]
### Source information

1.4.39

### Source language

PT BR

### Source new URL

https://luratoon.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Closed by #524
