### ISSUE TITLE
TuMangaOnline/LectorManga don't show any chapter

### ISSUE THREAD

**Issue by Xtikma** [keiyoushi/tachiyomi-extensions-source#5002]
### Source information

TuMangaOnline/LectorManga

### Source language

Spanish

### Steps to reproduce

1.Any Manga
2.Any Chapter
3. Show the same error
4. Webview is okay
![Screenshot_2024-09-10-18-09-39-470_app mihon](https://github.com/user-attachments/assets/e408287d-49e2-4b39-b9ee-3b444c6c8316)
![Screenshot_2024-09-10-18-10-40-006_app mihon](https://github.com/user-attachments/assets/d04c93a5-796c-4c0a-af04-bede68e26a5b)
![Uploading Screenshot_2024-09-10-18-11-04-242_app.mihon.jpg…]()
5.But Chapter has error, in navigation with browser. The Chapter URL is random domain
![Screenshot_2024-09-10-18-13-42-981_org mozilla firefox](https://github.com/user-attachments/assets/faba87e1-f770-430d-b3e2-45280ce09d8f)

### Expected behavior

Keep navigation on random domain 

### Actual behavior

Keep navigation in frist domain and don't read Chapter in right page

### Mihon/Tachiyomi version

0.16.5

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by yoo07** [comment]
Una solución temporal en lo que encuentran el problema y lo arreglan es abrir el capítulo en modo webview y borras las Cookies, luego de eso ya debería cargar el capítulo y poder descargar las imágenes
![Screenshot_20240910-210955_Mihon](https://github.com/user-attachments/assets/9c89c637-2a1a-451f-88ac-936321478457)
![Screenshot_20240910-212514_Mihon](https://github.com/user-attachments/assets/aa04ce6b-24f3-4e8f-847b-d9f28ba5c540)
