### ISSUE TITLE
Falla al buscar en Hitomi

### ISSUE THREAD

**Issue by Simpyke** [keiyoushi/tachiyomi-extensions-source#5009]
### Source information

Hitomi 1.4.33

### Source language

Varios idiomas

### Steps to reproduce

Al buscar un manga este no encuentra el titulo y da error 

### Expected behavior

Al buscar un manga aparece 

### Actual behavior

Al buscar un manga marca error 

### Mihon/Tachiyomi version

Stable 0.15.3

### Android version

Android 14

### Other details

![Screenshot_2024-09-11-11-38-18-52_afd66b7916d19a60815f56273408b73e](https://github.com/user-attachments/assets/04e0057b-1ae0-4e75-8ff2-e656f86467a4)
![Screenshot_2024-09-11-11-38-23-87_afd66b7916d19a60815f56273408b73e](https://github.com/user-attachments/assets/dc5caccf-13bc-4ee1-bf86-4707c3cc90be)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
If your Hitomi extension version is correct, then you're using either an old version or a different repo. Our Hitomi extension version number is 1.4.33

Come to the Keiyoushi Discord repo-support channel for more help

**Comment by Simpyke** [comment]
I'm sorry I made a mistake when placing the version if it is 1.4.33
![Screenshot_2024-09-11-11-57-51-07_afd66b7916d19a60815f56273408b73e](https://github.com/user-attachments/assets/5a28a8d9-d311-4fd7-82cc-9b04af87a55f)

**Comment by AwkwardPeak7** [comment]
use less keywords when searching, or alternatively use filters in the source

**Comment by Simpyke** [comment]
You are right, searching with keywords there is an answer from the extension
