### ISSUE TITLE
Update domain for Random Scan

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#501]
### Source information

Random Scan 1.4.39

### Source language

Portuguese (Brazil)

### Source new URL

https://luratoon.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ghost** [comment]
Dumb Bot 🤔

**Comment by beer-psi** [comment]
Duplicate of #500 anyways, which was also closed by accident.
