### ISSUE TITLE
Add the ability to change Url

### ISSUE THREAD

**Issue by DimaBroZY** [keiyoushi/tachiyomi-extensions-source#5010]
### Source name

Multimanga

### Source language

Russian

### Describe your suggested feature

In settings like in HenChan

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Why? The extension still works and was just added. This is just a waste of everyone's time.

**Comment by DimaBroZY** [comment]
Sometimes it stops working on Russian territory
