### ISSUE TITLE
Manhwas.net si not working 

### ISSUE THREAD

**Issue by Kratos43R** [keiyoushi/tachiyomi-extensions-source#5020]
### Source information

1.4.11

### Source language

Spanish

### Steps to reproduce

1 if you enter in the app this don't work
2 if yo uses webview it doesnt work 
3 if you use a internet bowser it works

### Expected behavior

Im trying to read manga

### Actual behavior

It doesnt works :(

### Mihon/Tachiyomi version

Beta r6876

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
their ssl certificate expired, wait for them to fix / renew it

**Comment by bapeey** [comment]
the site fixed the issue
