### ISSUE TITLE
Elarc Toon Timeout 

### ISSUE THREAD

**Issue by AweRulez** [keiyoushi/tachiyomi-extensions-source#5022]
### Source information

Elarc Toon 1.4.39

### Source language

English

### Steps to reproduce

1. Open Mihon app
2. View Elarc Toon latest button
3. SocketTimeoutException: timeout notice

### Expected behavior

List of mahwa/manhua should appears 

### Actual behavior

Got "timeout" notice instead 
![Screenshot_2024-09-13-12-36-45-191_app mihon](https://github.com/user-attachments/assets/fb4fe7a7-69ca-49b4-8f9f-449c68873bd0)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Other details

Webview seems ok
![Screenshot_2024-09-13-12-50-30-672_app mihon](https://github.com/user-attachments/assets/e3a3f6d7-e441-489d-9b48-9a0ff57ccd02)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Just cause it loads the home page (or even manga page) doesn't mean the site is working. Try reading something on their site (either in WebView or your own browser)
