### ISSUE TITLE
Vortex Scans (EN)

### ISSUE THREAD

**Issue by flfwpl** [keiyoushi/tachiyomi-extensions-source#5023]
### Source information

Vortex Scans en.arvenscans 1.4.36

### Source language

English

### Steps to reproduce

Go to any manga in that sources
open it
refresh the page by pull down to refresh

### Expected behavior

no error popping

### Actual behavior

popping an error like this

![1726206620117](https://github.com/user-attachments/assets/ced47494-9391-4a7f-9763-b95e5518fb74)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
They switched URLs, check WebView/your own browser next time to diagnose the issue & open the correct issue request. I've opened 5024 for a URL change request for you though

**Comment by AwkwardPeak7** [comment]
#5024
