### ISSUE TITLE
Vortex Scans changed domains

### ISSUE THREAD

**Issue by Smol-Ame** [keiyoushi/tachiyomi-extensions-source#5024]
### Source information

Vortex Scans 1.4.36

### Source language

English

### Source new URL

https://vortextoon.com

### Other details

Supercedes #5023

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Salinda001** [comment]
Have you uploaded the updated extension cuz I didn't got the update of vortex scan extension!

**Comment by Smol-Ame** [comment]
> Have you uploaded the updated extension cuz I didn't got the update of vortex scan extension!

The pull request to update the site's URL hasn't been merged to the repo yet (so no new update currently), since it seems like Vortex is sticking with their current domain still. I wasn't able to find any mention of the new site/URL on their Discord, so not sure what they're planning.
