### ISSUE TITLE
Vortex scans error in updating new chapters

### ISSUE THREAD

**Issue by ManiV97** [keiyoushi/tachiyomi-extensions-source#5029]
### Source information

Vortex scans 1.4.36

### Source language

English

### Steps to reproduce

Error when updating chapters: missingfieldexception
![Screenshot_2024_0913_153442](https://github.com/user-attachments/assets/92d78c99-cdaa-49cf-8dae-07c937c983e2)

### Expected behavior

Latest chapters should be updated 

### Actual behavior

Getting error: missingfieldexception
![Screenshot_2024_0913_153442](https://github.com/user-attachments/assets/641114df-9893-4f15-8798-efcb5c33a070)

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #5023 / #5024 

Search the existing issues before opening a new one
