### ISSUE TITLE
Add Philia Scans

### ISSUE THREAD

**Issue by Salinda001** [keiyoushi/tachiyomi-extensions-source#5030]
### Source name

Philia Scans

### Source link

https://www.philiascans.com

### Source language

English

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by BraveDude8** [comment]
Worth noting that this aggregator site uses a coin system and locks some chapters behind logging into an account + paying real money via Kofi.

![image](https://github.com/user-attachments/assets/7624f430-6c7a-496f-a432-5b7699b9db24)

![image](https://github.com/user-attachments/assets/2ba77743-90a1-4924-981f-7bdf7425d761)

![image](https://github.com/user-attachments/assets/bdb0e491-1a40-4dad-8b79-d6338f789721)

**Comment by Salinda001** [comment]
Most of the websites that relied on google adsense  now use coin system except for a few.
