### ISSUE TITLE
VyvyManga captcha in every single manga 

### ISSUE THREAD

**Issue by aoba-seragakii** [keiyoushi/tachiyomi-extensions-source#5041]
### Source information

VyvyManga 1.4.5

### Source language

English 

### Steps to reproduce

Open an entry
You will receive a captcha alert
Complete it
Open another one
Another captcha alert

### Expected behavior

One single captcha 

### Actual behavior

Various captchas

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
That's usually just how it is with some sources, how their website has a high-level bot/spam protection

**Comment by aoba-seragakii** [comment]
> That's usually just how it is with some sources, how their website has a high-level bot/spam protection

So it's normal for captchas to keep appearing right after solving one?

**Comment by aoba-seragakii** [comment]
> That's usually just how it is with some sources, how their website has a high-level bot/spam protection

Well I guess it probably is so I'll close my issue

Thank you very much

**Comment by Smol-Ame** [comment]
Hmm, seems fine on my end & only needed to verify once for the Cloudflare verification. Only issue is the covers aren't loading in, but otherwise, chapters load up fine without extra verification. If you are experiencing this verification every time you open the source/entries, such as coming back to the app after a few hours, that's usually expected as the verification doesn't last forever.

Otherwise, maybe try changing your user-agent to see if Vyvy behaves better/asks for less Cloudflare verification.

**Comment by aoba-seragakii** [comment]
> Hmm, seems fine on my end & only needed to verify once for the Cloudflare verification. Only issue is the covers aren't loading in, but otherwise, chapters load up fine without extra verification. If you are experiencing this verification every time you open the source/entries, such as coming back to the app after a few hours, that's usually expected as the verification doesn't last forever.
> 
> Otherwise, maybe try changing your user-agent to see if Vyvy behaves better/asks for less Cloudflare verification.

I'll try doing that.
Thank you
