### ISSUE TITLE
Yaoi Fan Club age verification error

### ISSUE THREAD

**Issue by aoba-seragakii** [keiyoushi/tachiyomi-extensions-source#5047]
### Source information

Yaoi Fan Club 1.4.9

### Source language

Portuguese 

### Steps to reproduce

Open WebView
Error appears

### Expected behavior

There should be any problem 

### Actual behavior

The site is inaccessible through WebView 

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
It's not a bug. It's a feature of the blog.
