### ISSUE TITLE
Vortex Scans - Chapters not Found! 

### ISSUE THREAD

**Issue by Salinda001** [keiyoushi/tachiyomi-extensions-source#5058]
### Source information

Vortex Scans 1.4.37

### Source language

English

### Steps to reproduce

1.  Select Vortex Scans
2.  Search Manhwa (Ex: Return of the Genius Player)
3.  Select Manhwa

### Expected behavior

The Chapters should be loaded/updated. 

### Actual behavior

Shows an error ($.post) when updating chapters or shows "No Chapters found" when tried to migrate to vortex scans again. 
_________________________________________________________

![Screenshot_20240915-033443~2](https://github.com/user-attachments/assets/c0e39560-72cd-4b3a-93fc-dd656954ff51)

_________________________________________________________

![Screenshot_20240915-033856](https://github.com/user-attachments/assets/96fa3e63-abdd-4fbe-85a8-cde5ae41dc28)
![Screenshot_20240915-033847](https://github.com/user-attachments/assets/2b8f6577-a141-4f2a-b2d8-23456079c506)

### Mihon/Tachiyomi version

Yokai v1.8.5.7

### Android version

Android 14

### Other details

I checked the website and they have the chapters listed. Also checked on Mihon and Tachiyomi apps too.

_________________________________________________________

![Screenshot_20240915-034053](https://github.com/user-attachments/assets/0372d5a5-a5a4-4ea4-903e-3a181d43a139)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by cheeenx** [comment]
I get this message in tachiyomisy
![1726378110858](https://github.com/user-attachments/assets/37c8d390-eab7-4e0c-8f09-f32087fe6706)
