### ISSUE TITLE
manwa - No pages found

### ISSUE THREAD

**Issue by a0976875335** [keiyoushi/tachiyomi-extensions-source#5060]
### Source information

manwa-v1.4.5

### Source language

Chinese

### Steps to reproduce

Read any comic from manwa

### Expected behavior

Enter the reading interface normally and load images correctly.

### Actual behavior

After clicking the "Start" button, it crashes and prompts "No pages found".

### Mihon/Tachiyomi version

App version: 0.16.5 (standard, 2a01a2a, 6, 2024-04-09T09:58:14Z) 

### Android version

Android 14

### Other details

But in webview, the manga can be normally read.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by yigedajiaque** [comment]
是的，我也是未找到页面

**Comment by anenasa** [comment]
I am working on this.

**Comment by AlphaBoom** [comment]
> I am working on this.

If you are working on analyzing obfuscated code, the decode function is as follows:
```javascript
function decryptPhotos(encryptedPhotos) {
  const key = "hsadfuh73zmc1do9";
  try {
    var keyUtf8 = CryptoJS.enc.Utf8.parse(key);
    var ivUtf8 = CryptoJS.enc.Utf8.parse(key.substring(0, 16));
    var decrypted = CryptoJS.AES.decrypt(encryptedPhotos, keyUtf8, {
      iv: ivUtf8,
      mode: CryptoJS.mode.CBC,
      padding: CryptoJS.pad.Pkcs7
    });
    var decryptedStr = decrypted.toString(CryptoJS.enc.Utf8);
    return JSON.parse(decryptedStr);
  } catch (e) {
    return e;
  }
}
```

**Comment by yigedajiaque** [comment]
> I am working on this.

Thanks♪(･ω･)ﾉ
