### ISSUE TITLE
Foy scan Http 404

### ISSUE THREAD

**Issue by Reydelasombras** [keiyoushi/tachiyomi-extensions-source#5077]
### Source information

Foy Scan

### Source language

español

### Steps to reproduce

1. Abro la extensión
2. No carga

### Expected behavior

Debería cargar

### Actual behavior

No carga

### Mihon/Tachiyomi version

Tachiyomisyp 1.10.5

### Android version

Android 14

### Other details

No carga pero al abrir webview la página esta bien

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
:/

Why did you close out your issue? If you saw the PR #5081, that's still pending review & merge into the repo, and when it does get accepted, it'll automatically close out your issue along with it.
