### ISSUE TITLE
Read all comics

### ISSUE THREAD

**Issue by Sundogg17** [keiyoushi/tachiyomi-extensions-source#5082]
### Source information

Readallcomics 1.4.3

### Source language

English 

### Steps to reproduce

Open source, doesn't show covers

### Expected behavior

To open and show covers of titles searched

### Actual behavior

Says no covers when searching 
![Screenshot_20240915_191526_TachiyomiJ2K](https://github.com/user-attachments/assets/41350bb6-b6b0-4cb8-87f7-cb2d6a244155)

### Mihon/Tachiyomi version

Tachij2k 1.74 

### Android version

17

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
That's intended/intentional, since the site itself literally doesn't have thumbnails when searching.

![Screenshot_20240915_191819_Mihon.jpg](https://github.com/user-attachments/assets/0954edaa-2ad0-4429-a58a-60be356788eb)
