### ISSUE TITLE
Shinigami Domain Changed

### ISSUE THREAD

**Issue by Hannaichi** [keiyoushi/tachiyomi-extensions-source#5088]
### Source information

Shinigami 1.4.61

### Source language

Indonesian

### Source new URL

https://shinigami05.com

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Just in case, if you didn't know (and for anyone else having this issue), you can manually change the domain/URL in the Shinigami extension settings (Tachi/Mihon Browse Page > Extensions tab > Shinigami)

Restart the app after changing said URL & check WebView to pass Cloudflare verification, and the extension should work while you wait for someone to change thebasseUrl

**Comment by Kunaguero110** [comment]
Thanks sir
