### ISSUE TITLE
Bato not working

### ISSUE THREAD

**Issue by Ojouchan12** [keiyoushi/tachiyomi-extensions-source#5106]
### Source information

Host cannot be found

### Source language

English

### Steps to reproduce

Bato host cannot be detected for tachimanga
![D1EE4E08-44C7-4370-A0E7-D6A270F57C5E](https://github.com/user-attachments/assets/4efa0cd1-c46f-49d9-a920-acab4b7af193)

### Expected behavior

Open of manga list

### Actual behavior

Nothing is detected

### Mihon/Tachiyomi version

Tachimanga V3.3

### Android version

IOS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by lamaxama** [comment]
This is your network issue and has nothing to do with the extension.

**Comment by vetleledaal** [comment]
The Bato.to extension has several mirrors you can pick from the extension settings, so if the default site doesn't work you should change it and check.

In any case, it's not an issue with the extension. If changing the mirror doesn't help it's better if you ask in #support on Discord for easier troubleshooting.
