### ISSUE TITLE
Leer novelas 

### ISSUE THREAD

**Issue by Izma80** [keiyoushi/tachiyomi-extensions-source#5134]
### Source name

Nova encuentra tus novelas ligeras

### Source link

https://novelasligeras.net/

### Source language

Español 

### Other details

Si

### Acknowledgements

- [x] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Mihon/Tachi can't do novels, so it's pointless to make an extension for this site.
