### ISSUE TITLE
CosmicScans.id: URL changed

### ISSUE THREAD

**Issue by Smol-Ame** [keiyoushi/tachiyomi-extensions-source#5135]
### Source information

CosmicScans.id

### Source language

Indonesia

### Source new URL

https://cosmic1.co

### Other details

They've finalized & announced on their Discord that the homepage for CosmicScans.id is cosmictoon.co, but the manga web page is cosmic1.co

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by deathstalker654** [comment]
Cosmicscan.id udah close ga?
Ngapain nambah secondary, mending ganti aj linknya

**Comment by ShoujoLover** [comment]
> Cosmicscan.id udah close ga? Ngapain nambah secondary, mending ganti aj linknya

Nah, Just change the url and add baseurl override feature

**Comment by Smol-Ame** [comment]
Bruh, I had made the request to change the URL, then they brought the original site back, then I changed the issue to a feature request as a backup domain, and then they take it down again.

Seems like they confirmed that they're switching (their homepage) to cosmictoon, which still redirects to cosmic1.co

Wait for a future fix or migrate to a different source.

**Comment by deathstalker654** [comment]
Hopefully they fix it sooner, tachiyomi can't read the comic in this site till now
