### ISSUE TITLE
HenChan broken search

### ISSUE THREAD

**Issue by Oleksandrigo** [keiyoushi/tachiyomi-extensions-source#5140]
### Source information

HenChan 1.4.41

### Source language

Russian

### Steps to reproduce

Open the HenChan source in the inspection.
Click the search button by name
enter any name
Profit -> Http 404
WebView is also not working. But only the search page, the site itself and the manga all works

### Expected behavior

no error

### Actual behavior

Work search

### Mihon/Tachiyomi version

SY v1.10.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
> WebView is also not working.

Then it's a site issue and not something that can be solved in the extension.

You should instead contact the site admins to report issues with their site.
