### ISSUE TITLE
MSY new

### ISSUE THREAD

**Issue by ADPtechs** [keiyoushi/tachiyomi-extensions-source#5143]
### Source name

MSY Publisher

### Source link

https://msypublisher.com

### Source language

English

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Adjusted tags

Afteredit: Actually, closing in favor of #5412 since it contains more info & correct issue request
