### ISSUE TITLE
tachiyomi: Team X change its domain link

### ISSUE THREAD

**Issue by Boy656** [keiyoushi/tachiyomi-extensions-source#5147]
### Source information

tachiyomi: Team X 1.4.15

### Source language

arabic

### Source new URL

https://teamoney.site

### Other details

please update the extension with the new link and please add the ability to change the link over mihon like some other extension if it possible 
thanks

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
As mentioned by the auto-mod, the extension is already using that link, and from a quick test, seems like it's working fine.

If the extension version number you wrote there is correct, you're not using Keiyoushi's version of the same extension (1.4.18):
* Make sure you have Keiyoushi's repo link in your app, if you don't, follow the Keiyoushi website instructions: https://keiyoushi.github.io/docs/guides/getting-started
* After adding the repo in your app, uninstall your old extensions & reinstall the extensions afterwards

Also, it seems like the extension already has the ability for the user to change the baseUrl (if you were on the right version)

Come to the Keiyoushi Discord repo-support channel for any other questions/issues
