### ISSUE TITLE
 Problems with mangas.in

### ISSUE THREAD

**Issue by DarkShadow12564** [keiyoushi/tachiyomi-extensions-source#5154]
### Source name

Mangas.in

### Source language

Spanish

### Source link

https://mangas.in/

### Other details

I'm having trouble updating my manga library with the mangas.in extension, when I update I get an error of 60 mangas/manwhas that could not be updated due to "connection reset"
![Screenshot_20240921_115629_com brave browser](https://github.com/user-attachments/assets/3df14024-832f-44b4-8926-acefe00760f6)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
Label is wrong

**Comment by MikeZeDev** [comment]
Its m440.in anyway now, Domain changed.

**Comment by AwkwardPeak7** [comment]
#5264
