### ISSUE TITLE
change cosmic scans id

### ISSUE THREAD

**Issue by Xfyuxx** [keiyoushi/tachiyomi-extensions-source#5157]
### Source information

"CosmicScans.id" 1.4.33 

### Source language

Bahasa Indonesia

### Source new URL

https://cosmic1.co/

### Other details

change https://cosmicsans.id to https://cosmic1.co/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Duplicate of #5135
