### ISSUE TITLE
change domain cosmicscans id

### ISSUE THREAD

**Issue by Xfyuxx** [keiyoushi/tachiyomi-extensions-source#5160]
### Source information

"CosmicScans.id 1.4.33" 

### Source language

Bahasa Indonesia

### Source new URL

https://cosmic1.co/

### Other details

change domain cosmicscans.id to https://cosmic1.co/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Xfyuxx** [comment]
> Masalah ini ditutup karena ekstensi dengan URL yang disediakan (cosmicscans.id) sudah ada dengan nama **CosmicScans.id** , di bawah bagian **Bahasa Indonesia** .
> 
> _Ini adalah tindakan otomatis. Jika menurut Anda ini adalah kesalahan, silakan berikan komentar agar masalah ini dapat dibuka kembali jika diperlukan._

whatt

**Comment by Smol-Ame** [comment]
Already reported, duplicate of #5135

Search the existing issues before you open a new one, and acknowledge that you did when you didn't
