### ISSUE TITLE
[URL Change] Komikindo.co to komiksin.id

### ISSUE THREAD

**Issue by Kunaguero110** [keiyoushi/tachiyomi-extensions-source#5167]
### Source information

Komikindo.co 1.4.33

### Source language

Indonesia

### Source new URL

https://komiksin.id/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
I think it's a false close
