### ISSUE TITLE
Vortex Scans changed domains, again

### ISSUE THREAD

**Issue by NotPhoenic** [keiyoushi/tachiyomi-extensions-source#5169]
### Source information

Vortex Scans 1.4.38

### Source language

English

### Source new URL

https://vortexscans.org

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Kantotero** [comment]
It looks like the extension is redirecting to vortextoon which the wrong link, and vortexscans.org is the right url

**Comment by Bella777tempress** [comment]
Should a second extension be made?

**Comment by kavillock** [comment]
> Should a second extension be made?

Probably not, vortex toons looks like backup url

**Comment by Kantotero** [comment]
The extension just needs an update & fix vortextoons is a separate site

**Comment by 1aam2am1** [comment]
Yes it is separate site

**Comment by Xeiv** [comment]
I think they're both by vortex scans but vortextoon.com only has the shojo series while vortexscans.org has them all
