### ISSUE TITLE
Merlin Scans not work

### ISSUE THREAD

**Issue by Thekages** [keiyoushi/tachiyomi-extensions-source#5175]
### Source information

Merlin Scans 1.4.36

### Source language

Turkish

### Steps to reproduce

Dont open

### Expected behavior

Open

### Actual behavior

Dont open

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 11

### Other details

Manga thema changed .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Thekages** [comment]
Not working :(

**Comment by Smol-Ame** [comment]
Why would you close the issue & comment that it's not working if nothing's been done towards the issue?

Just in case reminder that kind contributors volunteer their time fixing issues, there's no guarantee that it'll be fixed soon or at all.

**Comment by ghost** [comment]
Yeah it's don't working pls fix :(

**Comment by vetleledaal** [comment]
Fixed by #5879
