### ISSUE TITLE
Void scan new domain

### ISSUE THREAD

**Issue by Gerardalbert21** [keiyoushi/tachiyomi-extensions-source#5187]
### Source information

Infernal Void Scans 1.4.38

### Source language

English 

### Source new URL

https://hivetoon.net/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Ubada03** [comment]
Fix when it's been 2 days

**Comment by Norsze** [comment]
We are waiting for you to get on your PC and fix it.

Notice how there are 350+ reports of issues and they keep increasing every day even though about 10-20 are fixed every day. 

This is volunteer work, no one is paying anyone here, so until a volunteer wants to take this on it will stay open. 

We have reports from months ago, all you can do is wait. Asking for ETAs is usually frowned upon and not appreciated around here. 

So just give a thumb up on whatever report you want attention to and don't comment unnecessarily or ask for time frames. 🙂
