### ISSUE TITLE
New source

### ISSUE THREAD

**Issue by Igrisredblood** [keiyoushi/tachiyomi-extensions-source#5190]
### Source name

Komiksin.id

### Source link

https://komiksin.id/

### Source language

Indonesian

### Other details

18+/NSFW = No

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Igrisredblood** [comment]
Why it closed?
It's real problem. When I open the extension komikindo.co 1.4.33, it doesn't work on app then i open on the browser by the app and i saw the domain changed to https://komiksin.id/

**Comment by Norsze** [comment]
@Igrisredblood you failed to read 4 times in a row. READ what you agreed to when filing the report and read what the bot responded in both your issue reports
