### ISSUE TITLE
Manga livre Site novo 

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#5192]
### Source name

Manga livre 

### Source link

https://mangalivre.one/

### Source language

português (Brasil)

### Other details

Eu não sei, o site ainda tá em desenvolvimento, eles vão começar a postar do capítulos das obras amanha

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by EvaldoCeBr** [comment]
Ta em construção!

**Comment by ghost** [comment]
> Ta em construção!

Eu sei, só mandei aqui pra eles já porem a extensão no app

**Comment by EvaldoCeBr** [comment]
Site está pronto, extensão já pode ser feita!

**Comment by AnonymousPtBr** [comment]
> Site está pronto, extensão já pode ser feita!

É verdade!
