### ISSUE TITLE
Reset Scans Changed Domain

### ISSUE THREAD

**Issue by MrEhh** [keiyoushi/tachiyomi-extensions-source#5197]
### Source information

Reset Scans 1.4.41

### Source language

English 

### Source new URL

https://rspro.xyz/

### Other details

Moved from old domain [reset-scans.co](url) to new domain [rspro.xyz](url)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by MrEhh** [comment]
This is not duplicate!, Domain change [reset-scans.co](url) to new domain [rspro.xyz](url)

**Comment by luizguilhermeg** [comment]
By the way, some of their series like Dungeon Reset are only present in their sub-site [Reset-Scans.xyz!](https://reset-scans.xyz/).
<img width="227" alt="image" src="https://github.com/user-attachments/assets/9165152c-1750-4d72-ac47-ca0b03d5135a">
