### ISSUE TITLE
Asura scans - NullPointerException 

### ISSUE THREAD

**Issue by shabnix** [keiyoushi/tachiyomi-extensions-source#5198]
### Source information

1.4.39

### Source language

English 

### Steps to reproduce

1. Open Asura scans
2. Fetch chapter list

### Expected behavior

Should fetch the chapters

### Actual behavior

Shows NullPointerExceptions

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

Popular and lastest tabs seems to work.
Opening already fetch chapters also seems to work. It's just the fetching of the chapter list that produces errors.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by tsunaproxD** [comment]
Yes, have the same problem :(

**Comment by hassakajin** [comment]
same here, both desktop and mobile

**Comment by Scarlov** [comment]
The same thing is happening for me. It is worth noting that when browsing the new chapter section in the extensions, all series that were updated still appear, it's just that you can't fetch the chapters now.

**Comment by Smol-Ame** [comment]
Yes, no need to confirm, it just emails everyone in this issue & pings the Discord for no reason. Just wait for update or migrate to a different source.
