### ISSUE TITLE
Add Harem scan  

### ISSUE THREAD

**Issue by celay10** [keiyoushi/tachiyomi-extensions-source#52]
### Source name

El Harem de Kira

### Source link

https://haremscann.es/

### Source language

Spanish

### Other details

NSFW: YES

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
That site seems to be under construction or just a template, there is nothing of value on it

**Comment by Norsze** [comment]
Is this [carteldemanhwas.com](carteldemanhwas.com) the new URL? If it is, it uses mangareader theme

**Comment by bapeey** [comment]
They are uploading to [CartelDeManhwas](https://carteldemanhwas.com) now, that extension already exist.
