### ISSUE TITLE
Infinity Scans not loading

### ISSUE THREAD

**Issue by Xeiv** [keiyoushi/tachiyomi-extensions-source#5200]
### Source information

InfinityScans 1.4.4

### Source language

English

### Steps to reproduce

Click browse or latest for the source

### Expected behavior

It shows all the series the source has

### Actual behavior

Blank screen that's loading

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Closing in favor of #5561
