### ISSUE TITLE
Asura Acans resulting in NullPointerException

### ISSUE THREAD

**Issue by InfinitePrimus** [keiyoushi/tachiyomi-extensions-source#5207]
### Source information

Asura Scans 1.4.39

### Source language

English

### Steps to reproduce

1. Go to manga with Asura Scan as the source
2. Attempt to reload the manga

### Expected behavior

Manga should reload with any new chapters. 

### Actual behavior

NullPointerException is given instead, with no new chapters even when there are new ones
![Screenshot_20240924_182515_Mihon](https://github.com/user-attachments/assets/5b8c9f1c-eafd-4ad8-8df9-651e518c5191)
.

### Mihon/Tachiyomi version

Mihon App version: 0.16.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Duplicate of #5198
