### ISSUE TITLE
Asura scan null issue not fixed

### ISSUE THREAD

**Issue by Gamermemer** [keiyoushi/tachiyomi-extensions-source#5226]
### Source information

Asura Scan

### Source language

English

### Steps to reproduce

Open
Open source 
Open comic
Refresh
Eror

### Expected behavior

Refresh 
New chapter should come

### Actual behavior

![Screenshot_20240925_200730_Tachiyomi](https://github.com/user-attachments/assets/17bb022e-a194-45cd-874b-954acb778e36)
Not able to refresh
![Screenshot_20240925_200730_Tachiyomi](https://github.com/user-attachments/assets/b4acf849-53fc-4ca8-9a25-5b23355b0bd3)

### Mihon/Tachiyomi version

Tachiyomi stable0.15.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Gamermemer** [comment]
This issue was raised in morning,  that issue was closed but the error stayed

**Comment by bapeey** [comment]
update your extension

**Comment by Gamermemer** [comment]
> update your extension

Already updated

**Comment by bapeey** [comment]
whats your extension version number?

**Comment by Gamermemer** [comment]
> whats your extension version number?

I have re instaled it and it is solved not

**Comment by jvmunhoz** [comment]
Also having problems with this. What should be the version number with the fix?

**Comment by Norsze** [comment]
Guys, you tell us what your version is, it's not supposed to be we tell you cause we honestly don't trust users anymore. Most users will just say they are using whatever version we ask. So it's easier if you tell us your version and we confirm it.

**Comment by jvmunhoz** [comment]
Lying about what your version is just plain stupid lmao.

I was at 1.4.39, and Tachimanga hadn’t prompted me for an update yet, despite me trying to trigger it. As fate would have it, it just prompted the update and now it works. Just wanted to be sure it was a Tachimanga issue.
