### ISSUE TITLE
ReadComicsOnline not downloading images

### ISSUE THREAD

**Issue by Fry-kun** [keiyoushi/tachiyomi-extensions-source#5230]
### Source information

ReadComicsOnline 1.4.11

### Source language

English 

### Steps to reproduce

Add https://readcomiconline.li/Comic/Star-Trek-2022, try to download a chapter

### Expected behavior

Images download

### Actual behavior

Errors

### Mihon/Tachiyomi version

0.16.5

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
The source info you put is for Read Comics Online, which uses .ru for the domain.

The link you provided that ends in .li is for ReadComicOnline (1.4.26). If the link is the right thing, then this is a duplicate of #4115

**Comment by Fry-kun** [comment]
My bad, the link is correct
