### ISSUE TITLE
Asura Scans - Not able to download or view new chapters 

### ISSUE THREAD

**Issue by Shk555420** [keiyoushi/tachiyomi-extensions-source#5241]
### Source information

Asura Scans 1.4.40

### Source language

English

### Source new URL

https://asurascans.com/

### Other details

The site's domain of has shifted. 

### Acknowledgements

- [X] I have updated all installed extensions.
- [ ] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Xyndra** [comment]
Note that the entire website is down so the extension working is impossible

**Comment by Gamermemer** [comment]
W8 till they update the new domain in the ext

**Comment by tsunaproxD** [comment]
Same here 😭

**Comment by Smognoggler** [comment]
Extension is still working. site is at asuracomic.net

**Comment by Norsze** [comment]
They ran into issues and reversed the domain change, everything seems to be working again, for now. So I'll close this issue
