### ISSUE TITLE
asurascans not functioning

### ISSUE THREAD

**Issue by xX1bigfishXx** [keiyoushi/tachiyomi-extensions-source#5242]
### Source information

Asurascans 1.4.40

### Source language

English

### Steps to reproduce

open manga from asurascans in web view 
403 in viewer, 404 on web view

### Expected behavior

view manga page/chapter

### Actual behavior

instant redirect to asurascans.com/$1 resulting in 404 error

### Mihon/Tachiyomi version

TachiyomiSY 1.10.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Duplicate of #5241
