### ISSUE TITLE
No content from the noxscans source is opening.

### ISSUE THREAD

**Issue by Bastankara** [keiyoushi/tachiyomi-extensions-source#5249]
### Source information

noxscans version 1.4.30 

### Source language

turkish

### Steps to reproduce

It says the page is not found because it requires source verification and does not open. It asks for verification that it is not a robot. Webview also opens.

### Expected behavior

should be opened

### Actual behavior

It says page not found and won't open.

### Mihon/Tachiyomi version

mihon 0.16.5

### Android version

android 11 

### Other details

I hope this source will be resolved as it is more up to date than other sources. Thank you in advance.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate/part of #4917
