### ISSUE TITLE
Infinity Scans Update Issue and no Thumbnails

### ISSUE THREAD

**Issue by CardinalBirb** [keiyoushi/tachiyomi-extensions-source#5257]
### Source information

InfinityScans 1.4.4

### Source language

English

### Steps to reproduce

1. Update library
2. Entries from InfinityScans report null

1. Have InfinityScans entries
2. No thumbnails and will not fetch them

### Expected behavior

They should be updating fine and have thumbnails

### Actual behavior

Null update and no thumbnails

### Mihon/Tachiyomi version

App version: 1.10.5 (standard, 6c563d7, 65, 2024-03-02T20:42Z) 

### Android version

Android 12

### Other details

I can search for entries fine and webview works. Just something funky happening.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Closing in favor/superceded by #5561
