### ISSUE TITLE
Ikiru

### ISSUE THREAD

**Issue by ShoujoLover** [keiyoushi/tachiyomi-extensions-source#5261]
### Source name

Ikiru

### Source link

https://ikiru.me

### Source language

Indonesia

### Other details

Rebranding of mangatale

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
Ikiru is old https://mangatale.id . Template is identical. Just make sure to download images without referer, cdn dont like it.
