### ISSUE TITLE
Mangas.in  updated web address 

### ISSUE THREAD

**Issue by Athrun0311** [keiyoushi/tachiyomi-extensions-source#5264]
### Source information

Mangasin 1.4.14

### Source language

Spanish 

### Source new URL

https://m440.in/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
Duplicate (but with appropriate tags ) of https://github.com/keiyoushi/extensions-source/issues/5154 perhaps?
