### ISSUE TITLE
Infernal Void Scan change there URL to Hivetoon

### ISSUE THREAD

**Issue by TheLonelyOtaku315** [keiyoushi/tachiyomi-extensions-source#5265]
### Source information

InfernalVoidScans, 1.4.32

### Source language

English

### Source new URL

https://hivetoon.net/

### Other details

I believe the old URL is something like: https://void-scans.com/
but the new URL is not : https://hivetoon.net/

If is possible to change and have access to the catalogue will be nice

I am using Tachiyomi version 0.15.3

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
If your extension's version is correct, then you're not using our/Keiyoushi's extension. The current Infernal Void Scans extension is 1.4.39, uninstall your old extension & reinstall it.

As for the link, it's already on hivetoon.net, and in your own "previous link", it redirects to hivetoon.com (the link before the current one), which tells you to go to the new site, hivetoon.net

**Comment by TheLonelyOtaku315** [comment]
I see, I forgot to uninstall the extension and reinstall it.

Thank you for the instruction
