### ISSUE TITLE
Lua Scans Cloudflare Issue

### ISSUE THREAD

**Issue by StephenLeeY** [keiyoushi/tachiyomi-extensions-source#5283]
### Source information

Lua Scans 1.4.37

### Source language

English

### Steps to reproduce

1. Add extension Lua Scans 1.4.37
2. Mark as trusted extension
3. Browse using Lua Scans 1.4.37

### Expected behavior

Titles should load correctly in the popular and latest categories

### Actual behavior

No results found in latest and popular categories

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 14

### Other details

Lua Scans works when using in browser, but not in app. See website: https://luacomic.net/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Extension works fine. In general, search the existing issues (for Cloudflare in your case) before opening a new issue, and acknowledging that you did when you didn't.

You just need to pass Cloudflare verification in WebView for the source, nothing to fix. See first picture for reference on where to click to verify in WebView and/or where to click for help to pass Cloudflare, or use the Keiyoushi websites troubleshooting docs: https://keiyoushi.github.io/docs/guides/troubleshooting#cloudflare

Come to the Keiyoushi GitHub repo-support channel for any extra help, or minor/basic questions/issues like this in general.

![Screenshot_20240927_171436_Mihon](https://github.com/user-attachments/assets/ac8f8098-2fad-489c-8bd8-0766b7ace94e)

![Screenshot_20240927_171448_Mihon](https://github.com/user-attachments/assets/cd8fbd9e-3bc9-4242-8b84-44456f4409e3)
