### ISSUE TITLE
Team x url change report

### ISSUE THREAD

**Issue by Potato8151** [keiyoushi/tachiyomi-extensions-source#5292]
### Source information

Team x 1.4.15

### Source language

Arabic 

### Source new URL

https://teamoney.site/

### Other details

Thank you 🙏😊

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
If your extension version number (that you wrote into the issue) is correct, then you're not using the Keiyoushi version of the extension. 

Double-check that you are using the Keiyoushi repo, and if you aren't, follow the guide via this link: 
https://keiyoushi.github.io/docs/guides/getting-started

The current Team X version is 1.4.18, uninstall your old extension & reinstall it. For extra help, or any other basic/minor questions/issues, come to the Keiyoushi Discord repo-support channel.
