### ISSUE TITLE
MangaHub: Manhwa Chapter Updates Shows HTTP 404 error

### ISSUE THREAD

**Issue by BlazeFrost09** [keiyoushi/tachiyomi-extensions-source#5299]
### Source information

MangaHub 1.4.38

### Source language

English 

### Steps to reproduce

1. HTTP 404 error in any Manhwa while refreshing for new chapter update.

### Expected behavior

1. After refreshing any Manhwa for new chapters it should have uploaded new chapter.

### Actual behavior

While refreshing any Manhwa for new chapter updates it shoes HTTP 404 error.

https://github.com/user-attachments/assets/2b766c8f-8026-4a1c-a9ff-cce535ba417e

![Screenshot_20240929_090251](https://github.com/user-attachments/assets/63624325-6425-4cb6-9f5a-195989b6e4b5)
![Screenshot_20240929_090243](https://github.com/user-attachments/assets/ee8f3833-3553-46ca-92de-30863ce6e503)

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Did you check WebView (or even in your own browser) as mentioned in the error?

Since you didn't reply, I'm guessing you did & realized what's wrong. If you didn't, well, the source itself is missing the manga pages on their own site, so not an extension-related issue currently.
