### ISSUE TITLE
Diskus Scan

### ISSUE THREAD

**Issue by domflamingo2** [keiyoushi/tachiyomi-extensions-source#530]
### Source information

Diskus Scan - português - 1.4.36

### Source language

Português

### Steps to reproduce

1 - download the extension: Diskus Scan 
2 - open the extension and go from error

![image](https://github.com/keiyoushi/extensions-source/assets/75938421/e41846e9-145d-4f09-8d4a-4e34fdefbb34)

### Expected behavior

Error Http 403

### Actual behavior

Webview is working.

![image](https://github.com/keiyoushi/extensions-source/assets/75938421/c682b3bd-52be-49a7-9fe7-c78beb96e543)

### Tachiyomi version

0.16.1

### Android version

Android 13

### Other details

please bot don't close '-';

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by domflamingo2** [comment]
@beerpiss, could you make the bot not close?

**Comment by beer-psi** [comment]
> @beerpiss, could you make the bot not close?

Try reading the acknowledgements carefully.

**Comment by domflamingo2** [comment]
> > @beerpiss, could you make the bot not close?
> 
> Try reading the acknowledgements carefully.

where I read that then.

**Comment by beer-psi** [comment]
> > > @beerpiss, could you make the bot not close?
> > 
> > 
> > Try reading the acknowledgements carefully.
> 
> where I read that then.

At the bottom of every issue?
