### ISSUE TITLE
Weeb Central Null pointer exception

### ISSUE THREAD

**Issue by sivajipro** [keiyoushi/tachiyomi-extensions-source#5313]
### Source information

Weeb Central 1.4.1

### Source language

English

### Steps to reproduce

When trying to manual update, its throw Null pointer exception.

### Expected behavior

Its should update

### Actual behavior

Show Null pointer exception

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

![Screenshot_2024-09-30-08-00-26-02_551f7f0ca926862b368845ce7ee433aa](https://github.com/user-attachments/assets/ede9a4a4-b113-4c5c-bdf5-82880d1da1fe)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Gh0stR1pp3r** [comment]
Not even error at the moment, just doesnt work at all.

**Comment by Expakun** [comment]
> Not even error at the moment, just doesnt work at all.

I can confirm this and want to add that the website itself works in my browser and in web view.

**Comment by Smol-Ame** [comment]
No need to confirm or comment if you don't have any extra info to add that will help a contributor figure out a fix. You're just emailing the author of the issue & pinging the server for no reason.

**Comment by Xori71** [comment]
Note to the contributor/s:

Consider disabling chapter downloads before bringing the extension back up. There are a lot of stupid users who mass download when they have no reason to, unnecessarily straining NepNep’s servers and fueling his disdain for the extension. We have to be pragmatic.
