### ISSUE TITLE
This extension is not working in tachiyomi j2k

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#5317]
### Source language

English

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
Missleading tag : Source is not down, its just behind Cloudflare captcha.. Standard Madara

**Comment by Norsze** [comment]
Extension works fine. In general, search the existing issues (for Cloudflare in your case) before opening a new issue, and acknowledging that you did when you didn't.

You just need to pass Cloudflare verification in WebView for the source, nothing to fix. See first picture for reference on where to click to verify in WebView and/or where to click for help to pass Cloudflare, or use the Keiyoushi websites troubleshooting docs: [keiyoushi.github.io/docs/guides/troubleshooting#cloudflare](https://keiyoushi.github.io/docs/guides/troubleshooting#cloudflare)

Come to the Keiyoushi GitHub repo-support channel for any extra help, or minor/basic questions/issues like this in general.
