### ISSUE TITLE
Diskus Scan: HTTP error 403

### ISSUE THREAD

**Issue by domflamingo2** [keiyoushi/tachiyomi-extensions-source#532]
### Source information

Diskus Scan - português - 1.4.36

### Source language

Português

### Steps to reproduce

1 - download the extension: Diskus Scan
2 - open the extension and go from error

### Expected behavior

Error Http 403

![image](https://github.com/keiyoushi/extensions-source/assets/75938421/ab4076af-417c-4f3a-9e43-f3981f6d2e19)

### Actual behavior

the webview is working, but the extension is not, it keeps giving Http error 403

![image](https://github.com/keiyoushi/extensions-source/assets/75938421/a3573ce8-fb4b-4e04-8ec3-0be046b23611)

### Tachiyomi version

0.16.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Duplicate of #375
