### ISSUE TITLE
Raw Otaku giving Unknown Error

### ISSUE THREAD

**Issue by FateXBlood** [keiyoushi/tachiyomi-extensions-source#5324]
### Source information

Raw Otaku 1.4.1

### Source language

Japanese

### Steps to reproduce

1. Click on the source
2. Click on any entry
3. Get hit by "Unknown Error" that does not load the chapter cover and maybe other details
4. This issue can be seen in this title https://rawotaku.com/read/%E3%82%AB%E3%83%AC%E3%82%B7%E3%81%8C%E3%81%84%E3%82%8B%E3%81%AE%E3%81%AB-raw/

### Expected behavior

It should show the chapter cover.

### Actual behavior

It does not show the chapter cover.

### Mihon/Tachiyomi version

TachiyomiJ2K 1.7.4

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by celtirelia** [comment]
I get this error on all titles all chapters, although in my case the cover is displayed
![Screenshot_20241201-043355](https://github.com/user-attachments/assets/26e21582-5a8e-4f36-a237-39df66a3c80c)

**Comment by Smol-Ame** [comment]
Superceded by #6518
