### ISSUE TITLE
NullPointerException: Null on Asura Scans

### ISSUE THREAD

**Issue by r1yoru** [keiyoushi/tachiyomi-extensions-source#5327]
### Source information

Asura Scans 1.4.41

### Source language

English 

### Steps to reproduce

![Screenshot_2024-10-01-17-42-33-404_app mihon](https://github.com/user-attachments/assets/c59b5351-0e61-462d-bb31-0cdb73834171)

i dont know what to explain but this what pop ups in all the library thats connected to the asura scan extension.

### Expected behavior

I expected that it will update new chapters or able to read

### Actual behavior

The message pop up as NullPointerException: Null which i dont know what it is

### Mihon/Tachiyomi version

Mihon Stable 0.16.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Migrate the title back into Asura Scans to update the URL.

Come to the Keiyoushi Discord repo-support channel for more help, especially with basic questions/issues
