### ISSUE TITLE
HotComics and DAYComics single chapter fetched issue

### ISSUE THREAD

**Issue by haramaseis** [keiyoushi/tachiyomi-extensions-source#5328]
### Describe why this should be added

![1290660298285645825remix-1727788835793](https://github.com/user-attachments/assets/48976f96-bcb9-4c29-a7dd-45b61a9e95ce)

HotComics 1.4.1 English
DAYComics.me 1.4.1 English

Yōkai 1.8.5.7 
TachiyomiJ2K 1.7.4

Recent fetching will only show one latest chapter (if the series completed) or one upcoming chapter (if the series is ongoing). 

 WebView works, link doesn't change (maybe, I don't remember the web but considering titles and a chapter is fetched that link should not change)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Bob111111111111111** [comment]
Using suwayomi, for those two sources, the problem I have is that the chapters are empty.  Website's fine, the comic info loads fine, the chapter list loads fine, but opening the chapters from suwayomi nothings loads (page count shows as 1 / 0). Also, downloading them starts and finish as if there's no problem but doesn't actually download anything
