### ISSUE TITLE
Increase kemono page limit

### ISSUE THREAD

**Issue by jpsantos665** [keiyoushi/tachiyomi-extensions-source#5336]
### Source name

Kemono

### Source language

Multi

### Describe your suggested feature

Browsing the extension I found this profile (https://kemono.su/patreon/user/11946658) it has 61 pages and the extension limit is 50, so I request an increase in the limit. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by KenjieDec** [comment]
You can increase the post limit in the extension's preference settings, no?
