### ISSUE TITLE
Ikigai Mangas cant load chapters

### ISSUE THREAD

**Issue by Felixer123456** [keiyoushi/tachiyomi-extensions-source#5339]
### Source information

Ikigai Mangas 1.4.17

### Source language

Spanish

### Steps to reproduce

Select a series and try to view a chapter

### Expected behavior

You can view the chapter

### Actual behavior

Error: Failed to connect to

### Mihon/Tachiyomi version

Tachiyomi SY preview r564

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
They are changing domains, wait a bit for their page to redirect correctly, if you know the new url you can put it in the extension settings

**Comment by kuvoid** [comment]
the new url is: https://visorikigai.imsin.net
