### ISSUE TITLE
manwa无法加载图片

### ISSUE THREAD

**Issue by dqw18cm** [keiyoushi/tachiyomi-extensions-source#5341]
### Source information

“Manwa1.4.7”

### Source language

“中文”

### Steps to reproduce

点击漫画无法加载进入
![Screenshot_20241003_132538](https://github.com/user-attachments/assets/f440751a-1351-4c31-90f5-b07df3db134c)

### Expected behavior

应该直接进入漫画并观看漫画

### Actual behavior

但出现了如图所示的提示并无法观看漫画
![Screenshot_20241003_132538](https://github.com/user-attachments/assets/3c61e542-4569-4951-8beb-3c441025d4ff)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by anenasa** [comment]
Manwa changed back the image list. For now you can use [extension version 1.4.5](https://github.com/keiyoushi/extensions/raw/4f817f40cd9a644ef0fbc4354a1c9eea7caac5ab/apk/tachiyomi-zh.manwa-v1.4.5.apk). If no one make a pull request, I can update the extension when I have time.

**Comment by a2847802037** [comment]
Please update, thank you

**Comment by Smol-Ame** [comment]
@a2847802037 Don't comment if you don't have anything to say that will help contributors figure out a fix. Unnecessarily emails everyone involved in the issue & pings the server channel.

There's 400~ issue requests and less than a handful of contributors volunteering their time & willingness to contribute into the repo. Wait for a fix, migrate to a different source, contribute yourself, or find something else to use.
