### ISSUE TITLE
Quero pedir a adição de uma nova extensão que surgiu no português brasileiro 

### ISSUE THREAD

**Issue by Jmigaiarin15** [keiyoushi/tachiyomi-extensions-source#5350]
### Source name

Tsuki Mangás 

### Source link

https://tsuki-mangas.com/

### Source language

Português brasileiro - PT-BR

### Other details

![Screenshot_2024-10-04-00-17-13-729_app mihon](https://github.com/user-attachments/assets/1d7c0373-4260-4c75-895a-0736395bb98b)
![Screenshot_2024-10-04-00-16-52-706_com android chrome](https://github.com/user-attachments/assets/25c173cd-6dd2-4aeb-8af5-5497845643f3)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Jmigaiarin15** [comment]
No idioma português não se encontra essa extensão

**Comment by Jmigaiarin15** [comment]
Tentei todas as maneiras de procurar mas não se encontra no repositório

**Comment by choppeh** [comment]
> Tentei todas as maneiras de procurar mas não se encontra no repositório

Entra no discord man e pede ajuda. Por ser que você não configurou o Repositorio de extensões ou esteja com PT-BR desabilitado no app, mas entra no discord que podem te ajudar
