### ISSUE TITLE
Request copymanga to be added

### ISSUE THREAD

**Issue by andrew020211** [keiyoushi/tachiyomi-extensions-source#5355]
### Source name

Copymanga(拷貝漫畫）

### Source link

www.copymanga.tv(international) /www.mangacopy.com(China)

### Source language

Chinese 

### Other details

18+=yes

This is a reliable source that has been running for years and well known in the Chinese manga reading community. I think it will be great if this source can be added.

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
See #4010

**Comment by andrew020211** [comment]
> See #4010

Oh thanks(nothing came up when i search the issues, sorry for the duplicate. it will be closed

**Comment by andrew020211** [comment]
Duplicate
