### ISSUE TITLE
Manga 18x

### ISSUE THREAD

**Issue by Sundogg17** [keiyoushi/tachiyomi-extensions-source#5360]
### Source information

Manga18x 1.4.36

### Source language

English 

### Steps to reproduce

Open source, doesn't load

### Expected behavior

To display the titles

### Actual behavior

Doesn't display, but webview works

### Mihon/Tachiyomi version

Tachij2k 1.74 

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by LefanHu** [comment]
Seems to be a source issue sometimes...

Other times... the site itself taking more than 40 seconds to respond to a request causing socket timeout
![image](https://github.com/user-attachments/assets/18e312b5-a050-4e8a-95c0-158dccb4b675)
![image](https://github.com/user-attachments/assets/1bad9c27-f323-402b-9aa6-b3ae46711357)
