### ISSUE TITLE
Galaxymanga (AR) 

### ISSUE THREAD

**Issue by Kinupsy-co** [keiyoushi/tachiyomi-extensions-source#5365]
### Source information

Galaxy 1.4.4

### Source language

Arabic 

### Source new URL

gxcomic.xyz

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
The mentioned domain is just an index that links back to the currently used domain. If you want to report an issue with the extension you should use the 'issue report' template.
