### ISSUE TITLE
roumanwu 1.4.10 bug

### ISSUE THREAD

**Issue by zhuangssh** [keiyoushi/tachiyomi-extensions-source#5374]
### Source information

1.4.10

### Source language

chinese

### Steps to reproduce

open roumanwu

### Expected behavior

Normal

### Actual behavior

![Uploading IMG_4306.png…]()

### Mihon/Tachiyomi version

0.16.*

### Android version

androp11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by zhuangssh** [comment]
![IMG_4306](https://github.com/user-attachments/assets/8e0c5d98-a34e-43e6-a5fd-73fd7894ed47)

**Comment by NeKoOuO** [comment]
Update 
![Screenshot_2024-10-06-17-20-38-177_app.komikku.beta-edit.jpg](https://github.com/user-attachments/assets/837d676d-3ee4-499e-bc86-d18e85604ec5)

**Comment by NeKoOuO** [comment]
Also, the website update to 18

**Comment by oalieno** [comment]
The original extension used `__NEXT_DATA__` to fetch data from the website written in Next.js. With the upgrade to a newer Next.js version 13 adopting the App Router, `__NEXT_DATA__` is no longer available. Apparently, the website has upgraded its Next.js recently. We now have to parse the HTML using jsoup.

I have successfully rewritten the extension to make it functional again. However, I am currently facing an issue with obtaining the manga image content due to Cloudflare protection, and FlareSolverr does not seem to resolve this. Is there any suggestion on resolving this and i can test that my fix works?

**Comment by oalieno** [comment]
I found that the request actually was not block by cloudflare. The response i get is indeed the `image/jpeg` and can be viewed when i saved the file manually. Probably some other issue.

**Comment by oalieno** [comment]
I have resolved the issue, will make a pull request now.

**Comment by NeKoOuO** [comment]
> I have resolved the issue, will make a pull request now

Wow! Thanks ❤️

**Comment by zhuangssh** [comment]
My version still doesn't work, there is no version to update

**Comment by oalieno** [comment]
Hold on a second, the pull request is still pending review...

**Comment by NeKoOuO** [comment]
@oalieno the old version had a problem with website changing the main website and mirror one can't change on the extension setting

**Comment by NeKoOuO** [comment]
It seems your PR didn't change the website setting I only see you change the Chinese script of description so I think this problem still exists

**Comment by zhuangssh** [comment]
So slow, waited for so long

**Comment by Smol-Ame** [comment]
@zhuangssh Don't comment if you don't have anything useful to say that will help a contributor with a fix. You're unnecessarily emailing everyone involved in the issue request & pinging the server channel.

Contributors volunteering their time & willingness to fix issues around the repo. There's 390~ open issues currently and less than a handful of contributors. Be patient, wait for a fix, migrate to a different source, contribute yourself, or find something else to use.

After-edit: Plus, you can see that there's a discussion going on & linked PR trying to implement a fix.

**Comment by zhuangssh** [comment]
@oalieno After I updated the version, I found that it did not jump to the next page normally.
