### ISSUE TITLE
Some sources for Arabic languages is cloudflare need update 

### ISSUE THREAD

**Issue by AhmedMahsen** [keiyoushi/tachiyomi-extensions-source#5375]
### Source name

A lot of sources need update

### Source language

Arabic 

### Source link

Some sources for Arabic languages is cloudflare need update 

### Other details

Some sources for Arabic languages is cloudflare 
And need update to work

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
'a lot' is not a source.

For Cloudflare issues, make sure you go through the [troubleshooting guide](https://keiyoushi.github.io/docs/guides/troubleshooting#cloudflare) first. If it still doesn't work, you can create separate issues with the appropriate issue type. Just make sure you don't create duplicate issues.

**Comment by AhmedMahsen** [comment]
Just updating the source and anything be great
Thanks you for your work big thanks bro
