### ISSUE TITLE
Traducciones Amistosas 

### ISSUE THREAD

**Issue by ashliepolanco** [keiyoushi/tachiyomi-extensions-source#5378]
### Source information

Traducciones Amistosas 1.4.3

### Source language

Spanish

### Source new URL

https://traduccionesamistosas.eyudud.net/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Genzales6** [comment]
Not only did I change the domain, I also designed the website.
![Captura de pantalla_5-10-2024_183258_traduccionesamistosas eyudud net](https://github.com/user-attachments/assets/3e81b45f-833a-4021-a24e-7b9dd5ed7c8c)
