### ISSUE TITLE
GoDa manga error 

### ISSUE THREAD

**Issue by NeKoOuO** [keiyoushi/tachiyomi-extensions-source#5386]
### Source information

GoDa 1.4.31

### Source language

Chinese 

### Steps to reproduce

https://github.com/user-attachments/assets/d9795a8b-eec8-4101-873e-05c69ed3ef64

### Expected behavior

It should work fine as the second one

### Actual behavior

Some chapters, specially the newest one shows error when I click the chapter

### Mihon/Tachiyomi version

0.16.X

### Android version

Android 13

### Other details

Log 10-06 17:31
[komikku_crash_logs.txt](https://github.com/user-attachments/files/17268795/komikku_crash_logs.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ReanSchwarzer9029** [comment]
![image](https://github.com/user-attachments/assets/0ab5d943-d9c3-4dab-a97e-fefbca05d831)

Dropping screenshot of the error

**Comment by yigedajiaque** [comment]
我也遇到了一样的情况。

**Comment by oalieno** [comment]
This is zh.baozimhorg extension. The API has moved to `https://api-get-v2.mgsearcher.com`. Although the old `https://api-get.mgsearcher.com` is still avaliable, the json structure has changed. In the `PageListParse`, it need to get the `data.info.images.images` instead of `data.info.images`. 
I have fix the code and test it on my local, will make a pull request soon.
