### ISSUE TITLE
[URL change] KomikIndo

### ISSUE THREAD

**Issue by raisalfs** [keiyoushi/tachiyomi-extensions-source#5387]
### Source information

KomikIndo 1.4.30

### Source language

Indonesia

### Source new URL

https://komikindo.icu/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by vivalafreak1** [comment]
What is the previous URL?

**Comment by raisalfs** [comment]
komikindo.sbs

**Comment by raisalfs** [comment]
> https://komikindo.sbs/
