### ISSUE TITLE
connection closed

### ISSUE THREAD

**Issue by soraniconico** [keiyoushi/tachiyomi-extensions-source#5389]
### Source information

E-HENTAI 1.4.20

### Source language

English

### Steps to reproduce

when trying to download the manga which on e-Hentai. The download process always stops when there are only a few pages left and shows  “connection closed.” This issue only occurs with the e-Hentai. last week it was working perfectly fine, but now I’m unable to download anything at all.

### Expected behavior

This should download successfully but not. 

### Actual behavior

It's only happened on e-HENTAI.
I also tried to change my internet or vpn,But it doesn't work,don't know what's happened with it. 

### Mihon/Tachiyomi version

0.16.5

### Android version

Android12

### Other details

I have already tried to solve this problem, but I haven't been able to resolve it.
I would greatly appreciate your help in resolving this issue. apologize for my poor English.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by LefanHu** [comment]
Can't seem to reproduce the problem.... not sure about anyone else

**Comment by Norsze** [comment]
Closing as it is not reproduceable
