### ISSUE TITLE
TürkToon is down

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#539]
### Source name

TürkToon

### Source language

Turkish 

### Source link

https://turktoon.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
This issue didn't close automatically. My bad.

PR: https://github.com/keiyoushi/extensions-source/pull/1312

**Comment by stevenyomi** [comment]
Removed in #1312
