### ISSUE TITLE
VIZ Extension doesn't work with AZ

### ISSUE THREAD

**Issue by japzone1** [keiyoushi/tachiyomi-extensions-source#5393]
### Source information

VIZ 1.4.20

### Source language

English

### Steps to reproduce

1. Install TachiyomiAZ
2. Install VIZ extension
3. Browse for a manga and open a chapter 
4. Pages won't load

### Expected behavior

Pages should load

### Actual behavior

No pages load

### Mihon/Tachiyomi version

TachiyomiAZ v8.8.1-AZ

### Android version

Android 14

### Other details

Extension works fine in normal Mihon with pages loading as expected, but pages don't load in TachiyomiAZ. I did a fresh install of AZ and the issue persists. Other extensions work fine. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
If extension works correctly with mihon, then it is AZ issue, please report it to their github
