### ISSUE TITLE
Arven Scans Theme Changed

### ISSUE THREAD

**Issue by Salinda001** [keiyoushi/tachiyomi-extensions-source#5403]
### Source information

Arven Scans 1.4.30

### Source language

English

### Source new URL

https://arvencomics.com

### Other details

Not showing manga on extension. 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Wrong issue request, make one with the issue report, not URL change

**Comment by Salinda001** [comment]
This is not a duplicate. Arven Scans theme has changed
