### ISSUE TITLE
Access to manga saved on local network. No third-party programs.

### ISSUE THREAD

**Issue by Heavyarms04** [keiyoushi/tachiyomi-extensions-source#5408]
### Source name

Red local smb1

### Source language

English 

### Describe your suggested feature

Being able to connect over the network to a hard drive connected to a modem (To a local network for example 10.78.71.101 or 192.168.1.1) without having to use third-party applications such as komga Ideally, it would work like a browser and you could locate the manga you want to read live or with the possibility of downloading it. Sorry if I can't understand but English is not my native language.

Here are some reference images, thank you again for the time you can dedicate to this little dream.

![Screenshot_20241007_072620_Comic Screen](https://github.com/user-attachments/assets/1ec072b3-9abf-4a21-9a5d-1389b7d96fc5)
![Screenshot_20241007_072637_Comic Screen](https://github.com/user-attachments/assets/f6c43e38-0a37-4f78-b325-5cf5d75412e3)
![Screenshot_20241007_072714_Comic Screen](https://github.com/user-attachments/assets/6347b207-d739-4b38-8cee-689f071487f9)
![Screenshot_20241007_072800_Comic Screen](https://github.com/user-attachments/assets/a010e027-e7b8-4cb0-96b8-b00401790c5c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Isn't this basically the same as #1395 ? If you wanted to add more details you can edit that issue instead.
