### ISSUE TITLE
Tonari no Young Jump - NullPointerException: null

### ISSUE THREAD

**Issue by Syokhan** [keiyoushi/tachiyomi-extensions-source#5410]
### Source information

Tonari no Young Jump 1.4.5

### Source language

Japanese

### Steps to reproduce

1. Open a Tonari no Young Jump manga from either the library (for an existing entry) or the source tab (for a new manga)
2. Try to update chapters (existing entry) or display available chapters (new manga)

### Expected behavior

An existing entry should be updated, and a new entry should display a list of available chapters.

### Actual behavior

It displays a "NullPointerException: null" message and fails to update . Trying this on a new entry when exploring the source fails to display any chapter at all.

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by hatozuki-programmer** [comment]
This appears to be caused by the same issue as #4993 

It's an issue with the GigaViewer class not being able to find certain div elements.
