### ISSUE TITLE
msy domain changed 

### ISSUE THREAD

**Issue by Rasun0** [keiyoushi/tachiyomi-extensions-source#5412]
### Source information

msy fanyi 1.4.36

### Source language

English 

### Source new URL

https://msypublisher.com/

### Other details

![Screenshot_20241007_215818](https://github.com/user-attachments/assets/27cb9a1e-200c-43b3-9220-6f3d9249bcd2)
changed to a whole new website yesterday so pls update the extension soon or fix it thanx.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Reopened, supercedes #5143, added previous Theme tag

**Comment by dngonz** [comment]
Site is down
