### ISSUE TITLE
zaimanhua/再漫画 BUG

### ISSUE THREAD

**Issue by Volundio** [keiyoushi/tachiyomi-extensions-source#5414]
### Source information

zaimanhua 1.4.1

### Source language

Chinese

### Steps to reproduce

正常阅读漫画

### Expected behavior

漫画图片正常加载

### Actual behavior

每部阅读几十页后就有高概率出现一页加载失败，并且后续所有页数都是加载失败，且点击重试也是加载失败，只有重启mihon app后才可以重新正常加载漫画图片。其他插件都不会这样，只有再漫画插件频繁出现这个问题，缓存也都清过了。
![Screenshot_2024-10-07-03-24-57-079_app mihon](https://github.com/user-attachments/assets/ae985d77-07d4-4beb-a24b-0045b425d6e6)

### Mihon/Tachiyomi version

mihon 0.16.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by zhongfly** [comment]
也不能算是bug
背景知识：再漫画目前漫画图片链接的有效期较短，约5分钟，过期就失效了。

mihon的漫画图片在阅读时按需预加载的，只加载当前图片和后面几个，不会一次性下载全部。类似于在线视频网站的缓存，避免一次性消耗过多的内存和网络带宽。预加载逻辑在大部分图片/视频类应用中都广泛存在。
因此你打开一个章节5分钟后，剩下还没加载的图片链接就已经过期失效了，所以就加载失效了。
这是软件预加载与网站配置矛盾的问题，插件方面不知道如何处理，等其他有缘人来想办法吧。
当前建议看之前下载整章节，或者把软件的预加载设置调至最大（设置-阅读-页面预加载数量）

为什么官方app不会？因为他们压根没做预加载，只要打开一个章节就会开始下载整个章节……

The comic image link is only valid for 5 minutes, need to find a way to call fetchPageList again to get a new image link when the comic image fetch fails.

**Comment by Volundio** [comment]
> 也不能算是bug 背景知识：再漫画目前漫画图片链接的有效期较短，约5分钟，过期就失效了。
> 
> mihon的漫画图片在阅读时按需预加载的，只加载当前图片和后面几个，不会一次性下载全部。类似于在线视频网站的缓存，避免一次性消耗过多的内存和网络带宽。预加载逻辑在大部分图片/视频类应用中都广泛存在。 因此你打开一个章节5分钟后，剩下还没加载的图片链接就已经过期失效了，所以就加载失效了。 这是软件预加载与网站配置矛盾的问题，插件方面不知道如何处理，等其他有缘人来想办法吧。 当前建议看之前下载整章节，或者把软件的预加载设置调至最大（设置-阅读-页面预加载数量）
> 
> 为什么官方app不会？因为他们压根没做预加载，只要打开一个章节就会开始下载整个章节……
> 
> The comic image link is only valid for 5 minutes, need to find a way to call fetchPageList again to get a new image link when the comic image fetch fails.

难绷，他们家服务器带宽费不要钱的吗，直接下载全话....
同等个有缘人来救一下插件吧.....

**Comment by zhongfly** [comment]
> 难绷，他们家服务器带宽费不要钱的吗，直接下载全话.... 同等个有缘人来救一下插件吧.....

官方app的最新测试版，已经改为内置mihon/tachiyomi了，结果一样出现了这个问题(笑死，这下官方也干了

**Comment by Volundio** [comment]
> > 难绷，他们家服务器带宽费不要钱的吗，直接下载全话.... 同等个有缘人来救一下插件吧.....
> 
> 官方app的最新测试版，已经改为内置mihon/tachiyomi了，结果一样出现了这个问题(笑死，这下官方也干了

再漫画APP内置mihon/tachiyomi？这是什么操作
