### ISSUE TITLE
SpyFakku: Add display manga title as full title, show favorites only, offset result by # pages

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#5415]
### Source name

SpyFakku

### Source language

English

### Describe your suggested feature

![IMG_20241008_045211](https://github.com/user-attachments/assets/a170f437-d529-4164-a683-8ea936e6ca65)

-Display manga title as full title, the site show full title below the short title, please allow full title to display from setting 

![IMG_20241008_045147](https://github.com/user-attachments/assets/19947572-44b9-4536-bed5-b8dc7f224b40)

-Show favorite only, there is favorites function from the site

-Offset result by # pages is very useful when browsing the catalog from the app, it help prevent lags

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by KenjieDec** [comment]
> - Display manga title as full title, the site show full title below the short title, please allow full title to display from setting

Could you please give an example of a manga with a full title? Thank you.

**Comment by sadboy889** [comment]
> Could you please give an example of a manga with a full title? Thank you.

![IMG_20241009_050717](https://github.com/user-attachments/assets/0a9d6fbc-d874-45cc-b05d-4243b0842cd6)
![IMG_20241009_050339](https://github.com/user-attachments/assets/1bc7a832-83c5-4a5d-912b-e5765e29264a)
