### ISSUE TITLE
Genz Toons Domain Change

### ISSUE THREAD

**Issue by Salinda001** [keiyoushi/tachiyomi-extensions-source#5445]
### Source information

Genz Toons 1.4.34

### Source language

English

### Source new URL

https://genzupdates.com/

### Other details

The old domain still works but the newly released  chapters mentioned updated chapters are now in this new site. 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by AryanMithbawkar** [comment]
When will the source be released I can't find it

**Comment by Smol-Ame** [comment]
@AryanMithbawkar the issue request is still open so it hasn't been fixed/the extension hasn't gotten this URL change yet.

There's less than a handful of contributors volunteering their time & willingness to fix the issues within the repo. There's 380~ issues currently, so wait patiently for a fix, migrate to a different source, contribute yourself, or go somewhere else.

**Comment by AryanMithbawkar** [comment]
I thought it was added

**Comment by lavavex** [comment]
The folder for genz is still under the old name of SuryaScans, found and updated the url

**Comment by AryanMithbawkar** [comment]
Is the update available? I couldn't find it as shown about

**Comment by Smol-Ame** [comment]
@AryanMithbawkar this issue that you're commenting in is still open. Any of the issues mentioned in the comments section are just duplicate issues referencing this issue, stop asking & just wait.
