### ISSUE TITLE
manwa-Internal Server Error

### ISSUE THREAD

**Issue by mayu1995matsuoka** [keiyoushi/tachiyomi-extensions-source#5458]
### Source information

manwa-v1.4.7

### Source language

Chinese

### Steps to reproduce

Read any comic from manwa

### Expected behavior

Enter the reading interface normally and load images correctly.

### Actual behavior

![IMG_0963](https://github.com/user-attachments/assets/be473c9d-5afe-4fdd-b4f5-8a77795b5c75)

### Mihon/Tachiyomi version

Mihon v0.16.5

### Android version

Android 14

### Other details

But in webview, the manga can be normally read.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate/part of #5341
