### ISSUE TITLE
L scans Failed to bypass cloudflare.

### ISSUE THREAD

**Issue by AnonymousPtBr** [keiyoushi/tachiyomi-extensions-source#5464]
### Source information

L scans 1.4.36

### Source language

Portuguese Brazilian 

### Steps to reproduce

When opening the source, an error appears when bypassing cloudflare. The site opens in WebView and in the browser.

![Screenshot_2024-10-10-19-39-31-688_app mihon](https://github.com/user-attachments/assets/67953c77-5f50-441d-8aba-99c7e9d079f1)
![Screenshot_2024-10-10-19-39-50-967_app mihon](https://github.com/user-attachments/assets/b0f04b1f-ea86-46c8-972a-1fd81fcf912d)
![Screenshot_2024-10-10-19-40-04-802_com android chrome](https://github.com/user-attachments/assets/02cb57c4-8af7-4969-9b02-6d4b16a7d9a2)

### Expected behavior

Show the contents of the Source.

### Actual behavior

Failed to bypass cloudflare.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
You probably didn't refresh/back out of the Browse Page for the extension after passing Cloudflare. That error will go away once you do that, however, it seems like the site changed something as well which broke the extension.

I've made a new issue for you #5465, don't comment there unless you have something helpful for contributors to figure out a fix & don't ask for a fix. Follow that issue if you want to receive notifications for extra troubleshooting or whenever it gets closed (from a fix)
