### ISSUE TITLE
L Scans: HTTP 404 error

### ISSUE THREAD

**Issue by Smol-Ame** [keiyoushi/tachiyomi-extensions-source#5465]
### Source information

L Scans 1.4.36

### Source language

Portuguese (Brazil)

### Steps to reproduce

1) Go into source's browse
2) After passing Cloudflare verification, and refreshing, Latest/Popular/search brings up "HTTP 404, check website in WebView" error

### Expected behavior

Should load/bring up results

### Actual behavior

Doesn't load/bring up results

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

Maybe selector/theme changed, dunno myself

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Theme changed to PeachScan
