### ISSUE TITLE
Pururin is dead

### ISSUE THREAD

**Issue by MikeZeDev** [keiyoushi/tachiyomi-extensions-source#5473]
### Source name

doesnt matter

### Source language

doesnt matter

### Source link

pururin.to

### Other details

![image](https://github.com/user-attachments/assets/3d93d633-4280-4fb8-af34-f2c3cd791ded)

Since it doesnt mean anything, check manually and see a wonderful "Seized by FBI" picture.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by GrEgStAr3000** [comment]
Yup.
