### ISSUE TITLE
Put recent button in Manga Livre source Pt-Br 

### ISSUE THREAD

**Issue by AnonymousPtBr** [keiyoushi/tachiyomi-extensions-source#5480]
### Source name

Manga Livre 1.4.1

### Source language

Portuguese Brazilian 

### Describe your suggested feature

Place a recent button in Manga Livre source and, if possible, the filter option.

![IMG_20241011_123807](https://github.com/user-attachments/assets/42c4743b-4f92-47f8-8a27-2d1c33730947)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
Popular and Recent are the same thing, so you don't need the recent tab.

So I think the issue can be closed
