### ISSUE TITLE
Hunters Scan changed URL.

### ISSUE THREAD

**Issue by Behemoths15** [keiyoushi/tachiyomi-extensions-source#5482]
### Source information

Hunters Scans 1.4.40

### Source language

Portuguese Brazilian

### Source new URL

https://htoons.online/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by AnonymousPtBr** [comment]
Mudaram hj não foi?
