### ISSUE TITLE
Ikigai Mangas 1.4.18

### ISSUE THREAD

**Issue by ingridsterphane** [keiyoushi/tachiyomi-extensions-source#5486]
### Source information

Ikigai Mangas 1.4.18

### Source language

Español ( ES)

### Source new URL

https://lectorikigai.acamu.net/

### Other details

![Screenshot_2024-10-11-23-31-57-129_app komikku beta](https://github.com/user-attachments/assets/85d9585f-25c1-4872-a33b-40b38cb85f85)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
The extension is already using that domain internally, you can see what domain it is using if you press the webview button inside a manga or chapter. Also you can change the domain in extension settings
