### ISSUE TITLE
extension tachiyomi

### ISSUE THREAD

**Issue by Wapoll** [keiyoushi/tachiyomi-extensions-source#5488]
### Source information

masalah tidak bisa menginstal

### Source language

Bahasa Indonesia 

### Steps to reproduce

tidak dapat menginstal extension manual dan otomatis

### Expected behavior

bisa menginstal extension lewat manual dan otomatis

### Actual behavior

tidak dapat menginstal 

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 10

### Other details

tidak bisa menginstal 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Come to the Keiyoushi repo-support for troubleshooting, makes it easier to communicate & get more info.
