### ISSUE TITLE
tidak bisa menginstal ekstensi 

### ISSUE THREAD

**Issue by Wapoll** [keiyoushi/tachiyomi-extensions-source#5489]
### Source information

masalah tidak bisa menginstal

### Source language

Bahasa Indonesia 

### Steps to reproduce

![Screenshot_2024-10-12-11-42-49-07](https://github.com/user-attachments/assets/a1465cd4-e0ff-45d8-a52b-edac27938401)

### Expected behavior

bisa menginstal ekstensi manual dan otomatis 

### Actual behavior

![Screenshot_2024-10-12-11-42-49-07](https://github.com/user-attachments/assets/8646cf6f-edcb-4ef1-b85c-a8a4caf17745)

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 10

### Other details

saya tidak bisa menginstal ekstensi lewat jalur manual dan otomatis, saya sudah mencari tau bagaimana cara nya namun tetap tidak bisa
![Screenshot_2024-10-12-11-42-49-07](https://github.com/user-attachments/assets/a13b4624-f7a3-4977-ac79-5067bb3338a8)

jika kalian melihat foto nya disitu saya sudah memakai ekstensi yang sebelumnya 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Wapoll** [comment]
how to fix it?

**Comment by Smol-Ame** [comment]
You need to uninstall all of your old Tachiyomi extensions before you can update into Keiyoushi's version of the same extension since they are signed by different organizations/people.

Come to the Keiyoushi Discord repo-support channel for more help or if you have any questions, as mentioned in your previous issue request I closed.

**Comment by Wapoll** [comment]
> You need to uninstall all of your old Tachiyomi extensions before you can update into Keiyoushi's version of the same extension since they are signed by different organizations/people.
> 
> Come to the Keiyoushi Discord repo-support channel for more help or if you have any questions, as mentioned in your previous issue request I closed.

I have deleted all the old extensions but still can't install 
do i need to delete the app too? or delete the previous backup

**Comment by Norsze** [comment]
> Come to the Keiyoushi Discord repo-support channel for more help.

**DISCORD**
