### ISSUE TITLE
[URL Change] Dua Leo Truyen

### ISSUE THREAD

**Issue by jayqism** [keiyoushi/tachiyomi-extensions-source#5497]
### Source information

Dua Leo Truyen 1.4.5

### Source language

Vietnamese

### Source new URL

https://dualeotruyenbff.com

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
~The domain has not been changed. Updated at https://github.com/keiyoushi/extensions-source/pull/5053~

~Issue can be closed~

Current domain: https://dualeotruyenman.com
