### ISSUE TITLE
Fail to bypass claudfire

### ISSUE THREAD

**Issue by Nerannnn** [keiyoushi/tachiyomi-extensions-source#55]
### Source information

Mangás-chan 1.4.28

### Source language

Portuguese 

### Steps to reproduce

whenever I open the extension a message appears saying failure to bypass claudfire and even if I clear the cookies or open it in webview the problem does not resolve. and I even managed to open the extension at times, but when the site updates a work the problem returns

### Expected behavior

open and update manga normally

### Actual behavior

message saying failure to bypass claudfire even when in the webview it passed normally

### Tachiyomi version

0.15.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kairusds** [comment]
Which extensions does this?

**Comment by Nerannnn** [comment]
Mangás chan, portuguese Brazilian, a I tried uninstalling and reinstalling
the extension, as a user told me, but it didn't work

Em ter., 9 de jan. de 2024 21:43, harveyhans ***@***.***>
escreveu:

**Comment by Nerannnn** [comment]
I think it's back to normal now I'll report anything again

Em ter., 9 de jan. de 2024 21:58, Renan Nascimento Costa <
***@***.***> escreveu:

**Comment by beer-psi** [comment]
Refer to the **Solving Cloudflare issues** section at https://tachiyomi.org/docs/guides/troubleshooting/#cloudflare. If it doesn't work, migrate to other sources or wait until they lower their protection.

**Comment by Nerannnn** [comment]
I noticed something, this problem happens every time the site updates a
chapter

Em qua., 10 de jan. de 2024 04:38, beerpsi ***@***.***>
escreveu:
