### ISSUE TITLE
Zaimanhua can't search for resources through the search box in the bookshelf!

### ISSUE THREAD

**Issue by hsiayuchih** [keiyoushi/tachiyomi-extensions-source#5512]
### Source information

1.4.2

### Source language

chinese

### Steps to reproduce

Can't find the comic results in the bookshelf, you can only search for the comic by searching in the image source！

### Expected behavior

Search results like any other manga source.

### Actual behavior

Can't find the comic results in the bookshelf.

### Mihon/Tachiyomi version

TachiyomiSY V1.10.5

### Android version

Android14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Edited for clearer instructions:

* Screen record the issue if you can, no NSFW content in the recording please
* Upload the video here
* If you are able to come to the Keiyoushi Discord repo-support channel for more troubleshooting/extra info, that would be great too. You can also upload the video in that channel as well, in case I head off to sleep.

**Comment by zhongfly** [comment]
需要注意的是，SY有bug或者特殊的地方，书架的搜索框默认只会搜索“置顶”了的图源
![Screenshot_2024-10-13-20-53-57-811_eu kanade tachiyomi sy-edit](https://github.com/user-attachments/assets/28802542-7817-44f9-9da5-2303a4289bef)

请检查是否置顶了相应的图源，或者切换为“全部”

也欢迎加入tachiyomi/mihoon非官方(unofficial)中文讨论群(telegram) 进行沟通交流https://t.me/+z8WWWO43FAYzNjk1

**Comment by hsiayuchih** [comment]
> 需要注意的是，SY有bug或者特殊的地方，书架的搜索框默认只会搜索“置顶”了的图源 ![Screenshot_2024-10-13-20-53-57-811_eu kanade tachiyomi sy-edit](https://private-user-images.githubusercontent.com/11155705/376036111-28802542-7817-44f9-9da5-2303a4289bef.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MjQ3NjQsIm5iZiI6MTcyODgyNDQ2NCwicGF0aCI6Ii8xMTE1NTcwNS8zNzYwMzYxMTEtMjg4MDI1NDItNzgxNy00NGY5LTlkYTUtMjMwM2E0Mjg5YmVmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDEzMDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MGMyYjM2NjdhNzAxNjIyMGQyNDg4ZTBlZGI1OTk2MDdkYjlkMTg3ODI2ZTA0NGI3NTMzNWU2YmI1ZGIyMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z7mLsIZpRHUg-tnd2UMkSCYa-u9Obxy_Y9KPhK4LcqI)
> 
> 请检查是否置顶了相应的图源，或者切换为“全部”
> 
> 也欢迎加入tachiyomi/mihoon非官方(unofficial)中文讨论群(telegram) 进行沟通交流https://t.me/+z8WWWO43FAYzNjk1

确实是这个原因，感谢解答！
