### ISSUE TITLE
Weeb Central: "No results found" upon opening the source

### ISSUE THREAD

**Issue by Fmoment1** [keiyoushi/tachiyomi-extensions-source#5514]
### Source information

Weeb Central 1.4.1

### Source language

English

### Steps to reproduce

1. Browse the source

### Expected behavior

We should be able to see the manga available in the source or search for something.

### Actual behavior

Being greeted with "no results found"

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 11

### Other details

Trying to read a manga previously added to the library from this source yields a "No pages found" toast error.

The source website itself is functional and does not require solving a Cloudflare captcha.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate/part of #5313
