### ISSUE TITLE
pururin. RIP, domain seized

### ISSUE THREAD

**Issue by Wyld-One** [keiyoushi/tachiyomi-extensions-source#5515]
### Source name

pururin  - et. all

### Source language

all

### Source link

pururin.to

### Other details

java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
Domain seized

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Duplicate of #5473
