### ISSUE TITLE
Asura extension not showing Everything Available

### ISSUE THREAD

**Issue by Creepler13** [keiyoushi/tachiyomi-extensions-source#5517]
### Source information

Asura Scans 1.4.41

### Source language

English

### Steps to reproduce

Search for tutorial

### Expected behavior

![grafik](https://github.com/user-attachments/assets/c5009d88-8a73-4148-80b4-c6c82d3b4ce6)

### Actual behavior

![grafik](https://github.com/user-attachments/assets/1b925b8d-3f00-49b0-9885-489b2b263d23)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Shows up fine for me, probably a site hiccup.

Closing, come to the Keiyoushi Discord repo-support channel for more help/questions if you are still encountering this.
![Screenshot_20241013_122252_Mihon](https://github.com/user-attachments/assets/416cbf2d-7731-4379-b48a-fff444333dfa)
