### ISSUE TITLE
Maneha.net Errors 

### ISSUE THREAD

**Issue by julioxd123** [keiyoushi/tachiyomi-extensions-source#5520]
### Source information

Manwha.net

### Source language

Spanish

### Steps to reproduce

The page has a clo The page does not allow loading chapters due to an alleged failure in the cloudfore 

### Expected behavior

.

### Actual behavior

.

### Mihon/Tachiyomi version

.

### Android version

.

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
?blurb cf

**Comment by Smol-Ame** [comment]
First thing, the "Failed to bypass Cloudflare" error isn't an extension-related issue. That is the source's way to protect itself from spam/bots. Either follow the Keiyoushi Cloudflare troubleshooting guide, or click the button for help in the app (as shown in the first picture), and learn how to pass the verification on your end.

Second, seems like the site itself is having server-related issues, nothing anyone can do besides waiting for the site owners to fix their shit (see second picture).

Finally, last thing, actually fill out the issue request.

If you have any other questions/basic issues, come to the Keiyoushi Discord repo-support channel for help.

![Screenshot_20241013_220905_Mihon](https://github.com/user-attachments/assets/46f9d4c6-e47c-4615-9101-2ada21ffc3fb)

![Screenshot_20241013_220607_Mihon](https://github.com/user-attachments/assets/eb2f29b3-af78-4fe2-a2f9-718ecbe8c2c2)
