### ISSUE TITLE
Inarimanga changed URL

### ISSUE THREAD

**Issue by Athrun0311** [keiyoushi/tachiyomi-extensions-source#5522]
### Source information

Inarimanga 1.4.42

### Source language

Spanish 

### Source new URL

https://rukavpay.org/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Athrun0311** [comment]
> Este problema se cerró porque es un duplicado de #5363 .
> 
> _Esta es una acción automática. Si cree que se trata de un error, comente al respecto para que se pueda volver a abrir el problema si es necesario._

Inarimanga y ukyo se fusionan en una web. Como inarimanga es la principal. darle prioridad al cambio de dominio

**Comment by Smol-Ame** [comment]
Yeah, it's already mentioned in the open issue request (mentioned in the bot message above). Wait for a fix or migrate to a different source.
