### ISSUE TITLE
Koinobori Scan 404

### ISSUE THREAD

**Issue by Refresco2x** [keiyoushi/tachiyomi-extensions-source#5534]
### Source information

Koinobori Scan 1.4.37

### Source language

Spanish

### Steps to reproduce

1. Entrance to the extension 
2. I wait for the load and the error appears 
3. I log in through the website and it loads there, but not in the app.

![Screenshot_20241014_194133_Aniyomi](https://github.com/user-attachments/assets/82d66d68-a703-4834-beef-88a0ff25b439)

### Expected behavior

The projects should appear 

### Actual behavior

But when loading it gives http 404 and is not displayed 

### Mihon/Tachiyomi version

r6938

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Edited:

Actually (don't quote me), they might've changed something in their API which broke the extension. Wait for a fix or migrate to a different source
