### ISSUE TITLE
Comick Chapter Id not found

### ISSUE THREAD

**Issue by w00ogly** [keiyoushi/tachiyomi-extensions-source#5536]
### Source information

Comick 1.4.47

### Source language

English

### Steps to reproduce

1. Filter scan groups
2. Reset filter
3. Choose chapter from different scan

### Expected behavior

Read chapter like normal

### Actual behavior

![Screenshot_20241014_221721_Ykai](https://github.com/user-attachments/assets/864fb23a-0206-4dcc-a050-55d756f8f035)
![Screenshot_20241014_221409_Ykai](https://github.com/user-attachments/assets/c64c1ebf-bf86-4e6b-806b-8ea7647bbdb5)

### Mihon/Tachiyomi version

Yokai 1.8.5.9

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
That's an app-related issue since the app is the one handling the filtering (and it works fine on Mihon), check with Yokai GitHub instead
