### ISSUE TITLE
roumanwu 1.4.11bug

### ISSUE THREAD

**Issue by zhuangssh** [keiyoushi/tachiyomi-extensions-source#5538]
### Source information

1.4.11

### Source language

chinese 

### Steps to reproduce

1、Scroll screen

### Expected behavior

Normal page turning

### Actual behavior

Unable to turn pages

### Mihon/Tachiyomi version

0.16.3

### Android version

android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
* Can you be a bit more descriptive about your issue? "Page not turning" doesn't help with diagnosing/identifying what the problem would be.
* You can write in Chinese if you can't write English, or use translation software/sites like DeepL or Google Translate, to better explain the issue you are experiencing.
* You can screen record the issue you are experiencing if you can't write/explain the issue, no not-safe-for-work/18+ content in the screen recording please.
* Jot down the names of the entries & chapter you are having this issue as well
* Come to the Keiyoushi Discord server, repo-support channel if you have any questions/issues about the steps/recommendations above, or to communicate/troubleshoot faster if someone is online at the time.

**Comment by zhuangssh** [comment]
怎么说呢，就是没办法翻页呀，只显示一页的内容，正常不是滚动到底部，默认加载第二页内容吗？现在没有加载啊

**Comment by zhuangssh** [comment]
@Smol-Ame How can I put it? I just can't turn the page. It only shows one page of content. Normally, shouldn't it scroll to the bottom and load the second page by default? Now it's not loading.

**Comment by Smol-Ame** [comment]
What's the entry name & chapter that is doing this? Is this issue for every entry & every chapter?

**Comment by zhuangssh** [comment]
Not in the chapter, but in the table of contents
![Screenshot_20241015_193045](https://github.com/user-attachments/assets/61d9a177-c2e7-4ccc-8230-726d46e38419)

**Comment by zhuangssh** [comment]
@Smol-Ame On the catalog page, scrolling to the end does not load the next page of content，As shown in the figure above

**Comment by Smol-Ame** [comment]
Yeah, next time a little more info please.

It's intentional in the code to get it working/to display the Latest/Popular sections from the new site.

Closing as not an issue, search on the site & then search in the source to find titles outside of those sections.

![Screenshot_20241015_043214_GitHub.png](https://github.com/user-attachments/assets/b86aceb7-2866-4925-bebc-0d832ece865f)

![Screenshot_20241015_043038_Firefox Nightly.jpg](https://github.com/user-attachments/assets/1215f8bb-9cc4-440a-b931-d23676af4a24)

**Comment by zhuangssh** [comment]
OK, I understand.
