### ISSUE TITLE
Change Domain (TukangKomik ID)

### ISSUE THREAD

**Issue by ChriszZ8** [keiyoushi/tachiyomi-extensions-source#5540]
### Source information

TukangKomik

### Source language

Indonesia 🇮🇩

### Source new URL

https://tukangkomik.co/

### Other details

![Uploading Screenshot_2024-10-15-19-38-30-135_app.komikku.beta.jpg…]()

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by vivalafreak1** [comment]
I cannot open the screenshot,

**Comment by ChriszZ8** [comment]
![Screenshot_2024-10-15-19-38-30-135_app komikku beta](https://github.com/user-attachments/assets/8535935b-1017-4ca2-a7f7-6b288f38923b) old domain Tukangkomik.id change to TukangKomik.co
