### ISSUE TITLE
6manhua has changed domain.

### ISSUE THREAD

**Issue by ZerOri** [keiyoushi/tachiyomi-extensions-source#556]
### Source information

6manhua 1.4.9

### Source language

中文(Chinese)

### Source new URL

m.liumanhua.com

### Other details
Sharing the same domain with qiximanhua.com

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Theme changed, working on it.

**Comment by hsiayuchih** [comment]
![Uploading 微信图片_20240131120716.jpg…]()
