### ISSUE TITLE
InfinityScans Theme Change

### ISSUE THREAD

**Issue by Salinda001** [keiyoushi/tachiyomi-extensions-source#5561]
### Source information

InfinityScans 1.4.4

### Source language

English

### Steps to reproduce

1. Go to Sources
2. Select InfinityScans

### Expected behavior

1. Go to Sources
2. Select InfinityScans
3. Shows Manga lists

### Actual behavior

Not Showing Manga Lists

### Mihon/Tachiyomi version

Yokai 1.8.5.9 / Mihon 0.16.5

### Android version

Android 14

### Other details

Before the Theme Changed InfinityScans Extension, Mangas did not Show Thumbnails (return null)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ManiV97** [comment]
The extension is not working, error: "HTTPS 404"
![Screenshot_20241019_001202](https://github.com/user-attachments/assets/520b1b06-0254-4274-8c31-b793c0dfabb0)
The Webview of the extension is working
![Screenshot_20241019_001229](https://github.com/user-attachments/assets/b1c44a64-2e26-4c1c-a539-563138dc0901)

**Comment by Salinda001** [comment]
This is a theme change. Also if the theme is keyoapp check the image hosting is igniscans.com.

**Comment by 1aam2am1** [comment]
> keyoapp

This is not 'keyoapp', could you check with theme it is?
Or do I need to update this custom one?

**Comment by Salinda001** [comment]
> > keyoapp
> 
> This is not 'keyoapp', could you check with theme it is? Or do I need to update this custom one?

I do not know what theme it is. I posted this issue cuz they have changed the theme. The reason I mentioned "keyoapp" is b'cuz recently keyoapp themed manga sites had changed their image upload server so the extension didn't display chapters. If this is a keyoapp theme I just reminded to check the image server is corrected.

**Comment by Salinda001** [comment]
Is this going to take long to fixed?

**Comment by Norsze** [comment]
No ETA. If you read the project main page you'd see this clearly written:

> Please note that creating an issue does not mean that the source will be added or fixed in a timely fashion, because the work is volunteer-based. Some sources may also be impossible to do or prohibitively difficult to maintain.

**Comment by 1aam2am1** [comment]
I don't know how to do this, based on my analysis:
1. By going first time to site: https://infinityscans.net/comics?sort=latest it will:
set-cookie:
InfinityScans=xxxxxxxxxxxxxxxxxxxx; expires=Sat, 10 Nov 2025 22:07:43 GMT; Max-Age=31536000; path=/
2. Will use cokie to do request to https://infinityscans.net/api/verification to enable this cookie by sending 'cf-turnstile-response: 0.YPbL........'
3. After that will use 'https://infinityscans.net/api/comics'   -H 'accept: application/json, text/javascript, */*; q=0.01'  -H 'cookie: InfinityScans=xxxxxxxxxxxxxxxxxxxx'  -H 'referer: https://infinityscans.net/comics?sort=latest' -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'   -H 'x-requested-with: XMLHttpRequest'
to get json response with comics
![image](https://github.com/user-attachments/assets/24ffae75-f694-437a-8de1-42e8caf33368)

I think other data will be similar.
I don't know how to do this.
