### ISSUE TITLE
Manga livre erro

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#5568]
### Source information

Manga Livre 1.4.1

### Source language

Português (Brasil)

### Steps to reproduce

Quando eu vou abrir as capítulos das obras no Webview aparece o que está no vídeo abaixo  

https://github.com/user-attachments/assets/d76919b3-1932-4689-9a73-23b69ee6d6fa

### Expected behavior

Abrir o capítulo no site normalmente 

### Actual behavior

![Screenshot_20241018-022030](https://github.com/user-attachments/assets/7a1dbffc-839c-4a91-88a9-70217826e0b8)

### Mihon/Tachiyomi version

Tachiyomi SY 1.10.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
The direct link to the chapter url doesn't work in this source.

Example: https://mangalivre.one/manga/reader/9212.

The issue can be closed because it is a missing feature on the site

**Comment by AwkwardPeak7** [comment]
#5760
