### ISSUE TITLE
Magus Manga Page Domain Expired

### ISSUE THREAD

**Issue by Aragolt** [keiyoushi/tachiyomi-extensions-source#5592]
### Source information

Magus Manga 1.4.42

### Source language

English

### Steps to reproduce

1. Select any manga on the Magus Manga extension (for example, Black Killer Whale Baby)
2. Click on any chapter to attempt reading

### Expected behavior

The first page of the chapter should load and let you begin reading.

### Actual behavior

None of the pages load. Clocking "Open in Webview" reveals that thr domain has expired, so they may be uploading their pages to a new domain. 

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Seems like they might've changed CDNs/hosting sites for their manga pages, source's own domain isn't dead*.

**Comment by Salinda001** [comment]
> Seems like they might've changed CDNs/hosting sites for their manga pages, source's own domain isn't dead*.

Yes, Genz Toon (Genz Updates) also have the same issue and I don't know whether other extensions have the same issue if so I will comment on this issue.

**Comment by MikeZeDev** [comment]
It seems all Keyoapp websites are affected at this point .
