### ISSUE TITLE
Reset Scan Default Home Page URL Changed

### ISSUE THREAD

**Issue by Salinda001** [keiyoushi/tachiyomi-extensions-source#5596]
### Source information

Reset Scans 1.4.42

### Source language

English

### Source new URL

https://rspro.xyz/home/

### Other details

Previously the home page URL was "https://rspro.xyz".

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Salinda001** [comment]
The #5340 issue is the site of their beta website design. Currently this is the website they are now updating the manga's.

**Comment by Smol-Ame** [comment]
Auto-closed cause the site is technically still on the same link
