### ISSUE TITLE
Kewnscans chapters leads to igniscans

### ISSUE THREAD

**Issue by Xdxz** [keiyoushi/tachiyomi-extensions-source#5598]
### Source information

Kewn Scans 1.4.8

### Source language

English

### Steps to reproduce

1. find a chapter, any chapter will suffice
2. the image won't load.
3. when opened in webview, it will lead to igniscans

https://github.com/user-attachments/assets/eaa05d01-38b3-468c-a720-bb44b476cfba

![Screenshot_2024-10-19-20-12-19-83_551f7f0ca926862b368845ce7ee433aa](https://github.com/user-attachments/assets/d8fff890-df86-4f45-86dc-440c0aa15808)
![Screenshot_2024-10-19-20-15-47-23_551f7f0ca926862b368845ce7ee433aa](https://github.com/user-attachments/assets/89bfa343-df5f-4d41-9a16-6272bffb4c67)
![Screenshot_2024-10-19-20-15-53-35_551f7f0ca926862b368845ce7ee433aa](https://github.com/user-attachments/assets/23c2a138-62e5-4c49-adb9-6b26f102843d)

### Expected behavior

the chapters should load and when in webview of those chapters, it would lead to the website

### Actual behavior

it doesn't load the images of the chapters and when in webview of those chapters, it will lead to https://cdn.igniscans.com

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

the webview of the manhwa/manga and the the extension it self leads to the website but the chapters lead to igniscans.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AriaDeAzure** [comment]
I just passed by to add that the same thing has been happening to Lua Scans and Necro Scans. It's highly likely it's related to the paid chapters feature they all have.
