### ISSUE TITLE
Manga Livre Erro de paginas

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#5605]
### Source information

Manga Livre 1.4.1

### Source language

Português (Brasil)

### Steps to reproduce

As páginas da obra no aplicativo tá diferente do Webview

https://github.com/user-attachments/assets/3c22e059-ba53-4913-a4aa-b92298c0b80d

### Expected behavior

As páginas iguais 

### Actual behavior

As páginas da obra tão diferente do aplicativo para o Webview

### Mihon/Tachiyomi version

Tachiyomi SY 1.10.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Loads fine for me, try reloading the chapter list

**Comment by AwkwardPeak7** [comment]
#5760
