### ISSUE TITLE
Astrum Scan - redirected to: “LWB”

### ISSUE THREAD

**Issue by domflamingo2** [keiyoushi/tachiyomi-extensions-source#5612]
### Source name

Astrum Scans

### Source language

Português

### Source link

https://astrumscans.xyz/

### Other details

I don't know what happened to her: Astrum Scan, but it's been offline for a while and is redirecting to another site!

![image](https://github.com/user-attachments/assets/3f671475-f232-43ea-bdbd-6154c30dc7ac)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
Fechando o site deles, e fazendo fusão de scans
![image](https://github.com/user-attachments/assets/47e4107a-5052-4ac5-b7ba-58602e3fedc8)
