### ISSUE TITLE
Asura

### ISSUE THREAD

**Issue by Zack133** [keiyoushi/tachiyomi-extensions-source#5614]
### Source information

Asura Scans 1.4.58

### Source language

English

### Steps to reproduce

Opened extension 
HTTP 404
Opened Webview
Refreshed
Still same error

### Expected behavior

Should be able operating properly 

### Actual behavior

Was unable to see site on tachiyomi

### Mihon/Tachiyomi version

0.15.2

### Android version

Galaxy S10+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
1. That's not our extension, uninstall it and reinstall it after adding our repo (our Asura is 1.4.41)
2. Tachiyomi is dead, switch to Mihon
3. Come to the Keiyoushi Discord repo-support channel for any extension/repo related questions about this
