### ISSUE TITLE
Genz toons chapters only opening in web view 

### ISSUE THREAD

**Issue by AryanMithbawkar** [keiyoushi/tachiyomi-extensions-source#5619]
### Source information

1.4.36

### Source language

ENGLISH 

### Steps to reproduce

1. Open genz toons extension 
2. Open a comic 
3. Open a chapter not loading 
4. Open Web view it's loading 

### Expected behavior

Should on chapters in normal view 

### Actual behavior

Not opening chapters in normal view only in web view and can't download either
![Screenshot_20241021_002150_eu kanade tachiyomi j2k](https://github.com/user-attachments/assets/54131e7b-8fd3-4cd2-9bf4-73116d638589)
![Screenshot_20241021_002155_eu kanade tachiyomi j2k](https://github.com/user-attachments/assets/0fca5768-b3b5-402a-a540-9ad51f8ee8bd)

### Mihon/Tachiyomi version

1.7.4

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Their image hosting site/CDN's servers are down, not an extension-related issue.

![Screenshot_20241020_121527_Mihon.png](https://github.com/user-attachments/assets/5de82593-5c18-4d1e-86c7-9caee5d645d6)

![Screenshot_20241020_121842_Mihon.png](https://github.com/user-attachments/assets/e2973629-8f73-4073-822f-9c582144636d)

**Comment by AryanMithbawkar** [comment]
Server is up and running where I'm from still not working

**Comment by AryanMithbawkar** [comment]
Screen shot of current time
![Screenshot_20241021_005558_eu kanade tachiyomi j2k](https://github.com/user-attachments/assets/74203e3e-0a65-4463-989c-c863ae44db1f)
![Screenshot_20241021_005604_eu kanade tachiyomi j2k](https://github.com/user-attachments/assets/58e17fcf-2e9a-47c2-a70b-fc33576057bb)

**Comment by Smol-Ame** [comment]
Reopening cause contributor mentioned other related issue.

The source's website ≠ the source's site that they use to host manga pages
