### ISSUE TITLE
ManhuaZone error 502

### ISSUE THREAD

**Issue by Ayush62** [keiyoushi/tachiyomi-extensions-source#5622]
### Source information

ManhuaZone

### Source language

English

### Steps to reproduce

1. open source ManhuaZone error 502 (Doesn't work)

![WhatsApp Image 2024-10-20 at 23 40 07_6ad231c8](https://github.com/user-attachments/assets/06733b6f-f182-424d-9155-b1f41c15f8e6)

2. open webview (Works)

![WhatsApp Image 2024-10-20 at 23 40 07_2b423908](https://github.com/user-attachments/assets/ededb2c1-2661-42eb-8dde-f1d67f620809)

### Expected behavior

open the source in the app and be able to read/download Manhua.

### Actual behavior

opens source and gets error 502.

### Mihon/Tachiyomi version

stable 0.16.5

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Actually try searching on their own site (either in WebView or your own browser)
