### ISSUE TITLE
Manytoon related extensions have problem 

### ISSUE THREAD

**Issue by Achuabdu** [keiyoushi/tachiyomi-extensions-source#5627]
### Source information

Manytoon.me 1.4.41 / Adultwebtoon 1.4.39 / mangahentai 1.4.39 / manhwa hentai 1.4.36 / manhwa hentai.me 1.4.43 / Hentaiwebtoon 1.4.38
/ Hentaimanga 1.4.38

### Source language

English 

### Steps to reproduce

When opening the source it will not show anything 
While searching also the same problem 
But in web view it's working 

### Expected behavior

Can access the source 

### Actual behavior

Cant access the source through the extension 

### Mihon/Tachiyomi version

Tachiyomi 0.15.3 and tachiyomi sy 1.10.5

### Android version

Android 4

### Other details

https://adultwebtoon.com/
https://mangahentai.me/
https://manhwahentai.me/
https://manytoon.me/
https://hentaiwebtoon.com/
https://hentaimanga.me/
These all have the same problem  so I have put it all in one

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Learn to search existing issues (instead of opening duplicate ones & acknowledging that you did when you didn't), check WebView for errors, and to come to the Keiyoushi Discord repo-support channel for basic troubleshooting

**Comment by Achuabdu** [comment]
It's not one source all the extension have problem if search also work chapters will be not there

**Comment by Achuabdu** [comment]
But we can access this with web view

**Comment by Smol-Ame** [comment]
1. Don't group issues, since one fix for one extension will close out an issue with multiple ones listed in it.
2. I checked like 4 different extensions you listed as having an issue, and they all loaded up fine
3. Come to the Keiyoushi Discord repo-support channel, learn to do basic troubleshooting

No further answers after this message

**Comment by Achuabdu** [comment]
Ok
