### ISSUE TITLE
Image hosting website is down

### ISSUE THREAD

**Issue by Salinda001** [keiyoushi/tachiyomi-extensions-source#5629]
### Source information

Arven Scans 1.4.31, Genz Toons 1.4.36, Lua Scans 1.4.37, Magus Manga 1.4.42, Rezo Scans 1.4.7

### Source language

English

### Steps to reproduce

1. Go to Sources
2. Select one of the above sources
3. Select a Manga
4. Select a Chapter 

### Expected behavior

Should sbow Chapter Images

### Actual behavior

Not Showing Chapter Images.

### Mihon/Tachiyomi version

Yokai 1.8.5.9 / Mihon 0.16.5

### Android version

Android 14

### Other details

Their image hosting site "https://igniscans.com" is no longer working. All the above mentioned sources used this hosting site to upload their chapters. The above sources are the ones that I'm currently using and I checked other sources that I use. So, these are the only sources that has this issue. I don't whether other sources have this issue so you will have check the sources that's uses this hosting site. 
_________________________________________________________

![Screenshot_20241021-121539](https://github.com/user-attachments/assets/1a12e051-6ea1-4e47-98fd-e0d05930ce1e)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Xeiv** [comment]
I think it's the same issue that was solved in #5619 but it hasn't been applied to the other sources

**Comment by Salinda001** [comment]
I think they changed it again. The GenzToons 1.4.37 extension that was recently updated have the same issue now. #5664 has mentioned this issue.
_________________________________________________________

![Screenshot_20241024-120102](https://github.com/user-attachments/assets/52ee21d3-822a-44bc-b3d3-89073a0245cd)
