### ISSUE TITLE
Truyenvn

### ISSUE THREAD

**Issue by takahashikajima** [keiyoushi/tachiyomi-extensions-source#564]
### Source name

Truyenvn

### Source link

https://truyenvn.club/

### Source language

Vietnamese

### Other details

Yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by takahashikajima** [comment]
Pls Make truyenvn :(

**Comment by Smol-Ame** [comment]
Just be patient & don't bump or edit the issue request without reason. You're just going to end up annoying the maintainers.

**Comment by Karutovn** [comment]
> Pls Make truyenvn :(

English: Pls waiting for person create code for this source 
Vietnamese: chờ đợi xem có ai làm không đã (nếu dc thì bro thử học kotlin vs lại đọc phần contribute này để tạo source nhé)
https://github.com/keiyoushi/extensions-source/blob/main/CONTRIBUTING.md
