### ISSUE TITLE
Wrong source URL for Vyvymanga in newest version

### ISSUE THREAD

**Issue by mentlmelody** [keiyoushi/tachiyomi-extensions-source#5641]
### Source information

Vyvymanga 1.4.36

### Source language

English

### Source new URL

vyvymanga.net

### Other details

The newest version of the vyvymanga extension uses the wrong url. Vyvymanga.org is not the official site. Official url is vyvymanga.net

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
I am eager to know which one is the "good" one too because users will definitely complains.

**Comment by mentlmelody** [comment]
> I am eager to know which one is the "good" one too because users will definitely complains.

I'm just going based off the way the site looked before the URL change. Also the .org URL brings up alot of malicious site pop ups nor does it use cloudflare; where as, the original site (and the .net URL), did not flag as malicious and used cloudflare checks.

**Comment by aoba-seragakii** [comment]
I've noticed that in the .org url some manga is missing

**Comment by MikeZeDev** [comment]
.net
![image](https://github.com/user-attachments/assets/cf0d91e6-b81a-4bdc-a375-7d1b86a70dff)

vs org

![image](https://github.com/user-attachments/assets/b06c6e8d-fa5e-4a24-a22d-3b03615454ed)

Not sure it could help to make a decision, just saying.
