### ISSUE TITLE
URL change Reaper Scans FR 

### ISSUE THREAD

**Issue by LucienLF** [keiyoushi/tachiyomi-extensions-source#5643]
### Source information

Reaper Scans Français 1.4.36

### Source language

French

### Source new URL

https://reaper-scans.fr/

### Other details

Hi,
Its change from https://reaperscans.fr/ to https://reaper-scans.fr/
Thank for your work !!

### Acknowledgements

- [X] I have updated all installed extensions.
- [ ] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
And they use Keyoapp now
