### ISSUE TITLE
Mangaholic changed to radiantscan org to https://tcbscans.cc/manga/

### ISSUE THREAD

**Issue by Achuabdu** [keiyoushi/tachiyomi-extensions-source#5657]
### Source information

Mangaholic 1.4.40

### Source language

English 

### Source new URL

https://tcbscans.cc/manga/
### Other details

![Screenshot_2024-10-25-23-35-44-753_com opera browser afin](https://github.com/user-attachments/assets/71c9a8d8-05cc-45fb-bf02-41d167188c8c)
![Screenshot_2024-10-25-23-35-39-757_com opera browser afin](https://github.com/user-attachments/assets/7f16c760-0387-408b-a5d7-cfe8291341d5)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
![image](https://github.com/user-attachments/assets/e92baed6-9193-4396-abe4-fbf662102905)

And .com gives 

![image](https://github.com/user-attachments/assets/8d765290-d3be-438e-a4b3-4fa0f7863c00)

**Comment by Achuabdu** [comment]
It's not the real radiant  mangaholic website changes there url often and I think it's just temporarily down because they changed url yesterday only and it was working well till afternoon

**Comment by vetleledaal** [comment]
Domain doesn't have any A records, so I'd say the extension should be removed instead.
