### ISSUE TITLE
Animated Glitched Scans domian changed

### ISSUE THREAD

**Issue by prem-k-r** [keiyoushi/tachiyomi-extensions-source#5661]
### Source information

1.4.31

### Source language

English

### Source new URL

https://anigliscans.xyz/

### Acknowledgements

- [X] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by prem-k-r** [comment]
![image](https://github.com/user-attachments/assets/900474af-ccde-493f-925b-27069a2b6e37)

**Comment by prem-k-r** [comment]
Reopen

**Comment by Smol-Ame** [comment]
This is a domain change issue request, but the domain hasn't changed.

Also, both Animated Glitch links have their own extensions, actually search in your app or on the Keiyoushi website extensions list.
