### ISSUE TITLE
MyReadingManga unable to load in webview

### ISSUE THREAD

**Issue by CactusTheGuy** [keiyoushi/tachiyomi-extensions-source#5675]
### Source information

MyReadingManga 1.4.53

### Source language

English

### Steps to reproduce

1. Open webview from MyReadingManga extension
2. Error show "NOT FOUND"

### Expected behavior

Be able to properly load the website after manual cloudflare verify like in the typical browser.

### Actual behavior

Error show "NOT FOUND" on loading in webview

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 13 MIUI 14.0.8

### Other details

This site is known for only able to do a manual cloudflare **ONLY**.
Since the webview is broken lead to unable to do cloudflare verify lead to extension broken.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by edajio** [comment]
Experiencing the exact same issue with TachiyomiJ2K v1.7.4. This started happening after the new MRM extension commit three days ago.

**Comment by CactusTheGuy** [comment]
> Experiencing the exact same issue with TachiyomiJ2K v1.7.4. This started happening after the new MRM extension commit three days ago.

Can confirmed this with TachiyomiSY 1.10.5

**Comment by happywillow0** [comment]
The past few updates shouldn't have caused this. I also double checked and there wasn't any changes on the website end. My best guess is the outdated user agent string possibly catching within cloudflare protection. I would bump the user agent to a more current version. 

I am currently having issues building and testing on my computer so it'll take a bit longer from me if no one else looks into it.

**Comment by kokounet** [comment]
Is there any way to fix this? The extension is unusable since the update
using mihon 0.17.0 on Android 15 Pixel 6

**Comment by Smol-Ame** [comment]
@kokounet You can see that the issue is still open, and there's no workaround mentioned or fix linked to this issue.

Just follow the issue rather than unnecessarily commenting, since it emails everyone involved in this issue, and pings the server channel. There's over 400~ issues in the repo with less than a handful of contributors volunteering their time & willingness to fixing these issues. Wait patiently, migrate to a different source, contribute yourself, or find something else to use.

**Comment by xdeiimoss** [comment]
I have downloaded the version 1.4.51 and it works
1.4.52 doesn't work as well

**Comment by Verzide56** [comment]
> I have downloaded the version 1.4.51 and it works 1.4.52 doesn't work as well

how did you get that version?? i tested the extension with the commit that has the 1.4.51 changes but it doesn't work either

**Comment by xdeiimoss** [comment]
> > I have downloaded the version 1.4.51 and it works 1.4.52 doesn't work as well
> 
> how did you get that version?? i tested the extension with the commit that has the 1.4.51 changes but it doesn't work either

I checked the history on the extensions repo and got the extension version through there...
If 1.4.51 didn't work for you, theres all of the previous versions there as well

**Comment by xcl0udii** [comment]
> I checked the history on the extensions repo and got the extension version through there... If 1.4.51 didn't work for you, theres all of the previous versions there as well

please can you link the list of previous versions, I can only find the regular list of extensions and the oldest it has is 1.4.53 which does not work for me

**Comment by xdeiimoss** [comment]
> > I checked the history on the extensions repo and got the extension version through there... If 1.4.51 didn't work for you, theres all of the previous versions there as well
> 
> please can you link the list of previous versions, I can only find the regular list of extensions and the oldest it has is 1.4.53 which does not work for me

https://github.com/keiyoushi/extensions/blob/cd7b0114f6d9372995d207bc343aa9ed620eda83/apk/tachiyomi-all.myreadingmanga-v1.4.51.apk

**Comment by Norsze** [comment]
@xcl0udii @xdeiimoss @Verzide56 This is a warning to you guys.

This is not a help forum, this is a development forum, individual help is done either on the Discord server or elsewhere.

DO NOT RESPOND, AS I SAID, THIS IS NOT THAT KIND OF FORUM.
