### ISSUE TITLE
Tenshi.id change domain

### ISSUE THREAD

**Issue by ShoujoLover** [keiyoushi/tachiyomi-extensions-source#5676]
### Source information

Tenshi.id 1.4.35

### Source language

Indonesia

### Source new URL

https://tenshi01.id/

### Other details

Previous domain banned, So they replaced it with a new one.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by VrZeta** [comment]
In discord they say, the main domain https://tenshi.id/ and the new domain https://tenshi01.id/
