### ISSUE TITLE
Hentai Read "Unexpected JSON token at offset 2:" but Accessible to Webview 

### ISSUE THREAD

**Issue by shuukenji92** [keiyoushi/tachiyomi-extensions-source#5677]
### Source information

HentaiRead 1.4.44

### Source language

English

### Steps to reproduce

Steps to reproduce

1. Go to Browse
2. Access the Extension
3. Pick any Doujin
4. Click on Chapter
5. "Unexpected JSON token at offset 2:"

![att pq-Q0IvIE111-5EYSjq71R8Aa4I6F3Q5SZG57ql0PYE](https://github.com/user-attachments/assets/23c88108-c492-4cf2-ab91-74a2622596f1)

### Expected behavior

This should happen 

- got access to the Doujins.

### Actual behavior

This happened instead "Unexpected JSON token at offset 2:"

Can use Webview but can't access any doujin chapters

### Mihon/Tachiyomi version

Mihon 0.16.5 and Tachiyomi Stable 0.15.3

### Android version

Android 10

### Other details

Zoomed in

![String](https://github.com/user-attachments/assets/8f4f61ae-09ea-4dc3-b791-f95a13cd6c0c)

Thank you for your hardwork we truly appreciate it :)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MrMidnight001** [comment]
Up same problem

**Comment by vetleledaal** [comment]
Is this still an issue? I can't reproduce the issue for the depicted entity.

**Comment by shuukenji92** [comment]
![image](https://github.com/user-attachments/assets/3b7b1566-2736-4cba-bc2d-53ab9da90a19)

Yes it is still an issue and or bug... I did the same recreation of it

**Comment by shuukenji92** [comment]
> ![image](https://private-user-images.githubusercontent.com/86971859/392243912-3b7b1566-2736-4cba-bc2d-53ab9da90a19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyOTIwMzksIm5iZiI6MTczMzI5MTczOSwicGF0aCI6Ii84Njk3MTg1OS8zOTIyNDM5MTItM2I3YjE1NjYtMjczNi00Y2JhLWJjMmQtNTNhYjlkYTkwYTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA1NTUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkNTdlZGQ5ZDQyYWZhMDYzMjcwYjE3YjJhNWMxZjZiNDZkYjQ1MTc2OGY0MmFjMmNkYTAzNGM2Y2FhODQ0YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u39PUW8XDJOEQ6KG9msESbHuSSe8IieC4Nioa7JYYUU)
> 
> Yes it is still an issue and or bug... I did the same recreation of it

![image](https://github.com/user-attachments/assets/f0bfd726-3d0a-4626-88b2-6955d7b5677e)

Update it finally worked? Someone fixed it! Whoever you are GOD BLESS YOU!
