### ISSUE TITLE
The Blank Scanlation: chapters not showing

### ISSUE THREAD

**Issue by Kantotero** [keiyoushi/tachiyomi-extensions-source#5681]
### Source information

The Blank Scanlation 1.4.38

### Source language

English

### Steps to reproduce

Refresh or open a series so it can load the chapters

### Expected behavior

New chapter/s should load up like normal

### Actual behavior

New chapter/s doesn't load. Opening in webview just leads to homepage instead of the specific series

### Mihon/Tachiyomi version

J2K 1.7.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
I couldn't reproduce this issue. Maybe it's a Cloudflare issue. Try changing the UA, and the extension should work.

**Comment by KenjieDec** [comment]
The issue can be temporarily fixed by loading into the WebView and clicking on one of the mangas available until the page load

**Comment by Norsze** [comment]
Can't reproduce, site does have cloudflare though
