### ISSUE TITLE
Issue with new chapters for rizz comic

### ISSUE THREAD

**Issue by okseboku** [keiyoushi/tachiyomi-extensions-source#569]
### Source information

Rizz comic 1.4.2

### Source language

English 

### Steps to reproduce

Step 1. Check series with new chapter
Step 2. see in webview
Step 3. Go back into new chapter
Step 3. Click try again

### Expected behavior

That webview shows the site 
That chapters load

### Actual behavior

What happen that webview sometime shows a white screen, and chapters can't load but can in webview 
There is no capcha

### Tachiyomi version

Mihon stable 0.16.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ghost** [comment]
I have the same issue in Mihon as well. Mihon hasn't changed anything related to the reader under the hood so I'm very confused here. I've tried clearing cookies, webview cache, random useragent, different DNS.
