### ISSUE TITLE
AllHentai extension issue

### ISSUE THREAD

**Issue by Rad-Fore** [keiyoushi/tachiyomi-extensions-source#5695]
### Source information

AllHentai

### Source language

Russian

### Steps to reproduce

1. Open Source "AllHentai" or Library 
2. Select any manga
3. Сlick Web View
4. Log in
5. Open any chapter of the selected manga
6. See a stub on any page of the manga about the need to log in

### Expected behavior

The selected chapter of the manga should open

### Actual behavior

Instead of each page of the selected manga chapter, a stub will open asking you to log in.
![translated](https://github.com/user-attachments/assets/2e00b2ca-3dee-4540-9937-f7973cbe74b4)

### Mihon/Tachiyomi version

3.4(266)

### Android version

iPadOS 18.0.1

### Other details

This is probably because the variable with the id (.../vol1/1?d=xxxxx) now appears in the address bar of the chapter.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
Chapters urls are now modified at runtime by Javascript to carry a token that grant access.
That token can be fetched from the raw page and added manually to chapter links.

**Comment by faq4272** [comment]
> Chapters urls are now modified at runtime by Javascript to carry a token that grant access. That token can be fetched from the raw page and added manually to chapter links.

how to do that?

**Comment by Norsze** [comment]
@faq4272 are you the programmer who is volunteering to fix it? If the answer is no, then the information will be useless to you

**Comment by Gostik21** [comment]
All titles in the library need to be migrated to allhentai, otherwise instead of pictures from the manga there will be this
![Screenshot_2024-11-05-08-28-39-563-edit_eu kanade tachiyomi](https://github.com/user-attachments/assets/6e959785-9099-4acf-bcf3-058beb6434d5)
