### ISSUE TITLE
Animated Glitched Comics domain changed

### ISSUE THREAD

**Issue by Salinda001** [keiyoushi/tachiyomi-extensions-source#5698]
### Source information

Animated Glitched Comics 1.4.30

### Source language

English

### Source new URL

https://agrcomics.com/

### Other details

![Screenshot_20241025-214012~2](https://github.com/user-attachments/assets/c8915a83-eb3f-4695-8de0-8ae86c7b65af)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by AgentX2006** [comment]
They have also changed their group name to AGR or AGR Comics after they merged with another group so might want to change the extension name as well.

**Comment by Khrunch** [comment]
Animated glitch comics new domain. When it webview it redirects to agrcomics.com

**Comment by Smol-Ame** [comment]
@Khrunch thanks for saying the same exact thing as the issue request. Not like that's the point of the issue request & details.

Wait for a fix, migrate to a different source, or contribute a fix, don't unnecessarily comment (which emails everyone involved in the issue & pings the server) if you don't have anything helpful for contributors.
