### ISSUE TITLE
Image in reaper scans french isnt loading

### ISSUE THREAD

**Issue by LucienLF** [keiyoushi/tachiyomi-extensions-source#5712]
### Source information

Reaper Scans 

### Source language

Reaper Scans 1.4.12

### Steps to reproduce

1. Find Reaper Scans in french
2. open it
3. Find a chapter to read
4. click on the last chapter

### Expected behavior

Normaly you can read your favorite chapter :)

### Actual behavior

Actually you cant read anythink :(

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 12

### Other details

Some chapter load but its 1 for 10 issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
Their image hoster is in trouble perhaps, as webview also miss images. I wouldnt be surprised since its has been like that for some days now for all websites with the same template
