### ISSUE TITLE
Source request

### ISSUE THREAD

**Issue by Asphyxiav2** [keiyoushi/tachiyomi-extensions-source#5720]
### Source name

Nicomanga

### Source link

https://nicomanga.com/

### Source language

Japanese

### Other details

Raw manga provider🙏

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Asphyxiav2** [comment]
![Screenshot_20241027-130134](https://github.com/user-attachments/assets/7c5fa10e-4912-45c2-8e6d-ea61df4d3068)
The extension nicomanga doesn't exist.

**Comment by Smol-Ame** [comment]
It literally does, make sure Japanese language is enabled for both your Sources tab & Extensions tab

![Screenshot_20241026_222700_Mihon](https://github.com/user-attachments/assets/36234a20-961e-42bc-b75a-7585293c5b15)

**Comment by Asphyxiav2** [comment]
Where can I find that setting?

**Comment by Asphyxiav2** [comment]
Found it, thank you

**Comment by Asphyxiav2** [comment]
New problem
![Uploading Screenshot_20241027-133739.jpg…]()

**Comment by Asphyxiav2** [comment]
> It literally does, make sure Japanese language is enabled for both your Sources tab & Extensions tab
> 
> ![Screenshot_20241026_222700_Mihon](https://private-user-images.githubusercontent.com/155411819/380469991-36234a20-961e-42bc-b75a-7585293c5b15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMDc5NzUsIm5iZiI6MTczMDAwNzY3NSwicGF0aCI6Ii8xNTU0MTE4MTkvMzgwNDY5OTkxLTM2MjM0YTIwLTk2MWUtNDJiYy1iNzVhLTc1ODUyOTNjNWIxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QwNTQxMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTRmODQ4MDg0NGZkOTk4M2RiMzNiMzY0OTFkZGU4MzdhMWNjZGFmN2RhMDk4ZDJjODJmZWFkMTMxZjM5ZjY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6abF1vfUyGi9oIPHBGoVpBr0DaFO6XjeODuaoLP6W5E)

![Uploading Screenshot_20241027-133739.jpg…]()
New problem

**Comment by Smol-Ame** [comment]
You hit send before it fully uploaded, also, come to Keiyoushi Discord repo-support channel for basic troubleshooting instead
