### ISSUE TITLE
inmortalscan changed url

### ISSUE THREAD

**Issue by poliglesias** [keiyoushi/tachiyomi-extensions-source#5721]
### Source information

InmortalScan 1.4.32

### Source language

Spanish

### Source new URL

https://scaninmortal.com/

### Other details

Thats the original website:
https://mg.mundodrama.site/
thats the new one:
https://scaninmortal.com/
![Captura de pantalla 2024-10-27 092331](https://github.com/user-attachments/assets/4e811e54-8903-4c1a-97b2-56f5b2f0099f)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
If your extension's version number is correct, you're not using our extensions. The current Keiyoushi Inmortal Scan extension version number is 1.4.38

Uninstall your old extensions, make sure you're using the Keiyoushi repo, and then reinstall your extensions. Come to the Keiyoushi Discord repo-support channel for any questions/issues, and basic troubleshooting in general.
