### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#5722]

**Comment by hibinokoga** [comment]
This isn't a cloudflare issue

**Comment by hibinokoga** [comment]
The issue is that the webpage (myreadingmanga.info) cannot be found despite using what looks to be the correct link

**Comment by Smol-Ame** [comment]
Duplicate of #5675 before you purged it

Reminder to search the existing issues first before opening a new one & acknowledging that you did
