### ISSUE TITLE
Extensions show manga but does not show chapters

### ISSUE THREAD

**Issue by Vaishnaviiikk** [keiyoushi/tachiyomi-extensions-source#5729]
### Source information

Extension name: HentaiWebtoon (lang: en; package: eu.kanade.tachiyomi.extension.en.hentaiwebtoon) Extension version: 1.4.32 (lib: 1.4; version code: 32) NSFW: true  Update available: true Obsolete: false Shared: true Repository: https://raw.githubusercontent.com/keiyoushi/extensions/repo 

### Source language

English

### Steps to reproduce

1. Open extension.
2. Open any manga.

### Expected behavior

It should show chapters list 

### Actual behavior

You can see a message, "No chapters found"

### Mihon/Tachiyomi version

App version: 0.16.4.3 (standard, 959f84a, 124, 2024-07-01T22:25Z) Android version: 11 (SDK 30; build CPH1911_11_F.21) Android build ID: CPH1911_11_F.21 Device brand: OPPO Device manufacturer: OPPO Device name: OP4883 (CPH1911) Device model: CPH1911 WebView: Android System WebView 129.0.6668.100 MPV version: 4d32db2 Libplacebo version: v7.349.0 FFmpeg version: n7.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Works fine on my end. If your extension's version number is correct, then you're not using Keiyoushi's version of it.
* Uninstall the extension
* Check that you are using our/Keiyoushi repo link
* Reinstall the extension

If you have any questions or issues about this, or for basic troubleshooting, come to the Keiyoushi Discord repo-support channel
