### ISSUE TITLE
Manhwa-Latino: ListChapter not complet

### ISSUE THREAD

**Issue by Xush00** [keiyoushi/tachiyomi-extensions-source#5733]
### Source information

Manhwa-Latino 1.4.43

### Source language

Spanish

### Steps to reproduce

*open manga/manhwa with many chapters like "chainsaw-man"
*shows few chapters
![imagen](https://github.com/user-attachments/assets/67a57d8c-1fcf-4001-9ead-b46d2a4ac1f7)
![imagen](https://github.com/user-attachments/assets/ad0579fd-f9b0-40b9-a83d-d79d80f7d01f)

### Expected behavior

Complete list chapters

### Actual behavior

only show the fist page of chapters "181 -> 167" 

### Mihon/Tachiyomi version

Mihon v0.17.0

### Android version

Android 13

### Other details

on the web page there is a NavigationPage at the bottom of the page.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #5557

It's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

**Comment by Xush00** [comment]
sorry
