### ISSUE TITLE
Shinigami Change Domain

### ISSUE THREAD

**Issue by ChriszZ8** [keiyoushi/tachiyomi-extensions-source#5736]
### Source information

ShinigamiID 1.4.62

### Source language

Indonesia 🇮🇩

### Source new URL

https://shinigami06.com

### Other details

![IMG_20241028_121113](https://github.com/user-attachments/assets/c6fb2a5e-9ce3-41cd-be0b-24209070e5c1)

Old Domain : https://shinigami05.com
New Domain : https://shinigami06.com

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SupKelelawar** [comment]
shinigami kan dah ada settingannya buat ubah domain, cek aja di pengaturan ekstensi
