### ISSUE TITLE
LuraToon No pages found

### ISSUE THREAD

**Issue by wallace-pv** [keiyoushi/tachiyomi-extensions-source#5739]
### Source information

Lura Toon 1.4.54

### Source language

Brazilian Portuguese 

### Steps to reproduce

![Screenshot_20241028-064102_Mihon](https://github.com/user-attachments/assets/dccd04be-b3ce-4f9d-9204-7c93597b1795)

"Nenhuma página encontrada" It means No page found
But, the webview works perfectly, I can read through the webview

### Expected behavior

It was supposed to open the chapter normally, it was working until yesterday

### Actual behavior

When I press to read the chapter, page not found appears. I've tried several ways to solve it, but I believe there was a change on the site. It's the same domain https://luratoons.com but something has changed on the site. Now it has devtool protection and is no longer Peach Scan, I believe it goes something like this: https://github.com/theajack/disable-devtool

### Mihon/Tachiyomi version

App version: 0.17.0-6971 (standard, 38d5fc916, 8, 2024-10-26T21:17:45Z) Android version: 12 (SDK 31; build SP1A.210812.016.N975FXXS9HWG3) Device brand: samsung Device manufacturer: samsung Device name: d2s (d2sxx) Device model: SM-N975F WebView: Android System WebView 131.0.6778.14

### Android version

Android 12

### Other details

This Scan works by subscription, my account is linked to Google so I can't share it, But if there is any information that needs a signature to obtain, please tell me how to do it. I can also pay you a one month subscription if you are a contributor.  

This is the view of the website reader

![Screenshot_20241028-065242_Mihon](https://github.com/user-attachments/assets/22c02fe3-c268-4c5f-bf7b-56266e2bc554)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ViminioSM** [comment]
O site atualizou, deve demorar pra atualizarem

**Comment by wallace-pv** [comment]
> O site atualizou, deve demorar pra atualizarem

E ainda tem uma proteção de devtool e também tem a assinatura.  :/

**Comment by ReiSupremo** [comment]
![Screenshot_20241029-235511](https://github.com/user-attachments/assets/dbce2668-a6cd-4ea2-9968-54a3fbc1ea49)
![Screenshot_20241029-235445](https://github.com/user-attachments/assets/487ae847-dbc9-4495-893a-8936dd69652b)

**Comment by ViminioSM** [comment]
Descobri algo interessante, quando vc tá em uma pagina que não é de mangá o inspecionar elemento abre normalmente

**Comment by wallace-pv** [comment]
> ![Screenshot_20241029-235511](https://private-user-images.githubusercontent.com/178437101/381371858-dbce2668-a6cd-4ea2-9968-54a3fbc1ea49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyODgyNzgsIm5iZiI6MTczMDI4Nzk3OCwicGF0aCI6Ii8xNzg0MzcxMDEvMzgxMzcxODU4LWRiY2UyNjY4LWE2Y2QtNGVhMi05OTY4LTU0YTNmYmMxZWE0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQxMTMyNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTgyMzAzZmJlYzEwMmM3YmYyMWI4ZjRkMjJhYWYxZTRjYjg1MWJjZDQzZjZhNGRhMjBjYTFiYWJmOGQ3NTU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ghKhtu_Hs_azy_zYZAawZChhSRnA91YDNmCH9eQ58MA) ![Screenshot_20241029-235445](https://private-user-images.githubusercontent.com/178437101/381371886-487ae847-dbc9-4495-893a-8936dd69652b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyODgyNzgsIm5iZiI6MTczMDI4Nzk3OCwicGF0aCI6Ii8xNzg0MzcxMDEvMzgxMzcxODg2LTQ4N2FlODQ3LWRiYzktNDQ5NS04OTNhLTg5MzZkZDY5NjUyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQxMTMyNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODc2OTFhYmJkMWQ4NjNkMmJiOTU1MDMzNGU4MjZiOWUyZTcwNjExNjdjNGFlYmFiMzEwOGNlMmY1YWE0NzhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PAPPoImU-6D5la42hMWee0IjcDK7FXFfGRauawGoCX0)

Está funcionando normal aqui, pode ser que vc abriu em algum momento que o Dev do site estava fazendo pequenas alterações, o pessoal no Discord da Scan está sempre pedindo coisas que tem no mihon e não tem no site, aí ele está fazendo algumas manutenção, mas aqui está normal.
![Screenshot_20241030-083426_Chrome](https://github.com/user-attachments/assets/d469fcc9-a8d9-41ce-9235-0be7f84fcc79)

**Comment by wallace-pv** [comment]
> Descobri algo interessante, quando vc tá em uma pagina que não é de mangá o inspecionar elemento abre normalmente

Sim tanto que a extensão funciona mostrando títulos e capas das obras, mas na hora de abrir os capítulos só na webview

Não é mais Peach Scan

Pelo que eu procurei o site tá usando isso aqui https://github.com/theajack/disable-devtool

Eu tentei isso aqui https://github.com/dark-swordsman/disable-disable-devtool

Mas sem sucesso, não sou da área de programação :/

**Comment by ViminioSM** [comment]
> > Descobri algo interessante, quando vc tá em uma pagina que não é de mangá o inspecionar elemento abre normalmente
> 
> Sim tanto que a extensão funciona mostrando títulos e capas das obras, mas na hora de abrir os capítulos só na webview
> 
> Não é mais Peach Scan
> 
> Pelo que eu procurei o site tá usando isso aqui https://github.com/theajack/disable-devtool
> 
> Eu tentei isso aqui https://github.com/dark-swordsman/disable-disable-devtool
> 
> Mas sem sucesso, não sou da área de programação :/

Via script o download continua funcionando
![{1EA7BD9B-34A6-4A46-BDE4-DCFCF24832A1}](https://github.com/user-attachments/assets/c7c3bca9-f907-48ac-8c3b-c470eb751c7b)

**Comment by wallace-pv** [comment]
> > > Descobri algo interessante, quando vc tá em uma pagina que não é de mangá o inspecionar elemento abre normalmente
> > 
> > 
> > Sim tanto que a extensão funciona mostrando títulos e capas das obras, mas na hora de abrir os capítulos só na webview
> > Não é mais Peach Scan
> > Pelo que eu procurei o site tá usando isso aqui https://github.com/theajack/disable-devtool
> > Eu tentei isso aqui https://github.com/dark-swordsman/disable-disable-devtool
> > Mas sem sucesso, não sou da área de programação :/
> 
> Via script o download continua funcionando ![{1EA7BD9B-34A6-4A46-BDE4-DCFCF24832A1}](https://private-user-images.githubusercontent.com/185048516/381605303-c7c3bca9-f907-48ac-8c3b-c470eb751c7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMDA1NDYsIm5iZiI6MTczMDMwMDI0NiwicGF0aCI6Ii8xODUwNDg1MTYvMzgxNjA1MzAzLWM3YzNiY2E5LWY5MDctNDhhYy04YzNiLWM0NzBlYjc1MWM3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQxNDU3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGUzMTU4N2ZkOGU0YmUxNzJkYWJlYTMyNmRkNzk3YWIwYmM0MDJlZWM4ODVhN2RkYzA4ZmI0MDAwNDlmNTM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2EMeg6x08M6_jdXrf0HixOPSWFj-vXiY9tzIVVOGgLI)

Então deve dar pra alguém fazer a extensão voltar a funcionar? Se você conseguir essa extensão poderia colocar um link pra baixar aqui ? Não sei se pode isso, ou pelo Discord. Obrigado por sua atenção aqui, é uma vertente muito nichada o Dev da lura não quer fazer a extensão por questão de "segurança". :/

**Comment by ViminioSM** [comment]
> Então deve dar pra alguém fazer a extensão voltar a funcionar? Se você conseguir essa extensão poderia colocar um link pra baixar aqui ? Não sei se pode isso, ou pelo Discord. Obrigado por sua atenção aqui, é uma vertente muito nichada o Dev da lura não quer fazer a extensão por questão de "segurança". :/

Ele não quer pq eu baixo e upo de graça na sussy toons, mal sabe ele que independente do que ele fizer vou continuar upando pro povo ler de graça

**Comment by wallace-pv** [comment]
> > Então deve dar pra alguém fazer a extensão voltar a funcionar? Se você conseguir essa extensão poderia colocar um link pra baixar aqui ? Não sei se pode isso, ou pelo Discord. Obrigado por sua atenção aqui, é uma vertente muito nichada o Dev da lura não quer fazer a extensão por questão de "segurança". :/
> 
> Ele não quer pq eu baixo e upo de graça na sussy toons, mal sabe ele que independente do que ele fizer vou continuar upando pro povo ler de graça

É eu tô migrando tudo pra sussy agora as obras que eu acompanho, eu paguei o vip pra ver se virava um serviço melhor mas no momento em que eles tiraram a extensão acabou, aquele site que estão desenvolvendo está muito instável tudo para evitar a pirataria da pirataria, o Dev não desiste dessa ideia. Vou estar te agradecendo por achar um jeito de baixar as imagens e upar lá, impossível abandonar o mihon para ler em navegador é um regresso muito grande. Vlw Man pela atenção ao issue

**Comment by ViminioSM** [comment]
Eles arrumaram o script de baixar via zip, mas já providenciei outro injetável. Em breve no LuratoonDL kkkkkkkk

![{2649C6D9-C997-4D43-BFC6-734309E7B638}](https://github.com/user-attachments/assets/2341f3ca-6aad-410c-893a-16e0985123cd)

**Comment by ViminioSM** [comment]
![{E440FD20-C512-4CD6-83C6-5B417F3147B1}](https://github.com/user-attachments/assets/254bd991-4571-4201-a029-d168ea908487)
![{78714942-241C-4A43-A92E-0140BCC2AE40}](https://github.com/user-attachments/assets/90f28c20-1ada-43b8-a93e-1ce7dedaefd6)
Pra todos ficarem felizes em breve no site da sussy toons (vai toma no cu tsuko)
