### ISSUE TITLE
Source Request: Mangairo

### ISSUE THREAD

**Issue by Elixtra** [keiyoushi/tachiyomi-extensions-source#574]
### Source name

Mangairo 

### Source link

https://w.mangairo.com/home

### Source language

English

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by SnakeDoc83** [comment]
This already exists as well, you're 2 for 3.

(Note: Extension works, could update the subdomain though.)
