### ISSUE TITLE
Cambio la URL 

### ISSUE THREAD

**Issue by Blade1170** [keiyoushi/tachiyomi-extensions-source#5740]
### Source information

MHScans 1.4.40

### Source language

Español 

### Source new URL

https://twobluescans.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Duplicate of #5693
