### ISSUE TITLE
Magus Manga Page Domain Changed

### ISSUE THREAD

**Issue by Aragolt** [keiyoushi/tachiyomi-extensions-source#5743]
### Source information

Magus Manga 1.4.43

### Source language

English

### Steps to reproduce

1. Select any manga on the Magus Manga extension
2. Click on any chapter to attempt reading

### Expected behavior

The first page of the chapter should load and let you begin reading.

### Actual behavior

None of the pages load. 'Open in Webview' shows that the extension is looking to 3xfsjdlc.is1.buzz for pages, but Magus Manga's site (via inspect element) gets its pages from imageserver.is1.buzz.

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 12

### Other details

Seems similar to #5592; likely that Magus Manga changed CDNs again.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
update your extension, and clear chapter cache

also consider moving to mihon as original tachiyomi is dead

**Comment by Aragolt** [comment]
Magus Manga extension's latest version is 1.4.43 so there is no update to pull, clearing chapter cache did not fix the issue. And while I'll consider doing that, using Tachiyomi isn't the source of the issue.

**Comment by Norsze** [comment]
@Aragolt Latest is 1.4.44

**Comment by Aragolt** [comment]
For some reason the extension update wasn't showing even after checking for updates, it just showed up. That fixes the issue, many thanks and sorry for the confusion.
