### ISSUE TITLE
E-hentai

### ISSUE THREAD

**Issue by Craagh** [keiyoushi/tachiyomi-extensions-source#5745]
### Source information

1.4.20

### Source language

Multiple

### Steps to reproduce

https://github.com/user-attachments/assets/adef67c3-f1aa-4dc3-b6b9-e00d3d954d52

### Expected behavior

Broken chapter not found page

### Actual behavior

I click new post then press new chapter not found page

### Mihon/Tachiyomi version

0.16.4.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by sudoshindo** [comment]
Same problem
Subscribing to issue

**Comment by hullmat998** [comment]
Same problem

**Comment by Norsze** [comment]
No need to comment that you are following or have the same problem, we all don't want notifications from randoms that they followed the problem, right? Just give a thumb up if that's the case.

**Comment by Rackt00n** [comment]
Should we do something to resolve the problem or will an update be available soon?
