### ISSUE TITLE
MangaDex: Allow Titles to Be in Desired Language

### ISSUE THREAD

**Issue by rl559** [keiyoushi/tachiyomi-extensions-source#5747]
### Source name

MangaDex

### Source language

Multiple, but English in my case

### Describe your suggested feature

Manga titles can come in several languages. When it comes to MangaDex, the default title appears to be the transliterated one when available (sometimes it can be pure English, although rarer). Sometimes when refreshing a manga that originally did not have a transliterated title, the title will switch to the transliterated one, causing headache for myself and potentially others when wanting to find the manga in question later down the line.

Tl;DR: My request is to add an option to the extension settings for a preferred language for Manga titles.

Example Manga: https://mangadex.org/title/91503d4c-16d6-4962-9eca-93557667066c/naze-boku-no-sekai-wo-daremo-oboeteinai-no-ka
Title in app should change from `Naze Boku no Sekai wo Daremo Oboeteinai no ka?` to `Why Does Nobody Remember Me in This World?`

### Other details

I have tried with the latest TachiyomiJ2k and Yokai, and I can confirm that this option is not present with either of them.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AnonymousPtBr** [comment]
👍

**Comment by rl559** [comment]
Hello, 
After installing the update and restarting yokai (my preferred tachiyomi clone), I see the new "Use Alternate Titles" option. 
However, my mangas do not change titles to their alternate after refreshing regardless if the option is on or off. The only language I have enabled is English.

**Comment by Smol-Ame** [comment]
@rl559 How about if you enable said setting, restart the app, and then go back to said entry & refresh the chapter list/details?

**Comment by AwkwardPeak7** [comment]
There are many titles on mangadex which incorrectly mark romaji as English, as mentioned in the pr.

**Comment by rl559** [comment]
Oh I understand. The romanji titles are marked as English as well, which is what is causing the issue. Thank you for the help and update!

**Comment by Kladki** [comment]
The titles of manga in your library cannot change title. If you want to refresh the titles, you will have to remove the manga from your library, refresh them, then add them back. Note: this will invalidate downloads, so you should delete downloaded chapters before refreshing.
