### ISSUE TITLE
Zaimanhua: Some comics are hidden on the web side/再漫画部分漫画在网页端被隐藏

### ISSUE THREAD

**Issue by sakisoda** [keiyoushi/tachiyomi-extensions-source#5752]
### Source information

Zaimanhua 1.4.2

### Source language

Chinese

### Steps to reproduce

部分书架中的漫画检查更新时提示 漫画不存在
Some bookshelves check for updates indicating that the comic does not exist.
![8021bd1627fff0c6ca35959ce03fde51](https://github.com/user-attachments/assets/e363acf5-2451-4dc8-a638-3d6295dbf3e5)
这些漫画在WebView与浏览器中也无法打开
These comics also cannot be opened in WebView or browser.
![f429c3eb49dd6b66bbdd10727da0f4fc](https://github.com/user-attachments/assets/58e7e674-f781-4de0-818e-a363eb1fb528)
但是可以在再漫画app中打开
But  can be opened in Zaimanhua app.
![1fdc608563a18c1518f01a807cde15ea](https://github.com/user-attachments/assets/c0b2ff70-9a97-4572-b4f2-4b94ec78dd8e)
![dac93222e2f851cc331128e6a86d2a15](https://github.com/user-attachments/assets/f0c74749-b48d-4324-b1db-08f0f8a3377b)

### Expected behavior

所有来自再漫画的漫画都可以在mihon中更新、阅读
All comics from Zaimanhua can be updated or read in mihon.

### Actual behavior

部分来自再漫画的漫画无法在mihon中更新、阅读
Some comics from Zaimanhua cannot be updated or read in mihon.

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by zhongfly** [comment]
在插件设置里重新登录

**Comment by sakisoda** [comment]
> 在插件设置里重新登录

确实是这个问题，解决了，感谢🙏

**Comment by zhongfly** [comment]
之后会想办法做自动重新登录…
