### ISSUE TITLE
Doujindesu browse error

### ISSUE THREAD

**Issue by arrosyid7su** [keiyoushi/tachiyomi-extensions-source#5756]
### Source information

Doujindesu  1.4.6

### Source language

Indonesia

### Steps to reproduce

1. Browse
2. Doujindesu (id)
3. Populer/Last/Filter
4. Super Slow loading
5. not the popular one or not the last update

### Expected behavior

![Screenshot_20241029-173955](https://github.com/user-attachments/assets/80d8ec0c-2b7f-47bf-b1de-e61e6707061a)

SS From tachiyomi 0.15.0

### Actual behavior

![Screenshot_20241029-173723](https://github.com/user-attachments/assets/3353d2d7-fa71-4957-adf9-c29d0600bd5b)
![Screenshot_20241029-173519](https://github.com/user-attachments/assets/2313f358-215c-421f-877c-49d735b95a16)

### Mihon/Tachiyomi version

Mihon 0.17.0

### Android version

Android 13

### Other details

normal in previous versions of mihon and in tachiyomi 0.15.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Please remove your NSFW image, and i already check it, it's still fine and working normally, but can't reproduce the issue, maybe your internet problem not the extension nor DoujinDesu web?

Edit :
You could try [this](https://tachiyomi.org/docs/guides/troubleshooting/#clearing-cookies-and-webview-data)

**Comment by arrosyid7su** [comment]
but in mihon version 0.16 it is still normal, and I open it in tachiyomi 0.15.1 it is normal

**Comment by TheKingTermux** [comment]
Iam already try it on Mihon 0.17.0, and it's perfectly fine
That's why i can't reproduce your issue

**Comment by arrosyid7su** [comment]
it is possible but the problem is the timing is not right

https://github.com/user-attachments/assets/4ba39fd4-ac30-4677-96f8-eba3744cc6ed

test on latest mihon and latest tachiyomi, so it does work but the problem is with the time filtering

**Comment by TheKingTermux** [comment]
That's your Mihon problem 
Bruh
`Coba masuk ke pengaturan > Jelajahi > Semua catatan tersembunyi sudah ada di perpustakaan` apakah itu ON atau OFF, kalau ON selamat anda menemukan masalah anda, kalau OFF saya tak bisa membantu 🤣
Itu bukan `Time Filtering` yang kamu bicarakan, tapi `Filtering Bacaan` yg sudah masuk ke Pustaka agar dihapus dari list itu yang membuatnya menjadi semakin lama dalam Pemuatan

**Comment by arrosyid7su** [comment]
Aih😂

**Comment by TheKingTermux** [comment]
> Aih😂

Udh lancar? 😏

**Comment by arrosyid7su** [comment]
![Screenshot_20241030-101536](https://github.com/user-attachments/assets/a073df38-bb00-4922-b893-f39c506bd152)
 Maksudnya ini kah?

**Comment by TheKingTermux** [comment]
> ![Screenshot_20241030-101536](https://github.com/user-attachments/assets/a073df38-bb00-4922-b893-f39c506bd152)
>  Maksudnya ini kah? 

Hooh yg atas sendiri

Edit :
Pertama kali ini ane liat org Indo pake Settings Bahasa Inggris 🤣

**Comment by arrosyid7su** [comment]
On pak, ini error habis update, dan hanya terjadi di doujindesu, lainya normal kok

**Comment by arrosyid7su** [comment]
Hp pake bahasa Inggris jadi ngikut apknya

**Comment by arrosyid7su** [comment]
Jadi masalhnya cuma pas browse di last update, populer, sama filternya. Ane lapor di mihon katanya suruh di extension

**Comment by TheKingTermux** [comment]
> On pak, ini error habis update, dan hanya terjadi di doujindesu, lainya normal kok

Lainnya normal mungkin gk banyak Manga yg ditambahin ke Pustaka, kalau banyak hasilnya sama aja kek DoujinDesu

Edit :
Masalah Terselesaikan, silahkan tutup Isu ini dengan status Completed :v

**Comment by arrosyid7su** [comment]
![Screenshot_20241030-102746](https://github.com/user-attachments/assets/d6c03ebd-fde9-46eb-bc13-4edb68b8163a)
Gak banyak cuma 3000

Jadi ini kesalahan terjadi di mihon kah?

**Comment by TheKingTermux** [comment]
> Jadi ini kesalahan terjadi di mihon kah? 

Hooh, masalahnya cuma salah pengaturan aja, bukan masalah aplikasinya

**Comment by arrosyid7su** [comment]
👌ok
