### ISSUE TITLE
Manga livre 

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#5760]
### Source information

Manga livre 1.4.1

### Source language

Português ( Brasil )

### Steps to reproduce

Não está aparecendo as obras no aplicativo, no Webview está normal

Aplicativo 
![Screenshot_20241029-114214](https://github.com/user-attachments/assets/681bf581-c9ee-4096-9ff7-571b2237682d)

Webview 
![Screenshot_20241029-114228](https://github.com/user-attachments/assets/6e5dc1ad-ee78-4072-a299-f03106e625df)

### Expected behavior

Aparecendo as obras normalmente

### Actual behavior

As obras não tão aparecendo

### Mihon/Tachiyomi version

TachiyomiSY 1.11.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AnonymousPtBr** [comment]
New Theme.

**Comment by choppeh** [comment]
Etoshore: https://github.com/Etoshore/Wordpress-Manga-Theme

Related:  #5568, #5605
