### ISSUE TITLE
Ikigai Mangas are missing details from the website that are not reflected in the source 

### ISSUE THREAD

**Issue by ashliepolanco** [keiyoushi/tachiyomi-extensions-source#5779]
### Source information

Ikigai Mangas 1.4.18

### Source language

Spanish

### Steps to reproduce

There are more mangas, novels and manhwas on the website that are not reflected in the source.
![Screenshot_20241030_062616_Ykai](https://github.com/user-attachments/assets/ce84cce6-33a1-4e9c-9f8a-db129b6ce00b)
![Screenshot_20241030_062643_Chrome](https://github.com/user-attachments/assets/2f3700ce-211f-4eb1-9ce9-1bb7321b63ce)

### Expected behavior

In the source if I try to search for a manga that I see on the web I get a search error 
![Screenshot_20241030_063259_Ykai](https://github.com/user-attachments/assets/6471defd-9c78-4c57-bb73-f8e443b24ee2)
![Screenshot_20241030_063316_Chrome](https://github.com/user-attachments/assets/cffc0cab-418c-4aec-93f1-77099cc97d6b)
![Screenshot_20241030_063325_Chrome](https://github.com/user-attachments/assets/9533b1fc-682f-4f63-a0e6-d8d730f9f623)

### Actual behavior

The website has more information than the source in the app 
![Screenshot_20241030_062643_Chrome](https://github.com/user-attachments/assets/5b0e6009-cedb-42d2-9ba9-da51a8531a03)
![Screenshot_20241030_062659_Chrome](https://github.com/user-attachments/assets/87a1c75d-b34f-4438-a9cb-f48d38da2204)
![Screenshot_20241030_062616_Ykai](https://github.com/user-attachments/assets/fb73fa67-4299-40b0-bfb5-741cb59dbc3d)
![Screenshot_20241030_062712_Ykai](https://github.com/user-attachments/assets/10a6defe-17d1-4f2a-97f5-be6823ecdd31)

### Mihon/Tachiyomi version

Yōkai 1.8.5.9

### Android version

Android 14

### Other details

https://lectorikigai.acamu.net/ By the way, the website changed its domain. Someone already mentioned that, but I wanted to comment on this problem because I see that they never mention it, they only show the domain change. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Enable NSFW toggle in extension settings
