### ISSUE TITLE
Samurai Scan no muestra su contenido

### ISSUE THREAD

**Issue by Striven100** [keiyoushi/tachiyomi-extensions-source#5782]
### Source information

SamuraiScan (es.manhuaonline)

### Source language

Español

### Steps to reproduce

La extension anda bien, pero ya no puedo acceder al catalogo de Recientes o Populares (esto no es un problema muy serio, simplemente aviso por las dudas). Marca HTTP 404, pero la pagina web funciona bien.

### Expected behavior

La extension anda bien, pero ya no puedo acceder al catalogo de Recientes o Populares (esto no es un problema muy serio, simplemente aviso por las dudas). Marca HTTP 404, pero la pagina web funciona bien.

### Actual behavior

La extension anda bien, pero ya no puedo acceder al catalogo de Recientes o Populares (esto no es un problema muy serio, simplemente aviso por las dudas). Marca HTTP 404, pero la pagina web funciona bien.

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Xush00** [comment]
No era poner lo mismo en todo. Si lees bien cada título te dice lo que debes de poner.
