### ISSUE TITLE
Jobsibe: It's not a manga extension 

### ISSUE THREAD

**Issue by Refresco2x** [keiyoushi/tachiyomi-extensions-source#5803]
### Source name

Jobsibe

### Source language

Spanish

### Source link

https://jobsibe.com/

### Other details

The actual extension of Jobsibe is LMTO Online only they changed the name and the current extension is another page  

![Screenshot_20241031_025406_Aniyomi](https://github.com/user-attachments/assets/76552cf9-616f-4ea6-bd32-39c88725400e)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
Domain changed.

Issue: #5805

**Comment by vetleledaal** [comment]
Superseded by #5805. 'source is down' issues are solved by removing the extension, which is not quite right in this case.
