### ISSUE TITLE
LMTO Online It's Jobsibe 

### ISSUE THREAD

**Issue by Refresco2x** [keiyoushi/tachiyomi-extensions-source#5805]
### Source name

LMTO Online

### Source language

Spanish

### Describe your suggested feature

The page icon and name have been changed to Jobsibe 

![Screenshot_20241031_040042_Aniyomi](https://github.com/user-attachments/assets/82464c5d-a6e0-44d7-adde-2734117f3568)

### Other details

Since your other page is no longer available this one has been changed to the main one.  

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
label: _**Domain changed**_
