### ISSUE TITLE
YuraManga No Result Found

### ISSUE THREAD

**Issue by VrZeta** [keiyoushi/tachiyomi-extensions-source#5812]
### Source information

YuraManga 1.4.37

### Source language

Indonesia 

### Steps to reproduce

Just open the extension. Any tab (popular or latest)

### Expected behavior

Comic list appears

### Actual behavior

what appears is "No Result Found"
![1003194524](https://github.com/user-attachments/assets/594dacaf-78fb-4a3b-b1c5-0cd54608d374)

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ShoujoLover** [comment]
As a note, if the comic has been favorited, it can be updated normally By refreshing in the library.

I think this is because the url changed slightly?? From https://yuramanga.my.id/ to https://www.yuramanga.my.id/ 

*I tried editing the extension myself just by changing the url, and it works normally
