### ISSUE TITLE
Mgkomik Request UserAgent

### ISSUE THREAD

**Issue by ChriszZ8** [keiyoushi/tachiyomi-extensions-source#5817]
### Source name

Mgkomik 

### Source language

Indonesia 🇮🇩

### Describe your suggested feature

Everything is fine no bug i just request add custom user agent looks like before Mgkomik 1.4.43 is it possible?
![IMG_20241101_131305](https://github.com/user-attachments/assets/4849b4e8-ce7c-41ea-a553-7fbf4a08b58e)

### Other details

Old file Mgkomik 1.4.43 it's winrar unlock first
[tachiyomi-id.mgkomik-revived-v1.4.43.zip](https://github.com/user-attachments/files/17596814/tachiyomi-id.mgkomik-revived-v1.4.43.zip)

* the reason I asked for a custom user agent is because I use a different user agent between V1 all extensions and V2 for mgkomik. The user agent that I often use cannot penetrate MGkomik's Cloudflare security directly like the one I usually use for V1 so I hope you can add this custom feature like before, Thank you 🙏

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ChriszZ8** [comment]
No way why close i just request custom UA 😔

**Comment by Norsze** [comment]
Why did you share an extension from a different (and dead) repo?

**Comment by ChriszZ8** [comment]
Let's just say that's an example, maybe Keyoushi can make it like that. 🙏
