### ISSUE TITLE
Manga Demon not working 

### ISSUE THREAD

**Issue by SwiftGrim** [keiyoushi/tachiyomi-extensions-source#5819]
### Source information

Manga Demon 1.4.15

### Source language

English

### Steps to reproduce

1. Manga demon got connection reset error
2. Went to the extension and it doesn't load
3. Went to webview and it doesn't load as well
4. Try accessing the site (https://ciorti.online/) from a different browser and it loads

### Expected behavior

It should load on the extension itself as well as the webview

### Actual behavior

![Screenshot_20241101_123035_Tachiyomi](https://github.com/user-attachments/assets/2f5d3bbf-cb7e-40fe-ba80-aacecf36eb0d)
![Screenshot_20241101_123054_Tachiyomi](https://github.com/user-attachments/assets/933c5147-0b38-43fe-9aeb-0b1db5b26a20)
![Screenshot_20241101_123120_Chrome](https://github.com/user-attachments/assets/9e619c7a-4243-4bc5-9ce5-443d3b8e3f22)

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Nak99999** [comment]
Work fine for me

**Comment by SwiftGrim** [comment]
> Work fine for me

I have no clue why it isn't working on my end

**Comment by Smol-Ame** [comment]
Sounds like a personal internet-related issue, maybe you have DNS over HTTPS enabled in your Tachi app

Come to the Keiyoushi Discord repo-support channel for help with this
