### ISSUE TITLE
Luratoons has stopped working  

### ISSUE THREAD

**Issue by 0nur65** [keiyoushi/tachiyomi-extensions-source#5821]
### Source name

Lura tonn

### Source link

https://luratoons.com/todas-as-obras/

### Source language

Portuguese

### Other details

Good morning everyone, I came here to report the problem of an extension called Lura Toons, well the Lura Toons website charges a monthly subscription for people to have access to their translated works, so naturally their extension does not work on Mihon, however when paying a subscription and logging into your account through WebView the extension worked perfectly but two days ago it stopped working even with the website working normally, does anyone know how to help me? Sorry if there are translation errors
![Screenshot_20241101-111402_Mihon](https://github.com/user-attachments/assets/9063f5d9-12ae-4d2e-b163-9e0fafae8cd2)
![Screenshot_20241101-111357_Mihon](https://github.com/user-attachments/assets/8f74e0fd-dd3a-43c3-a765-2fcfdd3fe930)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by 0nur65** [comment]
The Lura Toons website had already been changed a long time ago, I remember that at the time I was able to download another extension with the luratons url. However, a few days ago the extension simply stopped displaying the new chapters in the Mihon app, but when entering the site through WebView the site continues to function normally when you have an account logged into it, it simply gives a message saying that it cannot find new chapters in the app.  
![Screenshot_20241102-095920_Mihon](https://github.com/user-attachments/assets/25cb056e-b86a-4441-86bc-21678fdd19f6)
![Screenshot_20241102-095929_Mihon](https://github.com/user-attachments/assets/8c2697a8-e86f-47d7-8d75-1620d56d3a0d)
![Screenshot_20241102-095940_Mihon](https://github.com/user-attachments/assets/328f31d6-0680-4a7f-be46-e48be3cac7e6)
![Screenshot_20241102-095952_Mihon](https://github.com/user-attachments/assets/aaad3911-6398-4f4b-963f-c0755da1278f)

**Comment by Norsze** [comment]
You filed a source request issue for an already existing source. 

Go back and file the correct issue report as you have an issue with an existing extension. What you filed is for when requesting new extensions.
