### ISSUE TITLE
Bilibili not working

### ISSUE THREAD

**Issue by kyoko-tk** [keiyoushi/tachiyomi-extensions-source#5827]
### Source information

Extension name: BILIBILI MANGA; Extension version: 1.4.11

### Source language

zh-Hans

### Steps to reproduce

Open or download any chapter

### Expected behavior

Chapter opened/downloaded

### Actual behavior

When downloading/reading a chapter I get the following error: Expected URL scheme 'http' or 'https' but no scheme was found for ?token....

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 14

### Other details

Expected URL scheme 'http' or 'https' but no scheme was found for ?token...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ABPolaris** [comment]
The protocol may be changed from http/https to bilicomic.

![Uploading Screenshot_2024-11-02-17-52-12-366_eu.kanade.tachiyomi.j2k.jpg…](https://github.com/user-attachments/assets/2ff5f943-5b25-4060-adad-5ba8b61fdd93)

**Comment by Nathaniel-Wu** [comment]
Same issue

**Comment by Vivi26499** [comment]
Same issue

**Comment by LMDM387** [comment]
Same issue in TachiyomiSY 1.11.0, Extension version: 1.4.11
Dervice：Xiaomipad 5 pro12.4(dagu), HyperOS 1.0.5.0, Android 14
try to update Android System WebView（https://play.google.com/store/apps/details?id=com.google.android.webview&pli=1）（Ver:130.0.6723.58）or use vpn, can`t work
But If click on webview(this button), It can read comics correctly
![QQ图片20241104012355](https://github.com/user-attachments/assets/8d5efe7c-b20f-4c99-9e39-dacd28dbeef1)

**Comment by ZerOri** [comment]
Same issue……

**Comment by MikeZeDev** [comment]
FYI they also recently added image encryption. So dev might want to check that after fixing that protocol problem.

**Comment by AlphaBoom** [comment]
Give some infomation about encrypt algorithm：
```python
import base64
import json
from Crypto.Cipher import AES
from Crypto.Util.Padding import unpad

CONFIG = """{"1":{"al":"AES-CBC","ak":[1,33],"an":[60,76],"at":[0,20]},"2":{"al":"AES-CBC","ak":[1,33],"an":[60,76],"at":[0,20]}}"""

def select_config(version:int):
    return json.loads(CONFIG)[f"{version}"]

def decrypt(b, A, x, E, S):
    i = b[S[0]:S[1]*1024+16]
    s = b[S[1]*1024+16:]
    # AES mode should from E
    cipher = AES.new(A,AES.MODE_CBC,x)
    decrypted = unpad(cipher.decrypt(i), AES.block_size)
    return decrypted + s

def decode_file(file:str, cpx):
    """
    """
    with open(file, mode="rb") as f:
        config = select_config(int.from_bytes(f.read(1), "big"))
        an = config["an"]
        al = config["al"]
        at = config["at"]
        x = base64.b64decode(cpx)[an[0]:an[1]]
        size = int.from_bytes(f.read(4), "big")
        b = f.read(size)
        A = f.read()
        decrypted = decrypt(b, A, x, al, at)
    with open("output.jpg", "wb") as f:
        f.write(decrypted)
```

**Comment by 1419606843** [comment]
same issue，cant read my already afforded comics，so baaaaaaad😭

**Comment by Rstoroniomi** [comment]
I though that is a terrible news ，I cannot open bilibili manhua ，either！
