### ISSUE TITLE
Batoto removing manga from site

### ISSUE THREAD

**Issue by xdeiimoss** [keiyoushi/tachiyomi-extensions-source#5847]
### Source name

Batoto 1.4.41

### Source language

English

### Describe your suggested feature

The way that Batoto removes manga from the site is just by changing the image and adding a message to the description. The message being: "This comic has been marked as deleted and the chapter list is not available." 
A few examples:
https://bato.to/series/170876/its-easy-to-ban-access-blue-lock-dj
https://bato.to/series/167901/worker-bee
This makes it hard to know when to migrate an entry.
Is there any way to make it so when the message is detected it shows an error 404 or any type of error that would appear in the update log?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by xdeiimoss** [comment]
Hello. I saw that there was an pull request which mentioned this issue and the title said that the exception was added, but when my updates finish, I still don't see anything in the update log. Did something went wrong?

**Comment by vetleledaal** [comment]
The linked PR does not address this issue. There was a relevant comment, this issue being 'other':

> only keep the regex change and revert rest, I'll do the other change later
>
> _Originally posted by @AwkwardPeak7 in https://github.com/keiyoushi/extensions-source/issues/5853#issuecomment-2481281547_
