### ISSUE TITLE
Mangas livre online

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#5856]
### Source name

Mangas Livre

### Source link

https://www.mangaslivre.com/

### Source language

Português (Brasil)

### Other details

Yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by AnonymousPtBr** [comment]
Cool!

**Comment by choppeh** [comment]
Source is down
