### ISSUE TITLE
Shinigami resolve cloudflare showing "heyyo" page instead

### ISSUE THREAD

**Issue by beegreen49** [keiyoushi/tachiyomi-extensions-source#586]
### Source information

Shinigami 1.4.46

### Source language

Indonesia

### Steps to reproduce

open webview

### Expected behavior

Resolve cloudflare page

### Actual behavior

this blank with "heyyo" page showed instead
![Screenshot_2024-01-25-00-50-03-660_eu kanade tachiyomi sy](https://github.com/keiyoushi/extensions-source/assets/62960343/db947ef2-1f14-46ab-9e7e-82f31f7c24ab)

before this happened, cloudflare could be resolved, but the chapter appeared was only "siapa sangka"
![Screenshot_2024-01-24-14-32-48-481_eu kanade tachiyomi sy](https://github.com/keiyoushi/extensions-source/assets/62960343/89c320d4-d6a8-4aab-b252-61054bb33b47)

### Tachiyomi version

TachiyomiSY 1.10.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by WEPOXS** [comment]
Gw bikin isue malah di bilang kurang cermat tch😀
https://github.com/keiyoushi/extensions-source/issues/587 sad:)

**Comment by ShoujoLover** [comment]
> Gw bikin isue malah di bilang kurang cermat tch😀 #587 sad:)

Lo yang emang kurang cermat tolo, ngapain juga lo cekllist bagian badut

**Comment by WEPOXS** [comment]
> > Gw bikin isue malah di bilang kurang cermat tch😀 #587 sad:)
> 
> Lo yang emang kurang cermat tolo, ngapain juga lo cekllist bagian badut

Lah emg ada 🗿

**Comment by WEPOXS** [comment]
> > Gw bikin isue malah di bilang kurang cermat tch😀 #587 sad:)
> 
> Lo yang emang kurang cermat tolo, ngapain juga lo cekllist bagian badut

Yang mana nya bjir, gw biasa ceklist semua kalo bikin issue

**Comment by ShoujoLover** [comment]
> > > Gw bikin isue malah di bilang kurang cermat tch😀 #587 sad:)
> > 
> > 
> > Lo yang emang kurang cermat tolo, ngapain juga lo cekllist bagian badut
> 
> Yang mana nya bjir, gw biasa ceklist semua kalo bikin issue



> > > Gw bikin isue malah di bilang kurang cermat tch😀 #587 sad:)
> > 
> > 
> > Lo yang emang kurang cermat tolo, ngapain juga lo cekllist bagian badut
> 
> Yang mana nya bjir, gw biasa ceklist semua kalo bikin issue

Hadeh, lo coba perhatiin yg ts g ceklist itu terus lo translate artinya apaan. Wakakaka 3x dibilang badut

**Comment by WEPOXS** [comment]
> > > > Gw bikin isue malah di bilang kurang cermat tch😀 #587 sad:)
> > > 
> > > 
> > > Lo yang emang kurang cermat tolo, ngapain juga lo cekllist bagian badut
> > 
> > Yang mana nya bjir, gw biasa ceklist semua kalo bikin issue
> 
> 
> 
> > > > Gw bikin isue malah di bilang kurang cermat tch😀 #587 sad:)
> > > 
> > > 
> > > Lo yang emang kurang cermat tolo, ngapain juga lo cekllist bagian badut
> > 
> > Yang mana nya bjir, gw biasa ceklist semua kalo bikin issue
> 
> Hadeh, lo coba perhatiin yg ts g ceklist itu terus lo translate artinya apaan. Wakakaka 3x dibilang badut

Gw tadi ceklist semua trus gw kg ceklist pas liat komen lu, mau di ceklist ato kg tetep di closed paksa

**Comment by ShoujoLover** [comment]
> > > > > Gw bikin isue malah di bilang kurang cermat tch😀 #587 sad:)
> > > > 
> > > > 
> > > > Lo yang emang kurang cermat tolo, ngapain juga lo cekllist bagian badut
> > > 
> > > 
> > > Yang mana nya bjir, gw biasa ceklist semua kalo bikin issue
> > 
> > 
> > > > > Gw bikin isue malah di bilang kurang cermat tch😀 #587 sad:)
> > > > 
> > > > 
> > > > Lo yang emang kurang cermat tolo, ngapain juga lo cekllist bagian badut
> > > 
> > > 
> > > Yang mana nya bjir, gw biasa ceklist semua kalo bikin issue
> > 
> > 
> > Hadeh, lo coba perhatiin yg ts g ceklist itu terus lo translate artinya apaan. Wakakaka 3x dibilang badut
> 
> Gw tadi ceklist semua trus gw kg ceklist pas liat komen lu, mau di ceklist ato kg tetep di closed paksa

Ya emang gitu, mau lo edit juga bakal tetep diclose. Kecuali lo buat issue baru

**Comment by WEPOXS** [comment]
> > > > > > Gw bikin isue malah di bilang kurang cermat tch😀 #587 sad:)
> > > > > 
> > > > > 
> > > > > Lo yang emang kurang cermat tolo, ngapain juga lo cekllist bagian badut
> > > > 
> > > > 
> > > > Yang mana nya bjir, gw biasa ceklist semua kalo bikin issue
> > > 
> > > 
> > > > > > Gw bikin isue malah di bilang kurang cermat tch😀 #587 sad:)
> > > > > 
> > > > > 
> > > > > Lo yang emang kurang cermat tolo, ngapain juga lo cekllist bagian badut
> > > > 
> > > > 
> > > > Yang mana nya bjir, gw biasa ceklist semua kalo bikin issue
> > > 
> > > 
> > > Hadeh, lo coba perhatiin yg ts g ceklist itu terus lo translate artinya apaan. Wakakaka 3x dibilang badut
> > 
> > Gw tadi ceklist semua trus gw kg ceklist pas liat komen lu, mau di ceklist ato kg tetep di closed paksa
> 
> Ya emang gitu, mau lo edit juga bakal tetep diclose. Kecuali lo buat issue baru

Ah okey, makasih ya info nya lain kali gw liat liat lagi

**Comment by beer-psi** [comment]
@WEPOXS @ShoujoLover GitHub is not a place for chatting. Please try to stick to the issue being discussed.

**Comment by WEPOXS** [comment]
> @WEPOXS @ShoujoLover GitHub is not a place for chatting. Please try to stick to the issue being discussed.

Ah... okey im so sorry

**Comment by iRust7** [comment]
Chapter not found, chapter link redirect to troll page
![Screenshot_2024-01-25-02-52-33-805-edit_eu kanade tachiyomi j2k](https://github.com/keiyoushi/extensions-source/assets/108685856/57b75190-aefb-459c-8bc4-908156344f51)

**Comment by beer-psi** [comment]
> Chapter not found, chapter link redirect to troll page ![Screenshot_2024-01-25-02-52-33-805-edit_eu kanade tachiyomi j2k](https://private-user-images.githubusercontent.com/108685856/299440965-57b75190-aefb-459c-8bc4-908156344f51.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMjY5NTQsIm5iZiI6MTcwNjEyNjY1NCwicGF0aCI6Ii8xMDg2ODU4NTYvMjk5NDQwOTY1LTU3Yjc1MTkwLWFlZmItNDU5Yy04YmM0LTkwODE1NjM0NGY1MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQyMDA0MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzk3ZjRhZDZlMGY0NDcyN2YzMTcwNTViYmRmM2FmYWExNTM5ZGEyN2M5NGQwNWExNTk4YzNhNzE0OTYxNzVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rhFBTeW5hst4HvSHQUYkVQsA_DF19SOyUw1ZJ9o8az4)

Please make a separate issue ticket for that.
