### ISSUE TITLE
Reaper scans is broken

### ISSUE THREAD

**Issue by Gadwin** [keiyoushi/tachiyomi-extensions-source#5867]
### Source information

Reaper scan 1.4.36

### Source language

French

### Steps to reproduce

Source in app says it has nothing since they updated their website si you just has to try to ser a recent Book to see app wont find anything

https://reaper-scans.fr/

### Expected behavior

Thé website is active so app should find things

### Actual behavior

The actual extension IS based on old website version so it doesnt work

### Mihon/Tachiyomi version

0.17.0

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
If your extension's version number is correct, then you're not using our/Keiyoushi's version of Reaper Scans (FR) extension. The current extension seems to work fine.

* Uninstall your old extension (and any other non-Keiyoushi extensions you still have installed)
* Make sure you have/are using the Keiyoushi repo link
* Reinstall the extensions & migrate your titles back into the same source (Reaper Scans FR to Reaper Scans FR) if needed (to update the entry's URL)

Come to the Keiyoushi Discord repo-support channel if you have any questions or issues about this, or for basic troubleshooting

**Comment by Gadwin** [comment]
Thanks it works now
