### ISSUE TITLE
Manhwa18 Chapter not found but WebView works fine

### ISSUE THREAD

**Issue by crest1993** [keiyoushi/tachiyomi-extensions-source#5871]
### Source information

Manhwa18 1.4.11

### Source language

English

### Steps to reproduce

Pull up refresh chapter
Chapter not found
Open webview
Title and chapter is fine in webview

### Expected behavior

Can grab the updated chapter

### Actual behavior

Show chapter not found toast

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by razhad** [comment]
got any workaround OP?

**Comment by AwkwardPeak7** [comment]
closing in favor of #5996
