### ISSUE TITLE
Blackout Comics (PT-Br Source), No results found

### ISSUE THREAD

**Issue by Yukizi** [keiyoushi/tachiyomi-extensions-source#5873]
### Source information

Blackout Comics 1.4.6

### Source language

Português 

### Steps to reproduce

Even when logging into the source settings, the message appears: No results found.
![357524167-4a59293c-17dd-46d4-81b1-f5750528ee3a](https://github.com/user-attachments/assets/20187890-7fc0-49aa-92e1-a0dfad79299e)
![357524173-7f1a3f01-75d1-4bef-a47b-21be5633dfae](https://github.com/user-attachments/assets/f54f847b-a6c7-4da8-b5e7-70973f3203cd)

### Expected behavior

View Source files.

### Actual behavior

Can't access the files.

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate/part of #5599

Search the existing issues first before opening a new one
