### ISSUE TITLE
Komikindo 

### ISSUE THREAD

**Issue by HZWK** [keiyoushi/tachiyomi-extensions-source#5875]
### Source information

KomikindoID 1.4.14

### Source language

Indonesia 

### Source new URL

https://komikindo.biz/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
Not blocked for me. In fact its already supported in keiyoushi its the new url of Komikindo.lol (and .biz redirect to .dev now)

https://github.com/keiyoushi/extensions-source/blob/main/src/id/komikindoid/src/eu/kanade/tachiyomi/extension/id/komikindoid/KomikIndoID.kt

SO its a DOMAIN change request.
