### ISSUE TITLE
Coffee Manga http error 500 on app

### ISSUE THREAD

**Issue by Zethzune** [keiyoushi/tachiyomi-extensions-source#5877]
### Source information

coffee manga 1.4.39

### Source language

English

### Steps to reproduce

1st is go to the coffee manga extension, 2nd pass the cloudfare if there's any in the webview, 3rd, webview should work just fine but when the coffee manga in the app is refreshed, it will pop up a http error 500
![image](https://github.com/user-attachments/assets/16f3673b-0804-479e-a247-49fd0e05f8ff)
![image](https://github.com/user-attachments/assets/2458a135-2c60-4dcb-9f4b-3d23d9918135)

### Expected behavior

no http error 500 in app

### Actual behavior

appview has http error 500
![image](https://github.com/user-attachments/assets/c4207e12-9fa0-4bac-9998-b01b5538070a)

### Mihon/Tachiyomi version

0.17.0

### Android version

android 13

### Other details

Ame said in discord he got 522 instead
![image](https://github.com/user-attachments/assets/d2c5796c-b25c-4173-ac4d-0c319483bc26)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Zethzune** [comment]
It's working now for some reason..
Should i close this now?

**Comment by TheKingTermux** [comment]
Error 5xx is a server side error, not an extension problem, you can close this issue
