### ISSUE TITLE
E-Hentai filter old behavior

### ISSUE THREAD

**Issue by Mazkoran** [keiyoushi/tachiyomi-extensions-source#5887]
### Source name

E-Hentai 1.4.22

### Source language

Multi

### Describe your suggested feature

In the version 1.4.22 filter, you have to input tags manually. This makes it impractical/hard to do as there is no instruction on what to input, and what tags are available.
Please do rollback of the changes done to filter - tags to how it was before, where you can use dropdown/checkbox menu for each type of tags (normal tags, female tags, male tags) with lists of what tags are available.

### Other details

Before the update, the filter tags is easier to use.
I tried to input in the female tags "sole female", then i got no results.
But when i inputted one word tags such as "blindfold", i can get results.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
There are at least 33,464 tags you can use, or 1,220 if you only count content tags. With the previous implementation you only had 323 tags to pick from. You might say that the previous implementation only had the most used tags, but still.

In  the meantime you can check the list of tags I compiled [into a gist](https://gist.github.com/vetleledaal/5271cc4e5a581fa54dbdf21c9f30f70d).

**Comment by Mazkoran** [comment]
There are tags that doesn't work though, like the example in other details. I don't know what should be inputted to make it work, as it seems like the input is still buggy for some of the two words tags.
But on the old behavior implementation, those tags works

**Comment by vetleledaal** [comment]
Tags with spaces should be surrounded in quotes. I don't remember the exact syntax, but something like:
```
mixed:"some tag"
"mixed:some tag"
```

**Comment by Norsze** [comment]
Maybe a clarification can be added of how to do multi word tags?

**Comment by Mazkoran** [comment]
Turns out all you have to do is replace the space with underscore, like sole female should be inputted sole_female. A clarification on how to do that is also nice
