### ISSUE TITLE
AllHentai extension issue

### ISSUE THREAD

**Issue by Gostik21** [keiyoushi/tachiyomi-extensions-source#5891]
### Source information

Allhentai 1.4.49

### Source language

Russian

### Steps to reproduce

1. Open Library
2. Select any manga from allhentai
3. Сlick Web View
4. Log in
5. Open any chapter of the selected manga
6. Manga pages match the content and are readable

### Expected behavior

The selected chapter of the manga should open and manga pages match the content

### Actual behavior

![Screenshot_2024-11-05-08-28-39-563-edit_eu kanade tachiyomi](https://github.com/user-attachments/assets/690205f9-3f12-4078-9b8d-60dcec4c6a2c)

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 11

### Other details

After migrating the manga to itself, the pages are displayed normally and problem fixed.
But when you have hundreds of added manga this is not a solution

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Gostik21** [comment]
Аfter updating the manga in the library everything is ok. Close the bug report.

**Comment by Smol-Ame** [comment]
You can close it yourself you know
