### ISSUE TITLE
Crystal Comics Error HTTP 404

### ISSUE THREAD

**Issue by AnonymousPtBr** [keiyoushi/tachiyomi-extensions-source#5898]
### Source information

CrystalComics 1.4.37

### Source language

Portuguese Brazilian 

### Steps to reproduce

When I try to update the work, the HTTP 404 error appears.

![Screenshot_2024-11-05-13-19-22-312_app mihon debug](https://github.com/user-attachments/assets/64bfb294-1481-4edd-be9e-b5d71230c2ed)

### Expected behavior

Update normally.

### Actual behavior

Does not update the works.

### Mihon/Tachiyomi version

App version: 0.17.0-6990

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by domflamingo2** [comment]
Thema change
