### ISSUE TITLE
Quero adicionar uma fonte para português brasileiro

### ISSUE THREAD

**Issue by Duquezao** [keiyoushi/tachiyomi-extensions-source#5899]
### Source name

Heitor Guilherme

### Source link

https://raw.githubusercontent.com/ThePBone/tachiyomi-extensions-revived/repo/index.min.json

### Source language

Português 

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Actually give a source link or get out
