### ISSUE TITLE
Koharu: Domain Change

### ISSUE THREAD

**Issue by mrtear** [keiyoushi/tachiyomi-extensions-source#5909]
### Source information

Koharu 1.4.8

### Source language

English

### Source new URL

https://niyaniya.moe/

### Other details

Old Domain: [koharu.to](https://koharu.to/)
New Domain: [niyaniya.moe](https://niyaniya.moe/)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by papaj-na-wrotkach** [comment]
I think you should use [Schale Network](https://schale.network/) instead of niyaniya.moe. niyaniya is backup mirror, koharu.to is primary mirror. Scale Network redirects to the best available mirror. See the [information on their page](https://niyaniya.moe/wiki/mirrors).

I don't know if the domain allows redirects to specific path or only to the main page though.

**Comment by mrtear** [comment]
@papaj-na-wrotkach thanks for the info.

so is this considered a domain change request or not? The primary domain (which they also added on the mirror page) is currently down—will it be back?

**Comment by papaj-na-wrotkach** [comment]
I'm not a maintainer or a developer of this repo but I think this is a domain change request.

I believe the main mirror will be back eventually. In my case it redirects to the backup mirror rn. Earlier I got NXDOMAIN. It might have something to do with me tinkering the private DNS settings on my Android (disabling private DNS).

**Comment by Kantotero** [comment]
> In my case it redirects to the backup mirror rn. Earlier I got NXDOMAIN. It might have something to do with me tinkering the private DNS settings on my Android (disabling private DNS).

Can you still access the koharu extension?

**Comment by Smol-Ame** [comment]
The site is dead apparently. There's a proposed PR to the repo to fix the extension/change the URL, pending review, wait for a future extension update or migrate to a different source.

**Comment by papaj-na-wrotkach** [comment]
> Can you still access the koharu extension?

No, I used my browser. The IP address was probably cached in the DNS I switched to. Now I get NXDOMAIN again.

**Comment by papaj-na-wrotkach** [comment]
They added new domains btw. One of them is another "observer" domain - [gehenna.jp](https://gehenna.jp/). Both observer domains redirect to the best mirror. Again, info on [this](https://niyaniya.moe/wiki/mirrors) page. The page mentions to use one of them when sharing things. They supposedly keep the path in url when redirecting.

Also Koharu mirror is listed as "dead", so it might not come back.
