### ISSUE TITLE
MangaBuddy takes 10 - 12 seconds to update per chapter.

### ISSUE THREAD

**Issue by KenzKD** [keiyoushi/tachiyomi-extensions-source#591]
### Source information

Mangabuddy

### Source language

English

### Steps to reproduce

1. Download Mangabuddy Extension
2. Make sure No. of MangaBuddy Series doesn't activate a Warning for too many Series
3. Go to Updates Tab and Hit the Update Button on the Top Right of the screen.
4. View the Updating Library Notification
5. Measure the time between each Mangabuddy Series

### Expected behavior

Should be Less than 2 seconds per Series as compared against Mangadex and Mangahere

### Actual behavior

Mangabuddy Takes 10 - 12 seconds per Series.

### Tachiyomi version

Mihon 16.1

### Android version

EMUI 12 Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Keiyoushi is **not** hosting any content, we are not affiliated with or responsible for any source that is: slow, down, missing chapters, or has subpar image quality.
