### ISSUE TITLE
404 error found while reading on HentaiFox

### ISSUE THREAD

**Issue by Darrel-Santoso** [keiyoushi/tachiyomi-extensions-source#5915]
### Source information

HentaiFox

### Source language

English

### Steps to reproduce

Open a doujin
Scroll to page 3 and above
"This page cannot be loaded"
Press "open in webview"
Error 404 not found

### Expected behavior

All pages should load properly.

### Actual behavior

404 not found error

### Mihon/Tachiyomi version

1.11.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by SushiTrashXD** [comment]
Can reproduce, also noticed that it's trying find the images at url/image.jpg while the images are at url/image.webp

**Comment by MikeZeDev** [comment]
> Can reproduce, also noticed that it's trying find the images at url/image.jpg while the images are at url/image.webp

Makes senses. Straight from website : 

```ts
  gt_inf = g_th[e];
      var a = gt_inf.split(',') [0];
      if ('j' == a) var t = 'jpg';
      if ('p' == a) t = 'png';
      if ('b' == a) t = 'bmp';
      if ('g' == a) t = 'gif';
      if ('w' == a) t = 'webp';
```

**Comment by SushiTrashXD** [comment]
> > Can reproduce, also noticed that it's trying find the images at url/image.jpg while the images are at url/image.webp
> 
> Makes senses. Straight from website : 
> 
> ```ts
>   gt_inf = g_th[e];
>       var a = gt_inf.split(',') [0];
>       if ('j' == a) var t = 'jpg';
>       if ('p' == a) t = 'png';
>       if ('b' == a) t = 'bmp';
>       if ('g' == a) t = 'gif';
>       if ('w' == a) t = 'webp';
> ```
> 
> 

They are saving storage by using webp then? , Good on em
Should be an easy fix, thanks for the hardwork
