### ISSUE TITLE
WNACG extension cannot view webp format images

### ISSUE THREAD

**Issue by loadingEZ** [keiyoushi/tachiyomi-extensions-source#5926]
### Source name

tachiyomi-zh.wnacg-v1.4.15.apk

### Source language

Chinese

### Describe your suggested feature

WNACG has updated a lot of webp format comics these days. They can't be displayed when using tachiyomi and mihon. I have checked comics from other source websites and the software can display webp images. I think it is a problem with the wnacg plug-in. I request to update the plug-in to support the webp format. Thank you (I use Google Translate, please forgive me for any incoherent sentences and words)

### Other details

![Screenshot_20241107_203624_eu kanade tachiyomi](https://github.com/user-attachments/assets/3893bcf0-bcdd-40a4-b8ce-e8df35b1e9f8)
https://img5.wnimg.ru/data/2738/94/03.webp
https://img5.wnimg.ru/data/2738/94/28.jpg
It could have displayed many images, but only the last blue jpg image was displayed
![Screenshot_20241107_203549_eu kanade tachiyomi](https://github.com/user-attachments/assets/2cc81140-a265-4751-bb78-570dcd138eba)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Kxdiong** [comment]
+1

**Comment by Smol-Ame** [comment]
@Kxdiong Rather than "+1" which unnecessarily emails anyone involved in this issue request & pings the Keiyoushi Discord server, subscribe to the issue & give it a thumbs up instead
