### ISSUE TITLE
Weeb Central "no pages found" when trying to view or download any manga.

### ISSUE THREAD

**Issue by Kitsune2431** [keiyoushi/tachiyomi-extensions-source#5928]
### Source information

Weeb Central 1.4.2

### Source language

English

### Steps to reproduce

1. Search for any manga in weeb central extension
2. Enter any manga to view all available chapters
3. Tap on any chapter or download button to start reading manga

### Expected behavior

The chapter we tapped should open or download

### Actual behavior

No pages found error appear after brief loading animation

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by noahwastaken** [comment]
Can confirm this is an issue still...no pages found error on all manga in source.
