### ISSUE TITLE
[dead] ManyComic

### ISSUE THREAD

**Issue by cuong-tran** [keiyoushi/tachiyomi-extensions-source#5934]
### Source name

ManyComic

### Source language

English

### Source link

https://manycomic.com

### Other details

Domain got redirected to some fashion shopping site.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Site appears to be up again.
