### ISSUE TITLE
Hunters Scans (PT-Br Source) New URL

### ISSUE THREAD

**Issue by AnonymousPtBr** [keiyoushi/tachiyomi-extensions-source#5935]
### Source information

Hunters Scans 1.4.42

### Source language

Portuguese Brazilian 

### Source new URL

https://hunterscomics.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by einstein95** [comment]
Currently in maintenance
> O site está em manutenção no momento, estamos trabalhando para que tudo esteja em seu devido lugar.
> Enquanto isso, entre em nosso discord e seja notificado quando estiver tudo pronto.

> The site is currently undergoing maintenance, we are working to get everything back in place.
> In the meantime, join our discord and you will be notified when everything is ready.

**Comment by AnonymousPtBr** [comment]
> Currently in maintenance
> > O site está em manutenção no momento, estamos trabalhando para que tudo esteja em seu devido lugar.
> > Enquanto isso, entre em nosso discord e seja notificado quando estiver tudo pronto.
> 
> > The site is currently undergoing maintenance, we are working to get everything back in place.
> > In the meantime, join our discord and you will be notified when everything is ready.

Site on!
