### ISSUE TITLE
Unable to read from Extension also not opening in the app/webview

### ISSUE THREAD

**Issue by Mudblood2001** [keiyoushi/tachiyomi-extensions-source#5936]
### Source information

"Omega scans 1.4.45"

### Source language

"English"

### Steps to reproduce

![Screenshot_20241107_113350](https://github.com/user-attachments/assets/55be2570-2149-4070-b2e5-2d2be97fb3c4)
![Screenshot_20241107_113358](https://github.com/user-attachments/assets/7e57d7a7-5767-4668-99f8-5b3ada4e414d)

### Expected behavior

![Screenshot_20241108_002731](https://github.com/user-attachments/assets/7a18138a-b014-4cb4-ba70-5d0241b9710a)
![Screenshot_20241108_002741](https://github.com/user-attachments/assets/8f0ee60b-ef6d-4822-9ecc-1b88013ed34d)

### Actual behavior

"Instead of the extension opening in the webview in mihon app it just shows webpage not available"

### Mihon/Tachiyomi version

0.17.0

### Android version

12

### Other details

It works fine if I open it in my browser(I apologize if there is any mistakes in reporting the issue this is my first time using github)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
This is an issue on your end, I'm afraid you will have to figure this out yourself or ask for help on the Discord server

**Comment by Mudblood2001** [comment]
Can you please give me link for the discord server

**Comment by Norsze** [comment]
@Mudblood2001 it is literally on the first page of this repo, if you had just even glanced at the read.me you'd see it instantly. https://github.com/keiyoushi/extensions-source check this page

**Comment by Mudblood2001** [comment]
Bro I don't use github all of this is  confusing as it is I did scroll
through but I just missed it no need to get aggressive 😅

**Comment by Norsze** [comment]
ah yes, facts are aggressive to people now, you don't want to see me aggressive snowflake

**Comment by Mudblood2001** [comment]
Facts..really ,were you there to see me scrolling without glancing at it
..and I was being polite and admitted my mistake I don't use github and
that's why I was confused, it's basic etiquette to be respectful but I
guess you wouldn't know anything about it
