### ISSUE TITLE
Manga time extension url changed

### ISSUE THREAD

**Issue by alucard61** [keiyoushi/tachiyomi-extensions-source#5938]
### Source information

Manga time 1.4.38

### Source language

Arabic

### Source new URL

https://mangatime.org/

### Other details

The url changed and the extension not working 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by alucard61** [comment]
There is a mistake  the first issue is for adding the source but the source already added and now the domain changed so please update the source url
![Screenshot_2024-11-08-07-38-26-06_afd66b7916d19a60815f56273408b73e](https://github.com/user-attachments/assets/92332a72-c244-4bd6-87a5-62eb2822f652)
![Screenshot_2024-11-08-07-35-10-88_4d38fce200f96aeac5e860e739312e76](https://github.com/user-attachments/assets/f08012c0-d4b6-4a47-8e2e-5355d5fed386)

**Comment by Smol-Ame** [comment]
I got an error code 522 when trying to access the current Manga Time extension, usually that means their site/servers are offline/experiencing an issue.

Do you have any proof or message (such as Discord announcement) to prove the new (.org) URL is the new site/under the same people as the old URL (.us) site?

**Comment by Norsze** [comment]
I am confused by this, cause they have definitely existed at the same time from me checking archived versions of them. And there has been a request for an extension for the org one since before this one went down.

**Comment by alucard61** [comment]
I checked their Twitter account and the site is offline
which means the site i provided is a new one
Please try to make an extension for it 
Thank you very much
