### ISSUE TITLE
Taiyō 

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#5941]
### Source information

Taiyō 1.4.1

### Source language

Português (Brasil)

### Steps to reproduce

Não aparece as obras do site na extensão, na Webview está aparecendo normalmente, vou mostrar no vídeo abaixo

https://github.com/user-attachments/assets/e7e09f75-93f7-43a9-a97b-e85232a2510e

### Expected behavior

Carregar as obras do site 

### Actual behavior

Nenhum resultado encontrado

### Mihon/Tachiyomi version

Tachiyomi SY  1.11.0

### Android version

Android 11 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AnonymousPtBr** [comment]
Aqui também não aparece!
