### ISSUE TITLE
Manga Pill Date issue

### ISSUE THREAD

**Issue by kakarot-dev** [keiyoushi/tachiyomi-extensions-source#5943]
### Source information

MangaPill 1.4.8

### Source language

English

### Steps to reproduce

Install the extension
Search any manga
Date will be shown as today.. Instead of the actual date

### Expected behavior

The actual date should be shown

### Actual behavior

The date is incorrectly shown

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by LefanHu** [comment]
chapter release date information is not available on the site

**Comment by kakarot-dev** [comment]
cant this issue be fixed by taking the dates from the trackers that the user uses?

**Comment by Smol-Ame** [comment]
Closing since it's a source-related issue.

We're not the app, the extensions just get the info from the source's site/details.
