### ISSUE TITLE
Hentaifox

### ISSUE THREAD

**Issue by RuijinJ1kka** [keiyoushi/tachiyomi-extensions-source#5948]
### Source information

Hentaifox 1.4.8

### Source language

English 

### Steps to reproduce

1. Opening the comic
2. 2. Not loading the comic
3. Retry loading does not work

### Expected behavior

Loading images

### Actual behavior

This happened the images are not loading
![Screenshot_2024-11-08-15-02-07-698_app mihon debug](https://github.com/user-attachments/assets/2a40283d-2184-4804-8d61-83df75d7d72a)

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 11

### Other details

![Screenshot_2024-11-08-15-02-07-698_app mihon debug](https://github.com/user-attachments/assets/defe09c0-c118-4155-9caa-fdd0a0c20c4e)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Duplicate of #5915
