### ISSUE TITLE
Please add webp format and gif format into WNACG extension

### ISSUE THREAD

**Issue by 2674190131** [keiyoushi/tachiyomi-extensions-source#5951]
### Source name

WNACG

### Source link

https://www.wn01.uk

### Source language

Chinese

### Other details

WNACG has updated a lot of webp format and gif format comics these days. They can't be displayed when using tachiyomi and mihon. I have checked comics from other source websites and the software can display webp images. I think it is a problem with the wnacg plug-in. please add webp format and gif format into WNACG extension, thank you very much!

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by fenglingu** [comment]
+1
