### ISSUE TITLE
Vortex scans wrong redirect link

### ISSUE THREAD

**Issue by prem-k-r** [keiyoushi/tachiyomi-extensions-source#5969]
### Source information

Vortex Scans v1.4.38

### Source language

English 

### Source new URL

https://vortexscans.org/

### Other details

Currently Vortex Scans is redirecting to Vortex Toon (https://vortextoon.com), There are only 7 series there. 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Learn to read first.

It's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

**Comment by prem-k-r** [comment]
> Learn to read first.
> 
> It's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

I checked the open issues from the last 14 days but didn't find anything. I just checked again and located it in the closed issues.
