### ISSUE TITLE
Change url hentaicb

### ISSUE THREAD

**Issue by thanhthiep** [keiyoushi/tachiyomi-extensions-source#5988]
### Source information

CbHentai 1.4.45

### Source language

Vietnamese

### Source new URL

https://hentaicb.site/

### Other details

This web add new web hentaicb if web hentaicb changer again. 
Đây là trang chuyển đổi web hentaicb khi họ đổi tên miền mới 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by dejavui** [comment]
Please uninstall and then reinstall the extension due to the domain name updated 👍.
