### ISSUE TITLE
Reaper Scans Cover Images Don't Show

### ISSUE THREAD

**Issue by Dinor** [keiyoushi/tachiyomi-extensions-source#599]
### Source information

Reaper Scans 1.4.47

### Source language

English

### Steps to reproduce

1. Browse
2. Tap on Reaper Scans or latest for Reaper Scans

### Expected behavior

All cover images shown.

### Actual behavior

Cover images for the series in the library are not shown but the others are however if you go to any of the series and refresh it, the cover image doesn't show anymore on the page with all the series
![ReaperScans SS](https://github.com/keiyoushi/extensions-source/assets/55923558/ad421819-5c26-4bda-8a28-f281e54a9c0a)

### Tachiyomi version

TachiyomiJ2K 1.7.4 & Mihon 0.16.1

### Android version

Android 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by l2eused** [comment]
internet connection issue? it seems take long time to download cover image in this site.

**Comment by beer-psi** [comment]
Can't reproduce.

**Comment by Pipixel** [comment]
also have the issue on the last version of Mihon
