### ISSUE TITLE
Number of entries from library on extensions

### ISSUE THREAD

**Issue by Character95** [keiyoushi/tachiyomi-extensions-source#5994]
### Source name

All

### Source language

All

### Describe your suggested feature

When you go to browse / extensions it will be nice to see number of entries from library for every extensions to see if there is extension without entries from library so that extension can be uninstalled without worry...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
We're not app support?
