### ISSUE TITLE
Manhwa18: error 404

### ISSUE THREAD

**Issue by DucNHH** [keiyoushi/tachiyomi-extensions-source#5996]
### Source information

Manhwa18 1.4.11

### Source language

English

### Steps to reproduce

Access extension

### Expected behavior

List of manhwa should appear

### Actual behavior

http 404

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 10

### Other details

url of this website still the same, I can also open it in webview so seem like logic is changed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
they change theme, apparently
