### ISSUE TITLE
Black flashing 

### ISSUE THREAD

**Issue by Manrajsin** [keiyoushi/tachiyomi-extensions-source#5999]
### Source information

All extensions 

### Source language

English

### Steps to reproduce

If I try reading a manga and move to next page the screen goes black and doesn't show anything until I try to zoom or skip to next page

### Expected behavior

It should keep flying smoothly 

### Actual behavior

It completely goes black

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
This isn't app support
