### ISSUE TITLE
Not downloading but able to read.

### ISSUE THREAD

**Issue by gracekhoo** [keiyoushi/tachiyomi-extensions-source#6]
### Source information

Bato 1.4.33

### Source language

English

### Steps to reproduce

1. Added the repo
2. Downloaded the apk
3. Tried to downloading chapters
4. Gives error message indicating it is unable to download

### Expected behavior

Should download but not sure why it is not.
![Screenshot_20240107_194746_Tachiyomi](https://github.com/keiyoushi/tachiyomi-extensions-source/assets/77096333/6d83018b-ad86-4249-8905-ee11f6214fa0)

### Actual behavior

Not downloading

### Tachiyomi version

0.15 0

### Android version

Android version 14

### Other details

![Screenshot_20240107_194746_Tachiyomi](https://github.com/keiyoushi/tachiyomi-extensions-source/assets/77096333/a7cafe6e-eeee-4194-868d-51ad00864760)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Pause download, close app, remove app from recent, open app again, resume download
