### ISSUE TITLE
Manga Fenix

### ISSUE THREAD

**Issue by KatoMegushua** [keiyoushi/tachiyomi-extensions-source#60]
### Source information

Manga Fenix 1.4.35

### Source language

Español

### Steps to reproduce

1 install source
2 to use

### Expected behavior

1 to use

### Actual behavior

1 not found

### Tachiyomi version

Stable 0.15.2

### Android version

Android 13

### Other details

![Screenshot_20240109_205428_Tachiyomi](https://github.com/keiyoushi/extensions-source/assets/145884813/ff071676-0a25-4c25-a3cd-c9024daf1fa1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Fixed in #50
