### ISSUE TITLE
Colamanga could not find key type again 

### ISSUE THREAD

**Issue by NeKoOuO** [keiyoushi/tachiyomi-extensions-source#6000]
### Source information

COLAMANGA 1.4.20

### Source language

Chinese 

### Steps to reproduce

Refresh for new chapters to download
Unable to download new chapters

### Expected behavior

Should automatically download chapters.

### Actual behavior

It's same issue with #4942

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Can't reproduce. Do you have manga and chapter to test with?

**Comment by NeKoOuO** [comment]
It seems work again now
