### ISSUE TITLE
MYREDINGMANGA 

### ISSUE THREAD

**Issue by Userd990120** [keiyoushi/tachiyomi-extensions-source#6015]
### Source name

MYREDINGMANGA 

### Source language

Español 

### Source link

https://myreadingmanga.info/

### Other details

No funciona no sirve para nada la extensión ya le moví de todo y no funciona para nada
![Screenshot_20241111-213421](https://github.com/user-attachments/assets/8e3a8777-d2e4-42f7-8711-e7cc59d04d20)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
Source works its on your end.

**Comment by xdeiimoss** [comment]
Is the extension working?
