### ISSUE TITLE
SSReading (EX - FurioScan)

### ISSUE THREAD

**Issue by LandonFZ** [keiyoushi/tachiyomi-extensions-source#6026]
### Source name

SSReading - FurioScan (BR)

### Source link

https://ssreading.com.br/

### Source language

Portuguese (Brazilian)

### Other details

18+/NSFW = Yes!

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by AnonymousPtBr** [comment]
Legal!
