### ISSUE TITLE
NinemangaEs Bug

### ISSUE THREAD

**Issue by yoo07** [keiyoushi/tachiyomi-extensions-source#6027]
### Source information

Ninemanga 1.4.20

### Source language

Spanish

### Steps to reproduce

https://github.com/user-attachments/assets/e022f6c8-3f04-4500-9d5f-474b3d57248b

### Expected behavior

The chapter should not disappear

### Actual behavior

The chapter disappears as seen in the video

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 14

### Other details

This is only happening in the Spanish source, it does not happen in the other ninemanga sources (English, Brazilian, Russian, etc.). Here is a video with ninemanga with English source.

https://github.com/user-attachments/assets/73d1f4ff-92e5-403b-bf9d-0874e50f0fcd

I don't know if you could replace the source of ninemangaEs with this one https://es.niadd.com, I don't know if ninemanga is a sub product of niadd or niadd a sub product of ninemanga but both are the same. As you can see here, Gachiakuta is updated with chapter 117, which is not the case in ninemangaEs as seen in the first video.
![Screenshot_20241112-153513_Iceraven](https://github.com/user-attachments/assets/cd409107-b5c5-46e8-b027-d5fd426014eb)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by yoo07** [comment]
Sometimes it updates correctly temporarily (we can notice it by the latest updates that coincide with the updates on https://es.niadd.com) but in the webview of ninemangaEs on mihon it still appears as November 6th.

https://github.com/user-attachments/assets/4e1ebd34-c751-4d0d-ba67-67304974271d

**Comment by bapeey** [comment]
> I don't know if you could replace the source of ninemangaEs with this one https://es.niadd.com

Although Niadd can be a mirror, the site's structure is completely different, so it will be necessary to create a new extension (a request is still open #3886)

About the issue, if the chapter disappears from the site itself, it's an issue with the site, not the extension

**Comment by yoo07** [comment]
Fck I know what the problem is, ninemanga and other illegal anime/manga websites are blocked in my country due to piracy 🗿, the solution is to use vpn or dns, I proceed to close the issue.
