### ISSUE TITLE
SussyToons: New Domain and Support for Login and Register

### ISSUE THREAD

**Issue by domflamingo2** [keiyoushi/tachiyomi-extensions-source#6034]
### Source information

SussyToons 1.4.41

### Source language

Português

### Source new URL

https://new.sussytoons.site/login

### Other details

![image](https://github.com/user-attachments/assets/4a4580d3-98b6-4d1c-aba4-a480bc073373)

To access manhua you have to create an account.

obs: They launched the new website, but it is still extremely unstable and probably has no manhua added.
fixing various errors and instability

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by AnonymousPtBr** [comment]
So fast!

**Comment by ghost** [comment]
> So fast!

Os cara é rápido kkkkkkk

**Comment by AnonymousPtBr** [comment]
O site já está funcionando normalmente!

**Comment by mthvs** [comment]
They haven't updated the URL yet

**Comment by AnonymousPtBr** [comment]
> They haven't updated the URL yet

![Screenshot_2024-11-18-22-48-42-186_app mihon debug](https://github.com/user-attachments/assets/558359f4-50c6-4c97-aacf-bd11982286f9)

**Comment by mthvs** [comment]
> > Eles ainda não atualizaram o URL
> 
> ![Screenshot_2024-11-18-22-48-42-186_app mihon debug](https://private-user-images.githubusercontent.com/183020529/387449149-558359f4-50c6-4c97-aacf-bd11982286f9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5ODEzNjksIm5iZiI6MTczMTk4MTA2OSwicGF0aCI6Ii8xODMwMjA1MjkvMzg3NDQ5MTQ5LTU1ODM1OWY0LTUwYzYtNGM5Ny1hYWNmLWJkMTE5ODIyODZmOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQwMTUxMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDU2NzRjOTExNDU4MTVjNWQ3YmQxOGM0MmFhZGMwNzMxOTYwNTExYWMzOGViYjU5YzY4MGI4ZjYxMTU1NjY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uKoNtbB9tMwKof_Qpl7e8H9vlFLE4SeKIDG4oHnY--c)

Exato vão fechar ele tem que migrar pro novo link

**Comment by AshbornXS** [comment]
quick update on that: now it's not entirely needed to login to access the page, but they didn't quite fully changed to the new domain

now they upload almost half-half, half on the old page and half on the new one

maybe for now the best solution would be making a new extension for the new page while they don't fully change?

**Comment by mthvs** [comment]
I think it's a good idea

**Comment by AshbornXS** [comment]
another update: they just announced that the new page has everything the old one had and that the old one will be shutdown, so now it's viable changing the domain to the new one and forget the old one

**Comment by BlackMember08** [comment]
Atualizar o site Sussy Toons

**Comment by mthvs** [comment]
I think they are ignoring this request

**Comment by AshbornXS** [comment]
@mthvs they aren't, don't worry, it's just that isn't that simple as just changing the url, they probably will need to basically make a new extension to fetch the new page, probably someone is already working on it but has some problems, just be patient and let the devs do their work

**Comment by AnonymousPtBr** [comment]
A extensão antiga só tá dando time out..

**Comment by Nazgerr** [comment]
Quando será que arrumarão o link correto da scan?

**Comment by Gutis-007** [comment]
É necessário a troca do domínio do site pois o antigo não está mais sendo atualizado apenas no novo

**Comment by Gutis-007** [comment]
Compreendo que a criação de uma nova extensão é algo demorado e que é fim de ano, porém por favor atualizem o domínio do site na extensão da sussy, ela é atualmente um dos maiores agregadores e também faz a tradução de várias obras em pt br

**Comment by AshbornXS** [comment]
sadly it isn't as easy as just changing the url, those things take time solving bugs and finding workarounds for the pages protection, just wait, pressure the devs will do more harm than good

**Comment by ArnaldoQ15** [comment]
A small contribution to the devs responsible for the issue: unlike when the issue was created, the login and password are no longer mandatory to view the mangas/manwhas.

**Comment by AnonymousPtBr** [comment]
A extensão em português mais esperada do ano!⌛

**Comment by Jefferson199809** [comment]
A antiga URL n está atualizando nenhuma obra
É necessário a mudança o quanto antes

**Comment by Jefferson199809** [comment]
Nova URL: https://new.sussytoons.site/

**Comment by Unkyyy** [comment]
parece que eles só tão ignorando msm

**Comment by choppeh** [comment]
Opa! glr, já vi e fiz algumas alterações na extensão, então não precisa ficar spamando no GitHub com solicitações de mudança de URL ou algo assim. A extensão não vai solucionar o problema de lentidão do novo site. Não enviei as alterações pois tenho algumas pendências para resolver e também estava esperando alguma melhora no site do Sussy. Algumas das URLs da API do site ainda são ineficientes e retornam dados desnecessários que causam a lentidão geral no site e tráfego excessivo de dados.

E não é simplesmente: "**URL atualizou, atualizem a URL**", como é um trabalho voluntário de cada contribuidor, não existe um tempo máximo para resolver um problema. Ficar spamando não ajuda em nada, evite esse comportamento.

Caso ache importante uma issue, marque a issue com 👍 em vez de 🚀.

Há diversas outras extensões em pt-br, migrem para alguma que tenha a obra que vocês acompanham.

**Comment by AshbornXS** [comment]
@choppeh você é um herói cara! muito obrigado por todo o trabalho, uma pena q mt provavelmente falar pra n spamarem n vai resolver em nada kkkkkkkk

**Comment by Gutis-007** [comment]
![Screenshot_20241204_180306_Discord](https://github.com/user-attachments/assets/db6061d0-b253-4626-9169-42d69963f385)

O site antigo voltará a ser atualizado devido à problemas no site novo, assim a mudança de URL não é atualmente necessária, porém tenho uma sugestão aos devs, que seria criad uma nova extensão para o site novo, pq daria para eles irem trabalhando nas melhorias para que o site novo funcione no app sem ter que fazer isso quando o site antigo for abandonado, se isso não for mais trabalhoso, claro!

**Comment by AnonymousPtBr** [comment]
> Opa! glr, já vi e fiz algumas alterações na extensão, então não precisa ficar spamando no GitHub com solicitações de mudança de URL ou algo assim. A extensão não vai solucionar o problema de lentidão do novo site. Não enviei as alterações pois tenho algumas pendências para resolver e também estava esperando alguma melhora no site do Sussy. Algumas das URLs da API do site ainda são ineficientes e retornam dados desnecessários que causam a lentidão geral no site e tráfego excessivo de dados.
> 
> E não é simplesmente: "**URL atualizou, atualizem a URL**", como é um trabalho voluntário de cada contribuidor, não existe um tempo máximo para resolver um problema. Ficar spamando não ajuda em nada, evite esse comportamento.
> 
> Caso ache importante uma issue, marque a issue com 👍 em vez de 🚀.
> 
> Há diversas outras extensões em pt-br, migrem para alguma que tenha a obra que vocês acompanham.

Meu herói! Obrigado por seu trabalho duro e contribuição nesse projeto!💐

**Comment by AnonymousPtBr** [comment]
E lá vamos nós!

**Comment by ghost** [comment]
> E lá vamos nós!

Kkkkkkk

**Comment by Smol-Ame** [comment]
Reminder that this is an issue request, not a chatroom. @AnonymousPtBr in particular, if you could learn to not unnecessarily comment if you don't have any useful information to provide, that would be great.

Unnecessary comments pings the Keiyoushi Discord channel, and emails everyone involved with the issue.

**Comment by domflamingo2** [comment]
Please close the channel so no one can send messages.
According to the text above "Chopper", you just have to wait.
