### ISSUE TITLE
Estou com um problema em uma das extensões. 

### ISSUE THREAD

**Issue by m4titi07** [keiyoushi/tachiyomi-extensions-source#6038]
### Source information

Manhastro 1.4.43

### Source language

Português (Brasil)

### Steps to reproduce

Em manhwas/mangás/manhuas com mais de 100 capítulos só fica disponível os 100 últimos, ou seja, começar uma obra que tem por exemplo 300 capítulos fica impossível.

### Expected behavior

Antigamente manhwas/mangás/manhuas eram completos.

### Actual behavior

Apenas os 100 últimos capítulos estão disponíveis. 

### Mihon/Tachiyomi version

1.11.0

### Android version

14

### Other details

Gostaria de dizer que essa é a melhor extensão que tem disponível, nenhuma outra extensão atende o público brasileiro tão bem quanto essa, se possível corrigam esse problema. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by m4titi07** [comment]
Uploading Screen_Recording_20241113_171201_TachiyomiSY.mp4…

Todos esses mangás possuem mais de 100 capítulos, mas só mostram os 100 últimos para ler.

**Comment by m4titi07** [comment]
Uploading Screen_Recording_20241113_171201_TachiyomiSY.mp4…

**Comment by AnonymousPtBr** [comment]
Você olhou no site se tem os  que estão faltando?

**Comment by m4titi07** [comment]
Sim, no site as obras estão completas, e na extensão até um tempo atrás tambem estavam completos, foi apartir de um certo momento que isso aconteceu...

**Comment by choppeh** [comment]
> Sim, no site as obras estão completas, e na extensão até um tempo atrás tambem estavam completos, foi apartir de um certo momento que isso aconteceu...

Faça login na WebView para visualizar todo o contéudo disponivel, comportamento padrão da fonte é exibir os 100 últimos capítulos.

**Comment by m4titi07** [comment]
Sim, estava dando uma explorada no que podia fazer enquanto alguém não respondia, fiz exatamente isso e deu certo.
