### ISSUE TITLE
Link has changed 

### ISSUE THREAD

**Issue by deathstalker654** [keiyoushi/tachiyomi-extensions-source#6047]
### Source information

‏CosmicScans.id 1.4.35

### Source language

Indonesia

### Source new URL

https://cosmic345.co

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by deathstalker654** [comment]
The link has changed and there's no update from the extension

**Comment by Smol-Ame** [comment]
Learn to read first.

It's already been reported before, search the existing issues first (both open & closed) before opening a new one, and acknowledging that you did when you clearly didn't.
