### ISSUE TITLE
Mangapark

### ISSUE THREAD

**Issue by Sundogg17** [keiyoushi/tachiyomi-extensions-source#6049]
### Source information

1.4.20

### Source language

English

### Steps to reproduce

Open source, doesn't load titles

### Expected behavior

To display titles 

### Actual behavior

Doesn't load titles 

### Mihon/Tachiyomi version

Tachij2k 1.74 

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Seems to load up fine
* Check WebView for errors
* Switch networks or use a VPN
* Switch the extension's mirror URL, restart, and try again
* Turn off (or enable) DNS over HTTPS in J2K Menu > Settings > Advanced, restart the app & see if that helps

Come to the Keiyoushi Discord repo-support channel for any questions/issues about this, or for basic troubleshooting in general

![Screenshot_20241114_131957_TachiyomiJ2K.png](https://github.com/user-attachments/assets/67e21836-1501-4362-b615-4293cfd1bb24)

**Comment by Sundogg17** [comment]
Oh ok. What's the sever link for Discord?

**Comment by Smol-Ame** [comment]
It's listed on both the Keiyoushi GitHub extensions/extensions-source page's description/README and the Keiyoushi website.
