### ISSUE TITLE
VisorInari: Change of url 

### ISSUE THREAD

**Issue by Refresco2x** [keiyoushi/tachiyomi-extensions-source#6051]
### Source information

Visor Inari 1.4.44

### Source language

Spanish

### Source new URL

https://clubinari.org/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by bhdai** [comment]
Your new domain is not working anymore

**Comment by NastMz** [comment]
> Tu nuevo dominio ya no funciona

That's true, the domain change a few days ago to https://clubinari.org/
