### ISSUE TITLE
Koharu: domain changed

### ISSUE THREAD

**Issue by kyoyacchi** [keiyoushi/tachiyomi-extensions-source#6053]
### Source information

SchaleNetwork 1.4.10

### Source language

English

### Source new URL

https://niyaniya.moe/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by papaj-na-wrotkach** [comment]
Did the domain really change?

SchaleNetwork is available normally from the browser for me. It should redirect automatically to NiyaNiya or other available mirror preserving the path in the URL. In Mihon when searching I get HTTP 400 which I believe is caused by malformed request to the API.

Maybe it's API that changed?

**Comment by papaj-na-wrotkach** [comment]
Update: They removed the scale.network domain from the observers list on the page [/wiki/mirrors](https://niyaniya.moe/wiki/mirrors), moreover they also have this page: https://rentry.org/schalenet.

If you change the domain then use one of the observer domains.

Maybe allowing user to choose the mirror in the settings would be a good idea? Or maybe we could get multiple sources like in Komga extension, where you can manually specify the base URL?

**Comment by papaj-na-wrotkach** [comment]
> Update: They removed the scale.network domain from the observers list on the page [/wiki/mirrors](https://niyaniya.moe/wiki/mirrors)

Nvm, I am stupid, they didn't remove SchaleNetwork from the list, they changed it to SCHALE.

**Comment by Gtoonm** [comment]
Is there any fix currently?

**Comment by kyoyacchi** [comment]
> Is there any fix currently?

it seems there is

**Comment by papaj-na-wrotkach** [comment]
So the issue was with the HTTP headers and the fact that we need to get the domain dynamically, right?

**Comment by Kantotero** [comment]
> > Update: They removed the scale.network domain from the observers list on the page [/wiki/mirrors](https://niyaniya.moe/wiki/mirrors)
> 
> Nvm, I am stupid, they didn't remove SchaleNetwork from the list

Speaking of, another [domain](seia.to) is dead together with the former main one koharu
