### ISSUE TITLE
Schalenetwork 

### ISSUE THREAD

**Issue by RuijinJ1kka** [keiyoushi/tachiyomi-extensions-source#6059]
### Source information

Schalenetwork 1.4.10

### Source language

English 

### Steps to reproduce

First step open site
Second step site does not load
Third step shows error 

### Expected behavior

Extension should load the site

### Actual behavior

But it doesn't load instead 

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 11

### Other details

None

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Yefita** [comment]
Duplicate to #6053
