### ISSUE TITLE
Nicomanga not working

### ISSUE THREAD

**Issue by Asphyxiav2** [keiyoushi/tachiyomi-extensions-source#6067]
### Source name

Nicomanga

### Source language

Japanese

### Source link

https://www.nicomanga.com

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment]
Source is up
