### ISSUE TITLE
BacaKomik Nullpointer

### ISSUE THREAD

**Issue by Miikasaaaaa** [keiyoushi/tachiyomi-extensions-source#6068]
### Source name

Bacakomik 1.4.10

### Source language

Indonesia

### Source link

https://bacakomik.net/

### Other details

Error when opening the source, the comic list is not displayed and there is only writing NullPointerException: nul

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by 0Ha16wA5** [comment]
Wrong label: the website is not down.

**Comment by vetleledaal** [comment]
Duplicate of #2396
