### ISSUE TITLE
Faster MangaLife rate limiter

### ISSUE THREAD

**Issue by pekatour** [keiyoushi/tachiyomi-extensions-source#6073]
### Source name

MangaLife

### Source language

English

### Describe your suggested feature

Chapters are downloader veery slowly, one image every two seconds it seems. I guess the source caps it. Would it be possible to make it faster? Without getting flagged ?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Eagle1337** [comment]
Generally, if  you have to cap something slower to prevent rate limiting/timeouts, going faster doesn't help the problem.

**Comment by vetleledaal** [comment]
> Ainz-Sama — 2021-04-13T08:18Z
> Mangalife is rate limited, it's to prevent the source from banning the app (which they have done before)

This hasn't changed
