### ISSUE TITLE
Area Scans change URL

### ISSUE THREAD

**Issue by a7mad115** [keiyoushi/tachiyomi-extensions-source#6075]
### Source information

Area Scans 1.4.31

### Source language

Arabic

### Source new URL

https://ar.areamanga.xyz/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by bhdai** [comment]
@a7mad115 old url still works? close this issue please

**Comment by vetleledaal** [comment]
If you want a new site added you should use the 'source request' issue template.
