### ISSUE TITLE
Não estou conseguindo ler manhwas pelo lura toon.

### ISSUE THREAD

**Issue by ROSQUEVE** [keiyoushi/tachiyomi-extensions-source#6077]
### Source information

Lura Toon 1.4.54

### Source language

Português Brasil - PT-BR

### Steps to reproduce

Eu não estou conseguindo ler, ou baixar, os capítulos. Ou seja, muitos manhwas não aparecem os capítulos, e se aparecem, não abrem, as páginas não carregam. Por fim, quero mencionar que estou conectado a uma conta que eu já paguei para ler.

### Expected behavior

As páginas dos capítulos carregariam e eu leria ou baixaria para ler off-line.

### Actual behavior

As páginas dos capítulos não carregam, ou melhor dizendo, em muitos manhwas nem o capítulo aparece. Sendo que eu já paguei e entrei com a conta paga que utilizo no site.

### Mihon/Tachiyomi version

0.17.0

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #5739

It's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.
