### ISSUE TITLE
Some galleries in WNACG cannot be read

### ISSUE THREAD

**Issue by Smile8848** [keiyoushi/tachiyomi-extensions-source#6079]
### Source information

WNACG1.4.16

### Source language

Chinese

### Steps to reproduce

Searching for かのまましんどろーむ2 眼鏡あり
Open and read
No prompt found page

### Expected behavior

Its link is alive, it should be able to read normally.

### Actual behavior

Unable to find the page

### Mihon/Tachiyomi version

0.15.3

### Android version

Android11

### Other details

![1](https://github.com/user-attachments/assets/e83c0f7e-eb2f-4a1a-a900-897a9c9c91b0)
![2](https://github.com/user-attachments/assets/9744f5ca-fb8c-426e-b293-70a569a4217e)
![3](https://github.com/user-attachments/assets/824320c6-758a-4507-b5f1-dab001998050)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate/part of #6050 and/or #6056

Search the existing issues first before opening a new one, and acknowledging that you did when you didn't
