### ISSUE TITLE
Mangadex extension:  Failed to find a manga title which is present on the site

### ISSUE THREAD

**Issue by Tatsuran** [keiyoushi/tachiyomi-extensions-source#6083]
### Source information

MangaDex 1.4.194

### Source language

English

### Steps to reproduce

1. Browse -> Sources -> Search
2. Search for "Chounin A wa Akuyaku Reijou wo Doushitemo Sukuitai"

### Expected behavior

 "Chounin A wa Akuyaku Reijou wo Doushitemo Sukuitai" is found and avaliable to read

### Actual behavior

No results found

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 14

### Other details

https://mangadex.org/title/ffbd1ee1-65e8-45d4-ba03-6441f584b74b/chounin-a-wa-akuyaku-reijou-wo-doushitemo-sukuitai

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
It shows up fine, you didn't enable Erotica/Pornographic content rating for the extension. Go to Mangadex extension settings > Default content rating, and enable it

Come to the Keiyoushi Discord repo-support channel for basic questions/issues

**Comment by Tatsuran** [comment]
Thank you, that worked (I've missed the setting somehow)
