### ISSUE TITLE
Sussy toons (new site)

### ISSUE THREAD

**Issue by thiefoflife** [keiyoushi/tachiyomi-extensions-source#6087]
### Source name

Sussy toons 

### Source link

new.sussytoons.com

### Source language

Portuguese - Brazil

### Other details

Need to make an account or log in to see the mangas, manhwas and manhuas

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by AnonymousPtBr** [comment]
Issue duplicate #6034

**Comment by vetleledaal** [comment]
> Issue duplicate #6034

Current domain `oldi.sussytoons.com` mentions `new.sussytoons.site`. The domain in this issue `new.sussytoons.com` seem to work, and neither the `.com` or `.site` site redirect to the other.

So if anything, the `new.sussytoons.com` domain should be added as a mirror to the existing extensions. Please open a feature request if desired.
