### ISSUE TITLE
Pages Not Found Error

### ISSUE THREAD

**Issue by Nagendra-456** [keiyoushi/tachiyomi-extensions-source#6098]
### Source information

Flame Comics 1.4.34

### Source language

English

### Steps to reproduce

1.Opened Hero Has Returned Manhwa
2.Put the first and second chapter for download
3.The download doesn't start and it shows "Pages Not Found" error.

### Expected behavior

The Chapters should start downloading without any issue since they are there on the website.

### Actual behavior

But rather than the chapters getting downloaded it showed "Pages Not Found" error and didn't download.

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SantoFantasy** [comment]
Site is down temporarily
Some issues regarding their finances or something
The http link redirects to their discord invite

**Comment by bauripalash** [comment]
Flame Comics site is back online. They have changed some internal things, thus the extension is no longer working.

**Comment by Norsze** [comment]
Superseded by #6230
