### ISSUE TITLE
A strange bug of happymh 嗨皮漫画

### ISSUE THREAD

**Issue by Nevermind425** [keiyoushi/tachiyomi-extensions-source#6102]
### Source information

1.4.12

### Source language

Chinese 

### Steps to reproduce

click a chapter and read 

### Expected behavior

Load the comic like normal 

### Actual behavior

Only can bypass cloudflare some chapters

### Mihon/Tachiyomi version

0.17.0

### Android version

14

### Other details

https://github.com/user-attachments/assets/b555ed17-7d49-4a20-a518-49f52c04b8a5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Nevermind425** [comment]
It kinds of strange cause I can still read it on webview

**Comment by Wistar1308** [comment]
I faced same problems. Happymw had only checked cloudflare when opening webview page and then pressing the search  button a while ago. But now happymw will check cloudflare when just opening webview page and the search button cant be used now.



https://github.com/user-attachments/assets/16758379-9fed-463d-9ea7-6ab37c0e3175

**Comment by alan0507** [comment]
![Screenshot_20241118_040751_Tachiyomi.jpg](https://github.com/user-attachments/assets/b1c54c1e-9059-4868-b3fd-668a011240f5)

When I use webview,this happened.

**Comment by anenasa** [comment]
Message "無法繞過Cloudflare" is not correct, pageListRequest returns 403, because query string changed.

**Comment by Smol-Ame** [comment]
@alan0507 that's unrelated to the issue. It's an ad/app redirect that can't go anywhere, ignore that page. Back out of WebView and click carefully next time

**Comment by anenasa** [comment]
I created a pull request, note that chapter url is changed, you have to refresh manga chapter list after updating extension.

**Comment by maplechia** [comment]
I've also encountered some problems, using the happymh source the manga will pop up directly in the mihon can't bypass cloudflare, in time it has been confirmed in the webview.

https://github.com/user-attachments/assets/8d59154d-877c-4cfa-b88f-aa18e521fd78

**Comment by BabyNurse020517** [comment]
same problem. pls help

**Comment by Rstoroniomi** [comment]
請大家看看百漫谷，6漫畫的插件，之前可以看漫畫，現在看不了出現錯誤了。
Please see the plug in of baimangu，6manhua，before those  can watch comics，now we cannot as it appear trouble

**Comment by alan0507** [comment]
有其他插件需求，請去開新的議題
If you have other plug-in requirements, please open a new topic.

**Comment by Rstoroniomi** [comment]
救命，我開不了空白議題

**Comment by Rstoroniomi** [comment]
幫幫我把這條問題發出去好嗎，thanks
