### ISSUE TITLE
Can't get Any Chapter for Nhentai

### ISSUE THREAD

**Issue by AnImEpRo3690** [keiyoushi/tachiyomi-extensions-source#6103]
### Source information

Nhentai 1.4.47

### Source language

EN and All

### Steps to reproduce

1. Choose Any Doujin
Example:
![image](https://github.com/user-attachments/assets/0e3a0fed-62a9-4178-8b6a-08f66e820e3a)

2. Doujin Load then this Pop up:
![image](https://github.com/user-attachments/assets/0f93a552-c802-400b-9b1a-1f1da0806d09)

### Expected behavior

Load Chapters

### Actual behavior

No Chapter Laoded
![image](https://github.com/user-attachments/assets/c0b594c8-67b5-4378-bd2f-49bb88cd5d98)

### Mihon/Tachiyomi version

TachiyomiSY Stable 1.11.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by KenjieDec** [comment]
Hello, the extension works fine for me. Have you tried checking WebView or restarting the app and reopening the library? And does this issue persist across all doujins? Sorry If I'm asking too much questions :pray:

**Comment by Draaxus** [comment]
> Hello, the extension works fine for me. Have you tried checking WebView or restarting the app and reopening the library? And does this issue persist across all doujins? Sorry If I'm asking too much questions 🙏

I'm not OP but I JUST updated my extension to 1.4.47 and am now getting the exact same error. Restarting the app and checking webview doesn't fix the error. 
![Screenshot_20241118-044305_Mihon](https://github.com/user-attachments/assets/9f6a7aba-f3ed-403d-abb9-6923f409ee37)

**Comment by KenjieDec** [comment]
The issue seem to occur after loging into an account in the webview.

**Comment by AnImEpRo3690** [comment]
> Hello, the extension works fine for me. Have you tried checking WebView or restarting the app and reopening the library? And does this issue persist across all doujins? Sorry If I'm asking too much questions 🙏

I already did everything. Reset the App, Webview(Well, Webview is Fine), Refreshing Library, Reindexing and Even Uninstalling and Installing the Extension.

And Yes, The Issue persist on every Doujin in Nhentai(Well, All of the Doujins I tried to View/ want to Download)

**Comment by pepe1987** [comment]
As a workaround i deleted the 1.4.47 and download the previous build https://github.com/keiyoushi/extensions/raw/3577b9f04c02d34e47f1198084a49d511b89d362/apk/tachiyomi-all.nhentai-v1.4.46.apk

**Comment by T0X1C89** [comment]
I'm getting this error as well with 1.4.47, but to add to the confusion I'm only getting it on my phone in SY, I installed Yokai after the error started to test something unrelated to this and found that nhentai was working just fine using the same extension that was downloaded with SY I just trusted it in Yokai, then I updated the extension on my tablet in SY and it worked fine there as well as in stock Mihon

**Comment by KenjieDec** [comment]
The error only appears when you're logged into an account on NHentai WebView. To temporarily fix the issue, you might need to log out. But if you'd like to wait, I've submitted a PR to fix the issue. No ETA when it'll be merged though.
