### ISSUE TITLE
Anime planent

### ISSUE THREAD

**Issue by davidzin46** [keiyoushi/tachiyomi-extensions-source#6122]
### Source name

Anime planet

### Source link

https://www.anime-planet.com/manga/

### Source language

PT BR 

### Other details

![Screenshot_20241118-102149](https://github.com/user-attachments/assets/1e597d52-6d82-4f74-92a6-64d2bc9ef647)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
(Google Tradutor) Você está bem? É como a segunda solicitação de problema que você abriu e fechou imediatamente. Se você acha que o botão significa dizer aos mantenedores/colaboradores para "se apressarem", esse não é o caso.

Abra o problema, não clique em mais nada e espere pacientemente. Como acontece com qualquer solicitação de problema, não há ETA e nenhuma garantia de que será implementado/corrigido.
