### ISSUE TITLE
SS Reading (Portuguese Brazilian Source) don't show everything content.

### ISSUE THREAD

**Issue by AnonymousPtBr** [keiyoushi/tachiyomi-extensions-source#6124]
### Source information

SS Reading 1.4.37

### Source language

Portuguese Brazilian 

### Steps to reproduce

Does not show all works.

![IMG_20241118_110159](https://github.com/user-attachments/assets/2f175f3c-c6c9-40fe-8a7b-acb0bcdeb2dd)
![Screenshot_2024-11-18-10-58-12-597_app mihon debug](https://github.com/user-attachments/assets/3ba98850-7311-4ffb-a75d-35be3da08d0e)

### Expected behavior

Show all works.

### Actual behavior

Does not show all works.

### Mihon/Tachiyomi version

App version: 0.17.0-7001 (standard, 9df21583d, 8, 2024-11-09T21:19:01Z) Android version: 12 (SDK 31; build SKQ1.211019.001 test-keys) Device brand: Redmi Device manufacturer: Xiaomi Device name: joyeuse (joyeuse_eea) Device model: Redmi Note 9 Pro WebView: Android System WebView 132.0.6834.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by choppeh** [comment]
É uma novel, não vai exibir conteudo algum

**Comment by AnonymousPtBr** [comment]
> É uma novel, não vai exibir conteudo algum

Vdd! Obg!

**Comment by AnonymousPtBr** [comment]
Não lia por que era novel!
