### ISSUE TITLE
Error when trying to migrate to Hitomi

### ISSUE THREAD

**Issue by xdeiimoss** [keiyoushi/tachiyomi-extensions-source#6132]
### Source name

hitomi.la

### Source language

English 

### Describe your suggested feature

![Screenshot_20241118_141003_Komikku](https://github.com/user-attachments/assets/c0419816-aec2-465d-9c87-5646b683ca86)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AwkwardPeak7** [comment]
Use fewer keywords to search

**Comment by 0Ha16wA5** [comment]
Maybe an information to use fewer keywords as error message would be useful

**Comment by Norsze** [comment]
This is not really on the extension. It uses the exact same search function as the website. Just a limitation that is required to think of when searching in the app in general, don't use special characters
