### ISSUE TITLE
Asura scans "no pages found"

### ISSUE THREAD

**Issue by Jashanbhakar** [keiyoushi/tachiyomi-extensions-source#6135]
### Source information

Asura Scans 1.4.41

### Source language

English 

### Steps to reproduce

1. Open the extension 
2. Try opening any series in the extension 
3. When we open the ch it says no pages found 

### Expected behavior

It should the pages in chapter of manhwa 

### Actual behavior

When we try opening it says no pages found 

### Mihon/Tachiyomi version

App version: 0.17.0 (standard, 38d5fc9, 8, 2024-10-26T17:39:14Z) Android version: 15 (SDK 35; build BP11.241025.006) Device brand: google Device manufacturer: Google Device name: panther (panther_beta) Device model: Pixel 7 WebView: Android System WebView 130.0.6723.107

### Android version

Android 15

### Other details

It is working fine in webview the problem is in extension.
Also the chapter I was reading a little while ago are still opening but the new chapters or I have read them like yesterday or in past are also not opening 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Jashanbhakar** [comment]
Now it is showing https 404 error

**Comment by kratoscortez** [comment]
@AwkwardPeak7 issue is still appearing

**Comment by morethanhater** [comment]
> @AwkwardPeak7 issue is still appearing

Update your extension

**Comment by micahflack** [comment]
~~Still broken after updating - "No pages found"~~

~~Asura Scans: English 1.4.42~~

edit: restarted app and fixed
