### ISSUE TITLE
Weeb Central "no pages found" when trying to view or download any manga

### ISSUE THREAD

**Issue by felthand** [keiyoushi/tachiyomi-extensions-source#6139]
### Source information

Weeb Central

### Source language

English

### Steps to reproduce

1. Search for any manga in weeb central extension
2. Enter any manga to view all available chapters
3. Tap on any chapter or download button to start reading manga

### Expected behavior

The chapter should open or download

### Actual behavior

No pages found error appear after brief loading animation

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment]
Are you using Weeb Central 1.4.3? It was recently updated to address this exact issue.

Since I can't reproduce this issue with 'any manga' I'll be closing the issue. Leave a comment with a more specific example that can be tested against if you're still facing issues after updating.

**Comment by felthand** [comment]
Yes, i am using Weeb Central 1.4.3
I tested with multiple titles, but you can try specifically with Beelzebub
https://weebcentral.com/series/01J76XY7EEHWD3S0TQ5T4KE8Y1/Beelzebub

I am unable to view or download chapters inapp
Please check if you're able to reproduce the issue, and reopen the issue if you can reproduce.

**Comment by noahwastaken** [comment]
I can also confirm that Weeb Central 1.4.3 does not work as the issue still persists @vetleledaal

**Comment by vetleledaal** [comment]
I still can't reproduce the issue. Tested with Beelzebub chapter 0, 1, and 240, where all the pages load.

Please try:
- Refreshing the manga entry
- Migrating the manga entry from Weeb Central to Weeb Central
- Force close the app and re-refresh the manga entry

If it is still broken I would suggest continuing troubleshooting on #repo-support in Discord. GitHub is not well suited for back-and-forth issues like this.

**Comment by noahwastaken** [comment]
@vetleledaal 
Have tried the above and no manga entrys work. All produce same issue. Tried the current 1.4.3 apk.

**Comment by Smol-Ame** [comment]
@felthand Just checking, could you paste the entire app info here? Go to Mihon More Page > About, tap the version number & paste the copied info here
