### ISSUE TITLE
Novo site da Sussy Scan PT-BR

### ISSUE THREAD

**Issue by zPlayGum007** [keiyoushi/tachiyomi-extensions-source#6145]
### Source information

Sussy Scan 1.4.41

### Source language

Portuguese (Brazil)

### Source new URL

https://new.sussytoons.site/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by DeBoaBaby** [comment]
> ### Source information
> Sussy Scan 1.4.41
> 
> ### Source language
> Portuguese (Brazil)
> 
> ### Source new URL
> https://new.sussytoons.site/
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have updated all installed extensions.
> * [x]  I have opened WebView and checked that the source URL has not changed yet.
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> * [x]  I have written a short but informative title.
> * [x]  I will fill out all of the requested information in this form.
> 
> Add a 👍 [reaction](https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to [issues you find important](https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

![Screenshot_20241119_231640_Mihon](https://github.com/user-attachments/assets/497e79fb-d662-44f3-9a67-52b6f40617ba)
