### ISSUE TITLE
Asura Scan , not able to read chapters

### ISSUE THREAD

**Issue by ThatCurious1** [keiyoushi/tachiyomi-extensions-source#6147]
### Source information

Asura Scans. 1.4.41

### Source language

English

### Steps to reproduce

Open any title in Asura Scan , and after clickng any chapters, it shows an error, No page found

### Expected behavior

Once clicked ,it should show that chapter

### Actual behavior

Once clicked, it shows no chapter found

### Mihon/Tachiyomi version

0.15.3

### Android version

14

### Other details

[
![Screenshot_2024-11-19-09-57-43-11_afd66b7916d19a60815f56273408b73e](https://github.com/user-attachments/assets/2f9e7588-f69e-47b6-847b-8d846c64d693)
](url)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ThatCurious1** [comment]
Closed

**Comment by AwkwardPeak7** [comment]
update extension and restart app; also migrate to mihon for better experience as tachiyomi is dead
