### ISSUE TITLE
6manhua and baimangu plug-in cannot open，but I can use their websites.

### ISSUE THREAD

**Issue by simulationcard** [keiyoushi/tachiyomi-extensions-source#6149]
### Source name

6manhua baimangu

### Source language

中文

### Source link

https://m.liumanhua.com/            https://www.darpou.com/

### Other details

![Screenshot_20241119_130419](https://github.com/user-attachments/assets/99686c6f-51cb-4347-99d4-d19fd6a8b641)
![Screenshot_20241119_130417](https://github.com/user-attachments/assets/20c6dd61-6c92-4935-8d45-9025889e9a83)
![Screenshot_20241119_130326](https://github.com/user-attachments/assets/d5908cbd-14c2-46bf-b247-da4348f13eff)
![Screenshot_20241119_130320](https://github.com/user-attachments/assets/93879b33-bfe1-48fc-867a-937779954a9f)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Rstoroniomi** [comment]
大家幫幫忙，謝謝！

**Comment by Rstoroniomi** [comment]
> ### Source name
> 
> 6manhua baimangu
> 
> ### Source language
> 
> 中文
> 
> ### Source link
> 
> https://m.liumanhua.com/            https://www.darpou.com/
> 
> ### Other details
> 
> ![Screenshot_20241119_130419](https://github.com/user-attachments/assets/99686c6f-51cb-4347-99d4-d19fd6a8b641)
> ![Screenshot_20241119_130417](https://github.com/user-attachments/assets/20c6dd61-6c92-4935-8d45-9025889e9a83)
> ![Screenshot_20241119_130326](https://github.com/user-attachments/assets/d5908cbd-14c2-46bf-b247-da4348f13eff)
> ![Screenshot_20241119_130320](https://github.com/user-attachments/assets/93879b33-bfe1-48fc-867a-937779954a9f)
> 
> 
> ### Acknowledgements
> 
> - [X] I have updated all installed extensions.
> - [X] I have opened WebView and checked that the source website is down.
> - [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> - [X] I have written a meaningful title with the source name.
> - [X] I will fill out all of the requested information in this form.
> 
> ### 
> 
> ---
> 
> Add a :+1: [reaction] to [issues you find important].
> 
> [reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
> [issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
>

**Comment by AwkwardPeak7** [comment]
please open separate issues for each source. Baimangu have been fixed

**Comment by Rstoroniomi** [comment]
thank you
