### ISSUE TITLE
Asura Scans, no pages found

### ISSUE THREAD

**Issue by Hellsice** [keiyoushi/tachiyomi-extensions-source#6159]
### Source information

Asura Scans 1.4.41

### Source language

English

### Steps to reproduce

1: open chapter
2: error

### Expected behavior

1: open chapter
2: read chapter

It is expected that pages are found, but this doe not appear to be happening

### Actual behavior

The extension is unable to find pages in chapters

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 11

### Other details

Webview shows that the pages are on the websites, the extension/mihon is just unable to find them.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AwkwardPeak7** [comment]
update your extension
