### ISSUE TITLE
Anime source request: Animeflix

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#616]
### Source name

Animeflix

### Source link

https://animeflix.live

### Source language

English

### Other details

There's an existing extension called "AnimeFlix" but it is different than the one I'm requesting. It leads to https://animeflix.mobi then redirects you to https://animeflix.lol. It's a complete joke.

Animeflix, the one I'm requesting, offers high quality anime with many subtitles depending on who they're ripping from. I haven't seen any dubbed animes there so I cannot confirm nor deny. They have a big community as well.

Edit: No doesn't offer NSFW content.

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by ghost** [comment]
Keiyoushi isn't a repo for anime extensions.

**Comment by Norsze** [comment]
Mango only, get your animo elsewhere

**Comment by beer-psi** [comment]
We don't do anime extensions. Go to https://github.com/aniyomiorg/aniyomi-extensions.

**Comment by ghost** [comment]
I see. It offers (or used to?) anime extensions for Aniyomi that's why I opened a request. Sorry.

**Comment by beer-psi** [comment]
> I see. It offers (or used to?) anime extensions for Aniyomi that's why I opened a request. Sorry.

We have never offered Aniyomi extensions. This has been a manga-only project since the beginning.

You might have added this extension repo to Aniyomi and then mistook their extensions for ours. You can confirm by going to https://keiyoushi.github.io/extensions and see that we have never had an extension called AnimeFlix.

AnimeFlix is available on the official Aniyomi repo however: https://aniyomi.org/extensions/#en.animeflix
