### ISSUE TITLE
Likemanga.io to Likemanga.in url change

### ISSUE THREAD

**Issue by ptoump** [keiyoushi/tachiyomi-extensions-source#6163]
### Source information

Likemanga 1.4.4

### Source language

English

### Source new URL

https://likemanga.in/

### Other details

Global Update and Update in manga page seem to work, but manga list in browse, as well as page list do not. 
There is a redirect in place  ( .io --> .in).

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by harleymerlin** [comment]
Has this case been solved?

**Comment by ptoump** [comment]
It seems that likemanga has set up a redirect from likemanga.io to likemanga.in but there is also likemanga.ink which according to https://likemanga.in/contact-us/ is their old site, while the likemanga.in is the new site. 

![image](https://github.com/user-attachments/assets/b4daba90-b6d0-4e68-bacd-771966346ca2)

**Comment by harleymerlin** [comment]
> from

So we need to wait till mihon update the extension?
