### ISSUE TITLE
Manhwa18 update stuck in Installing Loop

### ISSUE THREAD

**Issue by Georgeee0707** [keiyoushi/tachiyomi-extensions-source#6167]
### Source information

Manhwa18 1.4.11

### Source language

English

### Steps to reproduce

1. Start the download for the extension
2. Install the extension
3. Version stays 1.4.11
4. repeat

### Expected behavior

Installing update should update to the next build

### Actual behavior

Does not update to the next build and still stays on version 1.4.11

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 14

### Other details

I am aware that there is a closed issue regarding this source, but it is still not fixed due to the installing loop.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Eagle1337** [comment]
did you uninstall the old one from before keiyoushi was a thing?

**Comment by vetleledaal** [comment]
Exactly as @Eagle1337 said, you probably still have the old version installed. The [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/#app-or-extension-installation-issues) also suggests using "Split APK Installer" to get better error messages, which would probably be something related to a signature mismatch.

**Comment by Georgeee0707** [comment]
I did uninstall the old one.

**Comment by vetleledaal** [comment]
What is the error message you get from Split APK Installer?

**Comment by Norsze** [comment]
@Georgeee0707 if you could go to the Discord repo support channel that'd be great.
