### ISSUE TITLE
LikeManga

### ISSUE THREAD

**Issue by Elinosorry** [keiyoushi/tachiyomi-extensions-source#6179]
### Source information

LikeManga 1.4.4

### Source language

English

### Steps to reproduce

1. Open the extension
2. Entries do not show up and no results are found

### Expected behavior

After waiting for a few seconds the entires will show up

### Actual behavior

No results are found

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment]
Update to version 1.4.5. It was recently fixed.
