### ISSUE TITLE
Cut Pages Bug When Opening Manga in the App

### ISSUE THREAD

**Issue by denisbrunom** [keiyoushi/tachiyomi-extensions-source#6186]
### Source information

Sussy Scan 1.4.41

### Source language

Portuguese

### Steps to reproduce

Step 1 - Open "Recents."
Step 2 - Open the manga "caracteristicas evolutivas do necromante"(Necromancer's Evolutionary Traits.)
Step 3 - Go to Chapter 76, Page 46 (it happens throughout the chapter, but this is a good example).

### Expected behavior

The expected behavior is for the page to be fully legible.

### Actual behavior

When opening manga in the app, the pages appear cut, preventing the full content from being displayed. However, when accessing the same manga on the website, the issue does not occur, and all pages are displayed correctly. The bug seems to be exclusive to the app version, regardless of the selected title.

### Mihon/Tachiyomi version

Stable 0.17.0

### Android version

Android 13

### Other details

no app:
![Imagem do WhatsApp de 2024-11-20 à(s) 10 53 22_c7feadbf](https://github.com/user-attachments/assets/c46e85ec-a227-479f-9226-5700bdb9b30f)
no site:
![image](https://github.com/user-attachments/assets/6c578316-af8e-42a1-b3be-4ab3c17d3093)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by choppeh** [comment]
São duas configurações ativas no leitor que resulta nesse comportamento:
- Aparar as bordas;
- Dividir as páginas longas;

_**Caso resolva d boa, pode fechar a issue**_

https://github.com/user-attachments/assets/f61e0913-86fa-43a8-84a1-afbc4daa12f6

**Comment by Eagle1337** [comment]
disable crop borders in your viewer, there's 2.

**Comment by vetleledaal** [comment]
In any case, it is not an extension issue.
