### ISSUE TITLE
Asura scan sources not working

### ISSUE THREAD

**Issue by Kersu666** [keiyoushi/tachiyomi-extensions-source#6189]
### Source information

Not Asura scans 1.4.58

### Source language

English

### Steps to reproduce

Not downloading 

Not updating

### Expected behavior

It must show latest chapters and download it

### Actual behavior

It is not showing latest chapters nor downloading 

### Mihon/Tachiyomi version

1.11.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment]
What extension are you using? Is it from this repo? There's only:
Asura Scans
Asura Scans.gg (unoriginal)
Asura Scans.us (unoriginal)
Asura Scans TR

v1.4.58 is not a valid version of any of these extensions. 'Not Asura scans' excludes at most 4 extension, that leaves just 1382 extensions.

**Comment by Norsze** [comment]
58 must be the old Asura extension that we replaced months ago
