### ISSUE TITLE
Cubari "Brotli stream decoding failed"

### ISSUE THREAD

**Issue by CactusTheGuy** [keiyoushi/tachiyomi-extensions-source#62]
### Source information

Cubari 1.4.23

### Source language

Multi

### Steps to reproduce

1. Click Browse then press Cubari on the source tab
2. Wait until it show the error "Brotli stream decoding failed" (happen to both "Popular" and "Latest" tab)
![Screenshot_2024-01-10-11-41-15-337_eu kanade tachiyomi](https://github.com/keiyoushi/extensions-source/assets/75614340/0def2011-76ae-443e-9bd0-073d5b1d9d9a)
![Screenshot_2024-01-10-12-17-20-415_eu kanade tachiyomi](https://github.com/keiyoushi/extensions-source/assets/75614340/2a8c3e1b-ff9c-4b3b-877e-4a78c984f783)

### Expected behavior

Able to view the list of comics on cubari in tachiyomi

### Actual behavior

Error "Brotli stream decoding failed"

### Tachiyomi version

0.15.2

### Android version

MIUI 14 Android 13

### Other details

"Popular" in tachiyomi = "Pinned" in Cubari, "Latest" in tachiyomi = "History" in Cubari

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Ref: https://github.com/tachiyomiorg/tachiyomi/pull/10388
