### ISSUE TITLE
Argos Hentai - pt source request

### ISSUE THREAD

**Issue by jeanz3ra** [keiyoushi/tachiyomi-extensions-source#620]
### Source name

Argos Hentai

### Source link

https://argoshentai.com/

### Source language

Portuguese

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
The domain has been unified, so you can use filters in the search to retrieve information from the old domain \<https://argoshentai.com>.

Extension:
```kt
Argos Comics
pt.argoscomics@1.4.36
```
