### ISSUE TITLE
MangaOni connection reset

### ISSUE THREAD

**Issue by Zulxaar** [keiyoushi/tachiyomi-extensions-source#6206]
### Source name

MangaOni

### Source language

Spanish

### Source link

manga-oni.com

### Other details

When trying to open a chapter it displays a message that says "connection reset" and when entering the source browser it does not load.
![Screenshot_2024-11-21-10-21-39-397_eu kanade tachiyomi](https://github.com/user-attachments/assets/e9c3daee-1076-4fff-b706-2966c236dc87)
![Screenshot_2024-11-21-10-21-51-617_eu kanade tachiyomi](https://github.com/user-attachments/assets/637126ea-2ced-4ff7-b080-50a72a3b7364)
![Screenshot_2024-11-21-10-21-57-008_eu kanade tachiyomi](https://github.com/user-attachments/assets/cf6577b0-d763-43fb-9927-6192c0c8d069)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bapeey** [comment]
It's a problem with your connection, try enabling DoH in the app settings or a VPN
