### ISSUE TITLE
Coomer.su extension leaving out content after the first page from the source

### ISSUE THREAD

**Issue by NotYeMK** [keiyoushi/tachiyomi-extensions-source#6220]
### Source information

coomer.su 1.4.14

### Source language

All

### Steps to reproduce

1. Open up coomer.su source to search in app
2. Open up searched page in app
3. See what date the content begins in app through library or through source app
4. Compare what is showing in the app to looking at source media on the source website
5. Content begins where the first page ends for creators with multiple pages of content

### Expected behavior

It should show all pages of content available and not stop at the first page

### Actual behavior

It only loads up the first page of content shown on the source site and all the other pages before it don't show up in the app.

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Creepler13** [comment]
Theres is a setting that limits the results that is by default on one page aka 50 posts

**Comment by NotYeMK** [comment]
Ah ok. I'll close this issue then.
