### ISSUE TITLE
Mangageko( mangarawclub) URL change

### ISSUE THREAD

**Issue by Haf0** [keiyoushi/tachiyomi-extensions-source#623]
### Source information

mangarawclub 1.4.20

### Source language

English

### Source new URL

https://www.mgeko.com

### Other details

![IMG-20240125-WA0002](https://github.com/keiyoushi/extensions-source/assets/92144344/313dc0bc-0805-4910-b4bb-d875e56c16da)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Closed by #622
