### ISSUE TITLE
Flame comics URL change

### ISSUE THREAD

**Issue by Appoox** [keiyoushi/tachiyomi-extensions-source#6231]
### Source information

Flame Comics

### Source language

English

### Source new URL

https://flamecomics.xyz

### Other details

The base url remains the same; but the location of series have changed. 

For example, ORV used to be in:  
https://flamecomics.xyz/series/omniscient-readers-viewpoint

But Now it is in:
https://flamecomics.xyz/series/2
 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Appoox** [comment]
I am unsure if this is not a URL change and rather a bug. But here I go, reopen this issue. Apologies if I am wrong.

**Comment by Norsze** [comment]
We won't. Do some research on why it is not working.
