### ISSUE TITLE
sushiscan.fr - time out for volume

### ISSUE THREAD

**Issue by Celes1989** [keiyoushi/tachiyomi-extensions-source#6232]
### Source information

sushiscan.fr 1.4.33

### Source language

French

### Steps to reproduce

Just choose a volume and no a chapter

### Expected behavior

It charge faster to charge the volume before time out

### Actual behavior

Too slow so Mihon stop and say "time out"

### Mihon/Tachiyomi version

Mihon 0.17.0

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by KirinRaikage** [comment]
Can't reproduce the issue (Tried with Alice on Border Road +  All Out, which have volumes)
Can you bypass Cloudflare or do you have stable net work?

**Comment by Celes1989** [comment]
Thanks for your answer.

Are you sure you tried with the source sushiscan.fr ? (there are an other source named sushi scan which works well but the website seems abandonate because no new volume)

I tried with my smartphone (in 4G+ and wifi with fiber) + my tablet and same issue on this source (I also tried with this manga)
And yes, I bypassed cloudflare

Chapters are ok but volumes are "time out"

**Comment by KirinRaikage** [comment]
Yep. Have you tried another useragent ?

**Comment by Celes1989** [comment]
Thanks

I use that as user agent :  
Mozilla/5.0 (Linux; Android 11; SM-T725 Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.118 Safari/537.36 GoogleApp/14.4.6.26.arm64

I made a video screenshot to show the problem : https://www.youtube.com/shorts/9bJghxCHyCU
I bypass cloudflare, but volume don't load (time out) but chapters are ok.

May I have the user agent you use or if you have change something in the default parameters ?

![Screenshot_20241123_141448_app mihon](https://github.com/user-attachments/assets/54b1f37a-6c4a-4131-b3ae-2f3770e3917f)

**Comment by Celes1989** [comment]
Oh, I tried changing the user agent and it works with 
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.64 Mobile Safari/537.36

but this is strange for some manga like Demon Slave, there is "no page found"
Can you try this manga on this source if you have the same issue please ?

but others volumes works well apparently, thanks for your advice

**Comment by Celes1989** [comment]
I also desactivade DSN over https

**Comment by KirinRaikage** [comment]
Same settings as you. But indeed, I've tried with the previous user agent you've tried before, I had the time out error now. With the new one you tried, don't have errors anymore, even on "Demon Slave"
Feel free to clear WebView data and cookies in the settings.

**Comment by Celes1989** [comment]
thanks so much for your help

**Comment by KirinRaikage** [comment]
You can close the issue, it should be sorted out.
