### ISSUE TITLE
E-hentai wrong url

### ISSUE THREAD

**Issue by Wakr21** [keiyoushi/tachiyomi-extensions-source#6237]
### Source information

E-hentai 1.4.22

### Source language

Multi

### Source new URL

https://e-hentai.org

### Other details

Currently the open in web browser takes you to exhentai.org which does not exist.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment]
If you fill out `ipb_member_id` and `ipb_pass_hash` in the extension settings (or have it set by logging into WebView) it will use the alternate domain. IIRC, your account needs to be at least 1 week old before you get access.

**Comment by Wakr21** [comment]
> If you fill out `ipb_member_id` and `ipb_pass_hash` in the extension settings (or have it set by logging into WebView) it will use the alternate domain. IIRC, your account needs to be at least 1 week old before you get access.

Do you know if there's any way to log out from the website in Webbiew? Atm it directs to a blank screen, so I can't figure out a way to access the original website and log out.

**Comment by vetleledaal** [comment]
I would try clearing out the values in the extension settings **and** clear cookies in the app settings. Clearing both since I'm not sure if they are synced.
