### ISSUE TITLE
Kiryuu Change Domain

### ISSUE THREAD

**Issue by Frezian** [keiyoushi/tachiyomi-extensions-source#6247]
### Source information

Kiryuu

### Source language

Indonesia

### Source new URL

https://kiryuu.one/

### Other details

Link moved from https://kiryuu.org/ to https://kiryuu.one/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bhdai** [comment]
@Frezian the url changed but the extension still work right?

**Comment by Frezian** [comment]
> @Frezian the url changed but the extension still work right?

Not Work

**Comment by bhdai** [comment]
![kiryuu_extension](https://github.com/user-attachments/assets/f11f9903-b5fd-4e78-8366-bcedbbb43894)
bro it still works here

**Comment by Frezian** [comment]
I use Suwayomi Launcher on my PC.
![Screenshot 2024-11-24 151139](https://github.com/user-attachments/assets/d447b4c1-397a-46a4-8233-f5842577faff)

**Comment by davinantoni** [comment]
@buidai123 what's your user agent

**Comment by Norsze** [comment]
@davinantoni Shush, go away if you have nothing to contribute
