### ISSUE TITLE
E-hentai.org wrong domain

### ISSUE THREAD

**Issue by Wakr21** [keiyoushi/tachiyomi-extensions-source#6253]
### Source information

E-Hentai 1.4.22

### Source language

Multi

### Steps to reproduce

1. Open Mihon
2. Browse E-Hentai through extensions
3. Open webpage

### Expected behavior

Pages and entries should load, webpage should take you to E-Hentai.org.

### Actual behavior

No entries load on app, in-app browser takes you to exhentai.org instead.

### Mihon/Tachiyomi version

0.17

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Norsze** [comment]
You already had an answer in #6237

F off

**Comment by Wakr21** [comment]
> You already had an answer in #6237
> 
> F off

Geez man calm down, it got auto taken down because I posted it in the wrong section and thus didn't see the comment

**Comment by Norsze** [comment]
it got auto closed, but Vetle did give you an explanation. You just disregarded it
