### ISSUE TITLE
quero alterar uma url de uma extensão.

### ISSUE THREAD

**Issue by vinidavi** [keiyoushi/tachiyomi-extensions-source#6263]
### Source information

SlimeRead 1.4.13

### Source language

Português Brasil PT - BR

### Source new URL

https://slimeread.com

### Other details

![Screenshot_2024-11-24-09-00-58-03_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/18efa856-6770-428e-b8e9-e4b3c268fcbc)
![Screenshot_2024-11-24-09-00-47-95_afd66b7916d19a60815f56273408b73e](https://github.com/user-attachments/assets/d5af40b2-5724-4863-a715-86edf7fc6118)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vinidavi** [comment]
the error is about changing the domain not adding an extension.

**Comment by Norsze** [comment]
Mm, no, the error is about API URL which you don't seem to have a clue what it is. Doesn't matter though as you are someone who didn't even search existing issues, someone already opened the right type of issue, I will let you try to find it on your own
