### ISSUE TITLE
Eu acho que trocaram a URL da extensão SlimeRead

### ISSUE THREAD

**Issue by ToshiroLv** [keiyoushi/tachiyomi-extensions-source#6270]
### Source information

SlimeRead 1.4.14

### Source language

Português Brasil - PT-BR

### Source new URL

https://slimeread.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ToshiroLv** [comment]
![Screenshot_2024-11-24-15-54-07-525_app mihon](https://github.com/user-attachments/assets/1669c050-a30f-4bc8-a25e-40d5fe69d59b)
![Screenshot_2024-11-24-15-55-04-261_com opera gx-edit](https://github.com/user-attachments/assets/fad4e208-6015-4a69-b64d-473d62b320f3)

**Comment by Norsze** [comment]
Duplicate of #6242
