### ISSUE TITLE
Naver Webtoon

### ISSUE THREAD

**Issue by gamespvp93** [keiyoushi/tachiyomi-extensions-source#6274]
### Source information

1.4.5

### Source language

한국어

### Steps to reproduce

The extension is not saving the settings I make on the website through the app. For example, when I set the website to PC mode within the extension, it doesn't stay in PC mode when I access it again. This issue started happening to me recently. To keep the PC mode or account settings saved, I need to clear the data of Mihon, which is the app I use to open the extension.

### Expected behavior

The extension was to save the settings I make on the website through the app.

### Actual behavior

The extension unfortunately is not saving the settings I make on the website through the app.

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Norsze** [comment]
Just to make this clear, is this about using the webview?

**Comment by Norsze** [comment]
Actually never mind I'm 99% sure you are talking about webview. Webview is a means to an end, it is to help you pass Cloudflare checks or login to access locked content. If what you want is to browse on the web page, then use a browser and bookmarks. The point of apps like Mihon and the extensions is that you use the app to read, not to access a watered down version of the chrome browser (aka Webview)
