### ISSUE TITLE
Weeb Central webview/open in browser while inside a chapter appends unnecessary formatting in url which results in a website that u can't interact with to view comments, next chapter etc.

### ISSUE THREAD

**Issue by Kitsune2431** [keiyoushi/tachiyomi-extensions-source#6275]
### Source information

Weeb Central 1.4.5

### Source language

English

### Steps to reproduce

1. Open any chapter of any manga
2. Open in webview or browser

### Expected behavior

Regular website of chapter without formatting should open.

### Actual behavior

Formatted website of chapter opens which consists of manga pages only with no way to do anything else.

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 14

### Other details

Example:
[https://weebcentral.com/chapters/01JD2G6FZWE7NPKFNWWPTSFZJW/images?is_prev=False&reading_style=long_strip](https://weebcentral.com/chapters/01JD2G6FZWE7NPKFNWWPTSFZJW/images?is_prev=False&reading_style=long_strip)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Norsze** [comment]
I do believe there is a good reason why longstrip is selected, to get all the images on one page. This causes less stress on the source as there are less calls and requests. Also gonna say that our main focus is to make the extension work, not webview, if you want to read in a browser you should read in a real browser.

**Comment by Kitsune2431** [comment]
It's not about reading in browser. It's a fallback for reading in case app refuse to load. I also like reading comments from time to time for on going manga and you can only do it in webview. I'm not trying to annoy you by reporting this. Other extensions have normal url, so i assumed it's a bug. If you consider this as correct behaviour, then so be it. I just liked the soon to be deprecated mangasee and wanted the new weebcentral to work correctly.
