### ISSUE TITLE
SlimeRead ERRO

### ISSUE THREAD

**Issue by Poiares** [keiyoushi/tachiyomi-extensions-source#6278]
### Source information

SlimeRead 1.4.14

### Source language

Português (Brasil)

### Steps to reproduce

Show the erro: Could not find API URL

### Expected behavior

Show works available

### Actual behavior

![Screenshot_2024-11-24-23-22-37-625_app mihon](https://github.com/user-attachments/assets/a86e10c9-feef-4256-b749-64e907564e9b)

### Mihon/Tachiyomi version

App version: 0.17.0 (standard, 38d5fc9, 8, 2024-10-26T17:39:14Z)

### Android version

Android version: 14 (SDK 34; build UKQ1.231003.002 release-keys)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Norsze** [comment]
Duplicate of #6242

**Comment by Poiares** [comment]
thanks, i am newbie here.
