### ISSUE TITLE
Trocaram a URL da extensão SlimeRead

### ISSUE THREAD

**Issue by ToshiroLv** [keiyoushi/tachiyomi-extensions-source#6279]
### Source information

SlimeRead 1.4.14

### Source language

Português Brasil - PT-BR

### Source new URL

https://slimeread.com/

### Other details

![Screenshot_2024-11-24-15-54-07-525_app mihon](https://github.com/user-attachments/assets/5e95b131-e7c0-47c9-89dc-66d941bcad52)
![Screenshot_2024-11-24-15-55-04-261_com opera gx-edit](https://github.com/user-attachments/assets/0b8cc9c6-85c7-4341-878f-8a5cdfca5e20)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Norsze** [comment]
#6242 fucking read @ToshiroLv READ
