### ISSUE TITLE
Tsuki-Mangas - SockeTimeoutException: Time out

### ISSUE THREAD

**Issue by nomaxsnx** [keiyoushi/tachiyomi-extensions-source#628]
### Source information

Tsuki-Mangas 1.4.1

### Source language

Português 

### Steps to reproduce

1 - install extension Tsuki-Mangas
2 - Open extension
3 - wait now

### Expected behavior

TimeOut

### Actual behavior

![Screenshot_2024-01-25-12-08-31-947_app mihon-edit](https://github.com/keiyoushi/extensions-source/assets/157644160/271c678b-0a92-4dd3-a3c1-ff152cb3bca3)

### Tachiyomi version

0.16.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Keiyoushi is **not** hosting any content, we are not affiliated with or responsible for any source that is: slow, down, missing chapters, or has subpar image quality.
