### ISSUE TITLE
A fonte SlimeRead não está funcionando 

### ISSUE THREAD

**Issue by Klaus07b** [keiyoushi/tachiyomi-extensions-source#6280]
### Source information

SlimeRead

### Source language

Português BR

### Steps to reproduce

Could not find API URL

### Expected behavior

![Screenshot_2024-11-25-00-11-44-595_app mihon](https://github.com/user-attachments/assets/938544db-192b-4652-b1de-13ae828e7ffd)

### Actual behavior

![Screenshot_2024-11-25-00-11-50-952_app mihon](https://github.com/user-attachments/assets/e8627eee-9830-4082-8fba-7f04d6370866)

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Adicione um :+1: [reação] em [questões que você achar importante].

[reação]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[questões que você acha importante]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-

**Comment by Norsze** [comment]
Duplicate of #6242
