### ISSUE TITLE
SLIMEREAD Error (PT-BR) 

### ISSUE THREAD

**Issue by ImSARAGOSSA** [keiyoushi/tachiyomi-extensions-source#6287]
### Source information

slimeread - 1.4.14

### Source language

Brazilian Portuguese

### Steps to reproduce

![Screenshot_20241125_071720_Mihon](https://github.com/user-attachments/assets/6eb44d4f-e8fe-4c45-9237-d51b7bd65b09)

### Expected behavior

the bug in this extension had already been fixed, but they updated the site and now it's not working again. 
It is the best extension we have for our language now that all others have been torn down. 
I've already tried reinstalling, changing connections, etc

### Actual behavior

When we open the extension or try to read something from the library this error occurs: Could Not Find API URL 

### Mihon/Tachiyomi version

0.17.0

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dngonz** [comment]
Another Duplicate #6242

**Comment by ImSARAGOSSA** [comment]
> Another Duplicate #6242

Yes, that's why I mentioned that the error had been resolved, but the same error appeared again.

**Comment by dngonz** [comment]
The PR #6246 is not yet merge, that why has not been resolve
