### ISSUE TITLE
Trocaram a URL da extensão Slime read

### ISSUE THREAD

**Issue by XDGAMES2** [keiyoushi/tachiyomi-extensions-source#6289]
### Source information

Slimeread 1.4.14

### Source language

Português Brasil - PT-BR 

### Steps to reproduce

https://slimeread.com

### Expected behavior

O comportamento esperado é que funcione normalmente mais não tá funcionando as outras extensões funciona mais ela não tá funcionando 

### Actual behavior

![Screenshot_20241125_074451_Mihon](https://github.com/user-attachments/assets/cb983b1f-313a-46a5-90e1-86d60853b448)

### Mihon/Tachiyomi version

0.17.0

### Android version

13

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [ ] I have written a short but informative title.
- [ ] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [ ] I have updated all installed extensions.
- [ ] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [ ] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Norsze** [comment]
Duplicate of #6242
