### ISSUE TITLE
Trocaram a URL Da extensão Slime read

### ISSUE THREAD

**Issue by XDGAMES2** [keiyoushi/tachiyomi-extensions-source#6290]
### Source information

Slimeread 1.4.14

### Source language

Português Brasil - PT-BR 

### Source new URL

https://slimeread.com

### Other details

![Screenshot_20241125_074451_Mihon](https://github.com/user-attachments/assets/14e954d7-31bd-4058-b62a-ba88e1ab51d6)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Norsze** [comment]
Duplicate of #6242
