### ISSUE TITLE
No page previews on some NHentai doujins and all manga on Komga

### ISSUE THREAD

**Issue by HawaiianPizza** [keiyoushi/tachiyomi-extensions-source#6292]
### Source information

NHentai 1.4.48, Komga 1.4.58

### Source language

English

### Steps to reproduce

1. Browse > Sources > NHentai or Komga.
2. Open up any doujin.
3. No preview could be seen.
4. Only for NHentai: Sometimes, page previews would be shown. But most don't have any page previews.
5. For Komga: Page previews are never shown.

### Expected behavior

Page preview should be shown. See image: 

![signal-2024-11-25-110415_003](https://github.com/user-attachments/assets/1dd8bd2b-9e34-47cc-b313-710e408ee600)

### Actual behavior

No page preview shown. See image:

![signal-2024-11-25-110513_002](https://github.com/user-attachments/assets/3858b0db-47b0-4974-ac9a-bfb88e879fde)

### Mihon/Tachiyomi version

TachiyomiSY 1.11.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
Page previews is an SY-specific (fork) feature, not done by the extension

Also, censor or blur a bit more (for future reference), no NSFW pictures in GitHub pls
