### ISSUE TITLE
[Thunder Scans] Detecting last premium chapter

### ISSUE THREAD

**Issue by ehsan18t** [keiyoushi/tachiyomi-extensions-source#6313]
### Source information

Thunder Scans 1.4.36

### Source language

English

### Steps to reproduce

Open any manhwa with premium chapter.

### Expected behavior

Shouldn't detect premium chapter.

### Actual behavior

Detected the premium chapter.

![Screenshot_2024-11-26-16-49-03-662_eu kanade tachiyomi sy](https://github.com/user-attachments/assets/465b998c-4457-4735-970c-fbbcf83defc8)

(Ch 35 is premium chapter. There are ch 34 which is also premium, but not detecting.)

### Mihon/Tachiyomi version

Mihon Preview r7015

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mrtear** [comment]
related to https://github.com/keiyoushi/extensions-source/issues/5908

https://github.com/keiyoushi/extensions-source/issues/5908#issuecomment-2466734304

**Comment by Norsze** [comment]
I would go as far as calling it a duplicate even, unless someone can explain the difference to me

**Comment by mrtear** [comment]
> I would go as far as calling it a duplicate.

it is.

**Comment by ehsan18t** [comment]
It seems like a duplicate. I searched with `Thunder Scans` but no issue found back then.

I tried searching again, the issue mentioned is showing now.
