### ISSUE TITLE
Error http 525

### ISSUE THREAD

**Issue by Francorep12** [keiyoushi/tachiyomi-extensions-source#6324]
### Source information

https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json

### Source language

Español

### Steps to reproduce

Primero que nada me pasa solo con una app que descargue de la fuente y es olympus scan y me andaba bien y de la nada me sale el error http 525 y no me deja actualizar mis manwhas y me salta un error

### Expected behavior

Lo que deberia suceder esque me carguen con normalidad los capitulos pero no me deja hacer nada, presiono el capitulo y me saca y me dice error http 525

### Actual behavior

Salio el error http 525

### Mihon/Tachiyomi version

0.16.4.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Norsze** [comment]
Duplicate of #6300
