### ISSUE TITLE
Problemas en las fuentes de origen Español 

### ISSUE THREAD

**Issue by SoelMorow** [keiyoushi/tachiyomi-extensions-source#6325]
### Source information

Olympus Scanlantion

### Source language

Español

### Steps to reproduce

No funciona, como decirlo, cambió de sitio web por lo tanto la fuente en Mihon y sus diferentes versiones ya no funciona. 
![Screenshot_2024-11-26-12-01-20-940_app mihon](https://github.com/user-attachments/assets/0caa5787-de08-470a-89b0-152e7ffc9dd6)
![Screenshot_2024-11-26-12-01-18-565_app mihon](https://github.com/user-attachments/assets/2a343712-a71b-4889-9e42-a2f09f1918bc)

### Expected behavior

Debería abrir naturalmente dejándome ver el diverso catálogo de Manhwa's

### Actual behavior

No habré, ni siquiera me permite leer los Manhwa's guardados en mi biblioteca, unos días antes de que dejara de funcionar, no me permitía ver la portada de los manhwas en la fuente. 

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Norsze** [comment]
Duplicate of #6300
