### ISSUE TITLE
Bring back Kavita from Upstream

### ISSUE THREAD

**Issue by RandomLegend** [keiyoushi/tachiyomi-extensions-source#633]
### Source name

Kavita

### Source link

https://github.com/Kareadita/Kavita/releases

### Source language

Universal

### Other details

In #579 Komga was added back as it was asked for in #225 but there was also asked for others that are similar like Kavita.

Can we please bring back Kavita aswell?

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Kareadita (the organization that manages Kavita) already hosts a Kavita extension: https://github.com/Kareadita/tachiyomi-extensions

**Comment by RandomLegend** [comment]
There is nothing in the github. I can't add the repo to Mihon and there is nothing in the readme.
