### ISSUE TITLE
add new extension in brazilian portuguese

### ISSUE THREAD

**Issue by pedrodhss** [keiyoushi/tachiyomi-extensions-source#6334]
### Source name

InfinyxScan

### Source link

https://infinyxscan.cloud/

### Source language

Português Brasil- PT-BR

### Other details

![Screenshot_20241126-184419_Brave](https://github.com/user-attachments/assets/b2443382-8a3c-4e11-85a3-872aafa7bfc7)
![Screenshot_20241126-184408_Mihon](https://github.com/user-attachments/assets/2787581b-81af-4870-bac8-9d728d8caac1)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AnonymousPtBr** [comment]
Good!

**Comment by EvaldoCeBr** [comment]
Very good!
