### ISSUE TITLE
url extension di Indonesia kebanyakan sudah tidak bisa

### ISSUE THREAD

**Issue by afdhalzikri07** [keiyoushi/tachiyomi-extensions-source#6345]
### Source information

kiryuu 1.4.38 komikcast 1.4.60 komikindoid 1.4.41 komiku.com 1.4.30

### Source language

bahasa Indonesia 

### Source new URL

https://kiryuu.one/ https://komikcast.bz/ https://komikindo.wtf /https://komiku.com/  

### Other details

tolong di fixed secepatnya 
![Screenshot_20241127-105102](https://github.com/user-attachments/assets/b091cda8-809b-474a-b33f-a3b6d9aee135)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by afdhalzikri07** [comment]
> Masalah ini ditutup karena ekstensi dengan URL yang disediakan (komiku.com) sudah ada dengan nama **Komiku.com** , di bawah bagian **Bahasa Indonesia** .
> 
> _Ini adalah tindakan otomatis. Jika menurut Anda ini adalah kesalahan, silakan berikan komentar agar masalah ini dapat dibuka kembali jika diperlukan._

Salah domain masi tidak bisa

**Comment by vetleledaal** [comment]
You should only report one issue per issue report. #6240 and #6247 are still open, so there is no fix. Komiku.com is already using the domain you specified, if you're having issues, you are using the wrong issue template. Only komikindoid seems valid, but since you reported everything in one issue (with duplicates) it was closed automatically.
