### ISSUE TITLE
Flame comics HTTP 404

### ISSUE THREAD

**Issue by Obm16** [keiyoushi/tachiyomi-extensions-source#6349]
### Source information

Flame comics 1.4.34

### Source language

English

### Source new URL

https://flamecomics.xyz/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Obm16** [comment]
The error is still there. The chapters are not present in the application.

**Comment by Norsze** [comment]
Congrats you just described the very much still open issue, you can give yourself a big fat F in reading comprehension 👍
