### ISSUE TITLE
Baimangu didn't work，please help me.❤️😉

### ISSUE THREAD

**Issue by simulationcard** [keiyoushi/tachiyomi-extensions-source#6351]
### Source information

1.4.3

### Source language

中文

### Steps to reproduce

![Screenshot_20241127_234408](https://github.com/user-attachments/assets/951fe945-f17a-45ee-905c-41e57989c726)

### Expected behavior

I except it will be opening

### Actual behavior

but the truth is that this 插件 not working
![Screenshot_20241127_234408](https://github.com/user-attachments/assets/9c890ab0-1012-44fc-82ac-ed86f2274c6e)

### Mihon/Tachiyomi version

0.17.0

### Android version

Android9

### Other details

百漫谷not working，please help me

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Rstoroniomi** [comment]
![Screenshot_20241127_234750.jpg](https://github.com/user-attachments/assets/a57c0474-5d48-4cd6-b8c4-2e529948e523)
