### ISSUE TITLE
Read Comics Book dead

### ISSUE THREAD

**Issue by hyoretsu** [keiyoushi/tachiyomi-extensions-source#6352]
### Source name

Read Comics Book

### Source language

English

### Source link

https://readcomicsplus.net

### Other details

Existing comics give a null error and WebView redirects to ComicExtra, which already has an extension.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dngonz** [comment]
It's not down just redirect to [https://comixextra.com/](https://comixextra.com/)

**Comment by FourTOne5** [comment]
> Existing comics give a null error and WebView redirects to ComicExtra, which already has an extension.

**Comment by dngonz** [comment]
My bad, didn't check
