### ISSUE TITLE
Update Sussy Scans site

### ISSUE THREAD

**Issue by MilZeros** [keiyoushi/tachiyomi-extensions-source#6376]
### Source name

Sussy Scan

### Source language

Brazilian Portuguese - Português (Brasil) - PT BR

### Describe your suggested feature

The Scan, create a new site.

The new site: https://new.sussytoons.site
![IMG_20241128_195501](https://github.com/user-attachments/assets/3e4b47bd-c338-4fc5-8fc8-277fbb534f9c)

### Other details

Thank for suport.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment]
#6034
