### ISSUE TITLE
Zaimanhua:希望再漫画插件增加在章节末尾添加吐槽页功能

### ISSUE THREAD

**Issue by Volundio** [keiyoushi/tachiyomi-extensions-source#6378]
### Source name

再漫画

### Source language

Chinese

### Describe your suggested feature

类似拷贝漫画和动漫之家的插件，允许阅读到章节末尾的时候显示当前章节的吐槽评论
![Screenshot_2024-11-29-07-19-58-073_eu kanade tachiyomi j2k-edit](https://github.com/user-attachments/assets/ad138709-66ab-4638-89d5-8989f0ef9530)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by zhongfly** [comment]
那么再漫画(网页/官方app)是不是有这个功能呢？
据我了解是没有的
再漫画≠动漫之家
漫画源没有的，没办法凭空变出来

**Comment by zhongfly** [comment]
另外，上次我也说过，现在再漫画的app，内部的漫画阅读器是用的tachiyomi/mihon，可以预见，他们在这个基础上添加发吐槽的功能会比较困难。

请下载使用再漫画app亲自体验:
https://www.zaimanhua.com/app/index.html

**Comment by Volundio** [comment]
> 另外，上次我也说过，现在再漫画的app，内部的漫画阅读器是用的tachiyomi/mihon，可以预见，他们在这个基础上添加发吐槽的功能会比较困难。
> 
> 请下载使用再漫画app亲自体验: https://www.zaimanhua.com/app/index.html

不好意思，是我欠考虑了
