### ISSUE TITLE
Eternalmangas It is not functional 

### ISSUE THREAD

**Issue by Leon0000oooo** [keiyoushi/tachiyomi-extensions-source#6392]
### Source information

Eternalmangas 1.4.4

### Source language

Português PT-BR

### Steps to reproduce

![Screenshot_2024-11-29-19-24-09-378_app mihon](https://github.com/user-attachments/assets/63329183-6904-4b22-bfa1-f90d215546d5)
![Screenshot_2024-11-29-19-24-26-883_app mihon](https://github.com/user-attachments/assets/b92fcf4f-c7e9-4d9b-a35a-478877745aca)

### Expected behavior

I have already done the help procedures and the ones I knew, and the problem was not solved. 

### Actual behavior

The mangas on the site were supposed to appear, but instead nothing appears. Open the web view and the site appears normally.  I think it is necessary to log in, but it gives an error when doing this through WebView, I am grateful for the work, it is my favorite reader, not comparison. If there was a way to log in to the site, perhaps the works would be released, a way to get around this login error..., there are two extensions that I really appreciate, which have this error, thank you very much.

### Mihon/Tachiyomi version

1.4.4

### Android version

Android 14

### Other details

I am very grateful. Happy Holidays. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bapeey** [comment]
you are using the pt-br version of the extension, you should use the spanish version for those comics
