### ISSUE TITLE
Source not updating and categorys swapped

### ISSUE THREAD

**Issue by lukor79** [keiyoushi/tachiyomi-extensions-source#6400]
### Source information

Manhwa18 

### Source language

English 

### Steps to reproduce

Open source, observation that it is indeed not working properly 

### Expected behavior

The most popular should be the most popular and the latest should be the latest updated

### Actual behavior

The latest and most popular sections are swapped +1 and stopped updating 4 days ago

Caution NSFW 
I had to cut the video into chunks to upload sorry

\<NSFW video removed\>

\<NSFW video removed\>

\<NSFW video removed\>

\<NSFW video removed\>

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 14

### Other details

If you have any questions ping me on the discord server @ZebraBread

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment]
Do not post NSFW content on GitHub.

**Comment by lukor79** [comment]
![Screenshot_20241213_132132_Mihon](https://github.com/user-attachments/assets/1655e3f3-926b-40c5-b1b2-cc8edf2b8d44)
