### ISSUE TITLE
Quero pedir a adição de uma nova extensão que surgiu no português brasileiro

### ISSUE THREAD

**Issue by Maateus21397** [keiyoushi/tachiyomi-extensions-source#6426]
### Source name

Sussytoons

### Source link

https://new.sussytoons.site/

### Source language

Português Brasil-PT-BR

### Other details

![Screenshot_20241202-110918](https://github.com/user-attachments/assets/3ca7c64a-ba98-42bc-90c8-73f6c96512ef)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by choppeh** [comment]
Duplicate: #6034

**Comment by Smol-Ame** [comment]
1. It's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.
2. It's not a "Source request" when there's an extension for the source already, it's a "URL change request"
