### ISSUE TITLE
GALAXY MANGA: Couldn't reach problem

### ISSUE THREAD

**Issue by YYSS15** [keiyoushi/tachiyomi-extensions-source#643]
### Source information

ar.galaxymanga 1.4.30

### Source language

Arabic 

### Steps to reproduce

When I try to browse the manga list  this error showing to me 
![Screenshot_20240126-011633](https://github.com/keiyoushi/extensions-source/assets/132961602/8e451f97-a062-42f5-9f7a-11a95f4e5c0f)

### Expected behavior

The list of manga/manhwa should be listed 

### Actual behavior

When I try to browse the manga list  this error showing to me 
![Screenshot_20240126-011633](https://github.com/keiyoushi/extensions-source/assets/132961602/8e451f97-a062-42f5-9f7a-11a95f4e5c0f)

### Tachiyomi version

0.15.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
Cannot reproduce.
![Screenshot_Mihon](https://github.com/keiyoushi/extensions-source/assets/48650614/c014f9da-709f-4f11-a514-24fba4f79e9f)

**Comment by YYSS15** [comment]
The issue still happening to me. What should do I do ?
