### ISSUE TITLE
Comick late with manga updates compared to website

### ISSUE THREAD

**Issue by nphalem** [keiyoushi/tachiyomi-extensions-source#6452]
### Source information

1.4.5

### Source language

English

### Steps to reproduce

Blue lock has released a new chapter and it's not possible to update it or open in. (https://comick.io/comic/03-blue-lock)

Tried updating manually and tried opening the link in the app

### Expected behavior

Comick should update and provide latest chapter and when opening the link should open the chapter

### Actual behavior

Blue Lock page is opened but there is no latest chapter.

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 15

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment]
Chapter 286 was posted 2024-12-03T18:35:11Z, you created this issue at 2024-12-03T19:26:__Z. The cache is valid for 1 hour, so you probably just hit the cache. The reason for the mismatch between the extension and the site is due to using different request parameters.

This can be solved by cache-busting, but that is not a real solution. If anything, the site should invalidate all relevant caches when a new chapter is posted.

**Comment by nphalem** [comment]
I know this sounds like just being to impatient but I was wondering why I couldn't trigger update myself so thank you very much for the detailed explanation.
