### ISSUE TITLE
mangawt extension not working

### ISSUE THREAD

**Issue by ReCoffee** [keiyoushi/tachiyomi-extensions-source#6456]
### Source information

MangaWT

### Source language

Turkish / Türkçe

### Steps to reproduce

![image](https://github.com/user-attachments/assets/6f91adb7-badd-412a-9474-5aedc4fe6980)
![image](https://github.com/user-attachments/assets/53a372df-6969-45fe-9cf0-b80c0837eec2)
![image](https://github.com/user-attachments/assets/efe7ee3f-6d25-4c9f-978e-26477659d288)
![image](https://github.com/user-attachments/assets/581495b7-cf87-49f8-9139-75b4732c5d89)

### Expected behavior

Extension works

### Actual behavior

Extension does not works

### Mihon/Tachiyomi version

0.17.7015 Beta

### Android version

Android 13

### Other details

Even though I open webview it doesn't work

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment]
Domain changed to .com
