### ISSUE TITLE
Source request: Zona Fantasma

### ISSUE THREAD

**Issue by Pedro5644** [keiyoushi/tachiyomi-extensions-source#6462]
### Source name

Zona Fantasma

### Source link

https://zonafantasmanet.wordpress.com/

### Source language

Português Brasil - PT-BR

### Other details

![Screenshot_20241204-095709](https://github.com/user-attachments/assets/6a847cf6-5631-4c0b-bbe8-216f520828f1)
![Screenshot_20241204-095619](https://github.com/user-attachments/assets/13b2117e-3b34-4b8c-a813-83afb659eedf)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AnonymousPtBr** [comment]
Muito bom! Só usava a HQ Now, agora vou ter outra extensão para ler HQ. Tomara que alguém de bom coração faça o plugin!

**Comment by Norsze** [comment]
Actually, this is just a site with mediafire links, not a site able to become an extension.
