### ISSUE TITLE
Cambio la URL de Jobsibe

### ISSUE THREAD

**Issue by aldo4635** [keiyoushi/tachiyomi-extensions-source#6486]
### Source information

es.Jobside 1.4.38

### Source language

Español

### Source new URL

https://lmtos.com/

### Other details

Cambio el dominio por eso no deja acceder 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bapeey** [comment]
Probably your using a deprecated extension, uninstall your current extension and install the new one with the same name `Jobsibe`. Migration will be required

**Comment by Smol-Ame** [comment]
Seems to work fine currently (besides the chapter date), closing

Come to the Keiyoushi Discord repo-support channel for troubleshooting if needed, or for any basic questions/issues
