### ISSUE TITLE
Pururin has been seized. Please pull from extension repo

### ISSUE THREAD

**Issue by molitar** [keiyoushi/tachiyomi-extensions-source#6493]
### Source name

Pururin

### Source language

English

### Source link

pururin.io

### Other details

verified here https://www.reddit.com/r/animepiracy/comments/1g17n39/pururin_is_now_gone/ and https://boards.4chan.org/h/thread/8251046/pururin-is-seized

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
It seems to be working fine on my end. Try switching networks, use a VPN, or maybe adjust your user-agent if needed.

Add-on, looking at the Reddit post, I remember the concensus with users is that it was a fake out with the seized warning. Also, the current extension uses a .me link rather than .io or .to

![Screenshot_20241206_192256_Mihon.png](https://github.com/user-attachments/assets/c1f5c2f5-1bd5-449f-a1b5-e40841817f0a)

![Screenshot_20241206_192510_Mihon.png](https://github.com/user-attachments/assets/be5ae293-1d90-4102-a94c-143b949d71d9)

**Comment by molitar** [comment]
OK that is a new domain now let's hope that is not a honeypot and is really them.  As their is many images of Pururin.io has been seized with the actual seizure domain name servers. 

Here is from a month ago.
Domain: pururin.to
Created on: Fri Apr 30 20:39:50 2021
Last edited on: Thu Oct 10 09:06:17 2024
Expires on: Sun Jun 29 15:16:52 2025
Primary host add: None
Primary host name: ns1.seizedservers.com
Secondary host add: None
Secondary host name: ns2.seizedservers.com 

Than a day later we have this...

Expires On: 2025-01-16
Updated On: 2024-10-11

Status:
clientTransferProhibited
Name Servers:
ns1.abelons.com
ns2.abelons.com
ns3.abelons.com

for now I think I will avoid this site until confirmation comes down.  the seizedservers.com are government seized servers domain name servers.  Pretty strange it changes to new domain servers day later.  Also strange to only renew for 3 months really looks and smells like a honeypot trap to me now.

**Comment by KenjieDec** [comment]
The new domain was taken from their discord, it should be legit.
![image](https://github.com/user-attachments/assets/4ebc8565-884c-4c9e-9ba4-8fc6d68ee903)

**Comment by Smol-Ame** [comment]
Closing as answered/not an issue
