### ISSUE TITLE
MyReadingManga

### ISSUE THREAD

**Issue by sakamichii** [keiyoushi/tachiyomi-extensions-source#6504]
### Source information

MyReadingManga 1.4.53

### Source language

English, Japanese

### Steps to reproduce

1. Open Browse tab
2. On sources, click myreadingmanga
3. Error message "Failed to bypass Cloudflare"
4. Click on three dots on upper right, then "open in webview"
5. Page displays "not found".
6. Select open in browser, website is functioning normally.

### Expected behavior

When opening up the source the latest chapters should show up, but because it fails to bypass cloudflare it won't load. Usually the issue is resolved by opening the source in webview and verifying my internet connection.

### Actual behavior

When opening the page in webview it only says "not found". If I open it in my browser from there it shows up normally, but never in app. Clearing cookies also doesn't work.
![Screenshot_20241206_225237_Tachiyomi](https://github.com/user-attachments/assets/a28c2d3f-7661-4a20-a2d7-6f4141afafd0)

### Mihon/Tachiyomi version

0.15.3

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment]
#5675
