### ISSUE TITLE
Manhwa18.cc

### ISSUE THREAD

**Issue by Hsjjsshsh** [keiyoushi/tachiyomi-extensions-source#6507]
### Source name

Manhwa18.cc

### Source language

English 

### Source link

https://manhwa18.cc/

### Other details

Can't Open

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
Seems to work fine currently, checked like 12 different chapters in random titles. Maybe a site/source's server hiccup

Come to the Keiyoushi Discord repo-support channel for basic troubleshooting, and/or make another issue request with more details (which chapters/series) than "can't open"
