### ISSUE TITLE
Arven Scans: Unable to load source's Browse & update chapter list

### ISSUE THREAD

**Issue by Smol-Ame** [keiyoushi/tachiyomi-extensions-source#6515]
### Source information

Arven Scans 1.4.33

### Source language

English

### Steps to reproduce

1. Go into source's Browse page
2. Enter WebView, pass verification, and back out of WebView
3. Refresh or back out & go back into Browse page, still can't find entries

And/or, from repo-support user:
1. Go into manga entry in Library
2. Go into WebView & pass verification
3. Back out of WebView & refresh the chapter list
4. Still fails after passing verification

### Expected behavior

Should find entries/update the chapter list after passing verification

### Actual behavior

Fails to find entries/update the chapter list after passing verification

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 14

### Other details

From user's repo-support message:
* "it seems accessing the extension website directly in webview does not cause the CF check loop, but if im accessing a series webview, it will be in a loop, no idea why, im not trying a bunch of UAs seeing which one will stick"
* "They might be doing something weird, the only UAs that worked for me are safari and firefox ones (to get past the CF check, chromium based UA get stuck in a loop)"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment]
So the issue only occurs with specific UAs? Using the default UA in Mihon works.

**Comment by Smol-Ame** [comment]
On stable internet, works as intended, closing
