### ISSUE TITLE
Reaper scans Updated URL and template

### ISSUE THREAD

**Issue by sinnghabhay80** [keiyoushi/tachiyomi-extensions-source#652]
### Source information

reaperscans.com

### Source language

English

### Source new URL

reaper-scans.com

### Other details

The older one is missing some mangas like nano machine. Please update to the newer one.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by sinnghabhay80** [comment]
What the hell is a url change then?
Of course l it exists already that why change of url.

**Comment by beer-psi** [comment]
If you joined their Discord and searched for `reaper-scans.com` you would know it's not the real website. Reaper dropped Nano Machine a while back, which is why you don't see it on their official website.

**Comment by sinnghabhay80** [comment]
Yup just saw on discord.
