### ISSUE TITLE
Add url domain change feature for all extension

### ISSUE THREAD

**Issue by RXDCODX** [keiyoushi/tachiyomi-extensions-source#6532]
### Source name

HenChan 1.4.41

### Source language

Russian

### Describe your suggested feature

I suggest the possibility to change the domain for all extensions like HenChan 1.4.41 extension 

### Other details

![Screenshot_2024-12-08-17-31-39-64_551f7f0ca926862b368845ce7ee433aa](https://github.com/user-attachments/assets/e789ec2f-b128-46f4-ab09-9f85f3e43e19)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
Most sources aren't just "update the URL & everything will work like magic", they can undergo selector changes, site theme changes, redirects, additional of fields/info, etc etc. Any of those changes could require changes to the code for the extension and/or the theme the extension uses.

**Comment by vetleledaal** [comment]
This option will only be added to extensions known to change URL often. Open a feature request for _each_ extension you feel need it.

Adding a 'catch-all' for all extensions means it's not really an extension feature request, but rather a feature request with the app.
