### ISSUE TITLE
Bug: Slimeread: XSS Attack?

### ISSUE THREAD

**Issue by drysius** [keiyoushi/tachiyomi-extensions-source#6535]
### Source information

Slimeread

### Source language

Português (pt)

### Steps to reproduce

Download and install slimeread and use

### Expected behavior

List of mangas

### Actual behavior

{
  "username": "<script>alert('XSS Attack')</script>",
  "password": "' OR '1'='1",
  "email": "test@example.com",
  "message": "<img src='x' onerror='alert(1)' />",
    "comment": "Test comment with payload <script>alert('XSS')</script>",
    "json_data": "{\"key\":\"value\",\"injection\":\"<script>alert('injected');</script>\"}",
    "name": "<script>alert('XSS Attack');</script>",
    "email": "test@example.com",
    "password": "password123",

}

### Mihon/Tachiyomi version

App version: 0.16.4.3 (standard, 959f84a, 124, 2024-07-01T22:25Z) Android version: 13 (SDK 33; build TP1A.220624.014.A325MUBSADXJ2) Android build ID: TP1A.220624.014.A325MUBSADXJ2 Device brand: samsung Device manufacturer: samsung Device name: a32 (a32ub) Device model: SM-A325M WebView: Android System WebView 131.0.6778.104 MPV version: 4d32db2 Libplacebo version: v7.349.0 FFmpeg version: n7.0

### Android version

Android 13

### Other details

![Screenshot_20241208_130146_Aniyomi](https://github.com/user-attachments/assets/adc14299-b743-4ece-9fcc-aa097e745d97)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
See closed #6385

In general, WebView is used to check if there's issues (to check between the source & extension), so if the extension works, you don't need to care about WebView. This might be intended/how it is for the extension to function/how the site is responding back. I'll let someone more knowledgeable close this one out in case it is unintended/adjustable.

**Comment by drysius** [comment]
> See closed #6385
> 
> In general, WebView is used to check if there's issues (to check between the source & extension), so if the extension works, you don't need to care about WebView. This might be intended/how it is for the extension to function/how the site is responding back. I'll let someone more knowledgeable close this one out in case it is unintended/adjustable.

Thanks sir :3
