### ISSUE TITLE
EXTENSION ISSUE: Some Bato.to chapters and covers are not loading

### ISSUE THREAD

**Issue by Hatdog28** [keiyoushi/tachiyomi-extensions-source#6536]
### Source information

Bato

### Source language

English

### Steps to reproduce

1. I experienced the same thing from the Mihon app and tried to download the Yokai app, which also worked on my phone.
2. The issue is that some Bato.to chapters and covers are not loading. It always says "retry" or "open in webview."
3. It only loads on the Chrome browser.
4. I tried changing the user agent and clearing cookies and cache, but nothing worked. 
5. One time, I even tried to open it on the app itself, and it said something about the "scheme". I have forgotten the exact phrase, though, since I'm not techy. 

![Screenshot_20241209-091412](https://github.com/user-attachments/assets/0ebb6222-e7cb-4f1d-a688-8e7a409b950f)
![Screenshot_20241209-091418](https://github.com/user-attachments/assets/b598dcc9-eeb3-43bd-b055-1a8f1ed1cd29)
![Screenshot_20241209-091431](https://github.com/user-attachments/assets/b1999604-afcf-425d-8cbe-2193b08bcf22)
![Screenshot_20241209-091451](https://github.com/user-attachments/assets/66bc9615-9d70-4e51-857f-0e3651f395a7)
![Screenshot_20241209-091512](https://github.com/user-attachments/assets/ed6bd131-4e22-49bb-bf00-cd5fb90e4fe0)

### Expected behavior

I expected the covers and chapters to load but to no avail. 

### Actual behavior

I think it has a problem with the extension. It worked before but suddenly it happened 3 days ago. 

### Mihon/Tachiyomi version

Yokai 1.8.5.13

### Android version

Android 11

### Other details

Please get back to me sooner. Thank you! 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
Loads up fine on my end. Do you have DNS over HTTPS enabled in your app settings? Adjust or disable it (remember to restart), maybe also give "Clear chapter cache" in app's Settings > Data and storage, and see if that helps.

![Screenshot_20241209_092721_Mihon.png](https://github.com/user-attachments/assets/7c998d51-7ea2-4e33-a9e2-09c17d4a9ac9)

**Comment by Hatdog28** [comment]
My DNS over HTTPS was disabled. I tried changing it into Cloudfare and restarted my device but it still didn't work. I tried disabling it and restarted my device again but it still didn't work. I also tried clearing the chapter's cache but it didn't work.

**Comment by Smol-Ame** [comment]
I meant to restart the app. Maybe try changing the mirror URL in the Bato extension settings (remember to restart the app after changing it), otherwise I got nothing else off the top of my head.

Maybe switch networks, use a VPN, or check your router settings to see if it's blocking something?

**Comment by Hatdog28** [comment]
Thank you! It has only worked when I downloaded a vpn. The mirror URL did not worked though.
