### ISSUE TITLE
Snow Machine Translations Graphics issue

### ISSUE THREAD

**Issue by Deep-web08** [keiyoushi/tachiyomi-extensions-source#6539]
### Source name

Snow Machine translations

### Source language

English

### Source link

https://snowmtl.ru

### Other details

![WhatsApp Image 2024-12-08 at 11 28 48 PM](https://github.com/user-attachments/assets/dd22c4ae-84be-4c3a-9a39-459035f2cfa2)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by MikeZeDev** [comment]
I think the "source is down" label is meant for website that doesnt respond, its invalid here, perhaps you should remove it?

**Comment by Smol-Ame** [comment]
Site was down when the issue was made (I checked during then), seems like it's back up & I don't see any apparent issues currently. Closing as non-issue
