### ISSUE TITLE
Mangageko extension 

### ISSUE THREAD

**Issue by lxymix** [keiyoushi/tachiyomi-extensions-source#654]
### Source information

Mangageko 1.4.21

### Source language

English

### Steps to reproduce

1.I cannot install it 

### Expected behavior

Should be installed 

### Actual behavior

Cannot install 

### Tachiyomi version

0.15.3

### Android version

10

### Other details

I already tried the trouble shooting this:

Extension installation issues
Encountering problems while trying to install or update extensions? Follow these steps:

Try restarting the app. There is a known bug where the app doesn't recognize newly-updated extensions.
If the first step doesn't work, install Split APK Installer from the Google Play Store and install your .apk from there.
Split APK Installer helps show better error messages or may even successfully install your .apk without issue.

While installing the extension this message shows even when I don't even have the extension installed also my safe/secure folder is empty so and I already uninstall the old version I uninstall it in my device settings 

INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package eu.kanade.tachiyomi signatures do not match the previously installed version; ignoring!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by lxymix** [comment]
I already uninstalled the old version it but it won't install the new version

**Comment by lxymix** [comment]
![Uploading Screenshot_20240126-132938.png…]()

**Comment by lxymix** [comment]
![Screenshot_20240126-132709](https://github.com/keiyoushi/extensions-source/assets/155837366/767880dc-c035-4278-8888-ec39d591eccb)

**Comment by Smol-Ame** [comment]
Try restarting your phone

**Comment by lxymix** [comment]
> Try restarting your phone

Didn't work

**Comment by Smol-Ame** [comment]
I don't think any other troubleshooting/any other steps can be done, especially since you got the error earlier about it being a different signature compared to the other version.

I would double-check any secure/safe folder to see if it's installed there, or check the in-app extension list (normal & secure/safe folder version) to see if it's visible.

**Comment by lxymix** [comment]
> I don't think any other troubleshooting/any other steps can be done, especially since you got the error earlier about it being a different signature compared to the other version.
> 
> I would double-check any secure/safe folder to see if it's installed there, or check the in-app extension list (normal & secure/safe folder version) to see if it's visible.

Hello I think the extension it self is the problem because I tried it in another devices that doesn't have any extension or tachiyomi installed and I download the tachiyomi in that device and add the extensions and tried to install the (extension mangageko) in the app it didn't work and I installed the (mangageko.apk) in the keiyoushi extensions and I used sai to install the apk and this shows up (This is usually caused your previous extension having a different signature from the updated extension, making Android refuse to update it.) Even if there's no extension installed

**Comment by beer-psi** [comment]
> > I don't think any other troubleshooting/any other steps can be done, especially since you got the error earlier about it being a different signature compared to the other version.
> > I would double-check any secure/safe folder to see if it's installed there, or check the in-app extension list (normal & secure/safe folder version) to see if it's visible.
> 
> Hello I think the extension it self is the problem because I tried it in another devices that doesn't have any extension or tachiyomi installed and I download the tachiyomi in that device and add the extensions and tried to install the (extension mangageko) in the app it didn't work and I installed the (mangageko.apk) in the keiyoushi extensions and I used sai to install the apk and this shows up (This is usually caused your previous extension having a different signature from the updated extension, making Android refuse to update it.) Even if there's no extension installed

If Split APK Installer fails with the code `INSTALL_FAILED_UPDATE_INCOMPATIBLE`, that means a previous version of the extension is on the device somewhere.

**Comment by lxymix** [comment]
Uploading XRecorder_Edited_26012024_145834.mp4…

**Comment by lxymix** [comment]
Uploading XRecorder_Edited_26012024_145834.mp4…

**Comment by lxymix** [comment]
Uploading XRecorder_Edited_26012024_145834.mp4…

**Comment by lxymix** [comment]
Ok, thank you for your help.
