### ISSUE TITLE
Happymh  can't refresh to catch the latest episodes, and  can't read the comics 

### ISSUE THREAD

**Issue by somebodyxdd** [keiyoushi/tachiyomi-extensions-source#6540]
### Source information

Happymh 1.4.14

### Source language

Chinese

### Steps to reproduce

Open the comic book added to the shelf and pull down to refresh the chapter. At this time, "No chapter" will be displayed and click on the chapter to watch, and no picture can be obtained

### Expected behavior

Get the latest chapters normally, and can read comics

### Actual behavior

Can't get the latest chapters properly, can't read comics

### Mihon/Tachiyomi version

0.16.2

### Android version

Android12/Harmonyos 3.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Rstoroniomi** [comment]
我也看不了，點開漫畫根本沒有章節

**Comment by Nevermind425** [comment]
Well I got the same problem ,but it also tell me can't bypass the cloudflare 
![Screenshot_20241211_004241_Mihon](https://github.com/user-attachments/assets/bf8ae217-5ea7-4173-b578-e3c474c5542c)

**Comment by Nevermind425** [comment]
I don't even know why it happened cause I still can watch this in webview

**Comment by lwluo123** [comment]
你们能看吗，我更新了插件还是看不了
![20241213093519](https://github.com/user-attachments/assets/42c3cefd-cee5-4f16-9b90-80041a90b7cb)
