### ISSUE TITLE
Myreadingmanga extension not working. 

### ISSUE THREAD

**Issue by BangtanExo27** [keiyoushi/tachiyomi-extensions-source#6544]
### Source information

Myreadingmanga version 1.4.53

### Source language

English

### Steps to reproduce

Go into the extention and it says failed to bypass cloudfare, so click on webview, says "not found". The site is working when you use browser so there shouldn't be any problem.

### Expected behavior

It should be loading normally, I thought it would be fixed or reported by now but it's been about a month already.

### Actual behavior

Failing to load. Cloudfare bypass problems, when using webview it's reporting "not found" 

![Screenshot_20241209_165322_app mihon](https://github.com/user-attachments/assets/4c82ea91-7a1b-4931-8cbc-9dbd6b6001c7)
![Screenshot_20241209_165327_app mihon](https://github.com/user-attachments/assets/9d84978d-0b69-41e2-8d41-7441c7daed5c)

### Mihon/Tachiyomi version

Mihon App version: 0.17.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
Duplicate of #5675

It's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

**Comment by BangtanExo27** [comment]
I searched for it, but couldn't find it that's why I made a new one, how am I supposed to know with so many issues being out up everyday.

**Comment by Smol-Ame** [comment]
It's right there. And the first thing you see when searching since GitHub defaults to Open issues.

Also: " I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open or closed issue."

![Screenshot_20241209_231234_GitHub.png](https://github.com/user-attachments/assets/158d63cb-4a06-41e7-b84a-9cbdd7edbd17)

**Comment by BangtanExo27** [comment]
Sorry about that, considering it's an ongoing issue I didn't look through the closed section, my bad, just trying to find a solution.
