### ISSUE TITLE
MangaGeko no longer working | Pages no longer load

### ISSUE THREAD

**Issue by Fadwadwa089** [keiyoushi/tachiyomi-extensions-source#6552]
### Source information

MangaGeko 1.4.25

### Source language

English

### Steps to reproduce

1. Select any manga
2. Select any chapter
3. Chapter will not load, shows "Image couldn't be loaded"
4. Even in webview, chapters will not load, but if accessed from browser application (i.e. Google Chrome), chapters do load

### Expected behavior

Chapters should load

### Actual behavior

Chapters not loading, shows "Image couldn't be loaded"

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Fadwadwa089** [comment]
Nvm, it seems to be an issue with ISP. Since it does not work on tachiyomi app, both in-app and webview, but it works in separate browser app, the ISP might have an issue with how the tachiyomi app queries data from mangageko site as opposed to how a traditional browser app queries data from mangageko.

**Comment by Smol-Ame** [comment]
Then close it out if it's your own personal internet-related issue.

Only thing app-wise would be DNS over HTTPS in your Tachi/Mihon app's Settings > Advanced. Remember to restart the app after adjusting that setting. Come to the Keiyoushi Discord repo-support channel for help or basic troubleshooting.
