### ISSUE TITLE
Manhwa18 issue "SocketException: Connection Reset"

### ISSUE THREAD

**Issue by SaltySardines14** [keiyoushi/tachiyomi-extensions-source#6554]
### Source information

Manhwa18.cc

### Source language

Multi/English

### Steps to reproduce

1. Open the "Manhwa18.cc" extension 

### Expected behavior

should have work just fine

### Actual behavior

can't get the extension to load

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 11

### Other details

it works perfectly before but for the past few days it just doesn't. It's a hassle to migrate to other source because this is better than most 18+ extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AwkwardPeak7** [comment]
try vpn
