### ISSUE TITLE
SchaleNetwork - repo not available?

### ISSUE THREAD

**Issue by Sundogg17** [keiyoushi/tachiyomi-extensions-source#6555]
### Source information

1.4.9

### Source language

English

### Steps to reproduce

Web view works fine, but just in app it doesnt

### Expected behavior

To view, read and add to library 

### Actual behavior

Only web view works.

### Mihon/Tachiyomi version

Tachij2k 1.74 

### Android version

14

### Other details

Maybe it's don't know how to make it work right? I keep seeing closed tickets from past, but I still error 400, so maybe it's difficult then last time?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
1. Extension, not repo. Keiyoushi is the repo that has all the extensions available for you to use.
2. You're on an old version that has been replaced, uninstall SchaleNetwork & reinstall it.
3. Join the Keiyoushi Discord server & read the status-updates channel for these important notices, and ask for basic help/troubleshooting in the repo-support channel.
