### ISSUE TITLE
TuMangaOnline/LectorManga have changed their URL

### ISSUE THREAD

**Issue by miguel-catuche** [keiyoushi/tachiyomi-extensions-source#6556]
### Source information

TuMangaOnline/LectorManga 1.4.4

### Source language

Spanish

### Source new URL

https://zonatmo.com/

### Other details

This problem have like 2 months since it started, I supposed it to be just a Mihon bug and I though when the new version released it will be fixed, but today I installed the new version and I still can't read any manga, when you tap on a chapter of whatever manga it try to load, then it just stop loading and the app restarts, then I figured out it's an URL extension issue, cause I opened the webview and then realized there's no chapters to read and the URL doesn't matched with the official web version of the extension (I was reading mangas on the browser in the same manga extension). Thats all I have got to say, I hope it will be fixed soon, thank you.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by miguel-catuche** [comment]
TuMangaOnline have indeed the https://zonatmo.com/ URL but this extension has two "extensions" on it, LectorManga doesn't have the https://zonatmo.com/ URL.

**Comment by Smol-Ame** [comment]
Rewrote:

LectorManga has its own domain/website, and doesn't redirect anywhere else.

And as for LectorManga, try passing Cloudflare in WebView (and click around to see if there's extra verification needed)

Also this in Keiyoushi Discord status-updates channel:

![Screenshot_20241210_151857.png](https://github.com/user-attachments/assets/0d2a517d-f363-481d-a695-61b0f4676982)
