### ISSUE TITLE
Koharu: HTTP 400

### ISSUE THREAD

**Issue by kyoyacchi** [keiyoushi/tachiyomi-extensions-source#6558]
### Source information

1.4.11

### Source language

English

### Steps to reproduce

Try using SchaleNetwork, it won't work.

### Expected behavior

It should work.

### Actual behavior

![Screenshot_20241210-112654](https://github.com/user-attachments/assets/2261df96-278e-4b5e-83b3-48c618bfd76a)

### Mihon/Tachiyomi version

1.12.1

### Android version

Android 11

### Other details

https://github.com/keiyoushi/extensions-source/issues/6053 - https://github.com/keiyoushi/extensions-source/pull/6072, it seems that issue has been fixed but it's here again.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
Worked fine for me, did you check WebView?

Maybe you need to actually open WebView so it redirects to a working mirror, and then retry loading the source's Browse (Popular/Latest tab)

**Comment by kyoyacchi** [comment]
> Worked fine for me, did you check WebView?
> 
> Maybe you need to actually open WebView so it redirects to a working mirror, and then retry loading the source's Browse (Popular/Latest tab)

Yeah, it just worked again. It was temp i guess.
