### ISSUE TITLE
Adicione essa scan por favor ela tem várias obras boas 

### ISSUE THREAD

**Issue by Emanoluh** [keiyoushi/tachiyomi-extensions-source#6559]
### Source name

Reaper Scans 

### Source link

reaperscans.com

### Source language

PORTUGUÊS Brasileiro 

### Other details

Ela só tá disponível em inglês a em português taça disponível mas não sei o que aconteceu que ela diz apareceu depois de uma atualização! 

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
There's only 2 English Reaper Scans and 1 French Reaper Scans extension

Enable English or French in your Sources tab & Extensions tab, and also compare the extension version numbers to your own (if it's installed for you)

![Screenshot_20241210_170518_Mihon.png](https://github.com/user-attachments/assets/67737ae3-f6e3-40e3-a132-e8c3bda9897b)
