### ISSUE TITLE
Baozi Manhua Error Connection Reset

### ISSUE THREAD

**Issue by Padahjj** [keiyoushi/tachiyomi-extensions-source#6569]
### Source information

Baozi Manhua 1.4.22

### Source language

Chinese - 中文

### Steps to reproduce

1. Open the extension 
2. Open a work
3. Wait for it to load 

### Expected behavior

The chapter should open.

### Actual behavior

The chapter closes by itself and the error "connection reset" appears.

![20241211_012133](https://github.com/user-attachments/assets/e9836743-23de-4b3c-aab5-387c92b0f2bd)

### Mihon/Tachiyomi version

TachiyomiSY 1.11.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
Usually a personal internet-related issue, check WebView or in your own browser for errors, otherwise switch networks, use a VPN, and/or adjust DNS over HTTPS in your app's Settings > Advanced (remember to restart the app), if needed.

Come to the Keiyoushi Discord repo-support channel for any other questions about this, or basic troubleshooting.
