### ISSUE TITLE
Bato.to timeout

### ISSUE THREAD

**Issue by xdeiimoss** [keiyoushi/tachiyomi-extensions-source#6574]
### Source name

Batoto 1.4.42

### Source language

Multi

### Describe your suggested feature

I've been receiving timeouts from batoto. can rate limit be increased or maybe add a new configuration to change rate limit like some other extensions?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by xdeiimoss** [comment]
actually could this be an issue happening in the site instead of me causing a timeout? I've seen a bunch of people saying that their  site is running really slow on their discord server
for reference, I have 2163 entries from batoto and they have all updated overnight

**Comment by AwkwardPeak7** [comment]
most likely an issue with bato recently
