### ISSUE TITLE
Unable to read manhwa from lura toons source

### ISSUE THREAD

**Issue by Werique69** [keiyoushi/tachiyomi-extensions-source#6591]
### Source information

1.4.56

### Source language

PT-BR 

### Steps to reproduce

Erro 404

### Expected behavior

![Uploading Screenshot_20241212-115628.png…]()

### Actual behavior

![Screenshot_20241212-114655](https://github.com/user-attachments/assets/704ce9ce-75a0-4220-a584-a32dab78d675)

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
1. Duplicate of #6468, it's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.
2. For future reference, have some patience & make sure your uploaded images are fully uploaded before hitting submit. Again, future reference.
