### ISSUE TITLE
Cant install Webtoon Extension 

### ISSUE THREAD

**Issue by nottotallyLen** [keiyoushi/tachiyomi-extensions-source#6596]
### Source information

webtoons.com 1.4.41

### Source language

English

### Steps to reproduce

First. Im trying to install the source which is Webtoon by clicking the download

second. after downloading, I tried to install it however it keep saying "**app not installed**" even though my storage space is 25 gb

Third. it's still in the dl file but i cannot install it

### Expected behavior

after downloading the source, i should be able to install it and have it on my mihon app

### Actual behavior

however, I cannot install it. I tried it many times but still it keep saying "app not installed"

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
Come to the Keiyoushi Discord repo-support channel for help/basic troubleshooting with this
