### ISSUE TITLE
API Domain setting in LibGroup (RU)

### ISSUE THREAD

**Issue by NoPlagiarism** [keiyoushi/tachiyomi-extensions-source#6601]
### Source name

MangaLib, SlashLib (YaoiLib), HentaiLib

### Source language

Russian

### Describe your suggested feature

As mentioned in #6069 and [here](https://lib.social/forum/discussion/580104). There are some CF problems. 

To fix it there are multiple API mirrors. I suggest to add option to change API domain in extension settings

### Other details

Example domains (haven't tested  'em all yet):

- api.lib.social
- api2.mangalib.me
- api.imglib.info

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Norsze** [comment]
You made the issue now be quiet, and don't bother contributors

**Comment by e-shl** [comment]
> * api.lib.social

This from tachi and web

> * api.imglib.info

This from official app

> * api2.mangalib.me

Where this domain come from?

**Comment by NoPlagiarism** [comment]
> >  api2.mangalib.me
>
> Where this domain come from?

It is now in use on mangalib.me
