### ISSUE TITLE
Sign in to asura scans for subscription

### ISSUE THREAD

**Issue by KairuDeibisu** [keiyoushi/tachiyomi-extensions-source#6602]
### Source name

Asura Scans

### Source language

English

### Describe your suggested feature

The ability to sign in to our subscription for asura scans. 

### Other details

Extension name: Asura Scans (lang: en; package: eu.kanade.tachiyomi.extension.en.asurascans)
Extension version: 1.4.42 (lib: 1.4; version code: 42)
NSFW: false

Update available: false
Obsolete: false
Shared: true
Repository: https://raw.githubusercontent.com/keiyoushi/extensions/repo

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kalwadi** [comment]
There should be no need to do any modifications for this. Just open the webview from AsuraScans extension and login
(this process worked for logging into my kavita server trough extension if I remember correctly, can't test for asura because update broke extension)

**Comment by KairuDeibisu** [comment]
Did not know it worked like that.

**Comment by unCutlass** [comment]
The extension updated and now working

**Comment by Smol-Ame** [comment]
Closing in favor of #6614

As mentioned before, sign into your Asura account through WebView, then you should be able to view whatever paid content you have access to.
