### ISSUE TITLE
Asura broken

### ISSUE THREAD

**Issue by KairuDeibisu** [keiyoushi/tachiyomi-extensions-source#6603]
### Source information

Asura Scans

### Source language

English

### Steps to reproduce

Try to open any chapter with the latest version of the extension.

### Expected behavior

The chapter should open.

### Actual behavior

A null error.

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 14

### Other details

They just added a subscription option and it's possible this update has caused some issues.

App version: 0.17.1 (standard, 3a100c7, 9, 2024-12-06T17:14:05Z)
Android version: 14 (SDK 34; build UP1A.231005.007.F936USQU7GXK9)
Device brand: samsung
Device manufacturer: samsung
Device name: q4q (q4qsqw)
Device model: SM-F936U
WebView: Android System WebView 131.0.6778.104

Extension name: Asura Scans (lang: en; package: eu.kanade.tachiyomi.extension.en.asurascans)
Extension version: 1.4.42 (lib: 1.4; version code: 42)
NSFW: false

Update available: false
Obsolete: false
Shared: true
Repository: https://raw.githubusercontent.com/keiyoushi/extensions/repo

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bauripalash** [comment]
I am facing the same issue 

App version: 0.17.1-7031 (standard, be37f214d, 9, 2024-12-07T21:20:49Z)
Android version: 14 (SDK 34; build UP1A.231005.007.A346EXXS8CXIA)
Device brand: samsung
Device manufacturer: samsung
Device name: a34x (a34xdxx)
Device model: SM-A346E
WebView: Android System WebView 132.0.6834.33

**Comment by Ashu0269** [comment]
Yeah I also faceing the same issue

**Comment by Smol-Ame** [comment]
You guys don't need to confirm, this is literally the issue request about the shitty source issue. Give it a thumbs up reaction, otherwise, don't comment unnecessarily since it emails everyone involved & pings the Discord server channel.

**Comment by lcd047** [comment]
Sadly, paid chapters are not handled properly, see f.i. "Overpowered Sword" chapter 126:

https://asuracomic.net/series/overpowered-sword-4d8db79f

Please reopen.
