### ISSUE TITLE
The chapters aren't downloading because they're not bypassing cloudflare.

### ISSUE THREAD

**Issue by Oleksandrigo** [keiyoushi/tachiyomi-extensions-source#6606]
### Source information

HentaiLib 1.4.51

### Source language

Russian

### Steps to reproduce

1. Open any title
2. Press t odownlaod button
3. Profit

### Expected behavior

The chapters should be downloadable

### Actual behavior

The chapters aren't downloading

### Mihon/Tachiyomi version

SY 1.11.0

### Android version

Android 11

### Other details

not bypass cloudflare
![image](https://github.com/user-attachments/assets/35f7af08-fb64-4579-85f8-e8d7824e2648)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
Did you pass Cloudflare verification in WebView?

Eh, regardless, duplicate/part of #6601 or see the following bot message:

**Comment by Smol-Ame** [comment]
?blurb cf
