### ISSUE TITLE
Infernal Void Scan not working

### ISSUE THREAD

**Issue by Ubada03** [keiyoushi/tachiyomi-extensions-source#6612]
### Source information

Infernal Void Scans 1.4.40

### Source language

English

### Steps to reproduce

1. Open extension
2. No results found
![Screenshot_2024-12-15-01-36-17-23_551f7f0ca926862b368845ce7ee433aa](https://github.com/user-attachments/assets/0615b6b1-16f1-49ad-8d96-d734f453c2f1)

### Expected behavior

1. Open extension 
2. Series shown

### Actual behavior

No series shown

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bapeey** [comment]
Theme changed to `Iken`
