### ISSUE TITLE
Hide Locked Chapter in Asura 

### ISSUE THREAD

**Issue by prem-k-r** [keiyoushi/tachiyomi-extensions-source#6614]
### Source name

Asura Scans

### Source language

English

### Describe your suggested feature

![IMG_20241215_032018](https://github.com/user-attachments/assets/054c2c47-3df9-4fe5-85da-10798bc1d764)
![IMG_20241215_032037](https://github.com/user-attachments/assets/15f80a33-3c9e-4529-a8c2-02ab4f557b57)
Asura has introduced a subscription model.
Some of the latest chapters are locked, they unlock in ~6 hr after release. 

So, please add a toggle option to hide those paid/locked chapters.
![IMG_20241215_113129](https://github.com/user-attachments/assets/09fb3a1d-19e5-4583-b4c0-a208c9d35a21)
P.S.: Login with username/password is not part of this request, there is a separate issue for that.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by unCutlass** [comment]
Duplicated request  https://github.com/keiyoushi/extensions-source/issues/6602

**Comment by asdkant** [comment]
> Duplicated request  https://github.com/keiyoushi/extensions-source/issues/6602

No it isn't, #6602 requested support for reading the premium chapters, this one is to hide them if not logged in
