### ISSUE TITLE
Crystal Comics (PT-BR Source) don't show content.

### ISSUE THREAD

**Issue by AnonymousPtBr** [keiyoushi/tachiyomi-extensions-source#6615]
### Source information

CrystalComics 1.4.38

### Source language

Portuguese Brazilian 

### Steps to reproduce

Don't show content.
![Screenshot_2024-12-14-19-39-24-196_app mihon debug](https://github.com/user-attachments/assets/a2c0323b-c7be-4853-b9f4-28ac2b5c2116)

### Expected behavior

Show content.

### Actual behavior

Don't show content.

### Mihon/Tachiyomi version

0.17.31

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by choppeh** [comment]
what's the comic and the chapter?

I couldn't reproduce this issue

**Comment by AnonymousPtBr** [comment]
> what's the comic and the chapter?
> 
> I couldn't reproduce this issue

Olhei agora, voltou ao normal sozinha, acho!
