### ISSUE TITLE
Remanga - Field 'page' is required for type with name '...'

### ISSUE THREAD

**Issue by BlackYuzia** [keiyoushi/tachiyomi-extensions-source#662]
### Source information

Remanga 1.4.83

### Source language

~~ukrlan~~ rus-lan

### Steps to reproduce

1. Open app
2. Open any manga by remanga extension
3. Try read any chapter
4. Get `Field 'page' is required for type with name ...` error

### Expected behavior

Chapter of manga successfuly open

### Actual behavior

Getting error `Field 'page' is required for type with name ...`

### Tachiyomi version

0.15.3

### Android version

Android 11

### Other details

Suppose, website change API a bit? Hope it could be fixed by editing a few lines of code.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
fixed in #410
