### ISSUE TITLE
An extension is unable to access wepview

### ISSUE THREAD

**Issue by Willian00175** [keiyoushi/tachiyomi-extensions-source#6622]
### Source information

SlimeRead 1.4.15

### Source language

Brazilian Portuguese

### Steps to reproduce

First step: go to the browse tab Second step: Select the extension in sources third step: press the three dots and select "open wepview"

### Expected behavior

Access the extension's webview (in this case SlimeRead)

### Actual behavior

![Screenshot_20241215-052515](https://github.com/user-attachments/assets/d4b100ef-252e-4946-b47a-12e061f8df1d)

### Mihon/Tachiyomi version

App version: 0.17.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
See comments in duplicate & closed #6535, I'm not writing an explanation again

If you are having an issue with the extension, make it clear
