### ISSUE TITLE
Revert Filter Menu

### ISSUE THREAD

**Issue by LostFl0ptrop1can** [keiyoushi/tachiyomi-extensions-source#6625]
### Source information

E-Hentai

### Source language

"English" "Multi"

### Steps to reproduce

The Filter Menu won't work. The Filter won't work if the tag has spaces and won't work if there's two tags or more

### Expected behavior

If I put {-furry, males only} in Male Tags Box, it should give me filtered content
If I put {males only} in Male it should give me filtered content 

### Actual behavior

If I put {-furry, males only} in Male Tags Box, it would give me "no result found."
If I put { males only} in Male Tags Box,  it would give me "no result found."

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 11

### Other details

Please revert back to old filter menu with drop-down checkboxes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Norsze** [comment]
Refer to this: https://github.com/keiyoushi/extensions-source/issues/5887#issuecomment-2456355138
