### ISSUE TITLE
Tsuki-mangas: Pages are in wrong order

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#663]
### Source information

Tsuki mangás 1.4.1

### Source language

Português (Brasil)

### Steps to reproduce

A páginas tão em ordem errada

### Expected behavior

.

### Actual behavior

.

### Tachiyomi version

0.15.3

### Android version

Android 11

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
Could you provide examples of manga & chapters where this bug happens?

**Comment by ghost** [comment]
![Screenshot_20240127-115126](https://github.com/keiyoushi/extensions-source/assets/157044539/74ea8205-6c94-4a9e-8f52-79b583efab96)

![Screenshot_20240127-115133](https://github.com/keiyoushi/extensions-source/assets/157044539/ed84dbc1-acb8-418a-bf83-fc6a52161fe2)

![Screenshot_20240127-115156](https://github.com/keiyoushi/extensions-source/assets/157044539/6e931d26-7a39-482a-a953-3863b0a1c79e)

Está em em ordem

**Comment by beer-psi** [comment]
What manhua is that?

**Comment by Claudemirovsky** [comment]
❌ 🧠

**Comment by ghost** [comment]
![Screenshot_20240127-135044](https://github.com/keiyoushi/extensions-source/assets/157044539/311d3a97-8583-4f9a-acdb-1a8961505b74)
