### ISSUE TITLE
Add mahou scan source

### ISSUE THREAD

**Issue by Werique69** [keiyoushi/tachiyomi-extensions-source#6630]
### Source name

Mahou Scan

### Source link

https://mahouscan.com/

### Source language

Português PT-BR 

### Other details

![Screenshot_20241215-204951](https://github.com/user-attachments/assets/38f2209c-9cb3-489f-ae34-eae9549f20c4)
![Screenshot_20241215-205027](https://github.com/user-attachments/assets/9d2beb64-ea02-43e0-b177-cee5d5a25548)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment]
Site is just returning 404 for me. I assume this is geoblocking related.
