### ISSUE TITLE
Http 403 check website in webview for YakshaScans

### ISSUE THREAD

**Issue by Jalt3r** [keiyoushi/tachiyomi-extensions-source#6634]
### Source information

YakshaScans 1.4.37

### Source language

English

### Steps to reproduce

1. Click series I want to read, and click chapter>Get 403 error
2. Pull down to reload, doesnt update for new chapters>get 403
3. Click webview, loads fine, no captcha and chapters work fine
4. Click source>403, but webview works

![Screenshot_20241215_234851_TachiyomiSY](https://github.com/user-attachments/assets/0a2a8597-2ef2-40bf-81c6-7d591596d157)
![Screenshot_20241215_234913_TachiyomiSY](https://github.com/user-attachments/assets/0f73a96d-4741-4458-9e10-252a57f31d4c)
![Screenshot_20241215_234937_TachiyomiSY](https://github.com/user-attachments/assets/34b0f730-48bd-4ac2-bba9-e9a9ebf94b8b)

### Expected behavior

Clicking chapter should load the chapter to read or reloading a chapter for new chapters should show the new chapters

### Actual behavior

403 error upon clicking & updating chapters, also doesn't show new chapters.

### Mihon/Tachiyomi version

TachiyomiSY 1.11.0

### Android version

Android 14

### Other details

I do have mihon downloaded and updated to 0.17.1 and it's the same issue, I use SY as my main though.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment]
Javascript challenge - there is a similar implementation for AscalonScans (see `jsChallengeInterceptor`). This info is intended for other contributors.
