### ISSUE TITLE
Mikoroku change web

### ISSUE THREAD

**Issue by twelve1307** [keiyoushi/tachiyomi-extensions-source#6636]
### Source information

Mikoroku 1.4.10

### Source language

Indonesia 

### Source new URL

https://www.mikoroku.com

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment]
Did they announce the domain change somewhere? The old domain does not redirect to the new domain.

**Comment by twelve1307** [comment]
> Did they announce the domain change somewhere? The old domain does not redirect to the new domain.

Previous web deleted, now replaced to new one

**Comment by Ednahoshizora** [comment]
The extension has been updated from the previous version but still uses the old URL, which has not been changed to https://www.mikoroku.com

**Comment by Norsze** [comment]
Yes, that is why it's still an open issue @Ednahoshizora

**Comment by Unknown6946** [comment]
There are still no updates until now, really disappointed.

**Comment by Unknown6946** [comment]
![Uploading Screenshot_2024-12-22-09-10-45-66.jpg…]()
