### ISSUE TITLE
Happymh update issue

### ISSUE THREAD

**Issue by BabyNurse020517** [keiyoushi/tachiyomi-extensions-source#6639]
### Source information

Happymh 1.4.15

### Source language

Chinese

### Steps to reproduce

1. when i update my library on another day.
2. yesterday unread episode will mark as read.

### Expected behavior

unread episode should be remain unread not mark as read or disappear

### Actual behavior

old unread episode mark as read. they just disappear.

### Mihon/Tachiyomi version

0.17.1

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment]
Does this happen for every manga or just a select few? In other extensions, this is usually an issue when the app is unable to determine the chapter number _and_ the chapter's URL changes. Please provide some examples to test with.

**Comment by alan0507** [comment]
> Does this happen for every manga or just a select few? In other extensions, this is usually an issue when the app is unable to determine the chapter number _and_ the chapter's URL changes. Please provide some examples to test with.

It happened for those Manga that I have  read a least one episode.After I refresh t

**Comment by alan0507** [comment]
> Does this happen for every manga or just a select few? In other extensions, this is usually an issue when the app is unable to determine the chapter number _and_ the chapter's URL changes. Please provide some examples to test with.

It happened for those Manga that I have  read a least one episode.After I refresh the episode not read will all mark as read.

**Comment by vetleledaal** [comment]
I tested with "魔技科的剑士与召唤魔王" Ch.1. After marking it as read and refreshing the chapter list it remains marked as read.

By "when i update my library on another day" do you mean you have to wait a day before refreshing the chapter list?

**Comment by alan0507** [comment]
> I tested with "魔技科的剑士与召唤魔王" Ch.1. After marking it as read and refreshing the chapter list it remains marked as read.
> 
> By "when i update my library on another day" do you mean you have to wait a day before refreshing the chapter list?

Maybe he means that he update the extension and then this happened.
It's hard to explain,sorry My English isn't very good.😅

**Comment by BabyNurse020517** [comment]
> Does this happen for every manga or just a select few? In other extensions, this is usually an issue when the app is unable to determine the chapter number _and_ the chapter's URL changes. Please provide some examples to test with.

yup it happen on every manga in this extension, bcz manga from cola extension do not have this problem

**Comment by BabyNurse020517** [comment]
> I tested with "魔技科的剑士与召唤魔王" Ch.1. After marking it as read and refreshing the chapter list it remains marked as read.
> 
> By "when i update my library on another day" do you mean you have to wait a day before refreshing the chapter list?

not like this for example maybe魔技科的剑士与召唤魔王 unread chapter 1 on yesterday, when i refresh on the next day, 魔技科的剑士与召唤魔王 chapter 1 will automatic mark as read, although i did not read it

**Comment by AlphaBoom** [comment]
The new version chapter url format is : mangaread/yIjM1ATMxATM=cTO1ATMzATMzUTM=cTOycTM2ATM2ATMwATMyUTMzUTMxETM2ATM3ATM1QTM4QTM
It seems that this URL is not a permanent link but rather a temporary one. 

I'm not quite sure how to handle this situation. I may need to create a dummy chapter url first, and then retrieve the real chapter url when requesting the Page list.

**Comment by BabyNurse020517** [comment]
> The new version chapter url format is : mangaread/yIjM1ATMxATM=cTO1ATMzATMzUTM=cTOycTM2ATM2ATMwATMyUTMzUTMxETM2ATM3ATM1QTM4QTM It seems that this URL is not a permanent link but rather a temporary one.
> 
> I'm not quite sure how to handle this situation. I may need to create a dummy chapter url first, and then retrieve the real chapter url when requesting the Page list.

thx a lot, from what you said i ald know that how hard i can be fix

**Comment by NeKoOuO** [comment]
I think I found the problem #6697

**Comment by BabyNurse020517** [comment]
> I think I found the problem #6697

any solution?

**Comment by Norsze** [comment]
These are unrelated issues
