### ISSUE TITLE
SamuraiScan HTTP 404 Error

### ISSUE THREAD

**Issue by Anurag69** [keiyoushi/tachiyomi-extensions-source#6643]
### Source information

"SamuraiScan 1.4.47

### Source language

Espanol

### Steps to reproduce

1. Open extension.
2. 404 error page appear
3. Open webview it works as expected.

### Expected behavior

User should be able to see the latest comics on homepage.

### Actual behavior

HTTP 404 error occurs.

### Mihon/Tachiyomi version

Mihon --> 0.17.1

### Android version

Android 14

### Other details

PFA screenshots for your reference.
![Screenshot_20241217_034606](https://github.com/user-attachments/assets/31ab1f59-9423-4e29-b2d4-4c66922916d8)
![Screenshot_20241217_034719](https://github.com/user-attachments/assets/fabf0f3c-57aa-4513-beb0-25faaabbbe42)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Anurag69** [comment]
Could anyone please pick this up.

**Comment by Smol-Ame** [comment]
@Anurag69 there's over 490~ issues in the repo, with most of them waiting longer than you have. All the work is done by contributors volunteering their time & efforts to fixing said issues. There's no guarantee or ETA for anything, wait patiently, migrate to a different source, fix it yourself, or find somewhere else that'll fix things at your request.
