### ISSUE TITLE
Hitomi missing field error

### ISSUE THREAD

**Issue by okseboku** [keiyoushi/tachiyomi-extensions-source#6659]
### Source information

Hitomi 1.4.33

### Source language

Multi

### Steps to reproduce

1. Open latest 
2. Open popular 

### Expected behavior

Expect the latest to load and there be no error when loading popular 

### Actual behavior

Can't load latest and get an error on popular 
![Screenshot_20241217_202204_Mihon](https://github.com/user-attachments/assets/b34a6028-0b36-4068-bb2e-1cfd2adc981a)
![Screenshot_20241217_200029_Mihon](https://github.com/user-attachments/assets/ddc66835-6a27-43fd-8939-3c23bb4dca2e)

### Mihon/Tachiyomi version

Mihon stable 0.17.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by farhanajn** [comment]
How to apply this because i'am still experiencing the same error thanks

**Comment by Smol-Ame** [comment]
@farhanajn there's nothing to apply. The issue request is currently open, with linked pull request that might fix this issue (pending review & approval into the Keiyoushi repo).

Wait patiently or migrate to a different source.

**Comment by Beananator** [comment]
Not too sure if its just me but hitomi works if you use its multi extention instead of the English one its the same thing but multi needs you to type english in the search bar
