### ISSUE TITLE
SlimeRead (PT-BR Source) Could not find API URL.

### ISSUE THREAD

**Issue by AnonymousPtBr** [keiyoushi/tachiyomi-extensions-source#6673]
### Source information

SlimeRead 1.4.15

### Source language

Portuguese Brazilian 

### Steps to reproduce

Appears the error Couldn't find API URL.

### Expected behavior

Don't appears the error Couldn't find API URL.

### Actual behavior

Appears the error Couldn't find API URL.

![Screenshot_2024-12-18-11-01-05-236_app mihon debug](https://github.com/user-attachments/assets/ead94e21-fa98-4802-91b9-8860faf13642)

### Mihon/Tachiyomi version

0.17.1-7033

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
Check the site in your own browser

**Comment by AnonymousPtBr** [comment]
> Check the site in your own browser

![Screenshot_2024-12-18-11-27-41-774_com android chrome](https://github.com/user-attachments/assets/b9e44d9e-66b6-417f-952a-387c0994af61)

**Comment by Smol-Ame** [comment]
Probably region-blocking/changing things up in the background then. Site says it's under maintenance on my end (USA, Japan, Indonesia, Mexico VPN), only loaded up when I jumped to Portugal & Brazil VPN.

![Screenshot_20241218_223236_Firefox Nightly.png](https://github.com/user-attachments/assets/2e2348a6-7217-4b1e-97f7-8e1998d28591)

**Comment by domflamingo2** [comment]
> Probably region-blocking/changing things up in the background then. Site says it's under maintenance on my end (USA, Japan, Indonesia, Mexico VPN), only loaded up when I jumped to Portugal & Brazil VPN.
> 
> ![Screenshot_20241218_223236_Firefox Nightly.png](https://private-user-images.githubusercontent.com/155411819/396965335-2e2348a6-7217-4b1e-97f7-8e1998d28591.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MzM1NTAsIm5iZiI6MTczNDUzMzI1MCwicGF0aCI6Ii8xNTU0MTE4MTkvMzk2OTY1MzM1LTJlMjM0OGE2LTcyMTctNGIxZS05N2Y3LThlMTk5OGQyODU5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQxNDQ3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTEyYmE3N2RkMWM3NzBhNzE1ZDM2NWY4NTFmMTBhNzgxNWQyMTQ4MThlNjE3ZTgzZDA5YTVjZGVmMDU3ODI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1L_xHstIssoD2DmsFiiytlgTCmUspzXQAvQB1DGuzlk)

![image](https://github.com/user-attachments/assets/e9121fb7-0eca-4337-a102-5aef3d6a2626)

There was a maintenance today and it was finished, probably API was changed again.

obs: although this maintenance was a correction of their database.

**Comment by matheus-giordani** [comment]
I have the same problem! The site works normally in the browser 
![Screenshot_20241219_110657_Chrome](https://github.com/user-attachments/assets/09fe2cd2-8c7e-4b03-8516-0b505b14d84a)

**Comment by npkiler** [comment]
![Screenshot_20241222_154805_Tachiyomi](https://github.com/user-attachments/assets/9d8bbff9-ef7b-4827-bed3-2662e479dbd7)
please fix this

**Comment by Smol-Ame** [comment]
@npkiler This is the issue request, no need to unnecessarily comment the same exact issue. Shut up & wait, migrate to a different source, or fix it yourself.

**Comment by ToshiroLv** [comment]
O mihon ainda vai atualizar o API URL do SlimeRead no app? Para o SlimeRead funcionar no mihon

**Comment by taypss** [comment]
Essa é a tela que aparece quando se abre na Webview. 
![Screenshot_2024-12-22-15-06-44-672_app mihon](https://github.com/user-attachments/assets/938eedf5-fdf8-4ad5-9079-27d755a6d3ec)
