### ISSUE TITLE
Slime red ERRO API

### ISSUE THREAD

**Issue by tgc-2024** [keiyoushi/tachiyomi-extensions-source#6688]
### Source information

Slimered 1.4.15

### Source language

Português (Brazil)

### Source new URL

https://slimeread.com/

### Other details

Está dando erro de API.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
1. Duplicate of #6673, it's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.
2. For future reference, it's not a domain change request if the base URL hasn't changed.

**Comment by tgc-2024** [comment]
> 1. Duplicado de [SlimeRead (fonte PT-BR) Não foi possível encontrar a URL da API. ](https://github.com/keiyoushi/extensions-source/issues/6673)[ #6673](https://github.com/keiyoushi/extensions-source/issues/6673) , já foi relatado antes. Pesquise os problemas existentes primeiro antes de abrir um novo, e reconheça que você fez isso quando claramente não fez.[](https://github.com/keiyoushi/extensions-source/issues/6673)
> 2. Para referência futura, não é uma solicitação de alteração de domínio se a URL base não tiver sido alterada.

Como posso arrumar???

**Comment by Smol-Ame** [comment]
@tgc-2024 (Google Translate) Eu já disse, já existe uma solicitação de edição aberta sobre o SlimeRead. Solicitação de problema aberto significa que não há solução. Não há nada que você possa fazer a não ser esperar.

Ao abrir uma solicitação de problema, antes de enviar, há confirmações que você precisa verificar. Um dos reconhecimentos é que você verificou os problemas existentes, tanto abertos quanto fechados, antes de abrir um novo, o que seu idiota não fez. Eu disse isso duas vezes e você ainda abriu outra solicitação de problema duplicado.

Se você não sabe ler, por que se preocupar em consertar a extensão?
