### ISSUE TITLE
Error in Hitomi

### ISSUE THREAD

**Issue by LeoneLDVA** [keiyoushi/tachiyomi-extensions-source#6690]
### Source information

Hitomi 1.4.33

### Source language

Spanish

### Steps to reproduce

__1. Open Hitomi
2. Select "Latest" and "Filter" and also the Hitomi search engine.

### Expected behavior

I was just hoping it would work as usual.

### Actual behavior

![Screenshot_20241219-002120_Mihon](https://github.com/user-attachments/assets/2a96c4ee-b71c-4746-a97c-e355e6003ce4)

### Mihon/Tachiyomi version

App version: 0.17.1

### Android version

Android 12

### Other details

_I_ already went to many pages looking for help.
I am hopeful that you can help me here.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
Duplicate of #6659

It's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

**Comment by LeoneLDVA** [comment]
> Duplicate of #6659
> 
> It's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

I don't understand that last one.
What is the name of the issues so I can go see it.
I just want to help.

**Comment by Smol-Ame** [comment]
The issue is #6659, as I wrote in the message. You can click on it to view the issue request.

If you had search just "Hitomi" in the Issues page before opening a new issue, like you're supposed to do & agreed that you did, you would've seen it.

![Screenshot_20241219_153441_GitHub.png](https://github.com/user-attachments/assets/888487e6-e660-4da2-a4d7-06263274c9cf)

![Screenshot_20241219_153606_GitHub.jpg](https://github.com/user-attachments/assets/7383921a-e659-4b93-a30f-00aeed9c85f3)

**Comment by LeoneLDVA** [comment]
> The issue is #6659, as I wrote in the message. You can click on it to view the issue request.
> 
> If you had search just "Hitomi" in the Issues page before opening a new issue, like you're supposed to do & agreed that you did, you would've seen it.
> 
> ![Screenshot_20241219_153441_GitHub.png](https://private-user-images.githubusercontent.com/155411819/397266824-888487e6-e660-4da2-a4d7-06263274c9cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTM3ODksIm5iZiI6MTczNDYxMzQ4OSwicGF0aCI6Ii8xNTU0MTE4MTkvMzk3MjY2ODI0LTg4ODQ4N2U2LWU2NjAtNGRhMi1hNGQ3LTA2MjYzMjc0YzljZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOVQxMzA0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmEwMmU3OTRkNmNlNDExNWU4YTNkZGE4MTcyNDQ0YTU5MTFiZTc2ZGMxNzM4NTcyNjU0YmM2MWQ2ODJlYmNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.w4YVj4y4EHFrngUEz9juJZLpMFO9W5MU1Ryzlw-hcwk)
> 
> ![Screenshot_20241219_153606_GitHub.jpg](https://private-user-images.githubusercontent.com/155411819/397267126-7383921a-e659-4b93-a30f-00aeed9c85f3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTM3ODksIm5iZiI6MTczNDYxMzQ4OSwicGF0aCI6Ii8xNTU0MTE4MTkvMzk3MjY3MTI2LTczODM5MjFhLWU2NTktNGI5My1hMzBmLTAwYWVlZDljODVmMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOVQxMzA0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYWEzYzMwY2UwMTEwZDY2ODE1MjAyMzhlM2Y4OGY2ZTFlYWRjNGJkYTZhNDU4Nzc1NzFhYzdkYmMzNmJmY2E5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.41TfNgjsEskM3ykj4Y7QVQH_zEhVO-PMrjIWewccsl4)

Thank you
