### ISSUE TITLE
Manga pro change the Website design

### ISSUE THREAD

**Issue by a7mad115** [keiyoushi/tachiyomi-extensions-source#6702]
### Source information

Manga Pro 1.4.33

### Source language

Arabic

### Steps to reproduce

Manga pro change the Website design and resulted in this :
1- Open the extension from (Brawse) then (Sources).
2- you will get the massege "No results found".
![Screenshot 2024-12-20 025742](https://github.com/user-attachments/assets/a29a5194-a349-4b02-83f3-a94e3b981749)

### Expected behavior

Too see the results.

### Actual behavior

You will get the massege "No results found".

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mohamed1406** [comment]
Source new URL
https://promanga.pro/home

And when you open a page of a manga it was like : https://promanga.pro/manga/*/**
Now after the website update it became like that: https://promanga.pro/series/*/**
