### ISSUE TITLE
Mangago Loading Issue

### ISSUE THREAD

**Issue by saeiahz** [keiyoushi/tachiyomi-extensions-source#6707]
### Source information

Mangago

### Source language

English

### Steps to reproduce

1. When I tried using the extension to read episodes it just keeps on loading/doesn't work
2. It keeps on saying failed to connect and I tried restarting my phone and wifi to see if it will help but nope.
![Screenshot_2024-12-20-14-14-41-110_app mihon](https://github.com/user-attachments/assets/d9d9a155-fb13-44e6-b5d3-2441243f14af)
3. I tried doing the guide from the troubleshoot thingy but didn't help.

### Expected behavior

When clicking a chapter/episode it should load perfectly fine

### Actual behavior

Continuous loading happens and says "failed to connect"

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 13

### Other details

It only happens to this extension, the rest works perfectly fine and loads when you read it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
"Failed to connect" is a personal internet-related issue, check your network/follow the Mihon troubleshooting guide closer.

Otherwise, duplicate of #6675
