### ISSUE TITLE
Please change the domain of the read mangas extension 

### ISSUE THREAD

**Issue by BlackMember08** [keiyoushi/tachiyomi-extensions-source#6719]
### Source information

Read Mangas 1.4.32

### Source language

Português Brasil - PT-BR

### Source new URL

https://app.loobyt.com/

### Other details

![Screenshot_2024-12-20-12-49-34-077_com android chrome](https://github.com/user-attachments/assets/5ffc473f-bee2-464f-b3a4-64ab85ea86ef)
![Screenshot_2024-12-20-12-52-27-151_app komikku](https://github.com/user-attachments/assets/14fffef2-d95f-4585-823c-87f36d7e2eb9)
![Screenshot_2024-12-20-12-52-44-535_app komikku](https://github.com/user-attachments/assets/bb9480c9-fad8-44e8-a672-52720ce06a42)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by MrRobotCoder** [comment]
The theme has also changed, so a new analysis of the site will be needed, not just changing the domain.

**Comment by BlackMember08** [comment]
> O tema também mudou, então será necessária uma nova análise do site, não apenas uma mudança de domínio.

Mano parece que voltou a funcionar quando entro na extensão ela me redireciona para o novo site e voltou tudo a funcionar 
![Uploading Screenshot_2024-12-20-14-47-15-129_app.komikku.jpg…]()
![Uploading Screenshot_2024-12-20-14-47-21-127_app.komikku.jpg…]()

**Comment by MrRobotCoder** [comment]
@BlackMember08 This is just a workaround by the domain owner; they can stop the redirection at any time, breaking it again. The redirection only works in the webview, while in the app it doesn't work because it uses the URL https://readmangas.org

**Comment by AnonymousPtBr** [comment]
This website owner doesn't go a week without touching it!😅

**Comment by AnonymousPtBr** [comment]
Could you close this issue? #6629

**Comment by MrRobotCoder** [comment]
@Smol-Ame Duplicate issue (#6629)

**Comment by lordenecromante** [comment]
@BlackMember08 @AnonymousPtBr I'll submit a PR to fix the pagination of the chapters (I tested it with the manhwa 'Sucessão Imprestável' chapter 63, and now it's pulling the 5 pages) and the domain change.
