### ISSUE TITLE
A extensão "SlimeRead" alterou sua URL e não está sendo possível de ler mangás em Português Brasil - pt-br / Peço que verifiquem para reparar o bug

### ISSUE THREAD

**Issue by Subatomiic** [keiyoushi/tachiyomi-extensions-source#6736]
### Source information

SlimeRead 1.4.15

### Source language

Português Brasil - PT-BR

### Source new URL

https://slimeread.com/

### Other details

![Screenshot_2024-12-21-11-53-40-298_app mihon-edit](https://github.com/user-attachments/assets/6e4cdc53-c303-4464-bf2e-f5a3d179c2a8)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
Duplicate of #6673 

It's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.
