### ISSUE TITLE
Bato.to and Mangago Extension down 

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#6758]
### Source information

Bato.to 1.4.44  and Mangago 1.4.23

### Source language

English 

### Source new URL

https://hto.to/ for Bato

### Other details

said that the domain bato.to will be deprecate. unable to use it on Mihon. they still show the updates on chapters, but are no longer readable.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Norsze** [comment]
* Bato already has like 20 mirrors in the extension.
* only one bug per report.
* pretty sure mangago is already reported too, do a search before reporting.

**Comment by Norsze** [comment]
duplicate of #6675
