### ISSUE TITLE
Manga pro extension (AR)

### ISSUE THREAD

**Issue by Abdalla-R** [keiyoushi/tachiyomi-extensions-source#6760]
### Source information

Manga pro

### Source language

Arabic

### Source new URL

https://promanga.pro/home

### Other details

It would be great if an editing link button is added to the extension since it keeps changing,
Love you all and wish you the best!

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Anasplus** [comment]
أولا، لم يتغير الرابط، بل شكل الموقع 
ثانيا، خضع الموقع لتحديث في التصميم
ثالثا، نسيتَ وضع إصدار الإمتداد
رابعا، هناك أحد أخر أبلغ عن المشكلة، ربما أنت سبقته لكن طلبك رفض
