### ISSUE TITLE
Bato Cloudflare issue

### ISSUE THREAD

**Issue by diamanteuzumaki** [keiyoushi/tachiyomi-extensions-source#6761]
### Source information

Bato.to 1.4.44 

### Source language

English

### Steps to reproduce

1. Open comic from Bato.to
2. Pop-up saying "failed to bypass cloudflare"

### Expected behavior

The comic is opened

### Actual behavior

Comic does not open and popup appears.

### Mihon/Tachiyomi version

0.15.3

### Android version

14

### Other details

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by diamanteuzumaki** [comment]
Hi, I tried the links and I can't get it to work. I have Android 14 and use Chrome, if that helps.

**Comment by diamanteuzumaki** [comment]
Bato.to changed their domain to https://batocomic.com/ IDK if that's part of the issue

**Comment by Norsze** [comment]
Notice the rest of the message.

> If it doesn't work, migrate to other sources or wait until they lower their protection.

**Comment by Anutrix** [comment]
This is not a protection issue but domain redirect/change issue.
bato.to redirects to zbato.net now. The extension should use one of the mirrors.
See notice and also last one in deprecated section:
![Screenshot_20241224-033058_Firefox (1)](https://github.com/user-attachments/assets/17cb11b3-bd13-4245-b488-45c414676781)
![Screenshot_20241224-033116_Firefox](https://github.com/user-attachments/assets/9a7a3318-e5cd-44a5-80d5-4ff058989e48)

**Comment by diamanteuzumaki** [comment]
It worked now, thank you.
