### ISSUE TITLE
DeviantArt: UnsupportedOperationException 

### ISSUE THREAD

**Issue by AnonymousPtBr** [keiyoushi/tachiyomi-extensions-source#6788]
### Source information

DeviantArt 1.4.1

### Source language

Multiple 

### Steps to reproduce

Don't show content.

![Screenshot_2024-12-24-11-14-16-986_app mihon debug](https://github.com/user-attachments/assets/dbd29b47-dd0d-4206-93d7-3d7c8b395036)

### Expected behavior

Show content.

### Actual behavior

Don't show content.

### Mihon/Tachiyomi version

0.17.1-7043

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AwkwardPeak7** [comment]
read what it says... the extension only supports searching using the specified format

**Comment by AnonymousPtBr** [comment]
![Screenshot_2024-12-24-12-09-00-211_app.mihon.debug.jpg](https://github.com/user-attachments/assets/f5f92762-6c96-429c-b463-b7997f32df84)

**Comment by AwkwardPeak7** [comment]
don't add the {} in the query

**Comment by AnonymousPtBr** [comment]
And what is this error?

**Comment by AnonymousPtBr** [comment]
> don't add the {} in the query
> 

![Screenshot_2024-12-24-12-32-34-138_app.mihon.debug.jpg](https://github.com/user-attachments/assets/60704956-ce39-4ca4-895f-b4eba49e658f)

**Comment by AnonymousPtBr** [comment]
> don't add the {} in the query
> 

![Screenshot_2024-12-24-12-33-40-956_app.mihon.debug.jpg](https://github.com/user-attachments/assets/a1785ed2-58df-40d4-8268-aea3f6955f6b)

**Comment by DokterKaj** [comment]
> > don't add the {} in the query
> 
> ![Screenshot_2024-12-24-12-33-40-956_app.mihon.debug.jpg](https://private-user-images.githubusercontent.com/183020529/398439507-a1785ed2-58df-40d4-8268-aea3f6955f6b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNjE3NzIsIm5iZiI6MTczNTA2MTQ3MiwicGF0aCI6Ii8xODMwMjA1MjkvMzk4NDM5NTA3LWExNzg1ZWQyLTU4ZGYtNDBkNC04MjY4LWFlYTNmNjk1NWY2Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQxNzMxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTYzM2Q0MDRiMjU0NzZlNGYxNjc0NTIzNDcyMzRhZDFjN2ExMmJiNjcwY2VjZDExZmUzNTc3ZmVlY2IxMTE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BV-C48eDJZr3H5_msx4DgEJKhEZk5X_n235YAbj3lCU)

Open a new issue about this
I think I know the problem, I will fix it tomorrow
