### ISSUE TITLE
Legends no Fansub

### ISSUE THREAD

**Issue by lalalasupa0** [keiyoushi/tachiyomi-extensions-source#679]
### Source name

Legends no Fansub

### Source link

https://legends.nextnovels.com/

### Source language

Spanish

### Other details

+18/NSFW = no

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by lalalasupa0** [comment]
@beerpiss Wasn't it done well? I receive "No chapters found"

**Comment by bapeey** [comment]
> @beerpiss Wasn't it done well? I receive "No chapters found"

Which manga?

**Comment by bapeey** [comment]
Nvm, they changed domain just now xD

**Comment by lalalasupa0** [comment]
> Nvm, they changed domain just now xD

Should I open an url change report?
