### ISSUE TITLE
Jobsibe incorrect url

### ISSUE THREAD

**Issue by Kratos43R** [keiyoushi/tachiyomi-extensions-source#6797]
### Source information

1.4.38

### Source language

Spanish

### Steps to reproduce

1. Open the extension
2. This don't work 
3. Open the webview 
4. This redirect You to https://jobsibe.com/
5. If you search in Chrome  the real url is https://lmtos.com/ 
6. This don't concord so You can't use jobsibe extension

### Expected behavior

I expected the extension works because this extension have a Lot of mangas

### Actual behavior

This don't work :(

### Mihon/Tachiyomi version

Beta r7043

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bapeey** [comment]
You are using a deprecated extension, uninstall that version and install the new one with the same name

**Comment by Kratos43R** [comment]
Tk u merry christmas!!!
