### ISSUE TITLE
Request a new resource

### ISSUE THREAD

**Issue by yusufkaynakx** [keiyoushi/tachiyomi-extensions-source#6807]
### Source name

Elder Manga

### Source link

https://eldermanga.com/

### Source language

Turkish

### Other details

+18/NSFW = No

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by yusufkaynakx** [comment]
I reposted it because I thought it was forgotten.

**Comment by Smol-Ame** [comment]
There's over 480~ issues in the repo, and a lot more are older than that source request. Contributors can volunteer their time & efforts on any of the issue requests whenever they want. As with any source request or issue request, there's no guarantee & no ETA for anything.
