### ISSUE TITLE
Null exception

### ISSUE THREAD

**Issue by Stan-tab** [keiyoushi/tachiyomi-extensions-source#6809]
### Source information

Mangalib 1.4.99

### Source language

Russian

### Steps to reproduce

1. Tap to the extension
2. NullPoint Exception
![Screenshot_20241225-171412_Tachiyomi](https://github.com/user-attachments/assets/e362864a-d27f-4a47-9d00-0cbdddd2c086)

### Expected behavior

Extension should provide miraculous kinds of manga

### Actual behavior

Instead it provides issue
![Screenshot_20241225-171412_Tachiyomi](https://github.com/user-attachments/assets/3824a2fc-0a2f-4215-bce5-247ed715e219)

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 12

### Other details

I'm sure that it is issue in the extension because i can easyly browse any other(except of mangalibs subsource like hentaylib or yaoilib)
P.s i also wasnt able to read troubleshooting guide, please fix it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment]
This was fixed in #3219, you should update your extension.
