### ISSUE TITLE
Snow Machine Translations (EN) doesn't display numbers in text 

### ISSUE THREAD

**Issue by Hendeku** [keiyoushi/tachiyomi-extensions-source#6810]
### Source information

Snow Machine Translations 1.4.4 

### Source language

Multi 

### Steps to reproduce

1.tap any manga 
2.words appear but numbers do not 

### Expected behavior

It should display numbers in text 

### Actual behavior

It doesn't display numbers in text in the app
But numbers are display in WebView 

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment]
Do you have any example chapter to test with?

**Comment by Hendeku** [comment]
> Do you have any example chapter to test with?

All chapters

**Comment by vetleledaal** [comment]
I mean, do you have a chapter where numbers appear? The ones I looked at did not use any numbers.

**Comment by Hendeku** [comment]
> I mean, do you have a chapter where numbers appear? The ones I looked at did not use any numbers.

It Starts With a Kingpin Account chapter 1
