### ISSUE TITLE
تم رفضك أوتوماتيكيا، لأنك لم ادخل أي معلومات مفيدة

### ISSUE THREAD

**Issue by kirito58** [keiyoushi/tachiyomi-extensions-source#6815]
تم رفضك أوتوماتيكيا، لأنك لم ادخل أي معلومات مفيدة
و تلك الصور بدون فائدة
المشكلة بإختصار هي أن موقع "مانجا ليونز" لا يعمل
لكن أصحاب هذا الموقع أجانب لن يفهموا العربية 
و حتى لو كانوا، فأنت لم تلتزم بأضعف 
و أنا لن أعيد البلاغ لأننا لسنا في حاجة لهذا الموقع الذي تستخدمه، فهو يستعمل بوت لسرقة الفصول تلقائيا من موقع مانجا ليك، الذي يسرقها من المواقع المترجمة، جميع الأعمال بدون استثناء موجودة في مواقع أخرى، والأهم هو وجود مواقع أخرى تماما مثل مانجا ليونز، و التي تسرق كذالك من مانجاليك، لذالك إنقل أعمالك لها

_Originally posted by @Anasplus in https://github.com/keiyoushi/extensions-source/issues/6755#issuecomment-2558774315_
مشكلة انه في تطبيق يقول ليس هناك فصول و لا يمكن تحديث وقت تسوي تحديث صفحة تجاوبك منث مكتوب في صورة HTTP 404
![Screenshot_2024-12-25-19-46-13-823_app mihon](https://user-images.githubusercontent.com/146889079/398595327-297d326f-6110-4346-a3ec-0f77717cb1e8.jpg)

**Comment by vetleledaal** [comment]
Your screenshot did not upload completely, so it is not viewable.

Duplicate of #5732
