### ISSUE TITLE
تم رفضك أوتوماتيكيا، لأنك لم ادخل أي معلومات مفيدة

### ISSUE THREAD

**Issue by kirito58** [keiyoushi/tachiyomi-extensions-source#6816]
تم رفضك أوتوماتيكيا، لأنك لم ادخل أي معلومات مفيدة
و تلك الصور بدون فائدة
المشكلة بإختصار هي أن موقع "مانجا ليونز" لا يعمل
لكن أصحاب هذا الموقع أجانب لن يفهموا العربية 
و حتى لو كانوا، فأنت لم تلتزم بأضعف 
و أنا لن أعيد البلاغ لأننا لسنا في حاجة لهذا الموقع الذي تستخدمه، فهو يستعمل بوت لسرقة الفصول تلقائيا من موقع مانجا ليك، الذي يسرقها من المواقع المترجمة، جميع الأعمال بدون استثناء موجودة في مواقع أخرى، والأهم هو وجود مواقع أخرى تماما مثل مانجا ليونز، و التي تسرق كذالك من مانجاليك، لذالك إنقل أعمالك لها

_Originally posted by @Anasplus in https://github.com/keiyoushi/extensions-source/issues/6755#issuecomment-2558774315_
            و تقول لي نقل  مانهو لي اختيار أخر 1000 مانهو كم وقت  ا

**Comment by vetleledaal** [comment]
This is an app-related issue. Yes, you have to migrate manga one-by-one. There is a feature request for bulk migration here: mihonapp/mihon#14
