### ISSUE TITLE
WebtoonHatti

### ISSUE THREAD

**Issue by DanteZoldyck** [keiyoushi/tachiyomi-extensions-source#6838]
### Source information

Webtoon Hatti 1.4.41

### Source language

Türkçe

### Source new URL

https://webtoonhatti.me/

### Other details

URL has been changed
![IMG_3494](https://github.com/user-attachments/assets/f962eb28-2558-4fdb-ae54-4f2ff6867f68)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Norsze** [comment]
This is valid, as the bot didn't react to the URL and the old domain is https://webtoonhatti.dev.

**Comment by DanteZoldyck** [comment]
> This is valid, as the bot didn't react to the URL and the old domain is https://webtoonhatti.dev.

![IMG_3496](https://github.com/user-attachments/assets/e0d94bcd-32cf-46cf-9f79-0ff5a77eed90)

**Comment by DanteZoldyck** [comment]
> This is valid, as the bot didn't react to the URL and the old domain is https://webtoonhatti.dev.

![IMG_3497](https://github.com/user-attachments/assets/077e1132-937a-44db-a1a2-907e61c6593e)

This happens in the app but is there any way to fix it?

**Comment by DanteZoldyck** [comment]
Or is there nothing you can do, unfortunately I don't understand what you mean exactly

**Comment by Norsze** [comment]
You wait for an extension update

**Comment by DanteZoldyck** [comment]
> You wait for an extension update

Okey thank you so much thanks for helping have good day sir
