### ISSUE TITLE
DeviantArt: NullPointerException: null.

### ISSUE THREAD

**Issue by AnonymousPtBr** [keiyoushi/tachiyomi-extensions-source#6846]
### Source information

DeviantArt 1.4.2

### Source language

Multiple 

### Steps to reproduce

Don't show content in search.

![Screenshot_2024-12-27-17-34-17-262_com android chrome](https://github.com/user-attachments/assets/6cac0e7b-2425-4967-b16a-ede68b06b73d)
![Screenshot_2024-12-27-17-35-12-656_app mihon debug](https://github.com/user-attachments/assets/c47845c8-2a14-4bc7-b959-557f5f9a3cf3)
![Screenshot_2024-12-27-17-36-10-883_app mihon debug](https://github.com/user-attachments/assets/b5149d30-548b-4f52-a19c-1f48bf5154db)

### Expected behavior

Show content in search.

### Actual behavior

Don't show content in search.

### Mihon/Tachiyomi version

0.17.1-7043

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AnonymousPtBr** [comment]
![Screenshot_2024-12-27-17-37-43-405_app mihon debug](https://github.com/user-attachments/assets/cc73e045-70e9-444a-91e6-726bdc4d689d)

**Comment by Norsze** [comment]
Related to #6794

**Comment by AnonymousPtBr** [comment]
> Related to #6794 

It was opened by me too and it was closed as resolved, but the problem persists so I opened it again!

**Comment by vetleledaal** [comment]
`gallery:Serenity` shows nothing because the user 'Serenity' do not have any images uploaded.

`gallery:Serenity/Resennar` shows nothing because 'Resennar' is not a valid folderId.

What do you expect from the extension in these cases?

**Comment by DokterKaj** [comment]
@AnonymousPtBr as stated in the exception message, the search format is `gallery:{username}/{folderId}`, which returns a single gallery in the form of an entry. If you find it tedious to manually input it, you can set DeviantArt links to open by default in the extension settings.

**Comment by DokterKaj** [comment]
> `gallery:Serenity/Resennar` shows nothing because 'Resennar' is not a valid folderId.

Actually it seems that the gallery defaults to Featured in cases where `folderId` is neither numeric nor `all`. It might be best to restrict it to only allow those cases?

**Comment by AnonymousPtBr** [comment]
> @AnonymousPtBr as stated in the exception message, the search format is `gallery:{username}/{folderId}`, which returns a single gallery in the form of an entry. If you find it tedious to manually input it, you can set DeviantArt links to open by default in the extension settings.

![Screenshot_2024-12-28-13-02-41-478_com android chrome](https://github.com/user-attachments/assets/91667725-9af0-4efb-a75c-fbf1fc5c0d0f)
![Screenshot_2024-12-28-13-02-33-599_app mihon debug](https://github.com/user-attachments/assets/41660738-048a-436f-9e42-91124b24dc89)
![Screenshot_2024-12-28-13-01-31-047_app mihon debug](https://github.com/user-attachments/assets/95116c6d-cd31-48cf-92cf-1266bca9d341)
![Screenshot_2024-12-28-13-01-19-158_app mihon debug](https://github.com/user-attachments/assets/69ffa186-dd37-49e5-a9a8-fecb01d8f2c9)
![Screenshot_2024-12-28-13-01-08-401_app mihon debug](https://github.com/user-attachments/assets/35ea937a-9141-4cf3-931a-60cc70e0590b)
![Screenshot_2024-12-28-13-00-56-295_app mihon debug](https://github.com/user-attachments/assets/f5f7118c-0146-494e-ba28-549fc042a560)
![Screenshot_2024-12-28-12-59-04-821_app mihon debug](https://github.com/user-attachments/assets/0035b4e4-2283-4bde-91ea-c28abd86c45e)
![Screenshot_2024-12-28-12-58-36-504_app mihon debug](https://github.com/user-attachments/assets/9484f064-7a1e-471f-9661-1b832fef3ab7)
![Screenshot_2024-12-28-12-58-13-528_app mihon debug](https://github.com/user-attachments/assets/d1db4e2c-f2ec-47c3-938f-b3e9347d4bdb)

**Comment by DokterKaj** [comment]
@AnonymousPtBr I do not see a NullPointerException even when I search `gallery:Serenity`; I get an entry with zero chapters instead. Did you update your extension?

**Comment by DokterKaj** [comment]
Also, as explained before, do not actually add curly braces in the search query. If you find it unclear, do you want me to change the message to say `gallery:username/folderId` instead?

**Comment by AnonymousPtBr** [comment]
> @AnonymousPtBr I do not see a NullPointerException even when I search `gallery:Serenity`; I get an entry with zero chapters instead. Did you update your extension?

![IMG_20241228_130712](https://github.com/user-attachments/assets/0a8d0c2c-ea8f-4e58-a15f-0b7832eb882f)

**Comment by DokterKaj** [comment]
Can you press "Open in WebView" then take a screenshot and copy the link?

**Comment by DokterKaj** [comment]
@AnonymousPtBr actually can you go to `Settings > Advanced > Default user agent string` and send your user agent?

**Comment by AnonymousPtBr** [comment]
> @AnonymousPtBr actually can you go to `Settings > Advanced > Default user agent string` and send your user agent?

![Screenshot_2024-12-28-13-27-52-039_app.mihon.debug.jpg](https://github.com/user-attachments/assets/8746d824-ee83-4408-b252-c482ff05b41b)

**Comment by DokterKaj** [comment]
I think I know the issue now, I will do some testing tomorrow

**Comment by AnonymousPtBr** [comment]
> @AnonymousPtBr actually can you go to `Settings > Advanced > Default user agent string` and send your user agent?

I changed the agent to default and it worked!

![Screenshot_2024-12-28-13-32-43-381_app.mihon.debug.jpg](https://github.com/user-attachments/assets/68832453-4888-4e06-a0b7-3676b03f1413)
