### ISSUE TITLE
Os mangas da Sussy Scan não aparece

### ISSUE THREAD

**Issue by NEFMM** [keiyoushi/tachiyomi-extensions-source#6860]
### Source information

Sussy Scan 1.4.41

### Source language

Portuguese

### Source new URL

https://oldi.sussytoons.site/

### Other details

As obras não aparecem no app.
![Screenshot_20241227_221726_Mihon](https://github.com/user-attachments/assets/c06e4f86-6f8c-4fee-b289-825ac3ecfd92)

Mas quando faço o acesso através da Web view, os mangas aparecem.
![Screenshot_20241227_221825_Mihon](https://github.com/user-attachments/assets/306d53a4-e184-4028-a99d-8770e69bbcc9)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Norsze** [comment]
Duplicate of #6034
