### ISSUE TITLE
Scan-Manga Extension: URL Update Required

### ISSUE THREAD

**Issue by quamilou** [keiyoushi/tachiyomi-extensions-source#6862]
### Source information

Scan-Manga 1.4.8

### Source language

French

### Source new URL

https://www.scan-manga.com/?mf

### Other details

The current URL configured for the Scan-Manga extension (https://www.scan-manga.com) returns a 500 Internal Server Error when accessed via the app and a 404 error when accessed via WebView.  
After investigation, it seems that the correct URL for the source is https://www.scan-manga.com/?mf, which points to a valid manifest.json file.  

Suggested fix: Update the extension to use the new URL (https://www.scan-manga.com/?mf) to avoid these errors.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
Duplicate of #2232, but comment your findings in there.

Also, wrong issue request type, since the domain hasn't changed
