### ISSUE TITLE
Source request: Mangapark.io not Mangapark.net

### ISSUE THREAD

**Issue by DAVID02lah** [keiyoushi/tachiyomi-extensions-source#6873]
### Source name

Mangapark.io 

### Source link

https://mangapark.io/

### Source language

Multi /  English

### Other details

Just everything from Mangapark.io thanks.
I know theres Mangapark.net but some "manga" not available in  .net so yeah.
Warm regard.

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### 

_No response_

**Comment by AwkwardPeak7** [comment]
It is a mirror domain of mangapark, you can change domain in extension settings.
