### ISSUE TITLE
Trocaram a URL da extensão Sussy Scans

### ISSUE THREAD

**Issue by Darkrever2** [keiyoushi/tachiyomi-extensions-source#6881]
### Source information

Sussy Scans

### Source language

Português 

### Source new URL

https://oldi.sussytoons.site/

### Other details

![Screenshot_20241228-132241](https://github.com/user-attachments/assets/dcfcb382-6d0d-4bfa-ae6e-f87a9ed6957c)
![Screenshot_20241228-132252](https://github.com/user-attachments/assets/d2340339-af66-4b86-ab6c-ebcd2decb58b)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Norsze** [comment]
Duplicate of #6034
