### ISSUE TITLE
Two sources not working properly

### ISSUE THREAD

**Issue by LoginPanel07** [keiyoushi/tachiyomi-extensions-source#6890]
### Source information

Spider Scans 1.4.37 and Snow Machine Translations 1.4.5

### Source language

English

### Steps to reproduce

Disclaimer: I use Tachimanga, an unofficial iOS adaptation of Tachiyomi, that is nearly identical.

Spider Scans: 

Issue: URL not changed properly, the main url is changed to spidyscans.xyz, as well as the chapter URLs, but not the series urls, as they stayed the same. 

Example: 
Main url: spidyscans.xyz
Series url: spiderscans.xyz/manga/I-Can-See-the-Forbidden-Zone-Rules/
Chapter url: spidyscans.xyz/manga/I-Can-See-the-Forbidden-Zone-Rules/chapter-20/

Steps to recreate issue:
1. Open a series of the extension.
2. Check the url of the series

Snow Machine Translations:

Issue: Cannot view or download series’s chapters in the app, must use webview.

Error message when opening/downloading chapter: android.graphics.Bitmap android.gra phics.Bitmap.copy(android.graphics.B
itmap$Confia. boolean)

Steps to recreate issue:
1. Open a series of the extension
2. Try to view it in the app/download chapter

### Expected behavior

The Snow Machine TL should open the series properly, allowing to view and download them. And spiderscans extension should display and lead to the new urls.

### Actual behavior

Spiderscans: series link is wrong.
Snow Machine Translations: displayed error when trying to download or read in the app: android.graphics.Bitmap android.gra phics.Bitmap.copy(android.graphics.B
itmap$Confia. boolean)

### Mihon/Tachiyomi version

Tachimanga v4.1(291)

### Android version

iPhone iOS 18.0

### Other details

I use Tachimanga for reading

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
1. Tachimanga isn't something we support, and just cause it looks the same doesn't mean it is/nearly the same. Test with Mihon or forks of Mihon first to see if it's a Tachimanga issue
2. In general, make individual issue requests for each source/each issue
3. SpiderScans is set to spidyscans, and the series opens to said spidyscans URL, try migrating the title back into SpiderScans if you can on Tachimanga.
4. For Snow Machine Translations, seems to work fine, as mentioned above, try on Mihon.


Add-on, to show series link for SpiderScans, screenshotted as fast as possible to show it loads into the current URL:

![Screenshot_20241228_130938_Mihon.png](https://github.com/user-attachments/assets/5faff6b8-0db8-4b3b-a993-f0f88a14ad0b)

![Screenshot_20241228_130919_Mihon.png](https://github.com/user-attachments/assets/a92a4b65-d23e-45f9-893f-91946a44355f)

**Comment by vetleledaal** [comment]
Given [all the Android APIs used](https://github.com/keiyoushi/extensions-source/blob/a24e0d65e06eee184d93e435a3a2c79e04a63eec/src/all/snowmtl/src/eu/kanade/tachiyomi/extension/all/snowmtl/interceptors/ComposedImageInterceptor.kt#L3-L13) in Snow MTL, it would be kinda impressive if Tachimanga already supported that out of the box. I doubt even [Suwayomi](https://github.com/Suwayomi/Suwayomi-Server) supports the extension, even if it uses a proper JVM, because of all the Android APIs used.
