### ISSUE TITLE
features that might be useful

### ISSUE THREAD

**Issue by Hanglim88** [keiyoushi/tachiyomi-extensions-source#6906]
### Source name

not the actual scan

### Source language

English

### Describe your suggested feature

wouldn't it be better if we could lock the pages we choose? 

### Other details

I mean, in this application we can add several other pages besides the main page, wouldn't it be better if there was a page privacy feature, to protect user privacy. 
So I can put some manhwa that only I can open on this phone, I'm just annoyed when other people open my 2nd page just because of the manhwa genre they don't like.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
This is an extension repo, not an app, go check with them instead.
