### ISSUE TITLE
Omega Scans not working

### ISSUE THREAD

**Issue by Tsukishi-01** [keiyoushi/tachiyomi-extensions-source#6911]
### Source information

Omega Scans 1.4.45

### Source language

English

### Steps to reproduce

1. Install Omega Scans extension
2. Open the source
3. Site should work and show content

### Expected behavior

Show content from site

### Actual behavior

Cant connect and shows connection reset

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
Have you tried looking at the site in WebView or even your own browser?

**Comment by Tsukishi-01** [comment]
I did and the site doesnt load. Saying connection reset

**Comment by Smol-Ame** [comment]
Well maybe because their site has been/is down the past couple of days. Otherwise, it's your own internet-related issues.

Switch networks, use a VPN, and if needed change DNS over HTTPS in Mihon Settings > Advanced (remember to restart the app). Not an extension-related issue.

![Screenshot_20241230_060954_Firefox Nightly](https://github.com/user-attachments/assets/5f2fcc9f-a25b-48b1-aeea-8e4cb003e276)
