### ISSUE TITLE
Sussy Scan: WebView don't show content!

### ISSUE THREAD

**Issue by AnonymousPtBr** [keiyoushi/tachiyomi-extensions-source#6913]
### Source information

Sussy Scan 1.4.42

### Source language

Portuguese

### Steps to reproduce

WebView don't show content.

### Expected behavior

Show content.

### Actual behavior

WebView don't show content.

![Screenshot_2024-12-30-14-23-20-765_app mihon debug](https://github.com/user-attachments/assets/969afde6-79a8-4905-972c-91c13bd9e46a)

### Mihon/Tachiyomi version

0.17.1-7044

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by choppeh** [comment]
Mude seu user-agent
