### ISSUE TITLE
Extension not 'working'? 

### ISSUE THREAD

**Issue by AlmghtyLuc1D** [keiyoushi/tachiyomi-extensions-source#6917]
### Source information

Shinigami 1.4.66

### Source language

Indonesia

### Steps to reproduce

1. when i open the extension source, it failed to bypass cloudflare. but when i open it in webview. its normal, the webview is open

### Expected behavior

i hope that i can bypass the cloudflare or something

### Actual behavior

the webview is open, but the mihon cant see the source

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
Click around WebView, see if any other Cloudflare verification pops up. Otherwise, back out of WebView & hit retry, or change your user-agent to something else to see if the site just isn't happy with specific UAs. Works fine on my end.
