### ISSUE TITLE
ZinChanManga

### ISSUE THREAD

**Issue by reygrey666** [keiyoushi/tachiyomi-extensions-source#692]
### Source information

1.4.33

### Source language

English

### Source new URL

https://zinchanmanga.net/

### Other details

The old link (zinchanmanga.com) not dead yet but the content had many skipped and missing chapters and some title is not been updated. 
The new link had a whole chapters and more updated titles.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Sorry, the bot tripped on the "not been updated" keyword.
