### ISSUE TITLE
litch

### ISSUE THREAD

**Issue by miphiris** [keiyoushi/tachiyomi-extensions-source#6921]
### Source name

Mangadex

### Source link

https://mangadex.org

### Source language

English USA-EN

### Other details

![7d45f363-a9f4-472b-9a6a-b94295636170](https://github.com/user-attachments/assets/b7acb0ab-5521-449f-9a45-6372366b33c3)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment]
If you don't see MangaDex as an extension make sure you have added the correct repo and have not filtered out NSFW extensions. Please ask in #support on Discord if that doesn't help.
