### ISSUE TITLE
Hentai Era Source Request 

### ISSUE THREAD

**Issue by devil6venom** [keiyoushi/tachiyomi-extensions-source#697]
### Source name

Hentai era

### Source link

https://hentaiera.com

### Source language

English

### Other details

Nsfw= Yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by 0Ha16wA5** [comment]
Implemented on https://github.com/komikku-app/komikku-extensions/commit/dd867931e28be846433a334ae4b6a22972a7c0ac

https://github.com/komikku-app/komikku-extensions/issues/13

Might be wise to merge it here...
