### ISSUE TITLE
Batoto unable to view downloaded jpg image

### ISSUE THREAD

**Issue by CactusTheGuy** [keiyoushi/tachiyomi-extensions-source#700]
### Source information

Bato.to 1.4.34

### Source language

Multi

### Steps to reproduce

1. Start searching for a comic name "Yukyu Omega" (Alternate name: Paid Leave Omega)
2. After finding it, start download all chapters of it
3. Opening chapter 1 (Teaser chapter is not affected) and swipe from page 4 to page 9, page 36 and it start in a loading state.

### Expected behavior

jpg image should be viewed normally

### Actual behavior

Cannot view any image file that have extension .jpg

### Tachiyomi version

Mihon 0.16.1

### Android version

MIUI 14 Android 13

### Other details

This affect chapter 1 (page 4 to page 9, page 36), chapter 2 (page 4 and 33), chapter 3 (page 4 and 39), chapter 4 (page 4 and 39), chapter 5 (page 4 and page 34), chapter 6 (page 50), end chapter (page 4), teaser chapter does not contain jpg image file

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Seems to be a problem with the app's image decoder. All the pages you have mentioned uses the CMYK color space instead of RGB.

Closing as this is not something we can solve.

EDIT: Issue created in app repository. 243
