### ISSUE TITLE
Mangahub Api rate limit

### ISSUE THREAD

**Issue by ExoZNiK** [keiyoushi/tachiyomi-extensions-source#703]
### Source information

Mangahub 1.4.33

### Source language

English

### Steps to reproduce

Try to open a manga of the mangahub source.

### Expected behavior

Should open the chapter

### Actual behavior

![Screenshot_2024-01-27-12-29-08-95_a603e4da04bada03cae438f177815547](https://github.com/keiyoushi/extensions-source/assets/73558501/450bad0d-c871-4061-b2c0-140f1888add4)
It gives this error instead.

### Tachiyomi version

TachiyomiSY 1.10.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Delete cookies and WebView data and try again. I cannot reproduce the issue.

**Comment by ExoZNiK** [comment]
Ok i had alteady tried deleting cookies for the extension and that didn't work. But opening one manga of the mangahub source in webview and deleting the cookies there did the trick for now! I tought that deleting the cookies of the extension was the same thing.
