### ISSUE TITLE
Jianman Tiantang（禁漫天堂）custom UA

### ISSUE THREAD

**Issue by mxb945** [keiyoushi/tachiyomi-extensions-source#704]
### Source information

Jinman Tiantang 1.4.40

### Source language

中文

### Steps to reproduce

Cloudflare

### Expected behavior

UA

### Actual behavior

UA

### Tachiyomi version

tachiyomiSY542,mihon6458

### Android version

Android14

### Other details

The default UA can't get the update normally, so it needs to be changed to "Mozilla/5.0 (Linux; Android 14) Apple WebKit/537.36 (khtml, like gecko) Chrome/121.0.6167.101 Mobile Safari/537.36 ",Others can't bypass Cloudflare. Although they have been changed, they can get updated comics to read, but they can't display the comic cover normally.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ZerOri** [comment]
一些插件不修改app默认UA就无法正常浏览，你需要的是提出在插件内加入独立UA设置功能。

**Comment by luxiayo** [comment]
Even though custom or random UA fixes the cloudflare issue in the new version 1.4.41(however, still have to open the browser and click to verify), the cover still doesn't display properly.

**Comment by ZerOri** [comment]
> Even though custom or random UA fixes the cloudflare issue in the new version 1.4.41(however, still have to open the browser and click to verify), the cover still doesn't display properly.

无法复现你提到的问题，建议检查插件内镜像网址设置，或关闭代理工具试试。当然也可能是网站本身网络加载问题。
