### ISSUE TITLE
OPSCANS shows HTTP error 502 always

### ISSUE THREAD

**Issue by Kantotero** [keiyoushi/tachiyomi-extensions-source#705]
### Source information

OPSCANS 1.4.1

### Source language

English

### Steps to reproduce

1. Open OPscans when browsing from extension lists
2. It shows the HTTP error 502
3. Open in webview
4. the issue still persists, the manga series doesn't show up
![IMG_20240127_205057](https://github.com/keiyoushi/extensions-source/assets/125627064/cb2e9746-d6dd-4860-bf7c-5cb7af15bcc1)

### Expected behavior

The manga series/ collection should've popped up

### Actual behavior

HTTP error 502 always pops up

### Tachiyomi version

J2K 1.7.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DFBR1208** [comment]
For me it's loading error 404 and opening in webview, Android 14 SY 1.10.2
![Screenshot_20240131_013845_TachiyomiSY](https://github.com/keiyoushi/extensions-source/assets/121575433/7d6b2246-56f6-4558-9413-1707565cf4ad)
![Screenshot_20240131_013851_TachiyomiSY](https://github.com/keiyoushi/extensions-source/assets/121575433/a1cb1461-37e4-4384-8f22-579cac5eaec1)
