### ISSUE TITLE
3Hentai: Source Request 

### ISSUE THREAD

**Issue by ImAlwaysHorni** [keiyoushi/tachiyomi-extensions-source#707]
### Source name

3HENTAI

### Source link

https://3hentai.net/

### Source language

MULTI

### Other details

18+/NSFW=YES

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
@ImAlwaysHorni why did you wipe and close your old issue to create a new one

**Comment by ImAlwaysHorni** [comment]
> @ImAlwaysHorni why did you wipe and close your old issue to create a new one

for acknowledgment issues 🐸

**Comment by AwkwardPeak7** [comment]
> for acknowledgment issues 🐸


you closed #485, and made a new one. this won't magically make your request faster

**Comment by ImAlwaysHorni** [comment]
> > for acknowledgment issues 🐸
> 
> you closed #485, and made a new one. this won't magically make your request faster


i renamed it because that case got closed and i couldn't post a new request of same name or duplicate it..so i renamed the closed one and checked this acknowledgment ↓

" I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open or closed issue."

**Comment by AwkwardPeak7** [comment]
> i renamed it because that case got closed and i couldn't post a new request of same name or duplicate it..so i renamed the closed one and checked this acknowledgment ↓

You aren't supposed to open duplicate issues by wiping/closing the old one.

**Comment by ImAlwaysHorni** [comment]
> > i renamed it because that case got closed and i couldn't post a new request of same name or duplicate it..so i renamed the closed one and checked this acknowledgment ↓
> 
> You aren't supposed to open duplicate issues by wiping/closing the old one.

i would be more careful next time 🙂
thank you

**Comment by beer-psi** [comment]
Closing in favor of #485. I will not accept bumping issues like this.
