### ISSUE TITLE
Hentai20 website changed

### ISSUE THREAD

**Issue by sovit042** [keiyoushi/tachiyomi-extensions-source#711]
### Source information

Hentai20 1.4.36

### Source language

English

### Source new URL

https://hentai20.io

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by sovit042** [comment]
I extension is not loading any series and discord supporter told me its a website change so can u plz check but the extension is really broken as itsgoimg for a while now

**Comment by beer-psi** [comment]
I have already told you this is the wrong template to use. And also to read the acknowledgements carefully. If you can't figure this out you'll just have to move to a different extension.
