### ISSUE TITLE
Hentai20 extension is broken

### ISSUE THREAD

**Issue by sovit042** [keiyoushi/tachiyomi-extensions-source#718]
### Source information

Hentai20 1.4.36

### Source language

English

### Steps to reproduce

1. Download hentai20 extension
2. Trust it
3. Open the extension it will not load any series

### Expected behavior

It should load the series

### Actual behavior

It dosn't load any series and show no result found and you can't update any series while the webview works fine

### Tachiyomi version

Tachiyomi 0.15.3 and miho 0.16.1

### Android version

Android 10

### Other details

Its not a cloudflare protection problem

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by sovit042** [comment]
I have tried both of it even tried to download tachiyomi in new phone but the problem is still there

**Comment by sovit042** [comment]
Some plz solve this if you can 😭😭

**Comment by devil6venom** [comment]
> Some plz solve this if you can 😭😭

It uses mangathemesia theme now!!
Mail me i can provide you unofficial verison!

bunnykapoor49@gmail.com

**Comment by beer-psi** [comment]
> > Some plz solve this if you can 😭😭
> 
> It uses mangathemesia theme now!! Mail me i can provide you unofficial verison!
> 
> [bunnykapoor49@gmail.com](mailto:bunnykapoor49@gmail.com)

I'd appreciate it if you'd take time to make a pull request instead of providing fixes through back channels.

**Comment by sovit042** [comment]
Brother @devil6venom I appreciate you for the help but it will cause problem in updating the extension in the future if its not from the repo thats why I am reluctant to do that but thx

**Comment by sovit042** [comment]
@beerpiss brother u closed it as fixed but when I checked there wasn't any update can u plz explain ? Do I need to do something ?

**Comment by Norsze** [comment]
The update has not yet been pushed to the repo, it will be there the next update of the repo. The repo is not updated the moment a commit is made.

**Comment by sovit042** [comment]
Oo sorry until now all the extension I have reported got there update when the complain was closed so I thought that was the norm sorry 😅
