### ISSUE TITLE
Mangakakalot only loads first page

### ISSUE THREAD

**Issue by MyNamesKing** [keiyoushi/tachiyomi-extensions-source#723]
### Source information

Mangakakalot 1.4.8

### Source language

English

### Steps to reproduce

1. Open any chapter in Mangakakalot extension
2. The first page will load fine, but every subsequent page will read "The Image Couldn't Be Loaded"
3. The chapter will load fine in web view however
4. This is only on Mangakakalot and no other extension

![Tachiyomi Mangakakalot Bug](https://github.com/keiyoushi/extensions-source/assets/155758078/ab395197-0907-48a2-9600-b06b732faf26)

### Expected behavior

All pages should load ideally

### Actual behavior

Only the first page loads

### Tachiyomi version

Tachiyomi 0.15.3

### Android version

Android 8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by SnakeDoc83** [comment]
Can't reproduce.

**Comment by Norsze** [comment]
Neither can I

**Comment by MyNamesKing** [comment]
My best guess is it might have been an issue on mangakakalot's side? Just checked and I can't seem to reproduce it anymore either..
Thanks for looking into it anyway!
