### ISSUE TITLE
Hentai nexus chapter issues

### ISSUE THREAD

**Issue by devil6venom** [keiyoushi/tachiyomi-extensions-source#727]
### Source information

Hentai nexus 1.4.5

### Source language

English 

### Steps to reproduce

1. Install it from site.
2. Open it
3. It load fine but whenever i tap chapters, it shows error.

### Expected behavior

This should load chapter and able to show content 

### Actual behavior

It doesn't load chapters.

### Tachiyomi version

0.15.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by SnakeDoc83** [comment]
Problem seems intermittent. Tried 10 random chapters, had a problem once. After checking webview I was able to load the afflicted chapter. Couldn't reproduce again after that; can't say if that was coincidence or not. I didn't quite catch what the error was but it wasn't an exception, it read something like "xxxx = 7, xxxx = 7".

**Comment by beer-psi** [comment]
```
java.lang.ArrayIndexOutOfBoundsException: length=7; index=7
	at java.util.Arrays$ArrayList.get(Arrays.java:4210)
	at eu.kanade.tachiyomi.extension.en.hentainexus.HentaiNexusUtils.decryptData(HentaiNexusUtils.kt:39)
```

I forgot to fill in enough prime numbers. Oops.
