### ISSUE TITLE
Request mangatoto.com

### ISSUE THREAD

**Issue by dnet890** [keiyoushi/tachiyomi-extensions-source#733]
### Source name

Mangatoto

### Source link

https://mangatoto.com/

### Source language

English and Indonesian

### Other details

I believe this is the mirror site from bato. But, it is nice to have an alternatives

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
Mirror of bato.to which already exists. You can switch to this mirror in bato extension settings
