### ISSUE TITLE
Hentai Nexus Re-Chapter Issue

### ISSUE THREAD

**Issue by devil6venom** [keiyoushi/tachiyomi-extensions-source#738]
### Source information

Hentai Nexus 1.4.6

### Source language

English 

### Steps to reproduce

1. I uninstalled old Verison and updated new one!
2. Then choose any manga,
3. It shows chapter, thumbnail and chapter
4. After opening chapter you get the message"this page cannot be loaded"
5. Choose any manga..it shows same message!
6. In WebView it can show up though! Just not in tachiyomi!

### Expected behavior

After fix, i guess it should show all chapter, but none of page showing!

### Actual behavior

Page cannot be loaded! 

### Tachiyomi version

0.15.3

### Android version

Android 13

### Other details

Can i paste picture if it helps?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Can't reproduce. What entry can't you load?

**Comment by devil6venom** [comment]
> Can't reproduce. What entry can't you load?

Any manga, it shows loads manga but not chapters! It shows the message of the image couldn't be loaded!

**Comment by beer-psi** [comment]
Please give a specific entry so I can potentially debug the issue. "Any manga" doesn't exist on HentaiNexus.

**Comment by devil6venom** [comment]
Okay 

> Please give a specific entry so I can potentially debug the issue. "Any manga" doesn't exist on HentaiNexus.

The first one,happy milk life! Check this ..

**Comment by devil6venom** [comment]
A Flower Just For Me ~Part 1~

It also have the same error , the image cannot be loaded. When i open in WebView, it loads fine but not in tachiyomi!

**Comment by devil6venom** [comment]
![Screenshot_20240128-121329](https://github.com/keiyoushi/extensions-source/assets/92388530/552af6c4-a23d-48b3-a9a1-d3bb68fe2e47)

**Comment by 0Ha16wA5** [comment]
Both titles works perfectly on my phone.
Tested using latest version of Mihon, Aniyomi, and TachiyomiSY.

**Comment by devil6venom** [comment]
> Both titles works perfectly on my phone. Tested using latest version of Mihon, Aniyomi, and TachiyomiSY.

Oh yeah, now it is fixed.. before it was showing something like this image cannot be loaded and stuff.. i clear cache ...clear data too! Then reinstall 1.4.7 version, and its fixed🔥

Thank you sooo much for your help brother 🌚

I can close this now!⚰️💀
