### ISSUE TITLE
Request Komikges

### ISSUE THREAD

**Issue by ShoujoLover** [keiyoushi/tachiyomi-extensions-source#774]
### Source name

Komikges

### Source link

www.Komikges.my.id

### Source language

Indonesian (ID)

### Other details

Nsfw = no

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by SupKelelawar** [comment]
ngapain req web mati

**Comment by ShoujoLover** [comment]
> ngapain req web mati

Terserah org ngab, daripada req web mirror. Lagipula tujuan w req yura, berhubung templatenya webnya sama ya sekalian ae

**Comment by Riztard** [comment]
kasi detail templatenya sama kek yang mana, biar devnya tau

**Comment by ShoujoLover** [comment]
> kasi detail templatenya sama kek yang mana, biar devnya tau

Kalo ditanya detail w kurang paham sih, keknya buat ext tachi blom ada, kalo kotatsu udh ada.

https://www.rasgane.com/2023/11/makaru-blogger-template.html
