### ISSUE TITLE
MangaHub: Failed to connect to URL

### ISSUE THREAD

**Issue by Davidbolt121199** [keiyoushi/tachiyomi-extensions-source#775]
### Source information

MangaHub 1.4.33

### Source language

English

### Steps to reproduce

1.When open any Manga/Manhwa chapters the pages keeps loading.
2. After sometime it shows " failed to connect to api.mghcdn.com".
3. When open WebView on website also the chapters pages are not loading.

### Expected behavior

1.Instead of showing "failed to connect to api.mghcdn.com" error.
2. All pages should have uploaded without any error.

### Actual behavior

It shows "failed to connect to api.mghcdn.com/15.197.13"
![Screenshot_2024-01-29-16-11-40-117_eu kanade tachiyomi](https://github.com/keiyoushi/extensions-source/assets/121578582/3f6a4dfa-8dd9-40c3-ab58-00c7ed5eeefd)

### Tachiyomi version

0.15.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
If the website doesn't work, then it's not our problem.
