### ISSUE TITLE
Nettruyen urls changed again. please help

### ISSUE THREAD

**Issue by PartytimeMentat** [keiyoushi/tachiyomi-extensions-source#779]
### Source information

NetTruyen 1.4.24

### Source language

Vietnamese

### Source new URL

www.nettruyenss.com

### Other details

they changed the urls from www.nettruyenclub.com into www.nettruyenss.com

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Not again.
