### ISSUE TITLE
MGKOMIK cant read chapter

### ISSUE THREAD

**Issue by kaisanti** [keiyoushi/tachiyomi-extensions-source#78]
### Source information

MG Komik 1.4.43

### Source language

Indonesia 

### Steps to reproduce

Cant read chapter 

### Expected behavior

page not found image script , same admin in mgkomik and shinigami, maybe he use same patch to mgkomik

### Actual behavior

Please fix sir 🙏

### Tachiyomi version

0.15.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Closed by #407
