### ISSUE TITLE
Manhuagui will throw 403 when updating and searching

### ISSUE THREAD

**Issue by hoshibara** [keiyoushi/tachiyomi-extensions-source#780]
### Source information

Manhuagui 1.4.18

### Source language

Chinese

### Steps to reproduce

1. Search with manhuagui extension

### Expected behavior

Can search & update properly

### Actual behavior

`HTTP 403, Please check website in WebView.`
But in Webview, I can read and search manga normally.

### Tachiyomi version

mihon 0.16.2

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ZerOri** [comment]
无法复现问题，建议检查代理工具

**Comment by hoshibara** [comment]
那可以麻烦分享一些你们调试extension的方法吗？
我这边webview可以正常访问网站，ios上的aidoku也能正常获取，只有tachiyomi extension会出现这个报错。

**Comment by ZerOri** [comment]
> 那可以麻烦分享一些你们调试extension的方法吗？ 我这边webview可以正常访问网站，ios上的aidoku也能正常获取，只有tachiyomi extension会出现这个报错。

大概率是你使用的代理工具分流规则有问题，漫画柜需要挂大陆以外IP访问。

**Comment by hoshibara** [comment]
ok，感谢您的回复，我之后再确认一遍流量是否通过了代理

**Comment by hoshibara** [comment]
@ZerOri 我刚刚尝试用fiddler修改了mihon发出的请求包，观察到在发出的headers里添加（这个header来自webview请求manhuagui.com使用的headers）
```
Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7
```
就可以让请求正常响应，这可能是manhuagui对爬虫的一种判断，不知是否能在[manhuagui.kt](https://github.com/keiyoushi/extensions-source/blob/ff6913b42672a7b4c526c8c5c7b8f240378d7c49/src/zh/manhuagui/src/eu/kanade/tachiyomi/extension/zh/manhuagui/Manhuagui.kt#L254)中添加这个header？
