### ISSUE TITLE
auditore scans

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#785]
### Source name

auditore scans

### Source link

https://auditorescans.com

### Source language

Português (Brasil)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
This site might be dead

**Comment by Norsze** [comment]
According to the group's uploads on MangaDex they seem to now be be called **asgardscans** and are using https://asgardscans.com/ as their website

**Comment by vetleledaal** [comment]
Both of the links are currently dead. Open a new issue if they open another site.
