### ISSUE TITLE
Naver Comic Bug

### ISSUE THREAD

**Issue by Episode12** [keiyoushi/tachiyomi-extensions-source#786]
### Source information

Naver Comic 1.4.4

### Source language

Korean

### Steps to reproduce

1. Open Naver Comic Extention through Mihon app.
2. Open a 'Manhwa', then click on a chapter to read.
3. The Manhwa page loads just fine. No problem with the website either.
4. But, when i try to read a chapter it shows 'No pages found'.
5. I tried to open in webview mode to see if there's any cloudflare protection. There was none.
6. I checked if the page itself have problem, but no. The page loads fine in webview mode.

### Expected behavior

I should've been able to read any manhwa chapter.

### Actual behavior

The extention fails to load the chapter.

### Tachiyomi version

Mihon 16.3

### Android version

Android 13

### Other details

I use a Samsung phone with Android 13, One ui 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Episode12** [comment]
Sorry, i mistakenly wrote the Mihon app version 16.3😅😅 it's 16.2.

**Comment by SnakeDoc83** [comment]
Can you give an example: manhwa name and chapter? It seems in working order to me.

**Comment by Episode12** [comment]
수요웹툰의 나강림

https://comic.naver.com/webtoon/list?titleId=771718

Try this one. Updates are showing as usual. But when i try to read it, it shows 'No pages found'.

I read the chapter in webview. The chapter is loading fine. But, i can't read it through the app. Download is also not working as well.

**Comment by Claudemirovsky** [comment]
> 수요웹툰의 나강림
> 
> it shows 'No pages found'.
> 
> I can't read it through the app. Download is also not working as well.

I checked some chapters (1, 6, 12, 24, 48, 64, 96, 101, 128, 144) and all were able to load and be read/downloaded just fine here. Can you check if the problem still happens to you? Maybe it was a temporary issue.

Tested with TachiyomiSY 1.10.1, in Android 11(GO).

**Comment by Episode12** [comment]
I'll check with tachiyomi sy

**Comment by Episode12** [comment]
It worked! Sorry, it seems the problem was in my User agent string. I changed it to default and it's working now. Sorry to bother you. And thanks for keeping this repository active👍👍
