### ISSUE TITLE
Mangahub possible API change

### ISSUE THREAD

**Issue by buckbidoof** [keiyoushi/tachiyomi-extensions-source#787]
### Source information

Mangahub 1.4.33

### Source language

English

### Steps to reproduce

1. Attempt to read any manga within the app
2. Wait
3. Error

### Expected behavior

1. Attempt to read any manga within the app
2. Read

### Actual behavior

Nothing popped up for 30 seconds until the error message appeared.

### Tachiyomi version

Tachiyomi SY 1.10.2 (Latest)

### Android version

10

### Other details

![Screenshot_20240129-115023_TachiyomiSY](https://github.com/keiyoushi/extensions-source/assets/105699985/39495560-450d-4d8b-93fa-ea6345df5f18)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Their API has changed, yes, but currently the image CDN is broken too. Will have to look into this after everything is up again.
