### ISSUE TITLE
Mangakalot Source

### ISSUE THREAD

**Issue by Dresden0478** [keiyoushi/tachiyomi-extensions-source#79]
### Source name

Mangakalot

### Source link

https://mangakakalot.com/?u=zido.gq

### Source language

English

### Other details

Large repo

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by aboudiom59** [comment]
It changed to mangakakalot

**Comment by beer-psi** [comment]
This extension already exists under the name **Mangakakalot** under the **English** language: https://keiyoushi.github.io/extensions/extensions/#en.mangakakalot
