### ISSUE TITLE
XOXO Comics not loading

### ISSUE THREAD

**Issue by Expakun** [keiyoushi/tachiyomi-extensions-source#8]
### Source information

XOXO Comics 1.4.5

### Source language

English

### Steps to reproduce

1. Install or Update XOXO Comics
2. Search for Comic or Click on the Extensions to see Popular Comics
3. See that nothing loads

### Expected behavior

Comics load when I use search or click on the Extension

### Actual behavior

Nothing loads

### Tachiyomi version

0.15.2

### Android version

Android 13

### Other details

Webview works without an issue 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ghost** [comment]
Yup they changed the domain from .net to .com I think, was gonna try to fix it but I cant even find the extension in the source code lol

Update, found it, looks like it has been changed already?

**Comment by ZenOrion** [comment]
Does it load anything for you after updating the extension? I've updated it to 1.4.5 and I still don't see anything loading. I can see the site and everything just fine with Webview, but I can't actually search for/look at anything through the app.
