### ISSUE TITLE
Hitomi not showing after installing (and trust)

### ISSUE THREAD

**Issue by conztanz045** [keiyoushi/tachiyomi-extensions-source#803]
### Source information

all.hitomi 1.4.25

### Source language

Multi

### Steps to reproduce

Install hitomi

### Expected behavior

Show in Installed section of the extension

### Actual behavior

Nothing happen

### Tachiyomi version

1.6.2

### Android version

Android 9

### Other details

I already done some everything from ensuring there hitomi is uninstall in me to manually installing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by conztanz045** [comment]
> @conztanz045 this issue was not reopened because:
> 
> * You have not carefully read the acknowledgements.
> * Uninstall the extension before updating. If that does not work, uninstall it from your device's settings by navigating to your device's Settings -> Apps and uninstall it from there by looking for **Tachiyomi: **.
> 
> This is usually caused your previous extension having a different signature from the updated extension, making Android refuse to update it.

In done it you fuck ass bot!!!

**Comment by conztanz045** [comment]
https://github.com/keiyoushi/extensions-source/assets/79831076/a2868e23-4a89-4e7b-9b49-55c5a429bec8

![Screenshot_2024-01-29-21-13-26-38](https://github.com/keiyoushi/extensions-source/assets/79831076/275a6058-bacc-4e91-976f-7f029e6cede8)

**Comment by conztanz045** [comment]
Please reopen

**Comment by beer-psi** [comment]
I'd have reopened it if you could read the acknowledgements carefully.
