### ISSUE TITLE
Rawdevart

### ISSUE THREAD

**Issue by DchanN** [keiyoushi/tachiyomi-extensions-source#804]
### Source name

Rawdevart

### Source link

https://rawdevart.art

### Source language

Japanese - 日本語

### Other details

there are PR #607 remove rawdevart, not sure it's the same or not

![image](https://github.com/keiyoushi/extensions-source/assets/101858971/7c2e05c2-3a6c-4329-8c22-25f954ea6ec3)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
It's a different site.
