### ISSUE TITLE
[Bug] ManaToki: Rate limit not changing

### ISSUE THREAD

**Issue by jcha1600** [keiyoushi/tachiyomi-extensions-source#829]
### Source information

NewToki / ManaToki 1.4.29

### Source language

Korean

### Steps to reproduce

1. Open extension settings.
2. Change the rate limit(요청 제한) value on ManaToki section.
3. Restart the app and return to step 1.

### Expected behavior

rate limit should have been changed to the desired value.

### Actual behavior

Rate limit not changed, stayed on '1 second'.

### Tachiyomi version

8.8.0-AZ

### Android version

Android 10 (One UI 2.5)

### Other details

This issue can trigger a temporary ban, especially when you do global update.

Rate limit on NewToki works fine.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Can't reproduce. Could you provide screen recording or screenshot (before and after)?

**Comment by jcha1600** [comment]
https://github.com/keiyoushi/extensions-source/assets/58236045/f5afb2b9-2107-4227-b869-c5d8107bb759

**Comment by stevenyomi** [comment]
According to [this](https://discord.com/channels/1195734228319617024/1196409572903092325/1202275127937749002), it's probably an issue of AZ. Open issue at https://github.com/az4521/TachiyomiAZ
