### ISSUE TITLE
Manga Galaxy broken

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#830]
### Source information

Manga Galaxy 1.4.34

### Source language

English

### Steps to reproduce

Just open it

### Expected behavior

Have manga

### Actual behavior

No Manga

### Tachiyomi version

Mihon 0.16.2

### Android version

Android 12

### Other details

I'm using Mihon

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ghost** [comment]
If you guess is already on it then forgive me

**Comment by AwkwardPeak7** [comment]
now uses MangaReader theme

**Comment by Kantotero** [comment]
Its still broken any updates?

**Comment by Kenn876** [comment]
Are they ever gonna fix the extension? They marked as resolved but it's not.

**Comment by Norsze** [comment]
> Are they ever gonna fix the extension? They marked as resolved but it's not.

The source probably keeps breaking it every time it's fixed
