### ISSUE TITLE
Dm5,access protection is enabled on the website.

### ISSUE THREAD

**Issue by ZerOri** [keiyoushi/tachiyomi-extensions-source#838]
### Source information

dm5 1.4.1

### Source language

中文(Chinese)

### Steps to reproduce

Open any series it won't load and the following message appears when browsing in the webview.
If the problem can't be solved take down the plugin.

![Screenshot_2024-01-31-12-39-15-840_app mihon](https://github.com/keiyoushi/extensions-source/assets/46775615/abf00d1b-07d8-4283-8afa-89538c4ee443)

### Expected behavior

Normal loading of series.

### Actual behavior

Can't load series.

### Tachiyomi version

0.15.3

### Android version

Andriod 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by anenasa** [comment]
Looks like the behavior of the image server is dependent on location. When I created this extension, I only tested in Taiwan and everything worked for me, but in other places, you get error, and I also get error if I use vpn. I will make a pull request to fix this soon.
