### ISSUE TITLE
Xinmeitulu Broken?!

### ISSUE THREAD

**Issue by devil6venom** [keiyoushi/tachiyomi-extensions-source#841]
### Source information

Xinmeitulu 1.4.4

### Source language

English 

### Steps to reproduce

1. Go to ext
2. Select 'any' manga from row
3. It either have some error or the image cannot be loaded issues!

### Expected behavior

It should shows all images perfectly!

### Actual behavior

Image cannot be loaded!

### Tachiyomi version

Tachiyomisy 1.10.2

### Android version

Android 13

### Other details

![Screenshot_20240131-122640](https://github.com/keiyoushi/extensions-source/assets/92388530/ad20f08e-a322-4da8-9d5d-81a984f88b48)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by 0Ha16wA5** [comment]
It seems that only newest entries are unable to load.

And older entries can still show, but the images are not.

**Comment by SnakeDoc83** [comment]
Seems like a server side issue.

**Comment by 0Ha16wA5** [comment]
Tried it again with TachiyomiSY on the same exact entry.

Works flawlessly.
