### ISSUE TITLE
Batoto unable to open chapter

### ISSUE THREAD

**Issue by CactusTheGuy** [keiyoushi/tachiyomi-extensions-source#842]
### Source information

Bato.to 1.4.34

### Source language

All

### Steps to reproduce

1. Open up a random batoto comic
2. Open a comic
(Sorry for orientation)

https://github.com/keiyoushi/extensions-source/assets/75614340/a936869d-9a7f-4757-818d-04edb792cdd2

### Expected behavior

Open a chapter normally

### Actual behavior

Page not found on a chapter

### Tachiyomi version

Mihon 0.16.3

### Android version

MIUI 14 Android 13

### Other details

This is due to the batoto website side has updated on their side

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by PigStuffy** [comment]
Same issue on tachiyomiSY 1.10.2

**Comment by beer-psi** [comment]
> Bump
> Same issue on tachiyomiSY 1.10.2 

Please use the thumbs-up reaction if you have the same issue. Bumping adds nothing to the discussion.

**Comment by asdkant** [comment]
Can confirm same is happening with TachiyomiJ2K v1.7.4 + batoto v1.4.34

**Comment by PigStuffy** [comment]
> > Same issue on tachiyomiSY 1.10.2
> 
> Please use the thumbs-up reaction if you have the same issue. Bumping adds nothing to the discussion.

Thanks for advising me on the etiquette!

"Bump" text removed, post liked.

I left my tachi version in the comment still. Lmk if that's useful info, if so I will remove that too
