### ISSUE TITLE
HunterScan was accidentally removed

### ISSUE THREAD

**Issue by nomaxsnx** [keiyoushi/tachiyomi-extensions-source#856]
### Source name

HunterScan

### Source link

https://huntersscan.xyz/

### Source language

português 

### Other details

hunterscan has been deleted confirm commit: #847

but they are still publishing it.

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by SnakeDoc83** [comment]
So there website works for you? Interesting, I had had go back to October on archive.org to see a working website.

**Comment by nomaxsnx** [comment]
> So there website works for you? Interesting, I had had go back to October on archive.org to see a working website.

it works, you have to have a vpn to see it, because they're blocking it from other countries, so it won't be taken down by the DMCA.

**Comment by nomaxsnx** [comment]
> > So there website works for you? Interesting, I had had go back to October on archive.org to see a working website.
> 
> it works, you have to have a vpn to see it, because they're blocking it from other countries, so it won't be taken down by the DMCA.

try to use vpn from São Paulo or Brazilia
