### ISSUE TITLE
Toshi wa Yume

### ISSUE THREAD

**Issue by LucianoSegundo** [keiyoushi/tachiyomi-extensions-source#870]
### Source name

tosh iwa yume

### Source link

https://leitoronline.toshiwayume.com.br/

### Source language

portuguese

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by beerpiss** [comment]
Uses FoolSlide
