### ISSUE TITLE
Mihon will be requiring a repo.json file in 1 week

### ISSUE THREAD

**Issue by EnderShadow** [keiyoushi/tachiyomi-extensions-source#884]
### Describe why this should be added

The link to the channel where this is posted is here: https://discord.com/channels/1195734228319617024/1202678953429434408
Mentioned SO link: https://stackoverflow.com/a/22983861
![image](https://github.com/keiyoushi/extensions-source/assets/3260768/bc8dbcf5-11a9-463e-8403-07090df7fa27)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Closed by https://github.com/keiyoushi/extensions/commit/99b28e6b30fa062944d006b565980b328ab28fd8

**Comment by EnderShadow** [comment]
Keiyoushi bot just removed the file in the latest commit.

**Comment by Kyrela** [comment]
[From the Mihon discord server](https://discord.com/channels/1195734228319617024/1202678953429434408/1202909506271445012):

> Small change to the `repo.json` format. You can now add a optional `displayName` field which will be shown in the extension list. If not provided we will use the normal name.

```json
{
  "meta": {
    "name": "Mihon Extension Repo",
    "displayName": "Mihon",
    "website": "https://mihon.app",
    "signingKeyFingerprint": "7ce04da7773d41b489f4693a366c36bcd0a11fc39b547168553c285bd7348e23"
  }
}
```

**Comment by beer-psi** [comment]
Our name is short enough that this change to the schema is irrelevant.
