### ISSUE TITLE
ManhuaDB contains NSFW (18+) content

### ISSUE THREAD

**Issue by Qing-Novel** [keiyoushi/tachiyomi-extensions-source#897]
### Source name

ManhuaDB

### Source language

chinese

### Describe your suggested feature

This source contains NSFW (18+) content, it is recommended to add the NSFW (18+) identifier. As shown in the following manga (with link): 柔情姐姐的敏感课程（https://www.manhuadb.com/manhua/25926）
This website has a dedicated category to showcase NSFW (18+) content（https://www.manhuadb.com/manhua/list-c-26.html）

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Aggregator site with majority of titles SFW. Plus that's not a dedicated category.
