### ISSUE TITLE
MangaNoon domain change

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#898]
### Source information

MangaNoon 1.4.28

### Source language

Arabic

### Source new URL

https://manjanoon.net/

### Other details

There is a problem with the previous one, there are no chapters 
![Screenshot_٢٠٢٤٠٢٠٢-٠٥٣٧٥٦_Mihon](https://github.com/keiyoushi/extensions-source/assets/144265316/8b159d7f-9386-417a-a01a-2c43fe70aaa7)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by SnakeDoc83** [comment]
Referencing #907 the .com domain doesn't show chapters on https://manjanoon.com/manga/nn-sister-i-am-the-queen-in-this-life/ and advises to use .net, where chapters are available. If you or someone else properly PRs the needed changes, it can be accepted.
