### ISSUE TITLE
Cloud Recess io

### ISSUE THREAD

**Issue by Shahed-G** [keiyoushi/tachiyomi-extensions-source#90]
### Source name

Cloudrecess.io

### Source link

https://cloudrecess.io/manga/pizza_palace_en

### Source language

English 

### Other details

it updates new chapters regularly & includes high resolution manhwas

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Arekkusu1998** [comment]
The Cloudflare block on Cloudrecess.io is particularly strong: it isn't possible to break it even with HakuNeko or MangaDownloader. If I can give you a compromise solution that works right away, @Shahed-G, I recommend you this extension for [Chrome](https://chromewebstore.google.com/detail/image-downloader-imageye/agionbommeaifngbhincahgmoflcikhm) and/or [Firefox](https://addons.mozilla.org/it/firefox/addon/imageye_image_downloader/). Then download the images you want; you can also convert them, choose which ones to exclude, etc. Unfortunately, you'll have to rearrange pages by yourself.

**Comment by beer-psi** [comment]
An extension with the provided URL (https://cloudrecess.io/) already exists with the name of **CloudRecess**, under the **English** section: https://keiyoushi.github.io/extensions/extensions/#en.cloudrecess

**Comment by Arekkusu1998** [comment]
@beerpiss your indication is misleading: as I wrote, Cloudflare cannot be bypassed in any way on this website. Therefore, the fact that an extension exists is completely irrelevant: it doesn't work.

**Comment by FourTOne5** [comment]
@Arekkusu1998 doesn't change the fact it exists albeit unusable. So the "Source request" is satisfied

**Comment by beer-psi** [comment]
> Cloudflare cannot be bypassed in any way on this website.

Refer to the **Solving Cloudflare issues** section at https://tachiyomi.org/docs/guides/troubleshooting/#cloudflare. If it doesn't work, migrate to other sources or wait until they lower their protection.

Not opening this again, the fact that the extension cannot bypass Cloudflare is none of our issues.
