### ISSUE TITLE
Japscan extension not showing the Manga cover

### ISSUE THREAD

**Issue by akiran9** [keiyoushi/tachiyomi-extensions-source#905]
### Source information

Japscan 1.4.34

### Source language

French 

### Steps to reproduce

Go to the library and refresh 

### Expected behavior

Not showing the real manga cover

### Actual behavior

![301726961-71ced7cd-289b-4fe6-9780-23b1c8676195](https://github.com/keiyoushi/extensions-source/assets/72227362/24bab0b2-fd2d-4d8c-959d-2cb8557e1655)

### Mihon/Tachiyomi version

1.7.4

### Android version

Android 12 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
I cannot reproduce this. Have you tried refreshing library covers and/or check the actual covers in WebView? JapScan has really been pushing this AI sex chatbot thing recently, even inserting ads into manga pages (which the extension filtered out).

**Comment by KirinRaikage** [comment]
Can't we just reremove Japscan from the backlog?

**Comment by akiran9** [comment]
Yes, I've already cleared the cookies and WebView data.

**Comment by akiran9** [comment]
What's your default agent ?

**Comment by beer-psi** [comment]
> Can't we just reremove Japscan from the backlog? 

No, it still works. Scummy aggregators don't deserve to be removed.

**Comment by KirinRaikage** [comment]
That's fine, but we had so much issues in the past that it was a cat and mouse game, and they ended up winning. As long as it works, fine, but they'll end up breaking things on purpose as usual.
I'd like to avoid that kind of scenario

**Comment by beer-psi** [comment]
> That's fine, but we had so much issues in the past that it was a cat and mouse game, and they ended up winning. As long as it works, fine, but they'll end up breaking things on purpose as usual.
> I'd like to avoid that kind of scenario

Cat and mouse races are inevitable, sure, but I'd like to fight until the bitter end. JapScan has been resurrected for a while and the core functionality (i.e. reading chapters) hasn't been broken yet. The fact that they're pushing some shady 18+ service to *some* user agents (I don't get these covers with a Edge desktop UA) is a minor inconvenience in the scale of things.

**Comment by aboudiom59** [comment]
I think it's because the extension grabs the first image it finds for the thumbnail of individual mangas. And since the first image to show up in the code of individual manga pages is the ad it grabs that. Maybe making it more specific would work? I'm sorry if it's not too clear I'm not too familiar with Kotlin and web scraping.
