### ISSUE TITLE
leer capitulo is very slow

### ISSUE THREAD

**Issue by Gabriel062323** [keiyoushi/tachiyomi-extensions-source#911]
### Source name

leercapitulo

### Source language

spanish

### Describe your suggested feature

It's very slow, can't they make it faster?

### Other details

......

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
We do not host any content and are not responsible for sources being slow.
