### ISSUE TITLE
I can't update Reaper scan extension.

### ISSUE THREAD

**Issue by Raizel000** [keiyoushi/tachiyomi-extensions-source#92]
### Source information

Reaper scan 

### Source language

English 

### Steps to reproduce

First step: Go to Browse
Second step: Go to Extension
Third Step: Check for Updates, the Reaper scan appears.
Fourth step: Download and install the update.

### Expected behavior

The Reaper scan extension should have updated.

### Actual behavior

The Reaper scan update didn't update but the download option appeared instead.

### Tachiyomi version

0.15.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
uninstall old extension and install new one
