### ISSUE TITLE
All about Naruto and Boruto

### ISSUE THREAD

**Issue by xMohnad** [keiyoushi/tachiyomi-extensions-source#920]
### Source name

Oduto

### Source link

https://nb19u.blogspot.com/?m=1

### Source language

Arabic

### Other details

Does not contain (NSFW)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [x] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
I can't find any manga on this website
