### ISSUE TITLE
Can't update Kemono party entries

### ISSUE THREAD

**Issue by Gerardalbert21** [keiyoushi/tachiyomi-extensions-source#925]
### Source information

Kemono 1.4.8

### Source language

Multiple

### Steps to reproduce

1. Go to a Kemono entrie
2. Update it

### Expected behavior

It update

### Actual behavior

A error message is shown and it don't update
![IMG_20240202_145102](https://github.com/keiyoushi/extensions-source/assets/88115070/76da554c-4f13-4ad3-bbb1-478505b7fa51)

### Mihon/Tachiyomi version

SY 1.10.2 preview 542

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Gerardalbert21** [comment]
I already did it and it don't work 
It seem that if I update multiple of them it show that.


! Unexpected JSON token at offset 0: Expected start of the array '[', but had '<' instead at path: $
JSON input: <!DOCTYPE html><html lang=en><

**Comment by beer-psi** [comment]
> I already did it and it don't work 
> It seem that if I update multiple of them it show that 
> 
> 
> ! Unexpected JSON token at offset 0: Expected start of the array '[', but had '<' instead at path: $
> JSON input: <!DOCTYPE html><html lang=en><

You still haven't read the acknowledgements.

**Comment by beer-psi** [comment]
Congratulations for finally reading the acknowledgement. Sorry for this time, the bot trips on "not updated".

**Comment by Gerardalbert21** [comment]
Even after the update of the extension I still have this
![IMG_20240203_091656](https://github.com/keiyoushi/extensions-source/assets/88115070/731c5560-20ae-4316-af1f-b2e0cfa9bb29)

**Comment by stevenyomi** [comment]
https://github.com/keiyoushi/extensions-source/blob/21afb7d682b893d64255e6873af60a5f3e3e73de/multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/kemono/Kemono.kt#L166

How many posts do you set the extension to load? I'm not sure what error the server reported.

**Comment by natyoufri** [comment]
I have 36 entry and 20 of them failled with this error

**Comment by stevenyomi** [comment]
I'm asking how many posts in the extension settings do you set? Like, 50, 100, 150, ... or 1000?

**Comment by natyoufri** [comment]
500

**Comment by Gerardalbert21** [comment]
Me 300 but I can't reduce it because it show the error
