### ISSUE TITLE
HunterScan (Updated)

### ISSUE THREAD

**Issue by nomaxsnx** [keiyoushi/tachiyomi-extensions-source#927]
### Source name

HunterScan

### Source link

https://huntersscan.xyz/

### Source language

português 

### Other details

Apparently HunterScan has changed its theme, causing the extension not to work

Error: HTTP 404

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by nomaxsnx** [comment]
if an extension theme updates, what issues should I do?

**Comment by beer-psi** [comment]
> if an extension theme updates, what issues should I do?

Use the template for reporting bugs.
