### ISSUE TITLE
zinmanhwa url change

### ISSUE THREAD

**Issue by Alexis-Silvery** [keiyoushi/tachiyomi-extensions-source#946]
### Source information

Zinmanhwa 1.4.33

### Source language

English

### Source new URL

https://zinmanga.io

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by SnakeDoc83** [comment]
Zinmanga.com is still up, can you provide context on why it should be changed?

**Comment by Alexis-Silvery** [comment]
Zinmanga.com and zinmanhwa are two completely different sources, and
zinmanhwa is now zinmanhwa.io

A sábado, 3/02/2024, 19:07, Mike ***@***.***> escreveu:

**Comment by Alexis-Silvery** [comment]
Zinmanga.io*

A sábado, 3/02/2024, 19:30, Alexis Vas Tusto ***@***.***>
escreveu:

**Comment by Alexis-Silvery** [comment]
> Zinmanga.com is still up, can you provide context on why it should be changed?

Zinmanga.com and zinmanhwa are two completely different sources, zinmanhwa URL redirects to zinmanga.io
