### ISSUE TITLE
Re adding Reset Scans

### ISSUE THREAD

**Issue by Azurelightpkk** [keiyoushi/tachiyomi-extensions-source#95]
### Source name

Reset Scans 

### Source link

https://reset-scans.us/

### Source language

English

### Other details

The extension used to exist but was taken down by reset scans' request. Would it be possible to add it back? 

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by doubledge-spec** [comment]
https://github.com/Basara-Hatake/tachiyomi-unofficial-extensions/tree/repo
