### ISSUE TITLE
MnagaSpark : Dead Source

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#955]
### Source name

MangaSpark

### Source language

Arabic

### Source link

https://mangaspark.org

### Other details

[
![Screenshot_٢٠٢٤٠٢٠٣-٠٩٢٧٢٦_Mihon](https://github.com/keiyoushi/extensions-source/assets/144265316/d837f1ff-daf1-4ee1-9992-8eb4d37ccf4e)
](url)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
It's not down, you somehow got an extra slash "/" prepended to the URL.
