### ISSUE TITLE
manhuaren No value for response

### ISSUE THREAD

**Issue by smarttommyau** [keiyoushi/tachiyomi-extensions-source#97]
### Source information

Manhuaren 1.4.14

### Source language

中文

### Steps to reproduce

Just in all situation returns No value for response and load nothing

### Expected behavior

to load stuff

### Actual behavior

returning No value for response

### Tachiyomi version

0.15.2

### Android version

Harmony os 3(AOSP Android 11)

### Other details

Will this be fix? Or this extension will be removed?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by aawwsslll** [comment]
一样不行，好像签名不行了

**Comment by yzhaolabs** [comment]
Same.

**Comment by a0193143** [comment]
Temporary solution
Open official Manhuaren app first, let it send something to server so the extension could work.

**Comment by smarttommyau** [comment]
> Temporary solution
> Open official Manhuaren app first, let it send something to server so the extension could work.

I try to install and open the app, but still no value.

**Comment by ZerOri** [comment]
Same issue.

**Comment by stevenyomi** [comment]
cc @felixfon
