### ISSUE TITLE
Manga Link : Source request

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#977]
### Source name

MangaLink

### Source link

https://manga-link.org/
OR
https://manga-link.net

### Source language

Arabic

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by devil6venom** [comment]
Maybe uses madara theme!

**Comment by devil6venom** [comment]
There is already one ext with.net in arabic language section! Check that before requesting!! 

Someone close this issue!!
![Screenshot_20240207-095356](https://github.com/keiyoushi/extensions-source/assets/92388530/85d1b4fd-f5a4-4bfa-96ad-ec48a74aeb6e)
