### ISSUE TITLE
Hachiraw

### ISSUE THREAD

**Issue by DchanN** [keiyoushi/tachiyomi-extensions-source#979]
### Source name

Hachiraw

### Source link

https://hachiraw.net/

### Source language

Japanese - 日本語

### Other details

18+/NSFW = Yes
![image](https://github.com/keiyoushi/extensions-source/assets/101858971/4a64ec41-6074-4105-a8ef-717c7a66a250)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Uses nepnep theme like Mangasee and Mangalife
