### ISSUE TITLE
Allhentai 

### ISSUE THREAD

**Issue by Gostik21** [keiyoushi/tachiyomi-extensions-source#988]
### Source information

1.4.44

### Source language

Russian

### Steps to reproduce

After updating the manga, the chapter status "downloaded" disappears and you have to download the chapter again. And after repeated manga update the downloaded chapter disappears from tachimi again.
But in the phone system, the downloaded chapters remain

### Expected behavior

After updating the manga, the downloaded chapters remain in the app

### Actual behavior

Downloaded chapters disappear

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by beer-psi** [comment]
Try Settings -> Advanced -> Invalidate download index. If that doesn't work, you're out of luck. We don't support the app, only the extensions.

**Comment by Gostik21** [comment]
Didn't help( Strange that it only appeared in one extension
