### ISSUE TITLE
Komga: Change default sorting method

### ISSUE THREAD

**Issue by kanjieater** [keiyoushi/tachiyomi-extensions-source#991]
### Source information

Komga 1.4.52

### Source language

Japanese

### Steps to reproduce

1. Have a manga with a Japanese title, ex: `罠ガール`
![image](https://github.com/keiyoushi/extensions-source/assets/32607317/bcf272f3-816b-4954-a933-496bf3a4cbbd)

2.  Search it w/ Komga's extension 
![image](https://github.com/keiyoushi/extensions-source/assets/32607317/c27a592c-0798-4da3-a3ed-d80d74b6bd12)

3.  It fails to get the right titles. Alt titles in Komga _do_ get searched properly in _Japanese_ or english 
![image](https://github.com/keiyoushi/extensions-source/assets/32607317/44d83a89-66ac-4257-a591-6138be78469f)

### Expected behavior

Searching an exact match Title should match the exact march Title regardless of language.

### Actual behavior

Searching an exact match title only works if it's in the alternative title (at least for the cases I've tried in Japanese). Ideally, the search results should match what they would if you search Komga directly.

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kanjieater** [comment]
Seems like Komga is giving back the result but this might be a core Mihon issue as Mihon is sorting by unicode (so english chars, kana, then kanji) so in this case, the exact search result get's buried since there are other books in the library with english & kana names first.

A work around is to search with quotes, so komga only returns one thing that exact matches.

**Comment by beer-psi** [comment]
I don't think the app tampers with search results at all? The source gives it too the app, which displays the results as-is.

If anything was to change the ordering it'd be the extension.

**Comment by kanjieater** [comment]
So the komga extension would have to change it's default sorting method?

Update: Yeah i'm guessing this line is the culprit: https://github.com/keiyoushi/extensions-source/blob/0478cb29370c4c563106efd4e88d0b7bc6c820dd/src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt#L409C1-L410C1

**Comment by beer-psi** [comment]
Yes, that'd be the case. You can open the Filter card and check the Sort filter at the bottom, the default is alphabetical ascending.

**Comment by kanjieater** [comment]
Right. So what would be the appropriate fix for this?  Don't sort results that come back from komga at all, like a "source sort"?

**Comment by beer-psi** [comment]
Not sure what's the default sort setting for Komga's web UI, but I suppose we can follow that.
