### ISSUE TITLE
Galax scans

### ISSUE THREAD

**Issue by Wmestree** [keiyoushi/tachiyomi-extensions-source#994]
### Source name

Galax Scans

### Source link

https://galaxscans.blogspot.com/

### Source language

Brazilian Portuguese

### Other details

18+ = yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by devil6venom** [comment]
Maybe uses zeistmanga theme

**Comment by Mocchichoi** [comment]
você se incomodaria em me passar a sua adaptação? eu consegui fazer uma boa parte da codificação que peguei, mas ainda assim, não consegui mexer em muita coisa por ser nova nessa área...

**Comment by choppeh** [comment]
Source isn't available.
