### ISSUE TITLE
A Pair of 2+ complete dead after WSJ incident

### ISSUE THREAD

**Issue by CactusTheGuy** [keiyoushi/tachiyomi-extensions-source#999]
### Source name

A Pair of 2+

### Source language

English

### Source link

https://po2scans.com/

### Other details

Scanlator website deleted after the Weekly Shonen Jump incident

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Website is not dead and extension is still usable on my side.
